### ISSUE TITLE
Navigation issue when Back button pressed

### ISSUE THREAD

**Issue by ashokkumar88** [framework7io/framework7#1000]
Hi,

First of all, thank you to the Framework7 team for creating such a awesome mobile app framework.

I am switching my android app to Framework7 using Template7. I am facing issues with the Navigation. When I am navigating deep (2 or more) and again going back to page, the page is refreshing and the compiled templates not displaying. For example 

**News page->Detail page->Back to News page (working fine)**

But---

**News page->Detail Pages->More Detail Page->Back to Detail Page->Back to News Page (Not displaying the template rendering)**

Please help..

**Comment by ashokkumar88** [comment]
I got it worked by adding domCache:true

**Comment by ZanderBrown** [comment]
Congratulations on being the 1000th issue.

Would i be right in thinking this issue can be closed?
