### ISSUE TITLE
no-tabbar does not work on Safari for the messages page

### ISSUE THREAD

**Issue by seme1** [framework7io/framework7#1018]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: IOS , Safari
### What you did

Here is my setup:
dynamic navbar
auto hide navbar/tabbar on scroll for all pages except one with messages.
in the messages page, I have the following:

```
<div class="navbar">
<div class="navbar-inner">
    <div class="left sliding"><a href="index.html" class="back link"><i class="back-ionIcon ion-arrow-right-c"></i></a></div>
    <div id='msgPageTitle' class="center sliding">Messaging page</div>
</div>
</div>
<div class="pages navbar-through">
<div data-page="messagesChat" class="page navbar-through no-tabbar no-toolbar toolbar-fixed">
  <!-- Messages content -->
  <div class="toolbar messagebar">
    <form id='msgsFormId' class="toolbar-inner ">
      <input type="text" placeholder="write your msg.." class="ks-messages-input">
      <a href="#" class="link ks-send-message">send</a>
    </form>
  </div>

  <div class="page-content messages-content keep-bars-on-scroll keep-tabbar-on-scroll">
                    <div class="load-result"></div>
    <div id="AllMsgs" class="messages">
    </div>
  </div>
  <!-- Custom toolbar -->
</div> 
</div>
```

The above page works fine on Google Chrome. However, on safari the tabbar is hidden upon viewing the page for the first time. Once the page is scrolled down then up, the tabbar appears. I tried removing and adding `keep-tabbar-on-scroll` without any luck. 
Any idea how to make the tabbar invincible on Safari ?
### Expected Behavior

tabbar should be hidden on the messages page on both Chrome and Safari.
### Actual Behavior

tabbar is hidden only on Google Chrome.

**Comment by jvence** [comment]
+1

**Comment by eradin** [comment]
I have a similar problem.  I have a tabbar that has a messages tab.  When you click on the tab, the message bar appears at the bottom.  This works fine on MD (tabbar is at top) but on IOS, the tabbar is on the bottom and overlays the tabbar so you can no longer move to another tab.  I thought it was a quirk with the messagebar replacing the tabbar on that tab but that isn't the case with MD.  I don't know what the solution is other than to move the messagebar up on top of the tabbar for IOS.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
