### ISSUE TITLE
Meterial subnav bar invisible

### ISSUE THREAD

**Issue by bingzheyuan** [framework7io/framework7#1047]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2.
- Platform and Target: chrome v52 firefox v42.
### What you did

``` html
<div class="navbar">
      <div class="navbar-inner">
             <div class="left">
                   <a href="/" class="link icon-only back">
                        <i class="icon-arrow-left"></i>
                     </a>
             </div>
            <div class="center">Center</div>
            <div class="subnavbar">
                <form class="searchbar " action="/Search" >
                    <div class="searchbar-input">
                                <input type="search" placeholder="keyword" >
                      </div>
                  </form>
            </div>
      </div>
</div>   
<div class="page-content with-subnavbar hide-navbar-on-scroll">
<!-- other code -->
</div>
```
### Expected Behavior

sub nav bar shows up
### Actual Behavior

sub navbar is hidden

**Comment by bingzheyuan** [comment]
I found this template only works in iOS theme, in meterial the `.subnav` should be ouside `.navbar-inner`. However I counldn't figure out why it is invisible for this template.

**Comment by valnub** [comment]
See https://muut.com/framework7#!/framework7/questions:subnav-bar-material-design

**Comment by applecat** [comment]
I have the same issue too — when I use Sub Navbar in Material — suddenly it's hidden.

![](http://apple-cat.ru/github/f7-subnavbar.png)

Here is my code:
```
<div class="view view-main navbar-fixed" data-page="index">
  <div class="pages">
      <div data-page="index" class="page with-subnavbar">
        <div class="navbar">
          <div class="navbar-inner">
            <div class="left">
              <a href="#" data-panel="left" class="link icon-only open-panel "><i class="icon icon-bars"></i></a>
            </div>
            <div class="center sliding">Home Page</div>

            <div class="subnavbar">
              <div class="buttons-row">
                <a href="#tab1" class="button tab-link active">Tab 1</a>
                <a href="#tab2" class="button tab-link">Tab 2</a>
                <a href="#tab3" class="button tab-link">Tab 3</a>
              </div>
            </div>
          </div>
        </div>
        <div class="page-content">
          <p><a href="#">Open Left Panel</a></p>
          <p>Page content goes here</p>
          <a href="about.html">About app</a>
        </div>
      </div>
  </div>
</div>
```
In iOS theme everything is ok. What am I doing wrong?
In app init material: true set:
```
this.app = new Framework7({
    init: false,
    material: true,
    swipePanel: 'left'
  });
```

**Comment by jamesdixon** [comment]
I'm running into this as well and I'm also using the fixed layout. As @bingzheyuan mentioned, for the material theme, it works properly if you move the element outside of `navbar-inner`.

@valnub I believe this is in fact a bug and shouldn't be closed.

**Comment by ZanderBrown** [comment]
Are you using the markup as [shown here](http://framework7.io/kitchen-sink-material/bars-sub-navbar.html)

```html
<div data-page="sub-navbar" class="page">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="left">
                <a href="index.html" class="back link icon-only">
                    <i class="icon icon-back"></i>
                </a>
            </div>
            <div class="center">Sub Navbar</div>
                <div class="right">
                    <a href="#" class="open-panel link icon-only">
                        <i class="icon icon-bars"></i>
                    </a>
                </div>
            </div>
            <div class="subnavbar">
                <div class="buttons-row">
                    <a href="#" class="button active">Link 1</a>
                    <a href="#" class="button">Link 2</a>
                </div>
            </div>
        </div>
        <div class="page-content with-subnavbar hide-bars-on-scroll">
            <div class="content-block">
                ....
```

I think the most important thing to note here is the `with-subnavbar` class on `.page-content` something @applecat 's code lacks

**Comment by jamesdixon** [comment]
@ZanderBrown I'm actually using the example from this page: https://framework7.io/docs/sub-navbar.html

I believe one of the issues here is that there are a lot of inconsistencies in the documentation. For example, with the example you provided `with-subnavbar` is attached to the element with `page-content` applied, whereas the example in the documentation shows `with-subnavbar` being attached to the element with the `page` class. 

I've actually seen a number of inconsistencies across the documentation in general that could be the source of a lot of "bugs."

**Comment by thiagoabreu** [comment]
I think I found the "bug". The "navbar-inner" class contains a "overflow: hidden;" rule. [toolbars.less line 26](https://github.com/nolimits4web/Framework7/blob/379426fbcb582ecb0ac67a1869aa49151ab3a696/src/less/material/toolbars.less#L26)

After I put "overflow: visible" in my code it worked.

Is this the right behavior?

**Comment by cyberbeat** [comment]
I also suffer from this, and created a codepen example (following documentation https://framework7.io/docs/sub-navbar.html):

https://codepen.io/anon/pen/jGvBRd

And is indeed a result of the "navbar-inner" class containing a "overflow: hidden;" rule.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
