### ISSUE TITLE
Search Bar Button Press Feedback

### ISSUE THREAD

**Issue by Mojo90** [framework7io/framework7#1083]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: Cordova, iOS, android
### What you did

Wanted to have a Feedback from Search Bar Button Press.
### Expected Behavior

A callback to search bar object e.g. "searchButtonPressed".
### Actual Behavior

Is there a cleaner and less hack way than this to get the Feedback of the Search Button while using the search bar? (I have not found any infos about this in the docs). Also onDisable to let the searched text stay in there is more hacky. Any hints what I could improve or better use methods from framework7!?

```
var searchstring = "";

var mySearchbar = hyphy.searchbar('#searchbar-releases', {
    customSearch: true,
    onDisable: function(s) {
        if(searchstring.length > 0){
          $('#searchbar-releases input').attr("placeholder","");
          $('#searchbar-releases input').val(searchstring);
        }
        else{
          $('#searchbar-releases input').attr("placeholder",LocalStrings.searchReleases);
        }
    },
    onSearch: function(s) {
        searchstring = s.query;
    }
});

$('#searchbar-releases').bind("keypress", function(e) {
    if (e.which === 13) {
        if (searchstring.length > 0) {
            mySearchbar.disable();
            postLoader.loadProducts(searchstring.toLowerCase());
        }
    }
});
```

**Comment by ZanderBrown** [comment]
not sure what you mean by search button but thanks for sharing the onDisable code that fixes a problem I've been having

**Comment by Mojo90** [comment]
Haha no problem :)
Search button e.g. in iOS on the button right of this image:
![img_2163](https://cloud.githubusercontent.com/assets/2122156/17293808/d6671e76-57f2-11e6-9cda-9981448dd967.PNG)
It behaves in Apps (definitely on iOS) as a return button. Thus the keypress is "13". But as I said I think my solution is hacky and I would like to see sth. Integrated in Framework7, but I know it is not that easy especially on iOS I think

**Comment by ZanderBrown** [comment]
ah, the 'Done' button now I understand 😄. Yes it is a bit odd that the enter button doesn't close the search field it would be the expected functionality

**Comment by Mojo90** [comment]
Yes but for search it is not called done button, is it? Nevertheless the title of the button is search :D.
In my opinion my solution provided is not the best one thus this feature enhancement if it is possible to integrate in framework7...

**Comment by snsxn** [comment]
Nice hack @Mojo90!
The search button action event must be included in framework7!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
