### ISSUE TITLE
One Page scroll effect

### ISSUE THREAD

**Issue by iamafake** [framework7io/framework7#109]
Hello,
thx for your useful framework. But I have a problem:
When I have only one page the user can overscroll (grey bg).
I used a jquery code to prevent. It works great but I miss this bounce effect on a single page. How can I activate this? thx and sry for my bad english 😁

**Comment by scriptPilot** [comment]
This works well with current Framework7 version to eliminate the bounce effect:
- 1. Download https://github.com/lazd/iNoBounce/blob/master/inobounce.min.js
- 2. Include script `<script type="text/javascript" src="js/inobounce.min.js"></script>`
- 3. Add css to .views container
```
.views {
  height: 100%;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
}
```
