### ISSUE TITLE
is there a way to remove page to back button

### ISSUE THREAD

**Issue by toinkiie** [framework7io/framework7#116]
here is the scenario.
1. i have a search_engine.html, the user will search and click the result to see the details in details.html.
1. in details.html there is a button that will request the login credential, then user will be redirected to login.html.
2. the user will login and i need to bring the user back to details.html with backbutton, which the back button is intended to back into search_engine.html.

the question is , is there a way to remove login.html to the backbutton target, and the target should be in search_engine.html and the search result will retain.

i tried to remove the login.html page in mainView.history but still no luck.

**Comment by ionas** [comment]
@nolimits4web I have done as explained in:
https://github.com/nolimits4web/Framework7/issues/116#issuecomment-48782948
```javascript
myApp.onPageInit('users-index', function (page) {
  for (var i = 0; i < page.view.history.length; i++) {
    if (page.view.history[i] === '/users/add' || page.view.history[i] === 'users/add') {
      console.log(page.view.history);
      page.view.history.splice(i, 1);
      console.log(page.view.history);
      // The history item is gone!
    }
  }
});
```
However... clicking on back will still load the form again (prefilled with whatever was there)

**Comment by ionas** [comment]
`<a href="#" class="back link" data-force="true">` instead of just `<a href="#" class="back link">` made it work, however I don't understand why?!

**Comment by ionas** [comment]
However... force will remove all history. I just want to remove one item (the form) from the navigation history. How?

**Comment by ionas** [comment]
This seems to solve it for me (after myApp = new Framework7)
```javascript
myApp.params.cache = true;
myApp.params.cacheIgnore = ['/users/index', '/users/add', 'users/index', 'users/add'];
```
It was also possible to juse set cache = false.
However setting those params within myApp = new Framework7() call did not work.
