### ISSUE TITLE
Не работает скролл на Android 5.1.1

### ISSUE THREAD

**Issue by phwb** [framework7io/framework7#1184]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: Android 5.1.1 API Level 22
### Коротко:

при определенных условиях не работает скролл на странице cards.html из демо kitchen-sink-material (точнее при использовании компонента cards)
### Детально:

как я изначально поймал это баг описывать не буду, расскажу как его отловить. Баг срабатывает только на Android 5.1.1 (API level 22) проверял на версиях ниже и выше все работает отлично.

Из демо примера (kitchen-sink-material) на главной странице оставляем только два пункта "Cards" и "Virtual List" (пункт остается только для демонстрации бага), чтобы высота контентной области не превышала высоту экрана (это важно).

Редактируем страницу cards.html, оставляем там только картинки из локального каталога, большие картинки я заменил на img/beach.jpg иконки аватаров на img/icon.png, если этого не сделать то после загрузки картинок из вне, они меняют высоту контента и скролл появляется. В принципе для простоты картинки можно убрать.

На индексной странице подключаем скрипт cordova.js и инициализацию приложения вешаем на событие deviceready, в общем стандартное поведение приложений для кордовы.
Создаем эмулятор Android 5.1.1 - API Level 22 у меня получились следующие настройки 

![Настройки эмулятора](https://2.downloader.disk.yandex.ru/disk/9844ea44411418f1dcbf53048da83c42d7fa782d97c323b564cd3961a473d588/58127d4b/ERS2_hqilcc8yU0oNPSbEKj3uXWmLjnZot_cZEYOvv9hRKV_dpB0SKIbjj19qFs_n4vkSZoqPbxaGIUMF6OxsQ%3D%3D?uid=0&filename=2016-10-27_16-41-58.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=17027&hid=0261cf2e89add55b6a5756007f5268b7&media_type=image&tknv=v2&etag=ab1df518fc79f93d9c0da9caa1158dc2)
[картинка на Яндекс.Диск](https://yadi.sk/i/zXS5FJz7xgqpc)

Заливаем туда приложение, после запуска приложения кликаем по пункту "Cards" и пытаемся скролить страницу в низ, скролл не работает. Возвращаемся на главную и переходим по пункту "Virtual List", скролл работает. 

Выяснить почему так происходит у меня так и не получилось, но исправить положение помогло следующее решение:

``` javascript
$(document).on('pageAfterAnimation', e => {
    let container = e.detail.page.container
    container.style.overflow = 'auto'
});
```

$ - Dom7, то есть после окончания анимации страницы обновляем свойство overflow и скролл начинает работать. Буду рад за любые разъяснения, так как сам я бился над этой проблемой два дня, и ничего лучше обновления стилей не придумал.

Полагаю, что проблема не в самом фреймворке, а какой то особенности работы вебвьюшки

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
