### ISSUE TITLE
add extra param ajax error 

### ISSUE THREAD

**Issue by imic07** [framework7io/framework7#1209]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: CHROME
* Live Link or JSFiddle/Codepen: 
### What you did
there has a problem, when i use xhr.open method, post method couldn`t pass any data to the backgroud,   request.getParameter('xxx') always null.   only GET method can get data according request.getParameter('xxx'); ps. the header couldn`t containt 'X-Requested-With' or the header 'accept'
correct: ![image](https://cloud.githubusercontent.com/assets/16321067/20332172/0cdf20e8-abe5-11e6-87e2-dc5dacf14ba2.png)

///////////
error: ![image](https://cloud.githubusercontent.com/assets/16321067/20332118/bfe3e0e4-abe4-11e6-83dc-95c22fb0d9da.png)
so i couldnt according header to judgement is this  is a ajax request.
```
if (!(request.getHeader("accept").indexOf("application/json") > -1
					|| (request.getHeader("X-Requested-With") != null 
						&& request.getHeader("X-Requested-With").indexOf("XMLHttpRequest") > -1))) {
   // not a ajax request
}else{
    //ajax request 
}
```

```
$$(document).on('ajaxStart', function(e){
	var xhr = e.detail.xhr;
    var url = xhr.requestUrl;
    var newUrl = url + (xhr.requestUrl.indexOf('?')>=0 ? '&' : '?') + '_v=1000';
    xhr.open(xhr.requestParameters.method, newUrl, true, xhr.requestParameters.user, xhr.requestParameters.password);
xhr.setRequestHeader("X-Token", new Date().getTime());
});

```

my code is :
```
$$.ajax({
	 method: "POST",
	 url: "http://***/web/msgboard/wx/insert.json",
	 data:{content:'some data'},
	 dataType: "json",
	 success: function(json){
		 console.log(JSON.stringify(json))
	 }
 });

@ResponseBody
@RequestMapping(value = "/wx/insert.json", method = {RequestMethod.GET, RequestMethod.POST})
public Response insertOfWx(HttpServletRequest request) {
	// when POST the content is null. only GET method can get content data.
	String content = request.getParameter("content");
	....
}
```

### Expected Behavior
parame already added to url, POST/GET method can get content data, and i can judge is this is a ajax request

### Actual Behavior
parame already added to url,  but  when ajax method is POST the content is null. only GET method can get content data in background.

in jquery, i init like this work well, hope framework7 support it like jquery
![image](https://cloud.githubusercontent.com/assets/16321067/20345010/345c0e1a-ac30-11e6-92e7-dc5cc010349d.png)

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
