### ISSUE TITLE
list item onclick doesn't work

### ISSUE THREAD

**Issue by iamafake** [framework7io/framework7#122]
``` html
<li>
 <a href="#" class="item-link" id="list-1">
  <div class="item-content">
   <div class="item-media"><i class="icon icon-f7"></i></div>
   <div class="item-inner">
    <div class="item-title">Hello World</div>
    <div class="item-after">click</div>
   </div>
  </div>
 </a>
</li>
```

This is my listitem with link. I typed this code:

``` javascript
$$('#list-1').on('click', function(){
 myApp.alert('Hello, World!');
});
```

But, it doesn't work, I tested $$('.item-link').on('click')... : NO
Tested onclick="alert('Hello World');" : NO

Please help me!

**Comment by kyabas** [comment]
it still doesnt work on manually loaded alternative view.

for example

`// Add view
var mainView = myApp.addView('.view-main', {
    // Because we use fixed-through navbar we can enable dynamic navbar
    dynamicNavbar: true
});

var appView = myApp.addView('.view-login');`

the click function on view-login doesnt work.

**Comment by kyabas** [comment]
please check that you have included my-app.js
It is not included in the kitchen-sink
I did the same mistake
