### ISSUE TITLE
Popup grey background

### ISSUE THREAD

**Issue by iamafake** [framework7io/framework7#123]
Hey,
my Popup myApp.popup(HTMLCode, true) has a one Page Content and when the user scrolls, the popup navbar goes with. How to fix?

Thank you!

**Comment by onur-sahin-de** [comment]
Just add “popup-overlay” before your popups in HTML.
Solution would be look like this:

				<div class="popup-overlay"></div>
				<div class="popup" class="popup-about">
					<div class="content-block">
						<p>About</p>
						<p><a href="#" class="close-popup">Close popup</a></p>
						<p>Lorem ipsum dolor ...</p>
					</div>
				</div>
