### ISSUE TITLE
label-checkbox doesn't work with Web Pages Razor

### ISSUE THREAD

**Issue by DetectiveW** [framework7io/framework7#1244]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: Chrome V.55 , Visual Studio 2012, ASP.NET 4.0

### What you did
```
<li>
<label class="label-checkbox item-content">
                            @Html.CheckBoxFor(m => m.Test) 
                            <div class="item-media">
                                <i class="icon icon-form-checkbox"></i>
                            </div>
                            <div class="item-inner">
                                <div class="item-title">@Html.DisplayNameFor(m => m.Test)</div>
                            </div>
                        </label>
</li>
```
### Expected Behavior
Click on tick can set to true or false.

### Actual Behavior
Click on tick doesn't work.

**Comment by ZanderBrown** [comment]
I'm not sure this is directly related to F7. @DetectiveW could you please elaborate?

**Comment by DetectiveW** [comment]
Razor engine generate this code:
<li>
	<label class="label-checkbox item-content">
		<input data-val="true" data-val-required="Field required" id="Test" name="Test" type="checkbox" value="true">
		<input name="Test" type="hidden" value="false"> 
		<div class="item-media">
			<i class="icon icon-form-checkbox"></i>
		</div>
		<div class="item-inner">
			<div class="item-title">Test</div>
		</div>
    </label>
</li>

And this code doesn't work with label-checkbox, I tried to click on checkbox image but nothing happens.

@Html.CheckBoxFor is the standard in ASP.NET MVC so I think F7 label-checkbox should work with the code above.

**Comment by ZanderBrown** [comment]
F7 isn't designed to work with any particular server side environment, can you not define a custom method or add the control by hand?

**Comment by DetectiveW** [comment]
Other F7 form elements except label-checkbox and label-switch works perfectly with Razor engine.

I tried to make a custom HTML to label-checkbox to work with F7 but server side ASP.NET gets complicated...

**Comment by ZanderBrown** [comment]
If you're having problems using ASP.NET to generate your F7 site why use it? Why not use static files or PHP?

**Comment by DetectiveW** [comment]
I have no problems with ASP.NET, only it makes so complicated to create custom HTML to label-checkbox working and get/set the value on this custom HTML.

I use other popular frameworks with ASP.NET MVC for other projects with no problems, but for the last project, the client wants an iOS look and feel so I choose F7.

F7 works perfectly with ASP.NET MVC only label-checkbox and label-switch doesn't work.

I think you should reconsider change this issue to make F7 fully compliant with standard ASP.NET MVC.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
