### ISSUE TITLE
Disabling caching does not work

### ISSUE THREAD

**Issue by ammmir** [framework7io/framework7#1254]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2

```
// Initialize your app
var myApp = new Framework7({
    cache: false,
    ...
})
```

After loading a page with `mainView.loadPage()` the loaded page's content is still cached even though the cache is disabled as above.

Files being served with `python -m SimpleHTTPServer`

Expectation: Cache should be disabled completely.

**Comment by ZanderBrown** [comment]
Sorry i'm not quite understanding, do you mean the previous page is still in DOM?

**Comment by AysadKozanoglu** [comment]
The simplest way is to define a variable _timestamp_ and set it with _Date.now()_ and give it to route path parameter with _?timestamp_ on every route path ending. 

So in this case framework7 must load every html file on every browser reload again.

after your development and design is finished you can comment it out. This scenario you can use for every framework you use. it is not framework7 specific. 

for examle:
<pre>
var timestamp   = Date.now();

routes = [
  {
    path: '/',
    url: './index.html?'+timestamp,
  },
  {
    path: '/about/',
    url: './pages/about.html?'+timestamp,
  },
  {
    path: '/form/',
    url: './pages/form.html?'+timestamp,
  },
  {
    path: '/page-loader-template7/:user/:userId/:posts/:postId/?'+timestamp,
    templateUrl: './pages/page-loader-template7.html?'+timestamp,
  },
  {
    path: '/page-loader-component/:user/:userId/:posts/:postId/?'+timestamp,
    componentUrl: './pages/page-loader-component.html?'+timestamp
  }]
</pre>

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
