### ISSUE TITLE
Autocomplete not completing with mouse click on touchscreen on Chrome

### ISSUE THREAD

**Issue by rlundquist3** [framework7io/framework7#1300]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.5.2
* Platform and Target: Issue present on Chrome on touchscreen PCs

### What you did
When using an autocomplete on a touchscreen PC, clicking on the desired item does not complete the field, rather it leaves only what was typed in the input. The feature functions as expected when the item is selected on the touchscreen however.

The issue is not present on devices without touchscreens, and is not present on Firefox either way. Not tested on Safari or other browsers.

### Expected Behavior
Using the example [here](https://framework7.io/docs/autocomplete.html):
if the user types “ban”, the option “Banana” is in the dropdown. If the user clicks "Banana" with the mouse or touches it on the touchscreen, the field should complete with "Banana". 

### Actual Behavior
If the user clicks “Banana” with the cursor, the field seems to complete with “ban”, and the dropdown disappears. If the user touches “Banana” on the touchscreen, it is completed as desired.

**Comment by valnub** [comment]
Hi, works for me using Chrome on iOS. Are you on Android?

**Comment by ZanderBrown** [comment]
Works for me (Chrome on Win10 32Bit)

**Comment by rlundquist3** [comment]
@vanlub @ZanderBrown
This was on Linux, but my team members reported it on Windows as well. Again, only on machines with touchscreens when using the mouse.

**Comment by ZanderBrown** [comment]
Ah so clicking not tapping. Okay you had me confused their.

Okay so clicking doesnt work.

**Comment by valnub** [comment]
Mouseclicks not working on a touchscreen. Weirdest thing I've ever head of :D

**Comment by sfry77** [comment]
I have the same issue, but not with a touchscreen. Windows 10 desktop.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by Teja1234-2019** [comment]
I am also facing the same issue now.  Can you please clearly mention in which version it is fixed.
