### ISSUE TITLE
Homescreen web apps broken in iOS 8

### ISSUE THREAD

**Issue by JJJ** [framework7io/framework7#131]
Incase anyone else runs into this, it's not a Framework7 issue. Cross posting here to save y'all some time: https://devforums.apple.com/thread/237804

**Comment by fernap3** [comment]
Hey guys, I'm still seeing this on iPod touch (iOS 8.2).  I launch the Kitchen Sink (http://www.idangero.us/framework7/kitchen-sink) from the home screen in an iframe and many actions don't work properly.  As an example, try going to the "Side Panels" demo, then open the left panel.  The panel won't close by touching the space to the right.  Also, links doing show an "active" color after touching them.  In my app, the left panel can't be opened or closed by swiping either.  Some people in the thread that johnjamesjacoby posted say the issue has been resolved, but I'm not sure if they're using an iframe or not.

Anyone able to reproduce?

**Comment by nolimits4web** [comment]
It is absolutely fine for me in iOS 7-8 if i pin KS to homescreen. If you pin it using iframe, then probably could be issues, but they are not F7-related
