### ISSUE TITLE
UIWebview freeze

### ISSUE THREAD

**Issue by tatxini** [framework7io/framework7#1361]
I don't know if this bug is related to Framework7, but I consider you shoud know about it.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3.
* Platform and Target: Cordova iOS (UIWebView), iOS Theme.

### What you did
When I change too fast between pages (ajax pages), sometimes (it is totally random for what I see) the entire WebView it becomes frozen.

While I was debugging, I found the UIWebview throw an Exception.

I post the link about that and includes a potencial fix, but I'm not sure if the issue is completely solved.
[The link](http://stackoverflow.com/questions/25894173/uiwebview-throwing-exception-for-webactiondisablingcalayerdelegate-setbeingremo)

The changes I did, which I found from the link I posted, are:

In the style of body, I added this line: **-webkit-transform:translateZ(0px);**

I hope this can be helpful for somebody.

Thanks for your attention and for this great framework.

Regards

**Comment by valnub** [comment]
Hi, can you tell us more about your dev environment? Did you create a web app or native app (Cordova/PhoneGap)?

Also, live code demo via Codepen would help to reproduce the issue: https://codepen.io/hello/

**Comment by ciossi** [comment]
Hi,

I had the same problem. Native app with Cordova, F7 ver. 1.5.3 with material theme. Uiwebview often was frozen in a view with picker. I tried the solution -webkit-transform:translateZ(0px); . It seems to work.

Thanks,

Cristian

**Comment by tatxini** [comment]
I create a Cordova app with iOS theme. 
I would like to upload a recording showing the bug, but I still cannot reproduce it exactly because it's a random bug and it's happening in a different pages. I'll keep trying to record it and if i succed I'll post here.

The facts I recognized when I was debugging are:
 - If the UIWebview is"freeze" and I change the orientation on device then it work again
 - Even the UIWebview is"freeze", the javascript still working, this is because I throw an alert and it appears, and if i trigger the clicks from javascript still working.

Thanks for your attention

**Comment by valnub** [comment]
Hi, based on this information it is very hard to find out what's going on. I recommend to create a codepen example and try to make the bug **_reproducible_** so it can be debugged.

**Comment by ZanderBrown** [comment]
I'm thinking maybe this is a Cordova rather than F7?

**Comment by macdonst** [comment]
Yeah, if we can get a reproduction scenario and it is a Cordova problem we can get it fixed.

**Comment by valnub** [comment]
If it is a Cordova app, then he can upload it to Github or somewhere else and we can have a look into it.

**Comment by damienc89** [comment]
I was unable to resolve the problem by any of the above.

**Issue**
- Random, unpredictable freezing of the UI.  No error log, no console output - zip
- Stack: Framework7, Cordova , Material stylesheets
- Porting across from Android to iOS.

**Solution:**
- Changed all .material.framework7 CSS stylesheets to .ios.framework7.

 I pretty much never post but I do hope this helps somebody else.

Good luck!

**Comment by valnub** [comment]
That's extremely odd. Why would a UI freeze just by replacing the css file?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
