### ISSUE TITLE
DatePicker Issue

### ISSUE THREAD

**Issue by jwdsoft** [framework7io/framework7#1392]
This is a
* [x] bug

* Framework7 Version: Framework7 1.5.2
* Platform and Target: browser and Android

First of All I like to thank you for this great framework.
I finished my app quickely using it.
I checked on the net to find a simillar issue but didn't seem to find any
here is the two issue I came across.

I'm using regular Calendar initialisation
var DateOuverture = myApp.calendar({
  input: "#DateOuverture",
});
the first issue happen only on chrome but in mozilla it is working fine.when the calendar pop up in chrome the dates are not clickable (they are not disabled) to select a date you have to double click the date but in mozilla it is working smoothly

THE SECOND ISSUE : I think the attached pics will explain this issue more.but if you enter a page for the first time and you click the date field it work perfectly on any page for the first time.but when you move to another page and you comeback to any visited page the datePicker doesn't show up any more instead the regular browser behavior take effect (for example on mozilla a regular textbox which is anoying)
here is some pics atached from Chrome experience

Thanks
![1](https://cloud.githubusercontent.com/assets/3936079/23577510/f696a774-00b8-11e7-82ed-658aff0c9897.png)
![2](https://cloud.githubusercontent.com/assets/3936079/23577511/fe6df4e8-00b8-11e7-933c-90179a76f1a6.png)
![3](https://cloud.githubusercontent.com/assets/3936079/23577513/02208a24-00b9-11e7-81d8-52763f36cbc2.png)

**Comment by tribalboy3000** [comment]
I have the same issue. Some dates work fine, one click and it's selected. Then I try to click on another date then I need to double click to get it work.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by afganhalbana** [comment]
Hi @jwdsoft how you solved this issue? this issue happens to me also

**Comment by tribalboy3000** [comment]
This is actually not an issue. Whats going on is that you have 'touchMove' set to true. Turn that to false and you should be fine.
