### ISSUE TITLE
Pull to refresh from bottom of page

### ISSUE THREAD

**Issue by StefansArya** [framework7io/framework7#1403]
**Feature Request**

[About pull to refresh](http://framework7.io/docs/pull-to-refresh.html)
It would be nice if we can pull the bottom of page to refresh the content too. It just like [Infinite Scroll](http://framework7.io/docs/infinite-scroll.html), but it need to be pulled before loading a new content..

**Comment by sejalvrinsoft** [comment]
My requirement is opposite of it. Pull to refresh call only when i am top of the screen. Can you please let me know where i need to change. currently if i am at bottom of page and scroll up then pull to refresh call by default.
