### ISSUE TITLE
Possible change in searchbar for new android style

### ISSUE THREAD

**Issue by jeffersonmello** [framework7io/framework7#1404]
Does anyone have this change in css? Or the developers themselves could add this new style to the android searchbar, current style is obsolete.

Follows a good style image for the searchbar
![exm2y](https://cloud.githubusercontent.com/assets/17181273/23794876/4edddfd0-0571-11e7-862f-29bb437c3f8b.png)

**Comment by jeffersonmello** [comment]
how problem for clear button ?

![searchbar](https://cloud.githubusercontent.com/assets/17181273/23799757/6bcdc2d8-0588-11e7-8d03-f0076e3e0af5.png)

` @searchbarBorderColor: #b4b4b4;
 @searchbarSize: @toolbarSize;
.newsearchbar {
    height: @searchbarSize;
    width: 100%;
    background: @themeColor;
    box-sizing: border-box;
    padding: 0 16px;
    overflow: hidden;
    position: relative;
    .flexbox();
    .align-items(center);
    color:#5c636c;
    a {
        position: relative;
        color:#5c636c;
        .active-highlight();
    }
    .newsearchbar-input {
        width: 100%;
        color: #5c636c;
        background: #fff;
        border-radius: 2px;
        height: 32px;
        position: relative;
        .flex-shrink(1);
    }

    input[type="search"] {
        .bars-input();
        height: 100%;
        color: #5c636c;
        padding: 0 36px 0 24px;
        background-color: transparent;
        background-repeat: no-repeat;
        background-position: 0 center;
        opacity: 0.6;
        -webkit-background-size: 24px 24px;
        background-size: 24px 24px;
        .transition(300ms);
        .encoded-svg-background("<svg fill='#5c636c' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z'/><path d='M0 0h24v24H0z' fill='none'/></svg>");
        &::-webkit-newsearch-cancel-button {
            -webkit-appearance:none;
        }
    }

    input[type="search"]::-webkit-input-placeholder{ color: #5c636c;  }
    input[type="search"]::-moz-placeholder{ color: #5c636c;  }
    input[type="search"]::-ms-input-placeholder{ color: #5c636c;  }
    input[type="search"]::-moz-placeholder{ color: #5c636c;  }

    .newsearchbar-clear {
        position: absolute;
        width: 56px;
        height: 100%;
        right: -5px;
        top: 0;
        opacity: 0;
        pointer-events:none;
        background-position: center;
        background-repeat: no-repeat;
        .encoded-svg-background("<svg fill='#5c636c' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z'/><path d='M0 0h24v24H0z' fill='none'/></svg>");
        -webkit-background-size: 24px 24px;
        background-size: 24px 24px;
        .transition(300ms);
        cursor: pointer;
    }
    .newsearchbar-cancel {
        display: none;
    }
    &.newsearchbar-active {
        input[type="search"] {
            opacity: 1;
        }
        .newsearchbar-clear {
            pointer-events: auto;
            opacity: 1;
        }
    }
    &.newsearchbar-not-empty {
        .newsearchbar-clear {
            pointer-events: auto;
            opacity: 1;
        }
    }
}
.newsearchbar-overlay {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: 100;
    opacity: 0;
    pointer-events:none;
    background: rgba(0,0,0,0.25);
    .transition(300ms);
    .translate3d(0,0,0);
    &.newsearchbar-overlay-active {
        opacity: 1;
        pointer-events: auto;
    }
}
.newsearchbar-not-found {
    display: none;
}
.hidden-by-newsearchbar, .list-block .hidden-by-newsearchbar, .list-block li.hidden-by-newsearchbar {
    display: none;
}
.page > .newsearchbar {
    position: absolute;
    width: 100%;
    left: 0;
    top: 0;
    z-index: 200;
    & ~ .page-content {
        padding-top: @searchbarSize;
    }
}
.navbar-fixed, .navbar-through {
    .page > .newsearchbar, > .newsearchbar {
        top: @navbarSize;
        & ~ .page-content {
            padding-top: @searchbarSize + @navbarSize;
        }
    }
}


`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
