### ISSUE TITLE
Black area when swiping back 3 levels

### ISSUE THREAD

**Issue by lroal** [framework7io/framework7#1414]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: february
* Platform and Target: desktop browser, both safari and chrome

### What you did
Going 3 levels deep, then swiping back 3 times back to main view. The main view is displayed with a black area on the right side. It seems to have an extra class that should not be there: page-on-left.
PS I am using domCache:true at each view instance. 
When using the back button instead of swipe back, everything is normal.

### Expected Behavior
Should not have black area on right side. 

### Actual Behavior
Black area on right side. The div data-page has a class called page-on-left. When I remove this class, the black area disappears.

**Comment by tinyCoder32** [comment]
Maybe you are suffering the same: https://github.com/nolimits4web/Framework7/issues/1338

**Comment by ZanderBrown** [comment]
@nolimits4web any thoughts on this and #1338 ?

**Comment by honwlt** [comment]
It happens even with 2 levels deep page (without swipe) navigation. To reproduce: just go to the second page and click back to the first page very quickly, repeat few times, you will get black area on right side. I too see an extra "page-on-left" on the first page when the black area appears on the right.
I am using domCache:true

The workaround I did was to delay the level2 page rendering a little bit, it seemed to work. But it's a hack. Need a fix.

  setTimeout(function() {
    myview.router.load({
      pageName: "level2-page",
    });
  }, 70);

**Comment by lroal** [comment]
When using the swipe back and 3 levels deep, I always get the black area. It happens every time.
I will try the workaround. A proper bug fix, would be the best solution though.

**Comment by nolimits4web** [comment]
It looks like something wrong with the layout, will be good to see example or fiddle with the issue as it doesn't happen in default demos and examples

**Comment by lanasta** [comment]
This bug can be re-created in [the Inline Pages app example](http://framework7.io/examples/inline-pages/). 

### To re-create this bug:
1. Navigate to the About page
2. Go to the Services page by clicking on the blue link
3. Go to the About page by clicking on the blue link
4. Go to the Services page again by clicking on the blue link
5. Hit the back button until we land on the homepage. You should be able to observe two problems along the way: 
    - You land on the Form page even though you never opened it.
    - When you land on the homepage, the black area is there.

**Comment by lroal** [comment]
![blackarea](https://cloud.githubusercontent.com/assets/631501/26189141/4f0098e6-3ba3-11e7-85a7-871c747dad58.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
