### ISSUE TITLE
taphold not firing

### ISSUE THREAD

**Issue by phanivaranasi** [framework7io/framework7#1417]
I'm trying to work with taphold function, as given in doc 
https://framework7.io/docs/tap-hold.html
below is my screen shot of my application, when user long press on slots, i need to call a relevant function for cancelling the slot booking.

![screenshot_2017-03-16-12-53-06](https://cloud.githubusercontent.com/assets/6230353/23985923/8de07b22-0a47-11e7-8525-fe9b96cd07be.png)
Below is HTML for rendering slots (using angualrjs )
![ulli](https://cloud.githubusercontent.com/assets/6230353/23985987/dd1b61c0-0a47-11e7-9165-2d017b296620.PNG)
Below is js script for firing event.
![uliscript](https://cloud.githubusercontent.com/assets/6230353/23986017/0fe2ee52-0a48-11e7-8d55-c946b7bf1b68.PNG)

 I've also referred https://github.com/nolimits4web/Framework7/issues/405 
but I couldn't find any use.
Kindly could any one assist me in firing the event.

**Comment by masmanidis** [comment]
Hi

You should add taphold property to true at app initialization
Then remove app variable from event handler
Finally try to bind this event on page container or on document 

Hope this help you

**Comment by phanivaranasi** [comment]
@masmanidis , I have added taphold property to true. 
Below in my F7 configuration.
![taphold](https://cloud.githubusercontent.com/assets/6230353/23986971/00e2deda-0a4d-11e7-8eeb-edb49b1dbdf1.PNG)

**Comment by masmanidis** [comment]
So 
Use $$(document).on(“taphold”,“.list-item”, function(){}); 
or $$(page.container).on(“taphold”,“.list-item”, function(){});

[This is a suggestion I've got from f7 forum!]

**Comment by phanivaranasi** [comment]
@masmanidis 👍  temporary I have got response on taphold
using
$$(document).on(“taphold”,“.list-item”, function(){});
but will debug and update with any consequences arises.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
