### ISSUE TITLE
Want to create a Dynamic Timeline

### ISSUE THREAD

**Issue by alapanme** [framework7io/framework7#1418]
The idea is to create a Timeline having the date and some text as input using a form. Now save this Detail in the local storage and display the same in time line. 
Can anyone guide me as how I can achieve that. A code piece example will be more than useful.

**Comment by ZanderBrown** [comment]
`document.createElement('tag')` to make elements, `elm.appendChild(otherelm)` to put elements inside elements ect..

Or look at Template7

Past that it's your job to design the logic

**Comment by J05HI** [comment]
@nolimits4web 
A virtual list timeline would be great :)

**Comment by alapanme** [comment]
```
<ul>
    <!-- Text inputs -->
    <li>
      <div class="item-content">
        <div class="item-media"><i class="icon f7-icons">compose</i></div>
        <div class="item-inner">
          <div class="item-input">
            <input type="text" name="title" placeholder="Title">
          </div>
        </div>
      </div>
    </li>
    <li>
      <div class="item-content">
        <div class="item-media"><i class="icon f7-icons">document_fill</i></div>
        <div class="item-inner">
          <div class="item-input">
            <input type="text" name="achievement" placeholder="Describe">
          </div>
        </div>
      </div>
    </li> 
    <!-- Date -->
    <li>
      <div class="item-content">
        <div class="item-media"><i class="icon f7-icons">calendar</i></div>
        <div class="item-inner">
          <div class="item-input">
            <input type="date" name="date" placeholder="Birth day" value="2014-04-30">
          </div>
        </div>
      </div>
    </li>
  </ul>
  </form>
  <div class="content-block">
  <p><a href="#" class="button get-storage-data">Get Data</a></p>
</div>
```

JS Code-
```
var $$ = Dom7;
var arr = [];

$$('.get-storage-data').on('click', function() {
	
  var storedData = myApp.formGetData('my-form');
  arr.push(storedData);
  console.log(arr.length);
 // var title = [];
 for(var i = 0; i<arr.length;i++){
  //if(storedData) {
    //alert(JSON.stringify(storedData));
			localStorage.setItem(arr[i],JSON.stringify(storedData));
  //}
  //else {
    //alert('There is no stored data for this form yet. Try to change any field')
  //}
 }
});
```
I am able to set one set of data from the form to the local storage, but when I am putting the second set of data from the form, it edits the first set of data in the local storage. 
I want that whatever data I input through Form, it should get saved one by one.

**Comment by alapanme** [comment]
@nolimits4web @ZanderBrown

**Comment by alapanme** [comment]
```
$$('.form-to-data').on('click', function(){
  var formData = myApp.formToData('#my-form');
arr.push(formData)
for (var i=0; i<arr.length; i++)
{
formData[i]=localStorage.setItem(i,JSON.stringify(formData));
}
```
I have changed the App JS to set multiple items in local storage from a form. Can anyone suggest what changes can be made ?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
