### ISSUE TITLE
[Photobrowser bug] Panning an Image while zoomed in does not work

### ISSUE THREAD

**Issue by seme1** [framework7io/framework7#1427]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3.
* Platform and Target: IOS

In photobrowser when multiple images are presented, try to manually zoom in on any single image. While image is zoomed in, try to pan the image [move it to right or left] and the whole page would instead slide to right or left instead of the expected behavior.  This bug appeared for me on IOS. I don't have an Android device currently to confirm whether it also happen on Android.

**Comment by ZanderBrown** [comment]
Would be good to have a CodePen / jsFiddle.

**Comment by seme1** [comment]
Best example is the photobrowser component in the kitchen sink at http://framework7.io/kitchen-sink-ios/

**Comment by nolimits4web** [comment]
If you mean the native iOS Safari swipe back functionality when browsing app in browser (rather than in Cordova or Home Screen app) then it is not possible to disable it

**Comment by seme1** [comment]
No, I don't mean the swipe back functionality. Also, the problem occurs in Cordova, not in any browsing app.

When the picture is zoomed in, try to swipe/pan the image to view the different hidden portions of the zoomed in image and you will notice that instead of the picture moving, the whole page slides to the right or the left.

Unfortunately, I'm unable to reproduce the problem on my iPhone right now.  This problem was definitely occurring yesterday. I'll report back and come once I can reproduce it.

**Comment by seme1** [comment]
@nolimits4web Please view the video at the following link. The problem appears at the end of the video. Please note how an attempt to pan the image is made but photobrowser slides the whole page instead.

https://drive.google.com/file/d/0B6B6qgK4e41XckdtY214TnBYSUE/view?usp=sharing

The problem appears randomly, but sometimes it appears a lot and it's very annoying.

**Comment by seme1** [comment]
Any updates on this ? This bug is becoming extremely annoying on my app.

**Comment by media0101** [comment]
This problem has not yet been solved on Android (Chrome)?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
