### ISSUE TITLE
Range slider not visible in native Android apps

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#1441]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Used range element in form.

### Expected Behavior
Slider knob shown.

### Actual Behavior
Slider knob not shown in Android Cordova app.
(Slider known shown in iOS Cordova app and in Chrome web browser)

**Comment by macdonst** [comment]
@scriptPilot perhaps a few more details. What version of Android were you testing on? What version of Cordova? Could you throw up a quick code pen that reproduces the bug?

**Comment by scriptPilot** [comment]
@macdonst - Is this App okay for your tests?
https://play.google.com/store/apps/details?id=de.scriptpilot.appframework

Made with https://github.com/scriptPilot/app-framework

**Comment by nolimits4web** [comment]
Would be good to know is it actual for Material theme? iOS theme is not designed to be used on Androids

**Comment by scriptPilot** [comment]
Ah okay, could be the reason. But, isn't it possible to make both work on both systems? In fact, to have the same design people would try to use one theme and make it work on any device.

**Comment by scriptPilot** [comment]
@nolimits4web @macdonst - Tested on Android 7.1 via Emulator. But the same on older real phone.

**Comment by scriptPilot** [comment]
Same behaviour with iOS:
https://github.com/nolimits4web/Framework7/issues/1567

Screenshot from Android emulator (7.1):
![screenshot_1495485899](https://cloud.githubusercontent.com/assets/19615586/26327594/4e75e48a-3f40-11e7-9b45-04ab6a2214c3.png)

**Comment by rvanzon** [comment]
I probably have a work around for this here: https://github.com/nolimits4web/Framework7/issues/1567

**Comment by owen-mills** [comment]
Same issue

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
