### ISSUE TITLE
Group List Titles hidden behind top bars.

### ISSUE THREAD

**Issue by thiagoabreu** [framework7io/Framework7#1444]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4
* Platform and Target: iOS and Material

### What you did
Hi. I was trying to use the Contact List and end up with the following code:

```html
<div class="page">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="sliding center">
                Page Title
            </div>
        </div>
    </div>
    <div class="hide-bars-on-scroll page-content">
        <div class="contacts-block list-block">
            <div class="list-block-group">
                <ul>
                    <li class="list-group-title"><span>A</span></li>
                    <li>
                        <div class="item-content">
                            <div class="item-inner">
                                Anonimous 1
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="item-content">
                            <div class="item-inner">
                                Anonimous 2
                            </div>
                        </div>
                    </li>
                    <!--many more...-->
                </ul>
            </div>
        </div>
    </div>
</div>
```

### Expected Behavior
The `.list-group-title` elements should stay visible when I scroll the page.

### Actual Behavior
1. When there's no navbar, it works. 
2. When there's a fixed top bar (nav, tool, tab, etc), the group title stays hidden behind those bars.
3. When used along with the "hide-*-on-scroll" the group titles is scrolled out of the page and when the bars returns the group title is hidden by them.

I found that, in the 3rd case, the transition rule puts a [negative 'top' rule](https://github.com/nolimits4web/Framework7/blob/master/src/less/ios/toolbars-pages.less#L55), making the `position: sticky` rule being kinda useless. And when the bars return, the 'top' goes back to 0 and it's like the 2nd case when the bars hide the group title.

**Comment by J05HI** [comment]
@thiagoabreu @nolimits4web 
Can confirm the bug bit it was there before v1.5.4. 
Only on Chrome for Android, iOS Safari is fine.

**Comment by J05HI** [comment]
@nolimits4web 
Please take a look at this, it's a great feature but unusable because of iOS only support

**Comment by unstableair** [comment]
I'm also experiencing this issue.

The easiest way to replicate the problem is to view the F7 kitchen sink demo on an Android device in the Chrome browser, go to the List View section and scroll down to the 'Grouped with sticky titles' (which aren't sticky).

    `https://framework7.io/kitchen-sink-material/`

It can also be replicated in the Chrome desktop browser using the dev tools, device toolbar to emulate an Android device.

**Comment by nolimits4web** [comment]
It is a Chrome browser issue with wrong position:sticky implementation
