### ISSUE TITLE
Use Dom7 on server side / Dom7 only JS

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#1465]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

### What you did
Include Framework7 with `require('...')` in node server code.

### Expected Behavior
Dom7 could be used to manipulate html strings in the normal way.

### Actual Behavior
Warning "window is not defined".

**Comment by scriptPilot** [comment]
The following workaround creates the Dom7 standalone library, but then "document is not defined" is shown. So, I understand it's not in the browser, but isn't there no way to handle HTML tags with Dom7-like syntax server-side?

```
// Load Dom7 library
let dom7Content = 'var window = {};' +
                  fs.readFileSync(abs(f7Folder, 'src/js/dom7/dom7-intro.js'), 'utf8') +
                  fs.readFileSync(abs(f7Folder, 'src/js/dom7/dom7-methods.js'), 'utf8') +
                  fs.readFileSync(abs(f7Folder, 'src/js/dom7/dom7-ajax.js'), 'utf8') +
                  fs.readFileSync(abs(f7Folder, 'src/js/dom7/dom7-utils.js'), 'utf8') +
                  'return $; })(); module.exports = Dom7'
fs.writeFileSync(abs(f7Folder, 'src/js/dom7/dom7.bundle.js'), dom7Content)
let Dom7 = require(abs(f7Folder, 'src/js/dom7/dom7.bundle.js'))
```

**Comment by ZanderBrown** [comment]
DOM (Window, Document, HTML(*)Element) and their variables (window, document) don't exist in the Node.js environment

Try loading [jsdom](https://www.npmjs.com/package/jsdom) or similar

**Comment by nolimits4web** [comment]
Right, it is not intended/designed to be used on server-side

**Comment by scriptPilot** [comment]
@ZanderBrown - Thanks, JSDom works fine with jQuery@npm

@nolimits4web - Is there a chance to allow Framework7 to work in the same way as jQuery together with JSDom?

https://www.npmjs.com/package/jquery

```
require("jsdom").env("", function(err, window) {
    if (err) {
        console.error(err);
        return;
    }
 
    var $ = require("jquery")(window);
});
```

**Comment by ZanderBrown** [comment]
If you do the work it can probably be done but is a bit outside F7's scope

**Comment by scriptPilot** [comment]
@ZanderBrown - I will do so, please coul you reopen the issue?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
