### ISSUE TITLE
Accordion item's content disappear when pull to refresh layout is added

### ISSUE THREAD

**Issue by durad** [framework7io/framework7#1473]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4
* Platform and Target: CORDOVA, IOS, ANDROID
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/durad/yhtz663c/ (issue will not occur in the browser, only on the device)

### What you did

I've created an empty PhoneGap project and added Framework7 1.5.4 libs and material theme. Created a simple page with pull-to-refresh layout and an accordion control. Here is the structure of the page:
```
.views
  .view view-main
    .pages
      .page

        .page-content .pull-to-refresh-content
          .pull-to-refresh-layer
            .preloader
            .pull-to-refresh-arrow

          .list-block
            .accordion-item
              .item-content .item-link
                .item-inner
              .accordion-item-content
                .content-block
            .accordion-item
              .item-content .item-link
                .item-inner
              .accordion-item-content
                .content-block
            ...
```
Application was run in PhoneGap companion app as well as compiled app on an android device.

I've then expanded an accordion item, collapsed it and expanded it again.

### Expected Behavior

Accordion item's content should be visible every time the item is expanded.

### Actual Behavior

- With material theme: accordion items gets expanded properly only the for first time. Every other time that they are expanded their content is missing.

![material](https://cloud.githubusercontent.com/assets/3118582/24675501/3a10f034-1934-11e7-9979-0f14dfdc1aaa.png)

- With ios theme: repro steps are slightly different - start pull to refresh loading sequence first and then expand, collapse, expand an accordion item and it's content's will disappear.

![ios](https://cloud.githubusercontent.com/assets/3118582/24675597/a0a0b8e8-1934-11e7-8b8f-283b00fc05cb.png)

It seems to be related to the z-index of the components. A simple workaround is to add a following css code:

`.accordion-item { z-index: 10; }`

Please note that the issue will not appear in the browser, it only happens in PhoneGap developer app or when compiled and run as an Android app. Even though the issue happens on the accordion control, it will only happen when pull to refresh layout is present as well.

**Comment by jmail** [comment]
We are experiencing similar issue but in our case it is when accordion is expanded second time and you make a small scroll top. Video in attached zip

[IMG_3124.zip](https://github.com/nolimits4web/Framework7/files/934449/IMG_3124.zip)

**Comment by frontenddeveloping** [comment]
+1 for such behavior/bug

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
