### ISSUE TITLE
dir="auto" does not affect placeholder

### ISSUE THREAD

**Issue by tinyCoder32** [framework7io/framework7#1474]
Hi, I am using RTL style, I have input/textarea fields with `dir="auto"` attribute, it does move the text to the right when I type in Arabic, while the placeholder goes to left if the field is empty!

What should happen is that the placeholder also should be in RTL and aligned to the right side when it is empty.

** Current Case **

1- Empty Fields
![screen shot 2017-04-05 at 1 22 47 am](https://cloud.githubusercontent.com/assets/17817239/24681550/6a461cb0-199e-11e7-93af-a3dbee1a9b2a.png)

2- Filled:
![screen shot 2017-04-05 at 1 23 34 am](https://cloud.githubusercontent.com/assets/17817239/24681569/831e00c2-199e-11e7-8e77-66edaf27bd0a.png)

** CORRECT Case **
1- Empty:
![screen shot 2017-04-05 at 1 25 42 am](https://cloud.githubusercontent.com/assets/17817239/24681645/cf04c07a-199e-11e7-9da6-9299837c0391.png)

What I did is changing the placeholder CSS using:

```
::-webkit-input-placeholder { /* WebKit, Blink, Edge */
    text-align: right;
    direction: rtl;
}
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
    text-align: right;
    direction: rtl;
}
::-moz-placeholder { /* Mozilla Firefox 19+ */
    text-align: right;
    direction: rtl;
}
:-ms-input-placeholder { /* Internet Explorer 10-11 */
    text-align: right;
    direction: rtl;
}
```

Although, `direction: rtl;` didn't work on the placeholder element, the text in the second input filed is still LTR (dots should be at the end of the phrase), but at least direction is correct now.

I thought it worth telling about this issue and maybe include a fix in the RTL css file.

Thanks.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
