### ISSUE TITLE
Window.localStorage : Access is denied for this document.

### ISSUE THREAD

**Issue by bingzheyuan** [framework7io/framework7#1478]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4 (latest).
* Platform and Target: HUAWEI P8 EMUI(v4) Android6.0 Chrome 57.

got this error on app init
> Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

error on file [/src/js/framework7/f7-intro.js#L167](https://github.com/nolimits4web/Framework7/blob/master/src/js/framework7/f7-intro.js#L167)

I think we should wrap this line with try&catch.

**Comment by ZanderBrown** [comment]
Interesting,

How are you loading the app?

**Comment by bingzheyuan** [comment]
The error occurs when I load F7 in script tag, my code is not loaded at all. @ZanderBrown

**Comment by bingzheyuan** [comment]
OK, I think I understand your question. @ZanderBrown , I mention the source file just for the developer to find the error easier, I have imported the whole F7 of course.

**Comment by ZanderBrown** [comment]
I was meaning are you accessing it in browser directly from the devices file-system or from a server over HTTP?

Or are you using PhoneGap ect

**Comment by bingzheyuan** [comment]
@ZanderBrown no, not something that complicated. I used chrome remote debug and connected my phone. I try to open the page with F7 imported in Android Chrome and then I see the error.

**Comment by nolimits4web** [comment]
What do you mean by "the page with F7 *imported* in Android Chrome?

**Comment by bingzheyuan** [comment]
sorry for the misunderstanding, the scenario is simple, a simple page with a script tag, src set to F7.

**Comment by ZanderBrown** [comment]
Okay we understand what is in the page. What we need to know is how your accessing it.

Did you:
1. Copy the .html onto the device and use a file manager app to open in Chrome
2. Upload the page to a web server and browse to it's address (e.g. example.com/test.html)
3. Used PhoneGap or similar to package the page

**Comment by bingzheyuan** [comment]
No.2 is what happened. I have a local php server and navigated to it through url.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
