### ISSUE TITLE
Timeline not scrollable with iNoBounce

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#1482]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did
To avoid bouncing on iOS Web Apps, I use https://github.com/lazd/iNoBounce. So far, it works well with Framework7 in general, but not with horizontal timeline / calendar elements.

### Expected Behavior
Horizontal scrolling is possible.

### Actual Behavior
Scrolling is not possible. Disabling iNoBounce will fix it.
Is there any way to enable the usage of iNoBounce even with these new nice elements?

PS: Horizontal scrolling in data tables, sliders etc. works well with iNoBounce!

**Comment by scriptPilot** [comment]
I just figured out, that there is no issue with horizontal scrolling on data tables!

**Comment by mohshraim** [comment]
if you are using iOs webview please try the following:
webview.scrollView.bounces = no;

its work with my case to prevent bounce for the whole webview content.. but not for parts of the HTML content..

**Comment by scriptPilot** [comment]
@mohshraim - Thank you for that tip! Do you have a full example how to use that in a "normal" Cordova app? Are there any additional plugins required?

**Comment by mohshraim** [comment]
just add webview to your view controller

this code on  load

 NSString *urlAddress = [[NSBundle mainBundle] pathForResource:@"htmlFolder/index" ofType:@"html"];
    NSURL *url = [NSURL fileURLWithPath:urlAddress];
    NSURLRequest *request = [NSURLRequest requestWithURL:url];
    
    _webView = [[UIWebView alloc] initWithFrame:self.view.frame];
    [_webView loadRequest:request];
    _webView.scrollView.bounces = NO;
    _webView.keyboardDisplayRequiresUserAction=NO;
    [_webView setScalesPageToFit:true];
    [_webView setDelegate:self];
    [self.view addSubview:self.webView];

**Comment by scriptPilot** [comment]
@mohshraim - I provide HTML / JS code to Cordova, so I am not manipulating any iOS or Android code itself. Where do you place that code?

**Comment by ZanderBrown** [comment]
Quick Google suggests `<preference name="DisallowOverscroll" value="true" />` in config.xml

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
