### ISSUE TITLE
Material Searchbar Update

### ISSUE THREAD

**Issue by snowbreeze** [framework7io/Framework7#1489]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: latest
* Platform and Target: Material
* Live Link or JSFiddle/Codepen: https://material.io/guidelines/patterns/search.html#search-in-app-search

Requesting to update the search bar to the new material design search.
Sample https://material.io/guidelines/patterns/search.html#search-in-app-search

**Comment by J05HI** [comment]
Please give more information

**Comment by ZanderBrown** [comment]
@J05HI we have the info we need

**Comment by J05HI** [comment]
@ZanderBrown 
I think the search bar is great as it is. No need to change it to that ugly style

**Comment by snowbreeze** [comment]
If we are following the material guidelines then we should update.

Existing one is more like the ios style.

**Comment by J05HI** [comment]
Yeah but I can't see it clearly on that mockup. 
Can you maby provide a better screenshot :)

**Comment by snowbreeze** [comment]
Yes this is the exact thing!

**Comment by J05HI** [comment]
Okay then we are on the same level. 
Let's hope @nolimits4web has time to integrate that

**Comment by J05HI** [comment]
@nolimits4web @snowbreze

Here two gif examples:

![](http://i.imgur.com/n43Gab3.gif)

![](http://i.imgur.com/RDx1Y3n.gif)

**Comment by snowbreeze** [comment]
@J05HI the second gif isnt loading

**Comment by J05HI** [comment]
@snowbreeze 
Thx somehow its broken, I think one is enough :)

**Comment by snowbreeze** [comment]
Yes this searchbar looks good.

**Comment by nolimits4web** [comment]
Done in v2

**Comment by theavijitsarkar** [comment]
Thanks @nolimits4web
