### ISSUE TITLE
Auto scroll on sortable sort

### ISSUE THREAD

**Issue by brainformatik** [framework7io/Framework7#1493]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: LATEST
* Platform and Target: All

It would be nice if the sortable list will auto scroll the page if there are more items than the page height and you would like to drag an item to a location which isn't visible.
I hope @nolimits4web understand ;)

**Comment by J05HI** [comment]
@nolimits4web 
Yeah I have the same problem. Would be nix of you improve that :)

**Comment by nolimits4web** [comment]
Closing as it is done in v2
