### ISSUE TITLE
Pull to refresh material design 

### ISSUE THREAD

**Issue by J05HI** [framework7io/Framework7#1499]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Maby you can make the pull to refresh more material like. 
Here an example:
![below-color](https://cloud.githubusercontent.com/assets/16399787/25026861/fbc19d8e-20a8-11e7-8743-5d3aebb9ab60.gif)

**Comment by nolimits4web** [comment]
Done in v2
