### ISSUE TITLE
back button when popup is open

### ISSUE THREAD

**Issue by boynet** [framework7io/framework7#150]
when pushState: true.

1.when popup is open and you press back button(on browser or android not the framework back button) the popup stays and the pages under the popup change.
is there a way  to push a state on popup open? so the back button will close the popup?

**Comment by ZanderBrown** [comment]
Is this resolved?

**Comment by valnub** [comment]
Closed due to no reaction after several months

**Comment by boynet** [comment]
@valnub its not solved but I think that nolimits4web not seeing this as bug

**Comment by valnub** [comment]
Well, on iOS this definitely not a bug because there is no such behavior for pop-up (as there is no physical back button on the device).

On Android, yeah one could argue that this needs more refinement.

Maybe someone can create a plugin or pull-request to fix this.

**Comment by tinyCoder32** [comment]
Will this be taken in mind soon?
I'm having the same issue on my app, it is made for iOS and Android and having a lot of popups that need to be closed using the Android device back button.

**Comment by tinyCoder32** [comment]
I managed to do it as members suggested:

```
$$(window).on('popstate', function(){
  myApp.closeModal('.popup.modal-in');
});
```

`window.history.pushState('', '','#!/#signup');`

We hope that this will be taken into consideration to have an easy option in next versions.

**Comment by brainformatik** [comment]
@nolimits4web 
Please fix that. Everyone (android users) needs that.

**Comment by brainformatik** [comment]
@tinyCoder32 @boynet 

Our dirty fix for smart-select popups is this:
`this.$pageContainer.find('a.smart-select').on('click', function () {
            window.history.pushState('', '', '#/' + window.history.state.url + '&popupOpened');

            $$(window).on('popstate', onPopupHistoryBack);
            function onPopupHistoryBack () {
                myApp.closeModal('.popup.modal-in');

                $$(window).off('popstate', onPopupHistoryBack);
                $$(document).off('click', '.link.close-popup', onPopupCloseButtonClick);
            }

            $$(document).on('click', '.link.close-popup', onPopupCloseButtonClick);
            function onPopupCloseButtonClick () {
                window.history.back();

                $$(document).off('click', '.link.close-popup', onPopupCloseButtonClick);
                $$(window).off('popstate', onPopupHistoryBack);
            }
        });`

But dirty fixes are ugly. It's a framework7 issue, so we hope @nolimits4web has time for it.

**Comment by J05HI** [comment]
@nolimits4web 
I need this too for android compatibility, but dirty hacks aren't very good. I need a real implementation.

**Comment by ZanderBrown** [comment]
@J05HI With how long these issues have been open i suggest you contribute a 'real implementation'

**Comment by J05HI** [comment]
@ZanderBrown 
I'm not familiar with the Framework7 source. I think @nolimits4web can do this better and faster.

**Comment by tazzkiller** [comment]
For my apps a use a simple workaround with addClass/removeClass on the body element and my back button check if the body has the class or not before execute any action.

**Comment by J05HI** [comment]
@tazzkiller
Can you please post a code example :)

**Comment by tazzkiller** [comment]
```
$$('.your-popup').on('popup:close', function () {
  $$('body').removeClass('popup-open');
});
$$('..your-popup').on('popup:open', function () {
  $$('body').addClass('popup-open');
});
```

on your "backbutton" event : 

```
if ($$('body').hasClass('popup-open')) {
myApp.closeModal();
} else {
window.history.back();
}


```

**Comment by valnub** [comment]
I don't think this will get a fix in Framework7 1.x - As the work on v2 has begun, it might be fixed there as it is more a feature-request rather than a bug.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by J05HI** [comment]
@nolimits4web
Yeah in v2 it should already work :)
