### ISSUE TITLE
Redirect issue after login

### ISSUE THREAD

**Issue by subhomoy92** [framework7io/framework7#1510]
Hello every body,

I'm creating a appliction using framework7 and i'm having a very odd problem.

I've multiple page say index.html. login.html and dashboard.html

The login is working fine and getting redirected to dashboard but if we press the back button from the browser or from the phone, it is again coming to login page and further coming to index.html

i've tried everything like 

`myApp.onPageInit('login', function (page) {   
	var user_id = localStorage.getItem('userid');	
	if(user_id)
	{		
		mainView.router.loadPage({
	        url: 'dashboard.html',
	        ignoreCache: true
	    });	 
	    return false;
	}
});`

its not working.

i've also tried

`myApp.onPageBeforeAnimation('login', function (page) {   
    var user_id = localStorage.getItem('userid');
	
	if(user_id)
	{		
		
	 mainView.router.loadPage({
	        url: 'dashboard.html',
	         ignoreCache: true
	  });
	 return false;	
	}
});`

none of this things worked with me..

what i want is if the user is logged in, when ever he tries to visit login or index page, through url or back from phone, it will redirect to dashboard.

Any help will be very appreciated.

**Comment by centrual** [comment]
Delete login page from history after logged in.

**Comment by subhomoy92** [comment]
@centrual  can u please tell mehow to acheive this.

**Comment by centrual** [comment]
```javascript
var activeView=myApp.getCurrentView();
activeView.history.splice(0,1);
```

**Comment by subhomoy92** [comment]
@centrual 
Thanks for the reply, but tell me one thing where can i use the code? it still redirecting back to login on back

I have used this code just before after redirecting to dashboard after login.

Please explain in details. I'm a newbie in framework7

**Comment by centrual** [comment]
Hey @subhomoy92 

I didn't used this code. I just found similar question in framework7 dedicated forum for you and edited a little. You can debug framework7 in Chrome with developer tools and you can test different methods. Example:

```
var activeView=myApp.getCurrentView()
console.log(activeView.history)
```

You can find dedicated forum [here](http://forum.framework7.io/).

**Comment by subhomoy92** [comment]
Thanks @centrual  for your help.

**Comment by subhomoy92** [comment]
@centrual i've added your code and its working fine. but when ever i'm pressing the back button its just showing a alert button containing my current directory url.

Is there anything to remove that?

Thanks in advance

**Comment by ZanderBrown** [comment]
Do you have push state enabled?

**Comment by subhomoy92** [comment]
Yes push state is enabled. The push separator is '#!'

**Comment by subhomoy92** [comment]
@ZanderBrown push state is enabled

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
