### ISSUE TITLE
Dynamic Calendar Events

### ISSUE THREAD

**Issue by odesey** [framework7io/framework7#1511]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 1.5.3.
* Platform and Target:  Any.
* Live Link or JSFiddle/Codepen: NA

I have a question regarding the calendar feature. 

Is there anyway to dynamically load events? For example I may not want to load the events for the month of May while the calendar is on another month. 

In fullcalendar.io there is a feature called `refetchEvents`, that allows for getting events as needed. Is there anything similar in F7? If not can I suggest a possible feature request.

Thanks.

**Comment by J05HI** [comment]
@nolimits4web 
I need that too! Please add a method to dynamically add calendar events when the calendar is initialized.

**Comment by bene40** [comment]
This feature is very usefull, I need it too. Hope to see it in the future.

**Comment by manish2535** [comment]
Any updates on this? Need it desperately. Thanks.

**Comment by manish2535** [comment]
@J05HI , Did you find a way to do this?

**Comment by J05HI** [comment]
@manish2535
I think it is already implemented in v2

**Comment by manish2535** [comment]
It did not work for me so I had to push my changes into calendar.params.events and then do a update. That did the trick.

**Comment by J05HI** [comment]
@manish2535
Okay great it worked now! :)

**Comment by manish2535** [comment]
@nolimits4web This can be close now. Thanks.
