### ISSUE TITLE
Обновляется не тот Dom элемент

### ISSUE THREAD

**Issue by valentin93** [framework7io/framework7#1513]
Добрый день. Решил написать по русски, так как только так я смогу полностью выразить свою мысль правильно.

Использую реакт, но не суть, так как этот же баг я воспроизвел на коде из примера на главной странице сайта.
Инициализирую приложение с параметрами

 ```
       animatePages={false}
       preloadPreviousPage={false}
       activeState={false}
       cache={false}
       uniqueHistory={true}
       allowDuplicateUrls={false}
       pushState={false}
       pushStateOnLoad={false}
```

View:

```
       reloadPages={true}
       domCache={false}
```

Далее создаю 2 списка просто взяв их их примера на сайте и начинаю ходить по странице бесконечно далеко.

Грубо говоря есть 2 страницы live и line, и я открываю страницы в такой последовательности:

live-line-live-line-live-line

Далее мы сможем увидеть сам баг на видео, которое я заснял со своего экрана:
https://www.screencast.com/t/KbOijIHRA

Видео, что страница линии ТОЛЬКО В САМЫЙ первый раз инициализировала прелоадер и активный tab.
Во все остальные разы это происходило без инициализации.

Покопавшись в исходном коде f7 при помощт консоли я понял, что инициализация прелоядера и таба выполняется, но на том элементе, которого уже нет.

Пожалуйста ответьте мне , и если нужно, я предоставлю больше информации по этому багу.

Спасибо

**Comment by J05HI** [comment]
@valentin93 
English please! No one can help you!

**Comment by valentin93** [comment]
@J05HI 
https://www.screencast.com/t/KbOijIHRA

It can be seen that the page of the line ONLY IN THE MOST first time initialized the preloader and the active tab. In all other cases this happened without initialization.

**Comment by ZanderBrown** [comment]
@J05HI it's generally better to use native languages as reporters can often better express themselves in it.

In this case the language being used is Russian(?) which @nolimits4web and other round here speak perfectly well and [Google Translate](https://translate.google.com/) exists for everyone else / other languages

**Comment by J05HI** [comment]
@ZanderBrown 
Okay, but I don't really like Google Translate. I think every developer should be able to write english ;)

**Comment by ZanderBrown** [comment]
@J05HI i think we should live in a global community accepting of everyone, just because we don't want to learn anothers language doesn't mean they should learn ours or be excluded.

Sure automatic translation tools arn't yet perfect but they exist so lets use them

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
