### ISSUE TITLE
Material Input Form Enhancement

### ISSUE THREAD

**Issue by achmadk** [framework7io/Framework7#1516]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: both desktop and mobile browsers.
* Live Link or JSFiddle/Codepen: [here](https://jsfiddle.net/0ogxxcvt/6/)

### What you did
I used Framework7 material style and script in my project. I implemented material form input, e.g. full name, email, and also date input with default value current date. I type some value in full name input then jump to email input.

### Expected Behavior
When I want to type value in email input, the line below full name input value is disappeared. And then the line below input value is highlighted only when focus input event is fired.

### Actual Behavior
When I want to type value in email input, the line below full name input value still exist. And its line is also highlighted when input has value.

**Comment by ZanderBrown** [comment]
[Material Spec](https://material.io/guidelines/components/text-fields.html#text-fields-states), [Refrence Implementation](https://getmdl.io/components/index.html#textfields-section), [F7 Implementation](http://framework7.io/kitchen-sink-material/)

> ![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOb195LU9KWEdIeEk/states.png)
> *<cite>[Material Spec](https://material.io/guidelines/components/text-fields.html#text-fields-states)</cite>*

So it seems inputs should have a bold underline when focused or containing invalid data.

Framework7's current implementation uses a bold line when the field is focused or contains data which is clearly a breach of the spec
