### ISSUE TITLE
Disable scroll on page when panel is opened

### ISSUE THREAD

**Issue by Remskei** [framework7io/framework7#1523]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: CORDOVA, IOS

### What you did
I have created an app with this awesome framework, but I have an issue on iOS. I don't have this issue on Android or in Browser. It looks like it's a CSS property or something that doesn't work in UIWebView on iOS.

### Expected Behavior
On iOS when panel is opened, if I scroll, the content behind the panel doesn't scroll.

### Actual Behavior
On iOS when panel is opened, if I scroll, the content behind the panel is scrolling
![test-ios](https://cloud.githubusercontent.com/assets/15141534/25433683/83c4f714-2a89-11e7-9892-bc0fec93bae1.gif)

**Comment by ZanderBrown** [comment]
But why would you want the page under a open panel to scroll?

**Comment by Remskei** [comment]
Sorry I did a mistake. The page under panel is scrolling and I don't want that it scrolls.

**Comment by J05HI** [comment]
@Remskei
Mist be a bug in your apps layout

**Comment by Remskei** [comment]
@J05HI Maybe, my layout looks like this.
http://imgur.com/Vs5I6d5

**Comment by J05HI** [comment]
@Remskei
@Remskei
I think it looks fine. 
Test it in the kitchen sink: http://framework7.io/kitchen-sink-ios/

**Comment by Remskei** [comment]
@J05HI Same issue. I've just duplicated the paragraph multiple times to make content scrollable. And I changed panel-reveal class by panel-cover of the right panel.
http://imgur.com/XTYZ0JK

**Comment by J05HI** [comment]
@Remskei
Strange

**Comment by Remskei** [comment]
@J05HI You don't have this issue?

**Comment by sunnypatel** [comment]
+1 Does anyone have a solution to this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
