### ISSUE TITLE
Need previous page info during preprocess callback

### ISSUE THREAD

**Issue by WeaponX86** [framework7io/framework7#1525]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: Google Chrome, Phonegap
* Live Link or JSFiddle/Codepen: -

### What you did
During preprocess I load TARGET page data asynchronously and need to get the PREVIOUS page

Ex. If the page is navigating from login to home, I process the data differently.

Here is my preprocess code:
```javascript
function preprocess(content, sUrl, next) {
	var sPage = sUrl;
	
	if (window.location.hash){
		//console.log('Hash specified');
		
		if (sUrl.indexOf('page-') != -1){
			// Regular epression to extract page name from url hash
			var rxPageName = /(?:page-)(.+)(?=\.)/g;

			var oMatch = rxPageName.exec(sUrl);
			//console.log(oMatch);

			if (oMatch['length'] > 1){
				sPage = oMatch[1]
			}
		}		
	} else{
		//console.log('No hash specified');
	}
	
	console.log('ROUTER: preprocess - requested url: ' + sUrl + ' page: ' + sPage);
	
	Permissions.pageAllowed(sPage, function(bAllowed, sMsg){
		if (bAllowed){
			msg_success('Access granted');

			// Get page data asynchronously
			if (sPage in window.oPages){
				
				// Make sure target page has init function
				if (typeof(oPages[sPage].init) == 'function'){
					// Returns context object from target page for Template7
					
					oPages[sPage].init(function(oVars){

						console.log(oVars);

						myApp.template7Data['page:' + sPage] = oVars;
						next(content);
					});
				} else {
					console.log('No init function');
					next(content); // Throws Uncaught SyntaxError: missing ) after argument list if page init method not exposed
				}

			} else {
				next(content);
			}
			
		} else {
			//hideLoading({id: 'onPageContainerBeforeChange'});
			msg_warn(sMsg);
		}
	});
}
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
