### ISSUE TITLE
page not resize after keyboard apear in some case

### ISSUE THREAD

**Issue by kkordinia** [framework7io/framework7#1529]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 16.0
* Platform and Target: CORDOVA, ANDROID

### What you did
when user focus on one input palaced in page-content and list-block and keyboard apeared, page not resize. but when user focus on prompt modal input page resized.

### Expected Behavior
resize page when user focus on an input palaced on page like prompt modal input

### Actual Behavior
in empty cordova app when user focus on input page resized.

**Comment by J05HI** [comment]
Can confirm the bug on my Galaxy S7 Android 7.0.1

**Comment by tinyCoder32** [comment]
On iPhone 4 screen when the keyboard appears from an input element of a Modal, it pushes the modal up and out of the screen.

**Comment by J05HI** [comment]
@tinyCoder32
Yeah on iOS it's working but not on Android. 
It's because Chrome doesn't scroll the page content div.

**Comment by tinyCoder32** [comment]
I don't consider it "working" in my case, part of the modal is out of the screen :(

**Comment by tazzkiller** [comment]
Same here on android, for now i use windowSoftInputMode with the value "adjustpan" on my manifest file, with this value the keyboard overlay the full content.

**Comment by J05HI** [comment]
@tazzkiller
In the app manifest?

**Comment by tazzkiller** [comment]
yes on your android manifest.xml. If you use Phonegap or Cordova, put this on your config.xml 

```
<platform name="android">
<preference name="android-manifest/application/activity[@android:name='MainActivity']/@android:windowSoftInputMode" value="adjustPan" />
</platform>
```

**Comment by J05HI** [comment]
@tazzkiller
Oh that's the Android manifest :(
I need a solution for web only

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
