### ISSUE TITLE
Back to home / page-inline +template7 + modal

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#1544]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.06.
* Platform and Target: CORDOVA 
 
What I need is :
To go back home (page index) when I press OK on the button modal.
Consider that I've opened at least **3 dynamic inline-page with template7**.

// THIS WORKS BUT TAKES ME TO THE LAST OPENED PAGE.
mainView.router.back();

 //THIS IS NOT WORKING AND WHAT I NEED
mainView.router.back({pageName:'index',ignoreCache: true, force: true});

@nolimits4web  why I can't  go back home? no errors in the console

```

/* ===== CHECKOUT  ===== */

$$(document).on('click', '.checkout-submit', function( e ) { 
   var form = myApp.formToData('#frm-checkout');

  if (parseInt(form.opt_forma_pago) != 1) { // NO ES MP
 
      myApp.modal({
            title: '¡Gracias!',
            text: 'Tu pedido ha quedado registrado.',
            buttons: [
                {
                    text: 'Aceptar',
                    onClick: function() {
                        // THIS WORKS AND TAKES ME TO THE LAST OPENED PAGE.
                        //mainView.router.back();
                        myApp.closeModal(); 
                       //THIS IS NOT WORKING AND I NEED IT
                        mainView.router.back({pageName:'index',ignoreCache: true, force: true});
                        },
                },
            ]
        });
   }
});

/* ===== CHECKOUT  ===== */
```
  
And this is the html ..
```

      <!-- Your main view, should have "view-main" class -->
      <div class="view view-main">

        <div class="pages navbar-fixed toolbar-fixed">


          <!-- ===========  page-index ============ !-->
            <div class="page page-index" data-page="index">

```

**Comment by valnub** [comment]
Hm, `mainView.router.back({pageName:'index',ignoreCache: true, force: true})` should work. Can you provide a runnable version of your code via http://codepen.io ?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
