### ISSUE TITLE
Broken back button behavior with inline pages

### ISSUE THREAD

**Issue by lanasta** [framework7io/framework7#1553]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0, April 10,2017 release
* Platform and Target: iOS, Android
* Live Link or JSFiddle/Codepen: 
http://framework7.io/examples/inline-pages/

### What you did
I was testing the back button functionality on the inline pages app example, since I was facing some problems with the back button with the app I'm currently working on where I don't always land on the expected page with multi-level pages. I discovered that the same problem could be found in[ the inline pages example app](http://framework7.io/examples/inline-pages/). 
Here are the following steps to re-create it:
1. Navigate to the About page
2. Go to the Services page by clicking on the blue link
3. Go to the About page by clicking on the blue link
4. Go to the Services page again by clicking on the blue link
5. Hit the back button until you land on the homepage.

### Expected Behavior
Land on the homepage with no problems, without seeing pages that are not in history. 

### Actual Behavior
First bug: You land on the Form page even though you never opened it. 
Second bug: When you land on the homepage, the black area is there (#1414)

**Comment by lanasta** [comment]
I logged the page object to the console and found a discrepancy. The page name value does not match the url, which I believe causes the first bug.

![screen shot 2017-05-11 at 3 39 25 pm](https://cloud.githubusercontent.com/assets/9773638/25968615/2e3a36b4-3660-11e7-8ac7-ef12105dbffc.png)

**Comment by DareDevil73** [comment]
Me too!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
