### ISSUE TITLE
DataTable Checkbox for "select all" should only select checkboxes in associated column

### ISSUE THREAD

**Issue by darrenjennings** [framework7io/Framework7#1562]
This is a:
* [x] bug

* Framework7 Version: 1.6.0
* Platform and Target: Web Chrome
* JSFiddle: https://jsfiddle.net/abhz80cz/2/

### Expected Behavior
Expect only select checkboxes in associated column.

### Actual Behavior
All checkboxes in data table are checked in every column.

**Comment by nolimits4web** [comment]
Fixed by #1706
