### ISSUE TITLE
[v2]

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/framework7#1579]
More/complete Kitchen Sink demos:

* [x] Popup
* [x] Popover
* [x] Actions Sheet
* [x] Sheet
* [x] Progressbar
* [x] Preloader
* [x] Badge
* [x] Layout Grid
* [x] Login Screen
* [x] Preloader Indicator
* [x] Searchbar
* [x] Messages + Messagebar
* [x] Calendar/Datepicker
* [x] Picker/Selector
* [x] Swiper
* [x] Photo Browser
* [x] Notifications
* [x] Autocomplete
* [x] Form Storage

**Comment by J05HI** [comment]
Sticky list group titles only work for iOS Safari :(
It's because others don't support the "position: sticky". 

![](http://i.imgur.com/R1eqhWe.png)

**Comment by J05HI** [comment]
@nolimits4web 
Would be great if you add toast messages too:


![](https://s-media-cache-ak0.pinimg.com/originals/07/49/a6/0749a60b614e574d2385b5a255784f81.gif)

**Comment by J05HI** [comment]
@nolimits4web 
Would be great to have a user help. 
Here some native examples:

![](http://i.imgur.com/139NgoO.gif)

![](http://i.imgur.com/43lH5q5.gif)

![](http://i.imgur.com/fz2exIQ.gif)

![](http://i.imgur.com/oF1CaSO.gif)

**Comment by J05HI** [comment]
@nolimits4web 
Would be great if you add this (something like action sheet but centered):

![](http://i.imgur.com/f5dky2Z.gif)

**Comment by mix3d** [comment]
@J05HI You should be able to do that already, with http://framework7.io/docs/modal.html#custom-modals
