### ISSUE TITLE
[v3] Keyboard Component

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/framework7#1580]

**Comment by D-Marc1** [comment]
It would be cool if it could scroll to the correct position, while also keeping the status bar fixed. If the page isn't long enough for it scroll up enough to position correctly, then extra padding would be added to the bottom of the page. Just my thoughts, because I feel like that's something the current plugins lack, and I think would be ideal behavior for most people.

**Comment by J05HI** [comment]
@D-Marc1 @nolimits4web
Yeah the current implementation is a bit annoying. 
Please add auto scroll :)

**Comment by identy** [comment]
ionic plugin keyboard ... handler

**Comment by J05HI** [comment]
@identy
We need it for web not Cordova

**Comment by identy** [comment]
It's the only way I can get the keyboard wakeup event or it's the only way I know. :(

**Comment by D-Marc1** [comment]
@identy For a messaging system, the current Cordova plugins are unacceptable as well. In all the plugins I've seen, I have the option of either settling for the gross shrinking webview or a keyboard that doesn't sync with the message bar smoothly. Pick your poison.

**Comment by murliatdure** [comment]
@nolimits4web seems to be we are mixing mobility and UI!

No problem if we transform journey towards Mobile Kit!
But Ionic, Cordova many platforms have their own scope and compatibility approaches to get such colutions and many of them are already available in the market.

May be we can focus more on design and component aspects and ratgher getting into hardware.

You can again share the dieas to plug the hooks and events to achieve it. Liked your 1.x Plugin where we created multiple cordova exposures used in many projects.

**Comment by maciej-izak** [comment]
@nolimits4web lack of custom keyboards in v2 is a real problem and the main reason why I can't use new version of framework...  framework7-plugin-keypad was really amazing plugin for Framework 7! Any news in the topic or plans?
