### ISSUE TITLE
[v2] Notifications Component

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/Framework7#1583]
* [x] Implement custom in-app notifications (like in v1)
* [ ] add wrapper around native https://github.com/phonegap/phonegap-plugin-push (@macdonst could probably help)

**Comment by peon501** [comment]
This should be high priority

**Comment by nolimits4web** [comment]
Depends on #1610

**Comment by D-Marc1** [comment]
It would be pretty cool to add the ability to swipe up to remove iOS notifications, similar to how you would natively.

**Comment by numberokta** [comment]
It would be better if open with slide down and close with slide up animation.
