### ISSUE TITLE
[v2] Data Table Component

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/framework7#1585]
* [x] Port from v1
* [ ] Add JS Interface
* [ ] Pagination

**Comment by krosoftware** [comment]
Please add "priority"columns  (or "autohide" or "Column toggle") feature like http://demos.jquerymobile.com/1.4.5/table-column-toggle/
Additional, paging + search if possible.

**Comment by xbarter** [comment]
please add fixed columns. espacially useful in reports

https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html

**Comment by kevinqqnj** [comment]
if you use f7-vue, here's a demo of f7-table with pagination, sortable, cell action: https://github.com/kevinqqnj/f7-table
