### ISSUE TITLE
[v2] Tabs Component

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/Framework7#1587]
* [x] Implement
* [x] Routable:
  * [x] Switch Tabs by routed links clicks
  * [x] Update Router & Browser history
  * [x] Load routable tab by URL, HTMLElement, content, template, component
  * [x] Show specified Tab on Tabbed page load
  * [x] Emit some additional event when routable Tab content has been added `tabAttached`
  * [x] Delete routable Tab content when switching it off
  * [x] Routable Swipeable tabs
* [x] Animated
* [x] Swipeable (Depends on #1593)

**Comment by J05HI** [comment]
Can you please add the auto scroll tabs feature:

![ezgif-3-4fa01ce23b](https://user-images.githubusercontent.com/16399787/27508749-53dfbd72-58ec-11e7-9264-695927e8699e.gif)
