### ISSUE TITLE
[v2] Calendar Component

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/Framework7#1595]

**Comment by kkordinia** [comment]
please support Jalali calendar in Calendar Component using [jdate](https://github.com/tahajahangir/jdate)

**Comment by J05HI** [comment]
@nolimits4web 
Please add dynamic adding of calendar event if the calendar is already initialized

**Comment by J05HI** [comment]
What about adding this schedule view:
![](http://i.imgur.com/Pk8sgFf.png)

**Comment by nolimits4web** [comment]
@J05HI This is the Timeline component

**Comment by J05HI** [comment]
@nolimits4web 
Okay thanks, then I'll use this :)

**Comment by J05HI** [comment]
@nolimits4web 
Now another question:
Am I able to combine it with the virtual list and infinite scroll?
