### ISSUE TITLE
Blurred (Frosted glass) effect on navbar/toolbar

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/framework7#16]
This is a killer feature of iOS 7 ui, so we definitely need it:) 
Any thoughts on how realize it, perfectly with CSS only. 

I discovered pure CSS solution using CSS regions, it works perfect on desktop Safari, but super slow and buggy on iOS, so we need something different. 

It is also possible do it with JS by duplicating content, but it is not an option because we will have a lot problems when we need to update content there (in duplicated layers)

**Comment by ZanderBrown** [comment]
`backdrop-filter: blur(10px);` should do on iOS devices (no support in Chrome or Firefox)

**Comment by mkrikson** [comment]
Yeah only supported by safari and iOS safari: http://caniuse.com/css-backdrop-filter

But this enough for iOS theme

**Comment by Dielz98** [comment]
+1 for Frosted glass
