### ISSUE TITLE
How to turn off the bounces effect?

### ISSUE THREAD

**Issue by binggg** [framework7io/framework7#161]
First,I want to thank for the author of f7 framework.
I want to know how to turn off the bounces effect. We use the webpage made by f7 in the ios app webview. Our programmer can't use the native pull to refresh. 
I hope you can help me,thanks.

**Comment by scriptPilot** [comment]
Maybe this helps?

http://stackoverflow.com/questions/9651215/how-to-disable-bouncing-in-html5-fullscreen-iphone-app

**Comment by scriptPilot** [comment]
This works well with current Framework7 version to eliminate the bounce effect:
- 1. Download https://github.com/lazd/iNoBounce/blob/master/inobounce.min.js
- 2. Include script `<script type="text/javascript" src="js/inobounce.min.js"></script>`
- 3. Add css to .views container
```
.views {
  height: 100%;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
}
```

**Comment by projetoarduino** [comment]
Hi the bounce effect solution above is not 100%


I've created other projects with simple html, and this effect does not appear, I'm using cordova and framework 7 in the latest version.

On android and ios 8 this effect does not appear

**Comment by dgr8akki** [comment]
You can try:
html {
    overflow: hidden;
}
