### ISSUE TITLE
[v2] Router

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/framework7#1614]
Load pages by:
* [x] url (xhr and load)
* [x] HTMLElement
* [x] plain content string
* [x] template (t7)
* [x] template url (xhr, parse/compile template and load)
* [x] page name (inline pages)
* [x] component
* [x] component url (xhr, parse/compile component and load)

Extend with routable:
* [x] Tabs
* [x] Popup
* [x] Sheet
* [x] Popover
* [x] Actions Sheet
* [x] Login Screen
* [ ] Panels
* [x] Photo Browser

Additional features:
* [x] Support for none separated iOS dynamic navbar
* [x] Use js animation for page/navbar transitions
* [x] Restore previous page scroll top when going back
* [x] 404 routes

**Comment by ZanderBrown** [comment]
I'd say panels do need to interact with push state in some way to work with Android back button

**Comment by snakeman21** [comment]
Allowing Template7 on index page without having to refresh the content would be a wonderful feature to add if possible. This is especially helpful when you are adding a cross platform navbar, which creates "garbage" in the code when you refresh the page. Would be awesome to just be able to do Template7 on index with it automagically working.

**Comment by nolimits4web** [comment]
@snakeman21 it is already possible in v2 router

**Comment by snakeman21** [comment]
Didn't know that. As always, you're the man the Vladimir 👍! I'm very excited for this feature!

**Comment by J05HI** [comment]
@ZanderBrown @nolimits4web 
Yeah same for popups, popovers and that stuff (optionally defined in the settings)

**Comment by J05HI** [comment]
@nolimits4web 
Can you please add that all previous pages hold their scroll position if you go back?

**Comment by ZanderBrown** [comment]
Tabs shouldn't pushState because tabs don't work like that in android or the material spec but otherwise yes to popups, popovers & panels

**Comment by J05HI** [comment]
@ZanderBrown 
Yeah that's true but optionally it's great to have that feature if you need it.

**Comment by J05HI** [comment]
Reference to morph to page: https://github.com/nolimits4web/Framework7/issues/1582#issuecomment-312844086

**Comment by seme1** [comment]
Would be nice if following issue was considered, too.
https://github.com/nolimits4web/Framework7/issues/1694

**Comment by lailton** [comment]
@nolimits4web,

Please check this one #1815

**Comment by var-zhangbao** [comment]
Does anyone know how to load framework7+Vue routing on demand? Because my project front page is loaded too much resources, rendering rendering to the browser is particularly slow. If you have any trouble, please contact me. 1726470094@qq.com
