### ISSUE TITLE
[v2] Indexed List Component

### ISSUE THREAD

**Issue by nolimits4web** [framework7io/framework7#1674]
Consider adding Indexed List plugin to the core

**Comment by krisred** [comment]
This would be awesome addition - much needed.

**Comment by krisred** [comment]
Hello Vlad,
Could you please consider adding this feature, need for the project to move from v1 to v2. Also will the Numpad/Calculator plugin work in v2. If not, could you please update this as well

Thank you!
Kris

**Comment by krisred** [comment]
Hi Vladimir,
Could you please consider finishing Indexed List Component in v2 . 
Thanks,
Kris

**Comment by nolimits4web** [comment]
@krisred will be next release or release after the next one ;)

**Comment by nolimits4web** [comment]
Ok, it is added. Will be in update tomorrow

**Comment by krisred** [comment]
Thank you!
