### ISSUE TITLE
Open/close panel breaks when open&close the panel frequently

### ISSUE THREAD

**Issue by Luluno01** [framework7io/framework7#1676]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4.
* Platform and Target: Both Chrome@Windows8.1 and Crosswalk@Android4.4.4.

### What you did
I wrote a toggleSideNav() js function:
```
function toggleSideNav() {
  if($$("body").hasClass("with-panel-left-cover")) {
    app.closePanel();
    console.log("Panel closed.");
  } else {
    app.openPanel("left");
    console.log("Panel opened.");
  }
}
```

**On Windows:**

I opened the Developer Tools and call the toggleSideNav() function again and again as fast as possible.

**On Android:**

I bind the toggleSideNav() function to the Menu button and press the menu button again and again as fast as possible.

### Expected Behavior
The panel opens and close as normal.

### Actual Behavior
After several calls to that js function the app seemed to stuck, it just couldn't response to any user operations.
I opened the Developer Tools, in Elements tab I found this problem was caused directly by not removing the ```panel-overlay``` element's attribute ```style="display: block;"``` and not setting the ```app.ML.allowPanelOpen``` to ```true``` after a ```app.closePanel``` call (The panel was hidden but the user couldn't do anything with the ```panel-overlay``` that block the screen ops). But I have no idea about how to fix this.

### Why I test this
I know this issue would be kinda stupid since almost no one will open and close the panel that frequently. But still, I believe there must be someone like me who loves playing with the panel in my book. XDDDD

**Comment by Alvaro237** [comment]
Hi,

I have a similar code:

`function menuButton() {
    if($$('body').hasClass('with-panel-left-reveal')) {
        myApp.closePanel();
    }  else {
        myApp.openPanel('left');
    }
}`

Mine works perfectly.

Try instead of 'with-panel-left-cover' this 'with-panel-left-reveal'.

Regards.

**Comment by Luluno01** [comment]
@Alvaro237 Thx bro, but I didn't see the differences between your code and mine in process. I've tried your code, just as mine, they worked fine when I open & close the panel **as normal**, but once I type ```menuButton();menuButton();menuButton();menuButton();menuButton();menuButton(); ...``` or ```toggleSideNav();toggleSideNav();toggleSideNav(); ...``` in the console and launch them, the problem arises.
Although people would seldom (or never) play with the panel (keep opening and closing the panel in a **very short** time) like me but I'm afraid of this problem happening if the users' devices are of poor performance.
Still, thank you all the same!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
