### ISSUE TITLE
[v2] DateTime Picker

### ISSUE THREAD

**Issue by D-Marc1** [framework7io/framework7#1686]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Of course you can already do `<input type="datetime-local">` or something like that, but sometimes you need more control. How about something like [this](https://ionicframework.com/docs/api/components/datetime/DateTime/)?

**Comment by J05HI** [comment]
Would be great!

**Comment by nolimits4web** [comment]
Closing as the Picker component allows to do that

**Comment by J05HI** [comment]
@nolimits4web
Really?
I haven't seen a clock picker like [this](https://materializecss.com/pickers.html) in Framework7 yet.

**Comment by nolimits4web** [comment]
@J05HI original post refers to different kind of pickers, e.g. like Picker in F7

**Comment by J05HI** [comment]
Yeah but I think he means the kind of time picker I sent.

**Comment by D-Marc1** [comment]
Ya @J05HI is right. That's what I meant. While you can do a lot of the functionality in the current picker, as shown in the Framework7 docs, it requires a fairly large amount of code needed for it. I personally believe it could be improved.
