### ISSUE TITLE
Swiping back broken in iOS 11 beta 4

### ISSUE THREAD

**Issue by JJJ** [framework7io/framework7#1698]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Latest
* Platform and Target: iOS, web
* Live Link or JSFiddle/Codepen: None

### What you did
Went to look at the latest example app on the home page, noticed I could no longer swipe backwards in iOS 11 beta 4. Probably a bug in the beta, but alerting here in case it’s some new iOS behavior. 

### Expected Behavior
Swiping back (on the left side of the screen, dragging right) to work as it always has.

### Actual Behavior
Safari seems to be overloading the swipe action, attempting to go back within its own known history. Both seem to be trying to work though, as the animation jitters to indicate f7 is responding.

**Comment by JJJ** [comment]
Screen recording of current iOS 11 beta 4 behavior. I’ll be submitting a but report up to Apple soon also.

https://jjj.blog/baa973b2-ccb0-400e-b8a1-c6b13ba2bd22/

**Comment by ytbryan** [comment]
I'm using iOS 11 Beta 4 on my iPhone 6. The swipe backwards is working fine.

**Comment by JJJ** [comment]
This is only an issue when switching from a static page to an F7 app in the same open tab. Maybe this isn’t a supported state. If so, accept my apologies for the noise and feel free to close this issue. 👌

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by JJJ** [comment]
May have been an issue with Safari itself confusing the left-side drag-back, with the f7 drag back.

Oddly, I don’t think I had that issue (in the same way) with previous versions.

This will not be an issue on web apps or apps in a containerized view, so OK to close IMO. 👍
