### ISSUE TITLE
[v2] Keyboard hides inputs on Android and Windows Phones

### ISSUE THREAD

**Issue by J05HI** [framework7io/framework7#1703]
@nolimits4web

On iOS it works.

Sample here:
![ezgif-4-bd8601e20e](https://user-images.githubusercontent.com/16399787/28983810-9fee09e6-795b-11e7-9533-44db3cb79a12.gif)

**Comment by mix3d** [comment]
Not sure if it helps, but it appears that the root cause is a delay in the way android opens the keyboard; there is a significant delay before the document is resized for the keyboard. 

Attaching the following related issues from over the years.
#1572 
#1153 
#500

**Comment by J05HI** [comment]
Works with v2 now :)

**Comment by josteph** [comment]
@J05HI Sorry for asking a closed and it seems you have solution as why the keyboard doesn't overlap input field anymore..

Basically I have:
1. `android:windowSoftInputMode="adjustPan"`
2. `cordova-plugin-statusbar` installed
3. App param:
```
input: {
	scrollIntoViewOnFocus: true,
	scrollIntoViewAlways: true,
	scrollIntoViewCentered: true
},
```
4. `<preference name="Fullscreen" value="false" />` (Android)

But the keyboard still just overlaps the input field. I can use workaround with on focus on the input event, but trying to get this clean through framework7 itself. Did I miss something to make the `scrollIntoViewOnFocus` able to work?

Using: Framework7 v3.4.0

#500
