### ISSUE TITLE
[v2] Things to improve

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#1738]
Hi Vladimir, I sent you here some things to improve. I have to copy them from project to project and some maybe would be useful for other people. Maybe you can add them to v2

Preloader
=========
In material.css is missing the background-image of .preloader 
In ios.css it has it.

Side Panels + Infinite scroll + pull to refresh
===============================
It would be useful, if we can use this components to the side panels 
We use it for  notification's panel

Handler for Backbutton in Android
==========================
Maybe you could add this function to include in onDeviceready call.
If you don't use push state = true and you're in index page, you want to exit the app when the user press backbutton.
This function handles that:
```

onBackButton: function (e) { 

          if(mainView.activePage.name == "index" ){ 
              e.preventDefault(); 

              myApp.confirm("Te gustar&iacute;a cerrar la aplicación?", 
                config.app_name,
                function () {
                            navigator.app.clearHistory(); 
                            if (navigator.app && navigator.app.exitApp) {
                              navigator.app.exitApp();
                            } else if (navigator.device && navigator.device.exitApp) {
                              navigator.device.exitApp();
                            }
                },
                function () {
                  //myApp.alert('You clicked Cancel button');
                }
              );
          }else{ 
             mainView.router.back();
          } 
    },

```

Back HOME
===========
If you open many pages and you want in the last one to goback to home and reset the history, maybe you could add this function.

```
 index_forzar_back : function () {

                    $$('.navbar-on-left').remove(); 
                    $$('.page-on-left').remove(); 
                  
                    // RESET THE HISTORY
                    var index   = mainView.history[0];
                    var actual  = mainView.activePage.url;
                    mainView.history = [];
 
                   // ADD THE ACTUAL
                    mainView.history.push(index);
                    mainView.history.push( actual );

                   // GO BACK
                    mainView.router.back({ignoreCache:true,force:true});
        },


```
INFINITE SCROLL - PAGE COUNT LOADING
===================================
It happens that if you have multiples pages open and you want to keep in memory the pages that you look at each one, you need to have a var like this
```
var infinitscroll = {
   esta_cargando : false,
   paginas:        [],    // aca guarda la pagina y por que nro va, para evitar los historys
                          // ej:  ["index"] = 1 
                          //     infinitscroll.paginas[ "page-name" ] = XX
}

```
So when you enter  into the on('infinite you can handle the page that you've fetched  last time.
Maybe this could be added to the myApp var

```
    // INFINITE SCROLL 

    $$('.infinite-scroll').on('infinite', function () {
 
      // Exit, if loading in progress
      if (infinitscroll.esta_cargando)  return;
     
      // Set loading flag
      infinitscroll.esta_cargando = true;

      // Emulate 1s loading
      setTimeout(function () {

            infinitscroll.esta_cargando = true;
            $$(".page-name .infinite-scroll-preloader").show();

            load_data( function(){
                        infinitscroll.esta_cargando = false;
                       infinitscroll.paginas[ helpers.infinite_scroll_page_name() ]++; 

                       $$(".page-name .infinite-scroll-preloader").hide();
           });

        }, 1000);
    }); 
     

```
 And for pull-to-refresh method, you should initialize that var to 0
`infinitscroll.paginas[ helpers.infinite_scroll_page_name() ] = 0 ; `

History
=========
There are some cases generally when I use "reload:true"
```
mainView.router.load({
                        url: url,
                        reload: reload,

```
 That mainView.history has -1 items or has a page called "#".
Always should have in history as 0 the index. 

Optional fields (UX)
==============
As UX resercher's suggest is better for Users to mark wich inputs are optionals insted the required ones.
This is how we applied that to our apps:

```
    // CAMPOS OPCIONALES

    $('.item-input').each(function()
    {
        if ( ! $(this).find('input, textarea, select').attr('required') )
        {
            $(this).append('<span class="opcional">Opcional</span>');
        }
    });

```
and the CSS:

```
/* campos opcionales */

.opcional {
	color: #999;
	font-size: 11px;
	position: absolute;
	top: 0px;/*4px*/ right: 4px;
}
.focus-state .opcional,
.not-empty-state .opcional { display: none }

```

Hide / Show
=========
If you use .show() of F7, it add a "display:block" to the html element and cause errors in designs, instead wich Jquery does. In my case, I always have to use the Jquery method .show() to avoid that problem.

Autocomplete + tabs
=================
If you use dropdown autocomplete in a page with tabs, when you click on an option, it never fire the "onchange" event. You have to use in this case the "popup" autocomplete.

Autocomplete openIn: 'popup',
======================
When you use autocomplete in mode: openIn: 'popup' and you click on the input, it opens the new window to search; But the new input box to search do not have the focus, and 
you have to add this block of code, in the autocomplete , to get it. Maybe this could be declare by default in the autocomplete.

```
             onOpen(autocomplete) {
                  setTimeout(function() {
                    $$(autocomplete.page).find("input[type=search]").focus();
                  }, 60);
                },  
```

**Comment by J05HI** [comment]
Wow great list! 
I hope @nolimits4web can consider this.

**Comment by nolimits4web** [comment]
Thanks guys, I will consider it of course. Just trying to release first beta this week. And then I’ll go deeper for improvements

**Comment by J05HI** [comment]
@nolimits4web 
Amazing!!!!!! 
Thank you soooo much for your hard work!!!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
