### ISSUE TITLE
[v3] Local Forage Support

### ISSUE THREAD

**Issue by nigelbpeck** [framework7io/framework7#1752]
Just a request, but if there's any chance of having support for [Local Forage](https://github.com/localForage/localForage) as an alternative to Local Storage for [storing forms](https://framework7.io/docs/form-storage.html), it would be a nice feature, and not too hard to implement, I think. We can look at submitting a PR to V2 perhaps, but wanted to raise an issue for it to make a start on the process.

**Comment by nolimits4web** [comment]
Yes, like the idea. But i will need probably to create kind of storage interface in v2 and then we can extended it with LocalForage

**Comment by nigelbpeck** [comment]
Great, sounds good.
