### ISSUE TITLE
[v2] Ability for Picker to Submit Different Value to Server than what is Shown

### ISSUE THREAD

**Issue by D-Marc1** [framework7io/framework7#1762]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

In a regular `<select>` dropdown menu, you have the ability to do `<option value="server_val">Shown Value</option>`, so that the value inserted into the database is different than what is shown. Could something like this be integrated into pickers?

**Comment by D-Marc1** [comment]
@nolimits4web Any chance this can be added as a feature request?

**Comment by D-Marc1** [comment]
@nolimits4web any chance this feature request could be considered?

**Comment by D-Marc1** [comment]
@nolimits4web or @ZanderBrown any chance this feature request could be labeled?

**Comment by ZanderBrown** [comment]
Is this what you where looking for?

> ## Column Parameters
> When we configure Picker we need to pass cols parameter. It is an array where each item is an object with column parameters:

  Parameter | Type | Default | Description
  -- | -- | -- | --
  values | array |   | Array with string columns values
  displayValues | array |   | Array with string columns values that will be displayed in Picker. If not specified, it will display values from valuesparameter

[See docs](http://framework7.io/docs/picker.html)

**Comment by D-Marc1** [comment]
Thanks for the response. If I'm not mistaken, doesn't `displayValues` simply make the "picked" value in the input box different than the one in wheel selector? I'm looking for something that differentiates what the user sees from the server value.

**Comment by ZanderBrown** [comment]
As far as I'm aware it works as

```
If displayValues and displayValues[I]
<option value="values[I]">displayValues[I]</option>
Else
<option value="values[I]">values[I]</option>
```

Try it

**Comment by D-Marc1** [comment]
Yes, that works, and you are correct. However, it still doesn't account for my scenario. I want the ability to be able to provide a value to my AJAX requests that is different from what the user sees. By default, just using `values` makes the value on both the "picked" value and "wheel" value the same. Setting `displayValues` differentiates the "picked" value from the "wheel value".

Both of these just deal with what the user sees, but don't let you modify the data of the AJAX data. Now consider this scenario. Let's say I'm scrolling through events I want to attend on the picker. The event could be "Cool Event". The problem is that what if my database table stores this as its numeric event id, like 874. I would like the option to store values that are not seen by the UI at all, and only the server would. This is the only reason why I can't use pickers ever and have to use a regular select instead. I think a lot of people would benefit from this, as I believe my use-case is fairly common.

**Comment by nolimits4web** [comment]
It is not really possible to do on automate name, just rename the variable to what you need before sending it via XHR

**Comment by D-Marc1** [comment]
Couldn't this be added as an option called `serverVal`, which would become the input value if specified, while the value the user sees would be something like `data-shown-val` to differentiate between the server value and UI value?

It would really be shame if you don't want to add this, because it would require quite a bit of extra work to use the F7 picker for my use case, which is fairly common. Selects are essentially the native version of pickers and they have `<option value="server_val">Shown Value</option>`. Similar to pretty much any native feature, I would prefer to use the F7 picker, as it's far more versatile. I would appreciate if this could at least be considered.
