### ISSUE TITLE
view.activePage is not updated

### ISSUE THREAD

**Issue by anrikun** [framework7io/framework7#1771]
This is a bug.
* Framework7 Version: master
* Platform and Target: any

I'm using domCache.
I have a menu in left panel that let me display pages without animation nor history. Here's one of the links:
<a href="#my_page_name" class="item-link close-panel" data-reload="true">[...]</a>

The first time pages are displayed it works.
But when going back to a same page as before, nothing happens and app eventually breaks.

This is because view.activePage is not updated in that case.
view.activePage seems to be updated when:
- a new page has just been initialized: see app.pageInitCallback
- before a page animation: see app.pageAnimCallback()
But not when
- an already initialized page is loaded from cache without any animation. 

The faulty part seems to be:
```javascript
            if (pageContainer.f7PageInitialized && ((view && view.params.domCache) || (!view && $(pageContainer).parents('.popup, .popover, .login-screen, .modal, .actions-modal, .picker-modal').length > 0))) {
                // Reinit Page
                app.reinitPage(pageContainer);
        
                // Callbacks
                app.pluginHook('pageReinit', pageData);
                if (app.params.onPageReinit) app.params.onPageReinit(app, pageData);
                app.triggerPageCallbacks('reinit', pageData.name, pageData);
                $(pageData.container).trigger('pageReinit page:reinit', {page: pageData});
                return;
            }
            pageContainer.f7PageInitialized = true;
        
            // Store pagedata in page
            pageContainer.f7PageData = pageData;
        
            // Update View's activePage
            if (view && !params.preloadOnly && !params.reloadPrevious) {
                // Add data-page on view
                $(view.container).attr('data-page', pageData.name);
                // Update View active page data
                view.activePage = pageData;
            }
```
view's active page is not updated before the return.
A quick fix is to duplicate the "Update View's activePage" part after "app.reinitPage(pageContainer);"

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
