### ISSUE TITLE
[v2] Duplicate functions in distribution file

### ISSUE THREAD

**Issue by blikblum** [framework7io/Framework7#1784]
This is a (multiple allowed):
* [x] enhancement

* Framework7 Version: beta 3
* Platform and Target: web
* Live Link or JSFiddle/Codepen: NA

Some functions are being duplicated (from Dom7 and own code base) in the generated dist file:

`parseUrlQuery`, `getTranslate`, `request(cancel)AnimationFrame`

**Comment by nolimits4web** [comment]
I know there are, i will remove these methods from Dom7 library with next release making it DOM-manipulation only.

**Comment by nolimits4web** [comment]
Was fixed in latest betas
