### ISSUE TITLE
Possible issue in parseNewPage() function in the router component

### ISSUE THREAD

**Issue by anatolykazantsev** [framework7io/framework7#1788]
The issue is in the following lines: https://github.com/nolimits4web/Framework7/blob/d575d3972954c74a8e3d58e969fbc910dcc790ff/src/js/framework7/router.js#L807-L809

- First: the condition as is doesn't make sense because:
  `(typeof content === 'string') || (url && (typeof content === 'string'))`
  is simply equal to
  `(typeof content === 'string')`.
  So it doesn't clear what was the initial intention of the author.
- Second: it doesn't match what's happening when the condition is true, i.e. the condition is about `content` variable, but action is about `t7_rendered.content` variable. Those variables can be equal or can have different values.

In my usage case this function is called when Framework7 pre-loads a previous page because I have enabled swipe-back. I already have correct content of the previous page cached in `view.contentCache`, but because I use Template7 rendering for pages (i.e. `app.params.template7Pages` is `true`) Framework7 also renders the page content in `app.router._back()` method.

Framework7 doesn't ensure rendered content and cached content is always same, so there will be cases where they are different and because of the original issue in `parseNewPage()` function it produces unexpected results, i.e. it uses rendered content when cached content exists, so it cancels logic of following lines from `app.router._back()` function: https://github.com/nolimits4web/Framework7/blob/d575d3972954c74a8e3d58e969fbc910dcc790ff/src/js/framework7/router.js#L739-L741

**Comment by anatolykazantsev** [comment]
I did git blame and it shows `app.router.temporaryDom.innerHTML = t7_rendered.content;` was introduced at https://github.com/nolimits4web/Framework7/commit/2419dfea6fa3927ca31c417fa4a48809756b9bbf#diff-c9bf81348e383fe276f7b145b58c76d5R625

The change looks ok, but it's valid only for the case when there's only supplied content or rendered content in router's "back" functions.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
