### ISSUE TITLE
[v2] Sticky list group titles bug

### ISSUE THREAD

**Issue by J05HI** [framework7io/Framework7#1791]
@nolimits4web
The problem that the sticky list group titles only work for iOS Safari exists again :(
On other devices its hidden behind the navbar. Please fix it again.

![](http://i.imgur.com/R1eqhWe.png)   

If I remove the navbar it's visible:
![](http://i.imgur.com/dP0VJVM.png)

**Comment by nolimits4web** [comment]
The problem is in Chrome (with wrong implementation), with latest Chrome updates it is impossible to detect falsy sticky support.  It works fine in other browsers like Safari and FireFox. So the issue should be filled for Chromium

**Comment by J05HI** [comment]
Okay that's pity 😔

**Comment by J05HI** [comment]
@nolimits4web 
It was fixed with [https://github.com/framework7io/Framework7/commit/0ab82d7453dd772ed034640735760a371a5d57a7](https://github.com/framework7io/Framework7/commit/0ab82d7453dd772ed034640735760a371a5d57a7).
Why have you removed the fix again?
