### ISSUE TITLE
[v2] Notifications: Some graphic inconsistencies compared to version 1.6.5

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/Framework7#1797]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.0 beta 7

Graphic inconsistencies of Notifications concern the position of the closing button and the right padding of the text.

Some occur in vertical orientation, others in horizontal orientation.

For example, this occurs in "Default notification"

Version 2.0.0 beta 7:

![framework7-v2b7](https://user-images.githubusercontent.com/1197819/30473931-48368832-9a02-11e7-96df-2e018a626f9d.png)

Version 1.6.5:

![framework7-v165](https://user-images.githubusercontent.com/1197819/30473939-4f4b5e7c-9a02-11e7-8d0b-6fb99aa3b0b8.png)

I've tested that adding the following CSS rules in the Inspector Web of Safari improves the situation:

`.ios .notifications li.notification-item .item-inner {
	width: 100%;
}`

`.ios .notifications .item-text {
	padding-right: 15px;
}`

**Comment by nolimits4web** [comment]
This notifications is just a quick port from v1, they will be reworked later

**Comment by nolimits4web** [comment]
And there is a task for that https://github.com/framework7io/Framework7/issues/1583
