### ISSUE TITLE
The "onLazy" trigger issue

### ISSUE THREAD

**Issue by bau720123** [framework7io/Framework7#1799]
This is a Bug

* Framework7 Version: 1.6.5
* Platform and Target: Windows 7 Google Chrome 61.0.3163.91 64 bits
* Live Link or JSFiddle/Codepen: https://www.littlebau.com/lazytest.html

### What you did
Test the LazyLoad trigger behavior

### Expected Behavior
The function onLazyLoaded and onLazyError should only trigger 1 time

### Actual Behavior
The function onLazyLoaded and onLazyError trigger 2 times（But the Picture 1 is Expected）

### Screenshot
![01](https://user-images.githubusercontent.com/5110085/30537426-356620fe-9c9c-11e7-8bf7-f934b817f99d.jpg)
![02](https://user-images.githubusercontent.com/5110085/30537432-3b13abde-9c9c-11e7-833c-dbe887957c4d.jpg)
![03](https://user-images.githubusercontent.com/5110085/30537438-40d5c020-9c9c-11e7-8d07-4086d75a2021.jpg)
![04](https://user-images.githubusercontent.com/5110085/30537445-46764518-9c9c-11e7-8bfb-6626942c210c.jpg)

**Comment by bau720123** [comment]
no any reply ?

**Comment by nolimits4web** [comment]
It is because of these exact images (this server doesn't use caching), use own images and will be fine

**Comment by bau720123** [comment]
hi @nolimits4web 
as same as before...
https://www.littlebau.com/lazytest.html
please use CTRL+F5 and you will see the same result
