### ISSUE TITLE
f7 react router.back() cause page stay in unmounted state 

### ISSUE THREAD

**Issue by flowerchaton** [framework7io/Framework7#1800]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 0.9.2.
* Platform and Target: windows and meteor

I try to route back to home page after series action
Main.jsx
```
<Page noPageContent navbarFixed toolbarFixed>
             
                <Navbar title="My App"></Navbar>
                <Tabs swipeable>
                    <Tab active id="home"><Home></Home></Tab>
                    <Tab id="learn"><Learn></Learn></Tab>
                    <Tab id="profile"><Profile></Profile></Tab>
                </Tabs>

                <Toolbar tabbar labels>
                    <Link active  iconF7="home" text="Home" tabLink="#home"></Link>
                    <Link iconF7="book" text="Learn" tabLink="#learn"></Link>
                    <Link iconF7="person" text="Profile" tabLink="#profile"></Link>
                </Toolbar>
</Page>
```
Learn.jsx > Result.jsx
```
...
<Button onClick={ f7.mainView.router.back({ url: '/main/', reload: true, force: true })}>go to home page</Button>
```
after click this it will load Main.jsx, but the toolbar icons didn't work anymore
I tried to write  onclick on Link in the toolbar to set the active manually, then  i got this
```
Warning: setState(...): Can only update a mounted or mounting component
```
is there anyone knows how to solve this problem?

**Comment by nolimits4web** [comment]
This is opened in wrong repository. I believe should be at https://github.com/bencompton/framework7-react. Anyway, router will be highly improved with v2 version
