### ISSUE TITLE
[v2] Missed feature

### ISSUE THREAD

**Issue by lailton** [framework7io/Framework7#1801]
I am going to start to use v2 but I not found this methods:

Framework7:

addView
mainView.router.loadContent( HTML );

**Comment by nolimits4web** [comment]
addView -> app.views.create(...)

As for router i recommend you to read this https://blog.framework7.io/mastering-v2-router-958ea2dbd24f

**Comment by lailton** [comment]
Vladimir,

Can you tell me how to do it for example in the v2.

<div class="content-block"><a href="#" onclick="test()" class="button button-raised">OpenPage</a></div>

function test(){
 var cPage = `
      <div class="page">
        <div class="page-content">
          <div class="block">
            <p>This page created dynamically`+ (new Date()).toString() + `</p>
            <div class="content-block"><a href="#" class="link back button button-raised">About Framework7</a></div>
          </div>
        </div>
      </div>`;
 mainView.router.loadContent(cPage);
}

Note:
All pages in my app is dynamic so I can't create a router object in the first time with all the pages.

**Comment by minimallinux** [comment]
Hi does anyone know how we can use the code in the tutorial " manage both
themes from one index.html" but without using template7 ie just the pages
in the /dist folder (1.65) or alternatively how to use the template 7 tags
in those files so we can follow the tut ? Thanks

**Comment by jcroucher** [comment]
It is not ideal, but I am using

```
var mainView = app.views.create('.view-main');

app.on('formAjaxSuccess', function (formEl, data, xhr) {
	mainView.$el.html(xhr.response);
});
```

This whole router system in F7 V2 has thrown out everything about how I have developed apps with it. It's quite frustrating.
