### ISSUE TITLE
[V2] HTML Alert Dialog

### ISSUE THREAD

**Issue by danish1023** [framework7io/Framework7#1803]
![screenshot_13](https://user-images.githubusercontent.com/6543485/30632488-e9322712-9e05-11e7-9eee-92de07cd2ed5.png)

@nolimits4web
Can you please add html alert dialog in v2?

**Comment by J05HI** [comment]
@nolimits4web
Yeah would be great!

**Comment by nolimits4web** [comment]
It is there https://github.com/framework7io/Framework7/blob/v2/kitchen-sink/pages/dialog.html
