### ISSUE TITLE
[V3] Rating Component

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#1805]
@nolimits4web
Can you please add rating component like star rating, heart rating based on icons in v2?

**Comment by J05HI** [comment]
Could be useful! +1

**Comment by nolimits4web** [comment]
Well, don't think it worths of it to implement separate component for something like:
```
To display 3/5 rating
<i class="f7-icons">star_fill</i>
<i class="f7-icons">star_fill</i>
<i class="f7-icons">star_fill</i>
<i class="f7-icons">star</i>
<i class="f7-icons">star</i>
```

**Comment by J05HI** [comment]
@nolimits4web
Maby add it to the kitchen sink :)

**Comment by danish1023** [comment]
@nolimits4web  Please visit http://vuematerial.io/#/components/rating-bar

A smooth rating component is there.
