### ISSUE TITLE
Adding a middleware to rewrite URL of XHR requests

### ISSUE THREAD

**Issue by seme1** [framework7io/Framework7#1812]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I need to capture all URL (before being loaded) and rewrite them in order to fix an issue I have with cordova plugin. The issue (and possible fix) is described here:
https://github.com/nordnet/cordova-hot-code-push/issues/264#issuecomment-330997979

What's the best way for achieving the above ? Perhaps by adding a middleware for achieving the above ? If so, how ?
The format of the URLs will change from something like this file://myurl/page.html to http:// localhost:8080/application/binary/APP-ID/myurl/page.html (This is just an example, exact format is in the issue)

**Comment by nolimits4web** [comment]
Well, i know what you mean, it is not possible in v1, but now possible in v2 by using `beforeCreate` callback:
```
app.request.setup({
  beforeCreate(options) {
    options.url = 'http://google.com';
  }
})
```

**Comment by seme1** [comment]
I'd love to upgrade to v2, but it seems like the process won't be with as simple previous upgrades where only F7 file replacements were necessary. 

Do you intend to publish a guide for how the upgrade process can be achieved with as little steps as possible?

**Comment by seme1** [comment]
@nolimits4web Any chance for exposing a similar method in v1 so that I can use it for now in my application ?

**Comment by nolimits4web** [comment]
Upgrading process depends on how big and complex your app. Yes, with the v2 stable release i'll update docs with upgrading guides.

As for v1, i just pushed https://github.com/framework7io/Framework7/commit/1aaa88c8b089fc9f48c2cfdea624e47513aa91fd commit that adds same `beforeSend` callback so you can modify passed options properties

**Comment by seme1** [comment]
Thanks very much. 
There are now several new versions of Framework7 and it's really difficult for new comers (or those wishing to upgrade) to make the right choice. [v1.65, v2.0, v.react, v.vue].

I feel now that the increasing fragmentation will also increase the load on you since you are the main contributor and you will have very difficult time maintaining the different versions in the near future. This also makes me worried about the project future maintainability. 

I also don't entirely understand the main reason for fully restructuring the app with V2, especially since it seemed only few months ago that your focus was on the vue version of F7 !!
