### ISSUE TITLE
[V3] Gauge Component

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#1813]
@nolimits4web  

I am using http://justgage.com/ for gauge meter. It will be helpful if you add this component in next version.

**Comment by J05HI** [comment]
@danish1023
Take a look here [https://github.com/framework7io/Framework7/issues/1661](https://github.com/framework7io/Framework7/issues/1661)

**Comment by nolimits4web** [comment]
What stops you from keep using that http://justgage.com/ ?:)

**Comment by danish1023** [comment]
@nolimits4web 
1. I don't want to use third party library.
2. You can do it more better.

**Comment by J05HI** [comment]
@nolimits4web
Some lightweight charts would be much better for mobile :)

**Comment by murliatdure** [comment]
@nolimits4web I agree to integrate the third party libraries; since your focus is on Design, UI specifications for different platforms and usability aspects ONLY!

Visualization (Charts and Maps etc) should no part of the framework, as per me!

Personnel thoughts, don't mind!

**Comment by J05HI** [comment]
I think integrating it shouldn't be a problem because we have components so if someone doesn't need it his app won't load it.

**Comment by nolimits4web** [comment]
Added in v3
