### ISSUE TITLE
[v2] Router Dynamic

### ISSUE THREAD

**Issue by lailton** [framework7io/Framework7#1815]
I am trying to add a page dynamic to rounter but it not works.

Any suggestions?

    var n = 0;

    function inline() {
      var page = "/page" + ((++n).toString()) + "inline/";
      var data = {
        path: page,
        template: '<div class="page">testing...</div>'
      };
      app.router.routes.push(data);
      app.router.navigate(page);
    }

I am looking for a solution to do something like this ( [v1] )

	`
	<div class="content-block"><a href="#" onclick="test()" class="button button-raised">OpenPage</a></div>
	`
	function test(){
	var cPage = `
	<div class="page">
	<div class="page-content">
	<div class="block">
	<p>This page created dynamically`+ (new Date()).toString() + `</p>
	<div class="content-block"><a href="#" class="link back button button-raised">About Framework7</a></div>
	</div>
	</div>
	</div>`;
	mainView.router.loadContent(cPage);
	}

**Comment by nolimits4web** [comment]
Is there any sense for that? You may have dynamic routes, e.g. `path: '/sompage/:variable1/:variable2` etc. and depending on variables and context you can return different content in page templates. 

But if you decided to go your way, you have to push routes to `view.router.routes` rather than `app.router.routes`

**Comment by lailton** [comment]
@nolimits4web,

Yes, my request have not a response directly in the click. 
It send a message via ( websocket ) to server where will execute the procedure and based in the informations the process can create a new page or can for example show a simple
notification( "wrong loging" ).

for this reason I need be able in create a page in time execution and open them.

I have tested with view and it works! thanks a lot and congratulation for this awesome project!
