### ISSUE TITLE
[v2] Documentation

### ISSUE THREAD

**Issue by ghost** [framework7io/framework7#1821]
There are any documentation for this new one ?

**Comment by J05HI** [comment]
@lailton
No not yet

**Comment by kinimodmeyer** [comment]
this is important 👍

**Comment by J05HI** [comment]
If it is ready yeah

**Comment by kinimodmeyer** [comment]
until this is done you can get a lot information here https://github.com/framework7io/Framework7/tree/v2/kitchen-sink and https://blog.framework7.io/mastering-v2-router-958ea2dbd24f
