### ISSUE TITLE
Framework7 V2 with Cordova Statusbar Plugin

### ISSUE THREAD

**Issue by mubeenwd** [framework7io/Framework7#1826]
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: v2.0.0-beta.8 , Hash - 853fb9970b5646bde3a6ad623d58c4eda1cfe939
* Platform and Target:  CORDOVA for ANDROID.
* Device : Tested on Android 6.0 – Marshmallow

### What you did
I have used latest Framework7 V2 beta 8 with the [cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar)

here is my code for the status bar.

` if (window.StatusBar) {
        StatusBar.backgroundColorByHexString("#0B3861");
    }`

### Expected Behavior
It should work as it was working in earlier version of framework7

### Actual Behavior
When opening keyboard It pushes navbar to the top and overlap with the statusbar.

![f7statusbarissue](https://user-images.githubusercontent.com/5129276/30772865-80ec2732-a082-11e7-9cb6-0bfd1bebf042.png)

### Note
This issue only occurred when i use status bar plugin.

**Comment by mubeenwd** [comment]
Any update regarding this??

**Comment by ytbryan** [comment]
@mubeenwd related https://github.com/framework7io/Framework7/issues/1811 ?

**Comment by mubeenwd** [comment]
@ytbryan thanks for the link but I am working on android application and also tried the solution given in #1811 but still not working.

**Comment by mubeenwd** [comment]
Some how i manage to fix it i have added `class="with-statusbar"` to the `<html>` element and worked like a charm. thanks all by the way.

@nolimits4web you can close if you think adding with-statusbar class to html element is correct.

**Comment by mubeenwd** [comment]
![f7statusbarissueresolve](https://user-images.githubusercontent.com/5129276/32404967-ab979a14-c181-11e7-9dcf-f3b54acfda7c.png)


@nolimits4web i am closing it as it is working.
