### ISSUE TITLE
Avoid distribution files in repositories

### ISSUE THREAD

**Issue by ZanderBrown** [framework7io/framework7#1827]
A number of issues & causes of confusion seem to arise from having the built files stored in the repository.

Perhaps it would be better to instead distribute them as 'binaries' through the GitHub releases platform.

This way both source code and release downloads would be smaller and avoid confusion between build, dist and src directories

**Comment by macdonst** [comment]
I'd say most people get the project from npm. So if we did an .gitignore on the dist folder and .npmignore on the src folder we'd be able to only publish the dist to npm. Anyone cloning this repo and downloading it can probably figure out how to build it for themselves.

**Comment by ZanderBrown** [comment]
Unfortunately I'd say a lot of users click the download link on the website that takes them to https://github.com/nolimits4web/Framework7/releases/, from there they grab a zip and start wondering why it doesn't work out the box

**Comment by nolimits4web** [comment]
I'm ok to make it more organised for v2. So basically we need?
* add `dist` to gitignore
* keep only `dist` and `kitchen-sink` in GitHub releases. To be honest i'm not sure how to automate it. Any thoughts?
* keep only `dist` in npm package.

**Comment by ZanderBrown** [comment]
We could add a gulp target to zip up dist and kitchen-sink, unfortunately attaching to a GitHub Release requires manual drag & drop

**Comment by nolimits4web** [comment]
The easies solution that comes into my mind is just using additional `release` and `npm` repos where we can easily keep just what we need

**Comment by nolimits4web** [comment]
I think we can close it for now as v3 has new structure, should be better
