### ISSUE TITLE
mainView.router.load won't let me pass in objects or arrays

### ISSUE THREAD

**Issue by TroyMaeder** [framework7io/Framework7#1830]
* [ ] enhancement

I'm trying to pass in an array of values to another page then loop through those values on the other page. 

I'm using the ```onClick="mainView.router.load({ url: 'knowledge_links.html', context: { total: '{{array}}' }})">``` but it's passing it as HTML to the other page so I'm not able to run a `forEach` as I want to. 

Is this the intended behaviour? Does F7 not let you pass objects or arrays this way?

**Comment by NilakArgento** [comment]
`var arr = ['foor', 'bar']
mainView.router.load({
    url: 'knowledge_links.html',
    context: {
        total: arr
    }
})`

**Comment by TroyMaeder** [comment]
That's how I've been passing it but I'm unable to then loop over the array
in 'knowledge_links.html'. Is this the expected behaviour? Because I can
loop over the array in the first page but when it's passed with
mainView.router.load({
url: 'knowledge_links.html', context: { total: arr } }) I'm unable to do
anything with it.

**Comment by TroyMaeder** [comment]
In the end this solved the issue

```onClick="mainView.router.load({ url: 'knowledge_links.html', context: urls: [ {{#each urls}} '{{url}}' ,{{/each}} ] }})"```

**Comment by TroyMaeder** [comment]
onClick="mainView.router.load({ url: 'knowledge_links.html', context: {total: '{{title}}', urls: [ {{#each urls}} '{{url}}' ,{{/each}} ] }})"

**Comment by nolimits4web** [comment]
Closing as looks like solved

**Comment by rapgithub** [comment]
mainView.router.load in v.2 ?
