### ISSUE TITLE
Page not redirect in href link

### ISSUE THREAD

**Issue by Dhanasekaranjones** [framework7io/framework7#1832]
I have used the latest framework7 version 1.6.4

When i click the **href link to not redirect the page** and i also **tried in onclick event, but  not working**.

**This is my code:**
```
<li>
   <a href="document.html" class="item-link item-content">
      <div class="item-media"><i class="ion-ios-upload"></i> </div>
      <div class="item-inner">
         <div class="item-title"><span>Document Upload</span></div>
      </div>
   </a>
</li>
```

Note: i have used in <span> tag also not working page navigation.

How to fix the solution give any example code.

**Comment by httpiago** [comment]
I'm having the same problem, the links are not redirecting the pages in v2.
I already reported #1814

**Comment by Dhanasekaranjones** [comment]
How to fix the problem?

The html a href link not working

**Comment by lws68825** [comment]
I encountered the same problem. Ajax link does not work with redirection response.

**Comment by achmadk** [comment]
I am upgrading framework7 to version 2.0.2 and get same problem (cannot navigate to other page). You can try in [this repo](https://github.com/achmadk/mobile-dev-boilerplate).

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by ajvibik** [comment]
I've also faced the same problem alternate solution is call the function while clicking and use this 

window.location.href = 'http://www.example.com/';

**Comment by Aurelog** [comment]
Hello,
I was stuck with the same (false) issue but find the solution, if it could help someone else.

Just add class = "link external" to your <a>

<a class="link external" href="http://google.com">Open Google</a>

It is named bypass links handler, you can find it under links framework7 documentation 

Hope this will help.

Br
