### ISSUE TITLE
[v2] NoMatch Route, 404

### ISSUE THREAD

**Issue by russiann** [framework7io/Framework7#1834]
How to define a 404 page when url does not match with any defined route??

**Comment by russiann** [comment]
When I type some path in browser that not match with any defined route the app just throws me a blank white page;

**Comment by russiann** [comment]
👀

**Comment by russiann** [comment]
@nolimits4web ?

**Comment by nolimits4web** [comment]
👀 
I have put it in my TODO list https://github.com/framework7io/Framework7/projects/3
