### ISSUE TITLE
Ajax Link Authentication

### ISSUE THREAD

**Issue by lws68825** [framework7io/Framework7#1841]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Is it possible to make ajax link work with server side http basic authentication? I use ruby on rails on server and devise gem to authenticate user.

**Comment by nolimits4web** [comment]
Yes, it is possible. Need to send `username` and `password` parameters in Ajax request

**Comment by hongxiangrong** [comment]
Previously it was doable with $$.ajaxSetup
How to do so in v2?
