### ISSUE TITLE
Timeout on ajax not working

### ISSUE THREAD

**Issue by sweebee** [framework7io/Framework7#1843]
I've set a timeout on a ajax function, but the timeout does not work, it keeps searching for a server which is not online.

```
$$.ajax({
        type: 'GET',
        timeout: 1500,
        url: url,
        success: function (data, textStatus, XMLHttpRequest) {
            console.log('good');

        },
        error: function (XMLHttpRequest, textStatus) {
            console.error(textStatus);
            console.error('No connection');
            
        }
    });
```

**Comment by nolimits4web** [comment]
Can't replicate your issue, works totally fine for me:

<img width="672" alt="2017-11-09 17 20 06" src="https://user-images.githubusercontent.com/999588/32609925-4bded5f2-c572-11e7-91e8-616a48e215f9.png">
