### ISSUE TITLE
v1.6.5 - Autocomplete dropdown not working inside tabs

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#1845]
* [x] bug
* Framework7 Version: 1.6.4 and 1.6.5
* Platform and Target: cordova

If you use an autocomplete inside a tab, when you click on an item, this is didn't get selected:  https://jsfiddle.net/s2n1p730/14/

Instead, if you remove the tabs, it works fine when you click in an option:   https://jsfiddle.net/vousys/s2n1p730/17/

**Comment by vousys** [comment]
Simple autocomplete dosen't work. Inside tabs I had to use standalone autocomplete.
Sad ;(

**Comment by vousys** [comment]
@nolimits4web hi men! can you help me with that?

**Comment by ZanderBrown** [comment]
I copied the JS from [the fiddle without tabs](https://jsfiddle.net/vousys/s2n1p730/17/) to the [fiddle with](https://jsfiddle.net/s2n1p730/14/) and both seem to behave the same, I suspect a user JS error in the tab fiddle.

**Comment by nolimits4web** [comment]
Working example with tabs https://jsfiddle.net/6k5wpdzm/

**Comment by nolimits4web** [comment]
Issue in your Fiddle because you add pageInit handler AFTER it was fired

**Comment by vousys** [comment]
@nolimits4web @ZanderBrown thanks guys, but if you click on an item, for ex, write "apple" and click it to select them,  the onchange never gets fire

**Comment by nolimits4web** [comment]
This is the issue with Swiper, which blurs active input. If you switch to animated tabs or usual tabs you won't have such issue. Also, there is no such issue on mobile, desktop only thing

**Comment by vousys** [comment]
Fantastic!!!!!! thanks so much!!
