### ISSUE TITLE
[v2] module vs modular builds

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#1848]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: v2 branch from 04/10/17
* Platform and Target: web

### What you did
cloned v2 branch
npm run build-prod

### Actual Behavior
3 js files were created in dist folder

framework7.js
framework7.module.js
framework7.modular.js

The `framework7.js` build file is the traditional bundling all together. All ok

The `framework7.module.js` build imports `dom7` and `template7` and bundles by default all components. ES6 code is transpiled.

The `framework7.modular.js` build imports `dom7` and `template7` and bundles only core components and exports the remaining separately. ES6 code is not transpiled.

In package.json sets module and jsnext:main fields to `framework7.module.js`

When using webpack or rollup `framework7.module.js` will be used but will not enable treeshaking (do not bundle not used code)

To enable treeshaking is necessary to import directly `framework7.modular.js` but this build does not transpiles ES6 code. The issue here is that the common setup of webpack / rollup does not transpiles code from node_modules requiring an extra configuration.

### Expected Behavior
`framework7.modular.js` should keep the current ES import/export configuration but transpile the remaining code. For reference see: https://github.com/rollup/rollup/wiki/pkg.module

Also consider renaming `framework7.modular.js` to `framework7.esm.js` as other libraries are doing

**Comment by nolimits4web** [comment]
Hi,
I am ok with renaming es packages with `.esm` prefix. But not about transpiling. I have tested a lot treeshaking with F7, and the best results we can got is having it in ES-next syntax. I was explained a bit here https://github.com/nolimits4web/Template7/pull/38 why it is happening. And with even more complex classes in F7 it almost doesn't work at all. So probably later when treeshaking algorithms of bundlers will be improved i will be fine with transpilation.

**Comment by blikblum** [comment]
Ok. I think is necessary to document this. Is there something already?

If not, just tell me the appropriate place in docs and i can help with a PR

**Comment by nolimits4web** [comment]
Yes, need to be documented, but there is no v2 docs yet, so there is no place to put it currently :)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
