### ISSUE TITLE
[V2] Statusbar notworking

### ISSUE THREAD

**Issue by lailton** [framework7io/Framework7#1852]
Statusbar is not working.

**Comment by ytbryan** [comment]
related? https://github.com/framework7io/Framework7/issues/1811

**Comment by lailton** [comment]
Hi @ytbryan,

No, it is not related with this.
The problem started now with the last commits 90c21b7268402eb85e0182a058b3a0c116f010d7

**Comment by lailton** [comment]
@nolimits4web Solved!
Thanks
