### ISSUE TITLE
[v2] Help component

### ISSUE THREAD

**Issue by J05HI** [framework7io/Framework7#1855]
@nolimits4web 
Would be great to have a help. 

Here some examples:
![](http://i.imgur.com/139NgoO.gif)
![](http://i.imgur.com/43lH5q5.gif)
![](http://i.imgur.com/fz2exIQ.gif)
![](http://i.imgur.com/oF1CaSO.gif)

**Comment by httpiago** [comment]
They have a plugin that does this tour through APP. It's not in Material Design style but you can customize to look more like the design of project.

Framework7 Plugin Tour Guide: https://github.com/razekteixeira/Framework7-Plugin-Tour-Guide

**Comment by J05HI** [comment]
@httpiago
I've seen that already but a integrated component in v2 would be amazing :)

**Comment by nolimits4web** [comment]
Yeah, there is a plugin already for this. I think it is better to send request to the plugin author.

**Comment by nolimits4web** [comment]
Closing for now
