### ISSUE TITLE
[v2] Close FAB on outside click

### ISSUE THREAD

**Issue by J05HI** [framework7io/framework7#1857]
@nolimits4web
Could you please add an option to show a grayed background behind the opened FAB and close it if you click on that?

**Comment by nolimits4web** [comment]
It is easy to do manually:
```js
$(document).on('click', function (e) {
  if ($(e.target).closest('.fab').length === 0) app.fab.close()
});
```

**Comment by J05HI** [comment]
@nolimits4web
Yeah I have something like that already but a parameter would be nicer :)
