### ISSUE TITLE
[v2] Add/remove calendar events dynamically 

### ISSUE THREAD

**Issue by J05HI** [framework7io/Framework7#1858]
@nolimits4web
Could you please add a method to add and remove calendar events dynamically if it is already initialized?

**Comment by nolimits4web** [comment]
It is already there `calendar.update()` method will rerender currently opened/visible calendar

**Comment by J05HI** [comment]
@nolimits4web
Thank you very much!

**Comment by chenghsuan** [comment]
Hi~
Does `calendar.update()` method still work?

**Comment by manish2535** [comment]
calendar.update() does not seem to redraw the Event Dots under the Days. I have the calendar.update() in the Calendar's init() after the calendar.events has been populated with data...? Any ideas?
