### ISSUE TITLE
[v2] Add "real" material navigation drawer

### ISSUE THREAD

**Issue by J05HI** [framework7io/framework7#1860]
@nolimits4web
Could you please add a "real" material navigation drawer example?

![](https://i.imgur.com/bR2BfAt.jpg)

**Comment by lailton** [comment]
We need this!

**Comment by nolimits4web** [comment]
What do you mean by "real"?

**Comment by J05HI** [comment]
@nolimits4web
With this app like design

**Comment by nolimits4web** [comment]
Closing as not the issue, and it is more about customization
