### ISSUE TITLE
[V2] search bug 

### ISSUE THREAD

**Issue by GuillaumeBiton** [framework7io/Framework7#1861]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.0-beta.9
* Platform and Target: IOS, MacOS, IE 11, Edge
* Live Link or JSFiddle/Codepen: KitchenSink 

### What you did
Click on search to made search input appear. It creates an offset on the right.

### Expected Behavior
No offset

### Actual Behavior
offset

![ezgif-3-81b0c83683](https://user-images.githubusercontent.com/729578/31340585-ec30bfcc-ad06-11e7-9de1-2dd24d8b256d.gif)

**Comment by nolimits4web** [comment]
I know about it, but to be honest can't find a reason what causes it. Looks like iOS-related rendering issue, as according to styles and what inspector shows it should be on right place. If you know what cause it, let me know

**Comment by GuillaumeBiton** [comment]
Yes I have try to find from where it goes by myself but I didn't find. so I ask here.

I will search

**Comment by GuillaumeBiton** [comment]
OK found that the bug as been introduced between beta2 and beta3.

**Comment by GuillaumeBiton** [comment]
ffe9c3ff09437a92a37657e0f8075f320b5c19ae
