### ISSUE TITLE
I would like to be able to create dynamic pages with a custom url

### ISSUE THREAD

**Issue by httpiago** [framework7io/Framework7#1863]
In a website I did, I created a code that when the user clicks on a link a page appears with the load message and the url changes with the link.
![pp](https://user-images.githubusercontent.com/3616259/31354157-aedd8b82-ad0b-11e7-876d-4520a18e03ad.jpg)
But to do it first you have to call a dynamic page that has an ugly url (#content-4) and then request to reload the page with the actual link being requested by the user (it was the only form I found in the documentation). But sometimes this causes a browsing problem because when the user clicks back the browser returns to a "#content-4" page.

I wanted a more practical way of doing this just by request for something like:
app.router.navigate({
     'path': '/post/the-good-place',
     'content': '&lt;div class="page"&gt; ... &lt;/div&gt;',
});

There is a tip there for you to add in the second version.

**Comment by lailton** [comment]
http://framework7.io/docs/pages-dynamic.html

**Comment by nolimits4web** [comment]
It will be realized and already partial available in v2
