### ISSUE TITLE
Accessibility: previous page is visible when using screen reader

### ISSUE THREAD

**Issue by nirandas** [framework7io/Framework7#1864]
While using framework7 apps via screen reader, the previous page is still visible after navigating to a new page. Focus is still on the older page and elements on it are available and accessible.
This can be tested using NVDA or JAWS on browser  (Tested on chrome browser) and on android phone, using talkback.

The CSS classes added to the hidden page is not hiding it from the screen readers.

**Comment by nolimits4web** [comment]
Is it actual for v2?

**Comment by nirandas** [comment]
I'm using framework7 vue so probably v1. I'm checking the v2 out now.

**Comment by nirandas** [comment]
Issue is still there on v2. I cloned the v2 repo and ran the npm run prod command. On the kitchen sink page, if I click on the about link, the about content is loaded but it is shown after the content of the home page. I can still access the content and links on the home page as well as the text on the about page.

Tested on chrome and internet explorer only.

**Comment by nolimits4web** [comment]
All I can do is to add aria-hidden attribute to previous page

**Comment by nirandas** [comment]
Okay. I'll test this again when that change is made.
thanks

**Comment by ZanderBrown** [comment]
I think a combination of visibility: none and display: none are the solution from a CSS perspective

**Comment by nolimits4web** [comment]
Added `aria-hidden` to previous page in v2

**Comment by nirandas** [comment]
Thank you! it works on IE and chrome. Not tested on mobile but think it should work. 
Thanks again.
Any word / update on framework 7 vue?
