### ISSUE TITLE
Uncaught TypeError: $.get is not a function

### ISSUE THREAD

**Issue by arifulalam** [framework7io/Framework7#1865]
using
Framework7 2.0.0-beta.8

have in app.js, 
`var $ = Dom7;`

called following in console,
`$.get('url', function(data){
   console.log(data);
});`

printed:
`VM906:1 Uncaught TypeError: $.get is not a function
    at <anonymous>:1:3
(anonymous) @ VM906:1`

How to fix/call get of Dom7?

Regards

**Comment by nolimits4web** [comment]
v2 uses latest Dom7 version which doesn't have Ajax api anymore. It is moved to app's `.request`:
```
myApp.request.get('url', function(data){ console.log(data); });
```
or under Framework7 class static prop:
```
Framework7.request.get('url', function(data){ console.log(data); });
```
