### ISSUE TITLE
[v2] Scrolling virtual list on Android Chrome buggy

### ISSUE THREAD

**Issue by J05HI** [framework7io/framework7#1868]
@nolimits4web  
Scrolling a virtual list on Android Chrome is really buggy.
Please improve this. I can't use it :(

**Comment by J05HI** [comment]
@nolimits4web
It's on v1 too :(
Maybe chrome has changed anything..

**Comment by dotgodly** [comment]
+1, even with 1000 items, scrolling too fast makes the list glitch.

**Comment by J05HI** [comment]
@dotgodly @nolimits4web 
Yeah it's really annoying :(
Can't use the virtual list.

**Comment by J05HI** [comment]
@nolimits4web
Can you please give a statement to this :)

**Comment by J05HI** [comment]
@nolimits4web
Same here!
Closing issues won't fix them
