### ISSUE TITLE
Error doing an ajax call to a webservice with authentication.

### ISSUE THREAD

**Issue by AllanPamplona** [framework7io/Framework7#1869]
This is a bug.

* Framework7 Version: Current master branch.
* Platform and Target: Cordova on android.

I'm trying to call a web service with authentication using the f7 $$.ajax function.
I have this:
$$.ajax({
        url: "https://user:pass@www.bug.example/service?id=23241",
        cache: false,
        type: "GET",
        success: function(html){
          myApp.alert("j "+html.)
        }
      });
And i'm getting a 401 not authorized error, but when i call the service from browser everything is ok.
I'm debugging with google chrome and i can see when i call the ajax function it tries to make the get method to https://www.bug.example/service?id=23241.
I think it is ignoring the user and password on url.
Using jquery everything is okay:
$.ajax({
        url: "https://user:pass@www.bug.example/service?id=23241",
        cache: false,
        type: "GET",
        success: function(html){
          myApp.alert("j "+html.)
        }
      });

**Comment by nolimits4web** [comment]
It should be:
```
$$.ajax({
        url: "https://www.bug.example/service?id=23241",
        user: 'user',
        password: 'pass'
        cache: false,
        type: "GET",
        success: function(html){
          myApp.alert("j "+html.)
        }
      });
```
