### ISSUE TITLE
Custom JavaScript not working

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/Framework7#1870]
Hi! I have a button when I click I want to execute a alert and call AJAX but even the alert is not showing, where should I put my JS code?

**Comment by nolimits4web** [comment]
If you use v1 then check http://framework7.io/docs/page-callbacks.html. Also forum and StackOverflow can be much more helpful for such questions

**Comment by johndavemanuel** [comment]
okay! thank you :)
