### ISSUE TITLE
Swiping in swiper without dismissing android keyboard results in event handlers not being triggered

### ISSUE THREAD

**Issue by klick-barakgall** [framework7io/framework7#1874]
This is a: bug

* Framework7 Version: 1.6.5
* Platform and Target: Cordova on IOS and Android (reproduced on a plain website on Android)
* Live Link or JSFiddle/Codepen: https://codepen.io/rakus/pen/wrxpzy (spent a while creating this pen, didn't realize I should fork from an existing pen. My apologies.)

### What you did
I created a simple swiper with an `onSlideNextEnd` handler. On any slide that is NEITHER the first, nor the last slide I create a textbox.

When on the textbox slide on an android device (possibly also an iOS device, not tested) I click into the textbox and type something (something must be typed or this behaviour doesn't show up). Finally I swipe to the next slide *WITHOUT* dismissing the android keyboard first.

### Expected Behavior
The next slide should be brought into view and the `onSlideNextEnd` handler should be triggered.

### Actual Behavior
The next slide is brought into view but `onSlideNextEnd` is NOT triggered

### Additional details
After a bit of diving into framework7 code, it appears that on dismissing the keyboard an onresize event handler is triggered which then changes `previousSlide` and `activeSlide` variables to values that will not trigger a slide transition. I'm not sure why this only seems to happen after typing input and swiping without dismissing the keyboard.

**Comment by klick-barakgall** [comment]
Is there any other details I can add to help resolve this?

**Comment by nolimits4web** [comment]
Is this still happening in stable v2 versions?

**Comment by klick-barakgall** [comment]
Apologies @nolimits4web...

We had found a workaround. I believe it was a bunch of manual events, timeouts and checking internal state.

I don't recall exactly.

The project is now complete and working and we won't be able to change the solution or investigate further. Please feel free to have a look at the codepen I provided and try whatever version you'd like and see if it's behaving the same.

**Comment by nolimits4web** [comment]
Ok, good. Let's close it for now, as looks like no one reported something similar. Feel free to open new one if you will have this issue in latest v2 version
