### ISSUE TITLE
[v3] New Component WYSIWYG Editor

### ISSUE THREAD

**Issue by praveenmujawdiya** [framework7io/framework7#1876]
@nolimits4web 
It would be great to have a lightweight WYSIWYG editor.

![wysiwyg](https://user-images.githubusercontent.com/32750425/31518281-64861b04-afbc-11e7-89bb-9ee492e89695.png)

**Comment by J05HI** [comment]
Good idea 👍

**Comment by vousys** [comment]
Maybe integrating summernote or trumbowyg that works very well on web

**Comment by ZanderBrown** [comment]
Interesting not sure if this is quite in scope though.
Would definitely make a good plugin assuming it have be implemented in a way suitable for the different themes

**Comment by mitchellfranklin** [comment]
I was actually in progress of doing this to work with Pinegrow Web Developer, but one I saw V2 i put it on hold as its been simplified to work with both iOS and Material themes in the same layout so am waiting a bit longer then will start it again using V2
