### ISSUE TITLE
Show side panel in tablet and big device

### ISSUE THREAD

**Issue by AGhasemzadeh** [framework7io/Framework7#1877]
Hello,
I am using F7 for my hybrid application. It is important that we have off-canvas drawer panel.
For example user see side-panel in big device (Like tablets and laptops and PCs) and hide in small devices (Like phones and small tablets).

Panel like this page:
http://mdl.rtlcss.com/templates/dashboard/index.html

**Comment by nolimits4web** [comment]
There is an app parameter for this, e.g. `panelLeftBreakpoint` http://framework7.io/docs/init-app.html
