### ISSUE TITLE
 [Framework7+Vue]Auto generate 'undefined' after <f7> tag when I upload project to server??

### ISSUE THREAD

**Issue by phamhieu2212** [framework7io/Framework7#1878]
<a href="https://ibb.co/jZyBvb"><img src="https://preview.ibb.co/m6ZjFb/Screen_Shot_2017_10_13_at_18_03_33.png" alt="Screen_Shot_2017_10_13_at_18_03_33" border="0"></a>

**Comment by nolimits4web** [comment]
Hard to understand what happens here, probably issue on server side (if you use SSR). Otherwise make sure you are using latest Vue version. And please, open vue-related issues in appropriate repository
