### ISSUE TITLE
Build using laravel mix

### ISSUE THREAD

**Issue by AGhasemzadeh** [framework7io/Framework7#1879]
Hello,
I want to use laravel mix (Webpack) to re build my application but I get some problem:
1.
I make file by the name mobile.js:
https://pastebin.com/i122nwQK
After I compile (npm run dev) I get this error in browser console:
https://pastebin.com/QB61LQTZ

2.
I want to rebuild less files with webpack then I make file but the name mobile.less with following codes:
https://pastebin.com/QknCpL6D
but I get:
Property '$rtl' is undefined

3.
when I run `npm run production` I get:  
\mobile\js\mobile.js from UglifyJs
Unexpected token: name (Dom7) [./node_modules/dom7/dist/dom7.module.js:14,0][\mobile\js\mobile.js:12635,6]

Please help me to fix these errors.

**Comment by nolimits4web** [comment]
1.
I can recommend you to use v1 versions of both F7 and F7-Vue if you are going to go with such custom build.

2. Less in v2 is dynamically generated using JS, it can't work like usual less file, see https://github.com/framework7io/Framework7/blob/v2/scripts/build-less.js

3. Babel/Buble is required when using using v2's of F7, F7-Vue, etc.

**Comment by AGhasemzadeh** [comment]
Thanks,
Just I build all without any problem just I have one problem with:
TypeError: window.Framework7.prototype is undefined[Learn More]
