### ISSUE TITLE
Reload/Init Page on Back Clicked

### ISSUE THREAD

**Issue by sbryfcz** [framework7io/framework7#188]
Sorry if this has been asked before but I can't find the answer. How would you recommend triggering a page refresh/reload when the back button is clicked. It doesn't look like the page's init is called when it is navigated to from a back button. Should I manipulate the history or something? Any advice would be great. Thanks for the great work.

**Comment by 631068264** [comment]
For example I have navigation  Page1 -> Page2 -> Page3. 
 I wanto go back to Page2 form Page3 and refresh Page2
```
myApp.onPageBeforeAnimation('page2', function (page){
  
  if (page.from === 'left') {
       page.view.router.refreshPage();
  }
});
```
But page2 cant`t refresh .Why?  @nolimits4web

**Comment by amaster507** [comment]
@631068264 I am having this same issue, did this ever get resolved?

**Comment by 631068264** [comment]
#698 @amaster507 back and refresh

**Comment by Extracreative** [comment]
Use '*' to trigger it for all pages 
myApp.onPageAfterAnimation('*', function (page){
if (page.from === 'left') {
  }
});
