### ISSUE TITLE
[v2] One UI for all

### ISSUE THREAD

**Issue by AGhasemzadeh** [framework7io/framework7#1880]
* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Hello,
I think it would be good idea that framework7 can be used as web UI like bootstrap or zurb f6.
Just we need some option to disable touch features and minify css and js files after that we can use it anywhere.

**Comment by lailton** [comment]
The idea is not bad,
But I think that the focus is for mobile.

**Comment by ZanderBrown** [comment]
F7 already works very well in standard websites on desktop browsers, was there any extra functionality you'd like to see?

**Comment by AGhasemzadeh** [comment]
Quasar is good but it is not easy to use while f7 is easy to use.

@zanderbrown  Yes. f7 work on browser but not optimized.

**Comment by ZanderBrown** [comment]
Could we have info about 'Quasar' and expand on your 'not optimized' comment?

**Comment by AGhasemzadeh** [comment]
Please check F7 in desktop mode.

**Comment by mohshraim** [comment]
for web app use f7 for application navigation and bootstrap for web control and design!

**Comment by AGhasemzadeh** [comment]
yes, bootstrap has good components.
bootstrap + f7 nav will become the best

**Comment by ZanderBrown** [comment]
> Please check F7 in desktop mode.

Explain

**Comment by nolimits4web** [comment]
Closing as not really an issue, and F7 has material design which is the widely used now for desktop apps/websites

**Comment by mohshraim** [comment]
True, but i think we should work on table components to have strong one like bootstrap table (search, sort, pages ..etc)
