### ISSUE TITLE
f7 v.2 TypeError: undefined is not a function (near '...$$.ajax...')

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1883]
I am using framework7 v.2 beta and when using ajax calls i receive all the time this error:

TypeError: undefined is not a function (near '...$$.ajax...')

what am i doing wrong? 

        $$.ajax({
            url: 'about.html',
            dataType: 'json',
            data: data,
            method: "POST",
            statusCode: {
                404: function(xhr) {
                    alert('page not found');
                }
            },
            complete: function(){
                alert('complete');
            },
            success: function(response) {
                setTimeout(function() {}, 500);
            },
            error: function(){
                alert('got an error');
            }

        })

**Comment by nolimits4web** [comment]
In v2 it is `myApp.request({...})`

**Comment by rapgithub** [comment]
thanks now it is working! thanks app.request it is... 

Do you know how can I update my template in my page using app.request in my case the data object after success it is returned correctly but it does not update my template page with the object data:

do you know why?

my code:

   pageInit: function(e, page) {
        console.log('pageInit', page);
        var self = this;

        preloader: true, //enable preloader

        // Show Preloader
        app.preloaderShow();

        data = {user:'123456'};
        app.request({
              url: '_request.php',
              dataType: 'json',
              data: data,
              method: "POST",
              crossDomain: true,
              statusCode: {
                  404: function(xhr) {
                      console.log('page not found');
                  }
              },
              complete: function(){
                  console.log('complete');
              },
              success: function(response) {
                  console.log(response);
                  return (response);
                  setTimeout(function() {
                    autocomplete.preloaderHide();
                  }, 500);
              },
              error: function(){
                  console.log('error');
              }

          })
      })

thanks
