### ISSUE TITLE
app.openpanel not recognized in framework7 v.2

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1885]
i am getting stuck in framework7 with this new things..

i am using app.openPanel('right'); and not working and I get this error:

TypeError: app.openPanel is not a function. (In 'app.openPanel('right')', 'app.openPanel' is undefined)

is there any documentation online for v.2 and things that has changed because something like this not working in v.2 beta. and i guess this is because app.openPanel maybe has changed but to what? any information or documentation about the changes?

i will appreciate where i can find this manual of v.2
thanks

**Comment by nolimits4web** [comment]
v2 is still in development and there is no docs for it yet. In v2 it is `app.panel.open('right')`

**Comment by rapgithub** [comment]
thanks working now!
