### ISSUE TITLE
VirtualList - Allow template7 syntax in 'emptyTemplate' method

### ISSUE THREAD

**Issue by MatthiasBusch** [framework7io/Framework7#1886]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 1.6.5
* Platform and Target: All

### What you did
I used a virtual list with an emptyTemplate, that includes template7 variables

### Expected Behavior
The template7 syntax should have been parsed

### Actual Behavior
I can see the '{{emptyList}}' template

It would be great if you could use template7 in the emptyTemplate method of the virtualList

**Comment by nolimits4web** [comment]
Any sense in this? Empty template doesn't receive any items or whatever because there is no items. Just use plain JS there, otherwise do it manually:
```
emptyTemplate: Template7.compile('....')()

**Comment by MatthiasBusch** [comment]
Thank you for the example of how to do it manually.
I am using it for localization. I made a template7 helper method, that displays a translation for a file
