### ISSUE TITLE
[v2] RTL bug for md navbar

### ISSUE THREAD

**Issue by ahmeddaif1** [framework7io/Framework7#1890]
CSS
-
the `.md .navbar .right` for **RTL**  set `margin-right: auto;` but don't override the original `margin-left: auto;`  

I believe that the class in **framework7.rtl.css** should be
`.md .navbar .right {
    margin-right: auto;
    margin-left: 0;
}`

**Comment by nolimits4web** [comment]
You should NOT include both RTL (`framework7.rtl.css`) and LTR (`framework7.css`) stylesheets. If you need RTL then include ONLY `framework7.rtl.css`
