### ISSUE TITLE
FrameworkVue,access $f7 in route element monted lifecycle

### ISSUE THREAD

**Issue by Wolferring** [framework7io/Framework7#1892]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: framework-vue 0.9.1.
* Platform and Target: browser.

### What you did
	mounted(){
		var homeElement = this.$refs.homeContainer.$el
		this.$f7.pullToRefreshTrigger(homeElement)
	},

trying to use $f7 in  the route element mounted lifecycle,and then throw err :
Error in mounted hook: "TypeError: Cannot read property 'pullToRefreshTrigger' of undefined"
### Expected Behavior
I can use $f7 when the route element mounted

### Actual Behavior
can't use $f7,

**Comment by nolimits4web** [comment]
If you do it on initial rendering (home page), do it in `onF7Init` method:
```js
methods: {
  onF7Init() {
    var homeElement = this.$refs.homeContainer.$el
    this.$f7.pullToRefreshTrigger(homeElement)
  }
}
