### ISSUE TITLE
the layout of material is not working

### ISSUE THREAD

**Issue by voillsy** [framework7io/Framework7#1896]
![image](https://user-images.githubusercontent.com/24789216/31709601-18302ace-b3b8-11e7-96c9-476c4837bd2f.png)

**Comment by nolimits4web** [comment]
Looks like you have put `navbar` element in a wrong place. In material theme it must be inside of `<div class="page">` element

**Comment by voillsy** [comment]
@nolimits4web  thanks

**Comment by voillsy** [comment]
@nolimits4web  i just run 'gulp server ' the demo and open the examples ...
