### ISSUE TITLE
[v2] mainView.router.load does not work in framework7 v.2 any equivalent function?

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1897]
I am trying to send dynamic url params to a page according the form selection options the user selected but i am using v.2 and  mainView.router.load  does not work here... 

any way to send parameters to a page using v.2?
or how should I use the router.query with dynamic data to be passed to the next page?

thanks

**Comment by lailton** [comment]
https://blog.framework7.io/mastering-v2-router-958ea2dbd24f

**Comment by rapgithub** [comment]
I will give a try with this!! thanks!  

I am using ajax to retrieve the data from my database and show in that page the data but I need to pass from the previous page the parameters to filter the displayed data there... 

my console is ok showing the object data retrieved from db but the template is not showing that data dynamically ...

have you try this with dynamic data? in my case not working only working when the data is static ...
:( 

I am using f7 v.2

**Comment by lailton** [comment]
Hi @rapgithub,

Yes, I am doing exactly this one too.

Check in the link the part "Async"

I am sure that it will works for you ;)

**Comment by rapgithub** [comment]
thanks. i will do that i like this v.2 but there is no doc. about it yet so guessing some things other i must ask and so

**Comment by lailton** [comment]
The link contains a big and good documentation about router.
Anyway if you need help to be free to message me on skype ( suporte@lailton.com.br )

**Comment by rapgithub** [comment]
have you try to use method in the index page? in my case does not work! @click=postit  for instance does not work either only work in the called pages and router does not trigger anything in the index... 

<script>
routes: [ 
{
  methods: {
  postit: function () { 
  alert('this');
  },
},
}
]
</script>

**Comment by rapgithub** [comment]
I try Async but it does not work!!! in my case when i click the link to the page nothing happen no errors in console nothing!

                    < a href="/something/">l-something</a>

then in the script of the page, nothing inside the async function is executed nothing happen but if i use url: then it works the link :(

routes: [
  // Dynamic page from content
  {
    path: '/something/',
    async: function (resolve, reject) {
    	alert('');
        app.request({... 

   });
}

**Comment by rapgithub** [comment]
sorry         
< div class="view view-main view-init" data-url="/" >

was missing at the top and made all behavior not working properly!
now async is working ... at least by now...
