### ISSUE TITLE
[v2] Page Exchange

### ISSUE THREAD

**Issue by lailton** [framework7io/Framework7#1898]
@nolimits4web,

There are way to disable the animation when the page exchanged?

**Comment by J05HI** [comment]
@lailton
CSS?

**Comment by lailton** [comment]
Yes. I need to disable the frame animation.

**Comment by nolimits4web** [comment]
Use `animate:false` (in v2) or `animatePages: false` (in v1) router parameter when navigation to required page

**Comment by lailton** [comment]
Thanks!!

**Comment by l41lt0n** [comment]
Sorry for re-open this, but I was trying to disable the animation ( frame transition but it does not to work).
animate: false,

I am using the last version framework7.

Any suggestion?

**Comment by nolimits4web** [comment]
And how do you use it?

**Comment by l41lt0n** [comment]
I have tried differents way with the same result, for example:

var app = new Framework7({
	root: '#app',
	theme: 'md',
        animate: false
});

and I have added for all my load pages:

		var page_html = {
			path: page_name,
			content: page,
                         animate: false
		};

app.router.navigate(page_name);

all works fine. but I have a problem with delay to show page for PC/Desktop.
so for this reason for me this frame animation is better to be off.

Thanks

**Comment by l41lt0n** [comment]
Solved.

Now it is:
	options: {
		animate: false
	}

Thank you.
