### ISSUE TITLE
Scroll Bounce and Pull to refresh

### ISSUE THREAD

**Issue by zacksiri** [framework7io/framework7#19]
Hey 

First of all I have to say this is simply amazing. its basically the best HTML5 framework for building iOS apps. simply brilliant.

I was wondering if it was possible to do scroll bounce and pull to refresh like the native apps have?

**Comment by jeka5555** [comment]
Hi! This feature is available at the moment?I did not find an example of it. How to enable it?

**Comment by nolimits4web** [comment]
@jeka5555 http://www.idangero.us/framework7/docs/pull-to-refresh.html

**Comment by jeka5555** [comment]
Hi! I mean Scroll Bounce. To scroll in android works on both iphone. Thanks!

**Comment by nolimits4web** [comment]
@jeka5555 F7 uses native scrolling, Android just doesn't have it

**Comment by jeka5555** [comment]
Can not be made to work more smoothly it? It is too sharp, and when you scroll a little twitch pictures

**Comment by justradojko** [comment]
Is there a option just for scrolling with bounce (without refresh action) like iOS has on all pages? Maybe I just cannot find it?

I using iScroll plug-in, but it would be grate if I could ditch that.

**Comment by scriptPilot** [comment]
This works well with current Framework7 version to eliminate the bounce effect:
- 1. Download https://github.com/lazd/iNoBounce/blob/master/inobounce.min.js
- 2. Include script `<script type="text/javascript" src="js/inobounce.min.js"></script>`
- 3. Add css to .views container
```
.views {
  height: 100%;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
}
```
