### ISSUE TITLE
$$.ajax problem

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/Framework7#1905]
hello! i have my app, when in browser it is working the AJAX connecting in our api we made, but when I build it in phonegap test it on my android phone, it is not working  how to deal with that?

**Comment by rapgithub** [comment]
do you have your ajax code sample?

**Comment by johndavemanuel** [comment]
yes

**Comment by johndavemanuel** [comment]
myApp.onPageInit('signin', function (page)
{
    $$('#btn-signin').click(function()
    {
        $$.ajax({
            url: baseUrl+'api/member/login',
            type: "POST",
            data: $$("#ajaxForm").serialize()
        }).done(function(data)
        {
            //console.log(data.status + ' ' + data.alert + ' ' + $.type(data.alert));
            $$("#ajaxForm span.error").remove();
            $$("#ajaxForm div.msg-holder").remove();
            if(data.status == 'danger' && $.type(data.alert) == 'object')
            {
                $$.each(data.alert, function(fieldName, fieldMsg)
                {
                    //console.log('key:'+fieldName+' value:'+fieldMsg);
                    $$("input[name='"+fieldName+"']").attr('style', 'border-bottom:2px solid #ff0000;');
                    $$("input[name='"+fieldName+"']").parent().parent().append(fieldMsg);
                });
            }
            else
            {
                $$('#ajaxForm').prepend('<div class="msg-holder '+data.status+'">'+data.alert+'</div>');
            }

            if(data.status == 'success')
            {
                // console.log(data.row.user_id + ' taz ' + data.row.user_group_id);
                localStorage.setItem("user_id", data.row.user_id);
                localStorage.setItem("user_group_id", data.row.user_group_id);
                mainView.router.loadPage('home.html');
            }
        });
    });
});

**Comment by rapgithub** [comment]
I do not see a problem in your ajax request.... 
are you using cookies in your hybrid app? if so try removing the targetSdkVersion when building your android SDK version... 

go to the android project settings and permissions and check for internet permissions if you app make ajax calls needs to connect to internet to access the files...  then build again and try...

**Comment by rapgithub** [comment]
is there a way to check which status returns your ajax? 404?

**Comment by rapgithub** [comment]
if your ajax not working fine this way try to use this form and build I have heard that some people has problems using $$.ajax

var xhr = new XMLHttpRequest();
xhr.open('GET', 'yourfiletoberequested', true);
xhr.onload = function(){
    console.log(xhr);
};
xhr.send();

**Comment by rapgithub** [comment]
do you use Node.js?  try updated if so to Node.js to v0.10.31

**Comment by rapgithub** [comment]
a link to a helpful phonegap problems too in case if helps to test if this is your issue 

https://stackoverflow.com/questions/39097721/how-fix-or-disable-proxy-in-phonegap

**Comment by johndavemanuel** [comment]
What you mean android sdk?
I am using build.phonegap.com in buiding it

**Comment by johndavemanuel** [comment]
.I am not using node.js

**Comment by johndavemanuel** [comment]
I am having error in this 
data: $$("#ajaxForm").serialize()

since i put double ($) when i access on web ot it error

**Comment by rapgithub** [comment]
how have you configured your var as $$ = Dom7 ?

**Comment by rapgithub** [comment]
try this:
      $('#form-login').on('submit', function(e){

       var form_url = $(this).attr('action');
        var form_data = $(this).serialize();

        var form_ajax = $.ajax({
          url: form_url,
          type: 'POST',
          data: form_data
        });

   });

**Comment by rapgithub** [comment]
android sdk i mean when you compile or build your app for android you create your SDK for android...

**Comment by johndavemanuel** [comment]
yes i have configured your var as $$ = Dom7

**Comment by rapgithub** [comment]
have you read this ? 

https://framework7.io/docs/form-ajax-submit.html

and

https://framework7.io/docs/dom.html

framework7 use this form for ajax

$$.ajax(parameters)- Load data from the server

or 

$.ajax(parameters)- Load data from the server

in case you have your Dom7 configured with one $

all parameters are there..


I do not know if you try to send or get information from server but see the Shorthand Methods because there you can use the methods you need 



function ajaxRequest(method,url,data,callback) {

  //var data = JSON.stringify(data);
  //alert(data);
  var xhr = new XMLHttpRequest();
  //var method = 'GET' || 'DELETE' || 'POST' || 'PUT' || 'PATCH';
  var url = url;
  var asynchronous = true;
  //alert(method);
  xhr.open(method, url, asynchronous);
  xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');

  xhr.onload = function() {

        if (xhr.readyState === XMLHttpRequest.DONE) {

            var response = xhr.responseText;
            //alert(response);

            try {
              response = JSON.parse(xhr.responseText);
            } catch (err) {
              console.log(err.message + " in " + xhr.responseText);
              return;
              // not json
            }
            //alert(xhr.responseText);
            callback(response);

        }
        else {
          alert(xhr.status);
          console.log('something went wrong', status, err);

        }


  };
  
  if (['POST','PUT','PATCH'].indexOf(method) !== -1) {
    //xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    //xhr.setRequestHeader('Content-Type', 'text/plain');
    //xhr.setRequestHeader('Content-Type', 'application/json');
    //alert('POST');
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded; charset=utf-8');
    xhr.send(param(data));

  } else {
    xhr.setRequestHeader('Content-Type', 'application/json; charset=utf-8');
    //alert(JSON.stringify(data));
    xhr.send();

  }
  
}

**Comment by nolimits4web** [comment]
Make sure you have whitelisted your website in config.xml files and make sure you have correct specified CSP meta tag in your index.html file https://developers.google.com/web/fundamentals/security/csp/
