### ISSUE TITLE
iOS Input Issue in relation with Cordova and Iframe

### ISSUE THREAD

**Issue by Schnatteraffe** [framework7io/Framework7#1907]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5
* Platform and Target: Cordova, iOS

Input fields are not working correctly in relation with iOS and Cordova.

When you tap on the input field the keyboard pops up, but while typing no characters appear. Also copy, cut etc. does not work. When tap the input field a little longer (1-2 seconds) the focus is correct and you can start typing. A second click in the input field and typing does not work anymore, but keyboard is still there. It must be something that happens when Framework7 is initialized. I've tested with only the Framework7 styling and everything was fine. No problems with Android devices.

HTML and JS files are on our server and not inside the app. Cordova is used as an iframe and not using the inapp browser.

**Comment by nolimits4web** [comment]
This issue with inputs in iframe has been introduced in iOS 11, it is a system issue. Can't really do anything with it

**Comment by funkyMonkeyX** [comment]
I had the same issue with multiple iFrames. Have solved it by remove the following lines in the function handleTouchStart()

`			
if (needsFastClickTimeOut) { clearTimeout(needsFastClickTimeOut); }
needsFastClick = targetNeedsFastClick(e.target);
`
and some lines below

`
trackClick = true;
`

**Comment by funkyMonkeyX** [comment]
sorry, have not seen that this is regards to 1.6x version ... had the problem with 2.x
