### ISSUE TITLE
[V2] Drag to close Popup

### ISSUE THREAD

**Issue by D-Marc1** [framework7io/framework7#1908]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

This is starting be a widely used UX feature in iOS. Technically what you're doing is panning. You can even exit full screen on videos like that as well on iOS 11. Here's a simple demo of what I'm talking about. This is only for horizontal movements. I couldn't find a good gif for more than that. However, you can see a much cooler version of this if you just play a video. You'll see that it follows your finger movement when you try to exit full screen. I'll take video screenshot of me doing it if necessary.

![](https://i.stack.imgur.com/pkX9b.gif)

**Comment by rapgithub** [comment]
I could do something like this using animate.css library and set a popup overlay when the popup is and drag and go ... I like to call it drag and go...

**Comment by D-Marc1** [comment]
The modal on Photo Browser actually has a little bit of the functionality i'm describing. I should have used a better gif though

**Comment by rapgithub** [comment]
:) 👍

**Comment by nolimits4web** [comment]
Added in latest commits
