### ISSUE TITLE
[V2] dynamical content loaded via ajax? router ajax sync : any working sample for this?

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1910]
because no DOC yet for the v.2 i am lost here with the ajax to dynamically update content of the page because it is not as in the v.1.6.5 that in my case it was working fine... 

for the v.2 and the guides online are not clear and no working samples for this yet...

I use the one explained in the 
https://blog.framework7.io/framework7-v2-beta-41f983d6e89d

and it does not work either... 

I just need to update the content in my component page via ajax when going to that page... just simple like that but nothing seems to work in this aspect, i am using the router async and all data is in the console fine but is not not passed to the page ... 

any clues Vladimir all samples of pages for v.2 does not have a sample of ajax content for a page.. 
thanks 

how to load via ajax dynamical content for the component page requested in v2? no samples yet for router or pageinit available to know ... :(

**Comment by lailton** [comment]
Hi @rapgithub,

It's works for me:

routes: [
  // Load via Ajax
  {
    path: '/about/',
    url: './pages/about.html',
  },
  // Dynamic page from content
  {
    path: '/news/',
    content: `
      <div class="page">
        <div class="page-content">
          <div class="block">
            <p>This page created dynamically</p>
          </div>
        </div>
      </div>
    `,
  },
  {
    path: '/something/',
    async: function (resolve, reject) {
      // Get external data and return template7 template
      $.getJSON('http://some-endpoint/', function (data) {
        resolve(
          // How and what to load: template
          {
            template: '<div class="page">{{users}}</div>'
          },
          // Custom template context
          {
            context: {
              users: data,
            },
          }
        );
      });
    }
  }
],

More informations here, It is very useful and cleary.

https://blog.framework7.io/mastering-v2-router-958ea2dbd24f

**Comment by rapgithub** [comment]
Thank you for your reply but i have tried this  sync function in my case and it shows only what i have on the template: '<div class="page">{{users}}</div>' located in the router... if this is what you say it works but i need this dynamic content to be updated in the following page using componentUrl 

the following page has all the handlebars and lot of scripts js and css i need to include too.. this is why i cannot all this in the router async function but in the following page... 

the case will be to update the information in my template page that is the following page... 
have you tried to pass component information to the following page using component: ? in my case also it does not pass anything...

in my case this case it does not pass anything

this work but does not pass the params to the following page: all my data is dynamic 

    path: '/component-page/',
    componentUrl: './pages/component-page.html',
    component: {"user":"vladimir","userId":"123","posts":"about-me","postId":"1"},

in the case of ajax async it works in the template for like this
template: '<div class="page">{{users}}</div>'

but it does not pass the json object to the following page ... that is where I have all my template with handlebars created...

have you tried this way?

**Comment by rapgithub** [comment]
To show you the cases these are:

case 1 
=====================
this make the ajax request call and if user=0 return all users, and in this scenario the template: works but it shows only the template as a new page...

I just need to load an specific page for instance a component page like this componentUrl: './pages/contacts.html' and in that page update the content...

this component page has this form where contacts is my json object with all the contacts

< template >
{ {#each contacts }}
{{ this.name }} {{ this.address }}
{{ / each }}
</ template >

this code below works but it is not what i need my contact page has a lot of external js that need to load and a particular style for that page and cannot be included in the index.html 

    path: '/contacts/',
    name: 'contacts',
    async: function (resolve, reject) {
        dataf = {users:'0'};
        app.request({
              url: './path-to-scripts/script-file',
              dataType: 'json',
              data: dataf,
              method: "POST",
              crossDomain: true,
              statusCode: {
                  404: function(xhr) {
                      console.log('page not found');
                  }
              },
              complete: function(){
                  console.log('complete');
              },
              success: function(response) {
                  console.log(response);
                  resolve(
                  {
                    template: '<div class="page">{{response}}</div>'
                  },
                  {
                  context: {
                    response,
                  },
                  });
              },
              error: function(){
                  console.log('error');
              }
          })
      }


DOES  NOT WORK
also i tried to use this to send via component: all the objects  as specified in the Router information  to the following page componentUrl: './pages/users.html',  and it goes to that page but it does not send the params to that page... 

    path: '/users/',
    componentUrl: './pages/users.html',
    name: 'users',
    component: {"user":"vladimir","userId":"123","posts":"about-me","postId":"1"},

IT WORKS
but if I use the other way where all params are passed with the link then it works:
=============================================================

 <a href="/users/vladimir/123/about-me/1/">users</a>

    path: '/users/:user/:userId/:posts/:postId/',
    name: 'users',
    componentUrl: './pages/users.html',


all my data is dynamic this is why i need that!

**Comment by nolimits4web** [comment]
Added option to extend component context, should be:
```js
path: '/users/',
componentUrl: './pages/users.html',
name: 'users',
options: {context: {"user":"vladimir","userId":"123","posts":"about-me","postId":"1"}},
```

**Comment by rapgithub** [comment]
thank I will try this way!! and let you know I just need to pass an entire json object to the destination component page after ajax request returned it.. 

my component page has template and handlebars waiting for the json object to be available when entering the page.!

thanks
I hope this work for me!

**Comment by rapgithub** [comment]
thanks 👍

**Comment by rapgithub** [comment]
for sending static params it works but i need this to be updates after ajax success and I tried to put 
options: {context: {"user":"vladimir","userId":"123","posts":"about-me","postId":"1"}}, after ajax success 
inside resolve and without it and no working...  i need to pass those params dynamically in this case it is a big json object... that need to be passed to the loaded following page..

this works but only if the data is previously specified but it does not work if i add it this 
options: {context: {... after ajax success...
=============================================
path: '/users/',
componentUrl: './pages/users.html',
name: 'users',
options: {context: {"user":"vladimir","userId":"123","posts":"about-me","postId":"1"}},

I think the solution will be using template7 like in 1.6.5 that worked fine but in v.2 it is not working the same way... 

what is the alternative code for doing this that in 1.6.5 worked just fine to add content to a template with handleblars in the following page after ajax complete and success?

This worked in 1.6.5 (how to do the same in v.2?)
==============================================

 var template = $ $ ( '#template-name' ).html();
 var compiledTemplate = Template7.compile ( template ) ;
 var html = compiledTemplate({response});
 $ $( " #div-element " ).html(compiledTemplate( response) );

thanks

**Comment by nolimits4web** [comment]
Fixed in latest beta

**Comment by rapgithub** [comment]
thanks!

**Comment by caique0202** [comment]
Hi

Any solution for this?

**Comment by bahmanian** [comment]
Hello guys, I think I found the solution, here is my codes and they work very well:
{
        path: '/setting/',
        async: function (routeTo, routeFrom, resolve, reject) {
            // Requested route
            console.log(routeTo);
            // Get external data and return template7 template
            app.request.json('https://www.cheetahweb.ir/baraka/data.json',  function (data) {
                resolve(
                    // How and what to load: template
                    {
                        templateUrl: './pages/setting.html'

                    },
                    // Custom template context
                    {
                        context: {
                            users: data,
                        },
                    }
                );
            });
        }
    }

and this is setting.html:
<div class="page">
    <div class="page-content">
        <div class="block">
            <p>Hello {{users.name}}</p>
        </div>
    </div>
</div>

you cal also use post method and get data from database.
