### ISSUE TITLE
[V2] inline-pages issue in kitchen-sink

### ISSUE THREAD

**Issue by incmobs** [framework7io/Framework7#1911]
This is a:
* [x] bug

* Framework7 Version: Framework7 2.0.0-beta.11
* Platform and Target: Web (Chrome Version 61.0.3163.100 (Official Build) (64-bit))
* Live Link or JSFiddle/Codepen: Kitchen-sink (iOS)

Clicking through smart select first option (fruit) and then clicking "Back" produces the following error:

framework7.js:5617 Uncaught TypeError: Cannot read property 'f7Page' of undefined
    at n.T [as backward] (framework7.js:5617)
    at n.S [as loadBack] (framework7.js:5920)
    at framework7.js:6062
    at Array.forEach (<anonymous>)
    at n.$ [as back] (framework7.js:6060)
    at r (framework7.js:5837)
    at framework7.js:5858
    at l (framework7.js:6396)
    at p (framework7.js:6466)

Thanks for awesome Framework7 🍡 

Error only appearing in iOS

**Comment by nolimits4web** [comment]
Well, i can't replicate and see such issue on Kitchen Sink in iOS Safari. Can anyone else see such issue?

**Comment by incmobs** [comment]
rebuilt it and it is working now, sorry to waste your time (will make a donation). 

im struggling with inline pages a bit but thats probably my issue and not an issue with the script. looking forward to the docs!
