### ISSUE TITLE
[V2] 

### ISSUE THREAD

**Issue by vasilyzakharov** [framework7io/Framework7#1912]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2-beta 11.
* Platform and Target: CORDOVA

### What you did
I have got dynamically created list with Ajax on a swipeout page. I am trying to use methods:
`<li class="swipeout" @swipeout:deleted="onDeleted"><div class="swipeout-content"><a href="#" class="item-link item-content"><div class="item-inner"> <div class="item-title-row"> <div class="item-title">Title</div> </div> <div class="item-subtitle">Subtitle</div> </div> </a> </div> <div class="swipeout-actions-right"><a href="#" data-confirm="Are you sure you want to delete this event?" class="swipeout-delete swipeout-overswipe" @click="onDeleted">Delete</a></div></li>`

methods: {
      onDeleted: function () {
        var app = this.$app;
        app.dialog.alert('Thanks, event removed!');
      }

But it didn't help also I tried to use javascript:

$(document).on('deleted', '.swipeout', function () {
          app.dialog.alert('deleted');
});

### Expected Behavior
To display callback after deleting list elements.

### Actual Behavior
Callback is not fired. But list elements are deleted from the DOM.

**Comment by nolimits4web** [comment]
```js
$(document).on('swipeout:deleted', '.swipeout', function () {
  app.dialog.alert('deleted');
});

**Comment by vasilyzakharov** [comment]
Thanks a million!
