### ISSUE TITLE
[V2] All Calendars only works in internal pages but not in the root index.html

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1913]
I am trying to use the calendar picker in v.2 and in the index.html is not working and the console says: 

TypeError: undefined is not an object (evaluating 'app.calendar')

in the app.js

var app = new Framework7({
  root: '#app',
  theme: 'md',
 on: {
      pageInit: function(e, page) {
        console.log('pageInit', page);
        var self = this;
        var today = new Date();
        var app = self.$app;
        var $ = self.$;

        self.calendarRange = app.calendar.create({
          inputEl: '#demo-calendar-range',
          dateFormat: 'M dd yyyy',
          rangePicker: true
        });
      },
   ....   
}

and only onPageInit working at home but all the following methods below are not working if they are in the index.html initial page inside app.js

THESE DON'T WORK FOR THE INDEX.HTML 
======================================
 pageMounted: function(e, page) {
        console.log('pageMounted', page);
      },
      pageBeforeIn: function(e, page) {
        console.log('pageBeforeIn', page);
      },
      pageAfterIn: function(e, page) {
        console.log('pageAfterIn', page);
      },
      pageBeforeOut: function(e, page) {
        console.log('pageBeforeOut', page);
      },
      pageAfterOut: function(e, page) {
        console.log('pageAfterOut', page);
      },

thanks

**Comment by ZanderBrown** [comment]
I would imagine this is because index.html by nature is present in DOM when F7 initialises

**Comment by nolimits4web** [comment]
Don't mess APP events and component page events. Inside of APP `this` refers to app not to somewhere else:
```
var app = new Framework7({
  root: '#app',
  theme: 'md',
  on: {
      pageInit: function(e, page) {
        console.log('pageInit', page);
        var app = this;
        var today = new Date();
        var $ = app.$;

        var calendarRange = app.calendar.create({
          inputEl: '#demo-calendar-range',
          dateFormat: 'M dd yyyy',
          rangePicker: true
        });
      },
   ....   
}

**Comment by nolimits4web** [comment]
> THESE DON'T WORK FOR THE INDEX.HTML ...

Yes, it is because your index page is already in the DOM
