### ISSUE TITLE
[v2] sub-templates on template-7-pages/component-pages

### ISSUE THREAD

**Issue by cyberbeat** [framework7io/Framework7#1916]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [x ] feature-discussion (RFC)

* Framework7 Version: v2

Imagine the following use case:

I have a component page displaying some static content and some ajax-list data.
There should be a template7-template for the ajax-list-item.
On page load, the ajax-list-data is filled with some default content, but there is a search bar, to fetch different  list contents. Is it possible to define such list-item template(s) on a "componentUrl"-page?
The problem is currently, that the handlebars are always parsed. It would be cool, if that parsing could be excluded on some special html-elements (for example template7-script tags), so I could handle these templates later on page/component-init.

**Comment by nolimits4web** [comment]
Thanks it is fixed now with latest commits. Template7 must be update to latest 1.3.1 as well as it has `{{#raw}}` helper to bypass template compilition within these tags
