### ISSUE TITLE
Why were the AJAX functions removed from Dom7?

### ISSUE THREAD

**Issue by D-Marc1** [framework7io/Framework7#1917]
I recently read [this note](https://github.com/nolimits4web/Dom7/blob/92f0ed40c2b90fcfda9beacf7276a230e73d63a4/CHANGELOG.md) and all the AJAX functions no longer exist in DOM7. Just out of curiosity, what was the reason for this? Is there a different way to do it now in F7, or should we just do it the vanilla js way? I hope this isn't the case, as I really felt these functions were extremely useful.

**Comment by nolimits4web** [comment]
Because Dom7 is the DOM manipulation library, nothing common with Ajax. Ajax now is moved under `Framework7.request` or `app.request` with the same API:

* $.ajax -> app.request(...)
* $.get -> app.request.get(...)
* $.post -> app.request.post(...)
* $.getJSON -> app.request.getJSON(...)

**Comment by D-Marc1** [comment]
Ok I see. That's perfect, I had a feeling the functionality still existed in some form. Thanks, and looking forward to the official release of version 2! 😀
