### ISSUE TITLE
[v2] Page callbacks don't work (at least for pages already in dom)

### ISSUE THREAD

**Issue by cyberbeat** [framework7io/Framework7#1918]
Bug, Version: v2 beta 11

For page-callbacks to work I have to change code in framework7

Router.prototype.pageCallback = function pageCallback (callback, pageEl, navbarEl, from, to, options, pageFromEl) {
...
From
var on = options.on; if ( on === void 0 ) on = {};
to
var on = route.route.on; if ( on === void 0 ) on = {};

Also the "options.pageEvents" references should be "route.route.pageEvents".

I don't know, if this is the right place for a fix, or if there is a general structural problem elsewhere.

The options-parameter in my case is, it is the page in dom on first page:

{
  "route": {
    "query": {},
    "params": {},
    "url": "/",
    "path": "/",
    "route": {
      "path": "/",
      "name": "index",
      "url": "index.html",
      "on": {"pageInit": ...}
    }
  }
}

**Comment by nolimits4web** [comment]
This is still not working in beta and i'm not sure yet about implementation and correct place for this, but is on my roadmap. At the moment it can be used as is:

* within page components' `on`
* using usual app callback: `app.on('pageInit', ...)`
* using DOM event: `$(document).on('page:init', ...)`

**Comment by nolimits4web** [comment]
Fixed in latest beta
