### ISSUE TITLE
[v2] PhotoBrowser caption error

### ISSUE THREAD

**Issue by aporenta** [framework7io/Framework7#1919]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: v2 - beta 11

### What you did
When I create PhotoBrowser with caption only on third page (attached example), this caption is visible on first page.
![image](https://user-images.githubusercontent.com/3582031/31984802-13bcc69a-b963-11e7-9d65-48a45fd1b46b.png)

### Expected Behavior
When I don't declare caption. Caption must be hidden on selected page

### Workaround
I created caption with one blank on every page

### Code sample

    var phts = [
        {
            html: "<div>Text on page 1</div>",
        },
        {
            html: "<div>Text on page 2</div>",
        },
        {
            url: "https://www.google.si/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png",
            caption: 'Third page caption'
        }
    ];
    var pht = app.photoBrowser.create({
        photos: phts,
        initialSlide: initSlide
    });
    pht.open(initSlide);

**Comment by nolimits4web** [comment]
This should be fixed in latest beta
