### ISSUE TITLE
[v2]  Ajax async: function (resolve, reject) using it with componentUrl  not passing the ajax response :(

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1920]
I am using this below in the router.js  in my case the page it is a component page with < template > and I need to dynamically update the content of this page after ajax success...

is it possible to send this json object to the component page? this below does not work for me because it only open a new page with the template < div class="page">{{users}}< / div >

    path: '/something/',
    async: function (resolve, reject) {
      // Get external data and return template7 template
      $.getJSON('http://some-endpoint/', function (data) {
        resolve(
          // How and what to load: template
          {
            template: '<div class="page">{{users}}</div>'
          },
          // Custom template context
          {
            context: {
              users: data,
            },
          }
        );
      });
    }
  }

is there a way to pass the json object to a component page after ajax success? if I use template7data not working in my case, and if I use options: {context: {users}},

I need something like this below:

    path: '/something/',
    name: '/something/',
    componentUrl: '/pages/something.html ',

    async: function (resolve, reject) {
       app.request({
      url: 'path-to-script',
      dataType: 'json',
      success: function(response) {
        resolve(
          // How and what to load: template
          {
            template7data :  {users}, // no error but it does not work
          },
          // Custom template context
          {
            context: {
              users: response, 
            },
          }
        );
      });
    }
  }

inside my component something.html page i have:
< template >
  < div class="page" >
    < div class="page-content" style="background:#ddd" >
       {{#each users}}
          {{this}}
       {{/each}}
     </ div >
  </ div >
< /template >

any clues to make this work? I am stuck here in v.2 
thanks

**Comment by rapgithub** [comment]
sorry but i got it working now using like this:

path: '/something/',
name: '/something/',
async: function (resolve, reject) {
   app.request({
  url: 'path-to-script',
  dataType: 'json',
  success: function(response) {
    resolve(
      // How and what to load: template
      {
        template :  {users}, // no error and it does not work now object users is sent OK
        templateUrl: '/pages/something.html ',
      },
      // Custom template context
      {
        context: {
          users: response, 
        },
      }
    );
  });
}

**Comment by rapgithub** [comment]
I've got it working using like this putting the templateUrl: '/pages/something.html ', inside resolve and this way {{#each users}} works in the templateUrl page

path: '/something/',
name: '/something/',
async: function (resolve, reject) {
app.request({
url: 'path-to-script',
dataType: 'json',
success: function(response) {
resolve(
// How and what to load: template
{
templateUrl: '/pages/something.html ',
},
// Custom template context
{
context: {
users: response,
},
}
);
});
}

the problem is still that if I use other object name different of users inside context then it stop working again... :/

context: {
contacts: response,
},

for instance to send all contacts to the search page...

**Comment by rapgithub** [comment]
this is not working in a component page:


path: '/something/',
name: '/something/',
async: function (resolve, reject) {
app.request({
url: 'path-to-script',
dataType: 'json',
success: function(response) {
resolve(
// How and what to load: template
{
componentUrl: '/pages/something.html ',
},
// Custom template context
{
context: {
users: response,
},
}
);
});
}

**Comment by nolimits4web** [comment]
Fixed in latest beta

**Comment by rapgithub** [comment]
I tested and now with lastest beta everything stop working ...
resolve(... gives error in the console for template or component page...

can you give an example what did you changed and how to use it properly with ajax request on success resolve(...  it seems not to be working...

thanks

**Comment by nolimits4web** [comment]
@rapgithub have you seen my comment at https://github.com/framework7io/Framework7/issues/1925

**Comment by rapgithub** [comment]
thank you !! i will do now!! i hope get solved this way thanks

**Comment by rapgithub** [comment]
THANKS A LOT 
it is working now and the object is passed to the component page without problems! 
BIG thanks for the new release beta 15!!


My working code now after ajax request

 {
    path: '/page-loader-component/',
    async(to, from, resolve, reject) {
        data= {};
        app.request( {
            url: 'path-to-php-script', 
            dataType: 'json', 
            data: data, 
            method: "POST", 
            crossDomain: true, 
            statusCode: {
                404: function(xhr) {
                    console.log('page not found');
                }
            },
            complete: function() {
                console.log('complete');
            },
            success: function(response) {
                console.log('success');
                console.log(response);
                resolve(
                  {
                    componentUrl: './pages/page-loader-component.html',
                  },
                  {
                    context: {
                      users: response,
                  },
                  }
                );
            },
            error: function() {
                console.log('error');
            }
        });

    }


in component page:

          {{#each users}}
          {{this}}
          {{/each}}

BIG THANKS WORKING NOW!!!

**Comment by bahmanian** [comment]
Hello guys, I think I found the solution, here are my codes and they work very well:

        {
               path: '/setting/',
                async: function (routeTo, routeFrom, resolve, reject) {         
                console.log(routeTo);
                app.request.json('data/data.json',  function (data) {
                resolve(
                    // How and what to load: template
                    {
                                templateUrl: './pages/setting.html'

                    },
                    // Custom template context
                    {
                        context: {
                            users: data,
                        },
                    }
                );
            });
        }
    }

and this is setting.html:

<pre><div class="page"></pre>
    <div class="page-content">
        <div class="block">
            <p>Hello {{users.name}}</p>
        </div>
    </div>
</div>

you cal also use post method and get data from database.

**Comment by vascubrian** [comment]
Hello, any one can help
my app.js

app.onPageInit('index', function (page) {
    // Do something here for "about" page
var template = $$('#index').html();
var compiledTemplate = Template7.compile(template);
app.request.get('localhost/*****/home/TestAjax', function (data) {
 var context = data;
 var html = compiledTemplate(context);
});
}).trigger();



my view 

<script id="index" type="text/template7">
  <p>Hello, my name is {{firstName}} {{lastName}}</p>
 </script> 


its not working
