### ISSUE TITLE
[V2] Route Options not working

### ISSUE THREAD

**Issue by vasilyzakharov** [framework7io/Framework7#1921]
This is a (multiple allowed):
* [X] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

* Framework7 Version: 2 beta 11
* Platform and Target: Cordova

### What you did
I am trying to use Route Options in routes.js as described here. But getting no luck:
var routes = [
  {
    path: '/',
    url: './index.html',
    name: 'home',
    history: 'false',
    pushState: 'false',
    animate: 'false'
  }
}

### Actual Behavior
None of options are working. Please help to figure our how to achieve it with V2 router.

**Comment by nolimits4web** [comment]
They must be under `options` prop:
```js
{
path: '/',
url: './index.html',
name: 'home',
options: {
  history: false,
  ...
}
}
