### ISSUE TITLE
[V2] Open a page from push notifications

### ISSUE THREAD

**Issue by vasilyzakharov** [framework7io/Framework7#1922]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

* Framework7 Version: v2 beta 11
* Platform and Target: Cordova

### What you did
Created a page About and added to routes.js:
var routes = [
  {
    path: '/',
    url: './index.html',
    name: 'home',
    options: {
      pushState: true,
    }
  },
  {
    path: '/about/',
    url: './pages/about.html',
    name: 'about',
    options: {
      pushState: true,
    }
  }
]

Just want to mention I am using the Custom URL scheme plugin https://github.com/EddyVerbruggen/Custom-URL-scheme and the Phonegap Push plugin

### Expected Behavior
When I click on push notification with the link to myapp://#/about/ or myapp://about/ the page About should be displayed as a first page...

### Actual Behavior
Page isn't opening when the url from push notification called. Just index page being displayed. 
Even when I am trying to test it in my browser with XAMPP on by typing http://localhost/#/test/. 
Clicks on links work fine thought,

**Comment by nolimits4web** [comment]
You must call router's navigate method to navigate to such page, e.g. `app.views.main.router.navigate('/about'/)`. Or try to enable `pushState: true` on main view
