### ISSUE TITLE
[v2] Router updates

### ISSUE THREAD

**Issue by l41lt0n** [framework7io/Framework7#1925]
@nolimits4web 

Can you provide for us sample using the new features please?

 * Router
    * Added [path-to-regexp](https://github.com/pillarjs/path-to-regexp) for better route matching with support of RegExp in route path
    * Route `name` renamed to `pageName` parameter to specify page's name to load. Route `name` now means name of the route
    * Added additional routes arguments to `async` method. Now it is `async(routeTo, routeFrom, resolve, reject)`
    * `pushState` now supports for multiple Views at a time
    * Router component's context now can be extended with `options.context` route parameter
    * Router component now supports inline nested `<template>` that won't be parsed by Template7
    * Addded support for dynamic routes
    * Route events, now it is possible to specify `on` object with page events on route object

**Comment by rapgithub** [comment]
yes I want the same, any example how to use them?

**Comment by nolimits4web** [comment]
```js
...
routes: [
  {
    path: '/something/',
    async(to, from, resolve, reject) {
      resolve({
        componentUrl: 'page.html',
        on: {
          pageInit() {
            // page init
          },
        },
        options: {
          context: {
            user: 'John Doe',
          },
        },
      });
    }
  },
  {
    path: '(.*)',
    url: '404.html',
  },
]
```
For other things wait for docs
