### ISSUE TITLE
[v2] Problems with data-attributes

### ISSUE THREAD

**Issue by cyberbeat** [framework7io/Framework7#1927]
I use v2 beta 15:

It seems to be allowed to use a class "view-init" to initialize a view on startup, and use its data-attributes as its params. So I added a data attribute data-pushState="true", but the problem is, that html-attribute names are not case sensitive (so the view is initialized with not recognized "pushstate" option). Perhaps it would be better to not use camel-case for some options?

As a workaround I will add the view by hand on init.

**Comment by nolimits4web** [comment]
Use kebab-case for attributes data-push-state
