### ISSUE TITLE
[v2] Any showPreloader / hidePreloader methods in ajax async calls?

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1929]
is the any showPreloader / hidePreloader method in v.2 for using with ajax request in the router? 
I just want to show something is working... before ajax and after completed like in 1.6.5

in 1.6.5 I used myApp.hidePreloader();  to hide and myApp.showPreloader();  

I checked the page autocompleted and I see a preloader there but only for dropdown... 
how do you use the preloader in ajax async calls in the router  in v.2?

big thanks!

**Comment by nolimits4web** [comment]
`app.preloader.show()` or `app.preloader.hide()`

**Comment by rapgithub** [comment]
thanks
