### ISSUE TITLE
PhotoBrowser always reset first when pinch-zoom in Android 

### ISSUE THREAD

**Issue by francis6425** [framework7io/Framework7#1930]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5.
* Platform and Target: ANDROID

### Expected Behavior
Just like in the gallery photo viewer, user should be able to continue to zoom in or out and not reset to the initial scale every time we start to pinch on the same photo.

### Actual Behavior
When I pinch zoom in and I want to zoom more, if I pinch again it resets the image scale
I noticed that the issue is due to the return statement below but I don't know why it is required to have this condition to return in the first _place._

onGestureEnd: function (e) {
                var z = s.zoom;
                if (!s.support.gestures) {
                    if (e.type !== 'touchend' || e.type === 'touchend' && e.changedTouches.length < 2) {
                        return;
                    }
                }

**Comment by J05HI** [comment]
Have the same problem.
In v2 too.

**Comment by nolimits4web** [comment]
Fixed in latest v2 beta
