### ISSUE TITLE
[v2] Component Object - set the json object requested via ajax available to all pages no matter how deep... 

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1933]
I do not know if it is possible to keep the object passed via ajax to the component page be available to all the pages without being destroyed...

after ajax request success using 

   success: function(response) {
                    console.log(response);
                    resolve(
                      {
                        componentUrl: './pages/page-component.html',
                      },
                      {
                        context: {
                          users: response,
                      },
                      }
                    );
                }, 

the object is available in the /page-component.html' but not in any of the others pages that are called from /page-component.html...

in my case the object USERS is destroyed when changing the page and it is not available in other page, so i have to send the same request in every page to get the object again...

is it possible to keep the requested object via ajax available in every single page no matter how deep i can go this making things available all the time in the router ?

thanks

**Comment by nolimits4web** [comment]
There is a `$root` object available in components with root app data. You can specify default root data on app init:
```
new Framework7({
  data: function () {
    return {
      name: 'Vladimir'
   },
  },
}); 
```
Then in any component it will be available as `$root.name`. If you want to store there something in component then just do `$root.lastName = "Kharlampidi"`, or via app as `app.data.lastName = "Kharlampidi"`

**Comment by rapgithub** [comment]
I will try that thanks
