### ISSUE TITLE
router.back() with force:true does not refresh previous page

### ISSUE THREAD

**Issue by seme1** [framework7io/Framework7#1934]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.6.5

myApp.getCurrentView().router.back({'force':true,'pageName':'page-customSearch','reloadPrevious':true,'reload':true})

Above line is expected to go back in history till page page-customSearch is reached and then refreshes that page.
Current behavior: it correctly goes back in history to page-customSearch page but it does NOT refreshes that page.

**Comment by nolimits4web** [comment]
It won't refresh it because you use `pageName`, from where should it refresh it? Refresh works with `url` only
