### ISSUE TITLE
Swiper events on links (link-list)

### ISSUE THREAD

**Issue by cyberbeat** [framework7io/framework7#1935]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [ ] feature-discussion (RFC) / Question

* Framework7 Version: v2b15

I have a swiper, and in each slide I have a link-list.
These links should only be handled by the router, if the swipe is not succeeded (slide-changed).

I tried to handle the "touchEnd" event in the swiper, and called event.stopPropagation() but then the hover-effect on the links is stopped. How can I only disable routing in such case?

And setting 
preventClicks: true,
preventClicksPropagation: true
in the swiper does not help.

**Comment by nolimits4web** [comment]
For instance, swiper's `touchMoveStopPropagation` must be set to `false`
