### ISSUE TITLE
Keyboard issues

### ISSUE THREAD

**Issue by razaviv** [framework7io/Framework7#1936]
Hello, 

ive got some issues with keyboard, either android and iphone:

1. At start screen, when focusing on an input, the scroll get shrinked up properly so if the input is at the bottom of a page, it can be easily seen. But when switching to a different view, nothing happen - focusing on an input doesnt get the scroll to function and shift up (only in android, iphone works fine).
Maybe need to update the dom or something.
I have to mention, that myApp.picker or myApp.autocomplete methods works fine in deeper pages in contrast to the default input with scroll shrink.

2. The same thing as no 1. but with keyPad plugin - works at homepage, but not in deeper pages.

3. keyPad plugin: ive seen in the example at framework7 plugin page website that there is a way to promp a passcode!
but in plugin repot at github there isnt any information about this, maybe someone familier with this?

4. iphone: autocomplete with search bar doesnt get focus automaticlly, you should click the input manuly, people assume this is a bug and tell me this aint working.
ive tried almost everything, maybe you could solve this problem?

5. anothing thing about splashscreen: in android device i get a splash screen on load.
in iphone, in simulator and real iphone 7 device i receive the cordova default grey splashscreen.
ive used the: ionic resources which created either splash and icons.
maybe the source is too small?

thanks.

**Comment by nolimits4web** [comment]
1. It is fixed in v2
2. Same, and not related to this F7 main repo
3. There is no such
4. It is iOS limitation, it doesn't allow to focus something without user interaction, but it works fine in Cordova/Phonegap app
5. Doesn't related to F7

**Comment by razaviv** [comment]
What's Framework7 V2?
