### ISSUE TITLE
Template7 Pages do not trigger material behaviors

### ISSUE THREAD

**Issue by vuphuctho** [framework7io/Framework7#1937]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Framework7 1.6.5.
* Platform and Target: ANDROID.
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/thovu/er3avsLo/

### What you did
Enable Template7 Pages and material theme on app initialization:
```
var myApp = new Framework7({
  material: true,
  precompileTemplates: true,
  template7Pages: true,
  template7Data: {}
});
```

Add page via ```router.load``` using compiled template, which contain input with float label.

```
mainView.router.load({
  template: Template7.templates.form,
  context: {}
});
```

### Expected Behavior
Float label should behave as in kitchen sink sample

### Actual Behavior
Float label does not trigger; input label displays as normal one.

**Comment by nolimits4web** [comment]
It means you have wrong HTML layout, check the docs, for material inputs
