### ISSUE TITLE
Trouble getting inline page to load

### ISSUE THREAD

**Issue by ppetree** [framework7io/Framework7#1938]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version:  * Framework7 1.6.5
* Platform and Target: Cordova 
* Live Link or JSFiddle/Codepen: [https://jsfiddle.net/ppetree/hytfux9q/3/](https://jsfiddle.net/ppetree/hytfux9q/3/)

### What you did
I'm trying to get checkin page to load, not having any luck at all…

I've tried:
```
mainView.router.load({pageName: ‘checkin’});
<a href=”#checkin“>Checkin</a>
```
My page and view looks like this:
```
<div class="views">
  <div class="view view-main">  
    <div class="pages  toolbar-through">
    
      <div data-page="index" class="page homepage">
        <div class="page-content">
            <div id="drawer"></div>              
            <div class="logo"><a href="#checkin">CheckIn</a></div> 
        </div>
      </div>
    
      <!-- checkin page-->          
      <div data-page="checkin" class="page cached">
        <div class="page-content">
            <h1>Checking In</h1> 
    	    <img src="https://vignette.wikia.nocookie.net/inanimateinsanity/images/7/7c/TestTube2017Pose.png" />
              <p>More <b>check-in</b> stuff goes here!</p>                            
        </div>
      </div>
              
    </div>
  </div>
</div>
```

My app configuration looks like this...
```
var myApp = new Framework7({
animateNavBackIcon: true,
precompileTemplates: true,
swipeBackPage: false,
swipeBackPageThreshold: 1,
swipePanel: ”left",
swipePanelCloseOpposite: true,
pushState: true,
pushStateRoot: undefined,
pushStateNoAnimation: false,
pushStateSeparator: ‘#!/’,
template7Pages: true,
domCache: true // tried this as true and false… true makes it worse and no external pages get loaded.
});
```
What am I missing here?
Thanks,

### Expected Behavior
internal page transition to occur

### Actual Behavior
nada - nothing - popups work, slide outs work but internal pages don't

**Comment by nolimits4web** [comment]
domCache must be set on View, check the example https://github.com/framework7io/Framework7/blob/master/examples/inline-pages/js/my-app.js

**Comment by ppetree** [comment]
Perfect thanks! Spent a full 2 days mucking with that!

**Comment by ppetree** [comment]
You might wanna reopen this... I'm having the same problem again on a new project and this time domCache IS set on View... still can't get to inline pages!
