### ISSUE TITLE
Blank screen until scroll stops 

### ISSUE THREAD

**Issue by kiralikbeyin** [framework7io/Framework7#1939]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: iOS PhoneGap, iPhone 

### What you did
List view loaded with template7 after getting json data
### Actual Behavior
When i scroll to bottom, list view items not shown until scrolling ends or until i touch the screen.
 Same behavior when scrolling to top from bottom.
![5c348411-7211-4e37-bb52-610be900099b](https://user-images.githubusercontent.com/10079333/32328363-cdc7c516-bfea-11e7-8eaa-ae7664439c15.png)
![c25abc3e-e4d3-4658-b1a1-d8fcb28fed10](https://user-images.githubusercontent.com/10079333/32328364-cdfa074c-bfea-11e7-8cbc-81f024eadf04.png)

**Comment by nolimits4web** [comment]
Did you try to use WKWebView?

**Comment by kiralikbeyin** [comment]
There was a third party css element, i removed it and everything is fine with 1.6.5v

**Comment by genhaodegenhao** [comment]
There was a third party css element, i removed it and everything is fine with 1.6.5v
I also have this problem，Can you describe it in detail?

**Comment by kiralikbeyin** [comment]
Use only framework7 css thats all

**Comment by genhaodegenhao** [comment]
Thanks
