### ISSUE TITLE
Cannot Re-Add Infinite-Scroll-Preloader when already removed

### ISSUE THREAD

**Issue by arielrahmane** [framework7io/Framework7#1940]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4

* Platform and Target: CORDOVA 
                                    Cordova-Browser version: 5.0
                                    Cordova-Android  version: 6.2.3

### What I did
I'm displaying a list, which by default I have initially 10 items and when I scroll down, the Infinite-Scroll loads more items. When there are no more items to load, Infinite-Scroll is detached and Infinite-Scroll-Preloader removed with this two functions:

   myApp.detachInfiniteScroll($$('.infinite-scroll'))
   $$('.infinite-scroll-preloader').remove()

After making Pull-To-Refresh my list returns to its initially 10 items and I re-attach Infinite-Scroll and re-add Infinite-Scroll-Preloader with this two functions:

   myApp.attachInfiniteScroll($$('.infinite-scroll'))
   $$('.infinite-scroll-preloader').add()

### Expected Behavior
After detaching the Infinite-Scroll and removing the preloader, when I return to my initial 10 items when doing Pull-To-Refresh, I should be able to load more items when I scroll down again with the Infinite-Scroll while showing the preloader.

### Actual Behavior
Actually once I remove my Infinite-Scroll-Preloader, when I try to add it again it does not appear. Attaching the Infinite-Scroll works perfectly and more items are loaded when I scroll down, but without showing the preloader.

**Comment by nolimits4web** [comment]
This line doesn't make sense:
```
$$('.infinite-scroll-preloader').add()
```
```
$$('.infinite-scroll').append('<div class="infinite-scroll-preloader"><div class="preloader"></div></div>');
