### ISSUE TITLE
NavBar broken after $router.back() method with force

### ISSUE THREAD

**Issue by ryaposov** [framework7io/Framework7#1941]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5
* Platform and Target: Cordova.

### What you did
Created clean project with this webpack template. On About page, that is already included in project added click event on link with back method of router API.

**About.vue**
```
<template>
	<f7-page>
		<f7-navbar title="About" back-link="Back" sliding></f7-navbar>
		<f7-block inner>
			<p>Here is About page!</p>
			<p>You can go <f7-link @click="$router.back({url: '/form/', force: true})">back</f7-link>.</p>
		</f7-block>
	</f7-page>
</template>

...

```

### Actual Behavior

On click and after animation is done, NavBar is broken. `.navbar-inner` of previous page still has `.navbar-on-center` class, while `.navbar-inner` of new page that should be on center has `.navbar-from-left-to-center`.

![navbar](https://user-images.githubusercontent.com/5815992/32377124-c047819c-c0b7-11e7-9dbb-2fb4d966a5df.gif)

**Comment by nolimits4web** [comment]
Open Vue-related issues in appropriate repo at https://github.com/framework7io/Framework7-Vue
