### ISSUE TITLE
Migration Guide / List

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/Framework7#1942]
Good work, many improvements on v2! :-)

Is there an inofficial list to have an overview, which functions are replaced / not available anymore compared to v1 ?

Keep on the good work,

Dennis

**Comment by J05HI** [comment]
@nolimits4web 
Yeah, this would be really good to have :)

**Comment by vousys** [comment]
Excellent idea! because most functions/callbacks that we've in 1.6.5 are not availables in v2  ;(

**Comment by nolimits4web** [comment]
There isn't at the moment. Will be published a bit later

**Comment by J05HI** [comment]
@nolimits4web
Okay, great to hear :)
