### ISSUE TITLE
Popup doesn't behave correctly if using <f7-popup>

### ISSUE THREAD

**Issue by Pitouli** [framework7io/Framework7#1943]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5, used with app-framework v1.19.4
* Platform and Target: Web

### What you did
I develop an app using Vue, so all my pages are based on <f7-xxxx> tags.
In my app, there is a contact list, and in the contact page, there is an "edit" link that should open a popup.

### Expected Behavior
A popup with content inside

### Actual Behavior
If I define my popup like this, it works well: 
```
<div class="popup popup-contact-edit navbar-fixed">
	<f7-view>
		<f7-pages>
			<f7-page>
				<f7-list>
					<f7-list-button color="red">Delete this contact</f7-list-button>
				</f7-list>
			</f7-page>
		</f7-pages>
	</f7-view>
</div>
```
But if I use this, the content of the popup is now blank
```
<f7-popup class="popup-contact-edit navbar-fixed">
	<f7-view>
		<f7-pages>
			<f7-page>
				<f7-list>
					<f7-list-button color="red">Delete this contact</f7-list-button>
				</f7-list>
			</f7-page>
		</f7-pages>
	</f7-view>
</f7-popup>
```
Am I doing something wrong?

**Comment by nolimits4web** [comment]
It is because it is not render its content while it is closed. As the workaround you can do it like:
```
<f7-popup :opened="popupOpened" @opened="popupOpened = true" @closed="popupOpened = false">
```
Make sure to store that `popupOpened` variable somewhere
