### ISSUE TITLE
[v2] path: '/page-name/:id/'  pass the param id inside the async function before request? 

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1944]
in my case i need to get the :id before the ajax request because every link is linked to a specific ajax request call id....

is there a way to get the param :id value before ajax request call?

I tried to look for this value inside the router app and view and is not there only i can get with this.url the url without params..

my code

 path: ' /page-name/:id/ ' ,
 async(to, from, resolve, reject) {

    console.log(this.params); // I need here to get the params id of the url above.
    id = this.params.id // this is empty..
    app.request( {
    url: 'script-name?'+id, 
     ...

any solution to pass the url params before ajax request?

**Comment by nolimits4web** [comment]
console.log(to)

**Comment by rapgithub** [comment]
I wil check it now thanks...

**Comment by rapgithub** [comment]
thanks it is there  console.log(to.params.id); 
big thanks
