### ISSUE TITLE
[v2] how to refresh/update a component page template data after it was already loaded? router.navigate creates a new page but it does not update the current page template...

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1948]
in my component template page i need to put filters like: filter price ASC DESC, filter locations nearby to my location etc...

I need to apply these filter in the same component page the data is being displayed...
I am using now this method @click="updatePriceOrder" for instance

I call via ajax request the new json sending the filters params to get the reply and I can print this in the console, but what I cannot do it is update the template with this new data...

I have tried render(response); and it does not work 

I have tried also

async(to, from, resolve, reject) { resolve({....  }); and resolve needs the componentUrl page and gives error here too

I have tried 
template = Template7.compile(content);
var result = template(data);
next(result);

and i get the error also..

any ideas how can I update the template of this component page after applying the filters? my template has all the handlebars elements that need to be updated with the new json object already filtered..

I need to update the current page with the new data filtered... i thought about reload: true or shoud I use router.navigate(.... specifying the same current page as target? for this to work?

any reload method after ajax request success is returning the new object ? I am a little confused in V2.

my current code for @click=updatePriceOrder below:

I am using reloadCurrent: true,  

 updatePriceOrder: function (filter) {
        var self = this;        
        var $ = this.$;
        var app = this.$app;
        var router = this.$router;
        router.navigate( {
            url:'/page-name/', 
            route: {
                path: '/page-name/', async(to, from, resolve, reject) {
                app.request( {
                  url: 'script-name', 
                  dataType: 'json', 
                  data: data, 
                  method: "POST", 
                  crossDomain: true, 
                  preloader: true, 
                  statusCode: {
                    404: function(xhr) {
                    console.log('page not found');
                    }
                  },
                  beforeSend: function() {
                    console.log('beforeSend');
                  },
                  complete: function() {
                    console.log('complete');
                  },
                  success: function(response) {
                    console.log('success');
                    console.log(response);
                    app.dialog.close();
                    resolve({componentUrl: './pages/page-name.html'},{context: {json: response}});
                  },
                  error: function() {
                    console.log('error');
                  }
                });
                }
            },
            reloadCurrent: true, 
            pushState: true,
        });
      },  

or what is the current method in V2 to reload the current page template? in previous version we used to use this : 

mainView.router.load({
    reload: true,
    template: ...,
    context: ...
});

or how to update the handlebar template in the component page when data is updated ? 
render() in this case it does not work either ...

thanks Vladimir

**Comment by nolimits4web** [comment]
Please don't create such long titles! There is a description section for this. F7 doesn't have data binding so it won't work/updated. You need to update content manually (using DOM-manipulations/templates/etc.) Otherwise you can check the F7-Vue version, Vue.js allows it easily

**Comment by caique0202** [comment]
F7 V2 does not support Vue. How to proceed in this case?

**Comment by nolimits4web** [comment]
> F7 V2 does not support Vue
It does support Vue

**Comment by caique02** [comment]
So maybe a misunderstanding due to this message on the documentation “Current Framework7 Vue documentation is for Framework7 v1.x and for Framework7 Vue v0.x and not compatible with Framework7 v2”. Any updates on the documentation?

**Comment by nolimits4web** [comment]
Documentation will be released next week. But the library itself is ready
