### ISSUE TITLE
router.load empty content (onPageInit)

### ISSUE THREAD

**Issue by TCattd** [framework7io/Framework7#1949]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5
* Platform and Target: Codova iOS (and Cordova Android)

### What you did
I have a view that need to load another view from onPageInit.
I now know that this shouldn't be allowed, because after searching for a while, i got to see this issues:
https://github.com/framework7io/Framework7/issues/1099
https://github.com/framework7io/Framework7/issues/634

The weird thing is that even without setting allowPageChange = true in this app, it worked just fine in browser and Android.
We already release the Android version of the app without the allowPageChange trick, and it works just fine.

But, on iOS it doesn't work, not even setting allowPageChange to true before calling router.load.

I have tried (inside onPageInit):
```
myApp.mainView.allowPageChange = true;
mainView.router.load({url:'anotherpage.html', ignoreCache: true, reload: false });
```

And

```
mainView.allowPageChange       = true;
mainView.router.load({url:'anotherpage.html', ignoreCache: true, reload: false });
```

...but still doesn't work on iOS. Not with router.load and router.loadPage. Same result. Nothing loads.

The view is the main view, by the way.

And, again, this app (even without the allowPageChange) works just fine on Android and the Browser.

### Expected Behavior
Explained above. Sorry.

### Actual Behavior
Same. Explained above. Sorry again.

Thanks in advance for the time.
Esteban

**Comment by TCattd** [comment]
Turns out that mainView.allowPageChange = true; it's working.
I resorted to the good old console.log trick to see whats was going on on F7.

Check: http://prntscr.com/h738te and http://prntscr.com/h738x7

It was set to true.

So i added some more logs here: http://prntscr.com/h7399n

And got this: http://prntscr.com/h739gh

Empty content, and error true.

That's calling:
```
mainView.router.load({url:'home.html', ignoreCache: true, reload: false});
mainView.router.loadPage('home.html');
```
...any of those alternatives.

This exact same app works on Android, as i said, and without issues. Browser too.

Don't know whats happening on iOS here (iOS 11.1 BTW).

Any help or direction it's appreciated, please.

**Comment by TCattd** [comment]
Made a test from scratch. Created a new app: cordova create app-f7test

Installed F7 via bower.
Put the F7 templates, index.html, about.html and a pageinit.html test page inside.
Just followed the guide at https://framework7.io/docs/get-started.html

Added a very simple app.js initializing F7:
```
// Initialize app
var myApp = new Framework7();

// If we need to use custom DOM library, let's save it to $$ variable:
var $$ = Dom7;

// Add view
var mainView = myApp.addView('.view-main', {
  // Because we want to use dynamic navbar, we need to enable it for this view:
  dynamicNavbar: true
});

myApp.onPageInit('index', function (page) {
	console.log('onPageInit index');

	$$(document).on('click', '.testclick', function(event){
		console.log('.testclick cliked');
		mainView.allowPageChange = true;
		mainView.router.load({url:'pageinit.html', ignoreCache: true, reload: false});
		return false;
	});
}).trigger();

myApp.onPageInit('pageinit', function (page) {
	console.log('onPageInit pageinit');

	$$(document).on('click', '.gobackclick', function(event){
		console.log('.gobackclick cliked');
		mainView.allowPageChange = true;
		mainView.router.load({url:'index.html', ignoreCache: true, reload: false});
		return false;
	});
});
```

It works. Browser and iOS (on device).

So it's my issue i suppose. At some point something broke iOS compatibility on my app.

The weird issue is that in Browser and Android, the app still works just fine.

Will keep searching and testing.

**Comment by mohshraim** [comment]
try to use after animate event of your target page..
if it doesn't work, add delay timer to make sure the animation end. this will solve the problem as work around..

**Comment by nolimits4web** [comment]
Sorry, but it is not allowed to call `load` within `pageInit`

**Comment by TCattd** [comment]
@nolimits4web i know, sorry.

I read about the mainView.allowPageChange trick, and it works fine in my app on Android. That's why i opened this issue.

Anyhow, nevermind.

I found the culprit. It was cordova-plugin-wkwebview-engine (the plugin).
Once i changed it to cordova-plugin-ionic-webview, the app worked again without issues.
Took me a while to figure it out.

Thanks for the time, @nolimits4web
