### ISSUE TITLE
Pass Custom Context

### ISSUE THREAD

**Issue by sraychev** [framework7io/Framework7#1950]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
I am trying to pass an object/variable from one page to another. I used your example from:
https://framework7.io/docs/template7-pages.html#pass-custom-context

So in my index.html I have:
`<a href="recipe_details.html" data-context='{"tel": "(999)-111-22-33", "email": "contact@john.doe"}' >View Recipe</a>`

when recipe_details.html loads {{tel}} us undefined and app crashes

### Expected Behavior
I am expecting to pass the variable when clicked on the <a> tag

### Actual Behavior
Variable is undefined.

**Comment by rapgithub** [comment]
version 2?

**Comment by sraychev** [comment]
Framework7 1.4.0 

1 my-app.js
`var myApp = new Framework7({


    preprocess: function (content, url, next) {

        if (url === 'index.html') {
            // For example, we will retreive template JSON data using Ajax and only after that we will continue page loading process
            var post_data = {
                action_type: 'get_homepage'
            };
            callAPI('homecontent.php', post_data, function (result) {
                var resultContent;
                if (result == 'API error') {
                    resultContent = Template7.compile(content)({
                        error: true
                    });
                }
                else {
                    //console.log((result[0]));
                    resultContent = Template7.compile(content)({
                        recipe_of_the_day: result[0],
                        new_products: result[1]
                    });
                }
                next(resultContent);
            });
            // Now we shouldn't return anything
        }  
        

        else {
            
            var template = Template7.compile(content);
            var resultContent = template();

            return resultContent;
        }
    }
});`

this file gets the recipes from server and in preprocess assigns it to index.html

**Comment by sraychev** [comment]
2. index.html

...some code..
`<p>{{recipe_of_the_day.title}}</p>`
... some code...

I can access the recipe, but now I want to pass it over to next page, so testing with hardcoded data
`<a href="recipe_details.html" data-context='{"tel": "(999)-111-22-33", "email": "contact@john.doe"}' >View Recipe</a>`

**Comment by sraychev** [comment]
1.7.0

**Comment by rapgithub** [comment]
did you enable this?

precompileTemplates: true, //
template7Pages: true, 

when passing custom text be sure  to have this data-template specified like below that is the name of the template id you are trying to pass the custom data!

<a href="#" data-template="aboutTemplate" data-context='{"name": "John Doe", "age": "35"}'>About Me</a>


<script id="aboutTemplate" type="text/template7">
  <div class="page" data-page="about">
    <div class="page-content">
        <p>Hell, my name is {{name}}. I am {{age}} years old:</p>
    </div>
  </div>
</script>

let me know if now works! add the data-template reference

**Comment by rapgithub** [comment]
to load this in another page you can use also this:

mainView.router.load({
url: 'recipe_details.html',
    template: Template7.templates.aboutTemplate,
    context: {
        name: 'John Doe',
        age: 35
    }
})

**Comment by sraychev** [comment]
> precompileTemplates: true, //
template7Pages: true,

when passing custom text be sure to have this data-template specified like below that is the name of the template id you are trying to pass the custom data!

< a href="#" data-template="aboutTemplate" data-context='{"name": "John Doe", "age": "35"}' > About Me < /a>

<script id="aboutTemplate" type="text/template7">
Hell, my name is {{name}}. I am {{age}} years old:

</script>

Forget it. I've tried that already. I give up. Im just gonna make another ajax call event thou repetitive

**Comment by rapgithub** [comment]
send me your ajax call! maybe i can send you the one i use 
regards I hope you can get it resolved

**Comment by rapgithub** [comment]
lastest version before 2 it is 1.6.5? where did you get the version 1.7?

**Comment by sraychev** [comment]
Ok, so I created a new PhoneGap project and this comes with Framework7. I openened lib/framework7/js/framework7.js and it stated;

/**
 * Framework7 1.4.0
 * Full Featured Mobile HTML Framework For Building iOS & Android Apps
 * 
 * http://www.idangero.us/framework7
 * 
 * Copyright 2015, Vladimir Kharlampidi
 * The iDangero.us
 * http://www.idangero.us/
 * 
 * Licensed under MIT
 * 
 * Released on: December 7, 2015
 */

**Comment by sraychev** [comment]
I have 3 files:

1. my-app.js

`var myApp = new Framework7({

    //template7Pages: true,

    // Hide and show indicator during ajax requests
    onAjaxStart: function (xhr) {
        myApp.showIndicator();
    },
    onAjaxComplete: function (xhr) {
        myApp.hideIndicator();
    },
    preprocess: function (content, url, next) {

        if (url === 'index.html') {
            // For example, we will retreive template JSON data using Ajax and only after that we will continue page loading process
            var post_data = {
                action_type: 'get_homepage'
            };
            callAPI('homecontent.php', post_data, function (result) {
                var resultContent;
                if (result == 'API error') {
                    resultContent = Template7.compile(content)({
                        error: true
                    });
                }
                else {
                    //console.log((result[0]));
                    resultContent = Template7.compile(content)({
                        recipe_of_the_day: result[0],
                        new_products: result[1]
                    });
                }
                next(resultContent);
            });
            // Now we shouldn't return anything
        }  
        
        else {
            
            var template = Template7.compile(content);
            var resultContent = template();

            return resultContent;
        }
    }
});`

Index page uses preprocess to make ajax call get the recipe of the day from server, then page is compiled and displayed. So far so good.

**Comment by sraychev** [comment]
2. index.html

`                                {{recipe_of_the_day.title}} <br>
                                <a href="recipe_details.html"  >View Recipe</a>`

Recipe title is displayed, now I want when the < a > tag is clicked to pass the whole recipe to the details page to show the title, description, ingridients and so on

**Comment by sraychev** [comment]
3. recipe_details.html

`                <p>{{recipe_of_the_day.title}}</p>
                <p>{{recipe_of_the_day.description}}</p>`

I've tried every example and I the only way I can pass a variable to the recipe_details page is if I add another "else if (url === 'recipe_details.html') " in the preprocess

**Comment by sraychev** [comment]
I just came with another solution. When ajax returns the recipe in preprocess for index.html save in local storage, then in preprocess of recipe-details retrieve from local storage. Works for me. Just wish there was an easier way

**Comment by rapgithub** [comment]
here i am sending you my test and with version 1.6.5 and works the only thing it does not work it is mainView.router.load but the rest it is working! i hope you came out with this test with the solution for you!

pay attention that you need this in the declaration

var myApp = new Framework7({
    template7Pages: true,
    precompileTemplates: true, //
    domCache: true,

check the zip file with all my tests! it will be interesting if you send me yours to see how you made it work! but in my case in the tests it works for all but not for mainView.router.load method...

check the text!! I included a json test too... 

[f71.6.5.zip](https://github.com/framework7io/Framework7/files/1455417/f71.6.5.zip)

:)

**Comment by sraychev** [comment]
Thanks a lot rapgithub
I examined your code and I see why mine was failing. In mine app definition in preprocess I had

`else {
            
            var template = Template7.compile(content);
            var resultContent = template();

            return resultContent;
        }`

//this will trow error

and you have :`else { next(content);}`

//this will work fine

**Comment by sraychev** [comment]
see edited my-app.js

[f71.6.5re.zip](https://github.com/framework7io/Framework7/files/1455732/f71.6.5re.zip)

**Comment by rapgithub** [comment]
OK :)

**Comment by nolimits4web** [comment]
There was one more solution to pass context directly:
```js
Template7.registerHelper('json_stringify', function (context) {
    return JSON.stringify(context);
});
```
```html
{{recipe_of_the_day.title}}
<br>
<a href="recipe_details.html" data-context='{{json_stringify recipe_of_the_day}}'>View Recipe</a>

**Comment by sraychev** [comment]
Thanks Vladimir, I like your suggestion. Though, I must add it will break depending on the recipe_of_the_day content. For example the recipe_of_the_day had a field ingridients:

`"ingredients":"1 rabbit\r\n2 onions"`

So the slashes "\" will crash it.
My current solutions is to replace it with <br> tag since that is how the customer will be expecting to see it anyway.
`Template7.registerHelper('json_stringify', function (context) {

    var stringified = JSON.stringify(context);
    stringified = stringified.replace(/[\\]r/g, '<br>');
    stringified = stringified.replace(/[\\]n/g, '<br>');

    return stringified;
});`

**Comment by rapgithub** [comment]
Vladimir what about in v2? 

I tried the same things of version 1.6.5 but in v2 they do not work in the same way...
I need to pass an entire json object from one page to another page without having to read it in every page all the time...

data-context= in the html link as below seems not to work in version 2?

what is the equivalent in v2. for 

this 
            mainView.router.load({ 
            reload: true, 
            reloadPrevious: false,
            url: 'recipe_details_router.html', 
            context: {"title":"Pizza","description":"description mainView.router"},
            });

this
                content = Template7.compile(content)({
                context: response,
                });
                next(content);

or this

< a href="page-context.html" data-context='{"title":"{{context.title}}","description":"{{context.description}}"}' class="item-link">link </ a >

or this

< a href="#" onClick="mainView.router.load({ url: 'page-router.html', context: {title: '{{context.title}}', description: '{{context.description}}' }})" class="item-link">link </ a >


thanks
