### ISSUE TITLE
enhancement request - button callbacks all around.

### ISSUE THREAD

**Issue by ppetree** [framework7io/Framework7#1951]
This is a (multiple allowed):
* [x] enhancement

* Framework7 Version: 2.x

### Expand a function
What I'd like is to expand the following:
```
myApp.alert("User message/prompt.", "Title");
myApp.notification({...});
```

### Desired Behavior
Add another optional parameter that allows us to define the buttons and callbacks for those buttons.
The third parameter would look like this:
```
        {'buttons':  [
                        {caption: 'Yes', callback: function() { 
                              alert("Yes button was clicked.");
                              return(true); }},
                        {caption: 'No', callback: function() { 
                             alert("No button was clicked.");
                             return(false); }},
                        {caption: 'Cancel', callback: function() { 
                             alert("Cancel button was clicked.");
                             return(false); }}
                    ]}
```
It would look something like this:
myApp.alert("User message/prompt.", "Title",  {'buttons':  [
                        {caption: 'Yes', callback: function() { 
                              alert("Yes button was clicked.");
                              return(true); }},
                        {caption: 'No', callback: function() { 
                             alert("No button was clicked.");
                             return(false); }},
                        {caption: 'Cancel', callback: function() { 
                             alert("Cancel button was clicked.");
                             return(false); }} 
              ]});

This would give us complete control over the # of buttons, the button text, the call backs etc.
You could add other parameters as well... such as {type: question/warning/information/etc} which could automatically control the icon (now called media) and this would expand the option for the notification buttons by adding the callbacks.

Make sense?

**Comment by nolimits4web** [comment]
All these callbacks are available, check the docs http://framework7.io/docs/modal.html and http://framework7.io/docs/modal.html#custom-modals
