### ISSUE TITLE
how to run js on other page like on about?

### ISSUE THREAD

**Issue by varunajmera0** [framework7io/Framework7#1955]
This is my code but it doesnt work why? 
var $$ = Dom7;
$$(document).on('page:init', function (e) {
        var page = e.detail.page;
        // Code for About page
        if (page.name === 'about') {
            // We need to get count GET parameter from URL (about.html?count=10)
            var count = page.query.count;
            // Now we can generate some dummy list
            var listHTML = '<ul>';
            for (var i = 0; i < count; i++) {
                listHTML += '<li>' + i + '</li>';
            }
            listHTML += '</ul>';
            // And insert generated list to page content
            $$(page.container).find('.page-content').append(listHTML);
            alert('helllll')
        }
    })

**Comment by l41lt0n** [comment]
`var $$ = Dom7;
$$(document).on('page:init', function (e) {
var page = e.detail.page;
// Code for About page
if (page.name === 'about') {
// We need to get count GET parameter from URL (about.html?count=10)
var count = page.query.count;
// Now we can generate some dummy list
var listHTML = 'test';
for (var i = 0; i < count; i++) {
listHTML += i;
}

// And insert generated list to page content
$$(page.container).find('.page-content').append(listHTML);
alert('helllll');
}
})`

**Comment by varunajmera0** [comment]
This is my code for click event on button using id or i have tried div in place of button but it doesnt work.



<script type="text/javascript" charset="utf-8">
    var $$ = Dom7;
    $$(document).on('page:init', function (e) {
        var page = e.detail.page;
// Code for About page
        if (page.name === 'about') {

           $$('#takeVideo').click(function () {
               alert('hi');
           })
        }
    })
</script>


<div class="navbar">
    <div class="navbar-inner">
        <div class="left">
            <a href="#" class="back link">
                <i class="icon icon-back"></i>
                <span>Back</span>
            </a>
        </div>
        <div class="center sliding">About</div>
        <div class="right">
            <a href="#" class="link icon-only open-panel"><i class="icon icon-bars"></i></a>
        </div>
    </div>
</div>
<div class="pages">
    <div data-page="about" class="page">
        <div class="page-content">
            <div class="content-block">
      
                <button id="takeVideo">Take Video</button>
                <div id="videoArea"></div>
            </div>
        </div>
    </div>
</div>
<script>

</script>
<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript" src="lib/framework7/js/framework7.min.js"></script>
<script type="text/javascript" src="js/my-app.js"></script>

**Comment by varunajmera0** [comment]
This is my code for click event on button using id or i have tried div in place of button but it doesnt work.


<script type="text/javascript" charset="utf-8">
    var $$ = Dom7;
    $$(document).on('page:init', function (e) {

        var page = e.detail.page;

// Code for About page
        if (page.name === 'about') {

           $$('#takeVideo').click(function () {

               alert('hi');
           })
        }
    })
</script>

<div class="navbar">
    <div class="navbar-inner">
        <div class="left">
            <a href="#" class="back link">
                <i class="icon icon-back"></i>
                <span>Back</span>
            </a>
        </div>
        <div class="center sliding">About</div>
        <div class="right">
            <a href="#" class="link icon-only open-panel"><i class="icon icon-bars"></i></a>
        </div>
    </div>
</div>
<div class="pages">
    <div data-page="about" class="page">
        <div class="page-content">
            <div class="content-block">
      
                <button id="takeVideo">Take Video</button>
                <div id="videoArea"></div>
            </div>
        </div>
    </div>
</div>
<script>

</script>
<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript" src="lib/framework7/js/framework7.min.js"></script>
<script type="text/javascript" src="js/my-app.js"></script>

**Comment by nolimits4web** [comment]
Use page callbacks http://framework7.io/docs/page-callbacks.html
