### ISSUE TITLE
Inline picker screen orientation bug

### ISSUE THREAD

**Issue by joakimwennergren** [framework7io/Framework7#1956]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.0
* Platform and Target: IOS/Android

### What you did
Followed the example given.

### Expected Behavior
The picker to be working in both orientations.

### Actual Behavior
The inline picker gets "chopped up" and only the first letters show when orienting the device from landscape to portrait or vice versa.

**Comment by nolimits4web** [comment]
Please, update to latest version
