### ISSUE TITLE
[v2] onAjaxStart & onAjaxComplete

### ISSUE THREAD

**Issue by JosephShenton** [framework7io/Framework7#1957]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 2.0

Hi, i was wondering if we will be seeing the feature from Framework7 v1.x.x `onAjaxStart` & `onAjaxComplete` in Framework7 v2? I am using Framework7 v2 for a new app and this is a key feature and I do not want to have to rewrite the entire app using Framework7 v1.x.x. Is it possible we will see this soon?

**Comment by nolimits4web** [comment]
```
var app = {
  on: {
    routerAjaxStart: function () { /* ... */ },
    routerAjaxComplete: function () { /* ... */ },
}
