### ISSUE TITLE
[v2] Virtual List filtering

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1964]
Hi Vladimir I tried to use virtual List filtering in v2 without any success... is the any sample of virtual list filtering you can provide? the virtual list sample in the version v2 does not include how to make a filter so I can filter in the same page the list according some preferences...

this is in my case:

Price Ordering
Lowest Price
etc...

it will be great if framework7 has some filtering system similar to https://desandro.com/#isotope isotope for lists too...

**Comment by nolimits4web** [comment]
There is a vl method called `filterItems` where you need to pass and array with indexes of matching items. Same as in v1. And it works as you may use on Virtual List demo in Kitchen Sink when you try to search on the top. Searchbar uses same `filterItems` method

**Comment by rapgithub** [comment]
thanks I will try this
