### ISSUE TITLE
[v2] Passing custom context in v2 like in version 1.6.5

### ISSUE THREAD

**Issue by rapgithub** [framework7io/Framework7#1966]
Vladimir what about in v2? 

following the issue #1950 

I tried the same things of version 1.6.5 but in v2 they do not work in the same way...
I need to pass an entire json object from one page to another page without having to request ajax again the same object to read it in every page all the time...

data-context= in the html link as below seems not to work in version 2?

what is the equivalent in v2. for 
=======================
this 
===
            mainView.router.load({ 
            reload: true, 
            reloadPrevious: false,
            url: 'recipe_details_router.html', 
            context: {"title":"Pizza","description":"description mainView.router"},
            });

this
===
                content = Template7.compile(content)({
                context: response,
                });
                next(content);

or this
=====

< a href="page-context.html" data-context='{"title":"{{context.title}}","description":"{{context.description}}"}' class="item-link">link </ a >

or this
=====

< a href="#" onClick="mainView.router.load({ url: 'page-router.html', context: {title: '{{context.title}}', description: '{{context.description}}' }})" class="item-link">link </ a >

thanks

**Comment by nolimits4web** [comment]
This works in v2
```
< a href="page-context.html" data-context='{"title":"{{context.title}}","description":"{{context.description}}"}' class="item-link">link </ a >
```

This:
```
< a href="#" onClick="mainView.router.load({ url: 'page-router.html', context: {title: '{{context.title}}', description: '{{context.description}}' }})" class="item-link">link </ a >
```
->
```
< a href="#" onClick="mainView.router.navigate('page-router.html', {context: {title: '{{context.title}}', description: '{{context.description}}' }})" class="item-link">link </ a >
```

This
```js
mainView.router.navigate('recipe_details_router.html', { 
        reloadCurrent: true, 
        context: {"title":"Pizza","description":"description mainView.router"},
});
```

**Comment by nolimits4web** [comment]
Please, use Forum for questions forum.framework7.io

**Comment by rapgithub** [comment]
big thanks

**Comment by rapgithub** [comment]
I try this before not success but I will try another way to see if working in last version

**Comment by juliusbangert** [comment]
Please could someone give a full example of how to pass variables between pages using this method. I'm a noob and I'm just not getting it, I've been trying to piece together information from forums but the pre-version 2 example isn't available ... I'm using version 2. Help would be greatly appreciated.
