### ISSUE TITLE
[v2] Display active tab ID

### ISSUE THREAD

**Issue by vasilyzakharov** [framework7io/Framework7#1968]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2 beta 17

* Platform and Target: Cordova

### What you did
Using the code below on a tab page
```
return {
pageInit: function(e, page) {
        $('#about').on('show', function () {
            console.log('About Tab is visible');
        });

        $('#about').on('tab:show', function () {
            console.log('Tab 1 is visible');
        });
} 
}
```

### Expected Behavior
Should get a tab ID, on the example above just to display text in my console.

### Actual Behavior
Nothing happens

**Comment by nolimits4web** [comment]
And where did you put this code? Maybe you can show full page code?

**Comment by vasilyzakharov** [comment]
`<div class="page">
  <div class="navbar">
    <div class="navbar-inner sliding">
      <div class="left">
        <a href="#" class="link back">
          <i class="icon icon-back"></i>
          <span class="ios-only">Back</span>
        </a>
      </div>
      <div class="title">Animated Tabs</div>
    </div>
  </div>
  <div class="toolbar tabbar">
    <div class="toolbar-inner">
      <a href="./" class="tab-link tab-link-active" data-route-tab-id="about">Tab 1</a>
      <a href="contacts/" class="tab-link" data-route-tab-id="contacts">Tab 2</a>
      <a href="cv/" class="tab-link" data-route-tab-id="cv">Tab 3</a>
    </div>
  </div>
  <div class="tabs-animated-wrap">
    <div class="tabs tabs-routable">
      <div id="about" class="page-content tab tab-active">
        <div class="block">
          <p>About Tab 1 content</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam enim quia molestiae facilis laudantium voluptates obcaecati officia cum, sit libero commodi. Ratione illo suscipit temporibus sequi iure ad laboriosam accusamus?</p>
        </div>
      </div>
      <div id="contacts" class="page-content tab">
        <div class="block">
          <p>Contacts Tab 2 Form</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam enim quia molestiae facilis laudantium voluptates obcaecati officia cum, sit libero commodi. Ratione illo suscipit temporibus sequi iure ad laboriosam accusamus?</p>
        </div>
      </div>
      <div id="cv" class="page-content tab">
        <div class="block">
          <p>CV Tab 3 content</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam enim quia molestiae facilis laudantium voluptates obcaecati officia cum, sit libero commodi. Ratione illo suscipit temporibus sequi iure ad laboriosam accusamus?</p>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  return {
    on: {
      pageMounted: function(e, page) {
        console.log('pageMounted', page);
      },
      pageInit: function(e, page) {
        $('#about').on('show', function () {
            console.log('About Tab is visible');
        });

        $('#about').on('tab:show', function () {
            console.log('Tab 1 is visible');
        });
        $('#contacts').on('tab:show', function () {
            console.log('Tab 2 is visible');
        });
        $('#cv').on('tab:show', function () {
            console.log('Tab 3 is visible');
        });
        console.log('pageInit', page);
      },
    }
  }
</script>
`

**Comment by nolimits4web** [comment]
1. Where is the `<template>` tag surrounding page?
2. Does line `console.log('pageInit', page);` work?

**Comment by vasilyzakharov** [comment]
With the <template> tag it showing console.log('pageInit', page); 
But how to get the ID of the current/active tab?
Thank you

**Comment by nolimits4web** [comment]
```js
pageInit: function(e, page) {
  var activeTab = this.$el.find('.tab-active').attr('id');
  console.log(activeTab);
}
```
