### ISSUE TITLE
SwipePanel not working in Framework7 2.0.0-beta.8

### ISSUE THREAD

**Issue by M4ttscx** [framework7io/Framework7#1969]
Hello, I'm newbie, I'm using Framework7 2.0.0-beta.8, it has a bug that the "swipePanel" function does not work.

Someone give a light?

**Comment by SpiderNeo1** [comment]
Hello, 
Have you tested on the latest version : Framework7-2.0.0-beta.17 ?

**Comment by nolimits4web** [comment]
Update to latest beta

**Comment by M4ttscx** [comment]
Framework7-2.0.0-beta.17, not working in android cordova.
