### ISSUE TITLE
White page on Android App

### ISSUE THREAD

**Issue by eradin** [framework7io/Framework7#1970]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2 Beta 17
* Platform and Target: Android (potentially ios)
* Live Link or JSFiddle/Codepen:  N/A

### What you did
Hello World using "Initial Page Routes" (per blog discussion)

### Expected Behavior
It should work
### Actual Behavior
Works on desktop web browser.  Fails on android phone device.

Built a simple V2 hello world app for testing.  Runs perfectly in desktop web browser.  When installed on android device, app starts with a blank page and appears to freeze.

Test scenarios all built with Phonegap Build cli 6.5: 
1. F7 1.6 hello world version.  Runs perfectly in all environments.
2. F7 2.0 hello world version with index.html containing home page.  Works in all environments.
3. F7 2.0 hello world but moved home contents to home.html as discussed in blog post. Works in desktop web browser, Fails android with blank home page.
4. Repeated #3 but commented out cordova.js.  Works in desktop browser and also phone.

Providing a fiddle is not helpful because it works fine in web browser.  Attaching zipped project files.
[fw72.zip](https://github.com/framework7io/Framework7/files/1500935/fw72.zip)

**Comment by nolimits4web** [comment]
Looks like you have an issue with Ajax security rules, try to add the following meta tag to your HTML:
```
<meta http-equiv="Content-Security-Policy" content="default-src * 'self' gap://ready data: blob: 'unsafe-inline' 'unsafe-eval' ws: wss:;">
```
Tweak it according to your needs. More about CSP at https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by eradin** [comment]
Thanks.  I already had the standard meta tags from the hello world template.  I tried the one above but the same result of no home page loading.  

I don't think it's related to ajax because in the index.html (no home.html) approach, it all works fine including ajax load of about.html. It breaks once I use the home.html approach.

Can you think of anything else I am doing wrong?

**Comment by nolimits4web** [comment]
It is fine and recommended way that you need to use device ready event for cordova app. To test in browser just do single condition where to init all the stuff
Firefox error is because of wrong configured CSP meta tag.

**Comment by eradin** [comment]
Ok, got it working.  For anybody who stumbles across this post, here is the final word so they don't burn 4 days of time figuring this out.  This will eventually need to find it's way into the documentation.

First off, the component architecture is very nice and should be used.  It makes your code easier to maintain and debug and substantially reduces the code in your app.js.  The only issue is turning your home page into a component, that requires a little more work.

1. To start, do as the blog post states, create a home.html file with your home page details, make changes to routes.js and index.html and add view create call in app.js.  Home.html can be standard html markup (no component) or a component.  If it's not a component, the blog procedure will work as advertised.  The following steps are if it's a component (i.e. wrapped in <template>).

2. The code block:
myApp.views.create('.view', {
url: '/'
});

needs to be put inside your deviceready handler.  If you do this, the app won't run in your desktop browser so here are my changes to app.js to solve the problem:

var isCordovaApp = document.URL.indexOf( 'http://' ) === -1 && document.URL.indexOf( 'https://' ) === -1;

if ( isCordovaApp ) {
	// Handle Cordova Device Ready Event
	$$(document).on('deviceready', function() {
    	console.log("Device is ready!");
		initApp();
	});

	// other code to do after device is ready
} else {
    // Web page
	initApp();
}  

function initApp() {
	// load home page
	myApp.views.create('.view', {
		url: '/'
	});
}

3. That's it. Earlier comments talked about CSP changes but I found this deviceready block solves all of those issues too.  I used the standard production CSP policy and it works fine on both browser and device.
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: 'unsafe-inline' https://ssl.gstatic.com; style-src 'self' 'unsafe-inline'; media-src *" /> 

Note, this was done for a simple 2 page helloworld example to isolate the problem.  There is no ajax and external references.  In a real app, some minor changes will be required of the security policy as ajax and external resources will surely be used.

4. The isCordovaApp variable above is just one way to detect a device.  For a discussion on how to detect the running environment, check out

https://stackoverflow.com/questions/8068052/phonegap-detect-if-running-on-desktop-browser 

I hope this helps someone.

**Comment by rashnk** [comment]
i have one app built with f7 , on some android devices it shows white blank page, on some devices it worked after updating android webview from play store, still dint fgure out wht is the issue
https://play.google.com/store/apps/details?id=org.islamicmajlis.salahtimes

**Comment by daksamedia** [comment]
I tried this trick but nothing happen to my apps.
