### ISSUE TITLE
Ajax in page , help-me!

### ISSUE THREAD

**Issue by M4ttscx** [framework7io/Framework7#1972]
How to put a ajax script via sql on the page, I would like to create a sub page with details of a post.

Example:
   {
     // Page
     **path: '/ post /: id /: postID',**
     **componentUrl: './pages/post.html',**
   },

In routes, I would like to put a $.ajax where I would get data from the database, using the date of the "postid" id.

$.ajax + append html!

Can someone help me?

**Comment by M4ttscx** [comment]
Can someone help me? :(

**Comment by nolimits4web** [comment]
Something like this:
```
{
  path: '/post/:id/:postID',
  async(routeTo, routeFrom, resolve) {
    const { id, postID } = routeTo.params;
    // Do request here
    app.request({
      //...
      success(data) {
        // Modify data as you needed
        resolve(
          {
            componentUrl: './pages/post.html',
          },
          {
            context: data,
          }
        )
      }
    })
  }
}
```
P.S. Use Forum for questions
