### ISSUE TITLE
[v2] unsafe-eval required in CSP

### ISSUE THREAD

**Issue by eradin** [framework7io/Framework7#1973]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2 beta 17
* Platform and Target: Browser, android
* Live Link or JSFiddle/Codepen: 

### What you did
Run app with standard CSP policy (not including unsafe-eval).  

### Expected Behavior
Should work without opening eval 

### Actual Behavior
Browser throws a CSP exception

Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src http://localhost data: gap: 'unsafe-inline' https://ssl.gstatic.com”). Source: call to eval() or related function blocked by CSP.   [framework7.js:562]

There are numerous articles on the subject of the dangers of allowing eval in js files.  I don't know if this is a design issue or not but it should concern everyone that framework7 requires the allowing of eval.

If this is not a bug, I would hope a simple explanation to explain why this doesn't pose a security issue.

**Comment by nolimits4web** [comment]
`eval` is required and used by Template7! No chance to make it work without eval at the moment

**Comment by marti1125** [comment]
@nolimits4web how to implement eval config??? I don't find in the documentation
