### ISSUE TITLE
Choppy JS animation between pages in v2

### ISSUE THREAD

**Issue by ocean89** [framework7io/Framework7#1974]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2 beta 17
* Platform and Target: cordova iOS

### What you did
Load a second page with large DOM, in this case a couple of tables with data and images (weather data). The page is "stacked" and pre rendered.

### Expected Behavior
Fast smooth transition to second (next) page, like in v1.

### Actual Behavior
Choppy and slow JS transition.

I know the removal of the stacked class will cause a reflow that takes some time due to the new page is large, but the choppy transition makes the experience really bad. I have tried setting the animateWithJS=false on the router and the transition then gets very smooth, but i'm experiencing other problems like the page does respond to interaction for some time after the transition is completed.

**Comment by nolimits4web** [comment]
Do you use WkWebView or default. UIWebView?

**Comment by ocean89** [comment]
I have tried WkWebView, but I can't notice any improvement in performance.

**Comment by nolimits4web** [comment]
`animateWithJS=false` is the correct way. As for page doesn't respond after transition, F7 doesn't do much after transition, just changing page classes. So it is more likely up to iOS, especially if you do some heavy operations after page in. You can try to use some lazy loading technics like hiding heavy content during transition and show it after page transition, or/and hiding content which is below the screen, etc.

P.S. it is still highly recommended to use WKWebView as it a way more better and bugless than UIWebView

**Comment by ocean89** [comment]
Ok, I was afraid of this.. thanks anyway!
