### ISSUE TITLE
translate3d when i change to page to page i use cordova google maps

### ISSUE THREAD

**Issue by dsemerida** [framework7io/Framework7#1978]
hi there im working with framework7  and google maps cordova, when i navigate from pages to pages the last page cover all the now page,  do you know ?
![4a9ef17e-4f81-4919-8f75-e89a2b4ffe46](https://user-images.githubusercontent.com/17621449/33509977-3b20e03c-d6cc-11e7-85d9-3c45ae03c744.jpg)

**Comment by nolimits4web** [comment]
Yes it is by design
