### ISSUE TITLE
[v2] Documentation (A little guidance needed)

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#1979]
@nolimits4web 
Can you please add a little bit documentation of v2. I want to build apps on v2 beta version but i don't know how to start. A little guidance can help us. I know v2 is in development phase but still a little guidance can be really helpful.

**Comment by mitchellfranklin** [comment]
Hi @danish1023,
Not sure if this will work for you but it helped me pretty well. Download the V2 and open up Kitchen Sink as a project using Atom. From there take a copy of the index page and the JS folder (Kitchen Sink) and place that in your project 

> Delete all the content in index that you dont want like the `<ul> / <li>` stuff and that will give you the base

Using Atom and the Preview HTML pluguin open up the kitchen sink index in preview, from there find the components you want to add and view the code to copy what you want or need to yours. For the most part @nolimits4web has all the JS and info you need in each page so it starts to come together really easy once you know where to look.

Ping me if your getting stuck and I can quickly do a walkthrough (Video or something) of what Im talking about

**Comment by alextapia007** [comment]
If i getting stuck... can u help us too @mitchellfranklin?

**Comment by mitchellfranklin** [comment]
@alextapia007 sure

**Comment by nolimits4web** [comment]
v2 docs are already online
