### ISSUE TITLE
[v2] Page init

### ISSUE THREAD

**Issue by danish1023** [framework7io/Framework7#1980]
@nolimits4web 
How to change modal title on page init in v2?
var app = new Framework7({
 modalTitle: ‘My Project’,
});
is not working.

If possible, please share some common and useful page initialization parameter.

**Comment by mitchellfranklin** [comment]
Hi @danish1023 ,

Modals have been changed to Dialog. so in this instance to create a Dialog you can view the below.

`app.dialog.alert('My Information','My Title');`

**Comment by danish1023** [comment]
@mitchellfranklin Thank you!
