### ISSUE TITLE
[v2] on ajax Start

### ISSUE THREAD

**Issue by danish1023** [framework7io/Framework7#1981]
$$(document).on('ajaxStart', function (e) {
    myApp.showIndicator();
});

$$(document).on('ajaxComplete', function (e) {
    myApp.hideIndicator();
});

@nolimits4web 
How to write this in v2?

**Comment by mitchellfranklin** [comment]
Hi @danish1023 ,

You can do this with like the below.

```
$$(document).on('ajaxStart', function (e) {
myApp.preloader.show();
});

$$(document).on('ajaxComplete', function (e) {
myApp.preloader.hide();
});
```

**Comment by danish1023** [comment]
@mitchellfranklin Thank you!
