### ISSUE TITLE
Component Form Validators

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#1984]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [X ] feature-discussion (RFC)

Perhaps this could be a new feature.  

I've been playing with an implementation of form validators.  There is lots of discussion on the topic but no real clean implementations.  What I would really like is a way to incorporate form validators within a FW7 component.  Something to this effect.  

	return {
		on: {
			pageInit: function (e, page) {
				// init signin page here
			},
		},

		validate: function(page, form) {
			var errormess = '';
			var uname = page.$el.find('#user-name').val();
			var pwd = page.$el.find('#password').val();

			if (uname.trim() == '' || pwd.trim()=='') {
				errormess = 'Both a user name and password is required';
			}
			if (errormess != '') {
				myApp.dialog.alert(errormess, 'Error');
			}
			return (errormess == '');
		},
	}

At a minimum, the validate function will be called (if it exists) when a form on the current page is submitted.  A helper method to programmatically call the validator on click would be good too.  The validator returns true/false.  Implementation of the validation is up to the developer but common builtin validator methods within the framework would be welcome too (e.g. email, required, numbers etc.).  

I'm not suggesting a parsley.js implementation using DOM7 at this point.  But just a simple straightforward way to integrate validations into the component framework.  

Thoughts?

**Comment by nolimits4web** [comment]
But there is already fields validation implemented with the native HTML validation API https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation

**Comment by eradin** [comment]
That is true but it doesn't cover everything like dependencies.  For instance, if you have 2 fields like cellphone and carrier, you would require a carrier only if a cell phone was entered.  Other validations not included in html are credit card numbers and expiration dates.  I suppose some of these can be done with patterns but the dependency issue still requires javascript.

**Comment by J05HI** [comment]
@nolimits4web 
Would need that too :)

**Comment by eradin** [comment]
According to the link above, HTML validation does lack flexibility and control over messaging.  We need choices in this area.

**Comment by JCKodel** [comment]
+1 for lack of localization (my app is portuguese, but on an english browser, the message is in english):

![image](https://user-images.githubusercontent.com/379339/35410689-56313a14-01fd-11e8-9af4-a59fa811e556.png)

Also, there is a lot it cannot do (for instance: validate credit card numbers or brazilian security numbers (which uses a similar algorithm).

**Comment by TomySpagnoletti** [comment]
*@nolimits4web Firstly, thanks for your framework, it is awesome.*

**How can implement a "lazy" validation on vue component `f7-input`.**
I want to validate an input but only when the input is blur.

- For example, when I type a phone number, if my phone number isn't complete, the error appear, it's stressful!

Thanks for your time.
