### ISSUE TITLE
[v2] Routable tabs do not work on index.

### ISSUE THREAD

**Issue by dotgodly** [framework7io/Framework7#1987]
Routes:

     routes: [
        {
          path: '/',
          url: '/',
          tabs: [
            {
              path: '/',
              id: 'tab1',
              content: 'Tab 1',
            },
            {
              path: '/tab2/',
              id: 'tab2',
              content: 'Tab 2',
        },
        {
          path: '/tab3/',
          id: 'tab3',
          content: 'Tab 3',
            },
          ]

Index.html

    <div id="app" class="theme-dark">
    <div class="statusbar"></div>
    <div class="view view-main view-init ios-edges" data-url="/">
    <div class="page">
    <div class="toolbar tabbar">
                <div class="toolbar-inner">
                      <a href="/" class="tab-link" data-route-tab-id="tab1">Tab 1</a>
                  <a href="/tab2/" class="tab-link" data-route-tab-id="tab2">Tab 2</a>
                  <a href="/tab3/" class="tab-link" data-route-tab-id="tab3">Tab 3</a>
                </div>
              </div>
                  <div class="tabs tabs-routable">
                    <div class="page-content tab" id="tab1"></div>
                     <div class="page-content tab" id="tab2"></div>
                    <div class="page-content tab" id="tab3"></div>
                  </div>  
               </div>
             </div>
          </div>

Tab 1 does not display on load, but does work after clicking Tab 2 and going back to Tab 1

**Comment by saplmm** [comment]
这个还是没有解决啊，我下载了最新的包，还是一样的有问题

**Comment by arte0s** [comment]
Unfortunately i found this problem too, but here is simple workaround:
`app.router.navigate('/', { animate: false});`
