### ISSUE TITLE
input arrays not posting correctly

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#1988]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* V2.0
* firefox

### What you did
If you have html markup like so

<form id="form1">
<input type="text" name="fld[]" value="1">
<input type="text" name="fld[]" value="2">
<input type="text" name="fld[]" value="3">
</form>

And post via DOM7 ajax call, the posted variable "fld" is posted as an array of single item arrays. 

flds = [['1'], ['2'], ['3']]

It seems myApp.form.convertToData  is not serializing properly. 

Ajax call example

```
> // post the form data
>     console.log(myApp.form.convertToData('#form1'));
> 	myApp.request({
> 		type        : 'post', 
> 		url         :  'http://localhost/form.php',
> 		data        : myApp.form.convertToData('#form1'),
> 		dataType    : 'text',  
> 		success	: function(data) {
> 				data = JSON.parse(data);
> 
> 				// here we will handle return values
> 				if (data && data.status == 'ok') {
> 				},
> 		error		: function(request, status) {
> 			logIt('Ajax Error: '+ status, 1);
> 		},
> 	});
```

### Expected Behavior
"flds" should be a single array with 3 items.

flds = ['1', '2', '3']

This has been the behavior for regular non-ajax posts.  It is also the behavior for jquery serialize().

**Comment by nolimits4web** [comment]
Would be good to see your inputs HTML layout

**Comment by eradin** [comment]
It seems the html didn't get intp the original post.  

Here is an example:

```
<li>
<label class="item-checkbox item-content">
<input type="checkbox" name="colors[]" value="red">
<i class="icon icon-checkbox"></i>
<div class="item-inner">
<div class="item-title">Red</div>
</div>
</label>
</li>
<li>
<label class="item-checkbox item-content">
<input type="checkbox" name="colors[]" value="blue">
<i class="icon icon-checkbox"></i>
<div class="item-inner">
<div class="item-title">Blue</div>
</div>
</label>
</li>
<li>
<label class="item-checkbox item-content">
<input type="checkbox" name="colors[]" value="green">
<i class="icon icon-checkbox"></i>
<div class="item-inner">
<div class="item-title">Green</div>
</div>
</label>
</li>

```

Assuming all items are checked, the posted value is:
colors = [['red'], ['blue'], ['green']] instead of  ['red', 'blue', 'green']

This is not just the jquery result, regular html will post this way too.

There are many posts on the internet.  Here is just one:

https://stackoverflow.com/questions/6152436/posting-array-from-form

**Comment by nolimits4web** [comment]
Just remove `[]` from input names. F7 automatically assumes checkboxes as array

**Comment by eradin** [comment]
Yes I discovered that so my code works but it's not standard workings.  That appears to be a workaround.  The correct workings would be 

1. No parens, the post variable will contain the last checked item only.
2. With parens, you get an array.
