### ISSUE TITLE
iPhone X safe areas and MD theme

### ISSUE THREAD

**Issue by vasilyzakharov** [framework7io/framework7#1989]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.2
* Platform and Target:  IOS

### What you did
Used MD theme for iOS devices

### Expected Behavior
To have a space around notch/status bar and the indicator for accessing the Home screen

### Actual Behavior
Space around safe area not being added

**Comment by nolimits4web** [comment]
Added
