### ISSUE TITLE
[v2] Dom7 post example

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#1991]
@nolimits4web 

Can you please share an example of calling an api via post metod.

We are waiting for the official v2 documentation.

**Comment by danish1023** [comment]
How to send headers in api?
In my API, a basic authorization is set.

**Comment by nolimits4web** [comment]
in v1 `Dom7.post(...)` or `$$.post(...)`
Now with same options but `app.request.post(...)` or `Framework7.request.post(...)`
