### ISSUE TITLE
[v2] Status Bar Collapse issue

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#1995]
@nolimits4web 

version 2.0.2

How to fix this with framework7? It happens when we include:
<script type="text/javascript" src="cordova.js"></script>

![screenshot_20171208-153055](https://user-images.githubusercontent.com/6543485/33760865-4b16e660-dc2d-11e7-9aaf-7ab14ec21f07.jpg)

**Comment by kinimodmeyer** [comment]
try this (when y use cordova/phonegap)

    <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2" />
    <preference name="StatusBarOverlaysWebView" value="true" />
    <preference name="StatusBarStyle" value="default" />

**Comment by kinimodmeyer** [comment]
![ipad 3](https://user-images.githubusercontent.com/3705274/33784193-302031ee-dc60-11e7-9c90-7308d0d011b2.jpg)

@nolimits4web maybe it is the same problem here on ipad

**Comment by J05HI** [comment]
@nolimits4web
Have the same problem

**Comment by danish1023** [comment]
Include cordova.js at the end of index file. It will fix the issue.

@nolimits4web

Status bar is appearing a little bit late. I want the status bar functionality to turn off from framework 7 side. How can i do the same?
