### ISSUE TITLE
[v2] Is the a BeforeRemove action for smart select list popups available to detect when closing it?

### ISSUE THREAD

**Issue by rapgithub** [framework7io/framework7#1996]
I do not know if is it possible to detect when closing a smart select list popup..

I have a smart select list popup with radio and checkbox options... on close this smart select list popup I need to be able to update the previous page with the selected options on close...

is there any BeforeRemove action for smart select list popups available or something similar to use to filter the current page from the smart select list popup  ?

I mean I close the smart select list popup with the selected options I need to filtering the current page  
and when close I run an action to filter my selection on this page...

I will appreciate any info for V2 how to achieve this..
thanks

**Comment by nolimits4web** [comment]
Use forum for questions, please http://forum.framework7.io

**Comment by rapgithub** [comment]
sorry thanks!
