### ISSUE TITLE
no buttons will work...

### ISSUE THREAD

**Issue by tsad3v** [framework7io/framework7#1997]
hello,
i was trying to use your framework7 & i've been noticing that none of the buttons work. i've tried your main site, other tutorials, etc. please help! i'll leave the code below!

Thanks
Austin

> <html>
<head>
<title>AustinD3V</title>
	    <link rel="stylesheet" href="dist/css/framework7.ios.min.css">
	<link rel="stylesheet" href="dist/css/my-app.css">
	
	    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
</head>
<body>
    
    <div class="views">
      
      <div class="view view-main">
        
      <div class="view view-main navbar-through">
        <div class="navbar">
          <div class="navbar-inner">
            <div class="center sliding">AustinD3V</div>
          </div>
        </div>
		          <div data-page="index-1" class="page">
            
            <div class="page-content">
              <div class="content-block-title">Hello</div>
              <div class="content-block">
                <div class="content-block-inner">
                  <p>Welcome to my website! I used <a href="https://framework7.io" class="link">Framework7</a> to make this, but i custom made this theme.</p>
                  <p>I'll have the source code out for this site sooner or later so stay tuned!</p>
                </div>
              </div>
  

		</div>
		</div>
		</div>
		</div>
		  <div class="views">
    
    <div class="view view-main">
      
      <div class="pages">
        <div class="page" data-page="home">
          <div class="page-content">
            ... page content goes here ...
          </div>
        </div>
      </div>
    </div>
    
    <div class="view another-view" id="about">
      
      <div class="pages">
        <div class="page" data-page="home-another">
          <div class="page-content">
            ... page content goes here ...
          </div>
        </div>
      </div>
    </div>          
  </div>
		    
    <script type="text/javascript" src="dist/js/framework7.min.js"></script>
    
    <script type="text/javascript" src="js/my-app.js"></script>
	      
               src = "https://cdnjs.cloudflare.com/ajax/libs/framework7/1.4.2/js/framework7.min.js"></script>
<script type = "text/javascript" 
</body>
</html>

**Comment by nolimits4web** [comment]
Please, update F7 to latest version
