### ISSUE TITLE
[v2] use subnavbar-buttons to navigate routable tabs (active not working)

### ISSUE THREAD

**Issue by kinimodmeyer** [framework7io/framework7#2000]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2

active is not set correctly is you use routable from a subnavbar.

```
<div class="subnavbar ios-only">
        <div class="subnavbar-inner">
          <div class="segmented segmented-raised">
            <a href="./" class="tab-link button" data-route-tab-id="tab1">Allgemein</a>
            <a href="tab2/" class="tab-link button" data-route-tab-id="tab2">Tabelle</a>
          </div>
        </div>
    </div>
    <div class="toolbar tabbar md-only">
    <div class="toolbar-inner">
      <a href="./" class="tab-link" data-route-tab-id="tab1">Allgemein</a>
      <a href="tab2/" class="tab-link" data-route-tab-id="tab2">Tabelle</a>
    </div>
</div>
<div class="tabs tabs-routable">
    <div class="page-content tab" id="tab1">
    </div>
    <div class="page-content tab" id="tab2">
    </div>
</div>
```

**Comment by nolimits4web** [comment]
Works fine for me. Can you provide JSFiddle with the issue as i can't replicate it?

**Comment by kinimodmeyer** [comment]
@nolimits4web the problem appear when you go from a tab-based page to another tab-based routable page. (i think there is a ID conflict)

or just linking for the same page. like the above and adding in the first page-content a link to <a href="/thesamepage/tab2/">test</a>
