### ISSUE TITLE
[v2] get page name - current view

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#2003]
@nolimits4web 
How to get current page name in v2?

I am using below code in v1:

var page = myApp.getCurrentView().activePage;
if(page.name=="index"){
     			navigator.notification.confirm("Are you sure want to exit from App?", onConfirmExit, "Title", "Yes,No");
 }

How to achieve this in v2?

**Comment by nolimits4web** [comment]
There is no such in v2. You can refer current page HTML element by `app.views.main.router.currentPageEl`

P.S. use forum for questions!
