### ISSUE TITLE
[v2] Virtual list with items with different height

### ISSUE THREAD

**Issue by J05HI** [framework7io/framework7#2005]
Hello @nolimits4web,

how to create a virtual list with items which have different heights?

Thank you very much!

**Comment by nolimits4web** [comment]
Look at docs, there is a “height” parameter in Virtual List.

P.S. Use forum for questions

**Comment by J05HI** [comment]
@nolimits4web 
Yeah I've already seen this but I would like to have a different height for each item.
How can I solve this?

**Comment by nolimits4web** [comment]
> number or function(item)
> ... If function then function should return item height

http://framework7.io/docs/virtual-list.html#dynamic-height

**Comment by J05HI** [comment]
Okay thx, hope I'll get it to work with that :)
