### ISSUE TITLE
Docs out of sync with Version 2

### ISSUE THREAD

**Issue by philrob** [framework7io/framework7#2007]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [x ] feature-discussion (RFC)

* Framework7 Version: 2.0.2
* Platform and Target:  IOS, ANDROID

Version 2 not really in state for use until accompanying Version2 documentation available on main Framework7 Website. Currently docs are for Version 1.6.5.

**Comment by nolimits4web** [comment]
Docs for v2 are in progress. You can use v1 for now

**Comment by vousys** [comment]
@nolimits4web please, do not forget to write a "migration" section for the ones that uses 1.6.5 and want to upgrade to v2, just like me :)

**Comment by webloper** [comment]
Hello @nolimits4web , can we check progress, is it online, is there any way we also contribute to the docs.

**Comment by philrob** [comment]
Hi,
Any news yet on V2 docs expected time scale? Really would like to start using V2 of your excellent framework. Many Thanks.
