### ISSUE TITLE
getJSON and get don't work with WkWebView

### ISSUE THREAD

**Issue by SpiderNeo1** [framework7io/framework7#2011]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5
* Platform and Target: Cordova iOS >=9.0.0

### What you did
I Added WKWebViewEngine to my Cordova App
https://github.com/apache/cordova-plugin-wkwebview-engine

### Expected Behavior
With UIWebView, simple navigation is working And the call to the functions $$.getJSON and $$.get also works.

### Actual Behavior
With WKWebView, simple navigation is working **BUT** the call to the functions $$.getJSON and $$.get no't working.
I imagine that post and ajax functions don't work with WKWebView.

**Comment by nolimits4web** [comment]
This is because CORS policy applies. You must have correct CORS headers on server or try this plugin https://github.com/ionic-team/cordova-plugin-ionic-webview

**Comment by SpiderNeo1** [comment]
Thank you for your message but I'm not on ionic.
Where I have to put the good correct CORS headers ? In JS file ? In HTML file ? In the config.xml file for Cordova ?

**Comment by nolimits4web** [comment]
You don't have to be on ionic to use this cordova plugin

**Comment by SpiderNeo1** [comment]
I just tried https://github.com/ionic-team/cordova-plugin-ionic-webview instead of https://github.com/apache/cordova-plugin-wkwebview-engine and it's still the same problem :-(

**Comment by SpiderNeo1** [comment]
In fact, it works with internal file but not with WebServices.

**Comment by nolimits4web** [comment]
For requests to external services correct CORS headers must be set on server side https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#The_HTTP_response_headers

**Comment by SpiderNeo1** [comment]
I'm sorry Vladimir but I have already put this on my server (Apache/PHP) and it doesn't work better :

```
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");	
header("Content-Type: application/json");
header("Access-Control-Allow-Origin: *");
```

**Comment by nolimits4web** [comment]
Try also to add allowed methods https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods

If won’t work then check the errors in browser console

**Comment by SpiderNeo1** [comment]
I can't do it at all, I tried everything...

On the Chrome browser, I have to launch the application by launching the browser in this way: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --user- data-dir = "c:/chrome"

I think I'll go back to the UIWebView. Hoping that when I re-develop my application on the F7 v2.0, everything will work fine on WKWebView.

**Comment by SpiderNeo1** [comment]
http://uncaughterror.com/programming/ionic3/preflight-response-issue-with-ionic3-app-on-ios-build-only-resolved/

**Comment by SpiderNeo1** [comment]
Maybe you should also use https://github.com/apache/cordova-plugin-whitelist
No ?

**Comment by SpiderNeo1** [comment]
On my Browser Chrome, I have this error :

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1' is therefore not allowed access.
