### ISSUE TITLE
[v2] Не совпадает цвет StatusBar'a и NavBar'a в приложении под iOS: доп. плагины для StatusBar'a здесь ни при чем

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2012]
Приложение в iOS занимает всю высоту экрана, хотя стоит `<preference name="fullscreen" value="false"/>`, но цвет StatusBar'a не совпадает с цветом NavBar'a: цвет StatusBar получается белый, а NavBar'a (тема по-умолчанию) - чуть темнее.

**Исправление**: в index.html в body добавляем нужный цвет, к примеру:
`<body style="background-color: orangered;">`
и тогда StatusBar у нас будет оранжевым.

**Comment by shastox** [comment]
Вот тут про v1 написано: https://framework7.io/docs/status-bar.html т.е. добавляется padding, но в v2 с этим какая-то ошибка: паддинг добавляется, но цвет StatusBar остается белым.

**Comment by nolimits4web** [comment]
А элемент `<div class="statusbar"></div>` есть в коде?

**Comment by shastox** [comment]
Спасибо!
