### ISSUE TITLE
[V2] Sublists not formatting correctly, List Groups not working

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2020]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2.0.2
* Platform and Target: ANDROID
* Live Link or JSFiddle/Codepen:    https://jsfiddle.net/teamscoring/0ogxxcvt/12/

### What you did
Simple accordion list with sub list + basic list group 

### Expected Behavior
Last list does not format correctly. List group is not sticky

### Actual Behavior
Last list items have no line separators

See fiddle above. D1 and D2 have identical content.  Open D1 and see that each Team is separated with a line.  Open D2 and you will see no lines separating.  They should be identical.  P1 and P2 are simply dividers.  The css apparently hides lastchildren for ALL list items in the final outter list.

Also, list groups are not sticky in accordion.  The top group list (not in accordion) works.

**Comment by nolimits4web** [comment]
Issue with hairlines fixed in #2139. As for sticky titles, it is a browser issue, e.g. if you remove `transform` and `overflow` css props from accordion-item-content it will work but accordion won't work in this case
