### ISSUE TITLE
[v3] Safe area in landscape not working and missing status bar in portrait

### ISSUE THREAD

**Issue by mattkhaw** [framework7io/framework7#2021]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.2.
* Platform and Target: Cordova, iOS 11.2

### What you did
From portrait, rotate device in landscape, then rotate device in portrait. For now, I'm using a simulator and I don't have the actual device to test. Also, safe area for landscape is not working as well.

### Expected Behavior
Should have a padding or height for status bar in portrait and safe areas in landscape should be working.

### Actual Behavior
Status bar padding or height is missing. Safe areas in landscape not working. It still extends up to the notch.

**Comment by mattkhaw** [comment]
I think I've found the issue. The issue is upon rotation, it seems that the safe area inset values seems to be not working. Other people said that it is a bug in the UIWebView and it is resolved in later iOS versions but I don't think so since I'm on iOS 11.2. To workaround this, I just get the initial value after init() and check both orientationChange and resize events whether it is necessary to apply the insets.

`
// create a global variable to be accessed anywhere for convenience
var CONST_SAFE_INSET_TOP = 0;

// get the inset value from one of the elements and assign it in a variable
CONST_SAFE_INSET_TOP = $$('html.device-iphone-x .framework7-root').css('padding-top');

// apply this in orientationChange and resize events onDeviceReady
function fixStatusBar() {
    var root = $$('html.device-iphone-x .framework7-root');
    var statusbar = $$('html.device-ios.device-iphone-x .statusbar');

    if (f7.device.needsStatusbarOverlay()) {
        if (statusbar.css('height') == '0px') {
            statusbar.css('height', CONST_SAFE_INSET_TOP);
        }

        if (root.css('padding-top') == '0px') {
            root.css('padding-top', CONST_SAFE_INSET_TOP);
        }
    } else {
        statusbar.css('height', 0);
        root.css('padding-top', 0);
    }
}`

Most likely this workaround only can be applied when the app starts on portrait. As for landscape > portrait, this might not work since the top inset value is not present during startup. All the selector values are taken from Framework7's css. So, if you need to apply this kind of fix on other inset values, just refer to the css file.

**Comment by jpweg1993** [comment]
Just wanted to add that I'm getting this same issue on f7 v1.7.1 (update to v1 with iPhone X compatibility). I'm running iOS 11.2 in the iOS simulator.

Everything works beautifully in portrait, but in landscape there are no margins on the left and right, so content ends up under the notch.

Tested with the kitchen sink.

**Comment by yelban** [comment]
ver. 3.4.2 still got the problem

Safe area in landscape is ok when start app the device in landscape
but the wonderful page display will broken after once rotate

Does any method to re-render like app init when orientationChange?
