### ISSUE TITLE
[v1] React progress bar doesn't work

### ISSUE THREAD

**Issue by pavel-morozov-duallab** [framework7io/framework7#2024]
Hi, i'm using framework7 v1.5.3 and framework7-react v0.9.3-2.
I've got an issue with Progressbar component on my pretty old phone: progressbar wasn't updated when i changed progress attribute.

The problem is in my phone WebView: it doesn't support transform property. 
I have a quick fix for that. In  the framework7-module i edited framework7-vue.js (string 4049).
was:
                `style: {
                    'transform': progress ? 'translate3d(' + (-100 + progress) + '%,0,0)' : ''
                }`
became: 
`style: {
                    'transform': progress ? 'translate3d(' + (-100 + progress) + '%,0,0)' : '',
                    '-webkit-transform': progress ? 'translate3d(' + (-100 + progress) + '%,0,0)' : ''
                }`

And it works perfectly.

**Comment by nolimits4web** [comment]
Please open this issue in appropriate framework7-react repo
