### ISSUE TITLE
how import framework7 package ?

### ISSUE THREAD

**Issue by TongDaDa** [framework7io/framework7#2025]
the official said

![2017-12-27 7 57 52](https://user-images.githubusercontent.com/23241188/34398671-be99efa4-ebbb-11e7-99d3-156ab64f3042.png)

However, I through the import did not see anything, let alone registered window

open node_modules see framework7 except dist folder no entry file

![2017-12-27 8 01 31](https://user-images.githubusercontent.com/23241188/34398672-c089548a-ebbb-11e7-96fb-ce9f40871b6f.png)

Excuse me, How to use this import to introduce framework7 ?

**Comment by nolimits4web** [comment]
Check F7-Vue v2 Kitchen sink for example https://github.com/framework7io/framework7-vue/blob/master/kitchen-sink/app.js
