### ISSUE TITLE
Swiping panels initially 'jump' instead to smoothly follow the finger

### ISSUE THREAD

**Issue by tiptronic** [framework7io/framework7#2026]
Just to be sure: I like swipeable side-panels 😉 (no matter what any HIG recommends).

In both versions of F7 (v1 and v2) there's a slight 'hickup' when starting to drag the side panel from either side (best to be seen, if mode is set to 'reveal').

In v1 I fixed this in framework7.js by changing the line:

```javascript
var threshold = opened ? 0 : -app.params.swipePanelThreshold;
```
to
```javascript
var threshold = opened ? 0 : -(app.params.swipePanelThreshold + app.params.swipePanelThreshold/2);
```
and adding a swipePanelThreshold of 10 to my configuration.

I am not sure how to rate this, so please forgive me, if I rate this as a bug. It may very well be, that this collides with iOSEdgeSwipe, but for me the smooth operation of my app is more important...

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: origin/master v2.02
* Platform and Target: iOS

* Live Link or JSFiddle/Codepen: Just set panel-reveal and panel:{swipe: 'both'} 

### Expected Behavior
The expected behaviour is, that the panel just follows my finger without 'snapping' to it on the first couple of pixels/points of movement

### Actual Behavior
'jumping'/snapping after I dragged a couple of pixels horizonatlly

**Comment by nolimits4web** [comment]
Didn't get the point of this fix in source code. You just basically set threshold twice smaller, if you pass 10 there, then you'll get 5. So in other way, will be the same as passing just smaller threshold parameter value

**Comment by tiptronic** [comment]
You are right - it's not a fix, but it makes the problem much less visible. 
I think the correct fix would be to adjust for the (already moved) delta as soon as the swipe is detected. In this case the panel would follow the finger without the initial 'hickup'

**Comment by tiptronic** [comment]
Just a question: Will there be a generall fix for this, so opening the side-panel follows my finger smoothly (and without the initial 'jump')? 
Is there anything I can help with?
thx

**Comment by nolimits4web** [comment]
The code for panel suppose that it should follow finger smoothly. The "initial jump" you mention, is due to performance issue, especially with "reveal" effect. So no matter how smooth it be but if you have heavy content (or a lot of content) in panel and in view (which is also moved in reveal effect) then it will be more noticable

**Comment by tiptronic** [comment]
For me it's also noticable, if I swipe in a panel w/o much content over a fairly empty view. Btw. the same 'jump' also in Swiper, when swiping an empty slide or the 'swipe to delete'. 
In Ionic3 I don't see this behaviour (if that counts anything :) )
Btw: I'm testing on an iPhone X, so I can't get a much faster device...
