### ISSUE TITLE
v2.0.2 pushState and dynamicNavbar is true  routes async to  componentUrl  can't back to index.html

### ISSUE THREAD

**Issue by KELINGYANG** [framework7io/framework7#2027]
var routes = [
    {
        path: '/',
        url: './index.html',
        name: 'home',
    },
    {
        path: '/page/',
        async(to, from, resolve, reject) {
            this.app.preloader.show();
            setTimeout(function () {
                resolve(
                    {
                        componentUrl: './pages/page.html',
                    },
                    {
                        context: { colors: ['red', 'yellow', 'blue'] },
                    }
                )
                this.app.preloader.hide();
            }, 3000);
        }
    },
    {
        path: '(.*)',
        url: './pages/404.html',
    },
];

var app = new Framework7({
    id: 'io.framework7.test',
    name: 'Framework7',
    root: '#app',
    theme: 'ios',
    view: {
        pushState: true
    },
    routes: routes
});

【problem】
open url：http://localhost/#!/page/
back url：browser default url
back can't to url ：http://localhost/

**Comment by nolimits4web** [comment]
Back won't work in this case because push state works for browser history, so it won't work if you go to `http://localhost/#!/page/` and try to go somewhere because there is no history in browser
