### ISSUE TITLE
If side-panels are set to 'swipe', Swiper slider (horizontally) doesn't work on desktop

### ISSUE THREAD

**Issue by tiptronic** [framework7io/framework7#2028]
If side-panels are set to 'swipe', Swiper slider (horizontally) doesn't work on desktop.

```json 
 panel: {
    swipe: 'right'
  }
```
or
```json 
 panel: {
    swipe: 'both'
  }
```
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v 1.X - v 2.02
* Platform and Target: ios, macos

### Expected Behavior
Swiper can swipe

### Actual Behavior
If sidepanels are set to 'swipe' (any direction), Swiper doesn't work on desktop computers - instead one of the panel appears (depending what was set as 'swipe'). 

It works fine on mobile!

**Comment by nolimits4web** [comment]
There is no easy way to fix this because mouse events (on desktop) work in a bit different order. Both of this features swipe-panel and swiper slider are mobile-features, no much sense to use them on desktop
