### ISSUE TITLE
v2.0.2 app.router.load() method  Cannot load the about.html

### ISSUE THREAD

**Issue by wwl0503** [framework7io/framework7#2029]
<li id="about">
                <a class="item-content item-link" >
                  <div class="item-media"><i class="icon icon-f7"></i></div>
                  <div class="item-inner">
                    <div class="item-title">About Framework71</div>
                  </div>
                </a>
              </li>
  <script>

                var app = new Framework7({
               id: 'io.framework7.testapp',
  root: '#app',
});
var $ = Dom7;
$('#about').on('click', function (e) {
  app.router.load({
     url:'about.html'				    
   });
});
</script>

**Comment by shastox** [comment]
1. app.router.navigate(URL);
2. Check the 'routes'

**Comment by nolimits4web** [comment]
http://framework7.io/docs/view.html#router-api-methods-properties
