### ISSUE TITLE
Touch on color picker does not work

### ISSUE THREAD

**Issue by ahmadx87** [framework7io/framework7#2031]
I want to use a wheel color picker in my app. I use[ this Jquery plugin](https://github.com/fujaru/jquery-wheelcolorpicker). I’m using F7 ver 2.02 and I managed to create the page I wanted by using the kitchen sink example. Every thing looks great except short taping the wheel for picking colors does not work. However long tap and touch move seem to work with no problem. I uploaded my code [here](http://aysanoor.com/hedco/FW7/www/index.html). If you use google chromes Device Mode you will see it does not work. I tested it on a real device and it did not work. This plugin worked on Jquerymobile with no issues. Why is this happening? Is this an issue with F7?

**Comment by nolimits4web** [comment]
Looks like fixed http://forum.framework7.io/t/solved-touch-on-wheel-color-picker-does-not-work/1665
