### ISSUE TITLE
[v2] Маленькая ошибка в добавлении заголовка к запросу (есть решение)

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2032]
Строка кода: https://github.com/framework7io/framework7/blob/312aee530063a78b91ce94bc8232a50dcdba7827/dist/js/framework7.js#L3533

Т.е. вместо:
` xhr.setRequestHeader(headerName, options[headerName]);`

Должно быть:
xhr.setRequestHeader(headerName, **options.headers**[headerName]);

**Comment by nolimits4web** [comment]
Это уже было исправлено
