### ISSUE TITLE
[v2] Логическая проблема с infinite scroll (предлагаю решение) 

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2034]
Так устроено, что **preloader** помещается внизу экрана и, когда экран прокручивается до конца, то вызывается событие **infinite** и, если нам нужно, то сам **preloader** мы удаляем.

Но может возникнуть ситуация, когда список весь помещается на экране и элемент
`<div class="preloader infinite-scroll-preloader"></div>`
**сразу виден** при загрузке экрана: в этом случае событие `infinite` не сработает и **preloader** будет крутиться вечно. Чтобы этого не произошло, нужно при старте вызывать `infinite`.

Предлагаю решение: после этой строчки
https://github.com/framework7io/framework7/blob/master/dist/js/framework7.js#L18017
 добавить код:
`$el.trigger('scroll');`

в итоге получим:
```
create: function create(el) {
    var $el = $$1$1(el);
    var app = this;
    $el.on('scroll', function handle(e) {
      app.infiniteScroll.handle(this, e);
    });
    $el.trigger('scroll');
  },
```

**Comment by nolimits4web** [comment]
Такое решение пойдет далеко не всем и так будет всегда вызывать данное событие даже когда не нужно. Как решение просто вызовите это событие в коде своего приложения в нужном месте
