### ISSUE TITLE
[v2] Предложение: автоматическая подстановка параметров из path в url в routes

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2035]
Допустим, у нас есть маршрут:
```
     {
          path: '/page/:id/',
          url : './page/view'
      }
```
И ссылка вида `<a href="page/about">Go</a> `

Если у нас **именно веб-сервер** отдает данные, то было бы **крайне удобно** получить переменную id со значением about. Примерно так:

     {
          path: '/page/:id/',
          url : './page/view?id={id}'
      }

Что-то похожее есть только на форуме: http://forum.framework7.io/t/f7-v2-how-to-pass-query-value-to-web-server/1635/7 , но решение предложено не универсальное.

Возможно, можно это сделать через async или еще как-то "извратится", но очень бы хотелось встроенной поддержки. Спасибо.

**Comment by shastox** [comment]
Пока можно так сделать:
```
 async(routeTo, routeFrom, resolve, reject) {
              resolve({
                  url: '/page/view?id=' + routeTo.params.id,
              });
          }
```

**Comment by nolimits4web** [comment]
Можно еще так чтобы передать все параметры в query:
```
app.utils.serializeObject

async(routeTo, routeFrom, resolve, reject) {
   resolve({
       url: '/page/view?' + app.utils.serializeObject(routeTo.params),
   });
}
```

Подумаю как реализовать

**Comment by shastox** [comment]
С query string не универсальный способ, т.к. бывает и так: 
 '/page/view/{ID}/'
