### ISSUE TITLE
[v2] Путаница URL vs PATH, которая приводит к неработоспособности redirect (решения предложенного нет)

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2036]
Версия №2 оперирует со значениями **path**, а не **url** в массиве **routes**. Поэтому, все ссылки должны работать именно со значением **path**, и, если его нет в **routes**, ссылка не откроется.

Здесь https://framework7.io/docs/view.html сказано, что **router.navigate** работает с **url**, но это не так, она работает с **path**. Отсюда возникает путаница.

Вот здесь https://framework7.io/docs/routes.html сказано, что **redirect**  работает именно с **url**, а не с **path**: это не верно, **redirect** вызывает код в итоге:

`router[direction](redirectUrl, Utils.extend({}, options, redirectOptions));`

где **direction** - это **navigate**. Получается, что **redirect** работает именно с **path**, но не с **url**.

Если где ошибся - извините. Спасибо.

**Comment by nolimits4web** [comment]
В документации ошибки нет, под `url` в `navigate` и `redirect` подразумевается URL страницы (который далее сравнивается с `path` в роутах) а не URL роута который просто указывает из какого файла загрузить страницу, поэтому в редиректе мы должны вернуть URL страницы например `/user/123/posts/31/` который сравнивается например с path'ом `/user/:userId/posts/:postId`

**Comment by shastox** [comment]
> ...redirect подразумевается URL страницы ...
![2018-01-05_20-51-08](https://user-images.githubusercontent.com/1684567/34621428-277d4f62-f25a-11e7-87c0-f50035366fd3.png)

Что означает: Учитывайте, что в **redirects** мы передаем **url**, не **route path** как в **alias**.

**Comment by nolimits4web** [comment]
Ну так тут и сказано что мы передаём URL, имеется ввиду URL страницы
