### ISSUE TITLE
Added Support For AngularJS 1.x using Framework7 

### ISSUE THREAD

**Issue by siddmegadeth** [framework7io/framework7#2040]
Adding Support for AngularJS for Framework7. This is a Binding layer which provide Framework7
to be written as an AngularJS 1.x Application.
Refer to 
**(NG7)[https://github.com/siddmegadeth/ng7]**

This wrapper enables to write Framework7 using AngularJS. currently in heavy development,
created this ticket to highlight the support for Framework7 from NG Community.
This is battle tested now and is in use with few hybrid apps.
Currently working to add more directive.

**Comment by nolimits4web** [comment]
Thanks, i think the better place for it is adding it as a Plugin or Starter App/Template to the website. Also, will be good if it is compatible with F7 v2

**Comment by siddmegadeth** [comment]
thanks. Due to changes in V2 i am working on porting it for V2 but getting some setback due to a lot of structural changes in V2

**Comment by siddmegadeth** [comment]
I will add this to the project folder a s a starter project.Thanks
