### ISSUE TITLE
theme switch broken in cordova app

### ISSUE THREAD

**Issue by yelban** [framework7io/framework7#2044]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.5
* Platform and Target: Cordova android/ios

### What you did
switch theme beside kitchen-sink/index.html, got "Application Error" (Android) or nothing happen (ios)

### Expected Behavior
switch to ios theme (or material theme)

### Actual Behavior
got "Application Error" (Android) or nothing happen (ios)

![a77be7](https://user-images.githubusercontent.com/981381/34555426-aea10b44-f16c-11e7-8372-081b4c07bf96.png)

**Comment by yelban** [comment]
submit a PR to fix this issue.
[PR #2045 ](`https://github.com/framework7io/framework7/pull/2045`)

**Comment by nolimits4web** [comment]
Fixed by #2045, thanks
