### ISSUE TITLE
[v2] Несколько мелких ошибок в документации и одна серьезная (есть решение)

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2047]
https://framework7.io/docs/list-view.html#simple-list
https://framework7.io/docs/list-view.html#links-list

Нужно добавить тег `<ul>`

**Comment by shastox** [comment]
https://framework7.io/docs/app-layout.html 

Тут не важного элемента: `<div class="statusbar"></div>`

**Comment by shastox** [comment]
**Важная ошибка**, которая отняла много времени, при этом в Китчене все `ок`, т.к. там на компонентах.
https://framework7.io/docs/toolbar-tabbar.html

Везде, где `<div class="tabs"></div>` под `<div class="page">`, его нужно обернуть в` <div class="page-content">`

Получится так:
```
<div class="page-content">
 <div class="tabs">...</div> 
</div>
```

Или так: 
```
<div class="page-content">
<div class="tabs-animated-wrap">
 <div class="tabs">...</div> 
</div>
</div>
```

Смысл понятен. Если этого не сделать, то не будет нижнего паддинга у любого контента из-за Таббара (в том случае, если он **внизу**)

**Comment by shastox** [comment]
Еще здесь: https://framework7.io/docs/color-themes.html#helper-classes несоответствие текста и примеров.

**Comment by nolimits4web** [comment]
Для сайта есть отдельный репозиторий https://github.com/framework7io/framework7-website, PR приветствуется

**Comment by nolimits4web** [comment]
Ошибки в документации поправил
