### ISSUE TITLE
[v3] Expandable & Inline Sheet(s)

### ISSUE THREAD

**Issue by murliatdure** [framework7io/framework7#2049]
Looking for Inline/expandable (till touch area|position) for action sheets rather as an overlay behavior.

This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: v2.0.5
* Platform and Target: Android and iOS (Cordova)

### Expected Behavior
Can we have sheets like components expandable or inline to the views (e.g. Google places to open a place details and facebook create post different options like attach camera/video etc. that options are very prominent with inline and collapsible.

### Actual Behavior
Action Sheets are limited to the behavior to open into single / multiple categories as list/grid.

![image](https://i.stack.imgur.com/8ZGNr.gif)

**Comment by murliatdure** [comment]
Expansion something like this - where action sheet/picker gets morphed into the full popup.

![image](https://i.stack.imgur.com/LTaw5.gif)

**Comment by murliatdure** [comment]
![image](https://assets.materialup.com/uploads/98451fe1-1f8c-48b6-848a-3768c0178662/preview.gif)

**Comment by azzahrah** [comment]
helo, any news about this feature?

**Comment by willmero** [comment]
This would be the coolest thing. It’s the last piece of the pie for me personally for Framework7!
