### ISSUE TITLE
Panel swipe issue

### ISSUE THREAD

**Issue by softexe** [framework7io/framework7#2051]
1.
https://github.com/framework7io/framework7/blob/9ef5c7c80ed2c9d6bacaa9384ec908a4c461cdf4/dist/components/panel/swipe-panel.js#L131

No openPanel()/closePanel() functions

2.
Parameter swipeActiveArea set limit for closing panel too.

**Comment by mitchellfranklin** [comment]
Hi @softexe are you using V2?

**Comment by softexe** [comment]
@mitchellfranklin yes, it's v2 issue
