### ISSUE TITLE
[v2] Проблема с Tabbar'ом в FireFox: если он внизу, то нет отступа у контента.

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2053]
У контента отсутствует **нижний отступ,** если есть **нижний таббар** (вне зависимости от темы). Я предложил ранее сделать обертку `<div class="page-content"><div class="tabs">...</div></div>`, но она все ломает, если таббар **наверху**.

Проблема прекрасно воспроизводится в неизменном Китчене. При такой ширине окна - все ок:
![2018-01-06_11-44-06](https://user-images.githubusercontent.com/1684567/34638166-3a65067e-f2d7-11e7-805a-9b6d372c9794.png)

А вот если сузить окно браузера (окно прокручено максимально вниз), то видно, что не весь контент помещается (не хватает нижнего отступа):
![2018-01-06_11-44-22](https://user-images.githubusercontent.com/1684567/34638178-52e041fa-f2d7-11e7-9e03-5ce5f1c9fbc1.png)

**Comment by shastox** [comment]
Оказывается, проблема воспроизводится только в FireFox (скриншоты оттуда), в Хроме и Опере - все нормально.

**Comment by softexe** [comment]
это свойство файрфокса.. делал такой же тикет по отступу с messagebar
фикс для этого дела был такой 

```
.messagebar ~ .page-content {
	padding-bottom: 44px;
	bottom: 44px;
}
```
В вашем случае видимо надо .tabbar ~ .page-content  и применить это только для FF

**Comment by softexe** [comment]
Да, просто иметь ввиду о такой особености, потому что иногда и ФФ приходится использовать при разработке/отладке.
