### ISSUE TITLE
[v2] Проблема с preloader'ом и Cordova'ой в iOS (есть решение)

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2054]
Проблема возникает только в приложениях и только на iOS (тестировалось: 5, 5S, 6S plus; iOS10, iOS11).

У нас есть код, смысл которого понятен:  
```
routerAjaxStart: function (xhr) {
     app.preloader.show();
 },
  routerAjaxComplete: function (xhr) {
      app.preloader.hide();
 }
```

Мы сейчас на странице, где есть **ссылка** и **картинка** (картинка должна быть тяжелой, 0.5-1 мегабайт - это обязательное условие), картинка вставлена тегом `<img>`. При клике на ссылку будет проблема: экран заметно мелькнет. 
Проблема связана с тем, что метод `app.preloader.show();`, в отличии от `app.dialog.preloader();`,  добавляет class `with-modal-preloader `к `<html>`. Это приводит к мельканию (почему именно - неизвестно).

Решения два (чтобы экран не мелькал):
1. Использовать `app.dialog.preloader();` вместо `app.preloader.show();`
2. Очистить стиль для `html.with-modal-preloader .page-content`

Вот тут доп.информация (для v1): https://github.com/framework7io/framework7/issues/192

**Comment by nolimits4web** [comment]
Это возможно происходит из-за того что этот класс делает overflow:hidden на page-content. Как вариант попробуйте использовать WKWebView или если баг останется то переопределите это правило в CSS https://github.com/framework7io/framework7/blob/master/dist/css/framework7.css#L8661-L8663

Убрано это не будет так как этот фикс предотвращает скроллинг страницы позади открытого прелодера

**Comment by shastox** [comment]
> Убрано это не будет так как этот фикс предотвращает скроллинг страницы позади открытого прелодера
Это странно... В своем CSS я точно очистил всё, т.е. получилось так:
```
html.with-modal-preloader .page-content {
}
```

Специально на сервере сделал задержку: прелоудер долго крутился и страница вообще ни на что не реагирует, пока он крутится (клики, скроллинг). Тестировал в Хроме (Windows 7).

**Comment by nolimits4web** [comment]
А в хроме этого и не будет, это фикс для мобильных, для iOS в первую очередь

**Comment by shastox** [comment]
Только что протестировал в приложении, iOS 10 iPhone 5 и iOS 11 iPhone 5S (все так же, без этих стилей): приложение, пока крутится прелоудер не реагирует ни на клики, ни на скроллинг. Точно.

**Comment by shastox** [comment]
Протестировал в приложении под Анроид 6.0: так же нет реакции ни на клики, ни на скролл.

**Comment by nolimits4web** [comment]
в iOS без этих стилей попробуйте поскроллить водя пальцем по самому прелодеру

**Comment by shastox** [comment]
Блин, точно :) Скроллинг есть на самом прелоудере.
