### ISSUE TITLE
use "vue jsx" to provide easier migration to react or jump to react

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2055]
This is a (multiple allowed):
* [x] feature-discussion (RFC)
* Framework7 Version: 2

f7 officially supports vue.js but unfortunatly not react.js. 

I will not debate about the benefits in using react over vue, but would it be good to use at least **vue jsx** syntax (https://vuejs.org/v2/guide/render-function.html#JSX) to provide a easier migration path to react.js? Or even decide to jump completly to react.

I know about https://github.com/bencompton/framework7-react, however, I it s not from the same maintainer of f7 and still lacks behind the official version and as the future is not as sure as f7-vue, because f7-vue comes directly from the maintainer.

In my opinion, before supporting f7-vue officially, it would be good to officially support f7-react. Because there are **a lot more react users out there than vue.** (You see that vue even tries to copy react jsx and in my opinion the future of vue is not so good as for react). 

_By the way:
I also know and used vue.js in the past but I decided to jump to react and it was a good decision! The learining path from vue to react was very easy for me (1 day), because both share common concepts: What is important in react are two things: "lifecycle methods (if not needed, even "stateless components" can be used)" and "render()"-methods. Nothing more and its closer to javascript than vue.js with its templating language (which cannot be faster than the render()-method in jsx). It would also open up the project to a lot more contributors from the React community_

**Comment by nolimits4web** [comment]
I believe this should be opened in different repo https://github.com/framework7io/framework7-vue/ so closing it for now.

As for JSX, not sure about having it in F7 Vue components, will investigate it, currently moving to render function which is i believe is also similar to react's one

**Comment by nimo23** [comment]
> currently moving to render function which is i believe is also similar to react's one

yes, very similar. Vue.js does and maybe will adapt features coming from react (props, states, lifecycle) and I find, always lack behind. I had worked over 1 year with vue.js, I liked it at beginning. Now, I only work 2 month with react and I can say, "react.js" is so much better and I will never switch back to vue.js. It is really worth to investigate 2 days to dig into react and you see.

Imagine having stateless components in f7, with react very simple:

**All 3 versions are the same:**

```
// stateless component
const Tabs = (props)  => (
        <Tab {..props.config}>
            {props.content}
        </Tab>
);

function Tabs(props) {
    return (
             <Tab {..props.config}>
                 {props.content}
             </Tab>
 )}

class Tabs extends React.Component {

    render() {
        return (
            <Tab {..props.config}>
                 {props.content}
             </Tab>
        )
    }
}
```

Then user can use it:

`React.render(React.createElement(Tabs, myprops), document.getElementById(id));    `



I suggest, look at react and consider to switch fully to "react" and leave the "vue.js". You will get these benefits:
- much more react users than vue, so much more chance to have community support
- very easy api and nothing else than javascript (no templating language or the like)
- much better performance (e.g., in future, react.js uses async renders automatically)

The only thing, which was a more time consuming is to make a "webpack.config" (optional, you can still use gulp, but I suggest giving it a try). I had also used gulp before. 

So if I were you, I would go to react.js and leave vue.js behind. No need to support it in future. It gives you much more freedom and it is future-proof.
