### ISSUE TITLE
[Calendar]: provide property "scrollDirection"

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2063]
* [x] enhancement
* Framework7 Version: 2

Please provide property "scrollDirection" within Calendar-Component (https://framework7.io/docs/calendar.html):

"scrollDirection": horizontal (default)
"scrollDirection": vertical (calendar block can be scrolled from top to bottom)

Some prefers to scroll from left to right, but others from top to bottom (which is from the usability easier and better for your hands and fingers).

**Comment by nolimits4web** [comment]
There is a “direction” calendar parameter for this
