### ISSUE TITLE
Tabbed View - Click handler

### ISSUE THREAD

**Issue by murliatdure** [framework7io/framework7#2071]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 2.0.5
* Platform and Target: WEB

### What you did
https://framework7io.github.io/framework7-template-tabs/

### Expected Behavior
Looking for HOOK for the selection of Tab / View

### Actual Behavior
Unable to get where we can implement If the tab selected what needs to be done.

onPageInit - loaded before that view is selected (since of other tab activated initally)
I tried to app.on('tabShow', function(e) - Gives the Component page div contents

Can you please assist; as we are trying to add the map component; that needs to be initialized on-selected tab only. pageAfterIn - not getting called!

Kindly assist.

**Comment by nolimits4web** [comment]
tabShow or dom event tab:show happens when tab becomes active

**Comment by murliatdure** [comment]
$$('#view-locator').on('tab:show', function (e, tab) {
 ...
});
