### ISSUE TITLE
IOS Toolbar needs padding

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2072]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* V2
* IOS

On the IOS theme, if you put icons on the toolbar, the right icon is very close to the edge and difficult to press.  The right icon on the navbar seems to have the appropriate amount of padding.  Toolbar should be the same.

**Comment by nolimits4web** [comment]
Live example, JSFiddle, screenshot or anything else showing the issue?

**Comment by eradin** [comment]
Here is a screen shot from a browser (firefox).  This is the same on the ipad (safari).  Haven't tried it as an app but I expect same results.  The three dot icon over to far right should be aligned under the hamburger icon on the navbar.  This is not an issue on MD theme.

![ios_screenshot](https://user-images.githubusercontent.com/3924103/34686006-1236dda6-f45f-11e7-8d5a-4e8380edd90a.png)

**Comment by nolimits4web** [comment]
Add icon-only class to links
