### ISSUE TITLE
"Routable Tabs" of Tabbed Views"-app: tabs-property is missing in app parameters

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2073]
* Framework7 Version: 2

With "Routable Tabs", the routes of the tab must be declared within the tabs-property. When using a **tabbed view (multiple views layout / each "tab" is a "view")**, I only find the "tabs"-property within the "view"-parameters ("view.tabs"), but not in the "app"-parameters (only "app.routes", but no "app.tabs").

Or shoult I treat each tab as a view and put these "routable tabs" within the "routes"-property of the "app"-params?

**Comment by nolimits4web** [comment]
There is no support for routable tabs-view and probably won’t be implemented as it can bring too complex logic. Just use them as usual tabs and you can load content there dynamically when tab-view becomes visible

**Comment by nimo23** [comment]
Ok, thanks. I will use them as usual tabs.
