### ISSUE TITLE
Input value overlaps floating label (MD)

### ISSUE THREAD

**Issue by anpegar** [framework7io/framework7#2077]
Hi everybody,

I'm developing a project with framework7 and MD theme but when I set a value to a text field from javascript, the value overlaps the label.

I've tried with framerwork7 2.0.5  but it also happens with the other versions. To fix it I used jquery but you can also use native javascript.

I have solved it in this way but, is there any more elegant way to do it?
https://codepen.io/anon/pen/xpYEKV

Thanks in advance.

The error:
![errorpen](https://user-images.githubusercontent.com/8124520/34718363-a378b00a-f536-11e7-89c4-95e926547427.png)

My solution:
![solution](https://user-images.githubusercontent.com/8124520/34718388-bb0394ce-f536-11e7-996e-f45a93c58bed.png)

**Comment by nolimits4web** [comment]
How the F7 will know that you have set value there? You must then trigger "change" event on modified input

**Comment by anpegar** [comment]
Hi @nolimits4web,

Do you have an example about that? Sorry, but I don't know hoe to do it.

Thanks again.

**Comment by nolimits4web** [comment]
In v2 there is `app.input.checkEmptyState` method http://framework7.io/docs/inputs.html#input-app-methods

Otherwise call `$('your-input-selector').trigger('change')`

**Comment by anpegar** [comment]
ok, perfect !!

In v2 app.input.checkEmptyState('#myname'); works fine, now I'll try in v1.6.4 with $('myname').trigger('change') because in v2 this it doesn't work.

Why in v1.6.4? Because I'm using framework7-vue and I think at the moment it doesn't work with v2, isn't?

thanks.

**Comment by anpegar** [comment]
Hi again,

In v1.6.4 it doesn't work, could you check out my codepen please?

https://codepen.io/anon/pen/xpYEKV

thanks.

**Comment by nolimits4web** [comment]
Some issue with jQuery, use Dom7 instead https://codepen.io/anon/pen/wpydJa

**Comment by anpegar** [comment]
Works fine !! Thanks so much for your help.
