### ISSUE TITLE
Right click disabled in browser

### ISSUE THREAD

**Issue by chachew** [framework7io/framework7#2080]
I am developing in a cordova application and i use chrome to develop locally with and debug things. Since moving to V2 i can no longer right-click in the browser to get a local element view in my dev-tools. Is this disabled in the framework somehow?

**Comment by chachew** [comment]
Actually i see where its disabled in the framework. For anyone else looking its:
`document.addEventListener('contextmenu', function (e) {
    if (params.disableContextMenu && (Device.ios || Device.android || Device.cordova)) {
      e.preventDefault();
    }
    if (useRipple) {
      if (activableElement) { removeActive(); }
      rippleTouchEnd();
    }
  });
`

**Comment by 00j** [comment]
This can be enabled using

`touch: {`
  `   // enabled for development`
  `   disableContextMenu:false`
`}`

**Comment by Enalmada** [comment]
This should be enabled in the samples with a note about it.  Was driving me CrAzY!
