### ISSUE TITLE
DOC Panel, incorrect class attribute.

### ISSUE THREAD

**Issue by Braxmann** [framework7io/framework7#2081]
In DOC link https://framework7.io/docs/panel.html, the classes are receiving "panel-close" are incorrect. The correct form is "close-panel".

**Comment by shastox** [comment]
https://github.com/framework7io/framework7/search?utf8=%E2%9C%93&q=close-panel&type= ?

**Comment by SpiderNeo1** [comment]
@Braxmann :
In Framework7 V1 : the class name is "close-panel"
In Framework7 V2 : the class name is "panel-close".

In the website, the DOC is for the V2. So there is no error.
