### ISSUE TITLE
[v2] Plugin page callbacks not called on inline index page

### ISSUE THREAD

**Issue by valnub** [framework7io/framework7#2083]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

---------------------

* Framework7 Version: 2.0.5
* Platform and Target: Google Chrome on MacOS High Sierra

---------------------

### What you did
Tried to port [upscroller plugin](https://github.com/valnub/Framework7-Upscroller-Plugin) to v2.

### Expected Behavior
When inline page "index" is opened, event `pageBeforeIn` should be called. – At least in v1 this was the old behavior.

### Actual Behavior
Event is not called. But when a new file `about.html` with page name "about" is created and I open this page through a link `<a class="link" href="/about/">to about</a>`, then `pageBeforeIn` is called correctly.

Is this expected behavior or a bug?

### Test HTML

```html
<div id="app">
   <div class="view view-main">
      <div class="pages">
         <div data-name="index" class="page" data-page="index">
            <div class="page-content main">
               <a class="link" href="/about/">to page 2</a>
            </div>
         </div>
      </div>
   </div>
</div>
```

### about.html

```html
<div class="page" data-page="about">
  <div class="page-content">
    <p>About page</p>
  </div>
</div>
```

### Init code
```javascript
Framework7.use(f7UpscrollerPlugin);

var app = new Framework7({
    root: '#app',
    upscroller: true,
    routes: [{
        path: '/about/',
        url: 'about.html',
    }],
});

var mainView = app.views.create('.view-main');
```

### Plugin code

```javascript
f7UpscrollerPlugin = {
    name: 'upscroller',
    params: {
        text: 'Go up',
        ignorePages: []
    },
    on: {
        init: function() {
            /*
               This gets called correctly on app start. However, I miss
               "page" parameter because I need to check if the current
               page is listed in `app.params.ignorePages`.
            */
        },
        pageBeforeIn: function(page) {
            // Not called for index page :-(
            // But for "about" page this gets called correctly.
        },
    }
};
```

**Comment by nolimits4web** [comment]
It is expected, because `pageBeforeIn` triggers only BEFORE animation, initial page doesn't have any transition so it won't fire. I believe the `pageInit` event must be enough for you.

`init` event is the one-time event fired on App init (not page init)

And i think you want to put params under `upscroller` prop then use it like:
```
...
    params: {
        upscroller: {
          text: 'Go up',
          ignorePages: [],
        }
    },
...

**Comment by valnub** [comment]
Alright, @nolimits4web thanks! I'll see how far I can get just with `pageInit`.

**Comment by nolimits4web** [comment]
But why do you need `pageBeforeIn`, i see you have `pageBeforeInit` in your code at https://github.com/valnub/Framework7-Upscroller-Plugin/blob/master/src/framework7.upscroller.js#L9 This event in v2 has been renamed to `pageMounted`

**Comment by valnub** [comment]
@nolimits4web Ah, I see. Didn't know that it was renamed that way. I thought `pageBeforeIn` was the v2 version of `pageBeforeInit` looking at the [plugin docs](https://framework7.io/docs/plugins-api.html#demo-plugin) 😅

**Comment by nolimits4web** [comment]
Yeah, that was for example, refer to all router events list at https://framework7.io/docs/view.html#router-instance-events

**Comment by nolimits4web** [comment]
@valnub example on how do you use it?

**Comment by valnub** [comment]
@nolimits4web 
```javascript
f7UpscrollerPlugin = {
	name: 'upscroller',
	params: {
		text: 'Go up',
		ignorePages: []
	},
	on: {
		pageInit: function (page) {
			console.log('nothing happens');
		},
		pageMounted: function (page) {
			console.log('nothing happens');
		},
	}
};
```

**Comment by nolimits4web** [comment]
Ok and how do you enable/install it?

**Comment by nolimits4web** [comment]
Must be before you init the app

**Comment by nolimits4web** [comment]
Ok, even in Kitchen Sink if you do:
```js
Framework7.use({
  name: 'something',
  on: {
    pageInit() {
      console.log('pageInit')
    }
  }
});
```
Right before `var app = new Framework7()`, you will see `pageInit` in console twice for both main and right panel views

**Comment by valnub** [comment]
@nolimits4web Very weird, I don't understand what's wrong. I've uploaded the project [here](https://github.com/valnub/f7-v2-plugin-test). Just run `gulp` to start. Relevant files are [index.html](https://github.com/valnub/f7-v2-plugin-test/blob/master/index.html) and [framework7.upscroller.js](https://github.com/valnub/f7-v2-plugin-test/blob/master/src/framework7.upscroller.js)

**Comment by nolimits4web** [comment]
There shouldn't be `<div class="pages"></div>` element in v2, that was the error

**Comment by valnub** [comment]
@nolimits4web 🤔  Hm, ok now this happens:

1. Only `pageInit` gets called for index page.
2. Click on link to about page -> `pageMounted` and `pageInit` get called for about page.

`pageBeforeInit` never gets called.

Is this expected behavior?

**Comment by nolimits4web** [comment]
Yes, this is expected behavior, pageMounted doesn't called for init page because it was initially mounted

**Comment by valnub** [comment]
@nolimits4web Argh, nevermind. I had a typo mistake. I wrote `pageBeforeInit` instead of `pageBeforeIn` 😆

**Comment by valnub** [comment]
@nolimits4web Ok, cool thanks Vladi 😄 👍
