### ISSUE TITLE
use ".hide-on-phone" instead of ".tablet-only"

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2084]
This is a (multiple allowed):
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2

Components can make use of the css-class **".tablet-only"** which hides parts of it on phone. For example, http://framework7.io/docs/data-table.html.

Would be better to **remove the ".tablet-only" and use ".hide-on-phone"** instead. Because with this, the part is only hidden on phones, but not on all other displays (such as tablet, laptop or pc). Actually, with ".tablet-only", the parts will only show on tablets but not on laptop or pc.

**Comment by nimo23** [comment]
The same goes also for http://framework7.io/docs/list-view.html class: ".tablet-inset"

Use **"inset-phone"** instead, so only on phone "inset" is shown, but not on larger screens (like tablets or laptop,..).

**Comment by ZanderBrown** [comment]
First suggestion: Possible but I'm not sure and would be a breaking change

Second suggestion: Doesn't really make much sense

**Comment by nimo23** [comment]
>  Second suggestion: Doesn't really make much sense

yes, right. I mean: "large-screen-inset" inset for anything which is not a phone.

**Comment by ZanderBrown** [comment]
@nolimits4web thoughts?

**Comment by sanbenedetto** [comment]
tablet-only/tablet-inset means: 
any "screen-size" **equal or greater** than "768px"
which includes tablet or any other screen **>=** "768px"

"css" doesn't really know whether it is an iphone or ipad

i can definitely see the "comments" of data-table on my (big) screen
probably you guys have a small screen (??)


framework7.css:18610

```
.data-table .tablet-only,
.data-table .tablet-landscape-only {
  display: none;
}
@media (min-width: 768px) {
  .data-table .tablet-only {
    display: table-cell;
  }
}
@media (min-width: 768px) and (orientation: landscape) {
  .data-table .tablet-landscape-only {
    display: table-cell;
  }
}

```

**Comment by nimo23** [comment]
@sanbenedetto yes, it s ok. 

However, then ".tablet-only" should at least be renamed because it is not only ".tablet" and this clause should be used instead:

"Is it a phone or not" - and not "is it a tablet or not",

> "css" doesn't really know whether it is an mobile or tablet or desk

yes, however, on other parts, f7 could makes use of browser agent string (see https://framework7.io/docs/device.html).

The point is, this is not only for "datatable". It matters for every component where "tablet" and "phone" leads to different styles. But it s ok for now.

**Comment by sanbenedetto** [comment]
it is not only for "datatable".

anyway
you can add a custom role to your app.css

```
.phone-only {
  diplay:none;
}

/* iphone 6 */
@media only screen 
and (min-device-width : 375px) 
and (max-device-width : 667px) { 
  .phone-only {
    diplay:block;
  }
}
```

http://stephen.io/mediaqueries/#iPhone

**Comment by nolimits4web** [comment]
No chances to change/rename it for now as it, as @ZanderBrown pointed, will be a breaking change. Just keep in mind that it means for screens >= 768 width. If you need more precious rules just use simple media queries in your custom CSS
