### ISSUE TITLE
[data-table] provide ".links-datatable" for master-detail

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2085]
This is a (multiple allowed):
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2

The "http://framework7.io/docs/list-view.html" has a  ".links-list" - for clicking the list item. 

Would be nice to provide this also for datatable:
- **".links-datatable"**:
when clicking the overall row, action is triggered (going to "detail-view" for this row). The "list-view" shows a right arrow when using ".links-list", however, for datatable ".links-datatable", no arrow should be shown. Only the visual style by clicking the row should show the user that the row of the datatable is clickable.

**Comment by nolimits4web** [comment]
> when using ".links-list", however, for datatable ".links-datatable", no arrow should be shown. Only the visual style by clicking the row should show the user that the row of the datatable is clickable.

There is no sense in this because such links table won't look any different from usual data table and user will know that there is a link only when he clicks it.

Then just implement it manually by calling `.router.navigate('required-url')` when clicking a data table row
