### ISSUE TITLE
template7 not defined when using "componentUrl"

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2087]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 2

I have es6 module setup with f7 with this import:

`import Framework7 from 'framework7/dist/framework7.esm.bundle.js';`

When using **componentUrl (the same error for template/templateUrl/component)**:

```
<template>
  <div class="page" data-name="page-1">
   </div>
..</template>
```

I get this error in the console:

`ReferenceError: Template7 is not defined`

However, as I use "framework7.esm.bundle", Template7 must be defined.

**Comment by nimo23** [comment]
For a workaround, I put Template7 manually in the head section. 

Would be good to remove the dependency of "Template 7" and use common javascript for templating which is more powerful and faster.

https://github.com/framework7io/framework7/issues/2091

**Comment by nolimits4web** [comment]
Component includes T7 from node_modules, so if you are bundling the app with WebPack or something else, make sure you have enabled dependencies modules resolving from node_modules

**Comment by nimo23** [comment]
yes, I have to put the import statement of "template7", with this it works.

**Comment by nolimits4web** [comment]
Do you reference Template7 in your page custom code?

**Comment by nimo23** [comment]
Both cases works. Either manual by putting template7 within "head"-section. 
Or putting template7 as a import-statement within es-module. 

But users must know :

`import Framework7 from 'framework7/dist/framework7.esm.bundle.js';`

does not include "template7".

Maybe a short note in the doc should be included..

**Comment by nolimits4web** [comment]
Ok,

> Either manual by putting template7 within "head"-section.

Don't do it if you use ES import for F7, in this case you will have duplicated Template7 source in your code
