### ISSUE TITLE
v2.0.6 SwipeoutDeleted events do not work

### ISSUE THREAD

**Issue by KELINGYANG** [framework7io/framework7#2088]
&lt;li class="swipeout"&gt;&lt;/li&gt;
&lt;li class="swipeout swipeout-opened swipeout-deleting swipeout-transitioning" style="height: 0px;"&gt;&lt;/li&gt;

**Comment by nolimits4web** [comment]
And how and where do you listen for this event?

**Comment by nolimits4web** [comment]
This route events are used for pageEvents basically and may not work with other events. If you use component then you can do it in other way:
```
<template>
  <div class="page" @swipeoute:delete="onSwipeoutDelete" @swipeoute:deleted="onSwipeoutDeleted">
    ...
  </div>
</template>
<script>
  return {
    methods: {
      onSwipeoutDelete: function (e) {
        // do something on swipeout delete
      },
      onSwipeoutDeleted: function (e) {
        // do something on swipeout deleted
      },
    }
  }
</script>
