### ISSUE TITLE
[V2] Router Component Styles stay loaded

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2089]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: V2.
* Platform and Target: All

For router components, documentation states:

"Component CSS styles. Styles will be added to the document after component will be mounted (added to DOM), and removed after component will be destroyed (removed from the DOM)"

If a page (A) has styles defined and the following page (B) has styles defined, both styles are present in dom when B is displayed and will be applied to B.  This is confusing and difficult to debug.  I spent hours tracking this down thinking it was a caching issue.  Local styles should be local to that page.  As implemented this doesn't seem useful.

Perhaps adding an id or class to the style tag and then enabling and disabling the style sheet when the page is visible or hidden.  But a local style for one page should not affect another page.

**Comment by nolimits4web** [comment]
It is expected behavior because when you got to page B, then page A is still in DOM, so styles are not removed. You can use `scoped` styles in this case: http://framework7.io/docs/router-component.html#scoped-styles

**Comment by baixiaoyu2997** [comment]
I add  scoped, still don't work,  
style:
`
.navbar~*:not(.no-navbar) .page-content,
    .navbar~.page-content {
        padding-top: 88px !important;
    }
`
 A page to B page by
`
mainView.router.navigate('/improve/rationalizationAdviceAdd/', {
                    animate: true,
                    ignoreCache: true,
                })
`
B page data-scope="1523527536545" ,but in chrome devtools,i can see styles hava this:
`
.navbar~*:not(.no-navbar) .page-content, [data-scope="1523527440553"] .navbar~.page-content {
    padding-top: 88px !important;
}
`
[data-scope="1523527440553"] is A page data-scope
