### ISSUE TITLE
allow "router-component" to be written in jsx

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2091]
This is a (multiple allowed):
* [x] feature-discussion (RFC)

* Framework7 Version: 2

Actually, router components are written in html. Would be nice, if such components can be written in jsx-format. With this, "template7" is not needed anymore, because we can use all javascript functions (forEach,..). 

For example, vue.js also allows its components to be written in jsx-format. 

With this, it also renders faster. 

And please also investigate the possibility to use the **"virtual dom"** of react (the **"react-dom"-part).** A "virtual dom" is **more secure than acting with the dom directly**, is also **faster in rendering** and **uses less memory consumption** (diffs). Why re-inventing  lifecycle and templating and so on..? The virtual dom minimizes updates to the dom by using diffs and so on..leads to more secure code, better performance and less memory consumption (important when using mobile..)

**Comment by REIMYSS** [comment]
I'm having issues with  mainView.router.load({pageName:\"my_page_name\"});
Does not set class of page-current to the page anymore, since update.

**Comment by nimo23** [comment]
>mainView.router.load({pageName:"my_page_name"});

I dont understand what this has to do with this issue?

**Comment by REIMYSS** [comment]
Apologies. Wrong tab.

**Comment by nolimits4web** [comment]
No chances currently to add JSX support natively to F7 router component, because in case you load it via `componentUrl` it is parsed in browser. But you can use component as script files, because component is just an object, it has `render` function where you can use anything you want to return resulting HTML string or element http://framework7.io/docs/router-component.html#component-structure:

```js
/* my-page.js */
import whatEverYouWantToRenderHtml from 'something';

export default {
  render() {
    // context
    const self = this;
    console.log(self.foo); // -> 'bar';

    return whatEverYouWantToRenderHtml(...);
  },
  data() {
    return {
      foo: 'bar',
    }
  },
  on: {
    pageInit() {
      ...
    }
  }
};

/* routes.js */
import myPageComponent from 'my-page.js';

export default [
  {
    path: '/my-page/',
    component: myPageComponent,
  }
]

**Comment by nimo23** [comment]
This is cool. 

What about **performance difference** in compare to using "componentUrl"?

**Comment by nolimits4web** [comment]
The custom object thing apparently will be quicker than `componentUrl` at least because it won't have XHR request delay, but what is in `render` it will depend on what you use there. Tempate7 is fast enough as it just works with strings, but of course ES-next template string will be faster

**Comment by nimo23** [comment]
Thanks. F7 is very flexible, cool!

**Comment by nimo23** [comment]
I want to share some information about jsx/vue-support:

As I claimed in https://github.com/framework7io/framework7/issues/2055, I suggested to drop **vue.js** in favor of **react.js.** 

**However, I investigated these cases and come to the following conclusion:**

Read this carefully

https://www.zeolearn.com/magazine/hyperhtml-vs-vdom

and you come to the same conclusion:

- no more need for "vue/react"-support (dont waste time with this)
- still be framework agnostic (no vue/react-bindings)
- only use es6 templating with the help of **hyperHtml** or "lit-html":
  - https://github.com/WebReflection/hyperHTML
  - https://viperhtml.js.org/hyper.html 
  - https://github.com/PolymerLabs/lit-html
  - see comparison here: https://gist.github.com/WebReflection/fadcc419f5ccaae92bc167d8ff5c611b

So before investing time to support vue/react, I strongly recommend to incorporate these techniques descriped in **hyperHtml** or "lit-html". Maybe you can extend or replace "template.js" with these kind of templating. F7 can make use of it. 

Imagine ,if f7-components does not need to be fully rendered (actually, at least a page must be rendered fully) and other use cases..

Please look a this.


https://www.zeolearn.com/magazine/hyperhtml-vs-vdom

**Comment by nolimits4web** [comment]
This is interesting, thanks, will investigate it

**Comment by rossmartin** [comment]
@nimo23 @nolimits4web 

Thanks to your discussion and some investigating I have found a sound approach for rendering react components using the built in f7 router.  This might help someone in the future.

```javascript
import React from 'react';
import ReactDOM from 'react-dom';

import App from './components/App';
import SomePage from './components/pages/SomePage';

export default [
  {
    path: '/',
    async: renderReactComponent.bind(this, SomePage)
  }
];

function renderReactComponent(ComponentRef, routeTo, routeFrom, resolve, reject) {
  const container = document.createElement('div');

  ReactDOM.render(
    <ComponentRef />
    container,
    () => {
      resolve({ el: container });
    }
  );
}
```
