### ISSUE TITLE
[v2] EaseOutElastic for swiper

### ISSUE THREAD

**Issue by vasilyzakharov** [framework7io/framework7#2094]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: v 2.0.6
* Platform and Target: iOS and Android

### What you did
How can I add a EaseOutElastic effect to my swiper element? Should it be with css or jQuery? Or it is not possible? Thank you

### Expected Behavior
Have an effect of EaseOutElastic on my swiper element like it was implemented here: https://framer.cloud/TQcdd

### Actual Behavior
Need to figure out how to use it

**Comment by nolimits4web** [comment]
You can set required CSS property `transition-timing-function` on `.swiper-wrapper`:
```css
.swiper-wrapper {
  transition-timing-function: ...
}
