### ISSUE TITLE
[v2] call pageinit on index page

### ISSUE THREAD

**Issue by hacktube** [framework7io/framework7#2095]
How to implement call pageinit on the index page in framework7 v2 ?

As if I use the framework7 v1 using the callback function page function but how in v2.

Example code in framework7 v1

App.onPageInit('index', function (page) {
    // your code
}).trigger();

**Comment by nolimits4web** [comment]
in v2 there is no such page-named callbacks

function onHomeInit() {
 //...
};
app.on('pageInit', function (page) {
  if (page.name === 'index') onHomeInit();
});
//trigger it
onHomeInit();
