### ISSUE TITLE
[toolbar] ".hide-bars-on-scroll" does not work

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2097]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 2

In https://framework7.io/docs/toolbar-tabbar.html
there are these classes to hide toolbar and tabbar by setting css-class at "page-content":
- hide-bars-on-scroll
- hide-toolbar-on-scroll 
- keep-bars-on-scroll
- keep-toolbar-on-scroll

None of them work in my case. I have a multi view layout where each view is a tab. And within a view (tab), I have page as below (md-layout): 

```
<div class="page">
  <div class="navbar">
    ...
  </div>
<div class="toolbar tabbar">
..
</div>

<div class="tabs">
	<div class="page-content tab tab-active hide-bars-on-scroll" id="tab1">
	... much text content so that scrolling can be done ...
	</div>
	<div class="page-content tab" id="tab2">
	... Tab 2 content goes here ...
	</div>
	<div class="page-content hide-navbar-on-scroll tab" id="tab3">
	... Tab 3 content goes here ...
	</div>
	</div>
</div>
```

- Case 1: When scrolling down in "tab1", then "navbar" will be hidden but "toolbar tabbar" not. 
- Case 2: When using ".keep-bars-on-scroll" on "page-content" and scrolling down, then "navbar" becomes hidden (instead of keeping) and ""toolbar tabbar" is visible. (so nothing changes in compare to "Case 1"). The other css classes also does not change anything.

**Comment by KELINGYANG** [comment]
<div class="page hide-bars-on-scroll">
  <div class="navbar"></div>
  <div class="toolbar tabbar"></div>
</div>
