### ISSUE TITLE
Picker on change event not working

### ISSUE THREAD

**Issue by jonybuzz** [framework7io/framework7#2098]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 2.0.5
* Platform and Target: Cordova (Android)

### What you did
I used the [datetime picker example](https://framework7.io/docs/picker.html#examples) from the docs and kitchen sink 

### Expected Behavior
It should update the number of days when the month column is changed

### Actual Behavior
The picker never execs the event listener on change

**Comment by nolimits4web** [comment]
And how do you use it?

**Comment by MiguelQueiroz** [comment]
For me, I usually use the onClose event which then i do a getValue
