### ISSUE TITLE
[v2] Dynamic route params from path aren't correctly interpolated in url

### ISSUE THREAD

**Issue by mamccr** [framework7io/framework7#2099]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.5.
* Platform and Target: CORDOVA

### What you did
The documentation for routes (http://framework7.io/docs/routes.html#route-properties) says that if I'm loading page content vi ajax, I can embed dynamic route params from the route path in the url using handlebar syntax:

Load page content via Ajax.Also supports dynamic route params from route path using {{paramName}} expression, e.g.
```
{
   path: '/users/:userId/posts/:postId',
   url: 'http://myapp.com/posts/{{userId}}/{{postId}}'
}
```

Here's my route:

  ```
  {
    path: '/question/:question_id',
    url: '/question/{{question_id}}/answer'
  }
```

### Expected Behavior
When I link to /question/1 in the app, my server gets a request to /question/1/answer

### Actual Behavior
When I link to /question/1 in the app, my server gets a request to /question/%7B%7Bquestion_id%7D%7D/answer

**Comment by mamccr** [comment]
This may be more philosophical than just reporting the bug, but I would like to point out that all of this is only an issue because in v2 I can't just link to something and have it load that thing via ajax and figure out the right thing to do with it like I did in prior versions of framework7. Now it just complains that the route isn't found if I link to something that isn't explicitly defined in the routes. This is almost a deal breaker for me, but I'm beating my head against the wall of this migration (particularly the routing part) because the other features are worth it. But I can't help but wonder why that super nice feature was dropped in favor of the new approach, which feels like a real burden by comparison. Am I missing something?

**Comment by nolimits4web** [comment]
Feature with dynamic route params passing to url introduced in 2.0.6, just update F7
