### ISSUE TITLE
Autocomplete with Ajax in Framework7 BUG! it does not work in last version

### ISSUE THREAD

**Issue by rapgithub** [framework7io/framework7#2101]
in version 2.2 it was working! 

I was trying to figure it out why the Autocomplete with Ajax was not working and trying to find if there was an error to init it .. but finally I found out that the Autocomplete with Ajax  it is not working in the last version of framework7 it stuck when searching and make the browser unresponsive and with the need to refresh it... to exit... 

in version 2.2 it is working fine in the last version of framework7 not working anymore..
Please check it! thanks

**Comment by rapgithub** [comment]
by the meantime I received a feedback that can be fixed like this:

replace “query” with "obj.query" or “query” with "query.query" like below: 

in the code:

source: function (obj, render) {
  var query=obj.query;
...


or in the code:

source: function (query, render) {
  var query=query.query;
...

I will wait the fix later on...

**Comment by rapgithub** [comment]
I will wait the fix later on...

**Comment by ZanderBrown** [comment]
Doesn't seem to be a problem here
