### ISSUE TITLE
[v2] ul element in virtual list

### ISSUE THREAD

**Issue by hacktube** [framework7io/framework7#2103]
I want to use a virtual list using template7. However I'm having constraints, there is an extra element < ul style = "height: xxx" > where I don't use it. If there is such an element, the application will look ugly.

<a href="https://ibb.co/nbfFmm"><img src="https://thumb.ibb.co/nbfFmm/ul.png" alt="ul" border="0"></a>

the element can be deleted by using the code

`$ ("ul") find ("." col-50 ") unwrap ();`

But while typing the search, a list of searchable content disappears.

FYI:
I am using the design grid layouts, so there is no need to `<ul>` element

**Comment by ZanderBrown** [comment]
Can we see how your constructing your virtual list please

**Comment by hacktube** [comment]
My code same as example code in the fw7 docs.

https://framework7.io/docs/virtual-list.html

**Comment by hacktube** [comment]
@nolimits4web how to use virtual list without ul/list ? I set createUI: false, not change anything.

**Comment by nolimits4web** [comment]
This fix will be available in next release. For now you can use it with ul, just make your cards as `li` elements, some extra styles may be needed

**Comment by hacktube** [comment]
@nolimits4web thanks you so much bro..

**Comment by hacktube** [comment]
Hi @nolimits4web , I just tried virtual function list with infinite scroll, but there are some things that can make the look of the application being ugly.

If my earlier disputed element `<ul style="height: xxx">`, there are more such barriers automatically add elements of style="top: xxx" on element <a href ... > because previously did not use <a href ... > on previous issues.

not only is it top: xxx and the height:xxx value be increased if I scroll down using the infinite scroll. I've been using the function setListHeight: false but no change of any kind.

<a href="https://ibb.co/k3Obe6"><img src="https://thumb.ibb.co/k3Obe6/test.png" alt="test" border="0"></a>

have you added this feature to the next update?

and this is an example code

[virtual-list-infinite-scroll.txt](https://github.com/framework7io/framework7/files/1637822/virtual-list-infinite-scroll.txt)
