### ISSUE TITLE
Routable Tabs how to component url with Ajax request?

### ISSUE THREAD

**Issue by KELINGYANG** [framework7io/framework7#2104]
routes = [
  {
    path: '/tabs/',
    url: './pages/tabs/index.html',
    tabs: [
      {
        path: '/tab-1/',
        id: 'tab-1',
        componentUrl: './pages/tabs/tab-1.html',
      },
      {
        path: '/tab-2/',
        id: 'tab-2',
        componentUrl: './pages/tabs/tab-2.html',
      },
    ],
  }
]

**Comment by ryandong8321** [comment]
Hi @KELINGYANG , I still use the pageInit function in page, could you pls tell how did you do. Thx
