### ISSUE TITLE
[datatable] use "<caption>" for "title/header

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2106]
This is a (multiple allowed):
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2

Please add `<caption>` for visual styles for **title/header of datatable**-component:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption

According to doc http://framework7.io/docs/data-table.html:

> When data table is used within Card it is possible to use additional data table title with actions in card header.

But what about, when not using "Card"? Datatable should also be styled with "data-table-title" by using html-element `<caption>`.

**Comment by nimo23** [comment]
Or maybe it is not useful, because we already have "content block" where we can already set title. Feel free to close.

**Comment by nolimits4web** [comment]
Yes, use block-title instead
