### ISSUE TITLE
data-name for index page not working

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#2107]
@nolimits4web 

$$(document).on('page:init', '.page[data-name="**home**"]', function (e) {
  alert('hi');
})

I am using starter template(single view) and the above code is not working for index page, while below code is working for about page:

$$(document).on('page:init', '.page[data-name="**about**"]', function (e) {
  alert('hi');
})

**Comment by hacktube** [comment]
Check this out

https://github.com/framework7io/framework7/issues/2095

**Comment by danish1023** [comment]
@hacktube 
$$(document).on('page:init', function (e) {
  alert('hi');
})

Why this is not working on index page?
