### ISSUE TITLE
Page name check on index page

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#2108]
@nolimits4web 
#2095 
According to you -
in v2 there is no such page-named callbacks
```js
function onHomeInit() {
 //...
};
app.on('pageInit', function (page) {
  if (page.name === 'index') onHomeInit();
});
//trigger it
onHomeInit();
```
Below code is not executing on index page, so how can i check the index page?
```js
app.on('pageInit', function (page) {
  if (page.name === 'index') onHomeInit();
});
```

**Comment by hacktube** [comment]
Thats code is working fine

**Comment by hacktube** [comment]
Try this

function onHomeInit() {
alert("working");
console.log("this is index page");
};
app.on('pageInit', function (page) {
if (page.name === 'index')
onHomeInit();
});
//trigger it
onHomeInit();
