### ISSUE TITLE
[v2] Disabled route 

### ISSUE THREAD

**Issue by navi8602** [framework7io/framework7#2109]
Как переходить по страницам, не используя механизм f7 route. Если никак - то что прописать в route, что бы "грузились", пусть ajax ом страницы целиком. Ранее в v1 у нас удалось подружить f7 с роутами meteorjs! После обновления на версию v2 у нас перестали работать переходы в ссылках. Так как MeteorJS "подгружает" контент не "страницей целиком", а "правит DOM" как нужно прописать route f7, что бы это работало. Очень сильная нужда в обновлении и проект скоро обновлять, стилистику всю исправили, но вот с переходами случилась беда ( С нас вознаграждения за помощь

**Comment by J05HI** [comment]
@navi8602
Englisch please...

**Comment by navi8602** [comment]
@J05HI 

How to navigate pages without using the mechanism of the f7 route. If no - what to prescribe in route, that would care, let the ajax entire page. Previously in v1 we have managed to make friends f7 with routes meteorjs! After upgrading to v2 we have encountered in the navigation links. Since MeteorJS "loads" the content is not "entire page" and "rules of the DOM" as it is necessary to prescribe route f7, it worked. A very strong need to be updated and a draft will soon update the style of the entire fixed, but with transitions in trouble ( From us compensation for the help. Sorry for my English

**Comment by J05HI** [comment]
@navi8602
I think it's not possible yet. You have to define routes before.
@nolimits4web needs to add it :)

**Comment by nolimits4web** [comment]
Same as http://forum.framework7.io/t/v2-disabled-router-2/1928/3
