### ISSUE TITLE
[range-slider] knob too small

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2110]
This is a (multiple allowed):
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2

**The "knob" of the range-slider is too small for easy use on mobile phone (Actually, it is even smaller as a icon (for example, the icons on the left and the right side of the range-slider are bigger as the knob itself).**

I suggest to give it at least 
**two additional options controlled by css-class (".knob-big", ".knob-rect")**:

- **"knob-big"** (makes the knob bigger):
![range-slider-bigger-knob](https://user-images.githubusercontent.com/3045549/35016747-4af98da2-fb1a-11e7-91af-b51b5fee6316.png)

- **"knob-rect"** (uses a rectangle as a knob, the rectangle fills the available height of the range slider and has more width as standard-knob. If value is visible while changing the knob, the value can be printed left of the "knob-rectangle", if user scrolls right. And if user scrolls left, the value should be visible on the right side of the "knob-rectangle"):

![range-slider-knop-rect](https://user-images.githubusercontent.com/3045549/35016784-72c82992-fb1a-11e7-8818-0b94cfb7bbfe.png)

**Comment by J05HI** [comment]
Thanks really ugly 😩

**Comment by nolimits4web** [comment]
You can easily and customize it to your needs using simple CSS rule:
```
.range-knob {
  width: 44px;
  height: 44px;
  margin-left: -22px;
  margin-top: -22px;
}

**Comment by nimo23** [comment]
yes, I know. This is how I did to get the images above (md-style). 

However, why shipping with a too small knob as default? 

And only changing ".range-knob" is not enough, because  other classes must also be changed (.range-knob-active-state, label, etc..)

The knob is too small to use, at least it must be big as the icon. For ios-theme, you see, the knob has sufficient size to use, but knob for md-theme could be improved.

**Comment by nolimits4web** [comment]
Size of knob is the same as in official material design guides

**Comment by J05HI** [comment]
I think the knob is perfect 👌 
Can drag it easily :)
