### ISSUE TITLE
[V2] IOS tabbar not evening spaced

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2115]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2
* Platform and Target: Firefox, chrome (perhaps cordova too)

Tabbar items are evenly spaced in phone page width but not ipad page width.  On ipad, the items are centered on tabbar.  There appears to be a breakpoint.  This is not an issue in MD.

Example, add tabbar with 2 items (2 is most effective).  Size the browser width to a phone type width.  Items will be in 2 columns centered (expected).  Increase the width of the window and the items will be pushed to the center of the tabbar.  If this is intended, it's odd responsive behavior.

**Comment by nolimits4web** [comment]
This is intended because this is how native iOS apps behave on iPad, including Apple apps
