### ISSUE TITLE
Messages in RTL shifted to right in google chrome with vertical scrollbar 

### ISSUE THREAD

**Issue by pavel5** [framework7io/framework7#2116]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.6
* Platform and Target: Google Chrome 63.0.3239.132 (desktop client)
* Live Link or JSFiddle: https://jsfiddle.net/94nn7c4z/3/

### What you did
I take code example for messages from docs and add rtl support (add dir="rtl" to html tag and changed framework7.min.css to framework7.rtl.min.css)

### Expected Behavior
content window should be centered

### Actual Behavior
content window shifted to right 

It happens in desktop google chrome only (on mac at least), not in ios chrome & safari or desktop safari.

I use this framework for facebook messenger chatbot webview and this will be shown not only on messenger app in ios or android, but also in desktop client (at messenger.com)

**Comment by nolimits4web** [comment]
This is what i see in your fiddle:

<img width="762" alt="rtlmessages" src="https://user-images.githubusercontent.com/999588/35140338-f03eff9c-fd07-11e7-8888-683755958776.png">

Is this wrong?

**Comment by pavel5** [comment]
In google chrome (on mac) I see this one: 
Its look like all page shift to right on size of vertical scrollbar

**Comment by pavel5** [comment]
<img width="616" alt="2018-01-19 10 41 45" src="https://user-images.githubusercontent.com/22134724/35142191-3a67f738-fd06-11e7-9c46-0a7820292b62.png">

**Comment by nolimits4web** [comment]
I am same on macos and same Google Chrome, everything looks correct for me. Make sure you don't have enabled Chrome plugins that can break it

**Comment by pavel5** [comment]
Its happened in google chrome on mac with always shown scroll bars (System Preferences -> General -> Show scroll bars -> Always)
