### ISSUE TITLE
Smart Select on Custom Modal v1

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/framework7#2117]
I have a custom modal and it will be triggered when a button is click, inside of that we I have a smart select, but it is not showing, can somebody point me out what should I add?

PS: I have read some past issue  about this , but I did not understand clearly. (like the initilized the view etc..)

**Comment by nolimits4web** [comment]
http://forum.framework7.io/t/custom-modal-with-smart-select/1970/2
