### ISSUE TITLE
[V2] Swipeout Delete doesn't throw event

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2119]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.06.
* Platform and Target: Firefox, Chrome

I know this was an issue earlier but it still isn't working.  I swipe the list item with delete, the item is removed from the list but the swiped:deleted event fires intermittently.    I also tried it on kitchen sink and the alert box (after deleted) never fires.  The dom inspector does show the events bound to the <li> element.

Here is my markup and event handler.  Nothing special here.  My console messages will work once in a while but I can't seem to repeat it.  
```
html:
<div id="item-list" class="list media-list">
<ul>
<li id="1001" class="swipeout">
   <div class="swipeout-content item-content">
     <div class="item-inner">
        <div class="item-title-row">
	    <div class="item-title">Item 1</div>
		<div class="item-after"></div>
  	   </div>
	   <div class="item-subtitle">  </div>
	   <div class="item-text"></div>
      </div>
   </div>
	
    <div class="swipeout-actions-right">
       <a href="#" class="swipeout-delete" data-confirm="Are you sure want to delete this item?" data-confirm-title="Delete?">Delete</a>
    </div>
</li>
</ul>
</div>

js:
// bind swipe delete event
myPage.find('.swipeout').on('swipeout:deleted', function () {
	var id = $$(this).prop('id');
	console.log('Deleted: '+id);
});
```

After delete, the <li> tag looks like so:

`<li id="4" class="swipeout swipeout-opened swipeout-deleting swipeout-transitioning" style="height: 0px;">`

**Comment by nolimits4web** [comment]
1. Put `item-content` under `swipeout-content`
2. Make sure you have enabled `removeElements: true` parameter http://framework7.io/docs/swipeout.html#swipeout-app-parameters

It works perfectly in KS at http://framework7.io/kitchen-sink/, just try to add this to console:
```
$(document).on('swipeout:deleted', () => {console.log('test')})
```

Otherwise, problem is somewhere else

**Comment by eradin** [comment]
The markup seems correct.  It worked fine on my ipad but not in Firefox or Chrome on the desktop (the delete shows on FF but not on Chrome).  Probably has something to do with the mouse as swipe events.  It does seem to work on touch devices.

Thanks.

**Comment by nolimits4web** [comment]
> It does seem to work on touch devices.

Which is the main purpose of Swipeout component
