### ISSUE TITLE
[list-view] .item-after with buttons not aligned to arrow on right side

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2125]
* Framework7 Version: 2

Using buttons within `.list .item-after` within `accordion list`, renders this **on the right side** of a list item:

![b1](https://user-images.githubusercontent.com/3045549/35175885-337c5552-fd76-11e7-99d8-86a634b5dcaa.png)

By deleting `max-height: 28px;` form `.list .item-after`, the baseline with the arrow on the right side is better:

![b2](https://user-images.githubusercontent.com/3045549/35175889-37dd9840-fd76-11e7-93dd-51feef263c9e.png)

**Comment by nolimits4web** [comment]
There are typography classes to tweak flex box behavior, F7 can't cover all possible cases for all kind of layouts, don't hesitate to use custom styles to tweak it as you need:

http://framework7.io/docs/typography.html#align-items
```
<div class="item-after align-items-center"> buttons here </div>
