### ISSUE TITLE
[accordion] sticky "accordion item-link"

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2127]
This is a (multiple allowed):
* [x] enhancement

* Framework7 Version: 2

List-View-Component has grouped list:

> With list groups, group titles have sticky position during scroll within single group.

Please provide sticky position during scroll of accordion-list. The sticky element should be the `.item-content .item-link` of the accordion item which is actually opened (`accordion-item accordion-item-opened`).

So F7 could assign ".item-content .item-link" of actual item

```
position: sticky;
top: 0;
z-index: 1;
```

if user assigned css-classss **".item-link-sticky"** to ".accordion"

**Comment by nolimits4web** [comment]
F7 can't cover all possible cases for all kind of layouts, don't hesitate to use custom styles to tweak it as you need. This is basically CSS basics, i think it is not too hard to add `position: sticky` to the element you need to make sticky
