### ISSUE TITLE
on browser goBack close sheet insted go to back view

### ISSUE THREAD

**Issue by nicojmb** [framework7io/framework7#2128]
This is a (multiple allowed):
* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.6
* Platform and Target: ANDROID
* Live Link or JSFiddle: 

### What you did
IF open a sheet modal and click browser go back, modal still open buy view go back

### Expected Behavior
Close sheet only

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

**Comment by nolimits4web** [comment]
Routable modals must be used in this case http://framework7.io/docs/routes.html#routable-modals
