### ISSUE TITLE
Prevent scroll/bounce for Page or View in v2?

### ISSUE THREAD

**Issue by JasonKleban** [framework7io/framework7#2129]
I'm using an ios native control overlaid on top of the framework7-based web page, aligned with one of the elements in the page.  This works well, but the rubber-banding effect when scrolling still occurs and moves the html content underneath and independently of the native overlay.  Is there a way yet in v2 to disable the scrolling/bouncing for a page or view?

Alternatively, is there an efficient way to get animation frame callbacks when the bounce effect is animating and complete so that I can update the host with the current position of the alignment element?  I don't think there is.

Thanks!

**Comment by nolimits4web** [comment]
Well, if you use Cordova app then it supports  by setting `DisallowOverscroll` in config.xml (https://cordova.apache.org/docs/en/latest/config_ref/). If it is not Cordova, then will be not so simple. As a solution, you may try to set the following CSS rule:
```
html,
body {
  position: fixed;
  overflow: hidden;
}
```

**Comment by nolimits4web** [comment]
> Alternatively, is there an efficient way to get animation frame callbacks when the bounce effect is animating and complete so that I can update the host with the current position of the alignment element?

Not easy as well. I believe it is a `scroll` event on `document.body`
