### ISSUE TITLE
Smart-Select not work at first time on second page

### ISSUE THREAD

**Issue by nicojmb** [framework7io/framework7#2133]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.6
* Platform and Target: WEB
* Live Link or JSFiddle: I'cant do it work on jsFiddle, here other alternative http://dev.nicojmb.com/

### What you did
Open a second page with smart-select element, if a click on smart-select and select option page no show selected option.

To open this page click on "CART" link (on top right)

### Expected Behavior
Showme selected option at first click

### Actual Behavior
No show selected option buy if i click again works great.

**Comment by nolimits4web** [comment]
Provided link at  http://dev.nicojmb.com/ doesn't work me, not found

**Comment by nicojmb** [comment]
Maybe a DNS issue, i've moved the code to site root (www.nicojmb.com) try now with this link

**Comment by nolimits4web** [comment]
It happens because you init same View twice, first time in HTML with `view-init` attaribute, second time in JS with `views.create(...`. Use only something single

**Comment by nicojmb** [comment]
Ooh it's true, i did not realized, thanks!
