### ISSUE TITLE
[V2] input-clear-button doesn't work on textarea

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2135]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2.06
* Platform and Target: FF, Chrome, CORDOVA, IOS, ANDROID

Adding input-clear-button to textarea doesn't present a button.  Documentation states

input:clear | Input Element<input/textarea> | Event will be triggered after input value will be cleared by clicking on input clear button

Markup:

```
<div class="item-input-wrap">
<textarea id="event-message" rows="8" name="message" cols="69" autofocus></textarea>
<span class="input-clear-button"></span>
</div>

```

**Comment by eradin** [comment]
Correction, it does work.  Although, if text is present from a .val() method, it doesn't show up until a key stroke is made.  Would be nice to have it present if any text is present.

**Comment by nolimits4web** [comment]
How can i detect that you did something custom with JS? Trigger `change` event on input/textarea after you change its value programmatically:
```
$textarea.val('new value');
$textarea.trigger('change');

**Comment by nolimits4web** [comment]
Or use `app.input.checkEmptyState` method
