### ISSUE TITLE
V1 Smart Select in Modal

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/framework7#2138]
I am stuck for almost 1 day in here. How to init a view for a smart select?

I have this code for modal

           ``var paymentplan = myApp.modal({
        title: 'Add Payment Plan',
        afterText: '<div id="leave-form" class="list-block">' +
        '<ul>' +
        '<li>' +
        '<div class="item-content">' +
        '<div class="item-inner">' +
        '<div class="item-input">' +
        '<input type="date" placeholder="To">' +
        '</div>' +
        '</div>' +
        '</div>' +
        '</li>' +
        '<li>' +
        '<div class="item-content">' +
        '<div class="item-inner">' +
        '<div class="item-input">' +
        '<input type="text" placeholder="To">' +
        '</div>' +
        '</div>' +
        '</div>' +
        '</li>' +
        '<li>' +
        '<div class="item-content">' +
        '<div class="item-inner">' +
        '<div class="item-input">' +
        '<input type="text" placeholder="Amount">' +
        '</div>' +
        '</div>' +
        '</div>' +
        '<li>' +
        '<a href="#" class="item-link smart-select">' +
        '<select name="fruits">' +
        '<option value="apple" selected>Monthly</option>' +
        '<option value="pineapple">Weekly</option>' +
        '</select>' +
        '<div class="item-content">' +
        '<div class="item-inner">' +
        '<div class="item-title">One Time</div>' +
        '</div>' +
        '</div>' +
        '</a>' +
        '</li>' +
        '<li class=="align-top">' +
        '<div class="item-content">' +
        '<div class="item-inner">' +
        '<div class="item-input">' +
        '<textarea placeholder="Memo"></textarea>' +
        '</div>' +
        '</div>' +
        '</div>' +
        '</li>' +
        '</ul>' +
        '</div>',

        buttons: [{
        text: 'Cancel',
        onClick: function () {
        // myApp.alert('You clicked first button!')
        }
        },
        {
        text: 'Save',
        onClick: function () {
        mainView.router.loadPage('payment-plan.html');
        $$('#new-add-from').css('display', 'block');
        }
        },
        ]
        })`

here is my code for my modal open event
```
             $$(paymentplan).on('modal:opened', function () {
              var anotherView = myApp.addView('.another-view');
            });
```

Can somebody help me how to deal views in smart select?

**Comment by nolimits4web** [comment]
Please, no question at GitHub, http://forum.framework7.io/t/custom-modal-with-smart-select/1970/8
