### ISSUE TITLE
[V2] checkbox doesn't have checked attirbute when checked

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2140]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2.06

When either manually checking a checkbox or via page.$el.find('#checkbox').prop('checked', true), the checked attribute does not appear on the input element.  This can be verified in kitchen sink.

This is important because queries like $$(''input:checked').length will return erroneous results.

**Comment by nolimits4web** [comment]
Everything is correct and this is how it should work, you can check it with native browser checkbox. “:checked” css selector doesn’t have anything with checked attribute as well
