### ISSUE TITLE
when pushState is set to true, back action can't work correct.

### ISSUE THREAD

**Issue by ican1983** [framework7io/framework7#2141]
i download the source code and modify app.js file like bottom picture.
![image](https://user-images.githubusercontent.com/7636901/35316593-73b7f4c4-010d-11e8-9cdf-64858595dc87.png)

it work well when i navigate from index to "Accordion", "Action Sheet" and back to index page.
 but when i navigate like this: index => Tabs => Static Tabs => back => back. then the index page is reloading to 404.html. 
![image](https://user-images.githubusercontent.com/7636901/35317266-ec621244-0110-11e8-90c8-7dd426b5c431.png)

**Comment by nolimits4web** [comment]
You need to set correct pushStateRoot or change home page route to /kitchen-sink/

**Comment by ican1983** [comment]
thank you !  
i change home page route to /framework7/kitchen-sink/, and now it is not navigate to 404.html. 
but it still need to reload index.html page.
![image](https://user-images.githubusercontent.com/7636901/35317915-00a6fb0e-0114-11e8-9fcc-20fd61424bc6.png)

i don't want reload index.html.  please help me . thank you!!

**Comment by nolimits4web** [comment]
You can enable stackPages to keep loaded pages in DOM. Use forum for questions

**Comment by ican1983** [comment]
Thank you very much!!
Orz.

**Comment by MahmoudFawzy** [comment]
On phonegap start url is "file:///android_asset/www/index.html" , so when application use pushState , not working and getting 404
