### ISSUE TITLE
v2.0.6 When the Swipeable Tabs opens the Link automatically

### ISSUE THREAD

**Issue by KELINGYANG** [framework7io/framework7#2142]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2.0.6
* Platform and Target: CORDOVA, IOS, ANDROID

### What you did
```html
<div class="tabs-swipeable-wrap">
                    <div class="tabs">
                        <div id="tab1" class="tab tab-active">
                            <div class="list simple-list" style="margin:0;">
                                <ul>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>
                                </ul>
                            </div>
                        </div>
                        <div id="tab2" class="tab">
                            <div class="list simple-list" style="margin:0;">
                                <ul>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                    <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
```

### Expected Behavior

swipe to 'tab2'

### Actual Behavior

open link '/detail/'

@nolimits4web

**Comment by ZanderBrown** [comment]
I've put your example in ``` but I still have no idea what the problem is

**Comment by KELINGYANG** [comment]
You try the Swipeable Tabs of the demo. @ZanderBrown 

[v2.0.6] on Swipeable Tabs ,  the page to link "/detail/"
[v1.6.5] on Swipeable Tabs ,  the page to "tab2"  

details demo:

`<div id="app">`
    `<div class="view view-main view-init ios-edges" data-url="/">`
     `<div class="page">`
       ` <div class="navbar">`
         ` <div class="navbar-inner">`
            `<div class="title sliding">Framework7</div>`
        `  </div>`
     `   </div>`
       ` <div class="page-content">`
         ` <div class="tabs-swipeable-wrap">`
           ` <div class="tabs">`
             ` <div id="tab1" class="tab tab-active">`
               ` <div class="list simple-list" style="margin:0;">`
                 ` <ul>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                  `  <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 1 Title</a></li>`
                `  </ul>`
                `</div>`
             ` </div>`
              `<div id="tab2" class="tab">`
                `<div class="list simple-list" style="margin:0;">`
                 ` <ul>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                    `<li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                  `  <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                   ` <li style="height:100px;padding:0;"><a href="/detail/" class="item-link" style="height:100px;width:100%;">Tab 2 Title</a></li>`
                 ` </ul>`
               ` </div>`
            `  </div>`
           ` </div>`
         ` </div>`
       ` </div>`
     ` </div>`
   ` </div>`
 ` </div>`

**Comment by nolimits4web** [comment]
It is still not clear for me. Please fill the issue form correctly
