### ISSUE TITLE
swipe back also for md-theme

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2144]
This is a (multiple allowed):
* [x] feature-discussion (RFC)

* Framework7 Version: 2

For users with disabilities (and for the lazy one) it is hard to go to the previous page by **clicking the upper back button in md-theme**. So either **ios-theme with swipe-back** is used or md-theme but without swipe back possibility. This is not flexible. 

**I want to use swipe back but dont want to miss md-look and feel.** 

So why not let user choose between "swipe back" or not independent of the theme. 

Is it possible to extend (or merge this function from ios-theme) to use swipe back with md-theme?
(Swipe back is not about visual styles it s about usability and should not be missed only because of md-theme.)

**Comment by nolimits4web** [comment]
Are there any native Android Google apps use swipe back? How do “lazy” people use them? ;)

**Comment by nimo23** [comment]
> native Android Google apps use swipe back

because "native" android apps does not have the possibility of swipe back (it is not within android or md-theme, because a "swipe-back" is "apple-inventend"..). 
This does not mean, user will not use it. Dont you think it is easier to use swipe back instead of going to top of the screen and click the back button? For larger phones you risk a fall down of your phone if using with one hand without swipe back.

Please support swipe back. Swipe back is not useless, even for md-theme.

**Comment by ZanderBrown** [comment]
It's not good UX to add this on Android

**Comment by nimo23** [comment]
There are a lot of android apps using a kind of swipe back by flipping the actual page down to navigate back - this is is good UX. Bad UX in mobile is finding a button and clicking it only to go back..this is bad UX.

**Comment by nimo23** [comment]
Looking for example, at react native, there are **different kind of page transitioning animations** for both ios and android. Bad UX, no.

Maybe f7 can have also different kind of "page transitioning animations"..where swipe back is only one kind of page change..

**Comment by liyi1472** [comment]
WeChat App

**Comment by siophy** [comment]
There are a lot of Apps support this gesture, and sliding back is a very good gesture. iOS theme has been supported, why not transplant it to MD theme?

**Comment by SergeyKuzmenko** [comment]
Как использовать swipe back?
