### ISSUE TITLE
style for disabled toggle-button 

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2145]
This is a (multiple allowed):
* [x] enhancement

* Framework7 Version: 2

Using common checkbox with disabled flag, the checkbox is automatically rendered different (with opacity), so user can easily see that checkbox is disabled. However, using toggle-button with checkbox disabled, the style does not change. I can adapt the style with toggle-disabled, however, disabled toggle-buttons should always be styled a little different out of the box (maybe grey or with opacity) so user can see, this toogle-button is disabled. If not, user thinks, something does not work with this button..

**Comment by nolimits4web** [comment]
It can be done by adding “disabled” class to toggle element

**Comment by nimo23** [comment]
yes, thanks.
