### ISSUE TITLE
Can't find variable: Dom7

### ISSUE THREAD

**Issue by NikitaKA** [framework7io/framework7#2147]
This is a
* [x] bug

Framework7 Version: 2.0.6
Platform and Target: iOS 10.3.2 Safari

### What you did
Use `https://github.com/vuejs-templates/webpack` boilerplate with Framewok7 installed. Open in mobile Safari (iOS 10.3.2).

### Expected Behavior
Framework7 should initialize without errors.

### Actual Behavior
Error thrown: Can't find variable: Dom7
```
[Error] ReferenceError: Can't find variable: Dom7
  $$1 (dom7.module.js:31)
  Framework7$1 (framework7.esm.bundle.js:781:83)
  Eval Code (main.js:10:102)
  eval
  ./src/main.js (app.js:958)
  webpack_require (app.js:679)
  fn (app.js:89)
  (anonymous function) (app.js:967)
  webpack_require (app.js:679)
  (anonymous function) (app.js:725)
  Global Code (app.js:726)
```

P.S. There is another errors in 10.2, 9 versions...

**Comment by nolimits4web** [comment]
Make sure your webpack/babel also transpiles imported F7 to ES5

**Comment by NikitaKA** [comment]
You were right, thank you very much!
