### ISSUE TITLE
**Swipeout** Glitch on browser Safari  - Framework7 

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2149]
**Swipeout** Glitch on browser Safari 
- when swiping a row, you'll notice a flash when the user swipes, I tried it in my project, other browsers such as google chrome seems to work fine when swipe.
This includes all devices of apple.

**Comment by nolimits4web** [comment]
Can't see anything like that. Please provide more information, screenshot or live preview with the issue or video

**Comment by pluckannfeel** [comment]
![video-1516954268](https://user-images.githubusercontent.com/14131170/35430888-225c3050-02b5-11e8-9d5f-b6d7504281f6.gif)

**Comment by nolimits4web** [comment]
It is an iOS rendering issue try to set `transform: translate3d(0,0,0)` in different swipeout elements, try also to tweak z-index

**Comment by pluckannfeel** [comment]
is there a specific event to set transform: translate3d(0,0,0) in swipeout elements?

**Comment by nolimits4web** [comment]
No, just in CSS, try for different swipeout element parts

**Comment by pluckannfeel** [comment]
i've tried different approach, from tweaking z indexes of elements inside of swipeout, trying alternative transform property. it doesn't work..

**Comment by nolimits4web** [comment]
Would be good to check live example or JSFiddle with the issue then

**Comment by pluckannfeel** [comment]
its yours, even in your docs http://framework7.io/docs/swipeout.html , the behavior i showed to you is the same in your demo. It occurs to every ios device including safari browser

**Comment by nolimits4web** [comment]
Still can't see such glitch on my ios devices

**Comment by pluckannfeel** [comment]
try browsing safari. or your ios device. then swipe i already showed you that live preview
