### ISSUE TITLE
Back link reloads one page too far in the stack

### ISSUE THREAD

**Issue by MatthiasBusch** [framework7io/framework7#2150]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.6
* Platform and Target: Desktop, Windows, Chrome
* Live Link or JSFiddle: http://demo.casseo.de/

### What you did
I created three different pages with links to each other and a navbar with a back link. 
In the app the setting 'xhrCache' is set to 'false'
1. Open the developer bar and watch the network tab
2. Click around the pages from 'page 1' to 'page 2' to 'page 3'
3. Click the back link

### Expected Behavior
You get redirected to page 2, therefore page 2 should be reloaded

### Actual Behavior
You get redirected to page 2, BUT page 1 is reloaded

**Comment by nolimits4web** [comment]
It is by design to make swipeback work, if you don't need it, you can disable `preloadPreviousPage` and `iosSwipeBack` view paremeters

**Comment by MatthiasBusch** [comment]
I updated the demo with added data-attributes for preloadPreviousPage and iosSwipeBack in the back button, but I experience still the same behaviour

**Comment by nolimits4web** [comment]
It must be set as View parameters http://framework7.io/docs/view.html#view-parameters

**Comment by MatthiasBusch** [comment]
I think found a flaw in this concept. If I do need a back button, that doesn't trigger the page reload of the previous page, it's not possible atm? 

I tried adding data-ignore-cache 'false' and data-force 'false' on that specific link, but it is behaving still the same as before.

**Comment by nolimits4web** [comment]
You need to set `preloadPreviousPage: false` and `iosSwipeBack: false` View parameters on View initialization
