### ISSUE TITLE
Cannot copy when select the text

### ISSUE THREAD

**Issue by vcshing** [framework7io/framework7#2151]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: v2.0.6
* Platform and Target: ANDROID
* Live Link or JSFiddle: 

### What you did
Hold the text at input or textarea

### Expected Behavior

> the copy, paste, cut function is appeared. (this image is captured using the older version framework7)

![screenshot_20180127-013242](https://user-images.githubusercontent.com/5351025/35452819-e44781cc-0302-11e8-9cf0-7ecfec04fc23.png)

### Actual Behavior

> When i updated v2.0.6 of framework 7, the native copy and paste panel is missing. It cannot copy and paste (Even at input or textarea)

![screenshot_20180127-013315](https://user-images.githubusercontent.com/5351025/35452836-effba570-0302-11e8-965a-b6824246fda6.png)

i tried to add 
input, textarea {
     -webkit-user-select: auto !important;
     -khtml-user-select: auto !important;
     -moz-user-select: auto !important;
     -ms-user-select: auto !important;
     -o-user-select: auto !important;
     user-select: auto !important;
}
or inline style="user-select:text;"
but the problem still here.

**Comment by nolimits4web** [comment]
Try to set `touch.disableContextMenu: false` app parameter  http://framework7.io/docs/app.html#app-parameters
