### ISSUE TITLE
Tabbar doesnt change state on click

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2152]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2.06
* Platform and Target: All

I want to use the tabbar as a plain old filter bar to show filtered items in the view.  If I use this mark up

```
<div class="toolbar tabbar">
	<div class="toolbar-inner">
		<a href="#" id="filter-yesterday" class="tab-link tab-link-active">Yesterday</a>
		<a href="#" id="filter-today" class="tab-link">Today</a>
		<a href="#" id="filter-unposted" class="tab-link">Unposted</a>
		<a href="#" id="filter-all" class="tab-link">All</a>
	</div>
</div>

```

When I click on any of the last 3 tabs, it shows the click animation but it never changes the active active state.  It's always on the first tab.

My hrefs are '#' because I want to handle the the filtering via click events.  Changing the tab-link to link is worse because it takes away the "active state" all together.

Furthermore, the documentation implies the tabbar is a subset of toolbars that has the added state feature.  If the tabbar is so tightly coupled to tabs, discussion should be removed from the toolbar section and moved entirely to the tabs section of the documentation. Although using the tabbar for this purpose is valuable.

**Comment by nolimits4web** [comment]
Tabbar links are sticked to the logic - change tabs. In your case it won't work. In your case you need to manually set/unset tab-link-active class on clicked tab link, and after call `setHighlight` toolbar method to update  (in case you use MD theme) http://framework7.io/docs/toolbar-tabbar.html#toolbar-app-methods

**Comment by eradin** [comment]
Works perfectly and easy enough to do.  Thanks.
