### ISSUE TITLE
v2 bug

### ISSUE THREAD

**Issue by dulumao** [framework7io/framework7#2153]
i set app params with demo:

> var app = new Framework7({
  id: 'io.framework7.testapp',
  root: '#app',
  theme: theme,
  view: { //* new params
    pushStateOnLoad: false,
    stackPages: true, 
    pushState: true 
  },
  data: function () {
    return {
      user: {
        firstName: 'John',
        lastName: 'Doe',
      },
    };
  },
...

and open chrome debug to view http://localhost:3000/kitchen-sink/#!/action-sheet/

![image](https://user-images.githubusercontent.com/2610297/35473810-41ed0014-03c0-11e8-934d-1be9bcd82853.png)

**Comment by nolimits4web** [comment]
Where is the bug?! These console logs is in your dev tools settings

**Comment by dulumao** [comment]
@nolimits4web in dev tools(network) really has request page
![image](https://user-images.githubusercontent.com/2610297/35478063-33438ddc-040e-11e8-995c-142049a777fa.png)
