### ISSUE TITLE
confusing build

### ISSUE THREAD

**Issue by uptimestar** [framework7io/framework7#2155]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

version: master

### What you did
I compiled .less file to make css using a 3rd party less compiler. (prepros.io)

### Expected Behavior
I expect it to make a working css.

### Actual Behavior
The sample apps/templates stop working. The sample apps provided stop working: because of css. 

This is due to https://github.com/framework7io/framework7/blob/master/scripts/build-config.js
Notice how the needed components are NOT in the .less file.

Fix: move the needed components to the .less file.

**Comment by uptimestar** [comment]
Here is the improved less file that makes it easier: http://dropbox.com/s/9ktgxtos89n5kxw/framework7.less

It shows a missing form.less file, maybe OK.

**Comment by nolimits4web** [comment]
Everything is correct, these modules are included during build. The main f7.less has only core components and modules. In this case (if you do manual less build) you just need to include only components you use, .e.g:
```less
  @import '../node_modules/framework7/dist/framework7.less';
  @import '../node_modules/framework7/dist/components/dialog/dialog.less';
  @import '../node_modules/framework7/dist/components/popup/popup.less';
  @import '../node_modules/framework7/dist/components/login-screen/login-screen.less';
  @import '../node_modules/framework7/dist/components/popover/popover.less';
```
