### ISSUE TITLE
npm packages should be ES5

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2156]
This is a (multiple allowed):
* [ ] bug
* [X] enhancement
* [X] feature-discussion (RFC)

* Framework7 Version: 2.0.7
* Platform and Target: iOS 9.3.5

### What you did
Tried to run Framework7-Vue project on an old iPhone 4S (with iOS 9.3.5).
Unfortunately, we have the most expensive iPhone on the world here in Brazil and a bunch of people who cares about status, so we have a huge old iPhones market do deal with =\

### Expected Behavior
Using babel to transform what doesn't work on iOS 9 should only be on my code. A simple `transform-es2015-constants` and `transform-es2015-arrow-functions` should take care of it.

### Actual Behavior
As `/node_modules/template7/dist/template7.esm.js` (and also Dom7) were not compiled to ES5, and babel automatically ignores node_modules folder, the consts and arrow functions on those files prevented my app to run on such old iPhone. 

### Actual discussion
It would be possible to compile Dom7, F7 and any other dependencies to `dist` using ES5? 
Or at least those silly things that some "not-so-modern-but-not-as-bad-as-internet-exploder" browsers don't understand (like const vars and arrow => functions)?

**Comment by nolimits4web** [comment]
No, sorry, was discussed a lot. With F7 esm components compiled to es5 tree-shaking won't work

**Comment by scriptPilot** [comment]
@JCKodel - Maybe https://github.com/scriptPilot/app-framework may be a solution for you?

**Comment by JCKodel** [comment]
@scriptPilot  I tried, but... I didn't make much progress with it. It's amazing, but I have some issues that I could not figure out with appFramework. For instance: my apps runs inside Facebook messenger, so I need to load a different root page, depending on which part of the app is called (i.e.: it's one app, but the first page and subsequent navigation differs, depending from an argument sent to it).

Also, I guess is not updated for F7 V2, right? V2 gives me the possibility to do something like this:

```
<template>
    <div id="app">
        <f7-statusbar />
        <f7-view :url="rootUrl" :main="true" class="ios-edges" :iosSwipeBack="true" :iosDynamicNavbar="true" :restoreScrollTopOnBack="true"/>
    </div>
</template>

<script src="./app.js" />
```

See that bound :url right there? That's the golden spot for me ^^

In case you wondering, the app is this: https://m.me/assistentePessoalDiva (it's a hybrid Facebook Messenger bot... just say `oi`, then click on some buttons (sorry, is in portuguese)). Each button opens the same F7 app, but with different navigation contexts (and if you open it on the browser, you'll see a different root that is a global menu for all functions: https://bit.ly/assistentePessoalDiva).

That app in particular is F7 V1 and is kinda annoying, because I have to make a component (that is the page) and a index page that loads that component (or load the component in the app.vue, if it's on the website). I feel uncomfortable with this kind of hack (and I was unable to do so using appFramework). V2 solves this binding the url (@nolimits4web: you are a f* genious)

**Comment by blikblum** [comment]
If you are using webpack all you need is add such line to the config: https://github.com/blikblum/marionette.f7/blob/master/examples/hello-world/webpack.config.js#L15

**Comment by JCKodel** [comment]
Solved with
.babelrc
```
{
    "presets":
    [
        [
            "env",
            {
                "modules": false,
                "targets":
                {
                    "browsers":
                    [
                        "last 2 versions",
                        "safari >= 7",
                        "not ie <= 8"
                    ]
                }
            }
        ],
        "stage-2"
    ],
    "plugins":
    [
        "transform-vue-jsx",
        "transform-runtime",
        "transform-object-rest-spread",
        "transform-class-properties",
        "transform-decorators-legacy"
    ],
    "comments": false,
    "env":
    {
        "test":
        {
            "presets":
            [
                "env",
                "stage-2"
            ],
            "plugins":
            [
                "istanbul"
            ]
        }
    }
}
```

webpack config
```
{
                test: /\.js$/,
                loader: "babel-loader",
                include:
                [
                    resolve("src"),
                    resolve("test"),
                    resolve("node_modules/framework7/dist"),
                    resolve("node_modules/template7/dist"),
                    resolve("node_modules/dom7/dist"),
                    resolve("node_modules/framework7-vue/dist"),
                ]
            },
```

Now working on iOS 9.2 and IE 11 (with Promises polyfill)
