### ISSUE TITLE
make use of "param" as alternative for "queryParam"

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2157]
This is a (multiple allowed):
* [x] enhancement

* Framework7 Version: 2

With F7-**query**-object, I can transport data from one page to another. The **query**-object is available within **f7-routeTo.query**. 

However, often it is better to transport data from one page to another by making use of the "data-params"-tag. For example: 

```
<div class="list links-list">
      <ul>
        <li>
          <!-- saves query-params in "routeTo.query" -->
          <a href="/detail/?x=100">Link Item 1</a>
        </li>
        <li>
          <!-- should save params in "routeTo.params" -->
          <a href="/detail/" data-params="{x: 100}">Link Item 2</a>
        </li>

      </ul>
    </div>
```

If F7 detects a **"data-params"**- within the `<a>`-tag of a list item _(where the href leads to another route)_, then F7 should **store the values of "data-params"-tag **automatically** within the available F7-routeTo.params object.** 

**Benefits:**

- With this, there is no need to convert back and forth between url and json representation (for example, with the help of parseUrlQuery/serializeObject or encodeURI) - because "data-params" can store json directly and transport json directly to the next route.
- url/href stays clean and hides information about detailed query from the user (href is always visible in adress-bar and there are cases where detailed query-params should be hidden from the user)
- can store any lenght of json object and transport it to another view by storing it to **f7-routeTo.params** without decoding/encoding url.
- no more need to store data in view or anything else and garbage or update these values on each action (e.g. href-tag of list item is clicked), because "data-params" is like "?x" and transports automatically with refreshed and scoped values..

**Comment by nolimits4web** [comment]
There is already `data-context` attribute supported where you may specify custom JSON that will extended router's component context or template7 page context. 

In proposed example with data-param, it is still must be a valid JSON to be able to parse it. Params are basically URL params and can be used in URLs instead of query:
```
{
  path: '/detail/:x',
  url: '...',
},
```
And then just `/detail/100/` and it will pass `{x: 100}` param to next route

**Comment by nimo23** [comment]
I tried this:

This is from the master-site: 

<div class="list links-list">
      <ul>
   
        <li>
          
          <a href="/detail/" data-context="{x: 100}">Link Item 2</a>
        </li>

      </ul>
    </div>

The `"/detail/"` is a component. 

However, looking at the detail-component, there is no `context`-object binded after navigating to detail.

**Comment by nolimits4web** [comment]
Ok, if detail is a component, then context will extend components' context. It should be available in component as `this.x`

Also, data-context must contain valid JSON: 
```html
<a href="/detail/" data-context='{"x": 100}'>Link Item 2</a>

**Comment by nimo23** [comment]
It does not work good:

![screenshot at jan 29 17-51-07](https://user-images.githubusercontent.com/3045549/35522613-1934775c-051d-11e8-862f-5c1564b3164e.png)


data-context pollutes the global scope:

![screenshot at jan 29 17-49-34](https://user-images.githubusercontent.com/3045549/35522636-2bb5a0ae-051d-11e8-95b2-be424840e44a.png)

And even if this.x would work, it would be better, if "data-context" is only bound to the routeTo.context-object instead of the global app. It should work like the query-object /detail/100/ or /detail/?100.

**Comment by nolimits4web** [comment]
Pushed fix for this

**Comment by nolimits4web** [comment]
> it would be better, if "data-context" is only bound to the routeTo.context-object instead of the global app

Why? Context is context. If you want to have it in some var then you are free to go with `data-context='{"context": {"x": 100}}'`

**Comment by nimo23** [comment]
yes, I can do something like 

data-context='{"detail-tab": {"x": 100}}'

**Comment by nimo23** [comment]
thanks.
