### ISSUE TITLE
Routable Tabs on "/" index.html

### ISSUE THREAD

**Issue by FabioWidmer** [framework7io/framework7#2158]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.7

### What you did
I created routable tabs on the index "/" page. It loads all the tabs and switching to the second tab works perfectly. But going back to the first tab does not work.

```
{
  path: '/',
  url: './index.html',
  tabs: [
    {
      path: '/',
      id: 'home',
      component: home
    },
    {
      path: '/second/',
      id: 'second',
      component: second
    }
  ]
}
```

### Expected Behavior
Clicking on the first tab (while on the second tab) should go to the first tab page and load the content of it.

### Actual Behavior
Nothing happens when clicking (while on the second tab) on the first tab.
Edit: Clicking on a tab only works the first time. Changing the tab a second time does not work.

**Comment by FabioWidmer** [comment]
Update: It works when removing the dot from the URL.

From:
```
    <div class="toolbar-inner">
      <a href="./" class="tab-link" data-route-tab-id="about">About</a>
      <a href="./contacts/" class="tab-link" data-route-tab-id="contacts">>Contacts</a>
      <a href="./cv/" class="tab-link" data-route-tab-id="cv">>CV</a>
    </div>
```
To:
```
    <div class="toolbar-inner">
      <a href="/" class="tab-link" data-route-tab-id="about">About</a>
      <a href="/contacts/" class="tab-link" data-route-tab-id="contacts">>Contacts</a>
      <a href="/cv/" class="tab-link" data-route-tab-id="cv">>CV</a>
    </div>
```

The example looks wrong to me: http://framework7.io/docs/routes.html#routable-tabs

**Comment by joshua1996** [comment]
but for me, it must add the dot so it can work!
