### ISSUE TITLE
Ver1.6.5, Page.query is mess.

### ISSUE THREAD

**Issue by huaxia0624** [framework7io/framework7#2159]
* [x] bug
* [x] enhancement

* Framework7 Version: 1.6.5

### What you did
Using item of list-block to navigate a page, such as:
`<li>`
`    <a href="#homeUserAddressForm" class="item-link item-content">...</a>`
`</li>`
`<li>`
`    <a href="#homeUserAddressForm?id=2" class="item-link item-content">...</a>`
`</li>`
Probably, There is an bug in this callback method: `onPageReinit(pageId, function(page){...});`
the parameter page.query is mess.

1: Click the first link, there is no parameter, page.query is an empty object. (Correct)
2: Click the second link, there is a parameter, page.query is {id:2}. (Correct)
3: Click the first link again, then page.query is still {id:2}. (**Incorrect**)

Please referring to the screen print as blew:
![1517165901871](https://user-images.githubusercontent.com/5773595/35485881-810fa4aa-04a0-11e8-95d4-788913d08f1d.jpg)

### Expected Behavior
Step 3: When click an empty params URL, page.query should be an empty object.

### Actual Behavior
Step 3: It seems been cache the last URL parameters.
BUT, Using this code as blew will OK:
`<li>`
`    <a href="#homeUserAddressForm?id=" class="item-link item-content">...</a>`
`</li>`
`<li>`
`    <a href="#homeUserAddressForm?id=2" class="item-link item-content">...</a>`
`</li>`

The different of these tow part codes is the first link, I use '?id=' meaning no value.
It work.

**Comment by nolimits4web** [comment]
Ok, glad you have found a workaround. v1 currently is not maintained anymore, so closing this for now
