### ISSUE TITLE
convertToData with checkbox should return "true" or "false"

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2165]
* Framework7 Version: 2

The f7-checkbox http://framework7.io/docs/checkbox.html  returns a **array with on and off** instead of a simple **true** or **false** within http://framework7.io/docs/form.html convertToData-method. The f7-toggle also returns on and off, however, a checkbox should be either "true" or "false".

I can do this: 

`form.checkbox[0] == "on" ? true : false, `

But why? A checkbox should directly return true or false.

**Comment by nolimits4web** [comment]
Checkbox supposed to be an array, as you may have few checkboxes with same name - it is array structure
