### ISSUE TITLE
Stepper for input type number

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2167]
This is a (multiple allowed):
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2

F7 has **range-slider** (http://framework7.io/docs/range-slider.html) for numbers, which is good, but uses much space in compare to typical input forms of type number (also the actual input value is hidden by default and displayed outside of the range slider). 

In desktop browsers, input-type number is rendered with **a knob on the right side**, so user can **press and hold button up or down to change value** without typing in keyboard or moving fingers to left and right (with range-slider).

Please provide this also for f7 (**f7-input-number**), where knobs are touch sensitive like this:

![knob-input-range](https://user-images.githubusercontent.com/3045549/35646669-2cc537b6-06d0-11e8-827f-908cde7959d5.png)

**Comment by nolimits4web** [comment]
This is called Stepper https://www.google.ru/search?q=ios+stepper&newwindow=1&tbm=isch&source=iu&ictx=1&fir=Nuq2XdMhcFsizM%253A%252CedaNxuU7y-rbwM%252C_&usg=__zWPOmqGxYyWGpQkOfoIo1nimpak%3D&sa=X&ved=0ahUKEwi16vu5453ZAhVBPywKHUTwDVUQ9QEIODAE&gws_rd=cr&dcr=0&ei=giuAWtHwF4emsAG4xY2oCQ#imgrc=Nuq2XdMhcFsizM:
