### ISSUE TITLE
[v2] dialog component - close by backdrop click

### ISSUE THREAD

**Issue by JDok** [framework7io/framework7#2169]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.7
* Platform and Target: Windows 10 Chrome (latest), Android 7.1.2 Chrome (latest)

### What you did

`
 app.dialog.create({
  title: "Test Dialog",
  text: "This is a dialog",
   closeByBackdropClick: true,
   buttons: [
      { text: 'close',  }
    ]
}).open();
`

### Expected Behavior
Dialog close on backdrop click

### Actual Behavior
 Dialog doesnt close on backdrop click (no matter closeByBackdropClick is explicit set to true (default: true) or not)

**Comment by rakeshbaral92** [comment]
Same issue here. Any solution on it.
