### ISSUE TITLE
The DataType option is not used when you install through app.request.setup()

### ISSUE THREAD

**Issue by DimNS** [framework7io/framework7#2170]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.7
* Platform and Target: Google Chrome on Windows10

### What you did
```
app.request.setup({
    dataType: 'json'
});

app.request.get(url, {}, function (result) {
    console.log(result);
});
```

### Expected Behavior
```
console.log(result); // this is object (json parsed)
```

### Actual Behavior
```
console.log(result); // this is text
```

That's how it works
```
app.request.setup({
    beforeSend: function (xhr) {
        xhr.requestParameters.dataType = 'json';
    }
});
```

**Comment by nolimits4web** [comment]
You need to use `app.request.json` for json requests

**Comment by DimNS** [comment]
Yes, but in that case, it's going to be a get-request, right?

And if I need a POST request that returns data as JSON

The situation is: I want to reduce the amount of code and do not create my own façade, for this purpose all necessary parameters define directly in app.request.setup

**Comment by nolimits4web** [comment]
request.get is a shortcut method, it overwrites global dataType, but you can pass required dataType as last parameter in this call. Same for post methods

**Comment by DimNS** [comment]
AAAA overwrites, didn't know, here's the thing.

Well then understandable, thanks for the hint
