### ISSUE TITLE
Picker initialization method?!

### ISSUE THREAD

**Issue by sraychev** [framework7io/framework7#2174]
Hi I am unable to initialize the picker programmatically. My picker is actually a counter down. You visit timer page, set picker to 5 minutes. Navigate to another page. Navigate again to timer page. At this point counter is running every second and wont update the picker value unless I click on the picker itself and close it.

Note, I've tried going around the issue by calling pickerTimer.open(); pickerTimer.close(); This will do the trick, but then the router will start acting up and change pages.

Using timeout works, but then you see the picker pop up for half a second.
                //pickerTimer.open();
                //setTimeout(function (){
                //    pickerTimer.close();
                //}, 500);

Any suggestions will be appreciated.

**Comment by sraychev** [comment]
I've moved to another solution, but I just wanted to share that there is not way to set picker until you open/close it. Picker is created and I can console.log(picker), however the picker.cols is empty and it trows an error trying to call picker.cols[2].setValue(minutes);

**Comment by nolimits4web** [comment]
Didn't get what are you trying to achieve? Cols are not available until it is rendered. To set the picker value there is a `picker.setValue` method

**Comment by sraychev** [comment]
Ok, let me see if I can make it easy. I have picker on a page. Once the user opens the page, I want to set the picker value, i.e. I want to call picker.setValue() but that is not available. 
picker.setValue function can only be called after a user clicks on the picker

**Comment by nolimits4web** [comment]
> picker.setValue function can only be called after a user clicks on the picker

No, you can even just specify the value in picker `value` parameter on picker init
http://framework7.io/docs/picker.html#picker-parameters

**Comment by sraychev** [comment]
Thanks Vlad, I will try this next time. As I said, I removed the picker and use jQuery atm.
