### ISSUE TITLE
Facebook App SDK implementation?

### ISSUE THREAD

**Issue by dmk23** [framework7io/framework7#2175]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: N/A
* Platform and Target: ALL
* Live Link or JSFiddle: N/A

### What you did
I am evaluating frameworks/tools for rapid development of custom apps that will be promoted on Facebook, via Facebook advertising (App Ads). Framework7 sounds intriguing, but I need to figure out if it can meet my specific requirements for implementing marketing event tracking. I am completely new to mobile app development but have extensive experience in web/javascript/backend

### Expected Behavior
What I need is to implement Facebook SDK for App Ads. Specifically:

- Connect a Mobile App to a Facebook App
- Implement Facebook Login via that App
- Integrate user identity/actions with my application backend
- Fire tracking events on specific actions users take in my app
- Make it work on both iOS and Android; Get it into app stores

Facebook appears to suggest separate SDKs for iOS, Android, and JavaScript in their docs for App Ads. You can find some basic info here:
https://developers.facebook.com/docs/app-ads/sdk-setup
https://developers.facebook.com/docs/app-events

### Actual Behavior
I searched this repo and haven't seen any code or issues discussing Facebook SDKs of any kind. I am hoping you could provide some direction / roadmap on how I could achieve what I described here. If this is not possible today - perhaps you could suggest if/how I could modify Framework7 to make it happen

**Comment by nolimits4web** [comment]
> I searched this repo and haven't seen any code or issues discussing Facebook SDKs of any kind.

Because it doesn't related to Facebook SDKs. Just use facebook JS sdk if this is a web app or this cordova plugin for cordova app https://github.com/jeduan/cordova-plugin-facebook4
