### ISSUE TITLE
Subsequent `router.navigate(...)` ignored while previous `router.navigate(...)` not yet complete?

### ISSUE THREAD

**Issue by JasonKleban** [framework7io/framework7#2178]
I have a "/loading/" page route that gets navigated to while a network request is pending.  If the network request succeeds, UI should navigate to a "completed" route.

If the network request responds too quickly, the router.navigate('/completed/') is ignored with no error.  If I add in a `currentRouter.once('routeChanged', () => { ... }); ` then the UI works as expected.  But this seems undesirably complicated.

Instead of this:

```ts
currentRouter.navigate('/loading/');

io().then(() => {
    currentRouter.navigate('/completed/');
});
```

I have to use this:

```ts
currentRouter.once('routeChanged', () => { 
    io().then(() => {
        currentRouter.navigate('/completed/');
    });
}); 

currentRouter.navigate('/loading/');
```

I think there's a bug that while the router is in transition, it cannot accept new navigate() instructions.  Is that possible?

Thanks,

**Comment by nolimits4web** [comment]
Yes, it is by design. Routing is not allowed while in progress as it can produce unexpected results. And for such usecase it is better to use modals rather then a whole page for a moment
