### ISSUE TITLE
componentUrl doesn't work with routable tabs

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2182]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version:  V2.07
* Platform and Target:  All

```
  {
  	name: 'mo',
        path: '/mo/',
	url: './pages/mo.html',
	tabs: [
		{
		path: '/',
		id: 'mo-1',
	        componentUrl: './pages/mo1.html',
		},
		{
		path: '/mo_2/',
		id: 'mo-2',
	        componentUrl: './pages/mo2.html',
		},
		{
		path: '/mo_3/',
		id: 'mo-3',
	        componentUrl: './pages/mo3.html',
		},
    ],
  },

Markup

	<div class="page">
		<!-- Top Navbar-->
		<div class="navbar">
			<div class="navbar-inner">
				<div class="left">
					<a href="#" class="link back">
						<i class="icon icon-back"></i>
						<span class="ios-only">Back</span>
					</a>
				</div>
				<div class="title">Default title</div>
			</div>
		</div>

		<div class="toolbar tabbar">
			<div class="toolbar-inner">
				<a href="./" class="tab-link" data-route-tab-id="mo-1">Home</a>
				<a href="./mo_2/" class="tab-link" data-route-tab-id="mo-2">Games</a>
				<a href="./mo_3/" class="tab-link" data-route-tab-id="mo-3">Messages</a>
			</div>
		</div>

		<div class="tabs tabs-routable">
			<div class="tab page-content" id="mo-1">	</div>
			<div class="tab page-content" id="mo-2"></div>
			<div class="tab page-content" id="mo-3"></div>
		</div>

	</div>     
```

All component page templates load but the script code is never executed. Component files are variants of this markup:

```
<template> 
	<div class="page">

		<div class="page-content">
			<h3 class="block team-name">Team Title</h3>
			<div class="block">
				<div class="card page-info">
					<div class="card-content card-content-padding">
                                                  Some card content
					</div>
				</div>
			</div>
		</div>
	</div>     
 </template>

<style>
</style>

<script>
	return {
		on: {
			pageInit: function (e, page) {
				// init signin page here
				console.log('Init '+page.route.name);

				var myPage = page.$el;
				
				myPage.find('.team-name').html('New Title');
			},
		},
	}
```

**Comment by eradin** [comment]
I created a codepen project to test this out.  It doesn't work there as well.  It doesn't appear codepen projects can be shared and I need multiple pages which rules out jsfiddle.  If you want the project export zip I can upload.  I also tried with 2.0.5 and 2.0.6 and they both don't work either.  Everything works fine but the component script part won't execute.

**Comment by eradin** [comment]
Ok, I figured out to get this into a jsfiddle.  It doesn't matter if the component is via a url or inline.  It appears to be broken either way.  I hope it gets fixed soon because I really need this to work.  Thank you.

https://jsfiddle.net/o2ejupu1/6/

If the code executes, the title should not be the default on the Component tab and a log entry should appear in the console.log.

**Comment by nolimits4web** [comment]
This is completely wrong. Tab's component must return the single tab inner element. Now you will have page inside of page, it is prohibited. For same reason `pageInit` event won't work for the tab. Use `mounted` component hook for that

**Comment by eradin** [comment]
Thanks, That makes sense.  This is not indicated in the documentation (although it's implied in the examples).  Please add to the documentation so others don't burn hours on this.
