### ISSUE TITLE
Scrollable Toolbar (not only Tabbar) and List Item

### ISSUE THREAD

**Issue by webleaf** [framework7io/framework7#2186]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 2
* Platform and Target: Android, iOS

Would be great to have scrollable Toolbar (not only Tabbar) and also horizontal scrollable list item

**Comment by nolimits4web** [comment]
What is wrong with adding `overflow: auto` to the elements you need to be scrollable? ;)
