### ISSUE TITLE
[V2] Row columns not equal heights

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2189]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2.07
* Platform and Target: ALl

This is possibly an enhancement request but It seems like a bug to me.  If you create a row with columns, if one column has wrapping text, it doesn't remain even in height with the rest of the columns in that row.  This is also evident in the documentation examples.

I believe that if you have a row with columns, be it with flex or tables, the columns should always remain the same height.  This is possible with css flex and should be the default.

**Comment by nimo23** [comment]
would be easier with "css grid layout"..

**Comment by eradin** [comment]
Agreed.  After looking at the css it should work now but it doesn't.

**Comment by nolimits4web** [comment]
It is CSS basics. Just add `align-items: stretch;` CSS rule to the row or use `align-items-strech` class on required row
