### ISSUE TITLE
Security Error

### ISSUE THREAD

**Issue by k-yle** [framework7io/framework7#2191]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2.0.6
* Platform and Target: web and cordova-android
* Live Link or JSFiddle: 
### What you did
The following error occurs because of the line `2724` in framework7.js:
```js
2719.            move: app.support.touch ? 'touchmove' : 'mousemove',
2720.            end: app.support.touch ? 'touchend' : 'mouseup'
2721.        };
2722.    
2723.        // Link to local storage
2724.        app.ls = window.localStorage;
2725.    
2726.        // RTL
2727.        app.rtl = $('body').css('direction') === 'rtl';
2728.        if (app.rtl) $('html').attr('dir', 'rtl');
2729.    
```

On Mobile Safari 9.0 the error is: 
```
DOM Exception 18: An attempt was made to break through the security policy of the user agent.
```

On Mobile Safari 11.0 the error is: 
```
The operation is insecure.
```
### Expected Behavior
Obviously, not a security error

### Actual Behavior
Strange looking error

**Comment by k-yle** [comment]
Just saw #1518 which I think is the same (or similar) issue. 

Sorry if this is a duplicate

**Comment by dawiinci** [comment]
Issue is still present in 2.0.7. The error makes it unusable on iOs an macOS. 

The error appears on a vanilla installation of Framework7.

Is there any way to fix this?

**Comment by nolimits4web** [comment]
Looks like you have something wrong in app security settings or in CSP meta tag

**Comment by k-yle** [comment]
Hi, I am not using CSP and I don't have the meta tag on my page. This is my `new Framework7(...)` config:

```js
var app = new Framework7({
    root: '#app',
    id: 'nz.school.tgs.app',
    name: 'My App',
    theme: 'auto',
    routes: [ 
        // ......
   ],
    view: { pushState: true },
    actions: { convertToPopover: false },
    routerAjaxStart: () => app.preloader.show(),
    routerAjaxComplete: () => app.preloader.hide(),
    routerAjaxError: () => app.preloader.hide(),
});

var mainView = app.views.create('.view-main', { url: '/' });

```

**Comment by nolimits4web** [comment]
Still can't see such issue. Can you please setup a JSFiddle or give a link with live example of where i can see this issue?

**Comment by DAnn2012** [comment]
On Safari for Mac, as a temporary solution, you can select  "**Disable Cross-Origin restrictions**" from the "**Develop**" menu

**Comment by dawiinci** [comment]
To reproduce this simply download the latest release and open kitchen-sink demo  files. 

It won‘t work on Safari at all.

**Comment by nolimits4web** [comment]
Issue because of reference to localStorage which happens only when loading app from local `file://` protocol. I have removed it there is no much sense to use it from `file` protocol, anyway for web app server is required, in Cordova there is no such issue
