### ISSUE TITLE
No scrolling on popups

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2192]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2.07
* Platform and Target: All

I am using a popup to display help information about a page.  The text extends beyond the view but the popup doesn't allow the user to scroll to the hidden text.  Perhaps there is a way to do this but I couldn't find anything in the documentation.

**Comment by nolimits4web** [comment]
Use correct View > Page > Page Content structure inside to make it scrollable

**Comment by eradin** [comment]
Thanks, that worked.  Just to be more explicit for anyone seeing this, here is the structure that worked for me.
```
<a href="#" data-popup=".pop-info-action" class="popup-open">Popup</a>

<div class="popup pop-info-action">
	<div class="view popup-view">
		<div class="page">
			<div class="navbar">
				<div class="navbar-inner">
					<div class="left margin-left"><i class="f7-icons ios-only link-color">help</i><i class="material-icons md-only">help_outline</i></div>
					<div class="title">Title</div>
					<div class="right"><a class="link popup-close" href="#">Close</a></div>
				</div>
			</div>
			<div class="page-content block">
                           popup content
			</div>
		</div>
	</div>
</div>
```
