### ISSUE TITLE
Need f7-range event that fires on user input ONLY

### ISSUE THREAD

**Issue by owen-mills** [framework7io/framework7#2194]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.7
* Platform and Target: Cordova Android

I created a f7-range element as a scrubber for my music player. I want to set @range:change to fire whenever the *user* changes the range position in this range slider. However, the event I set for @range:change is fired every millisecond when I update the range position in code (because it needs to go up while the music is playing every millisecond). Is there an event or workaround I could use to get an event that fires only when the *user* changes the position in an f7-frange element?

**Comment by nolimits4web** [comment]
In 2.0.8 you can listen for `change` event on input element inside of range slider, it triggers only when user releases the slider after value has changed. Otherwise you can use some debounce logics with setTimeout

**Comment by owen-mills** [comment]
That event doesn't seem to be fired when I move the slider
