### ISSUE TITLE
[IOS] Not able to scroll the page when accordion is opened

### ISSUE THREAD

**Issue by ahilanbeyond** [framework7io/framework7#2196]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.6
* Platform and Target: PLATFORM CLIENT YOU ARE TARGETING SUCH AS IOS, ANDROID.

### What you did
We used framework7 accordion component in our application with IOS theme.

### Expected Behavior
We should be able to scroll the page to view the accordion content, if the content is larger than the page height. 

### Actual Behavior
We're not able to scroll the page when the accordion is opened and the accordion content stretches larger than the page height.[This happens only in IOS-Safari]

**Comment by nolimits4web** [comment]
JSFiddle or live example with the issue would be great

**Comment by ahilanbeyond** [comment]
Sure. I'll post it in some time

**Comment by ahilanbeyond** [comment]
@nolimits4web You can check the accordion section found in Kitchen Sink app - https://framework7.io/kitchen-sink/?theme=ios. Try this in IOS safari browser.

**Comment by nolimits4web** [comment]
Here is what i see
https://drive.google.com/file/d/1qiQpmZtUE8HPt5MW02Ti3ddxwZqA9k-S/view?usp=sharing

Have the same on real ios device

**Comment by ahilanbeyond** [comment]
We will upload our screen recording and share the link shortly

**Comment by ahilanbeyond** [comment]
@nolimits4web Please check this out - https://drive.google.com/file/d/12Q5d3t4l8VbxrO8Z2qGJfSvtGG_kaYo4/view?usp=sharing

**Comment by parthibeyond** [comment]
@nolimits4web Have you checked this out? Can we expect a patch for this behaviour?

**Comment by robinyip** [comment]
I got same problem too, looks like if the page height is less then the view height when accordion is closed, you won't able to scroll after accordion is opened.

Looks like the problem is with the view, my temporary solution in V2, you can add a line view.emit( 'resize'); to accordion:opened event

**Comment by ahilanbeyond** [comment]
@robinyip  We tried the solution which you suggested. But still the problem persists. Can you share some fiddle example?

**Comment by ahilanbeyond** [comment]
@nolimits4web The problem still persists. Is there any solution which you can suggest?

**Comment by nolimits4web** [comment]
Already pushed the fix

**Comment by ahilanbeyond** [comment]
@nolimits4web We have tried the recent f7 release in our app, but the problem persists.

**Comment by Maheshwbc** [comment]
I am also facing this issue in iOS can you guys give any work around?

Thank in advance

**Comment by Maheshwbc** [comment]
I got the work around for this scroll this

/* style for enable accordion scroll for iOS only*/
.accordion-item-content {
    -webkit-transform: none;
    transform: none;
}

**Comment by ahilanbeyond** [comment]
@Maheshwbc , we tried using snippet which you shared but still we weren't able to make it work. Can you provide some insight on this?

**Comment by goodfellasthai** [comment]
Hi, I wonder if you can help, I am still seeing this, I have pulled the latest version of f7 js and css from github.  I am using the latest version of iOS 11.3.1 on an iPhone 6.  This is exactly the same behaviour explained I am seeing in this case and the bug.  I have checked framework7.js and it has the code fix above mentioned but still the issue persists.

I have uploaded a screenshot attempting to scroll the accordion, unfortunately I cant really provide much else as this works fine when I view through the browser or on Android.

[https://drive.google.com/file/d/1kMVEzWDgrq9xWUXBOKna1j-w9bDsertu/view?usp=sharing](url)

Any help would be much appreciated

**Comment by parthibeyond** [comment]
@goodfellasthai We had a problem with a specific type of accordion(I guess its custom accordion). We just override the js related to the accordion. It solved the problem for us.
