### ISSUE TITLE
Request Support for Angular2+

### ISSUE THREAD

**Issue by Jake21x** [framework7io/framework7#2201]
Did F7 Planning to Support  Angular2+ ? Angular2 today has a big community and many expert dev  can watch and help to progress this project . also to add angular2+ is much faster as of today than angular1  

I think this is possible like this repo here
https://github.com/ashvin777/framework7.angular2
its working but f7 official site has no documentation how to implement this properly 

This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

**Comment by nolimits4web** [comment]
Sorry, but no, no Angular support in plans
