### ISSUE TITLE
$root is empty for Router Component

### ISSUE THREAD

**Issue by maciej-izak** [framework7io/framework7#2204]
Hi, I have hope that my first report is in right category :).

I found following problem related to "Router Component". In documentation is described $root property which seems not working. All data and methods are directly in "this" meanwhile $root is empty.

For example following code:
```
<template>
...
</template>
<script>
    return {
        data: function () {
            return {
                fooData: {}
            }
        },
        methods: {
            fooMethod: function () {
             }
        },
        mounted: function () {
            console.log(this);
            console.log(this.$root);
        }
    }
</script>
```
will print for "this":

> Framework7Component
>   $:$$1$1(selector, context)
>   $$:$$1$1(selector, context)
>   $app:Framework7
>   $destroy:destroy()
>   $dom7:$$1$1(selector, context)
>   $el:Dom7
>   $mount:mount(mountMethod)
>   $options:Object
>   $root:Object
>   $route:Object
>   $router:Router
>   $theme:Object
>   fooData:Object {}
>   fooMethod: ()
>   __proto__:Object

and for $root:

> Object
>  __proto__: Object

**Comment by nolimits4web** [comment]
$root contains data and methods defined in “data” and “methods” parameter in app init

**Comment by nolimits4web** [comment]
Possible https://github.com/framework7io/framework7/blob/master/kitchen-sink/pages/page-loader-component.html#L54-L59

**Comment by maciej-izak** [comment]
@nolimits4web Seems that this works only in template section. Access to $root outside is impossible (from <template> or from app/view instance or in any other way). Is that by design? In this case may be worth to extend access to $root for Router Components.

**Comment by nolimits4web** [comment]
* Go to http://framework7.io/kitchen-sink/
* Open browser console
* Navigate to "Component Page"
* Open in console and check
* See that `$root` is accessible

<img width="674" alt="ss" src="https://user-images.githubusercontent.com/999588/36204652-29887072-119d-11e8-88fe-7c6d75387271.png">

**Comment by maciej-izak** [comment]
@nolimits4web  You were right. Sorry for false alarm, I was sure that I found the bug but it was problem on my side (during some operations I have replaced $root). Thanks for fast and professional help!
