### ISSUE TITLE
SmartSelect doesn't work for Router Component

### ISSUE THREAD

**Issue by maciej-izak** [framework7io/framework7#2205]
Hi,

I found that I can't create SmartSelect for router components. I had try in both ways:

- by smart-select-init
- more dynamically inside "mounted" event by app.smartSelect.create

the second way is also affected even with specified view:

```
            var smartSelect = app.smartSelect.create(
                { 
                    el: $$('#super-hero'), view: mainView
                });
```
always the error *Smart Select requires initialized View* is raised.

**Comment by nolimits4web** [comment]
Means that "Smart Select requires initialized View" did you init the view where Smart Select is placed?

**Comment by maciej-izak** [comment]
@nolimits4web Probably it was my fault. Yes the view is initialized: `var mainView = app.views.create('.view-main', {url: '/'});`. Pleas note that field **view** passed in params in app.smartSelect.create is not used in implementation of constructor so  SmartSelect is always looking for $el.parents('.view') and finally crash (even when view is specified).  Anyway I found why smart-select-init does not want to work for me : It was my fault, SmartSelect constructior is looking only for $el.parents('.view') but can't find any because in my HTML I have declared only view-main without view (I have no idea how I overlooked this): 

```
    <div class="view-main"></div>
```

anyway ` app.smartSelect.create ` is always looking for "view" even when view is specified.

**Comment by nolimits4web** [comment]
But it doesn't accept `view` parameter http://framework7.io/docs/smart-select.html#smart-select-parameters

Think I will add it, but it is kind of useless to have smart select in one view and get it opened in another

**Comment by burtontanner** [comment]
@nolimits4web I think am running into a related issue. My page component does have a view but the smart select cannot find the router. If that page is navigated to using a link then the smart select works, but if my page is a child of the view it does not work.
    "framework7-react": "^3.0.1",
    "framework7": "^3.0.1",
```javascript 
<Popup opened={this.state.opened} className="rs-add-to-cart-popup" id="rs-add-to-cart-popup" animated>
        <Views>
          <View stackPages >
            <AddToCartPage noBackLink {...this.props}/>
          </View>
        </Views>
      </Popup>
```

AddToCartPage
```javascript 

  render() {
    let product = this.state.product || {};
    return (
      <Page pageContent={false} hideBarsOnScroll className="rs-add-to-cart-page" id="rs-add-to-cart-page">
      <ListItem
        title={this.props.title}
        smartSelect
        ref={ref => this.dropdown = ref}
        smartSelectParams={{closeOnSelect: true, openIn: 'popover'}}>
        <select name={this.props.title} multiple={false} defaultValue={this.state.value}>
          {this._displayOptions()}
        </select>
      </ListItem>
      </Page>
    )
```
