### ISSUE TITLE
How to use iframe in Framework7?

### ISSUE THREAD

**Issue by ashafizullah** [framework7io/framework7#2210]
Hi, i want to ask about how to use <iframe> tag in Framework7. I have <iframe> code like 
`<iframe src="https://www.facebook.com/" style="width:100%; height:100%;">`

But, the external page is not loaded, and i already add this line to the config.xml
```
<allow-navigation href="*" />
<allow-intent href="*" />
<access origin="*" />
```
also,

`<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">`

in the index.html file. But the page is still not loaded.

Thanks before.

**Comment by ZanderBrown** [comment]
Facebook blocks being loaded in an iframe with `X-Frame-Options`, tl;dr it can't be done and this isn't F7 related
