### ISSUE TITLE
[V2] Add name property to async

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2211]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I am using an analytics plugin to send data to google analytics.  One of the parameters is page view.  Current I send page.route.name for the page view.  This works great except when I use async for some routes.  Because async will select from various pages to load, the name I use in the route doesn't reflect the page that is loading.  I can't find a way to override the name property but if we could include it in the resolve call, that would be helpful. Another option is to use the actual page name but I can't find a way to do that either without adding an attribute to the page tag.

**Comment by nolimits4web** [comment]
No, route is route. If async means something different then probably another route must be used. And page.name fits better for this, what is wrong with adding required `data-name` attribute to the page that can be dynamic as well?
