### ISSUE TITLE
Redirect user to another page inside onPageBeforeAnimation

### ISSUE THREAD

**Issue by mishkeTz** [framework7io/framework7#2213]
Framework7: 1.6.5

Is it possible to redirect user to another page inside onPageBeforeAnimation event.

For example I have some checking on page1 where I made an ajax call and if there is an error I want user to redirect to page2 and all of that happens in onPageBeforeAnimation("page1", function() { });

I tried with:
mainView.router.loadPage('page2.html');

also with ignoreCache and froce set to true, but I couldn't make it work.

**Comment by nolimits4web** [comment]
It is not possible to load page in onPageBeforeAnimation event. Do it in onPageAfterAnimation or better do the request before loading a page
