### ISSUE TITLE
Navigation after click

### ISSUE THREAD

**Issue by Bary92** [framework7io/framework7#2221]
Hello, I am a beginner for this technology. 
Let me explain, there is a login page, after the validation of the data, I would like the page to be redirected to another page. I watched the doc but I am a lost. Can you help me? 
**Code**
`var $$ = Dom7;
var app = new Framework7({
	theme: 'md',
	root: '#app',

	routes :[
		{
			name:'home',
			path:'/home',
			url:'..pages/home.html',
			options:{
				animate: false
			}
		}

	]
});
$$('#login_button').on('click',function(){
	//validation data
  app.router.navigate('/home');
})
`

Thank you

**Comment by nolimits4web** [comment]
There is no `app.router`, router is a View's property and must be used on View, e.g. `app.views.main.router.navigate(...)`
