### ISSUE TITLE
timeout dont work

### ISSUE THREAD

**Issue by alextapia007** [framework7io/framework7#2223]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.
* Platform and Target: CORDOVA, ANDROID.
       
      app.request.post( 
       'url',
       {dato: 'dato' },
       function (data) {console.log(data)},
       function (error) {console.log(error)},
        'json',
        7000)

### Expected Behavior
after timeout send error

### Actual Behavior
dont send error

**Comment by nolimits4web** [comment]
Last parameter is not a timeout http://framework7.io/docs/request.html#post
