### ISSUE TITLE
Unable to send JWT token with headers.

### ISSUE THREAD

**Issue by dyanakiev** [framework7io/framework7#2225]
Hello,

Im trying to send Header with `JWT` token i simply added the following code in my app.

```
 app.request.setup({
        headers: {
            'Authorization': appStorage.getItem('jwt')
        }
    });
```

And this is the error i got after:
```
Failed to load resource: Request header field Authorization is not allowed by Access-Control-Allow-Headers.

XMLHttpRequest cannot load https://some.url/some/path. Request header field Authorization is not allowed by Access-Control-Allow-Headers.
```

I tried adding `Access-Control-Allow-Headers` but without any success.

Any help is appreciated.

**Comment by nolimits4web** [comment]
The issue what it says, header is not allowed by your server

**Comment by dyanakiev** [comment]
This is weird because i have iOS app on swift that works fine.

**Comment by nolimits4web** [comment]
Just check the request details (header and body) in Dev tools to see the details

**Comment by nolimits4web** [comment]
Did you find out what is the problem?

**Comment by safrazik** [comment]
Make sure your server sends a response header `Access-Control-Allow-Headers` with value `Authorization`. This error may occur even if a server exception is thrown (before those headers are sent) I don't think it's a Framework7 related issue
