### ISSUE TITLE
Load VI over HTTPS

### ISSUE THREAD

**Issue by FabioWidmer** [framework7io/framework7#2226]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Platform and Target: Website

### What you did
I tried to implement VI into my app.

### Expected Behavior
Framework7 loads the VI SDK.

### Actual Behavior
The request to the VI SDK gets blocked because it is an unsecure HTTP request while the app itself gets served over HTTPS. (Chrome)
![image](https://user-images.githubusercontent.com/6362414/36627980-41997b6a-194b-11e8-9cf0-713e81c5ba42.png)

**Comment by nolimits4web** [comment]
Made a fix in F7 to request it over https, and contacted vi to do the same with additional resources that this script requests to be available over https

**Comment by nolimits4web** [comment]
This was fixed
