### ISSUE TITLE
Need autocomplete on click event

### ISSUE THREAD

**Issue by owen-mills** [framework7io/framework7#2227]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Platform and Target: Cordova Android

There should really be an event on the autocomplete component that is triggered when a user selects an item from the autocomplete list. It would be helpful in a situation where wanted to search the query when the user selects it from the dropdown list, among other cases.

**Comment by nolimits4web** [comment]
There is a autocomplete's `change` event happens when user clicks on dropdown, you can use it
