### ISSUE TITLE
[list-item][media-list] Caret shown at wrong position

### ISSUE THREAD

**Issue by tiptronic** [framework7io/framework7#2228]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Platform and Target: iOS

* Live Link or JSFiddle: https://framework7.io/kitchen-sink/ 
choose 'List View' and scroll all the way down where media-lists are shown

### Expected Behavior
Caret (at the right) should be positioned in the vertical center of the list-item
E.g. as background-image in `<div class="item-inner">`

### Actual Behavior
Caret is placed as background-image in  `<div class="item-title-row">` 
This also results in the fact, that a media-list's item-text is a bit too wide

Here's a screenshot taken from [https://framework7.io/kitchen-sink/ ](url)
![screenshot 2018-02-26 13 02 52](https://user-images.githubusercontent.com/80752/36669500-67ba462a-1af5-11e8-8df0-0b80d4eba68e.png)

**Comment by nolimits4web** [comment]
This is by design, assuming media list needs more space for text. This is how native iOS mail looks

![d6720532-ebb3-44be-b053-b8fe7de4a704](https://user-images.githubusercontent.com/999588/36671219-ee4c70bc-1b0b-11e8-8477-099b7583f393.jpeg)

**Comment by tiptronic** [comment]
Imo Mail is not a good example, because it is not really a media-list, but a mashup.
If you go to settings and watch a true media-list, you'll see the caret is centered:
![medialist](https://user-images.githubusercontent.com/80752/36673844-75ce428e-1b04-11e8-9b12-9a78fac42741.jpg)

**Comment by nolimits4web** [comment]
Here also the item-after is centered as well. Anyway, this won’t be changed, because it can be a breaking change. It is easier to apply custom styles for single app to get the desired effect. 

I will add some additional class for list to have the chevron in centered

**Comment by tiptronic** [comment]
OK - great thanks!

**Comment by DAnn2012** [comment]
Great!

P.S. I had already reported it about a year ago... #1358
