### ISSUE TITLE
View init and Navbar behavior

### ISSUE THREAD

**Issue by huaxia0624** [framework7io/framework7#2233]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 2.0.10
* Platform and Target: IOS

### What you did
There are 3 Views in app, each of them has only one navbar, the pages which under their view have NO navbar:
```
<div class="views tabs">
    <div class="tabbar>...</div>
    <div class="view tab" id="tab-1">
        <div class="navbar">...</div>
        <div class="page">...</div>
    </div>
    <div class="view tab" id="tab-2">
        <div class="navbar">...</div>
        <div class="page">...</div>
    </div>
    <div class="view tab" id="tab-3">
        <div class="navbar">...</div>
        <div class="page">...</div>
    </div>
</div>
```
After init app without call `app.views.create('...')`, all of 3 navbar display as expected, but because of un-init views, (Of course) ajax link won't work. When I did the initialization of views by calling `app.views.create('...')`, all of 3 navbar have been add CSS class `navbar-hidden` (invisible!!)
JS might be here: `framework7.js Line 8376`
> router.$navbarEl.addClass('navbar-hidden');

Then I copy navbar into all page as their directly child before page-content, after view initialization, navbar work!! However, every page's navbar additional official CSS class won't copy to the right place. Such as `no-hairline no-shadow bg-color-white`, it seems like the JS create a DIV tag (with navbar CSS class) under the view, and copy navbar-inner into it.

### Expected Behavior
If using only one navbar in a view, then after view initialization, the navbar should visible.
If using the fixed navbar in a page, then when switch page, every navbar might carry all of its CSS classes.

**Comment by nolimits4web** [comment]
Disable Views iosDynamicNavbar setting
