### ISSUE TITLE
action sheet buttons background color not being applied

### ISSUE THREAD

**Issue by joseph-perez** [framework7io/framework7#2236]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Platform and Target: Android, IOS

### What you did
Set the bg property for a action sheet button to "red" but the background color of the button does not change.

### Expected Behavior
The color set in the bg property for a button in an action sheet should change the background color of the button.

### Actual Behavior
The color set in the bg property for a button in an action sheet isn't changing the background color of the button. It's adding a class of bg-red instead of bg-color-red.

**Comment by nolimits4web** [comment]
Fixed by #2237
