### ISSUE TITLE
PageInit not working correctly in Framework7 Component

### ISSUE THREAD

**Issue by FabioWidmer** [framework7io/framework7#2239]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10

### What you did
Created a component and loaded passed context via async request. Opened this page multiple times after.

Route (Only an example may not work and sorry for the bad indention):
```
{
    path: '/posts/edit/:id/',
    async(routeTo, routeFrom, resolve, reject) {
	resolve(
		{
                    component: {
                        template: `
                      <div class="page">
                        <div class="navbar">
                          <div class="navbar-inner sliding">
                            <div class="left">
                              <a href="#" class="link back">
                                <i class="icon icon-back"></i>
                                <span class="ios-only">Back</span>
                              </a>
                            </div>
                            <div class="title">{{post}}</div>
                          </div>
                        </div>
                        <div class="page-content">
                          <div class="block block-strong">About page</div>
                        </div>
                      </div>
                     `,
                            on: {
                                pageInit: function() {
                                    console.log(this);
                                }
                           }
                     }
		}, {
                    context: {
                        post: {
                            title: "Hello World"
                        }
                   }
              }
	);
    }
},
```

### Expected Behavior
The `console.log(this)` prints the whole `Framework7Component` with the post data in it.

### Actual Behavior
The first time the page opens everything is working correctly. The `Framework7Component` contains all methods and data. But the second time I am opening the page the `console.log()` prints an empty `Framework7Component`.

I am opening the page with: `this.$router.navigate('/posts/edit/'+event.target.dataset.id+'/');`
It is really strange but I hope you can help solving this issue.

**Comment by nolimits4web** [comment]
It is already was fixed in 39571d6
