### ISSUE TITLE
TypeError: parse is not a function

### ISSUE THREAD

**Issue by yelban** [framework7io/framework7#2252]
![_2018-03-06_ 5_10_36](https://user-images.githubusercontent.com/981381/37023782-f0050b88-2161-11e8-8779-6057f5a1e969.png)

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Platform and Target: macOS

### What you did
git clone https://github.com/framework7io/framework7.git
cd framework7
npm i
npm run build:dev

### Expected Behavior
build success

### Actual Behavior
got TypeError on both node v6.12.3 and v8.9.3

`TypeError: parse is not a function in ./framework7/src/framework7.js`

**Comment by nolimits4web** [comment]
There is no `parse` in framework7.js. Anyway, i see the build was secceed

**Comment by nolimits4web** [comment]
This looks similar http://forum.framework7.io/t/vue-js-kitchen-sink/2611

**Comment by yelban** [comment]
update node to v8.10.0
it still not work

framework7 2.0.5 @v8.9.3 --> ok (no "TypeError: parse is not a function")
framework7 2.0.10 @v8.9.3, v8.10.0, v6.12.3 -> fail (got "TypeError: parse is not a function")

**Comment by Jovaage** [comment]
@nolimits4web Has this fix also been applied to the vue kitchen sink?
Because I'm having the exact same issue there.

**Comment by nolimits4web** [comment]
@Jovaage not yet there, will be on a days
