### ISSUE TITLE
Append Range Slider 

### ISSUE THREAD

**Issue by rabee2050** [framework7io/framework7#2255]
Hi,

Appending range slider from javascript isn't working, it give only empty list item.

Here is an example:

```
var element='<li class="item-content item-input"><div class="item-media"><i class="icon demo-list-icon"></i></div><div class="item-inner"><div class="item-title item-label">Range</div><div class="item-input-wrap"><div class="range-slider range-slider-init range-slider-label" data-label="true"><input type="range" value="50" min="0" max="100" step="1"></div></div></div></li>';

$( "#listItem" ).append( element);
```

**Comment by nolimits4web** [comment]
You must initialize it after append

**Comment by rabee2050** [comment]
How to initialize it after append?

**Comment by nolimits4web** [comment]
app.range.create http://framework7.io/docs/range-slider.html#range-slider-app-methods

**Comment by rabee2050** [comment]
Dear nolimits4web,

app.range.create works only with pre existing element only, and doesn't work with the appended one.
Please advise if you have another resolution.

Thanks 
Rabee

**Comment by rabee2050** [comment]
Dear nolimits4web,

Kindly let me know if you have any update about my previous comment.

Thanks
