### ISSUE TITLE
[v1] Multiple Autocompletes - Keyboard open issue (android)

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#2257]
Hi guys. 
V1.6.5
I have an screen which has 3 autocompletes.
the ones at the bottom has the problem, when the keyboard is open I can’t see the options that the autocomplete shows me.
You can see at the image. 
How can I fix it? any ideas?
I know that in V2 is fixed, I've already read it but I can't migrate right now this app.

![image](https://user-images.githubusercontent.com/12813221/37095278-2b4ba6a6-21f4-11e8-9d3e-59f668fa619f.png)

I've also post it on forum, but no answer
http://forum.framework7.io/t/v1-multiple-autocompletes-keyboard-open-issue-android/2264

**Comment by nolimits4web** [comment]
You need to scroll page content to the input on input focus. This won't be fixed in v1 anymore. I can recommend you to migrate to v2, or try to use the code from v2 https://github.com/framework7io/framework7/blob/master/src/components/input/input.js#L115-L142

Basically you need to call this `scrollIntoView` function when on input focus

**Comment by nolimits4web** [comment]
```js
function scrollIntoView(inputEl, duration, centered) {
    const $inputEl = $(inputEl);
    const $scrollableEl = $inputEl.parents('.page-content, .panel').eq(0);
    if (!$scrollableEl.length) {
      return false;
    }
    const contentHeight = $scrollableEl[0].offsetHeight;
    const contentScrollTop = $scrollableEl[0].scrollTop;
    const contentPaddingTop = parseInt($scrollableEl.css('padding-top'), 10);
    const contentPaddingBottom = parseInt($scrollableEl.css('padding-bottom'), 10);
    const contentOffsetTop = $scrollableEl.offset().top - contentScrollTop;

    const inputOffsetTop = $inputEl.offset().top - contentOffsetTop;
    const inputHeight = $inputEl[0].offsetHeight;

    const min = (inputOffsetTop + contentScrollTop) - contentPaddingTop;
    const max = ((inputOffsetTop + contentScrollTop) - contentHeight) + contentPaddingBottom + inputHeight;
    const centeredPosition = min + ((max - min) / 2);

    if (contentScrollTop > min) {
      $scrollableEl.scrollTop(centered ? centeredPosition : min, duration);
      return true;
    } else if (contentScrollTop < max) {
      $scrollableEl.scrollTop(centered ? centeredPosition : max, duration);
      return true;
    }
    return false;
  }

**Comment by vousys** [comment]
Thanks Vladimir! I'll try it.

**Comment by vousys** [comment]
It worked in ios but not in Android,... rare

**Comment by nolimits4web** [comment]
Check the source code, for Android it calls this method once first window resize occurs (after keyboard slides in). Here is the full onFocus handler for v2:
```
function onFocus() {
      const inputEl = this;
      if (app.params.input.scrollIntoViewOnFocus) {
        if (Device.android) {
          $(window).once('resize', () => {
            if (document && document.activeElement === inputEl) {
              app.input.scrollIntoView(inputEl, 0, app.params.input.scrollIntoViewCentered);
            }
          });
        } else {
          app.input.scrollIntoView(inputEl, 0, app.params.input.scrollIntoViewCentered);
        }
      }
    }

**Comment by vousys** [comment]
Ahhh!!! Thank you Vladimir!
