### ISSUE TITLE
Custom name of Index route not included in page initialization when app is loaded

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2260]
i am having a problem dealing with first page load in my app. in my routes, i set home.html as my default route, but its not included in my view.router lists. and how to set default route or index route with a different name (not index.html) e.g home.html, dashboard.html.

```
{
      path: '/',
      url: '/home.html',
    },
    {
      path: '/dashboard/',
      url: '/dashboard.html',
    },
```

when first load, the home.html is not included in the lists of routers.

**Comment by nolimits4web** [comment]
http://framework7.io/docs/view.html#initial-page-route
