### ISSUE TITLE
[v2] Routes fire twice with pushState enabled

### ISSUE THREAD

**Issue by WeaponX86** [framework7io/framework7#2264]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Platform and Target: Chrome
* Live Link or JSFiddle: Can't use pushState with jsFiddle?

### What you did
Opened kitchen sink example, enabled pushState

### Expected Behavior
Calls to async in routes should only fire once

### Actual Behavior
Calls to async in routes fire twice

**MODIFY APP.JS**
```
// Dom7
var $ = Dom7;

// Init App
var app = new Framework7({
	id: 'io.framework7.testapp',
	root: '#app',
	routes: [
		// Index page
		{
			path: '/',
			//url: './index.html',
			//name: 'home',
			async: function (routeTo, routeFrom, resolve, reject) {
				console.log('/ routeTo', routeTo);

				resolve({
					url: './index.html'
				});
			}
		},
		// About page
		{
			path: '/about/',
			//url: './pages/about.html',
			//name: 'about',
			async: function (routeTo, routeFrom, resolve, reject) {
				console.log('/about/ routeTo', routeTo);

				resolve({
					url: './pages/about.html'
				});
			}
		}
	],
	view: {
		pushState: true,
		xhrCache: false
	}
});
```
**OPEN URL**
https://www.mysite.com/kitchen-sink/index.html#!/about/

**Console output**
/about/ routeTo {query: {…}, hash: undefined, params: {…}, url: "/about/", path: "/about/", …}
/about/ routeTo {query: {…}, hash: undefined, params: {…}, url: "/about/", path: "/about/", …}

**Comment by nolimits4web** [comment]
It happens because:
- you have enabled push state for all views
- there are 2 views in kitchen sink (one more in right panel)
- this is why it will try to load the page / restore state in both views
