### ISSUE TITLE
Animation function causing error

### ISSUE THREAD

**Issue by Frooplet** [framework7io/framework7#2269]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10

### What you did

`$$('html,body').animate({scrollTop: 0}, 0);`

causes this error:

`Uncaught TypeError: $$1$1.extend is not a function`

**Comment by nolimits4web** [comment]
It should be 
```
$$('.page-content').scrollTop(0);
```
