### ISSUE TITLE
How can i hide Navbar and Toolbar on index page?

### ISSUE THREAD

**Issue by nodkrot** [framework7io/framework7#227]
I tried this

``` html
<div data-page="index" class="page no-navbar no-toolbar"> ... </div>
```

it works on any page that comes next, except Homepage (index), whats wrong?

And how do you hide Tab bar?

Is there any way to load pages (HTML) for tabbar links? Currently if I place href="somefile.html" it slides it from right instead of switching page without an effect like default tabbar behavior.

**Comment by muzuiget** [comment]
> You also need to add "hidden-navbar" class to its parent View, and "hidden-toolbar" for toolbar/tabbar

Doesn't work at v1.2.0.

After read the source code this work, but it is undocuement;

```
<div class="navbar navbar-hidden">

<div data-page="index" class="page no-navbar">
```

**Comment by OkancanCosar** [comment]
now what's solution?

**Comment by nolimits4web** [comment]
same as in previous post:

```
<div class="navbar navbar-hidden">

<div data-page="index" class="page no-navbar">
```

**Comment by OkancanCosar** [comment]
thank you for solution

**Comment by RepAntik** [comment]
What about the toolbar? :)
