### ISSUE TITLE
On Page Init event fired twice.

### ISSUE THREAD

**Issue by rkaartikeyan** [framework7io/framework7#2270]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10.
* Platform and Target: in windows chrome.
* Live Link or JSFiddle: -Nil-

### What you did
I want to load data from API on homepage init, so I put following code on page init event in initializing the app `var app = new Framework7({`.

```
on: {
        pageInit: function (page) {
            // do something on page init
            console.log(page);
            if(page.route.name == 'home'){
                alert('homepage');
            }
        }
    }
```

then I put following code and the event not fired

```
app.on('pageInit', function (page) {
    // do something on page init
    console.log(page);

    if(page.route.name == 'home'){
        alert('homepage');
    }
});
```

### Expected Behavior
It's should show the alert once on home page load.

The event fired once for other pages. like if I want to trigger a code on page init forAbout Us page, its fire once. But for homepage only its fire twice.

also for About Us page `app.on('pageInit', function (page) {` is working

### Actual Behavior
When I load the page in my windows chrome browser it's showing the alert twice.

**Comment by nolimits4web** [comment]
Means you have at least two views with a same route, like in Kitchen sink, one is main and another one is in panel. So everything is correct here
