### ISSUE TITLE
Opening of the accordion is bugged on iOS 9

### ISSUE THREAD

**Issue by SpiderNeo1** [framework7io/framework7#2272]
This is a :
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10.
* Platform and Target: 
   - on my mobile phone : iPhone 5S - iOS 9.3.2 
   - either on mobile safari OR on an application with cordova (UIWebView or ionic WKWebView)

I copied and pasted the kitchen-sink directory without touching anything.

Accordion’s open animation is bugged. When I click/tap on the accordions, it first opens then closes then opens. But, the close animation is ok.

Vladimir, I can do a video if you want.

For information, I don't have the same bug with this accordion for example : http://demos.jquerymobile.com/1.3.0-rc.1/docs/demos/widgets/accordions/

Thank you.

**Comment by DAnn2012** [comment]
The same here too by visiting the page

[http://framework7.io/kitchen-sink/?theme=ios](http://framework7.io/kitchen-sink/?theme=ios)

with iPod touch (5th generation) and iOS 9.3.5

**Comment by ahilanbeyond** [comment]
@nolimits4web Please check into this issue. This is not resolved as you mentioned earlier over here https://github.com/framework7io/framework7/issues/2271

**Comment by nolimits4web** [comment]
Can't replicate both of these.  Here are two videos recorded on real device on current kitchen sink:

* https://drive.google.com/open?id=15y13tLOYEOkA7ppN22pjuYP9tnrXQjmD
* https://drive.google.com/open?id=1c5RtxbsRZHGoefrqRwNGYxECw1FBl3ad

**Comment by SpiderNeo1** [comment]
Vladimir, 
The problem arises on iOS 9.0 versions on older devices (iPhone 5 and 5S).

Your videos are running on an iOS 11.0 or higher.

**Comment by SpiderNeo1** [comment]
I just recorded a video : 
https://www.dropbox.com/s/7ca14l3cir8lufy/accordion_bug.mov

**Comment by nolimits4web** [comment]
Don’t have any opportunity to test on iOS 9

**Comment by SpiderNeo1** [comment]
The accordion on version 1.6.5 works fine on iOS 9.0 :

http://v1.framework7.io/docs/accordion.html


I will try to analyze what you changed between V1 and V2 on this component.

**Comment by SpiderNeo1** [comment]
I just tested the accordion on an iPhone 5S iOS 11 and it works.
So this is a bug related to the iOS and not the device.
I think it comes from the CSS.

**Comment by SpiderNeo1** [comment]
Vladimir, 
I found the source of the problem. 
This is the line : `$contentEl.css('height', '');`  which does the effect "open, **close** and open".
Can we remove it ?
I can create a pull request if you want.
Are you ok ?

**Comment by nolimits4web** [comment]
But this line is required, it unsets item height after transition

**Comment by nolimits4web** [comment]
Which is makes item content responsive in case you change window width/rotate device

**Comment by SpiderNeo1** [comment]
For close ok, for opening are you sure? So, maybe, it may be just misplaced.
In any case it is clearly the bug on iOS9 and can be on iOS10.

**Comment by SpiderNeo1** [comment]
Ok, I reproduced the bug when we change window width / rotate device.
I look if we can find a solution for that.
Thanks for reopening lthe issue.

**Comment by DAnn2012** [comment]
I tried to modify lines 12717 and following of the "framework7.js" file of version 2 in order to resemble those of version 1 from:

`$contentEl.css('height', '');`
`$contentEl.transition('');`
`$el.trigger('accordion:opened');`
`app.emit('accordionOpened', $el[0]);`

to:

`$contentEl.transition(0);`
`$contentEl.css('height', 'auto');`
`var clientLeft = $contentEl[0].clientLeft;`
`$contentEl.transition('');`
`$el.trigger('accordion:opened');`
`app.emit('accordionOpened', $el[0]);`

and on iOS 9.3.5 it seems to work well now

Perhaps the problem is around these lines

**Comment by SpiderNeo1** [comment]
It's good I found based on the V1.

**Comment by SpiderNeo1** [comment]
Here : https://github.com/framework7io/framework7/pull/2277
Thank you.
