### ISSUE TITLE
CSS class Suggestion for untouched/original  styles

### ISSUE THREAD

**Issue by MiguelQueiroz** [framework7io/framework7#2273]
Sometimes when using other plugins like for example intlTelInput  the form using such plugin will have wrong CSS because the generated <ul> have their styling overwritten by framework7.

I believe the framework should have a css class such as .no-theme that would be part of the general framework css customization such that element having that class and their childs would not be affected by the framework style, preserving the initial style.

so framework css should have for example instead of 

```
.margin-right {
margin-right:20px;
}

```
be 

```
.margin-right:not(.no-theme) {
margin-right:20px;
}
```

Allowing for a better handling of what should be or not be framework css modified.

just a thought...

**Comment by nolimits4web** [comment]
Not really possible, as most of selectors should be with :not(.no-theme) theme, that will produce a lot havier CSS files, and most of such selectors will be harder to overwrite/customize. I think this can be done without much efforts on a custom-styles level
