### ISSUE TITLE
REQUEST: app.autocomplete create valueProperty send a context instead of a single value

### ISSUE THREAD

**Issue by rapgithub** [framework7io/framework7#2278]
THIS IS A REQUEST:

I think it will be very useful and grateful that app.autocomplete valueProperty could be an object instead of a single value property this way sending an object as context after selected item will be lot easier and clean... 

I try to pass an object in the ID  and the autocomplete does not work anymore... 
selection stop working either...and only a single value can be passed to work...  :(

my object

"ID":  { "CityCode": "84747", "Name": "Londonderry", "LatLng": "42.8651,-71.3739" } 

and only I can pass a single value now:

"ID": "84747"
"Name:" "bla bla bla" 

right now we have only:
 valueProperty: "ID", //object's "value" property name

is there a way to pass a context value in the valueProperty ? 
I think it will be better to have this solution!

thanks Vladimir!

**Comment by nolimits4web** [comment]
As I see at http://forum.framework7.io/t/autocomplete-with-ajax-more-options-than-only-id-and-name/1910/14 that this request can be done using some of custom logic
