### ISSUE TITLE
[v2] Timeline

### ISSUE THREAD

**Issue by l41lt0n** [framework7io/framework7#2279]
@nolimits4web,

Can we to change the timeline format from this:
![screen shot 2018-03-15 at 9 32 53 pm](https://user-images.githubusercontent.com/32529405/37497707-cad8cdde-2898-11e8-813c-00035fba06f7.png)
To
2017, December

Is interesting too a footer to the timeline.

Thanks

**Comment by J05HI** [comment]
@nolimits4web
Yeah a little bit of configuration like in the calendar would be good

**Comment by nolimits4web** [comment]
Yes, just remove timeline years, and use 2017, December as month title

**Comment by l41lt0n** [comment]
@nolimits4web,

Yes, I did it and works, maybe is interesting to add a footer to each day?

![screen shot 2018-03-16 at 8 22 03 am](https://user-images.githubusercontent.com/32529405/37518248-26b00bea-28f3-11e8-9199-576a972b6e91.png)

Thanks.
