### ISSUE TITLE
Searchbar and Searchbar Expandable appears above the sidebar on iOS 9

### ISSUE THREAD

**Issue by SpiderNeo1** [framework7io/framework7#2280]
This is a :
* [x] bug

* Framework7 Version: 2.0.10.
* Platform and Target: iPhone 5S - iOS 9.3.2 

I copied and pasted the kitchen-sink directory without touching anything.

The "Searchbar" or "Searchbar Expandable" appears above the sidebar.
Anyone has ever had this problem ?

I recorded a video : https://www.dropbox.com/s/cbw18vj7u5e8f73/searchbar_bug.mov

I'll try to see where this can come from. 

Thank you.

**Comment by nolimits4web** [comment]
You won't be able to fix it as it is iOS native behavior, it scrolls view to inputs. In cordova app such behavior can be disabled

**Comment by SpiderNeo1** [comment]
How to do ?
Should I add the plugin "cordova-plugin-statusbar" to fix this problem ?

**Comment by nolimits4web** [comment]
No, it should be https://github.com/cjpearson/cordova-plugin-keyboard  with `Keyboard.shrinkView(true)` and `Keyboard.disableScrollingInShrinkView(true)`

**Comment by SpiderNeo1** [comment]
Ok, I'll try this plugin as soon as I have a moment.
But does this bug also exist on iOS 10 or iOS 11 ?
Thank you.

**Comment by nolimits4web** [comment]
Not iOS 11 at least. It handles it better

**Comment by SpiderNeo1** [comment]
Ok, thank you.
