### ISSUE TITLE
[RFC] Use Capacitor if available for native modals

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#2306]
As [Capacitor](https://capacitor.ionicframework.com/) is released now, my question is, if it's interesting to use the native APIs if available for modals? Maybe it makes sense as a plugin?

**Comment by nolimits4web** [comment]
Not really possible at the moment as it will require to do something like
```
import { Plugins } from '@capacitor/core';
```
In the F7 core. So as well as Cordova plugins, use i will suggest to use/install it manually
