### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by octaviobh** [framework7io/framework7#2307]
In order to view and study offline and locally framework7-2.1.2 I create a "build" directory inside "kitchen-sink" with "css\framework7.css" and "js\framework7.js" subdirs and files respectively. Also in Xampp apache server I define a vitual host for this "kitchen-sink", along with a site name in the hosts local DNS file in windows.

All works fine with chrome, http:// web access via the site name, but with file://.../index.html a blank screen appears.

The same blank screen appears in Firefox and in Edge browsers, using both access, via http:// and via file://

Clear caching and others changes in browsers did not resolve the problem, a blank screen appears.

In all browsers the Page Source is the index.html as well.

I am using Firefox Version 59.0.1 64-bit, Chrome Version 63.0.3239.84 (Official Build) (64-bit), Microsoft Edge 38.14393.1066.0, Microsoft EdgeHTML 14.14393

What could be happen?. 

Why in chrome the file:// does not work and the http:// works ok?.

Thanks in advance,

Octavio.

**Comment by nolimits4web** [comment]
There is something wrong with your server. Kitchen Sink requires correct server to work

**Comment by nolimits4web** [comment]
It is better to do the following in downloaded project repo:
```
npm install
npm run prod
```

**Comment by nolimits4web** [comment]
I assume you have installed latest node.js with npm on your system
