### ISSUE TITLE
[v2] Slide button

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#2309]
@nolimits4web 

![687474703a2f2f746869726467656e652e636f6d2f6d6d746f6f6c732f6d6d736c6964696e67627574746f6e2f73637265656e732f6578616d706c652e676966](https://user-images.githubusercontent.com/6543485/38089027-a83fa7c8-337b-11e8-8a3c-79695eddbb52.gif)

**Comment by J05HI** [comment]
Nice idea

**Comment by nolimits4web** [comment]
Can’t see much value in it for the app. It is more out of the app control
