### ISSUE TITLE
V2.1.3 iPhoneX Support (not working)

### ISSUE THREAD

**Issue by jamesalanfinnigan** [framework7io/framework7#2310]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.1.3
* Platform and Target: CORDOVA

### What you did
Built a sample project using the following template with the F7 v2.1.3...
https://github.com/caiobiodere/cordova-template-framework7-vue-webpack
and noticed a large gap at the top of the display area on an iPhoneX. (ios version 11.2.5)

### Expected Behavior
The framework should properly detect an iPhoneX so that the iphonex specific CSS classes are invoked properly and the gap at the top is removed.  The class "device-iphone-x" is NOT added to the HTML class list as expected.

### Actual Behavior
The framework appears to be testing for an iphonex by checking the height of 812px.  Instead, the height is actually 667px and thus fails the iphonex test.  The 812px test might be for full-screen mode but when it's not in full screen mode, the height is 667px.

The viewport-fit=cover was also added to the index.html
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui, viewport-fit=cover">

### Errata
If the 'device-iphone-x' class is manually added to the html tag using the safari debugger, the gap is removed as expected although the status bar still has a 20px gap for some reason.

**Comment by nolimits4web** [comment]
Everything is correct
> The 812px test might be for full-screen mode but when it's not in full screen mode, the height is 667px.

When app is not in fullscreen mode, `screen.height` will still be 812px. Please check it with default official F7 template and say is there is still issue?

**Comment by nolimits4web** [comment]
Even when it is not in full screen mode it can't have `667px` height. Where did you lost 145 pixels? :D

**Comment by nolimits4web** [comment]
Can please provide a screenshot?

**Comment by nolimits4web** [comment]
Looks like you forgot to upload iPhoneX splashcreen

**Comment by nolimits4web** [comment]
There is no issue on code level. Issue you described 100% for me related to splash screen. Google what happens with iPhoneX apps without correct splash screen size
