### ISSUE TITLE
[v3] route params not updated

### ISSUE THREAD

**Issue by Jule-** [framework7io/framework7#2311]
It seems that my `route.params` are not updated when I navigate back on an already loaded page with different parameters.

Indeed, here we can see that if page has already a route we don't use new route with new params.
https://github.com/framework7io/framework7/blob/2c949dbc01d9285daf9fa02a763174fd80b6c9a5/src/modules/router/router-class.js#L904

I don't know if it is done on purpose and why we are not using new `route` but I think at least we should merge `route.params` inside `currentPage.route.params` here.

Am I right?

**Comment by nolimits4web** [comment]
This is by design, since page was created it was created acoording to some specific and unique combination of route, its params and query

**Comment by nolimits4web** [comment]
As well as calling navigate or back to same route but with different url params creates new page. You probably need to use something else instead for your logic

**Comment by Jule-** [comment]
Do you mean that we cannot use `pageName` to target pre-loaded generic page using dynamic `params` in route path?

I mean what is the point to use old `route` object if we access this page with different path, especially different `params`?

I don't understand in which case we want to ignore new generated `route` object in the line I linked.

Some context on my project: I use [Aurelia](http://aurelia.io/) framework and specially to generate all my pages at app start (because I cannot use both f7 router and aurelia router). Then I create routes with `pageName` targeting all my generated pages and use `page:init` and `page:reinit` in order to do my pages (re)initialization.

The problem occurs when having routes like:
```
{
  path: '/main/',
  pageName: 'main-page'
}, {
  path: '/myroute/:id/',
  pageName: 'my-page-name'
}
```
1. Start at `/main/`
2. Navigate to `/myroute/01234/`, it triggers `page:init` with `e.detail.route.params.id === "01234"`
3. Navigate to `/main/` (or any other route)
4. Navigate to `/myroute/56789/`, it triggers `page:reinit` with `e.detail.route.params.id === "01234"`

And this is due to the line I linked before. It uses first computed `route` instead of new one.

I don't know how to get rid of this behavior in my case or how to setup a workaround... I expect that `route.params` are updated when I get back on my page with different `url` an so different `params`.

**Comment by nolimits4web** [comment]
I will think about. But by design, each page is designed to be used with unique route. So reusing one page element for different routes is not supported. It was done intentionally, because in reactive frameworks like Vue.js or React there could be problems, they use Vue/React components for (or instead) pages and having route be changed for already rendered page could bring unexpected behavior.

As a workaround you may just use `page.router.currentRoute`

**Comment by Jule-** [comment]
Oh great! I didn't realized... Thanks I will try this!
