### ISSUE TITLE
Grid layout columns

### ISSUE THREAD

**Issue by mishkeTz** [framework7io/framework7#2313]
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.1.3
* Platform and Target: Cordova (Android/iOS)

### What you did

```
<div class="row">
	<div class="col-100 tablet-33">
               <p>1</p>
         </div>
         <div class="col-100 tablet-33">
               <p>2</p>
         </div>
         <div class="col-100 tablet-33">
               <p>3</p>
         </div>
         <div class="col-100 tablet-33">
               <p>4</p>
         </div>
         <div class="col-100 tablet-33">
               <p>5</p>
         </div>
</div>
```
### Actual Behavior
On tablet size first three columns are placed to each other and that's fine 4th column is placed to the left (that is still fine) but 5th column is centered in the space where 5th and 6th column should stay (there is no 6th column). 

### Expected Behavior
Could 5th column be aligned left to the 4th column and space for 6th column stay blank?

*IMG (pic taken in chrome)
<a href="https://ibb.co/mwB3pn"><img src="https://preview.ibb.co/gfpZvS/Capture.png" alt="Capture" border="0"></a>

**Comment by nolimits4web** [comment]
You can add empty last column. Or add "justify-content-flex-start" class to "row" and add "margin-horiontal" class to every second column in row
