### ISSUE TITLE
can not click dom element in iOS11.3

### ISSUE THREAD

**Issue by wangiv2** [framework7io/framework7#2314]
can not click dom element when app resume from background, but run normal when disable fastclick

**Comment by robinyip** [comment]
I got the same and cannot scroll as well, do you?

**Comment by SimplyLab** [comment]
Maybe linked to this note in 11.3 release note ?

https://stackoverflow.com/questions/49500339/cant-prevent-touchmove-from-scrolling-window-on-ios

(document touch event listeners are now passive by default in Safari 11.1, which is bundled with iOS 11.3. This change is documented in the Safari 11.1 release notes:)

Web APIs
[…]
Updated root document touch event listeners to use passive mode improving scrolling performance and reducing crashes.

**Comment by nolimits4web** [comment]
Seems to fixed now. Issue was due to iOS bug reporting touch event timestamp as negative value

**Comment by robinyip** [comment]
Big like to you @nolimits4web you did a great job, will there be any emergency release?

**Comment by nolimits4web** [comment]
@robinyip today will be a regular release with this fix included

**Comment by robinyip** [comment]
Great and thanks for your efforts

**Comment by wangiv2** [comment]
@nolimits4web ,  i saw it was fixed in v2.x, may i know it will be fixed in v1.x also? due to we are using v1.x version, thanks.

**Comment by zdnet** [comment]
thanks for fixing, may i know this fixing is for both 1.x and 2.x ?

**Comment by yankopetrov** [comment]
@zdnet look like in 1.7.1 the fix is there. You can check here https://github.com/framework7io/framework7/commit/08d98477e3cff0cfb2b88666338077b7a58f6730

**Comment by wangiv2** [comment]
thanks for fixing
