### ISSUE TITLE
Webpack UglifyJs Dom7 Error

### ISSUE THREAD

**Issue by cody-chen-jf** [framework7io/framework7#2319]
**Does anyone have this problem? I made a mistake when I packed framework7+vue with webpack.**

> ERROR in static/js/vendor.js from UglifyJs
> Unexpected token: name (Dom7) [static/js/vendor.js:11703,6]

**Comment by nolimits4web** [comment]
Use search before opening new issues https://github.com/framework7io/framework7-vue/issues/393. Also pay attention to the issue form. Such issues will be closed immediately

**Comment by cody-chen-jf** [comment]
@nolimits4web First, I am sorry about it, I was looking for an issue bug on **framework7**. But forgot to search on **framework7-vue** project. Finally, very thank you for your help. I will consult the information more carefully in the future.
