### ISSUE TITLE
Can't back to index page

### ISSUE THREAD

**Issue by cody-chen-jf** [framework7io/framework7#2323]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0
* Platform and Target: IOS

### What you did
I use `f7.views.main.router.navigate(url)` to jump page, and use `this.$f7router.back();` to go back, but it can not back to the root page, where should i do for it? 
Here is my code:
```
<f7-views>
    <f7-view id="main-view" main @swipeback:move="onSwipeBack" @swipeback:afterchange="onAfterSwipeBack">
        <div data-page="main_page" class="page" @page:reinit="onPageReinit" @page:init="onPageinit">
               ...
        </div>
    </f7-view>
</f7-views>
```

### Expected Behavior
I want to back to root view.

### Actual Behavior
Can't back to root view, but other view contains can back.

**Comment by nolimits4web** [comment]
> but it can not back to the root page
what do you mean and what did you try to make it back to root page? Have you seen that `back()` method has options? http://framework7.io/docs/view.html#router-api-methods-properties

**Comment by cody-chen-jf** [comment]
@nolimits4web  For example, I have three page: A, B, C
and i jump the page by:
A->B
B->C
back by:
C -> B ( success )
B -> A  ( error, here can't go back to the main view )
and there are no logger show, i don't know how can i jump to the main page

**Comment by nolimits4web** [comment]
In F7-Vue, you need to main home page route into separate vue component too like here:

https://github.com/framework7io/framework7-template-vue-webpack/blob/master/src/app.vue#L19
https://github.com/framework7io/framework7-template-vue-webpack/blob/master/src/routes.js#L11-L14
