### ISSUE TITLE
List Index scroll upward display problem

### ISSUE THREAD

**Issue by robinyip** [framework7io/framework7#2324]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.0
* Platform and Target: Any

### What you did
Click on an List Index item which the list view element is above the current scrolling position so the list have to scroll upward

### Expected Behavior
The `list-group-title` of the clicked List Index value should be position at the top and follow by the `list-group` content

### Actual Behavior
Only the `list-group-title` is positioned at top but the group content is not visible

**Comment by nolimits4web** [comment]
Fixed by #2325
