### ISSUE TITLE
router.navigation and cordova.js

### ISSUE THREAD

**Issue by TkStas** [framework7io/framework7#2329]
Hi!
When I add to my cordova project.js and build it for android, I ceases to operate router.navigation.

**Comment by nolimits4web** [comment]
Why? More details and correctly filled issue form will be great to see

**Comment by TkStas** [comment]
I can't figure it out myself because the console doesn't show any errors. All scripts work, but the transition to the page specified via router.navigation does not occur. without cordova.js everything works!

**Comment by TkStas** [comment]
From the console goes.

**Comment by swestmoreland** [comment]
You need to take steps to isolate – if you can use the APIs from the console, for instance, then evaluate the code that triggers navigation in your project to determine the root cause.

**Comment by TkStas** [comment]
I'm not very reassuring in this.
So far, I solved this problem by transferring cordova.js below framework7.min.js
