### ISSUE TITLE
Touchevents don't fire for readonly inputs

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2330]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version:  V2
* Platform and Target: All mobile

* Live Link or JSFiddle:  Will provide if needed

It appears FW7 doesn't allow touch events for readonly inputs.  This does work for mouse clicks.  The issue has been verified on android and ios devices.  Touching a readonly input does nothing.  

So why do I need this? I have a page that has many number fields.  These fields need to be incremented or decremented by the user.  Real estate is limited so the stepper component is not an option.  Instead, I added the increment and decrement functions to the toolbar where the user can up click or down click the values once he focuses the input.  The problem I ran into was on IOS.  The keyboard just doesn't behave properly and is open and closing on various events causing confusion and scrolling of the page.  This is a known focus problem with IOS and the suggestion to fix this is to make the inputs readonly.  When readonly, the keyboard won't open and the user will rely on my tool bar for inputs.  This works great in a browser as well as on my mobile site.  The trouble is FW7 is not playing nicely.  Why the difference between touch and click events in this case?  

IOS and Android both allow readonly fields with their respective browsers.  Since we are using the same webview forthe app, it seems reasonable to have the same functionality within the app. Is there a technical reason for this decision?

Thanks.

**Comment by nolimits4web** [comment]
Didn't get anything. Provide more details and fill the issue form please, what are you trying to achieve, what you expect and get, etc.

**Comment by eradin** [comment]
In addition to comments above.

### Expected Behavior
Readonly inputs (e.g. <input readonly ...>) for regular mouse clicks events will show the cursor in the input but not let users type.  This is standard behavior on browser platforms as well as tap events  in IOS and Android webviews. In contrast, Disabled inputs don't show a cursor and prevent typing.

### Actual Behavior
FW7 Tap events treat both readonly and disabled as disabled.  This is inconsistent with ios and android browsers.

**Comment by nolimits4web** [comment]
https://jsfiddle.net/s1774ds4/ no cursor on desktop. Can't see much sense to have cursor focused in readonly input, and i can't remember i saw anything like this in apps. Anyway, just add `no-fastclick` to input if you want to disable F7's touch behavior on it

**Comment by eradin** [comment]
I don't think you understand.  The cursor is not the problem (although firefox shows a cursor, chrome doesn't).  There is no focus on tap where there is on click.  Now, you can argue there shouldn't be a focus on readonly but there is on click but not tap.  All I'm saying is click and tap should work the same regardless.
