### ISSUE TITLE
[v2] Swipe to delete not animating like in v1

### ISSUE THREAD

**Issue by Tarekajaj** [framework7io/framework7#2331]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.0
* Platform and Target: Chrome Version 65.0.3325.181

### What you did
In Kitchen sink, try "swipe to delete" an item.

### Expected Behavior
Item remove with swiping and shrinking animation.

### Actual Behavior
Item disappearing without any animation, causing page jump for media list items

**Comment by nolimits4web** [comment]
No, i can see same animation as in v1

**Comment by Tarekajaj** [comment]
Check video Please

[2018_04_08_09_55_40_1.zip](https://github.com/framework7io/framework7/files/1887115/2018_04_08_09_55_40_1.zip)

**Comment by nolimits4web** [comment]
And what is the browser and android version?

**Comment by Tarekajaj** [comment]
Chrome 65.0.3325.109
Android 7.0.0

**Comment by Tarekajaj** [comment]
I investigated the issue a little bit, and found that the height of the swipeout being calculated, before applying `height: 0px`, is not taking effect, so the transition between the calculated height and 0 is not happening which also does not trigger animationend so the element is not removed from DOM.

**Comment by nolimits4web** [comment]
Does anyone else see same issue?

**Comment by Tarekajaj** [comment]
It's happening on chrome on android and chrome on windows when viewing the page in mobile emulation mode.
