### ISSUE TITLE
[v2] Autocomplete: display of multiple values in the item-after

### ISSUE THREAD

**Issue by Lloyc** [framework7io/framework7#2332]
This is a (multiple allowed):
* [x] bug
* [] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version:  2.2.0
* Platform and Target: Chrome Version 65.0.3325.181

### What you did
In Kitchen sink, try to add multiple values in the Autocomplete.

### Expected Behavior
Should behave like the smart select with multiple values.

### Actual Behavior
![image](https://user-images.githubusercontent.com/11031281/38443728-b5de1550-39ba-11e8-86f2-c97cee68fde4.png)

**Comment by nolimits4web** [comment]
Because it is usual list, just add `max-width: 70%;` to `.item-after` in this list
