### ISSUE TITLE
Swipeable tabbar on iOS v1.7.1?

### ISSUE THREAD

**Issue by JosephShenton** [framework7io/framework7#2344]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.7.1
* Platform and Target: iOS

Is there a way to use the Swipeable tabbar on iOS in v1.7.1?

I got it to work fine how it's meant to however it doesn't scroll on iOS just on computer.

**Comment by nolimits4web** [comment]
No, there isn't swipeable tabbar for iOS theme in v1. You need to implement it manually
