### ISSUE TITLE
[v2] Searchbar-expandable is sluggish on Android

### ISSUE THREAD

**Issue by hongnk** [framework7io/framework7#2355]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.1.
* Platform and Target: Chrome 66 on Android.
* Live Link or JSFiddle: Just a default searchbar set up, like this https://jsfiddle.net/zomcmhc1/1/

### What you did
Use default searchbar-expandable sample.

### Expected Behavior
When click search, the searchbar slide out.

### Actual Behavior
 It is sluggish on android. Occasionally it shifts the whole screen 10px to the left.

I think this is due to the input focus (make keyboard popups) at the same time with slide out animation. I tried with override like this (only focus on input after transition ends) and it is smooth:
```javascript
Framework7.Searchbar.prototype.enable = function enable () {
    var sb = this;
    if (sb.enabled) { return sb; }
    var app = sb.app;
    sb.enabled = true;

    function enable() {
      if (sb.$backdropEl && ((sb.$searchContainer && sb.$searchContainer.length) || sb.params.customSearch) && !sb.$el.hasClass('searchbar-enabled') && !sb.query) {
        sb.backdropShow();
      }
      sb.$el.addClass('searchbar-enabled');
      if (!sb.expandable && sb.$disableButtonEl && sb.$disableButtonEl.length > 0 && app.theme === 'ios') {
        if (!sb.disableButtonHasMargin) {
          sb.setDisableButtonMargin();
        }
        sb.$disableButtonEl.css(("margin-" + (app.rtl ? 'left' : 'right')), '0px');
      }
      if (sb.$hideOnEnableEl) { sb.$hideOnEnableEl.addClass('hidden-by-searchbar'); }
      sb.$el.trigger('searchbar:enable');
      sb.emit('local::enable searchbarEnable', sb);
    }

    sb.$el.on('transitionend', function() {
      sb.inputEl.focus();
      sb.$el.off('transitionend');
    })
    enable();
    return sb;
  }
```

**Comment by newhow** [comment]
yes，I observed the same situation. But if you look at the search expandable example from [f7 kitchen sink](https://framework7.io/kitchen-sink/?themes=ios), you will find it is quite responsive.
