### ISSUE TITLE
Can't open panel from inside a function

### ISSUE THREAD

**Issue by ragcsalo** [framework7io/framework7#2356]
* [x] bug
* Framework7 Version: 2.0.10
* Platform and Target: Cordova Android

I can't open the panel from inside a function. This doesn't work:

```
function open_the_panel() {
  app.panel.open('left');
}

<button onClick="open_the_panel()">open<button>
```

I tested it with `alert(app);` inside the function, and it returned `[object Object]`, so it should work...

However, when I open the panel directly from the onClick, it works:

```
<button onClick="app.panel.open('left')">open<button>
```

**Comment by nolimits4web** [comment]
What you write in `onClick` handler must be available in global scope, e.g. 
```
window.open_the_panel = function () {
  app.panel.open('left');
}
```
