### ISSUE TITLE
[v2] Not Smooth Scrolling with virtual list

### ISSUE THREAD

**Issue by hacktube** [framework7io/framework7#2361]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Latest.
* Platform and Target: Android (Cordova).

I use the list virtual framework7 function, unfortunately the virtual list can not run smoothly. sometimes when scroll of app content becomes blinking.

and the following is the source code snippet I'm using.

```
var virtualList = app.virtualList.create({
  // List Element
  el: '.virtual-list',
  items: [],
  createUl: false,
  itemTemplate: '<div class="berita">'+
              '<div class="auth">'+
                '<a href="#">'+
                    '<img src="img/galaxy.jpg">'+
                  '</a>'+
                '<h1>{{judul}}</h1>'+
                '<h2>Posted By</h2>'+
              '</div>'+
              '<a href="/berita/?&judul={{judul}}" class="tab-link isi">'+
                '<img src="img/1.jpg">'+
                '<p>{{konten}}</p>'+
                '<h3>{{tanggal}}</h3>'+
                '<h4>See More</h4>'+
              '</a>'+
              '</div>',
})

function onHome(){

  var url = "http://192.168.1.2/cekdata.php"

  app.request({
    url: url,
    dataType: 'JSON',
    success: (data) => {
      data = JSON.parse(data)
      data.forEach((item,i) => {
        virtualList.appendItem({
          judul: item.judul,
          konten: item.konten.substr(0,255),
          tanggal: item.tanggal,
          })
      })
    },
    error: () => {
      toastCenter.open()
    }
  })

}
```

and here's what I'm going through.

https://youtu.be/RMGbKgcdO7g

**Comment by nolimits4web** [comment]
VL performance depends on many factors like device performance itself, webview performance you are using in app, browser (if runs in browser), and how heavy is VL item DOM and its styles

**Comment by tuzhiye123** [comment]
Because I need to set different heights for items, so the height parameter is the function, but the "rowsBefore" and "rowsAfter" parameters do not work. When height is number, the above two parameters work.

**Comment by hacktube** [comment]
I fix this. With add height function and set to 190. 👍

**Comment by J05HI** [comment]
@achubutkin
Yeah thats the problem maybe
