### ISSUE TITLE
function Request(requestOptions)  ignores POST & headers when dataType:'json' is used

### ISSUE THREAD

**Issue by goedzo** [framework7io/framework7#2362]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.1
* Platform and Target: www - Window Chrome, Cordova & Android

### What you did
Tried to send a JSON request while posting data and setting some custom headers in the process:

    app.request({
        method: 'POST',               
        crossDomain: true,
        contentType: 'application/json', // important
        url: 'http://www.google.com',
        dataType : 'json',
        headers: {
            'session-id': '1235455'
        },
        success: function(jsonData){
            console.log(JSON.stringify(jsonData));
        },
        error: function(xhr,status) {
            app.dialog.alert(status,xhr);
        }
    });        

### Expected Behavior
Session ID should be added to the headers, and the request type should be post.

### Actual Behavior
While looking into the chrome network browser, the method used actually was GET and the header was not added to the request.

Looking into the Framework7 code, it seems that it was caused by this code when dataType is set to json:

```
  // JSONP
  if (options.dataType === 'json' && options.url.indexOf('callback=') >= 0) {
    var callbackName = "f7jsonp_" + (Date.now() + ((jsonpRequests += 1)));
    var abortTimeout;
    var callbackSplit = options.url.split('callback=');
    var requestUrl = (callbackSplit[0]) + "callback=" + callbackName;
    if (callbackSplit[1].indexOf('&') >= 0) {
      var addVars = callbackSplit[1].split('&').filter(function (el) { return el.indexOf('=') > 0; }).join('&');
      if (addVars.length > 0) { requestUrl += "&" + addVars; }
    }

    // Create script
    var script = doc.createElement('script');
    script.type = 'text/javascript';
    script.onerror = function onerror() {
      clearTimeout(abortTimeout);
      fireCallback('error', null, 'scripterror');
      fireCallback('complete', null, 'scripterror');
    };
    script.src = requestUrl;

    // Handler
    win[callbackName] = function jsonpCallback(data) {
      clearTimeout(abortTimeout);
      fireCallback('success', data);
      script.parentNode.removeChild(script);
      script = null;
      delete win[callbackName];
    };
    doc.querySelector('head').appendChild(script);

    if (options.timeout > 0) {
      abortTimeout = setTimeout(function () {
        script.parentNode.removeChild(script);
        script = null;
        fireCallback('error', null, 'timeout');
      }, options.timeout);
    }

    return undefined;
  }

```

It just ignores all the headers, and options that have been set.

As a workaround setting  dataType : 'text' actually seems to work.

**Comment by nolimits4web** [comment]
You need to remove `callback=...` from the URL request query, in this it loads resource as a script which doesn't allow any headers, etc.

**Comment by goedzo** [comment]
Why should it be removed? This is not default behaviour. You should be able to send headers and post data, even when using the callback structure.

I need to send headers for authentication purposes.

**Comment by nolimits4web** [comment]
When using callback it will be loaded as script instead of XHR request, this is by design
