### ISSUE TITLE
[V2] Multiple notifications

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2365]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: V2
* Platform and Target: MD and IOS
* Live Link or JSFiddle: 

EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
In V1, notifications (in app) could stack as they came in.  This is not so in V2 as subsequent notifications will replace the last notification if it hadn't been dismissed.  Apparently the support for multiple notifications has been removed.

Why this is necessary.  On both IOS and Android, if a notification payload (as opposed to data payload) has been sent to the app via FCM and the app is not in the foreground, the notifications will be sent to the system tray (or notification bar).  If multiple notifications are sent, they will all appear "stacked" until the user acts on them.  If the app is in the foreground, the notification is sent to the app to handle the event.  Should subsequent notifications come in while the prior one is showing, the prior one will be replaced and therefore lost.

It would be nice to be able to have the same functionality in the app as in the system tray.

Also, perhaps an explanation on why this functionality was removed from V2.

**Comment by nolimits4web** [comment]
It was removed by design due to good practise guidelines, and to prevent app interface clean. App is not a system tray, and in iOS native apps you can't see more than one notification at once in foreground, same here.
