### ISSUE TITLE
Layout for Swipe To Delete in documentation is not correct?

### ISSUE THREAD

**Issue by achubutkin** [framework7io/framework7#2369]
Example in documentation [http://framework7.io/docs/swipeout.html#swipe-to-delete](http://framework7.io/docs/swipeout.html#swipe-to-delete) after the paragraph below is not correct? 

> It is also possible to call Confirm modal when user clicks on "Delete" button, and element will be removed only after confirmation. To make delete on confirmation you need to add additional data-confirm and data-confirm-title (optional) attributes to Delete link:

**Comment by nolimits4web** [comment]
Why? Looks correct for me

**Comment by achubutkin** [comment]
The unnecessary **div** tag after the **a** tag.

**Comment by nolimits4web** [comment]
You are right, fixed
