### ISSUE TITLE
Q: Access swipe event

### ISSUE THREAD

**Issue by StreetStrider** [framework7io/framework7#237]
Good day.
It looks like F7 has strong support for mobile events, like swipe and tap. Is it possible to make use of this events directly? For instance, I want to create custom behavior on swipe or smth. Does `Dom7` exposes this events? (`$$('.selector').on('swipeleft', fn)`)
The documentation does not cover this issue.

**Comment by plusmancn** [comment]
That's what i want too !

**Comment by sandeepy02** [comment]
Me too!

**Comment by velickym** [comment]
+1

**Comment by ziedmahdi** [comment]
+1

**Comment by ZanderBrown** [comment]
why aren't people using reactions or 👍 emoji?

**Comment by Unripe** [comment]
I would like to be able to respond to a swipe event in a custom way. Any idea when this might be added?

**Comment by iamsudharshan** [comment]
Which event(swipe up and swipe down) should we use make it work below example.
https://tympanus.net/Development/BookBlock/index2.html

**Comment by ZanderBrown** [comment]
Any progress on this?

**Comment by iamsudharshan** [comment]
@nolimits4web , @ZanderBrown I have done few modifications, this is not working onload of app but works on history back 

$$(document).on('pageInit', function() {
var touchmoved;
$(".bb-item").on('touchend', function (e) {
	if (touchmoved != true) {
		$(this).prev('input').val("");
	}
}).on('touchmove', function (e) {
	touchmoved = true;
}).on('touchstart', function () {
	touchmoved = true;
});

var Page = (function () {

	var config = {
			$bookBlock: $('#bb-bookblock'),
			$navNext: $('#bb-nav-next'),
			$navPrev: $('#bb-nav-prev')
		},
		init = function () {
			config.$bookBlock.bookblock({
				orientation: 'horizontal',
				speed: 700
			});
			initEvents();
		},
		initEvents = function () {

			var $slides = config.$bookBlock.children();

			$(".bb-item").swipe({
				//Generic swipe handler for all directions
				swipe: function (event, direction, distance, duration, fingerCount, fingerData) {
					if (direction == "up") {
						config.$bookBlock.bookblock('next');
						return false;
					} else {
						config.$bookBlock.bookblock('prev');
						return false;
					}
				}
			});

			//Set some options later
			$(".bb-item").swipe({
				fingers: 1
			});

			// add keyboard events
			$(document).keydown(function (e) {
				var keyCode = e.keyCode || e.which,
					arrow = {
						left: 37,
						up: 38,
						right: 39,
						down: 40
					};

				switch (keyCode) {
					case arrow.up:
						config.$bookBlock.bookblock('prev');
						e.preventDefault();
						break;
					case arrow.down:
						config.$bookBlock.bookblock('next');
						e.preventDefault();
						break;
				}

			});
		};

	return {
		init: init
	};

})();
	Page.init();
	});

**Comment by ZanderBrown** [comment]
@iamsudharshan could you put together a plugin or PR?

**Comment by iamsudharshan** [comment]
@ZanderBrown , this is not working onload of app

**Comment by Unripe** [comment]
Is this something I can use now? Do I need a new version of Framework7?

**Comment by ZanderBrown** [comment]
No it's not currently available

**Comment by ZanderBrown** [comment]
V2 has been released, this is largely related to Dom7 and has seen little activity
