### ISSUE TITLE
[v3] FAB - Text Label

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#2372]
@nolimits4web 

It would be nice if FAB has an optional label because sometimes we don't understand by icon.
For example:
![screenshot_015](https://user-images.githubusercontent.com/6543485/39739443-83ced4b6-52ae-11e8-9f6b-052cb57abf29.png)

**Comment by contfedorov** [comment]
But @nolimits4web, from the same spec:

> Related actions can have text labels.

https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions

**Comment by nolimits4web** [comment]
@contfedorov yeah, they actually updated MD recently, so guess will need to add it then, including extended FAB with text label too

**Comment by nolimits4web** [comment]
Added in v3 5d58b2a
