### ISSUE TITLE
Pageinit doesnt work on first load of index page

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2373]
pageinit doesnt work on first load but it has elements, only js not working

```
<div data-page="index" data-name="index" class="page">
<!-- contents here -->
</div>

// to identify if the page is loading
$$(document).on('page:init', '.page[data-name="index"]', function (e){
  console.log('index');
});
```
but if I return back to that page it loads now, why is that? and i check the details from first load, the page was not registered in routes. only after then it proceeded to other page and when return to index that was the time it got registered.

**Comment by nolimits4web** [comment]
No need to duplicate issues https://github.com/framework7io/framework7-vue/issues/422
