### ISSUE TITLE
Search bar fail if Virtual list created on popup

### ISSUE THREAD

**Issue by mohshraim** [framework7io/framework7#2375]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.5
* Platform and Target: IOS
* Live Link or JSFiddle:  https://jsfiddle.net/mohshraim/op84wjje/1/

### What you did
create a dynamic popup that contain a virtual list ;;; on open popup initialize the virtual list,, virtual list will created but search bar will fail..

### Expected Behavior
search bar should work on popup with  virtual list??

### Actual Behavior
search bar **doesn't** work on popup with  virtual list

**Comment by nolimits4web** [comment]
Just add additional `view-init` class to the view in popup. It is required for page to initialize
