### ISSUE TITLE
Page Does not reload  V1

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/framework7#2378]
HI! 

I have a notification list with unread and read sign (red for unread) (no sign if already read)

My problem is when user click on the notification to view it on notification detail page and go back again to the list, the LIST page did not update (we have code to remove the red sign if already read)

Our code is working properly, the only problem is the page does not reload/refresh

I try to navigate on some other page then go back again in notification list, that is only the time it refresh

I put a page back event to (that’s why there is alert after going back to detail page to list)

MORE DETAILS WITH VIDEO
http://forum.framework7.io/t/page-does-not-reload-refresh-v1/3418

**Comment by nolimits4web** [comment]
Sorry, but v1 is not maintained anymore

**Comment by johndavemanuel** [comment]
is this a known bug?

**Comment by johndavemanuel** [comment]
so there is no solution to this?

**Comment by nolimits4web** [comment]
No, for me looks like the problem in your code/implementation. GitHub is just not the right place for v1 issues/questions. There is a forum for this

**Comment by johndavemanuel** [comment]
hi I also posted in forums
