### ISSUE TITLE
app.panel.disableSwipe throwing error

### ISSUE THREAD

**Issue by chachew** [framework7io/framework7#2379]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.5
* Platform and Target: Cordova

### What you did
In previous parts of my code i am enabling the right panel swipe option. `app.panel.enableSwipe('right');`
Later in my code after i am done with the right panel i want to disable the right panel swipe action. `app.panel.disableSwipe('right');`

### Expected Behavior
I expect the system to disable the swipe action without issue.

### Actual Behavior
A js error is thrown in the console and it then locks up the rest of my application.

`Uncaught TypeError: panels.forEach is not a function
    at Object.disableSwipe (framework7.js:14811)
    at Framework7.<anonymous> (my-app.js:273)
    at framework7.js:3047
    at Array.forEach (<anonymous>)
    at framework7.js:3046
    at Array.forEach (<anonymous>)
    at Framework7.emit (framework7.js:3040)
    at framework7.js:3053
    at Array.forEach (<anonymous>)
    at View.emit (framework7.js:3052)`

**Comment by nolimits4web** [comment]
Fixed by #2380
