### ISSUE TITLE
When import framework7.esm.bundle.js in html, I got the error message which is "Uncaught SyntaxError: Unexpected token {"

### ISSUE THREAD

**Issue by harbourside** [framework7io/framework7#2381]
version : v.2.2.5

I import framework7.esm.bundle.js in html,like this

`<script type="text/javascript" src="js/framework7.esm.bundle.js"></script>`

When i run in browser,i get the error message which is "Uncaught SyntaxError: Unexpected token {"
in line 
`import { window as window$1, document} from 'ssr-window';`

Am i wrong to use it ? I fallow the guide to set it.

**Comment by nolimits4web** [comment]
Where did you get that you need to include `esm` script? It is for bundlers, use the script from `dist/js/` folder `framework7.js` or `framework7.min.js`
