### ISSUE TITLE
touchstart is triggered twice in Ember app

### ISSUE THREAD

**Issue by engwan** [framework7io/framework7#2382]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.5
* Platform and Target: desktop chrome, ios, android

### What you did
Used framework7 within Ember.js app.
Clicked on a button, or anywhere actually

### Expected Behavior
`touchstart` fires once

### Actual Behavior
`touchstart` fires twice. I added a `console.log` in the `handleTouchStart` function and it is called twice. When not in an Ember app, it works fine, so I'm not sure which part of Ember is causing the problem.

This causes ripple divs to remain after pressing buttons because `createRipple` is actually invoked twice and only one is removed.

**Comment by nolimits4web** [comment]
But the problem obviously on Ember or in your app side. Don't you init F7 twice?

**Comment by engwan** [comment]
That was it. I didn't notice I init F7 twice.

Thank you
