### ISSUE TITLE
calendar issue while clicking on background elements

### ISSUE THREAD

**Issue by Dreamax1** [framework7io/framework7#2383]
I got some weird issue while my Calendar is open to choose dates.
When its open and i click on background elements like checkbox OR if i double click fast on the inputs it will preform "back" action and will route me to the previous route, same as click on the "back" button on top.

basicly while calendar is open double click on elements outside of the calendar causing the page to close and return to the prev route i've been in.

i have no idea why this kind of behavious happening. 
i belive its a bug.

**Comment by nolimits4web** [comment]
Will be good to see JSFiddle or live example with the issue

**Comment by Dreamax1** [comment]
i made a simple example, using the code from your github (no changes in the code) it will show you the problem with the double click. if there was an checkbox  a click (one click) on the checkbox while the calendar is open , create same issue.
the code i did test on is located on /framework7-2.2.1/kitchen-sink/index.html
video on that link, u can test it yourself
https://vimeo.com/269388714

**Comment by nolimits4web** [comment]
Can't see such issue and can't replicate it. Could it be device related issue? Do you see same in other device?

**Comment by Dreamax1** [comment]
this video is taken from your demo on chrome browser on desktop pc

**Comment by Dreamax1** [comment]
i wonder why did you close it. this is a video from your app on your website. 
if you want i can give you access to my computer and i will show it to you live. 
Dont you want to find potential bug and fix it ?

**Comment by nolimits4web** [comment]
Because it was fixed and you can see it here

**Comment by Dreamax1** [comment]
Ohh you fix the issue thats great!
what file i should update ( i dont want to replace all my files)
