### ISSUE TITLE
Pull To Refresh (sometimes) does not reset state

### ISSUE THREAD

**Issue by Digigreg** [framework7io/framework7#2384]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Platform and Target: iOS

### What you did
I'm usinf "Pull To Refresh" in a tabbable view.

### Expected Behavior
I want to execute a function on pull action, then I want to reset the state of spinner.

### Actual Behavior
In two of the four tabs, it work normally. In the other two tabs it fires the function but the spinner continues to spin for forever without stop. I've tried to do some tests, to replace ids of tabs, but the result is still the same. Apparently without explanation.

Also I've Googled this problem, I have found some pages with this problem but no solution, so I've thought to open a new issue to understand if it's a little bug or not.

**Comment by nolimits4web** [comment]
Example or JSFiddle with the issue is appreciated

**Comment by Digigreg** [comment]
Sorry nolimits4web for long time reply, I was really busy in this week.

I've loaded a simplified copy of the app on this link: https://demo.digigreg.com/customers/framework7
And if you need, you can download a copy of that app from: https://demo.digigreg.com/customers/framework7/demo_app.zip

When you will open it, in the first page, on the right panel (open it by the right-top corner link), you will be able to use "Pull To Refresh" correctly.
Instead if you open the message view (second tab), you will see that "Pull To Refresh" works unproperly: it works but the loader won't disappear after the function is fired.

If you need more explanation feel free to ask, I will try to answer as soon as I can.

**Comment by nolimits4web** [comment]
You must pass correct PTR element to the `app.ptr.done` function http://framework7.io/docs/pull-to-refresh.html#pull-to-refresh-app-methods

**Comment by Digigreg** [comment]
I've done it, all is working perfectly. So I want to say sorry for my misunderstood of your beautiful framework.
