### ISSUE TITLE
Callback event for swipeout "cancel" in dialog

### ISSUE THREAD

**Issue by templatetuners** [framework7io/framework7#2387]
Hello and thanks for geat work you do here.

Can I get a sample code for the swipeout - cancel event?

Using this code right now to delete products

```
$('.deleted-callback').on('swipeout:deleted', function() {
    deleteProduct($(this).data('id'));
});
```

```
<li class="swipeout deleted-callback" data-id="my-custom-id-here">
...
</div>
```

When I swipe the popup shows with ok and cancel buttons. If I press cancel, the swipe remains open, need to close it.

Btw, when is the v3 going to be released?

Thanks

**Comment by nolimits4web** [comment]
Can't see much sense in such event. It is better and easier to do it manually then:
```
$('.swipeout-my-delete').on('click', (e) => {
  const $swipeoutEl = $clickedEl.closest('.swipeout');
  if ($swipeoutEl.length === 0) return;
  app.dialog.confirm('Are you sure you want to delete this?', 'My App Title',
    () => {
    app.swipeout.delete($swipeoutEl);
  }, () => {
    app.swipeout.close();
  });
});
