### ISSUE TITLE
Preventdefault active state

### ISSUE THREAD

**Issue by templatetuners** [framework7io/framework7#2389]
Disabled this:

```
    touch: {
        fastClicks: false,
        tapHoldDelay:0,
        tapHoldPreventClicks:false,
        activeState:false,
        activeStateElements:'a',
        materialRipple:false,
        tapHold: false //enable tap hold events
    },
    animatePages: false,
```

When I am opening new page in F7, than on pageInit i am running `$('#description').trumbowyg()`

Works only if it's html code. Even like that, on focus is going to bottom of text (and it's not from their side, checked with blank code)

Can't focus on normal editor. On press is adding active state class on any elements.

If I long press 1 - 2 seconds than is going out of active state and my editor is working, but just for a few second than F7 acting again.

Any ideea how can I get rid of this?

Tried with `stopImmediatePropagation`, `stopPropagation`, `preventDefault`.. Dunno what else to try.

**Comment by nolimits4web** [comment]
With such parameters it won't add active-state class, just checked, and it can't as you totally disable it.  Issue can be if you are using v1 and such parameters are only for v2. Refer to v1 docs at http://v1.framework7.io/

If you are really using v2 then create new issue and fill the issue form correctly and provide some live example or JSFiddle with the issue
