### ISSUE TITLE
[v3] Router not working properly with modal dialogs.

### ISSUE THREAD

**Issue by nschermer** [framework7io/framework7#2401]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.5
* Platform and Target: 

If I use the router to open a popup with ```pushState: true`` during app initiazation.
```
{
	path: '/popuptest',
	options: { 
		pushState: false,
		history: false
	},
	popup: {
		url: './pages/test.html'
	}
},
```
The close-popup link seems to trigger the router's back event twice.

**Comment by nolimits4web** [comment]
Can't replicate this issue, would be good to see more code or better JSFiddle with the setup where issue is reproduced

**Comment by nschermer** [comment]
I've worked around this by using a separate popup view [with its own router]. It was also not easy to reproduce.
