### ISSUE TITLE
When back to routable tabs, it will load the wrong component

### ISSUE THREAD

**Issue by sinofaneliu** [framework7io/framework7#2405]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2.2.5

with enabled Push State, when back to routable tabs page from other page, it will always load default route's component, but the url is right.

 My routes likes this:

```
  {
    path: '/other/',
    name: 'other-page',
    component: require('./components/Other.vue'),
  }, {
    path: '/tabs/',
    name: 'tabs',
    component: require('./components/Main.vue'),
    tabs: [
      {
        path: '/',
        id: 'tab1',
        name: 'tab1',
        component: require('./components/views/Tab1.vue'),
      }, {
        path: '/tab2/',
        id: 'tab2',
        name: 'tab2',
        component: require('./components/views/Tab2.vue'),
      }
    ]
  }
```

I go to `other-page` from` tab2`, then I check the button with `back`, the url path is `/tab2/`, bue the component loaded is `Tab1.vue`

it didn't happened in v2.2.1

**Comment by nolimits4web** [comment]
Can't replicate this, would be good to see live example or JSFiddle with the issue
