### ISSUE TITLE
dropdownContainerEl in Autocomplete (F7 v2.2.5)

### ISSUE THREAD

**Issue by jhonsore** [framework7io/framework7#2407]
Hi all,

i am trying to create an autocomplete with app.autocomplete.create() and realized that the option dropdownContainerEl cant be used because it is empty in framework7.js 

For some reason when i try to create my autocomplete dropdown, its position is wrong (check image below). It should be aligned to left of my input box.

![f7](https://user-images.githubusercontent.com/11234443/40379803-88f5f7ba-5dcd-11e8-87ff-bea02de89707.jpg)

So, i would appreciate to use the dropdownContainerEl param to put my autocomplete inside a container of my choice because it is always appended to element .page-content

**Comment by nolimits4web** [comment]
> it is always appended to element .page-content

This is actually correct behavior, because it must be on top of other elements.
It is better to find a reason why is it positioned in a wrong way. Do you have a live example with the issue so i can check?

**Comment by jhonsore** [comment]
Hi,

It is in dev mode so you can see by yourself.

http://webapp27940.ip-45-33-13-144.cloudezapp.io/
user: appadv
pass:12345a

When u log in will see two boxes (red and blue). Type in "Fruit 1" or "Fruit 2" input that u will check the wrong position. I put in parent div an inline css style to u see that the dropdown position changes according to the father position.

Fruit 1 input is inside a simple div, and Fruit 2 is inside a F7 html structure, maybe this can help u find the reason why the position is wrong.

Fruit 1 takes the complete wrong position moving dropdown to right.
Fruit 2 keeps the dropdown always in left, but, didnt moves according to the parent box.

Thanks ya!

**Comment by jhonsore** [comment]
I know that u closed this issue, but i updated my framework7.js/ framwork7.min.js and the error in position still happens.

Autocomplete is not being append to parent with dropdownContainerEl parameter.

I tried this code below, something is wrong?

`var autocompleteDropdownSimple = app.autocomplete.create({
        inputEl: '#autocomplete-dropdown-2',
        openIn: 'dropdown',
        dropdownContainerEl:"#teste2",`

`var autocompleteDropdownSimple = app.autocomplete.create({
        inputEl: '#autocomplete-dropdown',
        dropdownContainerEl:"#teste",
        openIn: 'dropdown',`

Should be good if you update http://framework7.io/docs/autocomplete.html#autocomplete-parameters with this param too because it is not documented.

I update the live code if u wanna check.

http://webapp27940.ip-45-33-13-144.cloudezapp.io/
user: appadv
pass:12345a

Thanks.

**Comment by nolimits4web** [comment]
The fix is not released yet. You need to build the library to see the fix

**Comment by jhonsore** [comment]
I built and now is ok.

Thanks a lot.
