### ISSUE TITLE
Line for list divider too short in MD-Layout

### ISSUE THREAD

**Issue by cyberbeat** [framework7io/framework7#2409]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.3.0
* Platform and Target: Android

You can see it here in your own example:
https://framework7.io/docs/list-view.html
Look at the list divider "Divider Here" in Android-Design: the top border-line starts not at the beginning - this could look better.

**Comment by nolimits4web** [comment]
You can tweak item style that is before divider to look it as you want in custom CSS, i can't do it automatically (CSS can't look forward) and don't see much sense to do it with JS
