### ISSUE TITLE
Template7 v2.3.0

### ISSUE THREAD

**Issue by sanbenedetto** [framework7io/framework7#2410]
`Template7.compile('{{#this}}{{/this}}')();`

sometimes  return error:
`Uncaught ReferenceError: Template7Helpers is not defined`

- Template7 v1.3.5
- Framework7 v2.3.0

**Comment by nolimits4web** [comment]
Go to http://framework7.io/kitchen-sink/?theme=ios and run it in console:
```
Template7.compile('{{#this}}{{/this}}')()
```
Can't see such issues

**Comment by sanbenedetto** [comment]
ks is ok

now i realize that the error occurs also in v2.2.5
so it is not the new-version "fault"

looks like it happens on a very-slow-network
i will investigate

you can close this issue

```
Uncaught ReferenceError: Template7Helpers is not defined
    at Object.eval [as views] (eval at <anonymous> (app.js:25), <anonymous>:8:40)
    at Object.success (app.js:66)
    at r (core.js:1)
    at XMLHttpRequest.Request.f.onload (core.js:1)
```
