### ISSUE TITLE
click bind on #id selector

### ISSUE THREAD

**Issue by cgcerro** [framework7io/framework7#2411]
When I try bind click element in a button in this way:

```
function nextAction(){
 //do something
};
$$("#nextbutton").on("click",nextAction);
```
The nextAction get any results, and navigate to the current route (reload) whith different results. In this point click is not binded again. if you click nextAction is not launched.

I have try different ways:
`$$(document).on("click","#nextbutton",nextAction);`
and now nextAction is launched, but every time I navigate the same route the event is re-binded. nextAction is launched 2 times. The same problem explained here:

http://forum.framework7.io/t/click-fired-multiple-times/2253

In this point I have tried use off to unbind previuosly:
```
$$(document).off("click","#nextbutton",nextAction);
$$(document).on("click","#nextbutton",nextAction);

```
but it seems not work.

then, finally, if I use a class selector 
`$$(".nextbutton").on("click",nextAction); `
instead Id selector, it seems to work fine.

I'm sorry about my english. But, I expect to be usefull.

**Comment by nolimits4web** [comment]
If you use ID you need to assign it in right place, if it doesn't work then it means there is no `#nextbutton` element or there is MORE THAN ONE such element in the DOM. It is better to it in related pageInit event like where you can target this element under page element, e.g. `page.$el.find('#nextbutton').on('click', ....)`

**Comment by cgcerro** [comment]
thanks a lot!!
