### ISSUE TITLE
Grid Layout does not contain styles CSS with -webkit- prefix

### ISSUE THREAD

**Issue by achubutkin** [framework7io/framework7#2415]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.3.0.
* Platform and Target: iOS 11.4, iPad, WKWebView

### What you did
Create Grid Layout. By defaul all "cells" has 15px gap between each other for iOS theme and 16px gap for MD theme.

### Expected Behavior
15px gap between each other for iOS theme.

### Actual Behavior
No gap. And css style **@media (min-width: 768px) .ios .row .tablet-33** does not contain -webkit-calc property.

**Comment by nolimits4web** [comment]
iOS doesn’t require -webkit- prefix for calc prop since iOS 7, so it is not actual to have it there

**Comment by nolimits4web** [comment]
Here is screenshot from iOS 11.4

![9597ba11-cd03-46ca-9c06-cde526983ebc](https://user-images.githubusercontent.com/999588/40874451-0c915954-6678-11e8-9745-52062182aea1.png)

**Comment by achubutkin** [comment]
Yes, it is. It is very strange. In Safari it works. I will do some experiments with WKWebView. Maybe, this is my mistake.

**Comment by achubutkin** [comment]
I'm sorry, this is my mistake. I put all the columns (col) in one container (row) for continuous filling with tiles.

**Comment by achubutkin** [comment]
When I added .ios .row .tablet-33 { width: -webkit-calc((100% - 15px*2)/ 3); } continuous filling works.
