### ISSUE TITLE
Routable Tabs on back lose the original position

### ISSUE THREAD

**Issue by KELINGYANG** [framework7io/framework7#2419]
* [x] bug
* Framework7 Version: v2.3.1
* Platform and Target: Chrome

### What you did

'tab-1' go to 'details'
'details' go back 'tab-1'

### Expected Behavior

back to 'tab-1' original position

### Actual Behavior

back to 'tab-1' top position

![ezgif-2-293ed3b1be](https://user-images.githubusercontent.com/34928087/40968261-b8a7eb9c-68e7-11e8-9f34-6d5bbc5dfef7.gif)

**Comment by nolimits4web** [comment]
Can't replicate this. Do you have more details? Or better live example?
