### ISSUE TITLE
[V2] Autocomplete problem when dropdown item with double quote

### ISSUE THREAD

**Issue by robinyip** [framework7io/framework7#2423]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.5
* Platform and Target: All

### What you did
Dropdown item with double quote

### Expected Behavior
Should work properly

### Actual Behavior
The value parameter in “change” event will be "undefined" when that item is selected

**Comment by nolimits4web** [comment]
Fixed by #2424
