### ISSUE TITLE
swipeoutDelete v2

### ISSUE THREAD

**Issue by tmwebs** [framework7io/framework7#2425]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.3.0
* Platform and Target:  IOS and ANDROID

### What you did

I am migrating from v1 to v2 an APP, and in v1 the following worked for me:
<pre>
$$('.borrar').click(function (e) {
     var clicked = $$(this);
     myApp.swipeoutDelete(clicked.parents('.swipeout'));
})
</pre>
to force the removal of the item, in v2 does not work: 

<pre>
$$('.borrar').click(function (e) {
     var clicked = $$(this);
     app.swipeoutDelete(clicked.parents('.swipeout'));
})
</pre>

in the documentation I do not see that it has changed swipeoutDelete. Thanks you

**Comment by nolimits4web** [comment]
http://framework7.io/docs/swipeout.html#swipeout-app-methods

**Comment by tmwebs** [comment]
Thanks you, 
It works but not as I would like, so it works for me:

<pre>
$$('.borrar').click(function (e) {
    var clicked = $$(this);
    app.swipeout.delete(clicked.parents('.swipeout'), function(){
         app.dialog.alert('eliminado')
     });
});
</pre>

but that's not how it works

<pre>
$$('.borrar').click(function (e) {
   var clicked = $$(this);
    
   app.request.get(
      "url",
      {
         funct: 'delete-item'
       }, function (data){
          jsonp = JSON.parse(data);
          if (jsonp.result == 'DONE'){
               app.swipeout.delete(clicked.parents('.swipeout'), function(){
                    app.dialog.alert('eliminado')
               });
          }
     });
});
</pre>
