### ISSUE TITLE
Load external html with javascript routes api

### ISSUE THREAD

**Issue by vikksr** [framework7io/framework7#2428]
Firstly, before anything else, I would like to thank you for the great framework and the associated libraries.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Framework7 version 2.3.1
* Platform and Target: Phonegap for Android

### What you did
```javascript
var myApp = new Framework7();

mainView    =  myApp.views.create('.view-main', {
  on: {
    pageInit: function () {
      myApp.router.navigate("https://www.services_side_html.com");
    }
  }
})
```

### Expected Behavior
When the app starts, the index.html which is bundled with the phonegap app loads initializing the framework7 view, after initializing load the server rendered html which has all the framework7 classes and functionality builtin already.

### Actual Behavior
I'm getting 404 error, which is from the catch all route.
My routes file:
``` javascript
var routes = [
  {
    path: '/',
    url: './index.html',
    name: 'home',
  },
  // Default route (404 page). MUST BE THE LAST
  {
    path: '(.*)',
    url: 'https://www.alusouq.com',
  },
];

```
I've changed the routes path to absolute url, but still getting 404 page load. How do i fix this??
Thanks for the taking the time to check on this. 👍

**Comment by nolimits4web** [comment]
What are you trying to load with `myApp.request.navigate("https://www.services_side_html.com");`?

There is no such API methods, did you mean `myApp.router.navigate`?

> still getting 404 page load

Do you have it for home page?

**Comment by vikksr** [comment]
Oops, sorry...my bad..I am actually using 

> myApp.router.navigate("https://www.services_side_html.com");

**Comment by nolimits4web** [comment]
According to your routes it will load page from `https://www.alusouq.com`. You need to specify it in route like:
```
path: '/some-page/',
url: `https://www.services_side_html.com`
```
and then load it as `mainView.router.navigate('/some-page/')`

**Comment by vikksr** [comment]
Changed my routes file to:
```javascript
var routes = [
  {
    path: '/somepage/',
    url: 'https://www.services_side_html.com',
  },
  {
    path: '/',
    url: './index.html',
    name: 'home',
  },
  // Default route (404 page). MUST BE THE LAST
  {
    path: '(.*)',
    url: './pages/404.html',
  },

];
```
I tried this in console using chrome USB debugger.
```javascript
mainView.router.navigate("/somepage/");
```
OUTPUT:
```javascript
Router {params: {…}, eventsParents: Array(1), eventsListeners: {…}, isAppRouter: false, app: Framework7, …} framework7.js:3757 
GET https://services_side_html.com/ 404 (Not Found)
```

**Comment by nolimits4web** [comment]
> GET https://services_side_html.com/ 404 (Not Found)

Because there is no such page, put there required URL to load

**Comment by vikksr** [comment]
Oh..i tried it with `https://www.google.com` as well, but still getting
> GET https://www.google.com/ 404 (Not Found)

**Comment by nolimits4web** [comment]
Then issues is somewhere on your side or in your environment

**Comment by vikksr** [comment]
oh!  Yup...I was missing cordova-plugin-whitelist from the phonegap config.xml.
```
<allow-navigation href="http://*/*" />
<allow-navigation href="https://*/*" />
```
It's working perfectly fine now...
Really thanks for helping me with this 👍
