### ISSUE TITLE
Split Views standard available 

### ISSUE THREAD

**Issue by gpetrov** [framework7io/framework7#243]
Hi Vlad,

I know you have a split view app in demos, done with custom css, but split views are really an integral part of IOS design, so maybe you can make them standard available, like the left and right panels and popups you already have.

It will be nice to be able to make them with ready to go css classes and also have them responsive, so for example the left panel gets hidden when there is no room and the panels become single cascading panels, like the settings on IOS.

Thanks,
   George

**Comment by gpetrov** [comment]
Was split-view functionality already implemented? As we are now at 1.0.6

Will be also nice if it can be combined with a drop down list. For example if there is room left panel is displayed but if not it becomes available under drop down button

**Comment by ZanderBrown** [comment]
It would seem this feature never really made it but is still a valid request

**Comment by ZanderBrown** [comment]
Ping @nolimits4web

**Comment by nolimits4web** [comment]
@ZanderBrown was trying to implement it but without much success as it relies heavily on custom app layout. So delayed until have more time to dig into it

**Comment by nolimits4web** [comment]
Closing as it is done in v4
