### ISSUE TITLE
Navbar disappearing after using input or textarea (focus out)

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2433]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V2
* Platform and Target: IOS

I noticed when you leave an input field, navbar is disappearing. whenever the action is swipe or clicking 'done' in the ios native's keyboard. 

Live preview:
![cohqntvornieh0cnrn](https://user-images.githubusercontent.com/14131170/41392133-57ad30f4-6fd1-11e8-8303-9136432aa58e.gif)

**Comment by nolimits4web** [comment]
Looks like iOS rendering issue. I can recommend you to use some of cordova keyboard plugins to handle such issues correctly

**Comment by pluckannfeel** [comment]
i would love to. thanks in advance sir!

**Comment by pluckannfeel** [comment]
sir?

**Comment by nolimits4web** [comment]
https://github.com/cjpearson/cordova-plugin-keyboard

**Comment by pluckannfeel** [comment]
hello @nolimits4web with this keyboard plugin, what exactly am i looking to resolve the rendering issue?

**Comment by pluckannfeel** [comment]
how can this be resolved while there's no solution?
