### ISSUE TITLE
links are triggered while swiping over them

### ISSUE THREAD

**Issue by dorad007** [framework7io/framework7#2434]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.5
* Platform and Target: any.
* Live Link or JSFiddle: https://jsfiddle.net/fdty08uj/

### What you did
Placed links in a slide of a swiper.

### Expected Behavior
While swiping over links, they shouldn't be triggered.

### Actual Behavior
While swiping over links, their action (navigation) is triggered

**Comment by nolimits4web** [comment]
You need to disable `touchMoveStopPropagation` for swiper https://jsfiddle.net/zjt0pdma/

**Comment by dorad007** [comment]
Hello,
Thanks for your comment.
I didn't notice that in my case it's about swipeable tabs.
opened [new issue](https://github.com/framework7io/framework7/issues/2436).
