### ISSUE TITLE
links in swipeable tabs are triggered while swiping over them

### ISSUE THREAD

**Issue by dorad007** [framework7io/framework7#2436]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.5
* Platform and Target: any.
* Live Link or https://jsfiddle.net/g4oy18ep/1/

### What you did
Placed links in a tab of a swipeable tab.

### Expected Behavior
While swiping over links, they shouldn't be triggered.

### Actual Behavior
While swiping over links, their action (navigation) is triggered

**Comment by nolimits4web** [comment]
They use Swiper so fix is the same
```
<div class="tabs-swipeable-wrap" data-touch-move-stop-propagation="false" ...
```

**Comment by dorad007** [comment]
Thanks man.
