### ISSUE TITLE
v3.0.0-beta.8  Autocomplete fails on render

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#2437]
Hi Vladimir, I've download the files from github, in Vainilla JS, when you use autocomplete and type something, the render functions fail.

framework7.js:29449 Uncaught TypeError: e.value.replace is not a function
    at t.renderItem (framework7.js:29449)
    at framework7.js:29111
    at <anonymous>:225:49
    at Object.callback_onsuccess [as success] (helpers.js:493)
    at r (framework7.js:3563)
    at XMLHttpRequest.Request.f.onload (framework7.js:3742)
t.renderItem @ framework7.js:29449
(anonymous) @ framework7.js:29111
(anonymous) @ VM3588:225
callback_onsuccess @ helpers.js:493
r @ framework7.js:3563
Request.f.onload @ framework7.js:3742
load (async)
Request @ framework7.js:3724
RequestShortcut @ framework7.js:3822
Request.post @ framework7.js:3834
call @ helpers.js:573
busqueda_rapida @ productos.js:477
source @ VM3588:209
u @ framework7.js:29092
l @ framework7.js:1078

Is something with this version, because the latest stable I've download 2.3.1 has no problems with the same code.

**Comment by nolimits4web** [comment]
Hi, update to latest beta, was fixed there
