### ISSUE TITLE
[v3] Bug when scroll on choices of autocomplete

### ISSUE THREAD

**Issue by SpiderNeo1** [framework7io/framework7#2438]
This is a :
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v3.0.0-beta.10
* Platform and Target: 
  Cordova with WKWebView : 
   - iOS 9.3.2 on physical device 
   - Simulator 5S iOS 9.0 with XCode 9.2 

### What you did
Copy of the kitchen-sink directory without any modification.
On the module " On the module "autocomplete" impossible to scroll on the choices.

### Video to explain the problem
https://www.dropbox.com/s/pmj1w27vgujteyy/autocomplete_bug.mov

**Comment by nolimits4web** [comment]
You need to use cordova keyboard plugin and set enable shrinkView, otherwise it is not possible to detect keyboard height to make dropdown smaller

**Comment by SpiderNeo1** [comment]
This plugin ?
https://github.com/cjpearson/cordova-plugin-keyboard

**Comment by SpiderNeo1** [comment]
Vladimir, 

I tested that but it did not work :

```
> document.addEventListener("deviceready", function() { 
> 	Keyboard.shrinkView(true);
> 	Keyboard.disableScrollingInShrinkView(true);
> });
```
