### ISSUE TITLE
Multiple Pages in a single file

### ISSUE THREAD

**Issue by gpetrov** [framework7io/framework7#244]
The current structure for loading pages from different files with Ajax is all great, but sometimes you need just a few pages that are in the same file.

Is it possible to have structures like this:

```
.views
  .view
     .pages
        .page data-page=index
            .page-content:
                a src=#other_index
        .page data-page=other_index
            .page-content
```

So that we can have multiple pages that can be switched with a simple link pointing to the other page data-page attribute

Or are there other ways to achieve this?

**Comment by guylando** [comment]
It would be very helpful if you have put here a link to the relevant explanation in the docs. From what I see now in 2017 it is still not possible to load via ajax content which has multiple pages.
