### ISSUE TITLE
Transpile node modules to es5

### ISSUE THREAD

**Issue by burtontanner** [framework7io/framework7#2442]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 3.0.0-beta.9
* Platform and Target: WEB

While trying to run framework7-react(3.0.0-beta.9) inside a create-react-app based project, the project works fine with local development (npm run start). But when you try to build a production version, it is not converting the html correctly. This appears to be because of the version of react-scripts(2.0.0-next.66cc7a90). However, when I down grade to the latest stable version (^1.1.4), it complains that many of the modules in framework7 and framework7-react are es6, not es5. Facebook suggests that all node modules be converted to es5 for the next few years http://bit.ly/2tRViJ9. 

To recreate this clone git@github.com:framework7io/framework7-react-app-template.git and check out the v3 branch. Cd into the project and run "npm run start". In another terminal, run "npm run build". Open this file in your browser "file:///path/to/index.html". In another browser, open "localhost:3000". You will be able to see the differences between the builds. Now remove react-scripts "npm uninstall react-scripts", and install a stable version "npm install react-scripts". npm run build will no longer work due to es6 modules. 

Thanks in advance for all the work you do!

**Comment by nolimits4web** [comment]
@bencompton is it possible to run transpiler on project build?

**Comment by GimpMaster** [comment]
@nolimits4web It would be awesome to figure this out. Like @burtontanner says the framework7-react-app-template produces different output when building or when debugging. 

Seems like a lot of styles are missing with the build version. I know @bencompton has a lot of stuff going on but it would be cool if the build was the same.

**Comment by burtontanner** [comment]
I added this to the package.json and it seems to work in development. Im not sure how to build it for production though. I hope this helps.
```javascript
 {"scripts":{   "es6toes5": "babel packages/react --presets babel-preset-es2015 --plugins transform-class-properties --out-dir packages/react"
}
}
```

**Comment by burtontanner** [comment]
I have created a pull request for you to see this in the project. https://github.com/framework7io/framework7/pull/2455

**Comment by nolimits4web** [comment]
Guys, is it still actual? Final release of this template https://github.com/framework7io/framework7-template-react works good, including production build. 

I don't like the idea of transpiling everything to es5, because it will highly reduce tree-shaking in bundlers. As an option i can generate addional `esm.legacy` version of f7, f7-react packages where i can proceed all imports (bundle) and transpile to es5

**Comment by burtontanner** [comment]
@nolimits4web Every thing works great now. Originally I thought react-scripts (2.0.0-next.66cc7a90) was the cause for having production builds render differently. v3.0.0-beta.15 fixed the issue and react-scripts (2.0.0-next.66cc7a90) works great.

**Comment by nolimits4web** [comment]
Ok, great. Then i guess we can close it

**Comment by burtontanner** [comment]
@nolimits4web @bencompton I am having an issue with testing. I would like to run "yarn test" and have it run all of my test files but I am getting this error "Unexpected token export" for 'framework7-react/utils/utils'. I believe jest expects node modules to be in es5. I have tried to find a way for babel to transpile them during testing but haven't had success. Do you have any suggestions?

**Comment by bencompton** [comment]
@burtontanner - you may have to configure Jest to [use Babel](https://github.com/facebook/jest/tree/master/packages/babel-jest).

**Comment by burtontanner** [comment]
@bencompton I have tried get babel to transform framework7-react but havent had any luck. Have you been able to get this to work in any of your tests?

**Comment by burtontanner** [comment]
@bencompton when babel seems to be working correctly, everything imported from framework 7 gets imported as undefined.
``` 
    TypeError: Cannot set property 'propTypes' of undefined

      3 | import Mixins from 'framework7-react/utils/mixins';
      4 | 
    > 5 | __reactComponentSetProps(NavTitle, Object.assign({
      6 |   id: [String, Number],
      7 |   title: [Array, String],
      8 |   subtitle: String,

      ```
