### ISSUE TITLE
[v3] Checkbox / Toggle onChange not working (React)

### ISSUE THREAD

**Issue by kyleroberthammond** [framework7io/framework7#2445]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v3 Beta 11
* Platform and Target: Web (React)

Can someone confirm that im not doing something stuipd?

Example Code
`export class ToggleReduxForm extends Component {
  constructor(props) {
    super(props);
  }

  onChange(){
    console.log("changed")
  }

  onClick(){
    console.log("clicked")
  }

  render() {
    return (
      <div>
        <Toggle name="test" onChange={this.onChange} onClick={this.onClick}></Toggle>
      </div>
    );
  }
}`

**Comment by nolimits4web** [comment]
Use `onToggleChange` event instead

**Comment by kyleroberthammond** [comment]
Thank you! Just need to read the docs eh!
Will become a pateron on soon! Thanks for the great work!
