### ISSUE TITLE
clicking checkbox while calendar or datepicker is opening will cause closing of page

### ISSUE THREAD

**Issue by wxfred** [framework7io/framework7#2448]
This is a:
* [x] bug

* Framework7 Version: 2.3.1.
* JSFiddle: https://jsfiddle.net/wxfred/564xgpt7/

### What you did
In my example of JSFiddle, i wrote a form page with a checkbox and a calendar input. 
1. click "Form" in the navigation list of the home page
2. open the calendar, ensure the width of the screen is small like a mobile device, so the calendar will display in sheet mode without modal mask
3. click on the checkbox

### Expected Behavior
Calendar will close, checkbox will be toggled.

### Actual Behavior
Current form page is closed and navigate back to the home page.

ps: datepicker also have the same problem, maybe all the modeless window will conflict with checkbox.

**Comment by nolimits4web** [comment]
Looks like it is fixed in v3 as i can't replicate it. But anyway you can disable its `routableModals` parameter to fix it https://jsfiddle.net/u8dvbLcg/

**Comment by wxfred** [comment]
@nolimits4web Really appreciate, it works.
