### ISSUE TITLE
Can't make my app go back a page in the stack on an android phone

### ISSUE THREAD

**Issue by shaulhadar** [framework7io/framework7#245]
Hi, first of all, this is a great framework man! Good job :)

I am trying to add the back button on android, so when you press on a link to a page that's being added to the stack, when you press the back button in android, it will pop the last page that was before...

Is there any method to do that? or is this for the wishlist?

Thanks...

**Comment by ZanderBrown** [comment]
@shaulhadar, @valnub & @nolimits4web any reason to keep this open? Seems @shaulhadar found a fix thats isnt suitable for inclusion in f7 and as the issue was opened almost 3 years ago i think its safe to assume its resolved

**Comment by valnub** [comment]
Vladi sometimes likes to keep tickets open as a "todo".

I think he knows best if this can be closed or not.

**Comment by iamsudharshan** [comment]
Hi @nolimits4web ,

I am using 3 tab-based layout, each tab has many pages after opening all pages and going back its showing first tab instead respective tab. Do we have any way to fix it.

**Comment by sjkushwaha21** [comment]
Hello guys i am new here, writing for the first time but i guess this code will resolve all the issue related to android back button for Popup, modal, side panel and page back. Have a look at the code.

/* Device Ready Funtion */
function onDeviceReady() {
    document.addEventListener("backbutton", onBackKeyDown, false);
}

function onBackKeyDown() {
    var cpage = mainView.activePage;
    var cpagename = cpage.name;
    console.log(cpagename);
    if (($$('#left_panel').hasClass("active")) || ($$('#right_panel').hasClass("active"))) { // #left_panel and #right_panel are id of both panels.
        myApp.closePanel();
        return false;
    } else if ($$('.modal-in').length > 0) {
        myApp.closeModal();
        return false;
    } else if (cpagename == "index") {
        myApp.confirm("Are you sure you want to exit?", function() {
                // var deviceType = device.platform;
                // if(deviceType == "Android" || deviceType == "android"){
                navigator.app.exitApp();
                // }
            },
            function() {

            });
    } else {
        mainView.router.back();
    }
}

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
