### ISSUE TITLE
[v2] BUG css:  ptr-preloader hidden in Subnavbar -> Searchbar 

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#2453]
Actually if I had a page with a subnavbar, and a searchbar then, the  ptr-preloader  is hidden behind the searchbar.

![ptr](https://user-images.githubusercontent.com/12813221/41818608-c7357b3e-7788-11e8-8871-02cb1c7e92ec.png)

This class: 
```
.md .page-with-subnavbar .ptr-preloader, .md .searchbar~.ptr-content .ptr-preloader, .md .toolbar:not(.toolbar-bottom-md)~.ptr-content .ptr-preloader {
    top: 64px;
}
```
Should be:

```
.md .page-with-subnavbar .ptr-preloader, .md .searchbar~.ptr-content .ptr-preloader, .md .toolbar:not(.toolbar-bottom-md)~.ptr-content .ptr-preloader {
    top: 120px;
}

```

**Comment by nolimits4web** [comment]
Why closed? Issue was on your side?

**Comment by vousys** [comment]
Moving the top didn't fix the issue, because ptr-preloader is visible all the time. It should appears only when I pull down.  

![image](https://user-images.githubusercontent.com/12813221/42049169-8cef59c6-7adb-11e8-8b40-b7f6f14e8ed7.png)

**Comment by nolimits4web** [comment]
Bit it looks right on your first screenshot, it should be hidden behind subnavbar/searchbar, and become visible when you pull your page down

**Comment by vousys** [comment]
Yes, that's why I close it. Thanks for your support!
