### ISSUE TITLE
[V3]Development vs production builds are not rendering the same

### ISSUE THREAD

**Issue by burtontanner** [framework7io/framework7#2459]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: ^3.0.0-beta.14
* Platform and Target: WEB(framework7-react)

### What you did
git clone git@github.com:framework7io/framework7-react-app-template.git.
Compare "yarn start" with "yarn build" in two different browser windows. I have taken screen shots of the "Navigation list" and the html differences.

### Expected Behavior
dev and production should look the same

### Actual Behavior
some html is formatted differently.

![screen shot 2018-06-26 at 1 56 16 pm](https://user-images.githubusercontent.com/10554651/41936272-ea711a82-7949-11e8-9fed-d6a53a3583a8.png)
![screen shot 2018-06-26 at 1 57 01 pm](https://user-images.githubusercontent.com/10554651/41936274-eab0f8a0-7949-11e8-9335-4ac164131cc9.png)
![screen shot 2018-06-26 at 1 56 26 pm](https://user-images.githubusercontent.com/10554651/41936273-ea92c2ae-7949-11e8-8b1b-b9da2348fd04.png)
![screen shot 2018-06-26 at 1 57 28 pm](https://user-images.githubusercontent.com/10554651/41936275-ead01c1c-7949-11e8-9bf2-b394ae064db1.png)

**Comment by nolimits4web** [comment]
Should be fixed now in beta 15
