### ISSUE TITLE
iOS Freeze Issue

### ISSUE THREAD

**Issue by mervekara** [framework7io/framework7#2465]
Hi @nolimits4web,

I use 1.4.2 version of the framework7. I had freeze issue. I changed it with a patch like yours [https://github.com/framework7io/framework7/commit/ac02ad1514f53ddd47a663f281104049ae59cb52](https://github.com/framework7io/framework7/commit/ac02ad1514f53ddd47a663f281104049ae59cb52)
`                if ((touchStartTime - lastClickTime) < app.params.fastClicksDelayBetweenClicks) {
                    e.preventDefault();
                }
`
`                if ((touchEndTime - lastClickTime) < app.params.fastClicksDelayBetweenClicks) {
                    setTimeout(removeActive, 0);
                    return true;
                }
`
`        
                lastClickTime = touchEndTime;`

But Users still see the freeze issue. You can help me, please.

**Comment by nolimits4web** [comment]
Sorry, but v1 is not maintained anymore, update to latest v1 or v2/3

**Comment by u01jmg3** [comment]
@mervekara: did you solve your issue?

**Comment by mervekara** [comment]
@u01jmg3 No. I have this problem.
