### ISSUE TITLE
iPhoneX MD theme [V1]

### ISSUE THREAD

**Issue by mishkeTz** [framework7io/framework7#2466]
This is a (multiple allowed):
* [ ] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.6.5 

### What you did
Used MD theme for iOS devices

### Expected Behavior
To have a space around notch/status bar and the indicator for accessing the Home screen

### Actual Behavior
Space around safe area not being added

Could the same thing be done for V1
https://github.com/framework7io/framework7/issues/1989

**Comment by nolimits4web** [comment]
Sorry, v1 is not maintained anymore, update to v2/3 or add required css fixes to your custom CSS
