### ISSUE TITLE
[V3] Imported List Item not rendering in parent List (React)

### ISSUE THREAD

**Issue by kyleroberthammond** [framework7io/framework7#2470]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v3 Beta 15
* Platform and Target: Web (React)
I have made a repo for this issue
https://github.com/kyleroberthammond/blankf7app
yarn start

```
const AImportedListItem = (props) => {
  return (
    <ListItem>
      Seems to be missing being included in the ul of the list
    </ListItem>
  )
}


const Home = (props) => {
  return (
      <Page>
        <BlockTitle>A framework7 app</BlockTitle>
        <List>
          <ListItem>
            No problems here
          </ListItem>
          <AImportedListItem/>
        </List>
      </Page>
  )
}
```

The AImportedListItem isn't rendered inside the Parent List.

Apologies if this is a stuipd question. Is this expected behavior?

**Comment by nolimits4web** [comment]
Because in this case (with custom component) it can't detect that it is a `<li>` element, just specify slot:
```js
<AImportedListItem slot="list"/>
```

**Comment by kyleroberthammond** [comment]
Thanks again. Have joined as a patreon so will ask in discord next time! Before submitting a issue.

**Comment by nolimits4web** [comment]
No problem, thanks for supporting!
