### ISSUE TITLE
[V3] className on Navbar ignored

### ISSUE THREAD

**Issue by burtontanner** [framework7io/framework7#2479]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version:    "framework7-react": "^3.0.0-beta.15",    "framework7": "^3.0.0-beta.15",

* Platform and Target: WEB

### What you did
put a className on a navbar that was inside a page component.
```javascript
<Page>
    <Navbar className="test-class" title="test"/>
</Page>
```

### Expected Behavior
"test-class" would be added to navbar-inner so that I could give this navbar some custom styles.

### Actual Behavior
"test-class" was ignored.

It seems like this could be low hanging fruit.

**Comment by nolimits4web** [comment]
iOS theme with dynamic navbar? check the #2475 and #2474

**Comment by burtontanner** [comment]
Yes both iOS theme and dynamic navbar. @nolimits4web thanks for the help. I ended up inheriting navbar and changing one line.
```
81             className: Utils.classNames('navbar-inner', {
```
now looks like this

```
81              className: Utils.classNames(className, 'navbar-inner', {
```

for this to work I also had to put an empty navbar inside my view component.

```
<View>
    <Navbar></Navbar>
    <Page>
        <Navbar className="test-class" title="test"/> 
     </Page>
</view>
```
