### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by jonorozcoc** [framework7io/framework7#2482]
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

**Comment by J05HI** [comment]
@jonorozcoc
You should open this issue in the Pheromone repository

**Comment by mblackritter** [comment]
@J05HI, can you detail what you're referencing by "Pheromone"? I couldn't find anything related.

**Comment by nolimits4web** [comment]
@mblackritter i believe he meant Phenome https://github.com/phenomejs/phenome

**Comment by mblackritter** [comment]
@nolimits4web, thanks, I wasn't aware of the latest developments. Just read the [article introducing Phenome](https://blog.framework7.io/framework7-v3-is-coming-soon-e327e9c10480). That's all very thrilling and I would bet on amazing times ahead for f7, which finally is well and long deserved.

**Comment by J05HI** [comment]
@nolimits4web
Oh yeah, thanks for the correction :)
