### ISSUE TITLE
Needs clear installation instruction

### ISSUE THREAD

**Issue by arjunmenon** [framework7io/framework7#2484]
Hey
The documentation is confusing.
There are so many files in the zip, it is not at all clear what all need to be required for a bare-bones pure js setup?
I am on cordova and it is taking many blog posts to figure out just the installation part and worse all of them are for old versions. And I am still not confident to proceed. I cant find anything anywhere nor in your own site.

Please add proper instructions for mobile or atleast the category you deem this project is targeted for.

**Comment by nolimits4web** [comment]
http://framework7.io/docs/installation.html

> From the downloaded Core package we will need files from css and js folders

Otherwise you just start from ready template  https://github.com/framework7io/framework7-template-single-view
