### ISSUE TITLE
Handling Failing xhr requests. Bug?

### ISSUE THREAD

**Issue by manish2535** [framework7io/framework7#2485]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.5.16.
* Platform and Target: CORDOVA, IOS, ANDROID.
* Live Link or JSFiddle: https://jsfiddle.net/90ot5hz7/11/

### What you did
I have a case where sometimes my server is down and when the app tries to make the call, the app just errors out. I would expect the ajax call to land in the ERROR function block where I can handle it properly but this does not happen. 
1. Open the Fiddle, (have the debugger open)
2. Click on the About Menu. You will see instead of going to the AJAX call's Error block, it just throws a error. 
`Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www..com/'`

Am I doing something wrong here? 

### Expected Behavior
If a ajax request fails for any reason, it should go into the ERROR  block.

### Actual Behavior
It just errors out which can be seen in the console log and never goes into the Ajax call's ERROR block like the documentation says.

**Comment by nolimits4web** [comment]
Never use `async: false`, set it to `true` and it will work as expected

**Comment by manish2535** [comment]
Thabks for the quick reply. I am using the Async false for some of my calls
because i want them to work synchronously. Shouldn't this work even for
synchronous calls?

**Comment by nolimits4web** [comment]
> Shouldn't this work even for synchronous calls?

No, it won't work in this case. Use `try/catch` in this case. But it is a very bad practise to use sync requets

**Comment by manish2535** [comment]
Ok gotch ya. Thanks.
