### ISSUE TITLE
Split view links behave strangely with tab bar setup

### ISSUE THREAD

**Issue by arjunmenon** [framework7io/framework7#2488]
Hey

The [split view](https://framework7io.github.io/framework7-template-split-view/) template merged with the [tabbar template](https://framework7io.github.io/framework7-template-tabs/) does not work.
Instead all split view links end up opening in the first tab only.
Even if I open the left panel from a different tab, click a link, the split view still opens in the first tab

Demo link - https://jsfiddle.net/L5skgrdv/9/

- If you open the left panel and click About, the view opens in the first tab, Home Page

The link does not open over all the tabs like in the split-view demo link above

- If you navigate to any other tab, open the left panel and click About, the view still opens in the first tab. This is an issue.

What I am trying to do is, just want to open any links in the panel over all the tabs, like a preferences page

In the JSfiddle link, the split view link opens only and only under the first tab, not over all the tabs and views, masking it.

EDIT - 
I am using Framework7 Version 2 on cordova

**Comment by nolimits4web** [comment]
This is by design, you have configured to open links in side panel in main view `data-view=".vew-main"`. Page can not be opened over other views. Page can be opened only in View

**Comment by arjunmenon** [comment]
1. There is also an issue that if the side panel link is open from different tabs, side panel link only and only opens in the first tab. Why is that?

    If I am on another tab and open the menu, I would expect to see the side panel page in the same tab. But instead I have to go back to the first tab to see it. This is unexpected while using the app.




2. > This is by design. .... Page can not be opened over other views. Page can be opened only in View

     In Android or iOS apps, that is not the default behaviour. If we are opening a link in the side panel, it opens up a separate view.
I did try to change `data-view=".vew-main"` to other containers but that doesn't work either.
