### ISSUE TITLE
stackPages: true, uniqueHistory: true, allowDuplicateUrls: false - not working as expected

### ISSUE THREAD

**Issue by AliMamed** [framework7io/framework7#2492]
* Framework7 version: [3.0.0]
* React.js version: [e.g. 16.4.1]
* Platform and Target: [all]
* Live Link or JSFiddle: update kitchen-sink to above parameters in main view

### Describe the bug
If you navigate to same pages without pressing back and within view that has `stackPages: true, uniqueHistory: true, allowDuplicateUrls: false` you still get duplicated pages in dom each time you navigate forward

### To Reproduce
Add above parameters to kitchen-sink. navigate to same pages without pressing back button (f.e. using side menu)

### Expected behavior
Pages should not duplicate

### Actual Behavior
New pages added to DOM each time you navigate

### Screenshots
<img width="487" alt="2018-07-09 23 50 42" src="https://user-images.githubusercontent.com/19426160/42475438-5164ed34-83d3-11e8-9095-35d0fbd66a27.png">

**Comment by nolimits4web** [comment]
What is in your routes? What is your main view initial HTML/JSX layout?

**Comment by AliMamed** [comment]
I just used kitchen-sink/react code for this example. The only change was in `src/app.jsx` Line 19
```
      <View url="/" main className="ios-edges" stackPages uniqueHistory />
```

**Comment by nolimits4web** [comment]
I see, then everything is correct, `stackPages` means that it will keep previous pages in DOM when you navigate forward, and remove them only when you navigate back from them

**Comment by AliMamed** [comment]
What should be my approach to prevent duplication of pages in DOM if I have link to previously (in history) rendered and now stacked page?

**Comment by Tarekajaj** [comment]
uniqueHistory & uniqueHistoryIgnoreGetParameters does not seem to work,
It seems they are only initialized but never used
see [here](https://github.com/framework7io/framework7/search?utf8=%E2%9C%93&q=uniqueHistory&type=)
