### ISSUE TITLE
Unexpected token: punc ()) [./node_modules/framework7/modules/router/process-route-queue.js

### ISSUE THREAD

**Issue by ferdiaddawy** [framework7io/framework7#2495]
I found this problem when running npm run build command (Framework7 Vue V3)

ERROR in js/app.4c5fea0ba04abaf.js from UglifyJs
Unexpected token: punc ()) [./node_modules/framework7/modules/router/process-route-queue.js:57,0][js/app.4c5fea0ba04abaf.js:20094,6]

please help me to solve this problem..

**Comment by nolimits4web** [comment]
Make sure you transpile your code to ES5 (with Babel or Buble) before uglifying it
