### ISSUE TITLE
no-toolbar class on views initial page does not work

### ISSUE THREAD

**Issue by ri-gr** [framework7io/framework7#2496]
hi folks

think this is a bug - folowing scenario:

views with three view elements, first view loads the first page which should hide the toolbar by default since it should act like a landing page.

div.views
 div.view 
  div.page.no-toolbar

toolbar appears despite the class on the page, after navigation into a another page and going back the toolbar is going to be hidden correctly. Tried adding some classes intially on the according elements (toolbar-hidden, hidden-toolbar) but it did not work out.

similar issue #227 

Cheers

**Comment by nolimits4web** [comment]
Please open new issue and don’t ignore issue template fields

**Comment by ri-gr** [comment]
additionaly info - preparing css classes won't help - also initially removing the ' tab-link-active' from the start tab did not work out

**Comment by ri-gr** [comment]
seems as the code is always toggling the toolbar and on init it seems the hide and show function are called multiple times - thats why it will be enabled again 

`if (page.$el.hasClass('no-toolbar')) {
        app.toolbar.hide($toolbarEl);
      } else {
        app.toolbar.show($toolbarEl);
      }`
