### ISSUE TITLE
Unexpected identifier on framework7.esm.bundle.js

### ISSUE THREAD

**Issue by httpiago** [framework7io/framework7#2498]
* Framework7 version: 3.0.1
* React.js version: 16.4.1
* Platform and Target: Google Chrome on Windows

### Describe the bug
I'm trying to use Framework7 in React using NextJS but every time this same error occurs during execution:

![image](https://user-images.githubusercontent.com/3616259/42626892-d46b56bc-85a1-11e8-9260-9ae3af69d1e2.png)

I do not understand I'm following the instructions at http://framework7.io/react/init-app.html but it's not right.

app.js:
![image](https://user-images.githubusercontent.com/3616259/42627492-941b0a06-85a3-11e8-81ae-1e1e86483d06.png)

**Comment by nolimits4web** [comment]
Make sure you run Babel/Buble over the Framework7 package to transpile it to ES5 syntax

**Comment by httpiago** [comment]
Yes, NextJS uses Babel.

@nolimits4web do you have (or are you preparing) a framework7 v3 test project with React? I only found [this](https://github.com/framework7io/framework7-react-app-template) but it's from v1. I tried to reuse it but I can not make it compatible (you even talked on the [blog](https://blog.framework7.io/migration-to-framework7-v3-928a21a1eac9)).

**Comment by nolimits4web** [comment]
Yes, this react template is in progress, you can try v3 branch of it https://github.com/framework7io/framework7-react-app-template/tree/v3

**Comment by httpiago** [comment]
**Resolution of the problem for those who reach this page:** Use the latest version of next (^7.0.0) together with the [@weco/next-plugin-transpile-modules](https://www.npmjs.com/package/@weco/next-plugin-transpile-modules) package to _transpile_ the framwork7 codes because nextjs does not _transpile_ files within the node_modules folder.
