### ISSUE TITLE
[V3] Suggestion for Routable Tabs -  Router.prototype.flattenRoutes

### ISSUE THREAD

**Issue by kleiteimc** [framework7io/framework7#2504]
* Framework7 version: [3.0.0]

### Describe the Enhancement

Routable Tabs cannot be used with "async route property"

By adding one line of code in the Router.protoype.flattenRoutes function at line 8072 (V3.0.0) this feature could be added:

   Router.prototype.flattenRoutes = function flattenRoutes (routes) {
      var this$1 = this;
      if ( routes === void 0 ) routes = this.routes;

      var flattenedRoutes = [];
      routes.forEach(function (route) {
        if ('routes' in route) {
          var mergedPathsRoutes = route.routes.map(function (childRoute) {
            var cRoute = Utils.extend({}, childRoute);
            cRoute.path = (((route.path) + "/" + (cRoute.path))).replace('///', '/').replace('//', '/');
            return cRoute;
          });
          flattenedRoutes = flattenedRoutes.concat(route, this$1.flattenRoutes(mergedPathsRoutes));
        } else if ('tabs' in route && route.tabs) {
          var mergedPathsRoutes$1 = route.tabs.map(function (tabRoute) {
            var tRoute = Utils.extend({}, route, {
              path: (((route.path) + "/" + (tabRoute.path))).replace('///', '/').replace('//', '/'),
              parentPath: route.path,
              tab: tabRoute,
              async: tabRoute.async    <===============  Add this line
            });
            delete tRoute.tabs;
            return tRoute;
          });
          flattenedRoutes = flattenedRoutes.concat(this$1.flattenRoutes(mergedPathsRoutes$1));
        } else {
          flattenedRoutes.push(route);
        }
      });
      return flattenedRoutes;
    };

Thanks,
Kris

**Comment by nolimits4web** [comment]
What do you mean not supported? Tab can be loaded with async, e.g.
```
{
  path: '/tabs-routable/',
  url: './pages/tabs-routable.html',
  tabs: [
    {
      path: '/',
      id: 'tab1',
      async(to, from, resolve) {
        resolve({
          content: '...',
        })
      }
    },
  ]
}
```

**Comment by kleiteimc** [comment]
I just tested your example with Kitchen Sink and confirms it worked.  I am reevaluating what is incorrectly configured in my project that caused the problem.

Sorry for the inconvenience. 
Thanks,
Kris
