### ISSUE TITLE
IPhoneX use UIScrollViewContentInsetAdjustmentNever something show error

### ISSUE THREAD

**Issue by cody-chen-jf** [framework7io/framework7#2511]
* Framework7 version: [3.0.0]
* Framework7-Vue version: [3.0.0]
* Vue.js version: [2.5.16]
* Platform and Target: [iOS 11 iPhoneX]

### Describe the bug
when I run the demo from [framework7-template-vue-webpack] in iPhoneX,
and I use `self.webView.scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever` to handle the status bar show, This is work well, but I found that the panel-left, panel-right, popup can not use after I add `UIScrollViewContentInsetAdjustmentNever`, but in iPhone 6(11.4), it can run well.

Here is my code: 
```
    self.webView =  [[WKWebView alloc] initWithFrame:CGRectMake(0, 0, SCREENWIDTH, SCREENHEIGHT)];
    self.webView.scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever; // error show in iPhoneX(11.4)
    [self.view addSubview: self.webView];

    NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
    NSString *basePath = [NSString stringWithFormat: @"%@/www", bundlePath];
    NSURL *baseUrl = [NSURL fileURLWithPath: basePath isDirectory: YES];
    NSLog(@"%@", baseUrl);
    NSString *indexPath = [NSString stringWithFormat: @"%@/index.html", basePath];
    NSString *indexContent = [NSString stringWithContentsOfFile: indexPath encoding: NSUTF8StringEncoding error:nil];
    [self.webView loadHTMLString: indexContent baseURL: baseUrl];
```

### To Reproduce
1. Build and run the framework7-template-vue-webpack to xcode.
2. Click 'Left Panel', 'Right Panel', 'Login Screen'...etc.
3. See error

### Expected behavior
Show the 'Left Panel' or 'Right Panel'

### Actual Behavior
Can not show all of them

### Screenshots
<img width="403" alt="2018-07-18 11 06 29" src="https://user-images.githubusercontent.com/18085824/42857047-ada44808-8a7a-11e8-8055-5b3ff10dea37.png">

**Comment by nolimits4web** [comment]
It is designed to work in Cordova environment where it works well, so I guess problem is somewhere on your side, no?
