### ISSUE TITLE
Issue with autocomplete

### ISSUE THREAD

**Issue by owen-mills** [framework7io/framework7#2518]
On all android devices and emulators it seems that the autocomplete element only closes when the user taps away, but not if they hold their finger down to scroll or something. Then the input is unfocused but the autocomplete is still open. It should close on touchstart, not just a tap/click.

**Comment by owen-mills** [comment]
Well it is a simple issue. I didn't think it was necessary.

But here you go

### Expected Behavior
I expected the autocomplete to close when I scrolled through the list below it.

### Actual Behavior
The autocomplete only closes when I click away from it, not on a touchstart like it should.

**Comment by nolimits4web** [comment]
It is designed behavior because page content sometimes may need to be scrolled keeping autocomplete opened. Just add custom touchstart handler and close autocomplete when you need such behavior
