### ISSUE TITLE
[Firefox] double back when using pushState: true

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#2530]
* Framework7 version: [e.g. 3.0.7]
* Platform and Target: [Firefox 61]
* Live Link or JSFiddle: https://jsfiddle.net/o2ejupu1/252/

### Describe the bug
With pushState: true occurs double back when clicking in back button (or calling `router.back`)

The second back is triggered in response to a popstate event (utils/history.js). The check `if stateUrl !== router.url` evaluates to false and a back action is queued 

Interestingly, this issue does not occurs in Chrome. At the popstate event `stateUrl === router.url` evaluates to true and no back action is queued 

### To Reproduce
1. Enable pushState
2. Navigate to two pages. Click back button

In this fiddle:  https://jsfiddle.net/o2ejupu1/252/ go to page 2 or 3 and click back button

### Expected behavior
Should go only one page back

### Actual Behavior
Go to two pages back in history

**Comment by blikblum** [comment]
> Interestingly, this issue does not occurs in Chrome. At the popstate event stateUrl === router.url evaluates to true and no back action is queued

I found that the call to `History.back()` inside backward (router/back.js) triggers the popstate immediately in Firefox but not on chrome, so at this time router.url still points to the previous url 

I see that there's a check postponing the History.back for ie or edge. This would fix firefox but unfortunately, Device does not has a Firefox field

**Comment by nolimits4web** [comment]
Pushed fix, can you check it and confirm it is workin?

**Comment by nolimits4web** [comment]
Pushed better tweak. As from my tests, having same for Safari/Chrome will also break it

**Comment by blikblum** [comment]
It works with Firefox desktop, android and in ipad. Also on chrome

Many thanks
