### ISSUE TITLE
Swipeble tabs issue and request

### ISSUE THREAD

**Issue by Guiladg** [framework7io/framework7#2537]
When you swipe a tab that contains a list with links, the horizontal movement do not stop the propagation as when you scroll, so the link is clicked after tap ends.

When you swipe right the leftmore tab from the very left edge it does not open the side panel as it does normally in Android native apps. It will be usefull.

**Comment by nolimits4web** [comment]
There are few same resolves issues
https://github.com/framework7io/framework7/search?q=touchmovestoppropagation&type=Issues

**Comment by Guiladg** [comment]
Thanks!
