### ISSUE TITLE
Range Slider - Doesn't Support Both Pointer & Touch Events

### ISSUE THREAD

**Issue by UniBrowse** [framework7io/framework7#2540]
Framework7 3.0.7
Windows 10 Desktop Browsers - Chrome & Firefox
Fiddle: https://jsfiddle.net/n0js4q9d/

### Description
The "Range Slider" control seems to be able to handle pointer/touch events in browsers that do not support touch events and browsers that do support touch events but not in browsers that support both touch and pointer events. (e.g. My Windows 10 touch screen notebook). I am guessing that the behavior will only show up when using a touch-enabled desktop device (I have only tested on one "hybrid" laptop and a few normal PCs). I have looked through the JS code and it looks like the "bug" makes sense because you do seem to be branching according to "Support.touch" and then not catering for pointer events.

### Expected behavior
That the Range Slider would listen for both touch and pointer events.

### Actual Behavior
The Range Slider is not listening for both touch and pointer events (but rather supporting only either touch or pointer events).

I hope that makes sense. I have tried to look further into the JS to figure out a fix but have not been able to fully understand the touch event handling yet.

Thanks & Regards

**Comment by dgurza** [comment]
We are also having issues with the lack of this feature for our desktop application. We would much appreciate a solution for this issue

**Comment by nolimits4web** [comment]
What F7 version? In latest version F7 pointer events are used by default where supported

**Comment by dgurza** [comment]
we are using 4.5.2, but I have also tried the slider on the website and it doesn't work with both mouse and touch screens https://framework7.io/vue/range-slider.html

**Comment by dgurza** [comment]
@nolimits4web Any Update for this?

**Comment by smipi1** [comment]
This still doesn't work with the latest. I reported the issue via questions: https://forum.framework7.io/t/range-slider-not-working-in-desktop/10079/8

On May 13, @nolimits4web said he would try to this fix into the next update.

@nolimits4web Any update on this?

**Comment by smipi1** [comment]
Hi @nolimits4web ,

Is there anything I could do to help with this?

**Comment by nolimits4web** [comment]
Fixed with https://github.com/framework7io/framework7/commit/2bd140e6745c9dad09a46766eae4636be2549e1a, also check for workaround here #3648
