### ISSUE TITLE
[V3.1] Searchbar.destroy being called by vnode

### ISSUE THREAD

**Issue by kleiteimc** [framework7io/framework7#2542]
Searchbar.destory appears to being executed by the vnode.

### To Reproduce
Using Kitchen sink on the F7 home page.  Click on "Virtual List" and then click on "back".  In the Chrome debugger the console will display the error message:

Uncaught TypeError: Cannot read property 'trigger' of undefined  framework7.js:23173 

After that error, the "Virtual List" link will not work any more.

Thanks,
Kris

**Comment by divinc** [comment]
I also had the same bug.
How can I fix it?

Always Thanks,
Framework7
