### ISSUE TITLE
Navigate through router module using route.name attribute

### ISSUE THREAD

**Issue by reksc** [framework7io/framework7#2544]
Quite many F7 code examples use url's as hardcoded strings, repeated multiple times across the application. One might say that this is a bad practice for many reasons - from refactoring pain to the risk of mistyping a url string somewhere.

**Describe the solution you'd like**
There is a route.name attribute and it could be used as an url (path) resolver, e.g.

```
{
  name: 'home',
  path: '/home'
}
// ...

router.navigate({ name: 'home' })
// or alternatively
router.navigate({ route: 'home' })
```

**Describe alternatives you've considered**
One of the workarounds is to define url values as constans in a separate file and import it if needed, then reference the desired constant. This feels a bit to complicated when we have a fully blown router module and route definitions. The proposed solution is also quite common in other top frameworks for web-related languages.

**Comment by nolimits4web** [comment]
Makes sense, but what URL must be set if we have such route:
```
{
  name: 'something',
  path: '/something/:param1/:param2/'
}
```
And we navigate to `{ name: 'something' }`?

**Comment by reksc** [comment]
Well, I've been thinking about it too. Considering that currently we don't have a distinction between optional and required parameters, I would say that parameters - if defined - are a required element of a valid, output url.

A strategy where missing parameters would take you to a path trimmed from params can lead to unexpected results, potentially navigating the user to a different context.

My first thought is that it should throw an exception like ``Missing required parameter [name] for path [path_name]``, but I'm not sure if that's very javascript-ish to throw exceptions. That's definitely what you would get from e.g. Symfony (PHP) and quite a few other frameworks.

The other option I would consider least harmful when for some reason an exception wouldn't be in favor is to return an empty string.

The syntax for a correct path generation could look like:

```
router.navigate({ name: 'editUser', params: { id: 3 }})
```

This is how I see it, happy to hear some other opinions.

Thanks for taking the time to consider this.
