### ISSUE TITLE
Use main snabbdom package instead of bundling a copy of it

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#2546]
* Framework7 version: [e.g. 3.1.0]
* Platform and Target: [all]
* Live Link or JSFiddle: --

### Describe the bug
In the latest version F7 is using snabbdom to handle components. 
A copy of snabbdom, added to f7 repository, is used instead of using the main npm package

This incurs in duplicating code for those, like me, that are already using snabbdom in F7 projects even if using the ESM package.

### Expected behavior
Use main snabbdom npm package. The ESM package users will resolve snabbdom from npm. For the bundle build includes snabbdom in the bundle. This is possible using rollup external option

**Comment by nolimits4web** [comment]
That is not an option at the moment as I modified couple of lines in snabbdom source to make it work better with iOS theme dynamic navbar which is detached from vdom tree. If I find a way to make pure snabbdom work with it I’ll use npm package
