### ISSUE TITLE
Use named exports in utils to allow tree shaking

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#2547]
* Framework7 version: [e.g. 3.1.0]
* Platform and Target: [all]

### Describe the bug
Currently the utils modules is exported as default object and used as
```
import Utils from './utils'

Utils.removeDiacritics()
```

. This prevents unused code to be tree shaked.

The most evident is removeDiacritcs functions and its data that is only used in searchbar component. Even if the search bar is not used in the project all diacritcs data is bundled

### Expected behavior
Use named exports and use utils like:
```
import {removeDiacritics} from './utils'

removeDiacritics()
```
I can provide a PR if deems appropriate

**Comment by nolimits4web** [comment]
It is already at `app.utils` http://framework7.io/docs/utils.html#removediacritics, so removing it to separate method could be a breaking change for those who use it

**Comment by ozra** [comment]
Make a "lean version" and a "compat layer" perhaps, for those who rely on the auto-imports?
