### ISSUE TITLE
Autocomplete doesn't handle selection of item on Firefox

### ISSUE THREAD

**Issue by kcarwilemiller** [framework7io/framework7#2549]
* Framework7 version: 3.1.0
* Platform and Target: Windows 10 / Firefox 61.0.1
* Live Link: https://framework7.io/docs/autocomplete.html (Issue is present on demo widget)

### Describe the bug
When you type and autocomplete options are presented as a dropdown, when you select one, the dropdown disappears but the input is not updated with the selection.

### To Reproduce
1. Go to https://framework7.io/docs/autocomplete.html
2. Using Firefox, type "App" in one of the autocomplete demo inputs on the demo widget
3. Select "Apple" from the list. The input value is not updated.

### Expected behavior
When you click an autocomplete result, the form input should update

### Actual Behavior
When you click an autocomplete result, the dropdown disappears but the input is not updated.

### Additional context
I did some troubleshooting on this and it appears that the problem is with the blur event blocking the click event.

https://stackoverflow.com/questions/9335325/blur-event-stops-click-event-from-working

The input with the autocomplete hides the dropdown on its blur event and the click event on the autocomplete item never occurs.

**Comment by nolimits4web** [comment]
Can someone else confirm this? I'm on same FF but on macOS and can't see such issue

**Comment by blikblum** [comment]
Works here
