### ISSUE TITLE
Framework7 Toolbar Tabs Click Jumping

### ISSUE THREAD

**Issue by muhammadadamfirdaus** [framework7io/framework7#2552]
Hello,

Today I found issue when we applied toolbar tabs. `a href` tag seems to be jumping/bounce when clicked. Tab toolbar goes down then up again. Caused by CSS classes `.md .ripple-wave` on `position: absolute !important`

When you add framework7.css is not problem. But I want to get rid those unimportant style because I just need my own style. So, that's happened.

Maybe it'd be best to consider `!important` style to other ways?

Thank you.

**Comment by nolimits4web** [comment]
You can disable that ripple effect in app parameters `touch.materialRipple: false` http://framework7.io/docs/app.html#app-parameters
