### ISSUE TITLE
The title navbar is not center when set the title text on pageAfterIn

### ISSUE THREAD

**Issue by masrodjie** [framework7io/framework7#2557]
* Framework7 version: 3.1.1
* Platform and Target: Mobile Chrome Browser
* Live Link or JSFiddle: https://jsfiddle.net/masrodjie/o2ejupu1/313/

### Describe the bug
When set title navbar on pageInit, the title is center. But when set title navbar on pageAfterIn, the title is not center

### To Reproduce
1. Go to https://jsfiddle.net/masrodjie/o2ejupu1/313/
2. Click on Test Title on pageInit
3. The title is center
4. Click on Test Title on pageAfterIn
5. The title is not center

### Screenshots
[Screenshot](https://content.screencast.com/users/masrodjie/folders/Snagit/media/5c7e51b8-3628-4d67-a5f6-a3da9125f7a4/2018-08-06_15-19-57.png)

**Comment by nolimits4web** [comment]
You need to call `app.navbar.size` method if you change it manually http://framework7.io/docs/navbar.html#navbar-app-methods
