### ISSUE TITLE
Add "more options menu" component

### ISSUE THREAD

**Issue by dorad007** [framework7io/framework7#2558]
**Describe the solution you'd like**
Add a "more options menu" component. look at this [StackOverflow question](https://stackoverflow.com/questions/51695710/is-there-a-more-options-vertical-ellipsis-menu-component-in-framework7).

**Additional context**
![image](https://user-images.githubusercontent.com/5598420/43710452-5f9bb2c4-9978-11e8-812f-c8145b65efb4.png)

**Comment by AliMamed** [comment]
Isn’t it a popover?
