### ISSUE TITLE
Auto init components are not initialized when dynamically show in a router component

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#2559]
* Framework7 version: [e.g. 3.1.1]
* Platform and Target: [Chrome browser]
* Live Link or JSFiddle: https://jsfiddle.net/o2ejupu1/327/

### Describe the bug
When a component (gauge, toggle) is dynamically show in a router component using $setState, the widget is not initialized. This occurs because how snnabdom / vtree diff works, as pointed in this [comment](https://medium.com/@blikblum/thankfully-snabbdom-has-special-hooks-that-allow-us-to-know-when-such-elements-are-inserted-or-f86f452ef859) on recent f7 medium article

### To Reproduce
In the fiddle: https://jsfiddle.net/o2ejupu1/327/, go to about page and click on show gauge, a second gauge should be show

### Expected behavior
The component should be initialized when dynamically  show

### Actual Behavior
The component is not initialized when dynamically show

**Comment by nolimits4web** [comment]
And as you correctly mentioned in your comment to avoid this, they must be "keyed" with `key` or `id` attribute, i will add info about this to docs. Otherwise, checking classes in each vnode update hook can be memory consuming

**Comment by blikblum** [comment]
Should be key. Id will not work

**Comment by nolimits4web** [comment]
@blikblum in F7 `id` also works https://jsfiddle.net/qvn4xred/

**Comment by nolimits4web** [comment]
Updated docs about it http://framework7.io/docs/router-component.html#keys-in-lists-auto-init-components
