### ISSUE TITLE
f7-link does not support specifying css selector in popup-close 

### ISSUE THREAD

**Issue by jamesnw** [framework7io/framework7#2562]
* Framework7 version: 3.1.1
* Vue.js version: 2.5.16
* Platform and Target: iOS/Android/Brower
* Live Link or JSFiddle: https://jsfiddle.net/xsanpcud/1/

### Describe the bug
In an f7-link component, `popup-close` works as expected, but `popup-close="#selector"` does not. 

With the boolean `popup-close` prop, the `a` has the following classes: `link popup-close`, and no `data-popup` (as expected).
With a string `popup-close="#popup"` prop, the `a` has the following class: `link`, and has the attribute `data-popup="#popup"`. Since it is missing the `popup-close` class, it does not close the popup.

### To Reproduce
1. Go to the jsfiddle https://jsfiddle.net/xsanpcud/1/
2. Open the popup
3. Click "Specified" and "Unspecified"

### Expected behavior
Both links should close the popup. 

### Actual Behavior
"Unspecified" closes the popup as expected.
"Specified", where `popup-close="#popup"`, does not close the popup.

### Additional context
It appears this is due to only including the `popup-close` class if the prop is true or empty. https://github.com/framework7io/framework7/blob/master/src/phenome/utils/mixins.js#L210

This likely is also an issue on other close props where it can be a boolean or a string.

**Comment by nolimits4web** [comment]
Good catch, thanks, fixes 👍
