### ISSUE TITLE
[v3] Android - Inputs don't have contextMenu to copy/paste data

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#2567]
I test it on android 7.1 and 8 and I still don’t have the context menu.  On iOS works fine.
 If I navigate throw chrome over android, the pages still don’t show the context menu to copy/paste.

I’ve tried it also with the kitchen sink that’s on framework7.io web: https://framework7.io/docs/kitchen-sink.html and don’t show the contextmenu.

Ex:
No contextmenu (but forced in app initialization with disabledcontextmenu = false )
 
![image](https://user-images.githubusercontent.com/12813221/43911929-215d41e2-9bd7-11e8-8764-f554c2be5f4d.png)

Context menu on text:

![image](https://user-images.githubusercontent.com/12813221/43911939-2a435de6-9bd7-11e8-9a68-c5ececf89200.png)

No context menu on inputs

![image](https://user-images.githubusercontent.com/12813221/43911949-339c9c9a-9bd7-11e8-8f62-6682c9e5227e.png)

**Comment by nolimits4web** [comment]
Did you try?
```
touch: {
  disableContextMenu: false,
}
```
Note, it is `disableContextMenu`, not `disable(d)ContextMenu`

**Comment by vousys** [comment]
SOLVED!!! thank you !

**Comment by sirpy** [comment]
Is there an option to enable the context menu only for inputs?
because enabling context does that for the whole app and removes the "mobile like" feeling
