### ISSUE TITLE
Onclick bug with item-radio in list

### ISSUE THREAD

**Issue by hmr-it-jr** [framework7io/framework7#2568]
* Framework7 version: [e.g. 3.0.7]
* Platform and Target: [Firefox, Chrome, Cordova App]
* Live Link or JSFiddle: https://jsfiddle.net/o2ejupu1/328/

### Describe the bug
The onclick event is executed wrongly.

### To Reproduce
Steps to reproduce the behavior (go to JSFiddle):
1. click on about
2. click on books (hello world will be visible two times)
3. click on movies (hello world will be visible only once)

### Expected behavior
Hello world should be visible only once.

### Actual Behavior
If the onclick event is on the \<li> it will be executed twice. If it's on the <input type"radio"> it will be executed only once, but not in an Cordova app.

### Screenshots
See JSFiddle.

**Comment by nolimits4web** [comment]
Because it is a label with radio, one click happens on input and another one on li, use `onchange` event instead https://jsfiddle.net/jzsaorgy/
