### ISSUE TITLE
Router "Back" not working with Routable Tabs

### ISSUE THREAD

**Issue by FabioWidmer** [framework7io/framework7#2573]
* Framework7 version: 3.1.1
* Platform and Target: Everywhere
* Live Link or JSFiddle: -

### Describe the bug
After switching multiple times the tab on a page with routable tabs the normal back button on the top left, the back method and the browser back button are not working anymore.

### To Reproduce
1. Create a page with routable tabs (not the main page). Each tab has a different path.
2. Open the page and switch the tab multiple times.
3. Click the back button or method

### Expected behavior
Changing the selected tab more than five times and then going back one page should work normally.

### Actual Behavior
Nothing happens and there is no error in the console.

**Comment by nolimits4web** [comment]
Need live example or JSFiddle with the issue

**Comment by FabioWidmer** [comment]
I am sorry for not providing a JSFiddle. #2861 fixed the problem! Thank you.
