### ISSUE TITLE
parameter panel.opened not set

### ISSUE THREAD

**Issue by GuillaumeBiton** [framework7io/framework7#2575]
* Framework7 version: 3.1.1
* Platform and Target: all
* Live Link or JSFiddle: https://jsfiddle.net/o2ejupu1/340/

### Describe the bug
panel.opened not updated on panel.open() and breakpoints reached

### To Reproduce
try to get app.panel.opened

### Expected behavior
app.panel.opened to be true or false

### Actual Behavior
app.panel.opened is undefined

**Comment by nolimits4web** [comment]
You should refer the panel, e.g. `app.panel.left.opened` or `app.panel.right.opened`

**Comment by GuillaumeBiton** [comment]
OK works sorry for the misunderstanding
