### ISSUE TITLE
pageInit on script file not called from page back

### ISSUE THREAD

**Issue by masrodjie** [framework7io/framework7#2576]
* Framework7 version: 3.1.1
* Platform and Target:Mobile Chrome Browser

This pageInit always called from page back
```javascript
app = new Framework7({
    on: {
           pageInit: function (page) {
            }
          }
});
```

But the pageInit in the files not called from page back. It only called on load page
```javascript
<template>
</template>
<script>
    return {
        on: {
            pageInit: function (e, page) {
           }
       }
}
</script>
```

### Expected behavior
Both pageInit on app or insider files should be called

**Comment by nolimits4web** [comment]
It is by design, because iOS theme holds previous page in DOM, use `pageBeforeIn` instead
