### ISSUE TITLE
Virtual DOM with Infinite scroll and Stackpages issue

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2587]
* Framework7 version: 3.1.1
* Platform and Target: Cordova App with Chrome browser

### Describe the bug
I have created listing of product with VDOM and infinite scroll, i have used stackpages on view caused in deep i want cache.

When i scroll two page infinite and then click on any product then goes to product detail and when back to previous page then whole DOM is clear and reinit whole page and infinte scroll ajax call automatically fire till when i at last time on page(means two time autoinfinite and put me where i leave at last but without VDOM its working perfect with stackpages).

### Expected behavior
So when stackpages and i goes back then don't clean DOM as without VDOM its work perfect same things i need on VDOM.

### Actual Behavior
Current behavior is when, i back DOM is clear and automatically fire infinite call where i am available to access last item: For example. on load i am display first 10 product, and every infinite scroll i append 10 product. So i have infinite scroll total three time so total record is now 10(page load)+30(3 time scroll)=40 record. Now when click on 39 record then open detail and when i goes back then again load all things with auto all infinite call.

VDOM is very useful for us and if we got solution for this issue then its very very good for me.

Thanks for adding VDOM in core framework.

Sorry for my bad english.

Hiren Raiyani

**Comment by raiyanihiren** [comment]
I will add example as soon as possible

**Comment by raiyanihiren** [comment]
Hello,

https://jsfiddle.net/o2ejupu1/384/

Please check above jsfiddle link for issue.

Thanks
Hiren Raiyani

**Comment by raiyanihiren** [comment]
Ok Thanks, But if stackpages and back to any pages then why its gone into pageAfterIn events. This same code working on simple DOM.

**Comment by GuillaumeBiton** [comment]
Use PageInit instead of pageAfterIn with is trigger after every animation of you page.

**Comment by raiyanihiren** [comment]
Ok Thanks
