### ISSUE TITLE
Using f7-link back attribute to go to previous tab

### ISSUE THREAD

**Issue by ThornWinters** [framework7io/framework7#2590]
### Describe the bug
How you can have routable tabs that allow the back button to go to the previous tab visited.

### To Reproduce
1. Visit Different Tab
2. Click on Back Button

### Expected behavior
If I am on Tab1 and visit Tab2 and click back I should be redirected to Tab1.

### Actual Behavior
If I am on Tab1 and visit Tab2 and click back nothing happens.

### JSFiddle

I cloned a JSFiddle you used to setup Vue Routeable Tabs and added a v7-link with the attribute of back to simulate the back button in JSFiddle.
https://jsfiddle.net/Michael_Warner/2f87p02q/101/

**Comment by nolimits4web** [comment]
Routable tabs replace state instead of push state, so by default it is not possible and such behavior is not supported.

**Comment by leyenda** [comment]
@nolimits4web Is this still the expected behavior?  In the documentation it is presented as one reason to use routable tabs:

> Routable Tabs
> What routable tabs means and why is it good?
>
> + First of all, it provides opportunity to navigate to tabs by usual links instead of so called special tab- links.
> + Second, when navigating to such route you can load a page with required tab opened.
> + **Third, with enabled Push State, the same tab will be opened when you navigate back and forward in history.**

But I expected the behavior described in this issue, and its not working with a back from the browser.

**Comment by mmis1000** [comment]
Considering using routerable tab with swipable tab, I believe it is the correct behavour.
Otherwise, it will push whenever you swipe the tab, which is insane.

**Comment by MichaelJGW** [comment]
Looking into this with native apps it does not support this behavior so it makes sense not to support it in Framework7 as it is trying to mimic native behavior.

With the Back Button info on Android for examples states the following

https://developer.android.com/training/design-navigation/ancestral-temporal#changing-view

**Changing view within a screen**
Changing view options in a screen should not change the behavior of Up or Back: the screen is still in the same place within the app's hierarchy, so no new navigation history is created.

Examples of such view changes include the following:

Switching views using tabs and/or left-and-right swipes
...
