### ISSUE TITLE
$setState with Lists

### ISSUE THREAD

**Issue by kleiteimc** [framework7io/framework7#2596]
* Framework7 version: [e.g. 3.1.0]
* Platform and Target: Chrome browser

### Describe the bug

It appears that when using lists, the suggestion in the documentation:

To give VDOM a hint so that it can track each node's identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item

Doesn't appear to work.

### To Reproduce

Using the template in documentation:

<template>
  ...
  <ul>
    {{#each items}}
    <li key="{{this.id}}">...</li>
    {{/each}}
  </ul>
  ...
</template>

The "key" attribute doesn't get included in the rendered DOM.  It appears that $setState is not using the "key" attribute to speed up list processing.

Note:  Lists are getting updated correctly.  It is just taking longer because the "key" doesn't appear to being used.

### Expected behavior

The "key" attribute would be in the render DOM so that $setState could use it to improve the time needed to update long lists.

### Actual Behavior

In framework7.js file starting at line 9153:
        }
      } else if (attrName === 'key') {
        data.key = attrName;
      } else if (attrName.indexOf('@') === 0) {
        if (!data.on) { data.on = {}; }

The string "key" is put into the "data.key" field where the "attrValue" would be more effective.  Secondly, the rendered DOM doesn't include the attribute "key" with the value so that it can be used to uniquely identify the <li> item.

Change to consider:

1)  Remove the lines in framework7.js file starting at line 9153:

      } else if (attrName === 'key') {
        data.key = attrName;

2)  21 lines farther down the existing code is this section:

      } else {
        if (!data.attrs) { data.attrs = {}; }
        data.attrs[attrName] = attrValue;

        if (attrName === 'id' && !data.key) {
          data.key = attrValue;
        }
      }

Consider changing to:

      } else {
        if (!data.attrs) { data.attrs = {}; }
        data.attrs[attrName] = attrValue;

        if (attrName === 'key') {
           data.key = attrValue;
        }  if (attrName === 'id' && !data.key) {
          data.key = attrValue;
        }
      }

The change will allow the "key" attribute to be rendered in the DOM and the vNode will have the associated unique id in the data.key field.

Thanks,
Kris

**Comment by nolimits4web** [comment]
Hey @kleiteimc
Everything is correct there, key shouldn’t be rendered on DOM, because vdom doesn’t work with actual DOM. It works with vnodes that correctly have data.key property

**Comment by kleiteimc** [comment]
>key shouldn’t be rendered on DOM

OK

What about the line around   9153 

} else if (attrName === 'key') {
data.key = attrName;   <<<<<<<<<<<<<< ????
} else if (attrName.indexOf('@') === 0) {

It would seem that should be changed to:

data.key = attrValue

Thanks,
Kris

**Comment by nolimits4web** [comment]
This was an issue
