### ISSUE TITLE
Issue in input clear icon (Framework7 2.3.1)

### ISSUE THREAD

**Issue by Maheshwbc** [framework7io/framework7#2597]
Empty the inputs value dynamically, after that open the form means the input values are cleared but the clear(X) icons are showing. How the avoid that?

Issue occurred in Framework7 2.3.1 

Initial filled form

![initial filled form](https://user-images.githubusercontent.com/32213371/44448312-879d9200-a608-11e8-961a-d569f6de30ac.png)

After cleared dynamically and open again

![after cleared dynamically and open again](https://user-images.githubusercontent.com/32213371/44448308-879d9200-a608-11e8-8666-75483bdff444.png)

Thanks in Advance.. @nolimits4web

**Comment by Maheshwbc** [comment]
@nolimits4web

**Comment by nolimits4web** [comment]
You need to call checkEmptyState app method on those inputs you cleared dynamically http://framework7.io/docs/inputs.html#input-app-methods

**Comment by Maheshwbc** [comment]
Thanks very much its worked for me...

Example code.

I have used for each input in particular division.

$("#ppSearchform :input").each(function () {
        myApp.input.checkEmptyState('#' + $(this).attr('id'));
})
