### ISSUE TITLE
View does not change dynamically with data

### ISSUE THREAD

**Issue by akandeBolaji** [framework7io/framework7#2598]
I created a boolean data that is supposed to show a default screen if user is not logged in and another screen  when user gets logged in. I bind this data to the root vue instance and set to false by default. The logic works fine (view and data props changes) when i manually change the data value to true. But when i update this value dynamically via an API call, the data props can be seen to change dynamically but the view does not get updated. How can i solve this issue?
P.S i used the vue dev tools to view the changes in the data props.

**Comment by nolimits4web** [comment]
Need more code examples of what and how are you doing. But i guess it can be related to Vue and your understanding of how reactivity works there

**Comment by akandeBolaji** [comment]
I already found my way around this. I had to replace the v-if directive with v-show directive meaning both views were readily available from initial page load . I was able to implement a similar functionality using the v-if directive without framework 7 and the views were loaded simultaneously with changes in data . I guess this has to do with me understanding how f7router loads its view.

**Comment by nolimits4web** [comment]
Ok, closing then for now
