### ISSUE TITLE
App height does not properly adjust with the keyboard open

### ISSUE THREAD

**Issue by mwargan** [framework7io/framework7#2600]
* Framework7 version:  3.0.0
* Vue.js version: 2.0.0
* Platform and Target: iOS 12 Cordova app

### Describe the bug
They keyboard covers form inputs that are towards the bottom of the screen / the app height does not properly adjust with the keyboard open.

### To Reproduce
1.  Install Kitchen Sink and publish production build with Vue
2. Remove the black bars in the info.plst so its all fullscreen as described [here](https://stackoverflow.com/a/47317437)
3. Run in iOS 12 iPhone X with Cordova and open Messages

### Expected behavior
![screenrecording_08-23-2018 16-01-24 2018-08-23 16_12_18](https://user-images.githubusercontent.com/13789481/44530713-551a9480-a6ef-11e8-9ada-3ad2c9e0eb7c.gif)
Also, preferably without the nav bar disappearing but thats a minor issue at this point...

### Actual Behavior
![screenrecording_08-23-2018 16-01-58 2018-08-23 16_10_34](https://user-images.githubusercontent.com/13789481/44530643-361c0280-a6ef-11e8-8016-cdce37654152.gif)

### Additional context
Running iOS 12 beta on a real iPhone X. Same issue in simulators. The issue is also causing wonky behaviour with the form navigation buttons (the up/down buttons on the iOS keyboard to move between input fields), especially when these fields are towards the bottom. Same behaviour can be observed in Inputs and Form Storage pages.

Don't know if relevant but I noticed that when the app has the top & bottom black bars removed the keyboard additionally shows the Change language icon and the microphone icon; notice the difference in keyboards between the two gifs.

**Comment by nolimits4web** [comment]
These issues are not related to Framework7. For keyboard issue use some of cordova keyboard plugins to handle this and shrink app accordingly. For issue with app running in part of window in iPhoneX, you need to specify correct size splash screen
