### ISSUE TITLE
Document what f7params.id is for

### ISSUE THREAD

**Issue by ariofrio** [framework7io/framework7#2604]
According to [the documention](http://framework7.io/docs/app.html), `f7params.id` is the "App bundle id."

However, I'm working on a project template and it would be good not to have to repeat the app bundle id in one more place. I notice that most Framework7 examples provide the app bundle id, but a quick grep through the code reveal no place where it's used.

Why do we need to provide the app bundle id to Framework7?

If it is used for something, can it be documented?

If not, can it be removed from the documentation (and the implementation, in a backwards-compatible way)?

**Comment by nolimits4web** [comment]
At the moment it is used in `vi` module http://framework7.io/docs/vi.html#vi-ad-parameters and can be used in future services that may appear in near future
