### ISSUE TITLE
Routable Popup Handle Close Event

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2605]
* Framework7 version: 3.1.1
* Platform and Target: Chrome Browser and iOS cordova app

### Describe the bug
How to handle close event of routable popup? 

I have created on poup which is open from one page, and when popup close then i want to handle that closed poup event same as we done for dynamic popup from where popup open.

I am using below method to load popup:
https://framework7.io/docs/routes.html#routable-modals
```
// Load Popup from component file
  {
    path: '/popup-component/',
    loginScreen: {
      componentUrl: './popup-component.html',
      /* popup-component.html contains:
        <template>
          <div class="popup-screen">
            <div class="view">
              <div class="page">
                ...
              </div>
            </div>
          </div>
        </template>
        <style>...</style>
        <script>...</script>
      */
    },
  },
```

Thanks
Hiren Raiyani

**Comment by nolimits4web** [comment]
Use DOM events:
```
<template>
  <div class="popup popup-screen" @popup:close="onPopupClose">
  </div>
</template>
<script>
return {
 ...
  methods: {
    onPopupClose() { ... }
  }
}

**Comment by raiyanihiren** [comment]
Thanks,

Not in this way, i want callback on parent from where i have open this popup/modal.

I want to call function of parent when close popup, same way we handle for dynamic modal example of doc.

**Comment by webenformasyon** [comment]
my problem is similar. how i trigger setState in previous page when routable popup closes

**Comment by nolimits4web** [comment]
Same way, in routable popup component you handle popup close event, like:
```
onPopupClose() {
  app.emit('my-awesome-popup-close`);
}
```
and other "parent" component you can listen for such event:
```
app.on('my-awesome-popup-close', () => {
  // do something
});

**Comment by webenformasyon** [comment]
component page: 
`    mounted() {
      var self = this;
      self.$app.on('new-photo-added', (imageName, imageData) => {
        console.log('new-photo-added ');
        //console.log(self.$route.context);
        //if (imageName != self.$route.context.imageName) return;
      });
    },`

when i press back on navbar then reopen the page link this event throws an error 
'Error in Success callbackId: .... : TypeError: undefined is not an object (evaluating 'self.$route.context')
'
