### ISSUE TITLE
Popup backdrop only work once

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2611]
* Framework7 version: 3.1.1
* Platform and Target: Cordova Browser
* Live Link or JSFiddle: https://jsfiddle.net/mLdvteg9/

### Describe the bug
The popup backdrop is being deleted, regadless if there are previous opened popups.

### To Reproduce
1. Open a popup (let's say "Create a new product"), in desktop or tablet 
2. Open a second popup without closing the first (ex.: an automated login procedure that creates and opens a popup)
3. Close the second popup

### Expected behavior
1. The second popup should hide the first popup shadow, so shadows don't stack to a huge black spot (minor bug)
2. The backdrop should remain on screen after closing the second popup.
3. Each backdrop to close its own popup (if I click the backdrop when popup2 is open, only popup2 is dismissed)

### Actual Behavior
When closing the second popup, the backdrop is deleted and user has access to the page, even if there is the first popup still in window.

When the second popup is open and we click on backdrop, both popups are dismissed.

### Screenshots
1. The app
![image](https://user-images.githubusercontent.com/379339/44634245-6cff4c00-a96d-11e8-86d4-9a2f0e42ead9.png)

2. The first popup (user is creating something)
![image](https://user-images.githubusercontent.com/379339/44634248-75f01d80-a96d-11e8-9442-e9944e1539d0.png)

3. The second popup (whenever something that requires login is needed, an automated login-on-popup action is triggered, so, yes, popup over popup). Notice the blacker shadow here (two shadows overlapping - minor bug)
![image](https://user-images.githubusercontent.com/379339/44634251-7dafc200-a96d-11e8-8ea4-63610d21654d.png)

4. Now I close the login popup and we're back where we were, but the backdrop is gone (and all elements of background can be manipulated)
![image](https://user-images.githubusercontent.com/379339/44634253-81dbdf80-a96d-11e8-99be-91b914f934b1.png)

**Comment by nolimits4web** [comment]
Fixed by https://github.com/framework7io/framework7/commit/755f80102c6232c076499dd5061ee73979d48a6a
