### ISSUE TITLE
Child-type investigation should be able to look one level down _inside_ each child also

### ISSUE THREAD

**Issue by ozra** [framework7io/framework7#2615]
It's very hard to abstract components now because they end up in the wrong slots (React, but I assume the code for this is transpiled so the issue should go into this repo).

Contrived minimal example:
```tsx
// Works fine, obviously
const foo = <List>
   <ListItem link="/" title="1" />
</List>
```
vs.
```tsx
function ListItem2(props) { 
    return <ListItem {...props} /> 
}

// NOT as expected!
const foo = <List>
   <ListItem2 link="/" title="2" />
</List>
```

### Suggestion
- Optimally, one shouldn't have to think about it to do above abstraction
- An alternative, that would be nice, is if one could use some flag or similar on the "wrapper component" so that FW7 knows to look to _it's_ child for type-tag, so it doesn't have to do it always, if that's preferred.
- Is there already a workaround to get it to work?

I find it convenient and yielding less clutter to make "pre-configured" complex list-items as components like this, also toolbars/tab-bars that are re-occuring, and just use it as one would expect. So far I've stumbled upon this for just a few components, but important one's.

**Comment by ozra** [comment]
Well, I just looked at the compiled code, and a ugly but seemingly working hack is just 
```(ListItem2 as any).displayName = "F7ListItem"```
If that's reliable, that's good enough for me.

**Comment by nolimits4web** [comment]
We can’t look deeper because during parent list rendering its children are not yet rendered so they are just functions or classes, and we can’t know what they return.

This case can be easily solved with slots http://framework7.io/react/list-view.html#list-slots

```
<List>
  <ListItem2 slot="list">...
```

Will do the trick

**Comment by ozra** [comment]
Yes, however it beats the purpose of keeping the pre-confed components clean in markup (these are the one's that are use a bunch). However, the displayName trick works for all the cases, so that's a "decently stable hack" :-) I'll go with that.
