### ISSUE TITLE
Smart select color themes not working

### ISSUE THREAD

**Issue by owen-mills** [framework7io/framework7#2617]
* Framework7 version: 3.2.0
* Vue.js version: 2.5.17
* Platform and Target: Android

### Describe the bug
The `navbarColorTheme` and `formColorTheme` parameters of the `smart-select` component do not work. No matter what color I set the formColorTheme to, nothing happens, and the form color for all the different smart-selects remains the same default theme. When I set `navbarColorTheme` on a popup smart-select, the navbar disappears and the whole page is out of alignment and has no color theme at all.

### Expected behavior
I expect the color themes to change as described in the documentation when these params are changed

### Actual Behavior
They do not work

**Comment by jcchen2018** [comment]
same problem here. still looking for a solution, please help.
