### ISSUE TITLE
Theme color not used in some components

### ISSUE THREAD

**Issue by mossaiby** [framework7io/framework7#2618]
* Framework7 version:
```3.2.0```
* Platform and Target:
PhoneGap

### The bug
Buttons in dialog routines (```app.dialog.alert```, ```app.dialog.confirm```, etc.) as well as buttons without color field set in action sheets do not use theme color. I think this should be fixed.

### To Reproduce
See the live demo on http://framework7.io for example; change the theme color and execute said examples.

### Expected behavior
Buttons in said places should use the theme color.

### Actual Behavior
The default (blue) color is used instead.

**Comment by mossaiby** [comment]
Dear Vladimir,
I see you have hard-coded the colors in the .less files; I hope this is not a design decision, as once you change the theme color, the buttons are not in par with other parts of the app.

Thanks.

@nolimits4web

**Comment by nolimits4web** [comment]
Sorry, this is by design because dialog mimics native dialog, and in native apps it is almost always have default system colors inspite of app custom colors. So if you need to change this, then please overwrite its colors in your CSS file

**Comment by mossaiby** [comment]
Thanks for reply.
How can I do that, so the current theme color is applied automatically for the buttons (and action sheet buttons)?

@nolimits4web

**Comment by nolimits4web** [comment]
CSS inspector shows you what you need

<img width="1116" alt="2018-08-30 15 27 29" src="https://user-images.githubusercontent.com/999588/44851523-41c87580-ac69-11e8-816c-46c1a683a30c.png">

**Comment by mossaiby** [comment]
Thanks, I did it!
