### ISSUE TITLE
Tab view not working when page is loaded via f7router

### ISSUE THREAD

**Issue by akandeBolaji** [framework7io/framework7#2623]
So in my framework7 vue app, I have users directed to the home page after successful login. When these home page is loaded via the f7router, the tabs are not working but only showing the default active tab for each tab. When  i refresh the page manually, everything works fine. Please kindly look into this for me.

**Comment by akandeBolaji** [comment]
The home page is loaded via an ajax call if successful in this manner `this.$f7router.navigate("/");` and the tabs are static(same as the ones on the vue kitchen sink)

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle with the issue
