### ISSUE TITLE
Input placeholder not showing for md floating

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2625]
* Framework7 version: 3.2.0
* Platform and Target: Cordova browser (on Chrome 68/Windows 10)

### Describe the bug
Input placeholders not showing when theme is md:

### To Reproduce
```
<f7-list no-hairlines-md>
	<f7-list-item>
		<f7-label floating>Nome do item que você deseja</f7-label>
		<f7-input type="text" placeholder="Ex.: MotoG6 Plus" />
	</f7-list-item>
</f7-list>
```

Test it on ios and md themes.

### Expected behavior
The placeholder in md theme should be visible only when the input has focus and only when empty:
![image](https://user-images.githubusercontent.com/379339/44885936-10b46900-ac9a-11e8-8c5e-502badfb96e3.png)

### Actual Behavior
theme iOS:
![image](https://user-images.githubusercontent.com/379339/44885843-879d3200-ac99-11e8-82f3-5a1136756fb1.png)

theme MD (with focus):
![image](https://user-images.githubusercontent.com/379339/44885860-a7ccf100-ac99-11e8-9986-61fc0d613697.png)

### Additional context
Notice that the `j` letter is being clipped on both themes, because my default font-family includes other system fonts:
```
{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; */
}
```

**Comment by nolimits4web** [comment]
It is by design, because when floating labels are used then floating label is used itself as placeholder

**Comment by nolimits4web** [comment]
But i'll check looks like you are right it needs to be visible when floating label "goes to top"
