### ISSUE TITLE
Gauge component not working in Kitchen sink

### ISSUE THREAD

**Issue by LarsVoith** [framework7io/framework7#2629]
* Framework7 version: [e.g. 3.2.1]
* Platform and Target: [e.g. all]

### Describe the bug
framework7.esm.bundle.js is missing 
`import Gauge from './components/gauge/gauge';`

Step to reproduce
 install all dependencies 
$ npm install

And build development version of Framework7:
$ npm run build:dev

Build production version of Framework7:
$ npm run build:prod

Run Kitchen Sink with production environment (configured to scripts and styles from dist/ folder):
//this will correct path for the template
$ npm run prod

Then i get the error 
VM146:16 Uncaught TypeError: Cannot read property 'create' of undefined

---> var demoGauge = app.gauge.create({

**Comment by nolimits4web** [comment]
Can see it here at https://github.com/framework7io/framework7/blob/master/packages/core/framework7.esm.bundle.js which built with same npm run build:prod

**Comment by LarsVoith** [comment]
OK, my fault, I now see that I did not update my  build-custom-config.js file.

```
// Gauge
    'gauge',
```

Then I ran "_npm run build:prod_" and "_import Gauge from './components/gauge/gauge';_" was removed.
