### ISSUE TITLE
Disable smart-select

### ISSUE THREAD

**Issue by owen-mills** [framework7io/framework7#2633]
**Is your feature request related to a problem? Please describe.**
There is no option for the smart-select component to be disabled.
**Describe the solution you'd like**
Allow the `disabled` prop to be passed to the `f7-list-item` when it is a `smart-select`, that grays-out the link in the list item, and also prevent the user from being able to open the smart-select.

**Comment by nolimits4web** [comment]
You can just add `class="disabled"` to list item to get the desired effect

**Comment by nolimits4web** [comment]
No, it won't. Otherwise will be good to see live example or JSFiddle where `disabled` class keeps item clickable

**Comment by owen-mills** [comment]
Well, sir, I don't know how you did it, but it seems to be working the way you said it should today. I guess I was doing something very wrong yesterday, but I don't know what.
Thanks for this help and the hard work you do on this framework. I love it and I appreciate people like you doing great things like this.
