### ISSUE TITLE
Page with id atttribute fails load

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#2637]
* Framework7 version: 3.x.0
* Platform and Target: All
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
If the page is a component and the page container contains an id, the page will not load completely.  If the page is not a component, it doesn't seem to be affected.

### To Reproduce

Take any component page and add an id to the page container

<div class="page" id="some-id">
. . . .
</div>

Then click on it's link.  Page events will be invoked but the page will not load. I invoked it from a simple link
<a href="/page_route/" class="link">bad component</a>

### Expected behavior
Should load page properly.

### Actual Behavior
Hangs

### Additional context
If this is documented as a no-no than I missed it.

**Comment by nolimits4web** [comment]
I can't replicate it, please provide a JSFiddle with the example

**Comment by nolimits4web** [comment]
Ok, see the issue
