### ISSUE TITLE
CSS compilation error

### ISSUE THREAD

**Issue by zhengmenglin** [framework7io/framework7#2640]
* Framework7 version: [e.g. 3.0.0]
* Vue.js version: [e.g. 2.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Expected behavior

CSS does not report errors at compile time.

### Actual Behavior
Explain what is actually happening

When I use " import Framework7Styles from 'framework7/css/framework7.css' " in Vue program, and I run ' npm run build ' ,  the css report errors.

### Screenshots

<img width="1064" alt="wx20180906-150319 2x" src="https://user-images.githubusercontent.com/38604167/45140684-2c61c700-b1e6-11e8-821e-88bdffe708a1.png">

**Comment by nolimits4web** [comment]
Problem with your build process and scripts that don't understand such css syntax. Not a problem with Framework7

**Comment by zhengmenglin** [comment]
Can you be more specific ？What should I do ？Thank you very much！
