### ISSUE TITLE
Something very wrong with range-slider on MD theme

### ISSUE THREAD

**Issue by owen-m1** [framework7io/framework7#2643]
* Framework7 version: 3.2.1
* Vue.js version: 2.5.17
* Platform and Target: Android (MD theme)

### Describe the bug
On the Framework7 docs, if you go to the range-slider component you can see that the examples on the android MD theme do not function properly. For the volume slider example, the slider has it's color fill completely out of line with the thumb scrubber. For the other two you cannot even move the slider. However, these work fine on IOS. In my own experience, I found that the range slider `setValue` method sets the value properly, but does not move the thumb scrubber at all. Only the color filling.

Likewise, it also seems that the `changed` event is not firing because the thumb cannot be moved.

### To Reproduce
1. Create a `range-slider` component using the MD theme

**Comment by nolimits4web** [comment]
Can't see anything like that. Do you have a live example or JSFiddle with the issue?
