### ISSUE TITLE
Floating label bug when using item-row/item-cell

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2644]
* Framework7 version: 3.2.1
* Platform and Target: Cordova Chrome 68 Windows 10
* Live Link or JSFiddle: https://jsfiddle.net/27uz8y1w/2/

### Describe the bug
The two inputs are side by side in a list using `.item-row` and `.item-cell`, the floating label and focus triggers for both (even if one of them is readonly).

In the fiddle, the second input has a default value, triggering the floating label of the empty first input.

### To Reproduce
Create two form items side by side using `.item-row` and `.item-cell` on md theme.

### Expected behavior
Independent behavior of each input.

### Actual Behavior
Both inputs are linked to the same behavior, just because they belong to the same list item.

NOTE: In the first example, when you edit the first input and set it to blank, the second floating label "unfloats" and mess up the second entry (which still has value). 

The general idea is to make a form where 2 inputs are too small (one is 9 chars, other is two), so I want them on the same line.

**Comment by nolimits4web** [comment]
This is by design, each .item-content.item-input can contain only one input. You need to restructure and put two item contents inside of LI

**Comment by JCKodel** [comment]
Fixed one, but one bug still remains:
![image](https://user-images.githubusercontent.com/379339/45374479-96081980-b5c8-11e8-9ef4-d22c3dbac404.png)

The left field is a ZipCode, and the rest of form is input with readonly (because all address parts are filled from ZipCode database).

All fields have their label floated when auto filled, except the iten inside an .item-cell.

The form is this:
```
<f7-list>
	<li class="item-content">
		<div class="item-inner item-cell">
			<div class="item-row">
				<div class="item-cell">
					<div>
						<p>Some intro text.</p>
					</div>
				</div>
			</div>

			<div class="item-row">
				<div class="item-cell item-input">
					<div class="item-title item-floating-label">Zip Code</div>

					<div class="item-input-wrap">
						<the-mask type="tel" required v-model="zipCode" mask="#####-###" />
					</div>
				</div>

				<div class="item-cell item-input">
					<div class="item-title item-floating-label">State</div>

					<div class="item-input-wrap">
						<input type="text" readonly :value="state" />
					</div>
				</div>
			</div>
		</div>
	</li>

	<f7-list-item>
		<f7-label floating>City</f7-label>
		<f7-input type="text" readonly :value="city" />
	</f7-list-item>

	<f7-list-item>
		<f7-label floating>District</f7-label>
		<f7-input type="text" readonly :value="district" />
	</f7-list-item>

	<f7-list-item v-if="mapImageUrl">
		<img :src="mapImageUrl" style="width:100%;" />
	</f7-list-item>
</f7-list>
```

Notice: there is no bug if the form is pre-filled at load. This only occurs when the load is made after the page is initialized.

I've forked that sample above with a delayed input fill from a timer for you to see the bug (the second input will be filled, but the form will not float automatically).

https://jsfiddle.net/3nL012aw/2/

**Comment by nolimits4web** [comment]
To handle input empty state call `app.input.checkEmptyState` app method on that input http://framework7.io/docs/inputs.html#input-app-methods, or trigger `change` event on that input, or if you use Vue, then `f7-input` component does it automatically

**Comment by JCKodel** [comment]
We really need a more granular input component =\ At times, we're forced to not use f7-input because it is impossible to define layouts (rows and columns) or apply directives to the input element itself.

It would be nice a f7-input directive so, in those cases, we could apply the f7 input events and methods directly on HTML (a directive that does what you told above).

**Comment by nolimits4web** [comment]
> At times, we're forced to not use f7-input because it is impossible to define layouts (rows and columns) or apply directives to the input element itself

Why? In your layout example above, `<f7-input>` is equal to the following:
```
<div class="item-input-wrap">
   <input type="text" readonly :value="state" />
</div>
```

**Comment by JCKodel** [comment]
Above this I have `.item-row` and `.item-cell` and also a `<the-mask />`.
`<the-mask/>` is a masked input box that can be either a component or a directive.

As a component, it would be useful for `<f7-input/>` to have a slot.
As a directive, I can't use `<f7-input/>` and must use the rendered HTML that `<f7-input/>` would render.

In those cases (custom layout that is not what `<f7-input/>` renders OR custom input directives or attributes), I can't use `<f7-input/>`.

Am I missing something?
