### ISSUE TITLE
Routable panels cannot be opened by swiping

### ISSUE THREAD

**Issue by dlee** [framework7io/framework7#2645]
* Framework7 version: [e.g. 3.2.0]
* Platform and Target: all
* Live Link or JSFiddle: https://jsfiddle.net/mryx47ef/

### Describe the bug
Routable panel cannot be opened by swiping.

### To Reproduce
1. Go to https://jsfiddle.net/mryx47ef/
2. Try swiping to reveal right panel (it works because it's NOT a routable panel)
3. Try swiping to reveal left panel (it does NOT work because it's a routable panel)

### Expected behavior
We should be able to open a routable panel by swiping.

### Actual Behavior
Only non-routable panels can be opened by swiping.

**Comment by nolimits4web** [comment]
Routable panels can’t be opened with swipe, routable panels means it will be loaded and opened on route change
