### ISSUE TITLE
React Swiper is broken inside Popup

### ISSUE THREAD

**Issue by dlee** [framework7io/framework7#2650]
* Framework7 version: 3.2
* React.js version: 16.4
* Platform and Target: all
* https://jsfiddle.net/0kauo6rf/

### Describe the bug
Swiper works in main view but is broken inside Popup

### To Reproduce
1. Go to https://jsfiddle.net/0kauo6rf/
2. Try the swiper in the main view. Should be working
3. Click on "Popup with swiper" button to launch Popup with Swiper.
4. Try the swiper in the Popup. Is NOT working.

### Expected behavior
Swiper inside of Popup should work.

### Actual Behavior
Swiper inside of Popup is broken.

**Comment by nolimits4web** [comment]
This is how Swiper works - it must be initialized when it is visible. Otherwise call its update() method on popup open or enable its observer and observeParents properites

**Comment by dlee** [comment]
Thanks, the `observer` + `observeParents` strategy works. That should be done automatically in the React component or at least given a prop and highlighted in the documentation for React.
