### ISSUE TITLE
app.request & XMLHttpRequest a mystery CORS problem, or a bug?

### ISSUE THREAD

**Issue by rapgithub** [framework7io/framework7#2653]
I wonder if there is an issue with the use of app.request and CORS because my APP needs to request data from the remote server to serve the App all the CORS are OK and working perfectly if I send the POST request using XMLHttpRequest but when using app.request the reply from server it is all the time but curiously not always but with XMLHttpRequest it is constant OK :

server reply using app.request Ajax call:

```php
 **_not allowed by Access-Control-Allow-Origin_**.
```

this works perfect all the time no problems with CORS.

```js
var xhr = new XMLHttpRequest();
xhr.onreadystatechange = function() {
    if (xhr.readyState == 4 && xhr.status == 200) {
        var json = JSON.parse(xhr.responseText);
        console.log(json);
    }
};
xhr.open('POST', 'http://oauth.mydomain.com/auth/', true);
xhr.withCredentials = false;
xhr.setRequestHeader("Content-type", "application/json;charset=UTF-8");
xhr.onload = function() {
    if (xhr.status === 200) {
        console.log(xhr.responseText);
    } else {
        console.log('Request failed.  Returned status of ' + xhr.status);
    }
};
var data = JSON.stringify({
    "Token": "token_code_here"
});
xhr.send(data);
```

and now with app.request it works and suddenly stop working again :( no clues why but it happens only if I use app.request Ajax call... so maybe there is something here...

```js
data = {
    Token: token_code_here
};
app.request({
    url: 'http://oauth.mydomain.com/auth/',
    method: "POST",
    dataType: "json",
    data: data,
    crossDomain: true,
    beforeSend: function(xhr) {
        xhr.withCredentials = false;
    },
    success: function(res) {
        console.log(res);
    },
    error: function(xhr) {
        console.log('error');
        console.log(xhr);
    }
});
```

again server reply using app.request Ajax call:

```php
 **_Origin is not allowed by Access-Control-Allow-Origin._**.
```

Any clues how to fix this? CORS on server are fine defined but works well only when using XMLHttpRequest Ajax call...

:(

**Comment by rapgithub** [comment]
I have been reading about some topics about Ajax and CORS and found out this:

[https://zqzhang.github.io/blog/2016/04/18/why-use-onload-in-cross-domain-ajax.html](url)

Maybe app.request works in the same way as onreadystatechange... I do not know if this is so but make sense why XMLHttpRequest works always instead of app.request...

any ideas?

**Comment by nolimits4web** [comment]
Request uses same XMLHttpRequest and it uses `onload` too. So would be good to see live example of where it is not working

**Comment by rapgithub** [comment]
Yes the response has it all!!! and  'Access-Control-Allow-Origin: *'  too... very weird this thing :( 
I will try to make a live example and post the link... here...

thanks for helping..

**Comment by gearintellix** [comment]
It still problem
