### ISSUE TITLE
Tab application layout with dynamic tabs.

### ISSUE THREAD

**Issue by boyandimitrov** [framework7io/framework7#2654]
Can't find a way to configure 2 tabs and add more dynamically. My goal is to create a tabbed layout, where the last tab is (Add a new tab). Tabs in my case will be limited to five. Every tab is a view.

I need myApp.addTabView({});

Can't figure any alternatives so far. I'm rather new to the framework.

**Comment by nolimits4web** [comment]
If you don't use Vue or React, then just do it manually, e.g.:
```
$('.views').append('<div class="tab view" id="some-view">...</div>');
app.views.create('#some-view')
```
