### ISSUE TITLE
app.views.current not taking navbar into account 

### ISSUE THREAD

**Issue by tdegrunt** [framework7io/framework7#2655]
* Framework7 version: 3.2.1
* Platform and Target: iOS/Android
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
app.views.current does not seem to take into account when a view is pushed through the nav

### To Reproduce
1. Open files, in zip - or check screenshots
2. Click on tab2, check app.views.current = tab2 = correct
3. Click on tab1, check app.views.current = tab1 = correct
4. Click on link item1, check app.views.current = tab1 = is this correct?

### Expected behavior
Upon clicking link item1 I had expected app.views.current to be item1

### Actual Behavior
Upon clicking link item1 app.views.current is tab1

### Screenshots
I've added screenshots of the step I ran through:
<img width="1068" alt="item1" src="https://user-images.githubusercontent.com/46554/45457608-183f2d80-b6f0-11e8-96cd-aec0b4be0518.png">

Here I had expected app.views.current to be item1, but it is tab1

<img width="1068" alt="tab1" src="https://user-images.githubusercontent.com/46554/45457609-183f2d80-b6f0-11e8-83ff-3eb622fd83c2.png">

Here I had expected app.views.current to be tab1, it is tab1, which is correct

<img width="1068" alt="tab2" src="https://user-images.githubusercontent.com/46554/45457610-18d7c400-b6f0-11e8-820f-14dba7f1e94f.png">

Here I had expected app.views.current to be tab2, it is tab2, which is correct

I've included the smallest possible test case in the zip.
[app-demo.zip](https://github.com/framework7io/framework7/files/2377117/app-demo.zip)

**Comment by nolimits4web** [comment]
Don't mess View and Page. Page is what is loaded through router is not a View, it is a Page inside of View
