### ISSUE TITLE
for production, the imported js and css are too big.

### ISSUE THREAD

**Issue by snowdream** [framework7io/framework7#2656]
* Framework7 version: [e.g. ^3.0.0]
* Vue.js version: [e.g. ^2.5.16]
* Platform and Target: [e.g. iOS 11 Cordova app]

### Describe the bug
https://framework7.io/vue/installation.html
I use framework7 by the way: ES Module  as need.
for production, the imported js and css are too big.

### To Reproduce
1. npm run build
2. See error

### Expected behavior
import app.css and vendor.js as need.

### Actual Behavior
the imported js and css are too big.

### Screenshots
![0f41b9da1637690052088e72617ebe87](https://user-images.githubusercontent.com/737958/45469786-840baf80-b75d-11e8-9ec4-d6cac44ffd3f.jpg)

### Additional context
Nothing

**Comment by nolimits4web** [comment]
You can use custom build to make it smaller http://framework7.io/docs/custom-build.html
