### ISSUE TITLE
React Navbar props don't work in iOS theme (Dynamic Navbar)

### ISSUE THREAD

**Issue by dlee** [framework7io/framework7#2659]
* Framework7 version: 3.2
* React.js version: 16.4
* Platform and Target: iOS
* Not working in iOS: https://jsfiddle.net/6sjnh4rq/
* Working in Material: https://jsfiddle.net/aojyp83z/

### Describe the bug
The ergonomic interface for showing/hiding Navbar in React doesn't work for iOS.

### To Reproduce
1. Go to https://jsfiddle.net/aojyp83z/. See everything works in Material theme.
2. Go to https://jsfiddle.net/6sjnh4rq/. See that nothing works in iOS theme.

### Expected behavior
The props provided in React Navbar should work in iOS theme.

### Actual Behavior
The props don't do what they're supposed to do.

### Additional context
There's a non-idiomatic workaround of having to use first fetch the DOM element of the navbar by using `this.$f7.navbar.getElByPage`, then passing that into `this.$f7.navbar.hide`. If this is the only way of accomplishing this, then the React component should be doing this for us.

**Comment by nolimits4web** [comment]
It needs small hack, because in iOS theme navbar is getting detached from page element, so basically you may create empty navbar element that will be reused https://jsfiddle.net/0o1m6uw5/

**Comment by dlee** [comment]
Although the hack works, it's not cross-platform compatible. The React component should be handling this for the user.
