### ISSUE TITLE
page.beforeLeave fired when open smartSelect as popover 

### ISSUE THREAD

**Issue by mohshraim** [framework7io/framework7#2671]
* Framework7 version: 3.2.0
* Platform and Target: Chrome browser

### Describe the bug
I have a page with beforeLeave listener.
Page contain popover AND smartSelect display as popover.
beforeLeave will not fire when open normal popover.. (correct behaviour).
beforeLeave will fire when open smartSelect with `openIn: 'popover'` (wrong behaviour) ==> i Think

I think targeted behaviour to fire beforeLeave if smartSelect opened on popup maybe.. but not when opened as popover or segment..

Thanks

**Comment by nolimits4web** [comment]
It is not about page but about route, and route leave happens here so this callback is fired correctly. You need to disable `routableModals` smart select's parameter
