### ISSUE TITLE
f7-searchbar 🔍 morphing to void on md theme

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2672]
* Framework7 version: 3.3.1 (forked)
* Vue.js version: 2.5.17
* Platform and Target: Cordova Browser Chrome Windows 10
* Live Link or JSFiddle: https://jsfiddle.net/7wjLg9x8/1/ (there is some serious problem with this suff O.o)

### Describe the bug
When I focus the search bar, the magnifying glass animates into nothing and never come back.

### To Reproduce
1) ```<f7-searchbar ref="searchBar" placeholder="Pesquisar" :clear-button="false" :custom-search="true" :disable-button="false" :backdrop="false" />```
2) Theme md
3) Click on searchbox

### Expected behavior
The 🔍 animate to something (and revert the animation after blur)

### Actual Behavior
🔍 animates and morphs into nothing (and never come back)

### Screenshots
![image](https://user-images.githubusercontent.com/379339/45590541-c4f7f580-b910-11e8-843d-c0fe5d46a485.png)

### Additional context
I just added the above line in JSFiddle and all layout went weird O.o
But the 🔍 bug is there, nevertheless.

**Comment by nolimits4web** [comment]
It is because you disabled `:disable-button="false"`, it should morph to disable button

**Comment by nolimits4web** [comment]
seems like it shouldn't do any morph anymation in this case
