### ISSUE TITLE
Tooltip over button in message bar not displaying correctly

### ISSUE THREAD

**Issue by sirlojik** [framework7io/framework7#2681]
I have a chat app am developing using framework7 v3. I tried to add a tooltip to record audio button in messagebar. 

how i created tooltip
```
		window.audioTooltip = app.tooltip.create({
		  targetEl: '#cSendBtn',
		  text: 'Hold to record, release to send',
		});	
		setTimeout(function(){app.tooltip.hide();},3000);
		audioTooltip.show();
```

1) The tooltip is well displayed but after a few seconds, it repositions on the message bar. 

in first screenshot, tooltip is displayed in correct position over send button...after a few seconds, it repositions as on screenshot2. I also noticed the DOM keeps getting populated with new tooltip elements and they become many over time. 

If you notice from the code... the timer is supposed to hide tooltip after 3 seconds but it never hides.

screen shots https://imgur.com/a/qBHKxQb

**Comment by nolimits4web** [comment]
Here is the correct code
```
var audioTooltip = app.tooltip.create({
  targetEl: '#cSendBtn',
  text: 'Hold to record, release to send',
});	
setTimeout(function(){audioTooltip.hide();},3000);
audioTooltip.show('#cSendBtn');
