### ISSUE TITLE
Is there a way to manage deep linking with framework7?

### ISSUE THREAD

**Issue by rapgithub** [framework7io/framework7#2684]
I just ended up with the thing that I will need to make Deep linking from social media to my app and I will like to know if f7 has a way to manage Deep linking ...

for instance redirect user to my app wherever they click a deep linking of social media that is related to my app and goes if possible to that page where the information is inside the APP...

here a simple explanation case:

https://help.tune.com/marketing-console/how-to-deeplink-to-your-mobile-app-from-your-website/

thanks for any ideas or reply regarding this topic!

**Comment by owen-mills** [comment]
I don't think Framework7 has anything to do with this. It's just a styling framework really.
You should look at `cordova-plugin-inappbrowser` for cordova for this I think.

**Comment by nolimits4web** [comment]
And check what i answered here #2658 

>  from social media to my app 

Deep/Universal links can only open app from the domain you own, so you need to setup website anyway.

**Comment by rapgithub** [comment]
thanks
