### ISSUE TITLE
React component type definition missing parameter type for event handlers

### ISSUE THREAD

**Issue by dlee** [framework7io/framework7#2687]
* Framework7 version: 3.3.1

### Describe the bug
React component type definitions are missing parameter type declarations for event handlers. Any time I want to use an event's argument, I get type errors saying that my handler `is not assignable to type '() => void'.`.

### Expected behavior
All Event handler props should have the proper type that gives precise typing for the argument(s) passed to the handler.

**Comment by nolimits4web** [comment]
They are generated automatically, so i can only do it like `(...args: any[]) => void` will it work?

**Comment by dlee** [comment]
Ideally, they should provide the correct signatures for the parameters. However, `any[]` would at least compile without typechecking instead of breaking.
