### ISSUE TITLE
Swiper slide issue (progress-bar not viewing)

### ISSUE THREAD

**Issue by Maheshwbc** [framework7io/framework7#2688]
I am using the framework 7 Swiper Slider its working well.

But while using the swiper slider type as progress-bar its **not visible progress-bar**.

Its only showing bullet pagination.

**Note**

Using version : Framework7 1.6.4

**html**
![screen shot 2018-09-19 at 11 18 38 am](https://user-images.githubusercontent.com/32213371/45733280-cb7eb980-bbfd-11e8-8cb3-45d90f8c60fd.png)

**js**
    var mySwiper = myApp.swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        spaceBetween: 10,
        direction: 'horizontal',
        **type: 'progress'**
    });
    setTimeout(function () {
        mySwiper.init();
    }, 500);

Could you check this code have missed any content.
Thanks in advance

**Comment by nolimits4web** [comment]
Framework7 1.x is not supported anymore

**Comment by Maheshwbc** [comment]
ok Thanks
