### ISSUE TITLE
F7 on Android very slow -> Telerik Native Transitions?

### ISSUE THREAD

**Issue by desmeit** [framework7io/framework7#2691]
F7 v1 and v2 is on my Samsung S5 very slow. It has Android 5.0.
I try to improve it with

* {
box-shadow: none !important;
}

and installed Crosswalk but it is not helping.

Is there a way to work with Native Transitions? For Example Telerik Native Transitions Plugin.
Second question: Is the performance in v3 better? Is there any difference of performance between v1, v2 and v3?

Thanks and best regards (i write here because in the F7 Forum nobody is answering).

**Comment by nolimits4web** [comment]
> i write here because in the F7 Forum nobody is answering

Sorry, it is still not a reason to post here questions
