### ISSUE TITLE
Is there a way to customise the page transitions in F7 so every page has a different transition?

### ISSUE THREAD

**Issue by rapgithub** [framework7io/framework7#2692]
I just need to know if there is a way to customise the page transitions in F7 with a simple directive when opening the page using the router:

I mean something like:

```js

 resolve(
      {
        componentUrl: './pages/page-toload.html', 
        pageTransition: '.transition-push-page'
      },
      {
        context: {},
      });

```
if not possible :(

it will be great if framework7 has this simple method to change page transitions, so some pages has different page transitions than others...  

thanks

**Comment by nolimits4web** [comment]
Only by adding custom class to page and overwriting css animations https://github.com/framework7io/framework7/blob/master/src/core/components/page/page-ios.less#L146-L245
