### ISSUE TITLE
React <ListItem accordionItem> should accept `opened` prop

### ISSUE THREAD

**Issue by dlee** [framework7io/framework7#2693]
* Framework7 version: [e.g. 3.3.2]
* React.js version: [e.g. 16.5.1]
* Platform and Target: all

### Describe the bug
`<ListItem accordionItem>` does not accept the `opened` prop like `AccordionItem`. This makes it hard to have an initially opened item.

**Comment by nolimits4web** [comment]
It has `accordionItemOpened` prop http://framework7.io/react/list-item.html#list-item-properties
