### ISSUE TITLE
Optimize selectors in platform-specific CSS

### ISSUE THREAD

**Issue by dlee** [framework7io/framework7#2700]
* Framework7 version: 3.3.2
* Platform and Target: all

### Describe the bug
A platform specific CSS file should not scope selectors to the platform, since we can assume that the CSS is running on the correct platform. Many styles are scoped to `.ios ...` or `.md ...`, which causes a performance hit due to each matching DOM node needing to traverse up the whole DOM tree.

To complicate the issue, I still see `.md` styles in the `.ios.css` and `.ios` styles in the `.md.css`.

**Comment by nolimits4web** [comment]
Closing as not really actual anymore in v4
