### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by renehauck** [framework7io/framework7#2701]
Hi, first of all, thank you so much for working on this package. I am currently trying to integrate Framework7 (react) into nextjs. Unfortunately I always get the error 
`Uncaught (in promise) Error: window is not defined` 
when SSR is activated. Is it possible to make Framework7 independent of `window`?

Thank you

**Comment by nolimits4web** [comment]
Do you have live link with the issue? Or repo where i can reproduce it? F7 uses `ssr-window` package that should work fine

**Comment by httpiago** [comment]
I also have this problem, I have been trying for 4 months (seriously) to use framework7 with nextjs and I even managed to make it work but i think f7 is not optimized for server-side rendering.

Errors that have already appeared:
- TypeError: Cannot redefine property: $f7
- Error: window is not defined

Here is a simple example [f7-and-nextjs.zip](https://github.com/framework7io/framework7/files/2540840/f7-and-nextjs.zip)
and run the command `npm run dev` for you to reproduce the error.
