### ISSUE TITLE
How can I use this template with cordova?

### ISSUE THREAD

**Issue by ahmu83** [framework7io/framework7#2706]
How can I use this template with cordova? I tried to separate out this folder in the cordova projects www folder but it did not work. The cordova www folder has plain js/css/html and I would like to use this template instead.

**Comment by nolimits4web** [comment]
It is not the template, all templates are here http://framework7.io/templates/

**Comment by ahmu83** [comment]
But I want to use this one as a template. Is it possible?

**Comment by nolimits4web** [comment]
Put content of `kitchen-sink/core` into cordova project `www` folder

**Comment by ahmu83** [comment]
so you mean create a project with `cordova create helloWorld` and replace the content inside www with kitchen-sink/core from the framework7 core?
