### ISSUE TITLE
Something is wrong with the types for RouteParameters

### ISSUE THREAD

**Issue by JasonKleban** [framework7io/framework7#2711]
Something is wrong with the `RouteParameters` type when setting Component to be a react component.   (also, the prop is just accepting `object` right now which makes it harder to discover.

If I don't cast `Splash as any` then I get the error that ``Type 'StatelessComponent<{}>' has no properties in common with type 'Component'.`.  (Splash is a  StatelessComponent<{}>).  Seems to work correctly at runtime so it must just be something wrong with the types.

```ts
export const routes : Router.RouteParameters[] = [
    {
        path: '/',
        component: Splash as any
    },
    ...
}
...
<App params={{ theme: 'ios', routes }}>
```

**Comment by chinfeng** [comment]
The same for me with 4.2.0

**Comment by jjzazuet** [comment]
Same for me. Can this issue get re-opened? Thanks!

**Comment by chinfeng** [comment]
@jjzazuet 

I open a new issue #3107 .

**Comment by rafamel** [comment]
Still an issue
