### ISSUE TITLE
sortable-open or sortable-close links fail if inside a panel

### ISSUE THREAD

**Issue by macsupport** [framework7io/framework7#2716]
* Framework7 version: 3.0.0
* Platform and Target: All
* Live Link or JSFiddle:  [JSFiddle](https://jsfiddle.net/macsupport/9k7aun6e/1/)

### Describe the bug
If links to open or close the sortable list are inside a panel, they do not work but toggle dose.

### To Reproduce
1. Open Panel
2. Click on Open sort or Close Sort
3. See error
4. Click on Toggle Sort and it works as expected

### Expected behavior
sortable-open and sortable-close should work as expected, but fail inside a panel

**Comment by nolimits4web** [comment]
There was issue in docs, fixed it. It should be `sortable-enable` / `sortable-disable`
