### ISSUE TITLE
Предложение по работе с событиями у popup

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2717]
1. У нас есть **popup**, он изначально был в DOM.
2. Мы открываем popup программно, т.е. `app.popup.open('.popup-about');`

Проблема в том, что повесить событие, к примеру, **open**, мы можем в этом случае только глобально, т.е. в **app**.

В документации https://framework7.io/docs/popup.html указан способ: 

```
$$('.popup-about').on('popup:open', function (e, popup) {
  console.log('About popup open');
});
```

но этот способ работает только тогда, когда **popup** открывается не программно, а:

`<a class="link popup-open" href="#" data-popup=".popup-about">Open About Popup</a>`

Предложение: сделать так, чтобы событие можно было повесить и в методе: `app.popup.open()`, а не только в `app.popup.create()`

**Comment by nolimits4web** [comment]
> но этот способ работает только тогда, когда popup открывается не программно

Нет, этот способ работает всегда если popup в DOM'е

> Предложение: сделать так, чтобы событие можно было повесить и в методе: app.popup.open()

Можно просто сделать так

```
const popup = app.popup.get('.popup-about')
popup.once('open', () => { .... });
popup.open();
```

**Comment by nolimits4web** [comment]
Или даже так
```
app.popup.open('.about-popup').once('open', ()=>{ console.log('open') })
```

**Comment by shastox** [comment]
Я наброcал минимальный пример. Почему-то даже пример в документации не работает.
[example.zip](https://github.com/framework7io/framework7/files/2429755/example.zip)

1. Открыть index.html
2. Кликнуть на Open Popup
3. Должно сработать сработать событие и всплыть alert:
```
$('.my-popup').on('popup:open', function (e, popup) {
  alert('About popup open');
});
```

но событие почему-то не обрабатывается.

**Comment by nolimits4web** [comment]
В примере не работает потому что у вас popup в HTML коде расположен после
`<script src="app.js"></script>`

Так делать не надо :) Либо тогда инициализируйте все в `DOMContentLoaded`
