### ISSUE TITLE
Issue with Framework7 VUE Routable tabs. Once you click on each individual tab twice or more. All the links stop working. 

### ISSUE THREAD

**Issue by changliu86** [framework7io/framework7#2719]
I have a issue with Routable tabs in my Cordova Hybrid app ( IOS and Android). 

-  **Live link https://sad-nightingale-f64f59.netlify.com/.**   
username : test@test.com
password:  test

- **Dependencies :**
    "cordova-android": "^7.1.0",
    "cordova-ios": "^4.5.5",
    "framework7": "^2.3.1",
    "framework7-vue": "^2.3.0", 
**( I did a migration to framework7 v3.31, it still has the same problem)** 
    "vue": "^2.5.2",

- **Issue Description:**
The issue is when you click on the routable tabs in the bottom (Feed, Events, Map, Info) twice or more times. All the links stop working. 

- **Ways to reproduce it:**

1. The "bell"  icon on the top right corner is a link to notification page (Other two icons are popups) 
2. Or If you click on the Floating Action Button ( + button) , and the link  "Add Post" and "Add Behavior" stop working. 

![image](https://user-images.githubusercontent.com/37410739/46034116-d047df80-c0cd-11e8-85f5-39bc353232ce.png)

![image](https://user-images.githubusercontent.com/37410739/46033984-8828bd00-c0cd-11e8-95a7-7517b9614424.png)

- **Here are the screenshots of the code on how the rouable tabs are setup.** 

![image](https://user-images.githubusercontent.com/37410739/46032865-bd7fdb80-c0ca-11e8-9f18-aa3b88628718.png)

![image](https://user-images.githubusercontent.com/37410739/46032929-e30ce500-c0ca-11e8-9e73-0569ef0f1550.png)

**Comment by nolimits4web** [comment]
Thanks for the demo. I was clicking for about 5 minutes and everything works fine for me. I would highly suggest to update to latest v3, it has a bunch of fixes for router and routable tabs.

Is this issue only in Cordova app? Because i can't see anything in browser (Chrome)

**Comment by changliu86** [comment]
> Thanks for the demo. I was clicking for about 5 minutes and everything works fine for me. I would highly suggest to update to latest v3, it has a bunch of fixes for router and routable tabs.
> 
> Is this issue only in Cordova app? Because i can't see anything in browser (Chrome)

Thank you very much for the reply. The issue happens in browser (Chrome) as well.  I did a migration to 
framework7 v3.31 and the latest framework7-vue, however, unfortunately I still got the same issue. 

I think might not describe how to reproduce the issue very clearly. The issue is once you click on each of those tabs(Feed, Events... )  in the bottom twice or more times **continuously**, (**Notes: All the other clickable are popups not links except those I mentioned below) .**   the "Bell" icon, which is a link to notification page stop working. 

![image](https://user-images.githubusercontent.com/37410739/46147735-52eaaf00-c234-11e8-9b1e-ab1e3d0f317c.png)


Also this happens If you click on the Floating Action Button ( + button) , and the link "Add Post" and "Add Behavior" stop working. 
![image](https://user-images.githubusercontent.com/37410739/46147029-49604780-c232-11e8-9ca9-5405896429ce.png)

In addition, if you click on the "Events"  tab, twice or more, the Floating Action Button ( + button) stops  working
![image](https://user-images.githubusercontent.com/37410739/46147213-e0c59a80-c232-11e8-9ee3-eed387ec6672.png)

Let me know if you still have a problem on how to reproduce this issue.  

Thanks!

**Comment by nolimits4web** [comment]
Ok, found the issue. It is because you have routable tabs under with `async` route. Pushed fix for this, will be in next release on a days
