### ISSUE TITLE
Small issue on events for sortable

### ISSUE THREAD

**Issue by etiennea** [framework7io/framework7#2721]
+ framework7-vue@3.3.2
+ framework7@3.3.2

`<f7-list media-list sortable @sortable:sort="onSort" @sortable:enable="onSortOpen" @sortable:disable="onSortClose">`

Only onSort fires, the other two never do. They used to.

**Comment by nolimits4web** [comment]
Can't replicate it, works for me in latest version. Would be good to see live example or JSFiddle with the issue
