### ISSUE TITLE
Bug on selectbox (impossible to choose an option)

### ISSUE THREAD

**Issue by SpiderNeo1** [framework7io/framework7#2723]
* Framework7 version:  3.3.2
* Platform and Target: iPhone 5S on iOS >= 9.0 with Cordova

### Describe the bug
I can't set an option on a selectbox.

### To Reproduce
On kitchen-sink, menu "form-storage" or "Inputs". When I try to choose an option in "Gender". Change from "Male" to "Female" for example.
I didn't touch anything.

### Expected behavior
I think that it misses a button "ok" at the top right after having selected the choice like what proposes a navigator when there is a drop-down list.

Thank you.

**Comment by nolimits4web** [comment]
> I think that it misses a button "ok" at the top right after having selected the choice like what proposes a navigator when there is a drop-down list.

Not related to Framework7. If you are using cordova keyboard plugin, make sure you don't hide keyboard accessory bar https://github.com/cjpearson/cordova-plugin-keyboard#keyboardhideformaccessorybar

**Comment by SpiderNeo1** [comment]
Ok, I will test that.

But is it better to use your link or this plugin https://github.com/ionic-team/cordova-plugin-ionic-keyboard ?

I'm using this plugin for the wkwebview https://github.com/ionic-team/cordova-plugin-ionic-webview

Thank you.
