### ISSUE TITLE
Framework7-Vue Tabs + Navigation Bug

### ISSUE THREAD

**Issue by qkdreyer** [framework7io/framework7#2724]
* Framework7 version: ^3.0.0
* Vue.js version: ^2.5.16
* Platform and Target: Every browser
* Live Link:
  * https://framework7-template-vue-webpack-dev-xonicljsec.now.sh
  * https://framework7-template-vue-webpack-build-bsiiaectsz.now.sh
* Source code: https://github.com/qkdreyer/framework7-template-vue-webpack/commit/3ecad82271d70f891ed7f4ba662f8268447ea465

### Describe the bug
Navigation in tabs can be blocked by a specific reproductible edge case.

### To Reproduce
1. Click on f7-tab "Tab1" (bottom left)
2. Click on f7-link "Increment tab" twice (until you see Tab1 #3)
3. Use the top left f7-navbar back-link
4. Click on f7-link "Increment tab" once
5. You cannot use the top left f7-navbar back-link anymore

### Expected behavior
Using the top left f7-navbar back-link should trigger a back navigation

### Actual Behavior
Using the top left f7-navbar back-link is void

### Screenshots
- dev on localhost : http://g.recordit.co/cfTs7YmUWZ.gif
- dev on now.sh : http://g.recordit.co/kCGLjcyc4R.gif
- build on now.sh : http://g.recordit.co/RuDACDo3OZ.gif

**Comment by qkdreyer** [comment]
Did you have time to look at it @nolimits4web ?

**Comment by qkdreyer** [comment]
Bump :(

**Comment by nolimits4web** [comment]
Is there a real usecase of such thing?

**Comment by nolimits4web** [comment]
Ok, but why do you use routable Tabs here, looks like it can be used as usual pages.

**Comment by nolimits4web** [comment]
Also noticed, you have `page` under tab. It is not supported. Page in Page is not supported

**Comment by qkdreyer** [comment]
Because I have multiple tabs : http://g.recordit.co/PAFvbL5vXI.gif

**Comment by qkdreyer** [comment]
It's working very well, it's pretty sad that going forward twice, back once, forward once, back twice is not working :/

**Comment by qkdreyer** [comment]
I'd like to patch it, but I didn't find what's causing this bug yet. Maybe you could give me a starting point ?

**Comment by qkdreyer** [comment]
Sadly this doesn't have any effect

**Comment by qkdreyer** [comment]
Did you think about another workaround @nolimits4web ?

**Comment by qkdreyer** [comment]
I’m still waiting for any advice/solution if that’s possible.

**Comment by qkdreyer** [comment]
Did you think about another workaround @nolimits4web ? The one you gave me earlier never worked :/
