### ISSUE TITLE
Framework7 overriding parameter StatusBarStyle in config.xml?

### ISSUE THREAD

**Issue by achubutkin** [framework7io/framework7#2728]
* Framework7 version: 3.3.2
* Platform and Target: Android 6+ 
* cordova-plugin-statusbar: ^2.4.2

### Describe the bug
Framework7 overriding parameter StatusBarStyle in config.xml.

### To Reproduce
1. Set **StatusBarStyle** parameter in config.xml to **lightcontent** (light text in dark background)
2. In your Framework7 app instance set parameter **statusbar/enabled** to **true** (or not set, by default still is true).
3. Run app in Adnroid 6+. 

### Expected behavior
Light text in dark background of statusbar.

### Actual Behavior
Dark text in dark background of statusbar.

P.S. 
If set **iosTextColor** parameter to **white** I will get expected behavior. 

### Screenshots

![image](https://user-images.githubusercontent.com/21987044/46130826-0d41dc80-c25c-11e8-9f69-ec6ea4c5cbc4.png)

**Comment by nolimits4web** [comment]
Hi, yes. If `statusbar.enabled` then it will use API to overrwrite it depending on statusbar parameters. I just pushed fix which adds android related parameters
