### ISSUE TITLE
Typescript .d.ts files for components 

### ISSUE THREAD

**Issue by shmuelgutman** [framework7io/framework7#2729]
* Framework7 version: 3.3.2
* Vue.js version: 2.5.17
* Platform and Target: all

Hi, 
Is it expected to have a declaration files (.d.ts) for componens? like in the React version?

**Comment by nolimits4web** [comment]
Expected but at the moment we couldn't find correct syntax for it. Can you help with it?

**Comment by shmuelgutman** [comment]
Not sure but a quick digging in the Vue types I found this:
https://github.com/vuejs/vue/blob/79cabadeace0e01fb63aa9f220f41193c0ca93af/types/options.d.ts#L55

**Comment by nolimits4web** [comment]
Saw that thanks. But i'm wondering how can we write Vue- equivalent of what we have for React, e.g. for this https://github.com/framework7io/framework7/blob/master/packages/react/components/messagebar.d.ts
