### ISSUE TITLE
Virtual list searchbar fails on pagereinit

### ISSUE THREAD

**Issue by knmr** [framework7io/framework7#2732]
* Framework7 version: 3.3.2
* Vue.js version: 2.5.17

### Describe the bug
Searchbar in combination with virtual list results in TypeErrors after opening the virtual list page for the second time.

### To Reproduce

Create project using vue webpack template.
Create a page using the sample code provided for the virtual list (f7 vue).
Create another simple page.
Run the app. Navigate to the virtual list page, run a search: it works fine.
Navigate to page 2, then navigate back to virutal list page, try to run a search, you get after typing any key in the input field

### Expected behavior
After using the search for the second time, I would expect the search to give the same results as the first time.

### Actual Behavior
Getting undefined errors on typing and when clicking the clear field button

### Additional:
Uncaught TypeError: Cannot read property ‘params’ of undefined
at Searchbar.search (framework7.esm.bundle.js?c501:17971)
at HTMLInputElement.onInputChange (framework7.esm.bundle.js?c501:17745)
at HTMLInputElement.handleEvent (dom7.module.js?d8c4:333)

**Comment by nolimits4web** [comment]
Please provide live example or better JSFiddle with the issue

**Comment by knmr** [comment]
I tried to reproduce it in jsfiddle but it was getting late. Here is a reproducation:

https://jsfiddle.net/bn6sz5q9/

Basically navigate to the Virtual list page, then navigate to another page(Form page) with the button inside the page and then navigate to the virtual list page again via the button on the Form page.

**Comment by nolimits4web** [comment]
Issue is you loading same page with virtual list instead of going back to it, if you need such logic then use unique selectors on each instance of such page, otherwise use `$f7router.back()` https://jsfiddle.net/bn6sz5q9/2/

**Comment by knmr** [comment]
Sorry for the late response. Thank you for your help. I ended up adding a unique selector for each instance. My users can navigate to the virtual lists directly using the navbar menu. Using $f7router.back() was not an option.
