### ISSUE TITLE
Fix bug Accordion on iOS 9 not applied correctly

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#2735]
* Framework7 version: 3.4.0
* Platform and Target: iOS 9.x

### Describe the bug
The correction to the bug (#2731) it has not been applied correctly.

### To Reproduce
The bug is still present by visiting the page (which currently has version 3.4.0 of framework7)

http://framework7.io/kitchen-sink/core/?theme=ios

with iOS 9.x

### Expected behavior
The change had to be made to the file

`framework7/src/core/components/accordion/accordion.js`

and not to the file

`packages/core/components/accordion/accordion.js`

Please @SpiderNeo1 you make this correction? Thank you.

**Comment by SpiderNeo1** [comment]
Oops, sorry ! In a hurry, I was wrong.
Thank you for the correction !
