### ISSUE TITLE
Incorrect display of the statusbar on first start app in iOS

### ISSUE THREAD

**Issue by achubutkin** [framework7io/framework7#2736]
* Framework7 version: 3.3.2
* Platform and Target: iOS
* cordova-plugin-statusbar: ^2.4.2

### Describe the bug
Incorrect display of the statusbar on first start app in iOS and then change device orientation. This applies to all iPhone devices **(except iPhone X)**.

### To Reproduce
1. Set **fullscreen** parameter in config.xml to **true**
2. Set **StatusBarOverlaysWebView** parameter in config.xml to **true**
3. In your Framework7 app instance set parameter **statusbar/enabled** to **true** (or not set, by default still is true).
4. In your Framework7 app instance set parameter **statusbar/overlay** to **'auto'** (or not set, by default still is 'auto').
5. Build and run app on iPhone devices (except  iPhone X).
6. Change the orientation of the device in any direction.

### Expected behavior
Correct check of overlapping statusbar and correct display (see image, from portrait to landscape).

![simulator screen shot - iphone 8 plus - 2018-09-29 at 14 12 53](https://user-images.githubusercontent.com/21987044/46244216-4a91a000-c3fd-11e8-8eb3-b1f93dd4ebf5.png)

### Actual Behavior
Incorrect check of overlapping statusbar and incorrect display (only once). Further turns of the device work correctly (see image, from portrait to landscape).

![simulator screen shot - iphone 8 plus - 2018-09-29 at 14 12 19](https://user-images.githubusercontent.com/21987044/46244227-7d3b9880-c3fd-11e8-9775-9a0385eaa94e.png)

### Additional

**Statusbar.checkOverlay() method is called twice when the orientation changes and this leads to an incorrect calculation of the screen size.** After the first rotation, this method is called only once and works correctly. In framework7.js here:

        if (Device.ios && (Device.cordova || Device.webView)) {
          if (win.orientation === 0) {
            app.once('resize', function () { 
              Statusbar.checkOverlay(); // <<<<<<<<<<<<< only once and first (add class .with-statusbar to html tag)
            });
          }

          $(doc).on('resume', function () {
            Statusbar.checkOverlay();
          }, false);

          app.on(Device.ios ? 'orientationchange' : 'orientationchange resize', function () {
            Statusbar.checkOverlay(); // <<<<<<<<<<<<< second (remove class .with-statusbar from html tag)
          });
        }

If in your Framework7 app instance set parameter **statusbar/overlay** to **true** (only for iOS and fullscreen mode!), you will not observe a similar phenomenon. All works correctly on all iPhone devices (include iPhone X).

**Comment by nolimits4web** [comment]
Well, took me a while to test this out. So the event handlers are correct, and issue can be related to Cordova's UIWebView which has some issue with safe-areas. Issue can be solved with 
* using WKWebView
* setting `StatusBarOverlaysWebView` to true
* adding `html, body { height: 100vh }` to the CSS rules (when app running under iOS)

**Comment by achubutkin** [comment]
Thank you so much for your help, Vladimir!

- I forgot to write that I used WKWebView, sorry
- `StatusBarOverlaysWebView` has already been set to true
- **Adding `html, body { height: 100vh }` to the CSS rules really helped!** 

My current solutions for this behavior:
```
  statusbar: {
    enabled: Framework7.device.ios && Framework7.device.webView,
    overlay: Framework7.device.ios || 'auto',
  },
```
