### ISSUE TITLE
Hopefully, don't top the navbar when I click on the form！！！

### ISSUE THREAD

**Issue by zhengmenglin** [framework7io/framework7#2738]
* Framework7 version: [e.g. 3.0.0]
* Vue.js version: [e.g. 2.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Describe the bug

When I click on the form，the navbar is topped up messages page in IOS. This is very serious, hope you can solve it quickly，thank you very much！We urgently need a stable framework！

### Expected behavior

Hopefully, don't top the navbar when I click on the form！！！
In a word, I hope the navbar have always had ！！
Thank you very much !!!

### Actual Behavior
Explain what is actually happening

### Screenshots

HOPE：

<img width="288" alt="wx20180930-153948 2x" src="https://user-images.githubusercontent.com/38604167/46254791-70837700-c4c7-11e8-87b1-2ee0140aeb32.png">
<img width="352" alt="wx20180930-154057 2x" src="https://user-images.githubusercontent.com/38604167/46254792-711c0d80-c4c7-11e8-9012-ec44b959e12f.png">

Don't want to :
<img width="341" alt="wx20180930-154024 2x" src="https://user-images.githubusercontent.com/38604167/46256321-a29ed400-c4db-11e8-974f-36dd71bbe10c.png">
<img width="361" alt="wx20180930-154127 2x" src="https://user-images.githubusercontent.com/38604167/46256322-a3d00100-c4db-11e8-9e73-da733e94fd2f.png">

**Comment by nolimits4web** [comment]
You need to use [cordova-plugin-keyboard](https://github.com/cjpearson/cordova-plugin-keyboard#readme) and set `Keyboard.shrinkView(true)` on app init
