### ISSUE TITLE
Scrolling inside animated tabs not working

### ISSUE THREAD

**Issue by shaulhadar** [framework7io/framework7#274]
Hi Vlad, I have been working with the kitchen sink and learning it and also the f7 docs.  I have made some test, and added the animation option to the tabs in the kitchen sink project.  But when i do this, the content inside the tabs is not scrollable any more.  if i use the regular tabs without animation, than it is scrollable.

this is the code i have in the tabs page:

Is this a bug or did I miss anything?

Thanks,
Shaul.

**Comment by TawabG** [comment]
If you're like me and you copied the ''get started lay-out from the docs'' you'll need to change this class (<div class="pages">)  

Example:
.pages {
   overflow: auto;
  -webkit-overflow-scrolling: touch;
}

That'll fix it.

**Comment by felipefrancisco** [comment]
```
   .tabs-animated-wrap > .tabs > .tab  {
     overflow: auto;
     -webkit-overflow-scrolling: touch;
   }
```
This solved my issue.
