### ISSUE TITLE
Performing action past certain scroll point.

### ISSUE THREAD

**Issue by JosephShenton** [framework7io/framework7#2743]
* Framework7 version: 1.7.1
* Platform and Target: All browsers and platform

### Describe the bug
I am trying to have my app perform a certain action when the user scrolls past a certain point however it seems like with Framework7 this isn't possible. Is there a certain reason why?

### To Reproduce
You can even use the kitchen sink to test this, just add one or all of these to the javascript file and try scrolling, nothing will happen.

```
var $document = $$('.views'),
    $element = $$('.navbar'),
    className = 'hasScrolled';

$document.scroll(function() {
  if ($document.scrollTop() >= 50) {
    myApp.alert('over 50');
  } else {
    myApp.alert('under 50');
  }
}); 

window.addEventListener("scroll",function(){
  if(window.pageYOffset > 10){
   myApp.alert('over 10');
  }
  else if(window.pageYOffset < 10){
    myApp.alert('under 10');
  }
},false);

$$('.pageContent').scroll(function () {
    var y = $$(this).scrollTop();
    if (y > 100) {
        myApp.alert('over 100');
    } else {
        myApp.alert('under 100');
    }

});
```

### Expected behavior
It is expected to show the alert if the user has scrolled past the certain point.

### Actual Behavior
Nothing happens at all.

**Comment by nolimits4web** [comment]
You need to attach scroll event listeners to page-content element. Also 1.7.1 is not supported anymore
