### ISSUE TITLE
Infinite Loader problem when items are not equal in size... per load :(

### ISSUE THREAD

**Issue by rapgithub** [framework7io/framework7#2744]
I am using the infinite loader to load swiper galleries of hotels, these hotels has 3-10 images per hotels so I create a list of hotels using the swiper... this works well...

using now the infinite loader I create the next swiper gallery for the next hotel dynamically when scrolling down... no problem whatsoever...

but I use filter in these screen so if I have in my list 200 hotels to show and then I show 5 hotels per load, then 250/5 = 40 this means 40 loads to load all..

the problem happens when I apply filter and I have now not 200 hotels but only the best hotels to show and after applying this filter the hotels to show are 57 for saying something... then I start scrolling and fine but right after getting to the end the console show the error...

it cannot find the next array elements to show because simply they do not exist... this is because

57/5 = 11,4 this means 11 loads and the last load 0,4 cannot show because it is missing....

is there a way the infinite loader can detect automatically the size of the array even if I want to show 5 per load.... and show accordingly without having this error when the quantity to show is more than the rest to show?

any solution for this?
thanks

**Comment by rapgithub** [comment]
in the moment I have pached the script like this but it will be a good solution if F7 has it incorporated having in count this issue above:


```js
  return {
    data: function () {
      return {
        allowInfinite: true,
        hasMoreItems: true,
        maxItems: 16,
        lastItem: 11,
        itemsPerLoad: 2,
        items: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11],
      }
    },
    methods: {
      loadMore: function () {
        var self = this;

        var $ = self.$$;
        if (!self.allowInfinite) return;
        self.allowInfinite = false;

        setTimeout(function () {
          if (self.lastItem >= self.maxItems) {
            self.$setState({
              hasMoreItems: false,
            });
            return;
          }



          for (var i = 1; i <= self.itemsPerLoad; i++) {
            self.items.push(self.lastItem + i);
          }

          self.allowInfinite = true;

          self.$setState({
            lastItem: self.lastItem + self.itemsPerLoad,
            items: self.items,
          })


          maxRemaining = (self.maxItems-self.lastItem);
          //console.log(maxRemaining);


          if ((self.itemsPerLoad > maxRemaining)) {

            maxRemaining = (self.maxItems-self.lastItem);
            console.log(maxRemaining);

            self.$setState({
              itemsPerLoad: 1,
            });
          }

        }, 1000);
      }
    }
```

**Comment by rapgithub** [comment]
Also is it possible to use template with handlebars to create the cards we want to display on scrolling down using infinite scroller?

**Comment by nolimits4web** [comment]
Sorry, but it doesn't related to infinite scroll. The main purpose of this component is to just fire an `infinite` event when you are at the bottom of the page. The thing you are talking is about custom logic and math.
