### ISSUE TITLE
F7 Swiper is reinitializing inside virtual list

### ISSUE THREAD

**Issue by adnanmasd** [framework7io/framework7#2747]
* Framework7 version: [e.g. 2.0.0]
* Platform and Target: [e.g. Chrome browser]

### Describe the bug
I have swiper inside the virtual list which gets reinitialized on scrolling. Further the items in virtual list items have different height. I have tried rowsBefore and rowsAfter with different combinations but couldnot get it work.

### To Reproduce
1. Add 5 or 6 swiper to the page so that you can scroll
2. Scroll down and the items before the screen will be removed, but when added again, reinitialized

### Expected behavior
It should be kept in the cache and be viewed as virtual list normally shows the item.

### Actual Behavior
It is reinitializing the swiper which in turn making API calls to fetch the data. This makes delay in loading the page.

### Additional context
The swiper are added through Vue Component

**Comment by nolimits4web** [comment]
Would be good to see JSFiddle with the issue

**Comment by adnanmasd** [comment]
hi @nolimits4web ,

The issue I am facing seems to be in android only. The browser and ios are working fine.

Would it be possible that you download the app (live on playstore) to see the issue and if you require to look into the code, we can connect with each other remotely and you can review the code.

**Comment by nolimits4web** [comment]
If i install app i can't see the nature of the issue. It will be better if you can setup minimal JSFiddle where i can see the issue
