### ISSUE TITLE
url or templateUrl support return script

### ISSUE THREAD

**Issue by aldoexpert** [framework7io/framework7#2748]
I combine Framework7 with PHP7.2
now I like use componentUrl because that I can manage code and framework7 code by file

now, can possible if feature route with **url** or **templateUrl** but support **return** script
`<script>
return {
	on: {
		pageInit: function (e, page) {
			// script for this page after load url
		},
	}
}
</script>
`
Are that possible?
becase I need that for manage code for more flexible
2 year I'm use framework7 and not have issue but this important case I found in my project

**Comment by nolimits4web** [comment]
`templateUrl` with return `script` is already what `componentUrl` is
