### ISSUE TITLE
The input box on the android browser is blocked by the keyboard

### ISSUE THREAD

**Issue by idreamin** [framework7io/framework7#2749]
The input box on the android browser is blocked by the keyboard in messages page  

![wechatimg8176](https://user-images.githubusercontent.com/38604167/46396409-ef73ec00-c721-11e8-8c69-999f61fdaf27.jpeg)

**Comment by templatetuners** [comment]
same here :(

**Comment by mohshraim** [comment]
did you find a solution for this?
