### ISSUE TITLE
Cannot use Framework7.request to send payload as application/json

### ISSUE THREAD

**Issue by mbplautz** [framework7io/framework7#2751]
* Framework7 version: 3.2.0
* Platform and Target: Cross-platform
* Live Link or JSFiddle: https://mbplautz.github.io/app/

### Describe the bug
When using `Framework7.request` to send AJAX requests, JSON payloads are always being converted to FormData.

### To Reproduce
1. Navigate to the Live Link: https://mbplautz.github.io/app/
2. Enable your browser's dev tools so you can see network traffic
3. Open the left side panel
4. Click **Send Ajax Post Request >**
5. You will note that the JSON payload has been converted to FormData and its integrity has not been preserved. See the image below.

### Expected behavior
I expect that I will get a stringified version of my JSON payload and not a FormData "param1=value&param2=value" payload.

### Actual Behavior
My data is being serialized into a payload that I would not expect.

### Screenshots
![Network Traffic](http://forum.framework7.io/uploads/default/optimized/1X/167702144e7ebf83b7eb2a7e876376d77fecd8d3_1_690x290.PNG)

### Additional context
My recommendation is to support a 4th type of content type, application/json. This will allow sending of literal values like `null`, which are supported by JSON and not by Form Data.

If the code in the repository path for src/core/utils/request.js on lines 177-179 were changed from this:
```
        } else {
          postData = data;
        }
```
to this:
```
        } else if (options.contentType === 'application/json') {
          postData = JSON.stringify(options.data);
        } else {
          postData = data;
        }
```
then this problem would be fixed entirely.

**Comment by nolimits4web** [comment]
There is `.postJSON` method that will post it as JSON as you need it:
```
app.request.postJSON('/app/index.html', { isAString: 'true', isABoolean: true, isNull: null, isObject: { yes: 'itIsAnObject' } }, console.log, console.err);
```

But i think it makes sense if contentType is set to `application/json` then it should be sent as JSON by default, will add it
