### ISSUE TITLE
Typescript definition error for new Framework7(on:{...})

### ISSUE THREAD

**Issue by jdspugh** [framework7io/framework7#2752]
* Framework7 version: [e.g. 3.4.0]
* Platform and Target: All

window.app = new Framework7({
  ...
  on: {
    init: function(): void {
    }
  }
});

Gives the error:

[ts]
Argument of type '{ name: string; statusbar: { overlay: true; }; panel: { swipe: string; swipeOnlyClose: true; }; routes: RouteParameters[]; on: { init: () => void; }; }' is not assignable to parameter of type 'Framework7Params'.
  Types of property 'on' are incompatible.
    Type '{ init: () => void; }' is not assignable to type '{ init: () => void; 'resize': () => void; 'orientationchange': () => void; 'click': (event: Event) => void; 'touchstart:active': (event: Event) => void; 'touchmove:active': (event: Event) => void; 'touchend:active': (event: Event) => void; ... 186 more ...; vlItemsAfterInsert: (virutalList: VirtualList, fragment: Do...'.
      Property ''resize'' is missing in type '{ init: () => void; }'.

### Solution:
Change line 66 in app-class.d.ts from
  on?: { [event in keyof Framework7Events]: Framework7Events[event] };
to
  on?: { [event in keyof Framework7Events]?: Framework7Events[event] };

**Comment by nolimits4web** [comment]
Thanks, fixed in src
