### ISSUE TITLE
Sheet "Pull from Bottom" component

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2753]
**Is your feature request related to a problem? Please describe.**
Not really. Just a common UI pattern that is missing.

**Describe the solution you'd like**
Like Uber, a draggable bottom sheet

**Describe alternatives you've considered**
No alternatives considered so far.

**Additional context**
https://medium.com/android-bits/android-anchoring-views-to-bottom-sheet-9c9069caf7d4
https://www.youtube.com/watch?v=md_mkKZy1kk 
https://br.pinterest.com/pin/656399714408907152/?lp=true

**Comment by willmero** [comment]
Similar/cross functionality with:
#3100
