### ISSUE TITLE
Left panel backdrop glitch on panel swipe

### ISSUE THREAD

**Issue by geoorg30** [framework7io/framework7#2754]
Using version 3.4.0
Platform and target: android (MD theme)

### Describe the bug
There is a glitch on the left panel backdrop when swiping.
The backdrop dissappears then quickly appear again when swiping to open the left panel
This doesnt happen when opening the panel with link
The issue is there on the kitchen-sink also

### To Reproduce
1. Swipe to open left panel
2. Backdrop dissappears then quickly comes back...glitch

### Expected behavior
A smooth transition of the left panel backdrop when swiping.

This issue does not exist in version 3.1.1 
(Maybe you will find this helpful?)

**Comment by provoaggie** [comment]
I'm experiencing this issue as well. I've done some testing and it appears that this bug appeared in 3.3.0. It didn't happen in 3.2.0 or 3.2.1.
