### ISSUE TITLE
Can i use vue-router with f7-vue?

### ISSUE THREAD

**Issue by yinfxs** [framework7io/framework7#2759]
* Framework7 version: [e.g. 3.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
No
