### ISSUE TITLE
Can you add a global method to perform the routing change? Because the title of each page may not be the same.

### ISSUE THREAD

**Issue by zdliuccit** [framework7io/framework7#2760]
Can you add a global method to perform the routing change? Because the title of each page may not be the same.

**Comment by nolimits4web** [comment]
Would be good to see more explanation

**Comment by zdliuccit** [comment]
@nolimits4web 
For example, the title of the home page is called "xxx home page", jumping to the list of goods page, Title needs to be changed to "list of goods", click back to the home page, title can be changed to "xxx home page".

Functions similar to vue-router. When defining a route, you can set custom properties in meta, such as title, and then perform a jump through the routing hook function to get the title of the next route, thereby setting document. title.

A function can monitor the current routing change function, and can get the relevant information of the current route.
