### ISSUE TITLE
SearchBar hide custom group headers

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2761]
**Is your feature request related to a problem? Please describe.**
I'm using a 3 level nested data item listing with searchbar:

```
<div v-for="first-level">
    <f7-block-title>Title of first level<f7-block-title>

    <div v-for="second-level">
        <f7-block-header>Title of second level</f7-block-header>
         <f7-card v-for="third level" />
    </div>
</div>
```

So I have a list of _companies_, each with a list of _product categories_, each with a list of _products_.

Search works fine (beside the detail that <f7-searchbar> *must* be inside searched container ¬¬), using those settings:

```
<f7-searchbar :key="'searchBar'" placeholder="Pesquisar" disable-button-text="Cancelar" remove-diacritics :backdrop="false" :clear-button="false"
				search-container=".list-products-page" search-in=".card-header" search-item=".card" />
``` 

But, my <f7-block-title> (header of first level) and <f7-block-header> (header of second level) are not being hidden when there are no cards available (so, my _product category_ (2nd level) is empty).

**Describe the solution you'd like**
Overload the `hide-groups` to accept also a string to mark an item as the group of another.
In my example, the div for second level could have a class like `.group` and <f7-searchbar> would hide (as it already does for the list-view-group).

Not sure how to do this for 3 (or more) levels like this (perhaps a cascade?)

**Describe alternatives you've considered**
None so far.

**Additional context**
![image](https://user-images.githubusercontent.com/379339/46641060-dca84f80-cb45-11e8-8e7d-4a279fc2ba54.png)

Restaurantes Fictício (1st level), with Bebidas (beverages as 2nd level) and two products inside the beverages section (3rd level).

If I search something that is not found:

![image](https://user-images.githubusercontent.com/379339/46641086-05304980-cb46-11e8-90f7-d0734cbf8077.png)

Also, couldn't make `found-el` and `not-foud-el` to work. (notice that the documentation is wrong (foud instead of found).

The expected behavior was to searchbar hide everything `.searchbar-not-found` at show everything `.searchbar-found`. Exchanging those visibilities when search found nothing, but all elements are present in screen at all times =\

**Comment by nolimits4web** [comment]
Can you please give me some demo HTML content that i can work/test with?

**Comment by nolimits4web** [comment]
Ok, pushed fix with new `searchGroup` and `searchGroupTitle` parameters to accept custom groups and titles. For understanding here is the HTML code that works correctly:
```
<div class="page">
  <div class="navbar">
    <div class="navbar-inner">
      <!-- ... -->
      <form
        data-search-container=".search-container"
        data-search-in=".card-header, .card-content"
        data-search-item=".card"
        data-search-group=".search-group"
        data-search-group-title=".block-header" 
        class="searchbar searchbar-expandable searchbar-components searchbar-init"
      >
        <!-- ... -->
      </form>
    </div>
  </div>
  <div class="page-content search-container">
    <div class="search-group">
      <div class="search block-title" style="color: rgb(32, 32, 32);"><span style="text-decoration: line-through;">Company A</span></div>
      <div>
        <div class="block-header">Beverages</div>
        <div class="card">
          <div class="card-header">Coca-Cola</div>
          <div class="card-content card-content-padding">
            Would be nice to be searchable as well
          </div>
          <div class="card-footer"></div>
        </div>
        <div class="card">
          <div class="card-header">Wine</div>
          <div class="card-content card-content-padding">

          </div>
          <div class="card-footer"></div>
        </div>
      </div>
      <div>
        <div class="block-header">Food</div>
        <div class="card">
          <div class="card-header">Meet Meet</div>
          <div class="card-content card-content-padding">
            Would be nice to be searchable as well
          </div>
          <div class="card-footer"></div>
        </div>
        <div class="card">
          <div class="card-header">Potato</div>
          <div class="card-content card-content-padding">

          </div>
          <div class="card-footer"></div>
        </div>
      </div>
    </div>
    <div class="search-group">
      <div class="search block-title" style="color: rgb(32, 32, 32);"><span style="text-decoration: line-through;">Company B</span>
      </div>
      <div>
        <div class="block-header">Cars</div>
        <div class="card">
          <div class="card-header">Honda</div>
          <div class="card-content card-content-padding">
            Awesome car
          </div>
          <div class="card-footer"></div>
        </div>
        <div class="card">
          <div class="card-header">BMW</div>
          <div class="card-content card-content-padding">
            Event better?
          </div>
          <div class="card-footer"></div>
        </div>
      </div>
    </div>
  </div>
</div>
```
