### ISSUE TITLE
Unsure how to keep F7 from removing elements with "swipeout"

### ISSUE THREAD

**Issue by ozra** [framework7io/framework7#2763]
- framework7-react@3.4.0
- react@16.5.2
- ubuntu × browser (any)

Where I looked / read
- In the f7-react-docs I don't find any info on how to make F7 keep it's nosy fingers out of the DOM.
- In the f7-core-docs there's a mention of  `swipeout: { removeElements: false }`, which I try to pass to F7App component in props, and also under `params` property of props, but it doesn't help.

So, how do I go about that? Naturally the ui-changes should be done via react-renders, from changes to the data, not "magic DOM manipulation"...

**Comment by nolimits4web** [comment]
`swipeout: { removeElements: false }` will disable F7 from removing swipeout element from DOM. If you need to prevent "delete" animation the it can't be prevented. In this case use your own swipeout delete button

**Comment by ozra** [comment]
Yes, however — _the configuration is not working_ — that's the issue.

**Comment by nolimits4web** [comment]
Example or JS Fiddle with none working example will be good

**Comment by ozra** [comment]
I think I'm just passing the conf in the wrong place or so? So here's a short excerpt of the conf-part which might show _what I'm doing wrong_.

My intention is for the _list-element to remain_, if I was unclear.

```typescript
/*
    ... cut away stuff ...
*/
export class App extends Component<AppProps, AppStateSpec> {
    /*
    ... cut away stuff ...
    */
    render() {
        _D("App::render ->")
        const s = this.state

        if (!s.is_fw7_ready) {
            return K(Spinner, { size: "90%" })

        } else {
            return K(React.Fragment, null,
                K(F7App, {
                    params: {
                        name: "Some name",
                        id: "some-id",
                        theme: "auto",
                        routes: some_routes,

                        swipeout: {
                            removeElements: false
                        },
    
                    },
                },
                    K(Statusbar),
                    K(LeftNavPanelAct),
                    K(View, this.main_view_conf)
                )
            )
        }
    }
}
```
