### ISSUE TITLE
page count more than 3,when back,it will be init again

### ISSUE THREAD

**Issue by pomelo828** [framework7io/framework7#2766]
step : PageA-->PageB-->PageC
Now , PageA removed .
when back to PageA , It will be init again .
but i don't want to init the PageA .

Please don't mind my poor English. -。-

**Comment by nolimits4web** [comment]
Check `stackPages` parameter http://framework7.io/docs/view.html#view-parameters

**Comment by pomelo828** [comment]
thanks !
谢谢，好人一生平安！(chinese)
