### ISSUE TITLE
List Item CheckBox not working if other elements on screen

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2767]
* Framework7 version: 3.4.0 (forked from master)
* Vue.js version: 2.5.17
* Platform and Target: Cordova Browser Windows 10 Chrome 69
* Live Link or JSFiddle: https://jsfiddle.net/2nv1txrk/

### Describe the bug
1. Open the fiddle above and click on the list-item to check the checkbox (doesn't work)
2. Comment those lines:

![image](https://user-images.githubusercontent.com/379339/46776324-6fc9bc80-cce1-11e8-8581-3c323c24b2ed.png)

3. Now everything works.

On my live project, a `<f7-toobar>` triggers the bug (on fiddle, only the h1 does so)

### Additional context
I'm trying to add the selected ids to an array to bulk delete (or edit them, if only one is selected).

**Comment by nolimits4web** [comment]
You sure that JSFiddle correct?

**Comment by JCKodel** [comment]
Sorry about that.

https://jsfiddle.net/2nv1txrk/1/

There are two f7-list in this page. The second works, the first does not (but, if you delete the `<h1>{{ selectedItems }}</h1> both work.

If you delete all `<div slot="">` from the first list, it also works.

I tried to my best check and recheck if I miss something, like a " or close all tags, and all seems right.

**Comment by nolimits4web** [comment]
This is how Vue rendering works, it may not know that first checkbox must be not rerendered. To get the right behavior, use `checked` attributed bound to data https://jsfiddle.net/12wv0tbx/
