### ISSUE TITLE
[v1] Pull to refresh is triggering on scrollup when the list is inside tabs

### ISSUE THREAD

**Issue by Gabplay** [framework7io/framework7#2769]
This happens when I use a page with multiple tabs and lists inside each tab.

The ptr was expected to refresh only on the top of the list, but `container[0].scrollTop` is = 0, because the container is the .page not the .tab

https://github.com/framework7io/framework7/blob/v1/dist/js/framework7.js#L9294

This works for my case, it migth be helpful to include in the code:

`if($$(container[0]).hasClass('tabs-and-searchbar')){
    scrollTop = $$(container[0]).find('.tab.active').scrollTop();
} else{
    scrollTop = container[0].scrollTop;  
}`

**Comment by nolimits4web** [comment]
Sorry, v1 is not maintained anymore
