### ISSUE TITLE
React Subnavbar Navigation Glitch

### ISSUE THREAD

**Issue by aiba** [framework7io/framework7#2770]
* Framework7 version: 3.4.0
* React.js version: 16.3.2
* Platform and Target: any
* Live Link or JSFiddle: https://jsfiddle.net/aaroniba/u0ke7op3/1/

### Describe the bug

If the presence of a subnavbar is dependent on state, then navigation gets screwed up when you click a backLink.

### To Reproduce

See https://jsfiddle.net/aaroniba/u0ke7op3/1/

1. Click on "Go to page B"
2. Click "Increment" until N is an even number (and the subnavbar is visible).
3. Click "< Back"

### Expected behavior

You should see the home page.

### Actual Behavior

Page B's navbar is rendered over the home page.

### Screenshots

https://imgur.com/a/MLJtCRd

**Comment by nolimits4web** [comment]
Yep, happens because React unset page classes set by F7's router, when it adds `page-with-subnavbar` class. As a temporary solution we need to set/unset this class manually https://jsfiddle.net/s4p3ryz5/

I will work on correct fix for this
