### ISSUE TITLE
momentum scroll events not work by touch gesture.

### ISSUE THREAD

**Issue by sherlockat** [framework7io/framework7#2775]
I made code that outputs a log by assigning a scroll event to the div.page-content element

<div class="page-content" id="scrollDiv"></div>

$("#scrollDiv").on("scroll", ()=>{ console.log('scroll'); })

This works well with the following actions:
1. control scrollbar or wheel button on PC's web browser
2. If you touch move the finger with touching the screen

but momentum scroll does not work.
1. Events not work while momentum scroll is running.
2. At the end of the momentum scroll, scroll event work only one.

Please, check this issue

**Comment by nolimits4web** [comment]
Not related to Framework7. If you use iOS cordova app, make sure you use WKWebView
