### ISSUE TITLE
Scroll to hide and show fab

### ISSUE THREAD

**Issue by malikdoksoz** [framework7io/framework7#2776]
How to hide FAB element on scroll to down and scroll to top i wanna show it. 
I can't get scroll position.
I've tried, but its not working

```
var pxScrolled = 180;
  $(window).scroll(function() {
   if ($(this).scrollTop() > pxScrolled) {
   $('.fab').css({'display': 'none'});
   } else {
  $('.fab').css({'display': 'block'});
   }
   });
```
Sorry my bad english.

**Comment by nolimits4web** [comment]
You need to assign scroll event handler to `page-content` which is in required page:
```
$('.page-content').on('scroll', function(){
  ...
});
```
