### ISSUE TITLE
state() handling of input.jsx screws up $event.target.value

### ISSUE THREAD

**Issue by kozmanbalint** [framework7io/framework7#2777]
* Framework7 version: 3.4.2
* Vue.js version: 2.5.17
* Platform and Target: Desktop Chrome browser 69

### Describe the bug
$event.target.value is null since `this.setState({ inputFocused: true })` appeared in `onFocus()` and `onBlur()`.

### To Reproduce
As even production kitchensink is affected, the issue can be seen [here](http://framework7.io/vue/login-screen.html) e.g. on the login overlay.

### Expected behavior
Value entered to the username / password fields should be reflected in the viewmodel, and remain untouched in the corresponding textfield.

### Actual Behavior
Value entered to the username / password field disappears upon focus or blur event.

### Additional context
Removing `this.setState({ inputFocused: true })` from onFocus() and onBlur() actually works around the issue - but that's frankly not the way it should be handled.

**Comment by nolimits4web** [comment]
Not really an issue but fixed it. In such data-binding frameworks it should be correctly bound to values to avoid such issues like here https://github.com/framework7io/framework7/blob/master/kitchen-sink/vue/src/pages/login-screen.vue#L24-L31

**Comment by kozmanbalint** [comment]
Exactly, thanks for the fix though!
