### ISSUE TITLE
The last entry is crossed out by a line - virtual list example

### ISSUE THREAD

**Issue by DennisStudent** [framework7io/framework7#2779]
https://framework7.io/docs/virtual-list.html

The last entry is crossed out by a line. (Theme: iOS)

![bildschirmfoto vom 2018-10-16 09-42-34](https://user-images.githubusercontent.com/16091129/47000168-f9391e80-d127-11e8-9bcd-dd0a55c54f7c.png)

The scrollbar starts from behind the navbar.

**Comment by nolimits4web** [comment]
> The last entry is crossed out by a line

It will be fine on iOS

> The scrollbar starts from behind the navbar

It is by design
