### ISSUE TITLE
Dynamic tabbing tab higlight issue

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2780]
* Framework7 version: [e.g. 3.2.4]
* Platform and Target: [e.g. Chrome browser]
* Live Link or JSFiddle: https://jsfiddle.net/0kejcgnh/10/

### Describe the bug
When tabs is created dynamically then tab highlight is not working initally.

### Expected behavior
When tab created dynamically, we need tab highlight for first tab also.

### Actual Behavior
Currently, when tabs are created dynamically at that time first tab not highlight automatically, when we click on next tab and then click on first tab then its working.

so i think, issue is tab highlight is not working when tab is dynamically created.

Please check js fiddle demo for issue. First click on tabs then i have created dynamic tabs now click on tab other then first to start highlight bar. 

Thanks

**Comment by nolimits4web** [comment]
https://jsfiddle.net/ybgxopcs/
