### ISSUE TITLE
On dynamic data swipable and swipable scrolling is not work

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2781]
* Framework7 version: [e.g. 3.2.4]
* Platform and Target: Chrome browser
* Live Link or JSFiddle: https://jsfiddle.net/0kejcgnh/9/

### Describe the bug
Swipable initialization issue when tabs are dynamic

### Expected behavior
When tabs created from dynamic data then its should be automatically initialized

**Comment by nolimits4web** [comment]
https://jsfiddle.net/78yv1rz4/

or 

https://jsfiddle.net/7njmx9ad/
