### ISSUE TITLE
Tabbar tab:show event call multiple times when change sub tabbar

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2783]
* Framework7 version: [e.g. 3.4.2]
* Platform and Target: [e.g.  Chrome browser]
* Live Link or JSFiddle: https://jsfiddle.net/ybgxopcs/1/

### Describe the bug
When any tab inside another tab and we need to handle both parent and sub both toolbar event and we change child tab then parent tab:show event automatically called.

### Expected behavior
If we change child tab then only child tab event called not parent also.

### Actual Behavior
Here when we change child then automatically parent tab:show is occurred and we need to prevent it.

### Additional context
I have added fiddle link for more information, you can see on console if you change child then its called parent also.

**Comment by nolimits4web** [comment]
This is how DOM events work. Check `event.target` to know exact tab
