### ISSUE TITLE
Swipable tabs not scroll  when we swipe and tab is not display on top

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2784]
* Framework7 version: [e.g. 3.4.2]
* Platform and Target: Chrome browser
* Live Link or JSFiddle: https://jsfiddle.net/78yv1rz4/

### Describe the bug
When we swipe any tabs using swipe but heading of tab is not swipe when tabs is not visible. Its basic requirement when scrollable tabs we are using.

### Expected behavior
When we swipe tabs body and heading is on scrollable panel then we also need to scroll tabbar scroll.

### Actual Behavior
Currently if heading is hidden then swipe is working but tab is not scroll as per body display.

### Additional context
I have added example of issue on fiddle.

Sorry for my bad english

**Comment by nolimits4web** [comment]
Toolbar auto scrolling not supported and must be implemented on your own
