### ISSUE TITLE
Bug: <f7-messagebar> value is disappeared after blured

### ISSUE THREAD

**Issue by l2aelba** [framework7io/framework7#2786]
* Framework7 version: 3.4.2
* Vue.js version: 2.5.17
* Platform and Target: Desktop browsers
* Live Link: http://framework7.io/docs-demos/vue/messages.html?theme=md

### Describe the bug
When typing values on messagebar and loosing the focus (blur), value is disappeared.

### To Reproduce
1. Go to http://framework7.io/docs-demos/vue/messages.html?theme=md
2. Type something on message bar
3. Click another element (blur)

### Expected behavior
Should not be disappeared?

### Actual Behavior
Value will be disappeared

**Comment by l2aelba** [comment]
**Solution** is something like..

```
<f7-messagebar :value="newMessage" v-on:input="newMessage = $event.target.value"></f7-messagebar>
```

But this is bug or something?

**Comment by nolimits4web** [comment]
This is already fixed in src. But the solution you have is anyway the right way of using it

**Comment by nolimits4web** [comment]
@l2aelba yep
