### ISSUE TITLE
[v3] iphone X Safe area stop working when orientationChange 

### ISSUE THREAD

**Issue by yelban** [framework7io/framework7#2787]
* Framework7 version: [3.4.2]
* Platform and Target: [e.g. iOS 11 Cordova app]

### Describe the bug
iphone X Safe area stop working when orientationChange, it broken the wonderful F7 page

### To Reproduce
1. start app
2. it looks perfect full screen in iPhone X, XS
3. change the device orientation
4. get the out of the screen app,

### Expected behavior
correct safe area display

### Actual Behavior
out of the screen area

### Screenshots
app start in landscape / portrait, display is okay
![2018-10-19 5 03 43](https://user-images.githubusercontent.com/981381/47208714-218f7a00-d3c1-11e8-896b-9e71b727f3e8.png)

safe area is out of the box when the orientation of the device has changed
![2018-10-19 5 03 15](https://user-images.githubusercontent.com/981381/47208790-569bcc80-d3c1-11e8-88fb-068847d34ab0.png)

### Additional context
index.html viewport setting: add viewport-fit=cover
use cordova-plugin-splashscreen and add Launch storyboard images in config.xml
`<splash src="res/screen/ios/Default@2x~universal~anyany.png" />`

**Comment by nolimits4web** [comment]
That is a cordova issue, try to use WKWebView plugin
