### ISSUE TITLE
CSS classes loaded in wrong order

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2790]
* Framework7 version: 3.4.3
* Vue.js version: 2.5.17
* Platform and Target: Any

### Describe the bug
This code:
```
<f7-page class="menu-page">
```
results in this output:
![image](https://user-images.githubusercontent.com/379339/47271766-9645ee00-d552-11e8-9ced-8aa65c87c5ae.png)

As our custom class is set before F7 classes, we can't override F7 default behaviors without `!important` (which is bad).

### To Reproduce
Try to add any class on any F7 element.

### Expected behavior
The custom class be set after the F7 classes (so our CSS overrides the default F7 CSS).

### Additional context
As this could lead to breaking changes, perhaps a `after-class="menu-page"` in EVERY component (AND slots)...

**Comment by nolimits4web** [comment]
Order of CSS classes in `class` attribute has no any effect. Only order and specificity of CSS rules matters. Just use more strict rule like:

* `.page.menu-page`
* `.ios .menu-page`

etc
