### ISSUE TITLE
After sending message messagebar does not get clear.

### ISSUE THREAD

**Issue by takielias** [framework7io/framework7#2791]
After sending message messagebar does not get clear . How Can I fix it?

https://framework7.io/vue/messages.html#messages-events. In This example Messagebar does not get clear after sending text.

**Comment by nolimits4web** [comment]
You need to correctly bind messagebar value to the component state https://github.com/framework7io/framework7/blob/3d671d41c88a4cab0dc6f8729e39e601f5ce6599/kitchen-sink/vue/src/pages/messages.vue
