### ISSUE TITLE
When redirect to another page ad or toast is overlapped with screen

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2793]
* Framework 7 version: [e.g. 3.2.4]
* Platform and Target: Chrome browser

### Describe the bug
When app is initialized all is good, but when we redirect page to another then banner ad or toast is overlapped with screen,

We have checked same issue SAMTUNG, MI, MOTO and OPPO phone which have virtual button on screen and some of has not virtual button on screen.

### Expected behavior
I need to solved issue of overlap for ad/toast with screen.

### Screenshots
First screen when initialized when all is good:
http://prntscr.com/l9sjv1

On all tabs of this page all is  working great:
https://prnt.sc/l9skjv

When click on tab on third tab then i navigate page to another using **app.router.navigate("url")**, and issue is raised. On open this page f7 toast or action sheet all things will be open from overlapping as below screen shot.
https://prnt.sc/l9smo9
https://prnt.sc/l9smwg

App initialized code is as below:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui, viewport-fit=cover">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#2196f3">
    <title>Demo</title>
    <link rel="stylesheet" href="lib/framework7/css/framework7.css">
    <link rel="stylesheet" href="css/app.css">
  </head>
  <body>
    <div id="app">
      <div class="statusbar"></div>
      <div id="view-home" class="view view-main">
      </div>
    </div>
    
    <script type="text/javascript" src="cordova.js"></script>
    
    <script src="lib/framework7/js/framework7.js"></script>
    <script src="js/routes.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>
```

In app.js code:
```
var $$ = Dom7;
var app= new Framework7({
  root: '#app', 
  id: 'com.demoapps',
  name: 'demo', 
  theme: 'auto', 
  data: function() {
    return {};
  },
  view: {
    stackPages:true,
  }
  routes: routes,
});
var homeView = myApp.views.create('#view-home',{
  url:"/home/"
});
```

**Comment by raiyanihiren** [comment]
Please give me some solution where is i am wrong.

**Comment by nolimits4web** [comment]
Didn't get what happens, but looks like you have some styling issue

**Comment by raiyanihiren** [comment]
Got it, On page load we are overlap statusbar true that is issue, after removing its working perfectly.
