### ISSUE TITLE
toggle not working in framework 7  v1.7.1 

### ISSUE THREAD

**Issue by annamalai143** [framework7io/framework7#2795]
![togg](https://user-images.githubusercontent.com/38519591/47444961-915c8680-d76c-11e8-9222-1bc8bd4e6d92.png)
i am using framework 7 v1.7.1 for my project..
in my project when i try to use toggle option it comes as  checkbox instead of toggle

**Comment by nolimits4web** [comment]
Did you mean switch http://v1.framework7.io/docs/form-elements.html ?

**Comment by Kristiyandz** [comment]
I have the same issue, if this is a switch element why is under the toggle section?

**Comment by nolimits4web** [comment]
Everything is correct in docs. Pay attention to F7 version
