### ISSUE TITLE
How do you reduce number of rows in Calendar?

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2796]
I'd like to reduce the number of rows in the calendar component, the default is 6. how can i make it to just 5

**Comment by nolimits4web** [comment]
This is not supported and i can't see a reason why it can be required. If you really need this you can provide your own `renderMonth` function https://github.com/framework7io/framework7/blob/master/src/core/components/calendar/calendar-class.js#L848-L1001
