### ISSUE TITLE
virtualList.create is not working

### ISSUE THREAD

**Issue by AndriySvirin** [framework7io/framework7#2799]
On phonegap appears error: ```call to eval() blocked by CSP```

**Comment by nolimits4web** [comment]
Make sure you have correct CPS tag like
```
<meta http-equiv="Content-Security-Policy" content="default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap:">
```

**Comment by AndriySvirin** [comment]
Hi. Thanks a lot for response.
In documentation a did not find any suggestion for such issue. In interent is too luck off information about this issue.
So you can add into doc this. My first decission was to change framework.

**Comment by nolimits4web** [comment]
All official F7 templates have correct CSP meta tag set
