### ISSUE TITLE
After swipeout  when remove element using $setState its will remove two element

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2800]
* Framework7 version: [e.g. 3.5.0]
* Platform and Target: [ Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/ybgxopcs/16/)

### Describe the bug
After swipeout delete, when we refresh virtual dom then two element will deleted.

### Expected behavior
Which element is deleted using swipeout, if that is already removed from dom then not remove next second element

### Actual Behavior
We only need to remove which is swipeout

### Additional context
Please check js fiddle demo for information.

**Comment by nolimits4web** [comment]
Use `key` attribute to correctly identify item https://jsfiddle.net/kg7ms1rp/

**Comment by raiyanihiren** [comment]
Thanks
