### ISSUE TITLE
> I searched this repo and haven't seen any code or issues discussing Facebook SDKs of any kind.

### ISSUE THREAD

**Issue by cyrusonline** [framework7io/framework7#2801]
Because it doesn't related to Facebook SDKs. Just use facebook JS sdk if this is a web app or this cordova plugin for cordova app https://github.com/jeduan/cordova-plugin-facebook4

_Originally posted by @nolimits4web in https://github.com/framework7io/framework7/issues/2175#issuecomment-364743722_

**Comment by cyrusonline** [comment]
the above plugin not work for framework7, i tried it work on ionic. When add in framework7 cordova vue, 
it will prompt the following error

> BUILD FAILED in 14s
>     at ChildProcess.whenDone (E:\f7project\fblogin\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at maybeClose (internal/child_process.js:925:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> (node:33516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()

**Comment by nolimits4web** [comment]
Sorry, there is something wrong on your side. https://github.com/jeduan/cordova-plugin-facebook4 works perfectly with Framework7 and not related to Framework7 in general

**Comment by cyrusonline** [comment]
> Sorry, there is something wrong on your side. https://github.com/jeduan/cordova-plugin-facebook4 works perfectly with Framework7 and not related to Framework7 in general

Could you please give an example code, as facebook4 work well on even simple cordova. The app cannot run even just after add plugin related to facebook, did not add any code.  i tried facebook4  and firebase facebook login , but these two ways also not work.

**Comment by nolimits4web** [comment]
- download https://github.com/framework7io/framework7-template-vue-webpack repo
- run `npm install` and `npm run build`
- copy content of generated `www` folder to newly created cordova project's `www` folder
- instal that facebook plugin
- all should work
