### ISSUE TITLE
Routable Tabs IOS swipe from left to right to go back generate error

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#2803]
* Framework7 version: [e.g. 3.5.0]
* Platform and Target: Chrome browser
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/o2ejupu1/696/)

### Describe the bug
On routable tabs, on swipe back generate error "ncaught TypeError: Cannot read property 'route' of undefined". Please check screen shot for that.

Try below demo in browser IOS screen and after open detail page go back using swipe back as IOS functionality.
https://fiddle.jshell.net/o2ejupu1/6/show/

**Comment by nolimits4web** [comment]
Sorry, but native iOS browser's swipeback is not supported because we have no any control over it

**Comment by raiyanihiren** [comment]
So its work in IOS device?

**Comment by casyalex** [comment]
I found out its page in page cause this bug, but i need to use toolbar & toolbar-top inside the tabs-page. if less a page wrap the toolbar, i won't work properly. How to solve..
