### ISSUE TITLE
How to stay all processes within all pages even if going next/ going back to pages?

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2805]
Hello Vladimir, 
I want to ask if there's a setting in initialization of view/router when you are going back to pages it will stay the same (the actions you made) 

Just like when you go to other page, and when you go back to it you can still see your actions, but when you access a page the third time will lose its session

**Comment by nolimits4web** [comment]
You can enable View's `stackPages: true` parameter and it will keep previous pages in DOM

**Comment by pluckannfeel** [comment]
thank you vladimir
