### ISSUE TITLE
stackPages - Incorrect behavior?

### ISSUE THREAD

**Issue by matthewbecker1990** [framework7io/framework7#2806]
* Framework7 version: Latest
* Platform and Target: Browser

### Describe the bug
When using stackPages, new copies of pages are being loaded into DOM, even though existing copy exists.

![image](https://user-images.githubusercontent.com/6112221/47823960-c72dea80-ddbe-11e8-85a8-71d872ef7117.png)

### Expected behavior
If pageName present in route, router should check if page exists in DOM. Only if page doesn't exist in DOM should it then continue and load from URL.

![image](https://user-images.githubusercontent.com/6112221/47824027-0f4d0d00-ddbf-11e8-8a04-f13afc5dc929.png)

**Comment by nolimits4web** [comment]
What is the point of having both `pageName` and `url` in route? Use only something one, e.g. `pageName` only

**Comment by matthewbecker1990** [comment]
I think it makes sense, you get the best of both worlds. You can keep all your pages separated and tidy and load them on demand. Once loaded in DOM, then the route uses the first option in order which would be pageName.

This:
a) Keeps the DOM as clean as possible, only loading pages that are necessary. In-lining the pages loads them into DOM every time the app opens, even if that particular page is never visited.
b) Keeps the files organised. In-lining is messy.

Thoughts?

**Comment by nolimits4web** [comment]
Only kind of page loading prop can be specified. Then you can try to use async route and check inside, if page is in DOM then resolve it with pageName or `el`, otherwise resolve it with `url`

**Comment by matthewbecker1990** [comment]
I'll give async a try tomorrow, should do the trick I think. Thanks!

**Comment by matthewbecker1990** [comment]
If anyone stumbles upon this and would like similar functionality, this snippet below does the trick. Thanks for pointing me in the right direction @nolimits4web!

`{
    path: '/step-1/',
    async(routeTo, routeFrom, resolve, reject) {
      if (document.querySelector('.page[data-name="step-1"]')) {
        resolve({ pageName: 'step-1' })
      } else {
        resolve({ url: './pages/step-1.html' })
      }
    }
  }`
