### ISSUE TITLE
bug RTL css with tabs-animated-wrap

### ISSUE THREAD

**Issue by mohshraim** [framework7io/framework7#2811]
* Framework7 version: 3.4.3
* Platform and Target: ios

### Describe the bug
want to report a bug and another enhancement suggestion..
* Bug-> 
when use RTL css and create a tabs control with tabs-animated-wrap. 
the result is only first tab will be visible but 2nd 3rd ..etc will not be visible when active..
i think it's F7 will animated to wrong direction...
Note; that its working normally when use RTL css without tabs-animated-wrap.

* Suggestion ->
TRL css working fine for me as expected but.
Navigation bar will exchange the location of left menu button with right one,,->correct.
Click on menu  button (now it is on top right to open left panel)  but the left-panel will stay at left..
so i add override on RTL CSS 
```
.panel-left {
    right: 0;
    left: unset;
}
.panel-left.panel-cover {
    -webkit-transform: translate3d(100%, 0, 0);
    transform: translate3d(100%, 0, 0);
}
```
so now left panel will be handled on RTL design without need to change the app code

Thanks

**Comment by mohshraim** [comment]
I solve it by change the        
` myApp.rtl = false;`
because i change the layout and language at run time that both css is included and i disable the unwanted design..

i will keep the issue open for the suggestion if you find it useful..

Thanks

**Comment by nolimits4web** [comment]
I see everything is correct, when is loaded with RTL stylesheet, here is the video https://www.dropbox.com/s/xfjj9st2gysfqmz/rtl-tabs-video.mov?dl=0

Enabling/disabling RTL during runtime is not supported
