### ISSUE TITLE
[V3] page.route.params not updating

### ISSUE THREAD

**Issue by mossaiby** [framework7io/framework7#2813]
* Framework7 version: 3.5.1
* Platform and Target: PhoneGap

### Describe the bug
I have recently started to use stacked pages, and everything works fine. I have a route like this:
```
{
  path: '/store/:store_id/',
  pageName: 'store',
  on: {
    pageAfterIn: function (event, page) {
      console.log(page.route.params);
    }
  }
}
```
The first time I click a link related to this route, e.g. ```/store/1/```, it works fine. If I use browser's back button and click another link, ```/store/2/```, I still get the previous result. The fun fact is that ```app.view.main.router.currentRoute.params``` returns correct value in all cases.

### To Reproduce
1. Define a stacked page in the main view.
2. Click on said links.
3. See the results.

### Expected behavior
```page.route.params``` should be update each time a related link is clicked.

### Actual Behavior
```page.route.params``` returns the value with the first link clicked.

### Additional context
```app.view.main.router.currentRoute.params``` always returns the correct value.

**Comment by nolimits4web** [comment]
Page's route property with its params and query and others is not reactive. It will be set on page once it is loaded and won't be changed. It is by design. So in your case, just use router's `currentRoute.params` instead
