### ISSUE TITLE
Accordion toggle event fires twice on iOS (reopens #2397)

### ISSUE THREAD

**Issue by mlitwin** [framework7io/framework7#2814]
I am seeing https://github.com/framework7io/framework7/issues/2397 "Accordion toggle event fires twice on iOS", which is a bug closed for inactivity.

Framework7 version 3.5.1
Platform and Target: CORDOVA, IOS 12.1

As stated in https://github.com/framework7io/framework7/issues/2397, in ios cordova app, there can be double clicks from a single touch in the accordion - it's not clear exactly under what circumstances, but fast taps and slow taps seem to be the areas of issue.

My workaround is:
`.item-link.active-state {
  pointer-events: none;
}`
which works for my use case of accordion in list.

Fast clicks may implicated, as configuring touch for
`fastClicksExclude: '*'`
seems to fix the issue, although 
`fastClicks: false`
did not.

One effect of the bug is that sometimes taps open and then quickly close the accordion, sometimes fast enough that it seems like the tap didn't work.

**Comment by nolimits4web** [comment]
Ok, will investigate this

**Comment by nilamdoc** [comment]
I am also having the issue with accordion. Click it once opens and closes. I tried every solution. Did not work.
Using it in Monaca Framework7. All other functionality works perfectly!.

**Comment by VisualMafia** [comment]
Add this:
.accordion-item {
	-webkit-transform: translate3d(0,0,0);
	transform: translate3d(0, 0, 0);
}
