### ISSUE TITLE
[V3] Stepper values are displayed wrong

### ISSUE THREAD

**Issue by marchildmann** [framework7io/framework7#2824]
* Framework7 version: 3.51
* Platform and Target: Chrome Browser

### Describe the bug
If a stepper is initialized with 
`<input name="my_stepper" type="text" value="0" min="0" max="10" step="0.1" readonly>`
then it'll display values like this

0.1
0.2
0.30000001
0.4
0.5
0.6
0.70000002
... and so on

### Expected behavior
The values should be 0.1, 0.2, 0.3, 0.4 ...

### Actual Behavior
See above.

**Comment by praveenmujawdiya** [comment]
Hi,

The value displayed inside the stepper is not wrong at all. It is because the way computer performs floating point arithmetic.

Test this `console.log(0.1+0.2)` and you will get `0.30000000000000004` as the answer.

You can read more about why this happens at https://0.30000000000000004.com

**Comment by nolimits4web** [comment]
@praveenmujawdiya is right. @marchildmann just do required Math.round with stepper value
