### ISSUE TITLE
How to back 'query' to the previous page with router.back

### ISSUE THREAD

**Issue by pomelo828** [framework7io/framework7#2828]
hi ,how to back 'query' to the previous page with router.back, and trigger reinit method , thx.
i can did it with f7_v1 , but can't in f7_v3.
like this:
mainView.router.back({
                query: {
                    test: '111',
                    test2: '111'
                }
            });

**Comment by nolimits4web** [comment]
It is not possible to overwrite page's route query once it was loaded and sits in DOM, like previous page. There only thing that could work here  is:
```
mainView.router.back('/url-of-previous-page/?test=111&test2=111', { force: true })
