### ISSUE TITLE
IOS Status Bar - mobile hotspot blocking the navbar

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2830]
I have this problem where status bar is not pushing down the navbar, is there a settings in initialization or fix on css with this matter? See Image below. 

Thanks

![image](https://user-images.githubusercontent.com/14131170/48337508-0ea95600-e69e-11e8-9604-034aacb419e9.png)

**Comment by pluckannfeel** [comment]
there isnt setting here in http://framework7.io/docs/statusbar.html which is related to the issue..

**Comment by shastox** [comment]
This is a known issue. I have not found a solution.

**Comment by shastox** [comment]
Solution (Google): 
https://github.com/ionic-team/ionic/issues/7579#issuecomment-241877779

Need statusbar-plugin.

**Comment by pluckannfeel** [comment]
@nolimits4web hello vladimir, is there any solution existed with this matter? thanks for answering

**Comment by shastox** [comment]
@pluckannfeel https://github.com/ionic-team/cordova-plugin-statusbar ?

**Comment by pluckannfeel** [comment]
its the same, cordova added this plugin too

**Comment by nolimits4web** [comment]
There is nothing can be done on HTML side here. From what i see "in-call" statusbar handled correctly, and if this with hotspot is none then the issue in cordova-statusbar-plugin
