### ISSUE TITLE
Framework7 and cordova Status Bar Plugin

### ISSUE THREAD

**Issue by tharunkumar0** [framework7io/framework7#2833]
I am having an input text box at the bottom of the page which on clicked, the keyboard appears and the text box goes behind the keyboard. This doesn't happen when I remove the cordova status bar plugin. I tried many solution that involves adding the cordova keyboard plugins but didnt work.

* Framework7 version: 3.0.0
* Platform and Target: Cordova app Android

**Comment by nolimits4web** [comment]
It is a some issue in Statusbar plugin. Make sure you disable `StatusBarOverlaysWebView` for Android, same in statusbar parameters http://framework7.io/docs/statusbar.html#statusbar-app-parameters
