### ISSUE TITLE
How to find model length from server response ?

### ISSUE THREAD

**Issue by WbcMaha** [framework7io/framework7#2835]
How to find model length from server response ?

{"message":null,"didError":false,"errorMessage":null,"pageSize":10,"pageNumber":1,"model":[{"userID":155,"jobMasterID":3,"patinetName":"sathishsathish","jobDate":"2018-11-13T00:00:00","profileUrl":null,"userName":"parthibansk","price":930.0,"address":null,"jobDistance":null},{"userID":155,"jobMasterID":4,"patinetName":"parthibansk","jobDate":"2018-11-13T00:00:00","profileUrl":null,"userName":"parthibansk","price":930.0,"address":"ewrwef,Bharathithasan street,karaikudi,Tamilnadu,India,630002","jobDistance":null},{"userID":92,"jobMasterID":1,"patinetName":"sdgdfgh","jobDate":"2018-11-13T22:26:26","profileUrl":null,"userName":"sdgdfgh","price":3000.0,"address":null,"jobDistance":null}]}

this is my server response . how can i find out length of the model from this service ?

**Comment by praveenmujawdiya** [comment]
Hi,

The response you are getting from the server is in JSON format.

First assign the response to a variable, lets assume

var response = {"message":null,"didError":false,"errorMessage":null,"pageSize":10,"pageNumber":1,"model":[{"userID":155,"jobMasterID":3,"patinetName":"sathishsathish","jobDate":"2018-11-13T00:00:00","profileUrl":null,"userName":"parthibansk","price":930.0,"address":null,"jobDistance":null},{"userID":155,"jobMasterID":4,"patinetName":"parthibansk","jobDate":"2018-11-13T00:00:00","profileUrl":null,"userName":"parthibansk","price":930.0,"address":"ewrwef,Bharathithasan street,karaikudi,Tamilnadu,India,630002","jobDistance":null},{"userID":92,"jobMasterID":1,"patinetName":"sdgdfgh","jobDate":"2018-11-13T22:26:26","profileUrl":null,"userName":"sdgdfgh","price":3000.0,"address":null,"jobDistance":null}]}

Now you can get the length of 'model' key using

`console.log(response.model.length); // This will print 3 on console for the above response`

**Comment by nolimits4web** [comment]
Closing as not related to F7
