### ISSUE TITLE
Stackpages Issue: Undefined vars when loading a page which is already in router

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2836]
Im using stackpages for domcaching of my pages, but there is a problem when you have a page existing in a router, and then when you navigate  the page back, it will generate  undefined vars or the processes you set it there. Am I missing something in my view's initialization?

**Comment by nolimits4web** [comment]
Not the issue with Framework. Conversation moved here https://forum.framework7.io/t/stack-pages-how-do-you-remove-a-certain-specific-page-from-dom/5000/6
