### ISSUE TITLE
Google to pay JavaScript frameworks to implement performance-first code

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2838]
Tried to write this on the forum, but it isn't working (it gives me a 403).

The news:
https://www.zdnet.com/article/google-to-pay-javascript-frameworks-to-implement-performance-first-code/

The signup link: https://bit.ly/framework-perf

Not sure if it's usefull, but, there is it =)

**Comment by nolimits4web** [comment]
Thanks, signed up
