### ISSUE TITLE
Generate FrameWork7 Vue Custom build 

### ISSUE THREAD

**Issue by manish2535** [framework7io/framework7#2839]
* Framework7 version: [e.g. 3.0.0] 3.4.0
* Vue.js version: [e.g. 2.0.0] 2.5.17 
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser] 
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Describe the bug
Hi I am trying to change the colors being used in the library so trying to do a custom build.

I have been using the “framework7-template-vue-webpack” and it comes with the following npm run commands:

1. build-dev
2. build-prod
3. dev
4. prod
There are 3 more commands but those dont seem relevant.
I followed the instructions found here - https://framework7.io/docs/custom-build.html
In my my-config.js file I have changed the color of
md: {
themeColor: ‘#333333’, (GREY)
colors: { blue: ‘#333333’…(GREY)
}
just to test if the custom build is working or not.

I tried running
`npm run build-prod -– --config ./scripts/my-config.js --output ./www2`
=> But there is **no change in the site color** and the output folder is still www instead of www2. It seems my config is not being used at all.

Can someone tell me if this is a bug or how to do a custom build in the “framework7-template-vue-webpack”? Thanks.

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
For webpack follow the guides for ES modules and LESS:
http://framework7.io/docs/custom-build.html#es-modules
http://framework7.io/docs/custom-build.html#lessjs
