### ISSUE TITLE
Memory leak in Framework7 Vue navigation

### ISSUE THREAD

**Issue by curlycabbage** [framework7io/framework7#2848]
* Framework7 version: 3.5.2
* Vue.js version: 2.5.17
* Platform and Target: Windows 10 Chrome 70, Android 6 Chrome 70

### Describe the bug
VueComponents aren't being garbage collected after you navigate off a page.

### To Reproduce
1. Download, update, install and run the official F7 Vue Webpack sample app: https://github.com/framework7io/framework7-template-vue-webpack.
2. Visit page in Chrome. Note memory usage in DevTools | Memory. Take a heap snapshot.
3. In the sample app, click on Form, then Back.
4. In DevTools | Memory, force garbage collection then take another snapshot. Note that memory usage has increased by several MB.
5. Click Form > Back > Form > Back a few more time, force garbage collection and then take another heap snapshot. Note that memory usage has increased yet more. Note the increasing number of VueComponent instances in each snapshot. 

### Expected behavior
While navigating back and forth between two pages in an F7 Vue app, I expect memory usage to stay within constant bounds. I do not expect the upper bound to continually group.

### Actual Behavior
Memory usage grows continuously while navigating between pages in an F7 Vue app. It appears that VueComponents are not being GC'd after destroyed().

### Screenshots
![image](https://user-images.githubusercontent.com/8975454/48927182-06bd9300-eea2-11e8-86af-ec8de49668c4.png)
![image](https://user-images.githubusercontent.com/8975454/48927190-0f15ce00-eea2-11e8-921f-55131ac8125f.png)
![image](https://user-images.githubusercontent.com/8975454/48927191-15a44580-eea2-11e8-8c83-2805736989fe.png)

### Additional context
I've reproduced this using:

* F7 Vue Webpack sample (dev, build-dev, build-prod)
* F7 Vue Simple sample app: https://github.com/framework7io/framework7-template-vue-simple

It happens with both versions 3.4 (sample config) and 3.5.2 (current). It also happens with the real F7 Vue app I am working on. Navigation eats up memory and makes the UI increasingly sluggish. Eventually, the browser throws an out of memory exception.

**Comment by nolimits4web** [comment]
Can you track where does it come from? Because last time we faced it, issue was on Vue/Webpack side, all components are being destroyed correctly in F7-Vue from F7 side

**Comment by curlycabbage** [comment]
I have reproduced the memory leak in sample apps "F7 Vue Simple", F7 Vue Webpack", and "F7 React". This suggests to me that the problem is between the router and components, whether Vue or React, and that router holds a reference to component objects even after the component has been destroyed. 

Even a destroyed component cannot be garbage collected until all references to it have been removed from other reachable objects in the JS memory graph. The router is always reachable, so if it has a reference to a destroyed component, the component will never be GC'd. I'm guessing there might be an event emitter or an array somewhere in the router that still has a reference to the destroyed component object after you navigate off the page.

I don't the router code well enough to know where to look, though. Any suggestions?

**Comment by nolimits4web** [comment]
Maybe you can help? As i can't understand where it comes from, double checked all the stuff.

Phenome (Vue/React) Router is here https://github.com/framework7io/framework7/blob/master/src/phenome/utils/components-router.js. You may check page `pageComponentLoader` and `removePage` methods.

Pages itself handled in View component https://github.com/framework7io/framework7/blob/master/src/phenome/components/view.jsx

Router and View communicate with each other with events emitter https://github.com/framework7io/framework7/blob/master/src/phenome/utils/events.js

These are all files that can contain reference to components

**Comment by curlycabbage** [comment]
I have made very limited progress so far, despite substantial effort. 

I can consistently fix the sample app About page component memory leak by not rendering the on.click handler of the f7-link component. Why this handler keeps the components from getting garbage collected I don't know. Other components on the About page also render click handlers (like navleft), but for whatever reason these--on their own--don't cause the page and sub-components to stay in memory.

In the heap dump I see a lot of native_binds and feedback_cells in the retainers. This and the fact that the memory leaks appear to be all or nothing suggest to me that it might be one of the more exotic closure scope leaks, as described here: 

https://blog.swmansion.com/hunting-js-memory-leaks-in-react-native-apps-bd73807d0fde. 
https://blog.meteor.com/an-interesting-kind-of-javascript-memory-leak-8b47d2e7f156

But if that is the case, I haven't figured out how to identify the source from the heap dump or from trial & error.

Next I will try to reproduce the bug in plain VueJs, and use the results of that to further bisect the problem. This is not my wheelhouse, so it's be quite a learning curve to even get this far.

Unfortunately, if we can't solve this problem, we'll have to find something other than F7 for our app. We've already replaced most of our nested components with plain F7 markup. This has reduced the magnitude of the memory leak, and also improved overall performance, so its turned out to be a good thing. But still there's a steady leak, and we need our app to be stable during continuous heavy use, so any level of memory leak is going to be a serious problem for us. Alas!

**Comment by nolimits4web** [comment]
And weird thing is that similar events added in router pages are removed correctly. So problem is not in router

**Comment by mmis1000** [comment]
Will fixed slot ...etc break vue's assumption?  
The element is no longer existed at what vue expected it to be, because it is moved away.

**Comment by nolimits4web** [comment]
I keep researching. But issues on that pages is because we still have same Vue’s native input events (onChange/Focus/Blur, etc.) I tried to remove and situation becomes better, but I don’t feel it is right move. If we move all listeners to custom addEventListener then it will break React, because it requires those events to be specified. Need to find the origin of the issue

@mmis1000 will check the slots thing

**Comment by curlycabbage** [comment]
Vladimir, just to clarify where things stand now:

a) you are confident that you will fix the memory leak, you just need to find the best approach.

-- or -- 

b) you may or may not be able to fix the memory leak, depending on whether you find the origin of the issue.

I spent a few days trying to find the origin of the issue, but with no luck. Since then I have put the issue aside, hoping that you might be able to solve it. Now we have some decisions to make regarding our own software. We can't release it with a memory leak, so this issue here will become a blocker sooner or later.  Maybe we could crowd-source the answer? I have spare karma on SO to place a bounty, if there's a suitable question.

Cheers!

**Comment by nolimits4web** [comment]
I would say (b) - i keep looking but can't 100% guarantee  that will be able to find its origin

**Comment by ringsatu** [comment]
Hi @nolimits4web any update for this issue? I have similar issue now, here is the repro:
- Open panel right
- on panel closed get data from API using Axios
-  render data using f7-link
- click the link and you'll see the memory usage increasing and unresponsive script alert

OS: Windows 10 (64)
Browser: Version 75.0.3770.142 (Official Build) (64-bit)
F7: Latest

**Comment by ringsatu** [comment]
I managed to solve my issue, in my case it has nothing to do with F7, the issue related to  Vuex
