### ISSUE TITLE
Giving up on Framework 7 - Please, fix the router

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2850]
After working two months in a PWA app with F7, the router just stopped on production. It work fine on development, but in production it executes Vue created and mounted, but never renders the page. No errors, no sign of anything that could indicate the problem.

All my problems with F7 were about the router... So I gave Ionic a chance and, guess what... Bug on Ionic router as well (navigating from a tabbar page to another page have different behaviors when clicking the Ionic back button or the browser/android back-button)

So, now I'm trying OnsenUI with Vue. In terms of UI quality and components, it cannot be compared with F7. Sometimes I'm learning Onsen and can't help but think "oh, this is so easy in F7", but router and nav-bar is done right.

That's my app.vue (the main view):
```
<template id="app">
    <v-ons-navigator swipeable :page-stack="pageStack" @push-page="pageStack.push($event)">
    </v-ons-navigator>
</template>
```

The "code-behind", is magical:
```
@Component
export default class App extends Vue
{
    public pageStack: Array<any>;

    constructor()
    {
        super();

        this.pageStack = [Home, Keyboard];

        if(!("cordova" in window))
        {
            for(var ct = 1; ct < this.pageStack.length; ct++)
            {
                history.pushState(this.pageStack[ct].name, document.title);
            }
        }
    }
}
```

That's it: to navigate, all I need to do is to manipulate that array. All animations (and android's hardware back button) is automatically done by Onsen. You can even use vue-router, if you want (no, thank you, I'm traumatized with those routers >.<)

As my app is a hybrid Cordova/PWA, I'm manipulating the browser navigation stack with ```history.pushState``` (in the constructor, I push two pages to ```history.pushState`` so the browser gives me two history items - and the back works (even if you reload the browser)).

To make the navigation work with browser history object, is simple as:

```
if(!("cordova" in window))
{
    window.onpopstate = (e) =>
    {
        this.pageStack.pop();
    };
}
```

Again, checking for cordova because is a hybrid (if it were only cordova, nothing is needed).

All animations just work (because Onsen puts the navigation bar inside my component, so I can control the color, for instance, something that is impossible to do with F7 (it takes the navbar away from our component and move it to outside the page in iOS theme, so css won't work =\).

Anyway, I love F7, I really do. It's the most amazing framework, comparing Ionic, Vuetify, Quasar and Onsen UI, but I can't stand the routing problems and the iOS navbar =( 

Hoping F7 V4 fixes that (and that's what this issue is about).

**Comment by SimplyLab** [comment]
Your post is really weird. 

In particular, this sentence

"It work fine on development, but in production it executes Vue created and mounted, but never renders the page. No errors, no sign of anything that could indicate the problem."

Production ? Development ? WTF
