### ISSUE TITLE
iOS iframe input focusing bug

### ISSUE THREAD

**Issue by FishSaidNo** [framework7io/framework7#2851]
* Framework7 version: **3.5.2**
* Platform and Target: **iOS 12 (Safari/Chrome/Cordova)**

### Describe the bug
When trying to click between form inputs inside an iframe it can occur that the click to focus an input doesn't register. It seems that manually closing the keyboard is required to select a different input.

This issue doesn't occur 100% of the time, but very frequently. 
If it seems that inputs are working correctly, interacting with an element outside the iframe, then re-entering the iframe and trying again, will cause the issue to surface.

This issue occurs only when Framework7 is initialised. Occurs only on iOS devices. Interestingly in an old Framework7 v1 project, this issue does not occur.

### Videos of actual vs expected behaviour

In these videos, all the form elements are within the iframe, the `Buy Now` button is outside of the iframe.

[Issue (Framework7 initialised)](https://drive.google.com/file/d/1QfmA6t__5bNjGFff1ENE5D53Y1WqtBaD/view?usp=sharing)

[No issue (Framework7 disabled)](https://drive.google.com/file/d/10VELJPfVZk9OGjpUIi-6lWHU2bIgC4VT/view?usp=sharing)

**Comment by nolimits4web** [comment]
Try to add `no-fastclick` class to `iframe`
