### ISSUE TITLE
this.$f7.views is empty

### ISSUE THREAD

**Issue by reksc** [framework7io/framework7#2852]
Hi, I'm using v.3.5.2 with a cordova-webpack project template.

I used to distinguish between login screen and home screen inside the ``mounted`` hook of Vue. This worked on v2. After upgrading to the latest F7 I see that ``this.$f7ready()`` is called within mounted hook, but ``this.$f7.views`` is __empty__, thus I can't navigate from code using ``this.$f7.views.main.router`` (main is undefined).

What's most absurd is that it occurs only when I disable live-reload - so basically each time I prepare to test on a real device. Don't see any significant difference in webpack's config that would break things.

Maybe someone knowing the internals of F7 better will have an idea on what might be the cause or where to look around?

I think it must be something with the router config.

Many thanks to the author and contributors!

**Comment by nolimits4web** [comment]
Correct usage of this should be:
```
mounted() {
  this.$f7ready(() => {
    this.$f7.views // reference it here
  })
},
```
If it is empty it can mean that there are no initialized views available. If you sure they are, then would be good to see live example or JSFiddle with the issue

**Comment by reksc** [comment]
Hi Vladimir, thanks for your reply.

I found your fiddle for v2, showing how to postpone main view initialization and create it dynamically with some logic inside $f7ready hook (``f7.views.create('.view-main', { url: '/login/' })``). As it works well, I think I will discard the problematic router approach.

Here is the fiddle for future reference: https://jsfiddle.net/1wgtov4z/.
(_onF7Ready was redesigned in v3_)
