### ISSUE TITLE
路由之后的页面无法运行JS

### ISSUE THREAD

**Issue by dousee163** [framework7io/framework7#2855]
我在使用F7的最新版本 V3.5.2

现在有三个页面 a.jsp, b.jsp, c.jsp，而每个页面又有各自的js文件a.js, b.js, c.js
每个页面的路由信息都写在各自的js文件中。

a.jsp可以顺滑的平移到b.jsp，但此时b.js无法运行，导致b.js中的路由信息没法注册进去。
结果是b.jsp中的所有的迁移都不好用。

难道所有的路由信息必须都定义在a.js中吗？
有什么办法执行b.js

**Comment by nolimits4web** [comment]
In English?

**Comment by dousee163** [comment]
我通过pageInit方法+seajs解决了该问题，所以关闭。

**Comment by dousee163** [comment]
Close
