### ISSUE TITLE
KS: Use array index as key will break all operation that affect item order in vue and react

### ISSUE THREAD

**Issue by mmis1000** [framework7io/framework7#2856]
* Framework7 version: any
* Platform and Target: any
* Vue and React: any
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Describe the bug
The kitchen sink demo use index as key to prevent vue and react from blaming.
But such usage will cause swipeout to break in virtual list.

### To Reproduce
1. Setup virtual list with `v-for` or react list like the KS demo
2. Add swipeout on it
3. swipe out the item in the middle

### Expected behavior
It swipeout correctly

### Actual Behavior
It malfunction

### Additional context
React and vue both use key property of item in list to track whether a item is moved or not.
But use array index as key will compromise this functionability, because the key will now always be the same for the item at the same place

Normal list is not affected as the item management there does not rely on react/vue list, but the one in virtual list will be affected

**Comment by nolimits4web** [comment]
KS doesn't use keys in such indexes. Indexes used there are for demo purpose only. And of course if your data is going to be changed, then it is up to developer to use correct keys, and i suggest you aware of it
