### ISSUE TITLE
Framework7 Core: Router.allowPageChange did not set back to true after navigate between routable tabs when on async pages

### ISSUE THREAD

**Issue by mmis1000** [framework7io/framework7#2861]
* Framework7 version: 3.5.2
* Platform and Target: vue (but the bug is in `core`, so other platform may be affected as well)
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
`Router.allowPageChange` did not set to `true` after navigate between routable tabs that on async pages.
It cause all links that are not navigate between tabs to be disabled
My route setup that cause issue: https://gist.github.com/mmis1000/cbc67269e77cc887b4eca50f1f6bd723
This bug may be the cause of #2573 

### To Reproduce
1. Add a page
2. Add a nested page with routable tabs, async componenet and a back button on the navbar
3. Enter from the master page to the page that has routable tabs
4. Navigate between tabs using tabbar of tabs
5. Click the back on navbar

### Expected behavior
`Router.allowPageChange` is `true` and allow navigation to be happened
The page goes to master page

### Actual Behavior
`Router.allowPageChange` is `false` and all navigation breaks.
The page keeps the same

### Additional context
Trying to set `Router.allowPageChange` to true from dev console make the route works again in my test.
But I don't know where is the proper position to set the `Router.allowPageChange` back to true in this case.

**Comment by nolimits4web** [comment]
Can you please setup a JSFiddle to illustrate the issue?

**Comment by mmis1000** [comment]
@nolimits4web 
https://jsfiddle.net/aqdgw1se/1/
here you are
go about
go tab2
click back

And it should break
