### ISSUE TITLE
Navbar[hidden] is not working

### ISSUE THREAD

**Issue by darkkishao** [framework7io/framework7#2865]
- [<f7-page>
     <f7-navbar         :hidden="true”>
       ...
    </f7-navbar>
</f7-page> ]

**Comment by mmis1000** [comment]
maybe related https://github.com/framework7io/framework7/issues/2869

**Comment by holtwick** [comment]
Related #2229 

Demo: https://jsfiddle.net/perenzo/1emfya6x/
