### ISSUE TITLE
Video Intelligence (vi) Error

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/framework7#2867]
I have follow the instructions on how to put a video advertising here (http://vi.framework7.io/)

1. I have successfully register
2. I have already the "placement"

My issue is when I try the code in the demo it is error

```
https://appserver.vidint.net/api/v1/ads/sdk/interstitial net::ERR_CERT_DATE_INVALID
VM1385 vi.min.js:2 [vi] Event: AdError / Server response status: undefined
```

How can I resolve this?

**Comment by mmis1000** [comment]
Contact the video site owner, the https cert of that site is outdated before 21 days.
There is nothing framework7 can do here

**Comment by johndavemanuel** [comment]
Hi,

I try to contact them on my dashboard on VI and they what said

`The people from Framework7 work for us, but they are more specialized, and can give you better insights.`

**Comment by nolimits4web** [comment]
Sorry, not an Framework7 issue, issue with certificate on their side
