### ISSUE TITLE
route back donot work

### ISSUE THREAD

**Issue by chenxu-javascript** [framework7io/framework7#2868]
![image](https://user-images.githubusercontent.com/16332458/49493892-c0503700-f898-11e8-9808-7c76344d838d.png)

**Comment by chenxu-javascript** [comment]
Use the browser to return， and then cannot read property 'route'

**Comment by krolow** [comment]
@chenxu-javascript did u figure out how to solve this?

**Comment by chenxu-javascript** [comment]
> @chenxu-javascript did u figure out how to solve this?

I suspect that my project is a webpack hot update that causes this problem to occur, modifying the code, webpack hot variations instead of manually refreshing the page. Causes the route to be lost. The project package did not have this problem, so the issue was closed.
