### ISSUE TITLE
Framework7-vue: dynamicNavbar does not respect scoped style and all other attributes defined in page

### ISSUE THREAD

**Issue by mmis1000** [framework7io/framework7#2869]
* Framework7 version: 3.5.2
* Vue.js version: All
* Platform and Target: ios (or android with dynamic navbar enabled)
* Live Link or JSFiddle: https://jsfiddle.net/mmis1000/a1mckpyd/1/ (the navbar text color is not applied, toggle theme to android to see the different)

### Describe the bug
The dynamic navbar move only inner content of navbar to the top location, but it forgot that the navbar itself can be a target for coloring and apply other attributes.

### To Reproduce
1. enable dynamic navnbr in param
2. make a navbar in page
3. apply any attribute you like on it

### Expected behavior
The attribte applied correctly/ color...etc is displayed as expect

### Actual Behavior
It does not work

### Additional context
This bug also breaks scoped style of vue, because the scope id attribute is gone due to this situation.

**Comment by nolimits4web** [comment]
But as you noticed it is detached from component so it will never work will scoped styles, it is just impossible. I would recommend to use `inner-class` attribute where you can set class on its inner element and style it like here https://jsfiddle.net/aho7cqkg/

**Comment by mmis1000** [comment]
And I guess It may work with scoped style if we copy all attribute from original one to the outer wrapper (or even replace the wrapper all together

**Comment by nolimits4web** [comment]
> The bottom border is on the navbar wrapper instead of navbar inner, use scope css to only change theme in certain page is simply impossible.
I can just update them in page:* hooks with DOM7, but I think it isn't really eligible to do so

Yes, can be done with DOM (check About page) https://jsfiddle.net/4ysxoter/

> And I guess It may work with scoped style if we copy all attribute from original one to the outer wrapper 

This what could probably be done in v4, some classes could be copied

> even replace the wrapper all together

this is impossible as it will break dynamic navbar

**Comment by mmis1000** [comment]
I believe this is important
