### ISSUE TITLE
wrong icon

### ISSUE THREAD

**Issue by vjg1** [framework7io/framework7#2872]
"waterdrop" icon incorrectly displays as "at" icon on safari, chrome and xcode sim when used with tabbar labels.

**Comment by nolimits4web** [comment]
Where? I see everything is correct

<img width="362" alt="ios" src="https://user-images.githubusercontent.com/999588/49640145-d3d8da80-fa1d-11e8-896b-c98ca304772e.png">

**Comment by vjg1** [comment]
<img width="960" alt="screen shot 2018-12-07 at 8 53 06 pm" src="https://user-images.githubusercontent.com/41230569/49640633-30f67f80-fa62-11e8-8ae6-fabae71ee655.png">

**Comment by nolimits4web** [comment]
Make sure you use 2.x version of F7-icons

**Comment by vjg1** [comment]
so i cant use v4?
