### ISSUE TITLE
Vertical range slider

### ISSUE THREAD

**Issue by StefansArya** [framework7io/framework7#2873]
Hi!
I just tried the [current range slider](http://framework7.io/docs/range-slider.html#examples) and it's only support with the horizontal position. I have tried to rotate it with transform.. But when I want to move the slider, I still need to slide it horizontally. I think it's because the framework only calculate the horizontal movement.

Is there any way to make the range slider behavior like [this example](https://simeydotme.github.io/jQuery-ui-Slider-Pips/#example-vertical)?

**Edit:**
I think we can modify the mouse position calculation on `handleTouchStart` and `handleTouchMove`:
https://github.com/framework7io/framework7/blob/5df4fe619253e834201310cc6668e9d41901250a/src/core/components/range/range-class.js#L169-L174

And also the CSS calculation on:

https://github.com/framework7io/framework7/blob/5df4fe619253e834201310cc6668e9d41901250a/src/core/components/range/range-class.js#L345-L370

**Comment by nolimits4web** [comment]
It is not supported. Added to roadmap to implement it

**Comment by StefansArya** [comment]
Thanks for adding this feature on version 4 :+1:
I will close this issue
