### ISSUE TITLE
Example code for framework7-vue swipeable tabs from official demo is not working (v3.6.0)

### ISSUE THREAD

**Issue by 1isten** [framework7io/framework7#2875]
* Framework7 version: [3.6.0]
* Vue.js version: [2.5.17]
* Platform and Target: [Android 8 Chrome browser]
* Live Link: https://framework7.io/vue/tabs.html#swipeable-tabs

### Describe the bug
The official demo of Swipeable Tabs for framework7-vue is not working. I copied exactly the same code from the example code and tested in my project, the swipe feature is really not working, neither on Android browser nor Google Chrome on my Mac. Please help to check the issue!

### To Reproduce
1. Go to 'https://framework7.io/vue/tabs.html'
2. Scroll down to 'Swipeable Tabs' demo
3. Try to drag the screen of mobile simulator to the right or left, nothing happens.

### Expected behavior
The content should be switched upon swiping.

### Actual Behavior
Nothing happens.

### Additional context
The demo from https://framework7.io/docs/tabs.html#swipeable-tabs works as expected.

**Comment by mmis1000** [comment]
After investigation, It seems swiper.$wrapperEl is now an empty list after bump from 3.5.2 to 3.6.
Which cause the window.getComputedStyle to crash.

**Comment by 1isten** [comment]
@mmis1000 What can I do to fix the incorrect DOM generation? Or if I have to wait until next release?

**Comment by mmis1000** [comment]
You need to either wait for next release or use framework7-core directly(Which is error prone), i guess

**Comment by 1isten** [comment]
@mmis1000 Thanks for your investigation, I just updated the title.

**Comment by mmis1000** [comment]
The required fix for this would be 
Change [this](https://github.com/framework7io/framework7/blob/master/packages/vue/components/tabs.js#L25-L31) To
```
    const classes = Utils.classNames(className, Mixins.colorClasses(props), {
      'tabs-animated-wrap': animated,
      'tabs-swipeable-wrap': swipeable
    });

    const tabsClasses = Utils.classNames({
      'tabs': true,
      'tabs-routable': routable
    });
```

And it should give us the correct html structure

**Comment by 1isten** [comment]
@mmis

**Comment by 1isten** [comment]
@mmis1000 Tried just now, it works!
