### ISSUE TITLE
view "name" parameter type is wrong

### ISSUE THREAD

**Issue by dorad007** [framework7io/framework7#2876]
In the file "src/core/components/view/view.d.ts"
In interface "Parameters"
The parameter "name" should be a string and not a boolean.

**Comment by nolimits4web** [comment]
It is `string` https://github.com/framework7io/framework7/blob/master/src/core/components/view/view.d.ts#L14

**Comment by DAnn2012** [comment]
For @nolimits4web 

@dorad007  refers to this:
[https://github.com/framework7io/framework7/blob/master/src/core/components/view/view.d.ts#L31](https://github.com/framework7io/framework7/blob/master/src/core/components/view/view.d.ts#L31)
