### ISSUE TITLE
Calendar disable all especific days

### ISSUE THREAD

**Issue by noveweb** [framework7io/framework7#2877]
Possibility of disable especific days of the week, for example, disable ALL SATURDAYS and ALL SUNDAYS like it:

disabledDays: [0,6],

This way the user will be unable to select saturdays and sundays days.

Thanks!!!

**Comment by nolimits4web** [comment]
Documentation clearly shows how to achieve it by passing function to `disabled` and checking what you need there http://framework7.io/docs/calendar.html#date-range
