### ISSUE TITLE
Framework7-core: tab:hide and tab:show is forgotten in swappable/animated tabs

### ISSUE THREAD

**Issue by mmis1000** [framework7io/framework7#2878]
* Framework7 version: 3.6.0
* Platform and Target: All
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
tab show/hide event is not fired for animated tabs

### To Reproduce
1. Make a swippable tab
2. add tab:show and tab:hide on it
3. swipe it now

### Expected behavior
It fires

### Actual Behavior
nothing happened

### Additional context
Code here does not fired for tab show/hide events when it is an animated tab at all

https://github.com/framework7io/framework7/blob/master/src/core/components/tabs/tabs.js#L101-L114

Maybe it should be

```js
    // Remove active class from old tabs
    const $oldTabEl = $tabsEl.children('.tab-active');
    $oldTabEl.removeClass('tab-active');
    if (!swiper || (swiper && !swiper.animating)) {
      $oldTabEl.trigger('tab:hide');
      app.emit('tabHide', $oldTabEl[0]);
    } else {
      onTabsChanged(function() {
        $oldTabEl.trigger('tab:hide');
        app.emit('tabHide', $oldTabEl[0]);
      })
    }

    // Trigger 'show' event on new tab
    $newTabEl.addClass('tab-active');
    if (!swiper || (swiper && !swiper.animating)) {
      $newTabEl.trigger('tab:show');
      app.emit('tabShow', $newTabEl[0]);
    } else {
      onTabsChanged(function() {
        $newTabEl.trigger('tab:show');
        app.emit('tabShow', $newTabEl[0]);
      })
    }
```

**Comment by nolimits4web** [comment]
Can't see such issue. Would be good to see live example or JSFiddle

**Comment by mmis1000** [comment]
@nolimits4web I found this problem only exist when using animated tab and routable tag together.
