### ISSUE TITLE
Input can't suppout all of emoji

### ISSUE THREAD

**Issue by boboxiaodd** [framework7io/framework7#2879]
* Framework7 version: 3.4.2
* Platform and Target:  Chrome browser (Mac)
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
input and area tag can't suppout all of emoji 
but other website can show 

### To Reproduce
1. fouce searchbar or MessageInputbar
2. Control + Command + SPACE , and choose 🥶🥳🥰....etc.
3. it can't show

**Comment by nolimits4web** [comment]
Can't see any issues with it, and it is not related to Framework7.

Otherwise provide correct JSFiddle where issue can be replicated.


<img width="555" alt="screen" src="https://user-images.githubusercontent.com/999588/49725388-9cb43480-fc7c-11e8-8cfa-e67bf516cb18.png">

**Comment by boboxiaodd** [comment]
@nolimits4web  
i am use f7 in desktop app

![image](https://user-images.githubusercontent.com/4714247/49728253-3398e500-fcad-11e8-9ac4-f4784ed4f704.png)
