### ISSUE TITLE
Loop thought jSON results

### ISSUE THREAD

**Issue by noveweb** [framework7io/framework7#2882]
Hi, how can i do it using DOM7? Is it possible? I want remove the jQuery library from my app, using only DOM7.

$.each([ 52, 97 ], function( index, value ) {
  alert( index + ": " + value );
});

Thanks in advance!!!

**Comment by nolimits4web** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
