### ISSUE TITLE
Misaligned center title

### ISSUE THREAD

**Issue by vg0x01** [framework7io/framework7#2883]
* Framework7 version: 4
* Platform and Target: iOS 12, Safari 12. (Works fine on Chrome)

### Describe the bug
Title is not centre aligned when using person_round icon in class "right" in navbar.

### To Reproduce
Use person_round icon in navbar

### Expected behavior
Normally aligned title. No dynamic elements added. Although will try app.navbar.size(navbarEl) to recalculate the navbar and report back.

### Actual Behavior
Title shifts to the right occasionally. Sometimes works as expected.
Issue also occurs in safari but becomes fixed when resizing window. 

### Screenshots
<img width="284" alt="screen shot 2018-12-12 at 10 39 12 pm" src="https://user-images.githubusercontent.com/45692184/49867792-a053e100-fe5f-11e8-9c8c-c626ba97c85c.png">

**Comment by vg0x01** [comment]
Issue was caused by an empty left div in the navbar. Used html comments to remove or hide the "left" div and title aligns correctly in the center.

**Comment by vg0x01** [comment]
issue persists, see image below. 

```
<div class="navbar">
                  <div class="navbar-inner sliding">
                     <div class="left">
                        <a class="link">
                           <i class="icon f7-icons">add</i>
                        </a>
                     </div>
                     <div class="title sliding">Overview</div>
                     <div class="right">
                        <a class="link">
                           <i class="icon f7-icons">person_round</i>
                        </a>
                     </div>
                     <!--<div class="title-large">
                        <div class="title-large-text">Home</div>
                     </div>-->
                  </div>
               </div>
```

<img width="292" alt="screen shot 2018-12-12 at 11 00 23 pm" src="https://user-images.githubusercontent.com/45692184/49868545-e1e58b80-fe61-11e8-8340-7148d2c34706.png">

**Comment by nolimits4web** [comment]
It is because icon font loaded after js was executed. Just specify icon width directly

**Comment by nolimits4web** [comment]
No, by default it is not specified. So just set `style="width: 28px"` on that icon and it will work correctly

**Comment by vg0x01** [comment]
my apologies. i meant font-size:28px was specified. i have used inline css as noted and now works. thanks again.
