### ISSUE TITLE
Toolbar navigation, page:beforein and page:beforeout fire instantly for the destination page

### ISSUE THREAD

**Issue by reksc** [framework7io/framework7#2887]
Well, this isn't common in the examples, but I wanted to have both - side panel navigation and a toolbar at the bottom, to navigate between pages.

My home page listens to both page:beforein and page:beforeout to manipulate DOM and change some styling (different statusbar color etc.)

This worked OK with the side panel which resides outside f7-view, but started to fail when using the Toolbar.

Below my toolbar definition, it is present on every page:

```js
<f7-toolbar labels>
        <f7-link href="/home">
            <font-awesome-icon icon="cubes"></font-awesome-icon>
            <span class="tabbar-label">Home</span>
        </f7-link>
        <f7-link href="/documents">
            <font-awesome-icon icon="file-invoice"></font-awesome-icon>
            <span class="tabbar-label">Other page</span>
        </f7-link>
        //...
</f7-toolbar>
```

When I go from Home to the Other Page and from that I again click on "Home", then I get ``page:beforein`` and ``page:beforeout`` for the Home page **fired right after each other** which ruins my styling :(.

Any ideas why it behaves that way, or suggestions how to get the result I'm after? This is a really handy navigation style I would like to keep.

**Comment by nolimits4web** [comment]
There is something wrong. Would be good to see JSFiddle or live example with the issue
