### ISSUE TITLE
White screen on cordova app for android

### ISSUE THREAD

**Issue by AldeirJampier** [framework7io/framework7#2889]
Hello, I'm facing some problems on some versions of android. As you can see in the gif, it always happens, that the page is facing or rolled. This does not happen in Google Chrome for PC. But already in lower versions like, 4. + and 5- occur. If anyone has the solution, thank you.

<img src='https://im2.ezgif.com/tmp/ezgif-2-ced1f7d1ada1.gif'>

**Comment by nolimits4web** [comment]
I would suggest:
- if you have enabled pushState then it is configured wrong
- Framework7 doesn't compatible with Android < 5
