### ISSUE TITLE
Accessible swipe

### ISSUE THREAD

**Issue by codearachnid** [framework7io/framework7#289]
I am working through several accessibility items in a new app I am buildind with the framework. For the most part it is somewhat accessible. The photo browser has a few pieces that could be improved on when voiceover is active on an app. First is that swipe gestures completely stop when voiceover is active. I know when using other 3rd party gesture libs (hammerjs & quo) that the gesture is still recognized and actionable when using the accessible gesture (3 finger swipe). Is there any plan for supporting swipe in accessibility mode?

**Comment by codearachnid** [comment]
Sorry for the late reply - didn't see your follow up.

So in short the idea would be to add caption property to the image object and then assign that the image element when the template is generated.

You can see how I implemented in an app with an override on the hook `onSlideChangeEnd` in lines 801-808 of https://github.com/codearachnid/com.chestercomix.reader/blob/master/www/js/app.js

```
if( activeSlide.find('.align-claw-to-this').attr('alt') == '' ){
    var caption = response.comix[0].panels[ slider.activeSlideIndex ].caption;
    activeSlide.find('.align-claw-to-this').attr('alt',  caption );
}
```

**Comment by valnub** [comment]
Does F7 support accessibility at all from the ground up? If not, I'm not sure that this fix does make sense.
