### ISSUE TITLE
Gauge Component bug

### ISSUE THREAD

**Issue by VenkiGovind** [framework7io/framework7#2894]
Currently using the following framework versions:
* Framework7 version: [e.g. 3.0.0]
* React.js version: [e.g. 16.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]

Description:
- Gauge (React) component throws a console error in the browser when rendering a SemiCircle gauge.

I used the same code provided in the documentation:
[https://framework7.io/react/gauge.html](url)

HTML Code:
`<Row>
	<Col>
		<Gauge
			type="semicircle"
			value={0.5}
			valueText="50%"
			valueTextColor="#ffeb3b"
			valueFontSize={41}
			valueFontWeight={700}
			borderWidth={10}
			borderColor="#ffeb3b"
			borderBgColor="transparent"
		/>
	</Col>
</Row>`

When I run the app, I see the following error in the browser console, but the semicircle gauge is rendered correctly.

![image](https://user-images.githubusercontent.com/26425600/50165081-246bf580-02b2-11e9-8095-ec610bae55e0.png)

Changing **semicircle** to **circle** in the above code works without any issue.

**Comment by nolimits4web** [comment]
What exactly versions of F7 and F7-React?
