### ISSUE TITLE
External link is not working

### ISSUE THREAD

**Issue by Er-rchydy** [framework7io/framework7#2895]
External links don't work.
This is my code
```
<div class="page-content">
      <div class="block">
                <p>HomePage content goes here</p>
                <p><a href="/web/" >Get the page</a></p>
      </div>
</div>
```
this is my routes:
```
routes: [
                {
                    name: 'Web',
                    path: '/web/',
                    url: 'http://website.com'
                },
]
```
When i click on the link, the request for `http://website.com` is successfully made, but  the content of it is not inserted in the `DOM`.  
What i want is to click that link and load that page inside the application like it's a normal local page of the application. i don't know if that's how it work or i didn't fully understand it.

**Comment by shastox** [comment]
https://framework7.io/docs/link.html#bypass-links-handler

**Comment by nolimits4web** [comment]
It is not designed to be used in this way, and it is impossible to load whole webpage inside of the page. Or use iframe for this case
