### ISSUE TITLE
[v3] React Checkbox/Radio onChange event not fired due to fastClick

### ISSUE THREAD

**Issue by mjwvb** [framework7io/framework7#2896]
* Framework7 version: 3.6.2
* React.js version: 16.6.3
* Platform and Target: 
  - Google Chrome Browser with developer tools + device toolbar turned on
  - Mobile browser (tested on iOS safari - iphone 6s)
  - (Cordova; I need to confirm this again)
* Live Link or JSFiddle: Reproducible using React KitchenSink, or using the following Fiddle with device toolbar turned on: https://jsfiddle.net/kLvg4rdt/2/

### Describe the bug
The onChange event on the Checkbox/Radio component is not fired on F7 React v3. However, it works again when you disable fastclick using the class "no-fastclick" or setting the touch param "fastClicksExclude" to "label.checkbox, label.radio".

### To Reproduce
1. Startup React Kitchen Sink
2. Add the following lines to home.jsx:

```javascript
// At the top
import { Checkbox, Radio } from 'framework7-react';

// Within <Page></Page>
<Block>
    <Checkbox onChange={() => { alert('onChange') }} />
    <Radio onChange={() => { alert('onChange') }} />
    No change event fired
</Block>
<Block>
    <Checkbox onChange={() => { alert('onChange') }} className='no-fastclick' />
    <Radio onChange={() => { alert('onChange') }} className='no-fastclick' />
    Change event fired with no-fastclick
</Block>
```

3. Open the kitchen sink page on your mobile phone, or in chrome developer tools with device toolbar turned on.
4. Click on the Checkboxes en Radio buttons. The ones on the first row do fire the event, while the ones on the second row don't.

**EDIT:** The following JSFiddle seems to work also, in contrary to what I originally posted here.
See https://jsfiddle.net/kLvg4rdt/2/. Make sure to open it with chrome developer tools + device toolbar turned on, and refresh afterwards. 

### Expected behavior
The onChange event should fire for Checkbox/Radio components, even if fastclick is enabled.

### Actual Behavior
The onChange event is not fired for Checkbox/Radio components.

### Additional context
- I noticed this problem with v3 since a couple of months, but always thought I did something wrong.
- While trying to debug, I also noticed that disabling fastclick as a whole doesn't work (using params: { touch: { fastClicks: false } }.

### Workaround
Adding the following app touch param works around the problem for now:
```javascript 
touch: {
        fastClicksExclude: "label.checkbox, label.radio"
}
```

**Comment by nolimits4web** [comment]
Closing as not actual anymore in v4
