### ISSUE TITLE
'@index' works abnormal in item-template for virtual list

### ISSUE THREAD

**Issue by hongfu** [framework7io/framework7#2898]
* Framework7 version: 2.0.6
* Platform and Target: Win 10， Chrome browser

Describe the bug
When ‘@index’ was used as virtual list as item template，the result was abnormal.

```
> var virtualList = app.virtualList.create({
>   el: '.virtual-list',
>   items: items,
>   itemTemplate:
>     '<li>' +
>       '<a href="{{@index}}" class="item-link item-content">' +
>         '<div class="item-inner">' +
>           '<div class="item-title-row">' +
>             '<div class="item-title">{{title}}</div>' +
>           '</div>' +
>         '</div>' +
>       '</a>' +
>     '</li>',
>   height:73,
> });
```

When output，only index 0 displayed for href, others were gone.

**Comment by nolimits4web** [comment]
@index is not supported here because it is not rendered in “each” T7 helper. Use renderItem instead, it passes index
