### ISSUE TITLE
pushStateRoot not working when use fremework7+vue

### ISSUE THREAD

**Issue by zhengmenglin** [framework7io/framework7#2900]
Hello, when I go to deep level navigation and come back to home page. It says not found error(404).

view:
 {
          pushState: 'true',
          pushStateRoot: '/'
  }

such as:
<img width="396" alt="1" src="https://user-images.githubusercontent.com/38604167/50272098-a8201080-0471-11e9-898d-3a169785e0b9.png">
<img width="396" alt="2" src="https://user-images.githubusercontent.com/38604167/50272115-b0784b80-0471-11e9-9ba3-dd4919c54029.png">
<img width="391" alt="3" src="https://user-images.githubusercontent.com/38604167/50272130-b5d59600-0471-11e9-81f9-b1eac45b76ec.png">
<img width="386" alt="4" src="https://user-images.githubusercontent.com/38604167/50272132-b79f5980-0471-11e9-9c42-3d462d986ab4.png">
<img width="385" alt="5" src="https://user-images.githubusercontent.com/38604167/50272135-ba01b380-0471-11e9-9380-ca687537e281.png">
<img width="384" alt="6" src="https://user-images.githubusercontent.com/38604167/50272138-bc640d80-0471-11e9-960f-3ade0bd80ea9.png">

I hope the sixth picture is the home page.

**Comment by nolimits4web** [comment]
What is your routes configuration?

**Comment by zhengmenglin** [comment]
<img width="694" alt="7" src="https://user-images.githubusercontent.com/38604167/50272664-67c19200-0473-11e9-963f-fd6d7565ddd0.png">

**Comment by mmis1000** [comment]
https://framework7.io/vue/view.html

I believe it work 100% in official way.
Have you tried it?

**Comment by nolimits4web** [comment]
You need to set home page’s route as component in routes too. This simple template is not for production

**Comment by zhengmenglin** [comment]
I know,this is just an example.

**Comment by zhengmenglin** [comment]
Thank you very much ! I have solved the problem,Framework7 is a great framework !
