### ISSUE TITLE
Framework7-core: Multi tabbar in same page breaks tab highlight under md theme

### ISSUE THREAD

**Issue by mmis1000** [framework7io/framework7#2901]
* Framework7 version: 3.6.1
* Platform and Target: all
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
If you place more than one tabbar for the same tabs, it will break

### To Reproduce
1. place more than one tabbar for the tabs
2. witch to md theme

### Expected behavior
I works smoothly without problem

### Actual Behavior
The tab highlight is broken

### Screenshots
<img width="327" alt="2018-12-21 2 01 19" src="https://user-images.githubusercontent.com/2993977/50327208-09ef8180-0529-11e9-8c02-f1365139b28a.png">
The hightlight should be under `SUN`, but actully it does not

### Additional context
https://github.com/framework7io/framework7/blob/0efa66dda3d5e1f54b5cacba67da41305236b925/src/core/components/toolbar/toolbar.js#L14

Line here should count items from "only" one tabbar instead of all tabbar

```
-- const tabLinksCount = $tabbarEl.find('.tab-link').length;
++ const tabLinksCount = $tabbarEl.eq(0).find('.tab-link').length;
```

**Comment by nolimits4web** [comment]
Can you please create minimal JSFiddle where i can see the issue? Need to see your layout
