### ISSUE TITLE
Routable Tabs  is not working when view-main is dynamic

### ISSUE THREAD

**Issue by Er-rchydy** [framework7io/framework7#2903]
* Framework7 version: 3.6.2
* Platform and Target: All
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/8u46arnz/)

### Describe the bug
The Routable Tabs  is not working when we  load the `viewMain` like this:
`var viewMain = app.views.create('.view-main', { url: '/' });`
you can only click on the tabs once, then after that you can't change it.

### To Reproduce
1. Click on any tab, then try to click another tab, it will not work

**Comment by nolimits4web** [comment]
You need to correctly specify links https://jsfiddle.net/8u46arnz/1/
