### ISSUE TITLE
Предложение: привести к одинаковым действиям одинаковые по названию опцию и метод в роутере

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2905]
В методах роутера **navigate** и **back** можно передавать в опциях:
**reloadAll** - удаление предыдущих страниц из истории и DOM
**clearPreviousHistory** - удаление предыдущих страниц только из истории

также есть метода для роутера:
**clearPreviousHistory** - удаление предыдущих страниц из истории и DOM
**clearPreviousPages** - удаление предыдущих страниц только из DOM

Получается два одинаковых названия, **clearPreviousHistory**, а действия - разные.
Предложение для "опций":
clearPreviousHistory - удаляет только из истории.
clearPreviousPages -удаляет только из DOM.
"Методы" сделать аналогично.

**Comment by ozra** [comment]
Perhaps it could be a prudent thing to include at least a google translation in issues, if tech-english is seen as the lingua franca? So it's easier to find things that might affect one when searching...
