### ISSUE TITLE
Visual User Session Replay

### ISSUE THREAD

**Issue by jdspugh** [framework7io/framework7#2907]
**Is your feature request related to a problem? Please describe.**
I want to be able to replay and view remote user sessions in my apps to improve user experience.

**Describe the solution you'd like**
It would be good to be able to playback user sessions much like hotjar.com does so we can analyse remote user behaviour.

**Describe alternatives you've considered**
- Hotjar
  - Doesn't work on mobile devices
- Firebase
  - Doesn't have visual session replay

**Additional context**
This could work by recording all inputs to the app and playing them back later. Inputs would include any non-deterministic events such as user input and incoming network events.

**Comment by nolimits4web** [comment]
Got the message from client that https://www.fullstory.com works good with Framework7

**Comment by jdspugh** [comment]
Great! I'll give it a try.
