### ISSUE TITLE
ListItem controlled component

### ISSUE THREAD

**Issue by joetm** [framework7io/framework7#2919]
Controlling radio button elements is a common task. I load choice options via an API. Once a choice is made, I show new options - so the radio buttons need to be cleared.
With simple components, like Input and Radio, it's straightforward to convert the component into a controlled element. But with ListItem, it's a mess. OnClick handler are registered on the labels, and don't trickle down to the input itself. OnClick handlers on the radio button itself go to the icon.
React deactivates the component and complains that no onChange event is set. But since the list items are deactivated by react, they cannot be changed.

Hypothesis: It is impossible to control the values of a Framework7 ListItem the way they are defined now.
Prove me wrong.

**Comment by nolimits4web** [comment]
It must be used with `onChange` event. https://jsfiddle.net/b8ur1mLn/ Check the About page
