### ISSUE TITLE
[v3] Problem with "list-index" and class "simple-list"

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#2923]
Please note that this problem only occurs with version 3 of Framework7 and not with version 4 (beta).

In the <code>"list-index"</code> with <code><div class="list simple-list contacts-list”></code> the group titles do not have a sticky position when scrolling within a single group.

Probably because the CSS property <code>"position: relative"</code> of the element <code>".list.simple-list li"</code> overwrites the CSS property <code>"position: -webkit-sticky"</code> of the element <code>"li.list-group-title"</code>.

Forcing <code>"!important"</code> on the property <code>"position: -webkit-sticky"</code> of the element <code>"li.list-group-title"</code>, the problem does not occur.

**Comment by elahe-dev** [comment]
> Please note that this problem only occurs with version 3 of Framework7 and not with version 4 (beta).
> 
> In the `"list-index"` with `<div class="list simple-list contacts-list”>` the group titles do not have a sticky position when scrolling within a single group.
> 
> Probably because the CSS property `"position: relative"` of the element `".list.simple-list li"` overwrites the CSS property `"position: -webkit-sticky"` of the element `"li.list-group-title"`.
> 
> Forcing `"!important"` on the property `"position: -webkit-sticky"` of the element `"li.list-group-title"`, the problem does not occur.

I have same problem
