### ISSUE TITLE
Dom7 click events in Components unbound on $setState

### ISSUE THREAD

**Issue by jdspugh** [framework7io/framework7#2925]
* Framework7 version: 3.6.3
* Platform and Target: Chrome

### Describe the bug
When using a component, on click functions bound using Dom7 set on pageInit are unbound when $setState() is executed.

### To Reproduce
Create a component with a pageInit and uses Dom7 to bind click events and then from the click events, call $setState.

### Expected behavior
Bound click method is executed.

### Actual Behavior
Click method is executed only until $setState is called.

### Additional context
I started using @click instead of binding clicks with Dom7's on click and the problem went away. So this bug should be fixed or a note made in the docs that people should only use the @click method.

**Comment by nolimits4web** [comment]
Well, it depends on what is changing on rendering. So if you bound something to `click` event and after rerendering that element replaced with another one the of course it won't work anymore - because element doesn't exist anymore. But if layout hasn't changed with `setState` and click events are gone, then it could be an issue. Do you have some minimal example of the component which causes this issue?

**Comment by nolimits4web** [comment]
Ok, it is what i said. New element was created.
Before set state you had
```
<li>
  <a href="#">1</a>
</li>
<li>
  <a href="#">2</a>
</li>
<li>
  <a class="onClickAdd"><i class="f7-icons">add</i></a>
</li>
```

And after
```
<li>
  <a href="#">1</a>
</li>
<li>
  <a href="#">2</a>
</li>
<li>
  <a href="#">3</a>
</li>
<li>
  <a class="onClickAdd"><i class="f7-icons">add</i></a>
</li>
```

So VDOM will change 3rd list item (with add link) to the category 3 and create new one with add link. You can see it by clicking on category 3 item, you will see log in console. To take control over it, you need to use keys http://framework7.io/docs/router-component.html#keys-in-lists-auto-init-components

Here is the working fiddle https://jsfiddle.net/4hpgvt3s/

**Comment by jdspugh** [comment]
Ah yes you are right, I do need to set keys in that case. Interestingly it also works in the first case if I switch to using @click https://jsfiddle.net/jdspugh/0ryLh4ov/3/
I guess @click adds a key or id automatically.

**Comment by jdspugh** [comment]
Ah yes you are right, I do need to set keys in that case. Interestingly it also works in the first case if I switch to using \@click https://jsfiddle.net/jdspugh/0ryLh4ov/3/
I guess \@click adds a key or id automatically.

**Comment by nolimits4web** [comment]
Yeah, `@click` rebinds events
