### ISSUE TITLE
Range control on popup page

### ISSUE THREAD

**Issue by aparmar** [framework7io/framework7#2926]
* Framework7 version: 3.6.3
* Platform and Target: Chrome browser on Win 10 machine. Eventual target for Android, iOS

Put a range slider on a popup page (in a list). Doesn't get initialized. Need to call API to initialize. Expecting it to work like it would on a normal page.

There is also some css weirdness with it getting off the page. Working through that.

**Comment by nolimits4web** [comment]
Yes, API must be used or it must be in initialized view like here https://jsfiddle.net/jgzdoL4w/
