### ISSUE TITLE
Архитектурная проблема / предложение по Framework7 при работе с Cordova'ой

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2929]
При использовании Cordova, у нас метод **init()** по-умолчанию откладывается до события **deviceready**. Это означает, что такой код:

```
var app = new Framework7({..});
console.log(app.data.var1);
```

при использовании **Cordova** не сработает (TypeError: undefined is not an object (evalutating 'app.data.var1')) на практике, т.к. после создании экземпляра **app** метод **init()** сразу же не выполнится, он будет ждать **deviceready** и доступа к **data** не будет. Иными словами, работать с **data** мы сможем только при обработке события **deviceready**. Хотя делать другие вещи, например создавать **View**, мы можем сразу. 

Я не знаю, почему **init()**'у при использовании **Cordova** нужно ждать **deviceready**. Также возникает другой вопрос: может ли успеть сработать анимация перехода на другой URL до того, как будет событие **deviceready** и, соответственно, **init()**. В таком случае доступа к **data** и на другой странице не будет. 

Может, это все ожидаемое поведение, но тогда это явно белое место в документации... Спасибо.

**Comment by nolimits4web** [comment]
Так положено, если такой подход не нужен, есть параметр `initOnDeviceReady` http://framework7.io/docs/app.html#app-parameters

> Также возникает другой вопрос: может ли успеть сработать анимация перехода на другой URL до того, как будет событие deviceready

Не может

**Comment by shastox** [comment]
Да, я перед созданием тикета ознакомился с опцией **initOnDeviceReady**.

Мне кажется, есть такие варианты:
1. Указать в документации, что **data** и **methods** будет доступны только после **deviceread**  (для Кордовы).

2. Всю-всю работу с кодом перенести в **deviceready** (или тут будут проблемы)?

3. Вынести создание **data** и **methods** в другой метод, который будет их создавать сразу при создании экземпляра Framework7.

**Comment by shastox** [comment]
Может кому пригодится. Вариант правильной работы с **data** и **methods** если нужна какая-то начальная инициализация:
var app ....
```
on : {
init : function () {
//Код
}
}
```
