### ISSUE TITLE
Gulp error: The following tasks did not complete: Did you forget to signal async completion?

### ISSUE THREAD

**Issue by yelban** [framework7io/framework7#2934]
* Framework7 version: [3.6.5]
* Platform and Target: []
* Live Link or JSFiddle: 

### Describe the bug
got `Gulp error: The following tasks did not complete: Did you forget to signal async completion?` error when stopping gulp server

### To Reproduce
1. npm run dev ( or prod, [code|react|vue]:dev )
2. stop Gulp with Ctrl+C
3. get error message

### Expected behavior
stop gulp server without error

### Actual Behavior
got Gulp error: The following tasks did not complete: Did you forget to signal async completion?

### Screenshots
![1546918377599](https://user-images.githubusercontent.com/981381/50808394-4c8ec780-1339-11e9-94a3-1a2d3f5bb430.jpg)

### Additional context
fixed pr [#3933](https://github.com/framework7io/framework7/pull/2933)
￼

**Comment by nolimits4web** [comment]
Fixed by #2933
