### ISSUE TITLE
Text on white button should be darken by default

### ISSUE THREAD

**Issue by l2aelba** [framework7io/framework7#2935]
![screenshot 2019-01-08 at 12 10 30](https://user-images.githubusercontent.com/983458/50827315-6d0d5080-133e-11e9-9b81-e4433127df03.png)

* Framework7 version: 3.6.3
* Platform and Target: All (ios & md)
* Live Link or JSFiddle: https://jsfiddle.net/9jLvgfmd/

### Describe the bug
Text on **white button** (.color-white) should be dark.

### To Reproduce
1. Go to https://jsfiddle.net/9jLvgfmd/
2. See first button has white text.

### Expected behavior
Text should be black or primary or something better by default. **without custom fix**

### Actual Behavior
Text is white

**Comment by nolimits4web** [comment]
Just add extra `text-color-$color` class to that button

**Comment by l2aelba** [comment]
@nolimits4web 
Thanks, but does not it quick fix?
