### ISSUE TITLE
router.clearPreviousHistory не применим при работе с popup

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2939]
В routes:
```
        {
            path: '/page1',
            componentUrl: './page1.html',
        },
        {
            path: '/page2',
            popup : {
                componentUrl: './pages/page2.html'
            },
        },
```

```
var view = app.views.create('#view', {
    url : '/page1',
});

```
Теперь на странице **page1** жмем на` <a href="/page2">Page2</a>`, открывается **popup**.

Задача: обновить содержимое (сделать рефреш) **page1** в методе компонента **page2**. Или, в крайнем случае, при закрытии **popup** сделать рефреш **page1**.

Поскольку открытие / закрытие **popup** - это навигация, с добавлением / удалением в **view.history**, пробуется такое решение:

`view.router.clearPreviousHistory(); `

Теперь ожидается, при закрытии **popup** (т.е. возврате "назад"), **router** сделать рефреш **page1**.

Чтобы происходит на самом деле:
- из **view.history** происходит удаление информации о **page1**
- из **DOM** - нет.

При закрытии **popup** **page1** не обновляется. 

Метод **clearPreviousHistory** был добавлен этим реквестом: https://github.com/framework7io/framework7/pull/2842

**Comment by nolimits4web** [comment]
Поправил этот кейс, но это конечно не самый оптимальный способ так делать. Проще отправить событие в попапе `app.emit('foo')` и по этому событию в page1, сделать то что нужно чтобы обновить UI

**Comment by shastox** [comment]
Мы сможем в page1 только обновить UI, а вот просто "рефрешнуть" не сможем, т.к. page1 и page2 находятся в одном вью, т.е. код view.router.refreshPage(); обновит текущий popup.
