### ISSUE TITLE
this.$f7ready is not a function

### ISSUE THREAD

**Issue by srsalute** [framework7io/framework7#2949]
#######################################################################
That is my component:
#######################################################################

![code1](https://user-images.githubusercontent.com/14018087/51393889-f9c6c400-1b1f-11e9-911f-c7ccb687f328.PNG)
![code2](https://user-images.githubusercontent.com/14018087/51393661-5f668080-1b1f-11e9-92f2-d6419e5f385f.PNG)

...
########################################################################
this is the error i got in console:
########################################################################
TypeError: this.$f7ready is not a function
    at VueComponent.mounted (pages_Dashboard_index.js:687)
    at callHook (commons.app.js:13256)
    at Object.insert (commons.app.js:14489)
    at invokeInsertHook (commons.app.js:16284)
    at Vue.patch [as __patch__] (commons.app.js:16503)
    at Vue._update (commons.app.js:12995)
    at Vue.updateComponent (commons.app.js:13117)
    at Watcher.get (commons.app.js:13477)
    at new Watcher (commons.app.js:13466)
    at mountComponent (commons.app.js:13130)

![error1](https://user-images.githubusercontent.com/14018087/51393821-ce43d980-1b1f-11e9-9a16-4d03cf02cdd0.PNG)
![error2](https://user-images.githubusercontent.com/14018087/51393822-ce43d980-1b1f-11e9-8a1a-9d88085a91d2.PNG)

########################################################################
I follow this http://framework7.io/vue/installation.html, http://framework7.io/docs/installation.html
I have installed framework7, framework7-vue
The f7-gauge works, but the f7-wiper not works, the error is in f7-swiper and is "this.$f7ready is not a function"
My english is not very good, sorry for any confusion, please help me with this.

**Comment by nolimits4web** [comment]
And did you follow this guide http://framework7.io/vue/init-app.html ? Where is your Framework7.use(...)?

**Comment by srsalute** [comment]
Ok, Framework7.use(Framework7Vue) works, i dont get the error "this.$f7ready is not a function" anymore, but the swiper in the page dont work, he prints all cards and dont make the slide, look
![tela1](https://user-images.githubusercontent.com/14018087/51475254-f8d4a300-1d68-11e9-9b18-02a5a742058d.PNG)
Have i use the tag  <f7-app :params="$root.f7params"> ? because i dont using a layout, only components, can i use this tag in a component?

**Comment by nolimits4web** [comment]
Only component can’t be used. Correct app layout must be preserved with `f7-app` and the rest http://framework7.io/vue/app-layout.html

**Comment by srsalute** [comment]
I'm doing: 
import Framework7 from 'framework7';
import Framework7Vue from 'framework7-vue';
//import Framework7 from 'framework7/framework7.esm.bundle';
//import Framework7Vue from 'framework7-vue/framework7-vue.esm.bundle.js';

Framework7.use(Framework7Vue);
Vue.use(DashboardPlugin)

In my layout file i'm using: 
                  <.f7-app>
                     <.f7-view>
                        <.nuxt/>
                     <./f7-view>
                  <./f7-app>
but the framework7 still dont work, the swiper still dont work

**Comment by srsalute** [comment]
i'm trying use <.f7-card> too, but dont work as the swiper, the only component has work until now was the gauge, i dont know what i missing, the <.f7-card> dont show nothing, like there is no css.
