### ISSUE TITLE
Running a F7 project has high CPU load

### ISSUE THREAD

**Issue by tiptronic** [framework7io/framework7#2952]
* Framework7 version: 4.0.0 beta 25
* Platform and Target: Mac, iOs, Android (not tested on Windows)

When running devServer and opening any project in a browser (e.g. kitchen-sink at `http://0.0.0.0:3000/kitchen-sink/vue/`, the CPU-load jumps to 99% (quad-core i7 iMac)
![image](https://user-images.githubusercontent.com/80752/51426374-15969c80-1bea-11e9-926c-98f35c318f11.png)

It seems to constantly invalidate and re-render all styles.

This makes it impossible to preview a project on slower devices, because rendering impacts the whole performance of such a device. (If you want to check: Get an older Android device and run 'Cards expandable' on it -> It flickers like crazy)

Btw: you can reproduce it on Safari for Mac or Android WebView. 
On Chrome and Firefox it works

**Comment by nolimits4web** [comment]
See this issue on desktop Safari, could be Safari issue on how it handles CSS vars. Will investigate

**Comment by nolimits4web** [comment]
Ok, found out it is a WebKit bug https://bugs.webkit.org/show_bug.cgi?id=194332

**Comment by tiptronic** [comment]
Cool! Great find!! I'll see, if I can disable the gradients and test again!

**Comment by nolimits4web** [comment]
Temporary solution, just add this CSS rule to custom stylesheet:
```css

**Comment by tiptronic** [comment]
Ah - so you mean it's really *just* affected, when custom properties inside gradients are used??

**Comment by nolimits4web** [comment]
Yes, so if we replace it here with actual value then issue with overload is gone

**Comment by ZMilosevich** [comment]
I also noticed, high cpu usage on desktop (OSX 10.14.3, Safari, Fr7 4.1.1), default theme: 'md'. When I switch to 'ios' theme it works fine. On Chrome and FF no issue at all with both themes'md' or 'ios'. I tried css fix for 'md' theme same CPU issue.

**Comment by maxime-guyot** [comment]
I have same problem as @ZMilosevich (macos Mojave, Safari 12.0.3 : Framework7 4.2.0)
Problem seems to come from navbar, when i remove it from DOM, CPU load is ok 🤔
Problem visible on https://framework7.io/kitchen-sink/core/?theme=md

(the problem is also present with IOS)

with navbar :
<img width="1440" alt="Capture d’écran 2019-03-24 à 08 28 22" src="https://user-images.githubusercontent.com/5451838/54876362-e6312580-4e0e-11e9-9f13-ba82edd9e258.png">

without navbar :
<img width="1440" alt="Capture d’écran 2019-03-24 à 08 30 27" src="https://user-images.githubusercontent.com/5451838/54876373-1c6ea500-4e0f-11e9-8b86-3834d003a4da.png">

**Comment by bcd55** [comment]
This is still a problem in Safari 13.0.3 with md theme. I added the suggested CSS rule and that solved it for me. Thanx!

**Comment by webraptor** [comment]
on a 2.6 GHz 6-Core Intel Core i7 processor, running on MBP 16" 2019, MacOS Catalina:
- without this CPU usage is roughly 10%
- with this CPU usage is less than 2%

**Comment by webraptor** [comment]
> Temporary solution, just add this CSS rule to custom stylesheet:
> 
> ```css
> .md .navbar a.link:before,
> .md .toolbar a.link:before,
> .md .subnavbar a.link:before,
> .md .data-table-rows-select a.link:before,
> .md .data-table-pagination a.link:before,
> .md .searchbar-disable-button:before,
> .md .searchbar .input-clear-button:before,
> .md .notification-close-button:before {
>   background-image: radial-gradient(circle at center, rgba(0, 0, 0, 0.1) 66%, rgba(255, 255, 255, 0) 66%);
> }
> ```

on a 2.6 GHz 6-Core Intel Core i7 processor, running on MBP 16" 2019, MacOS Catalina:
- without this CPU usage is roughly 10%
- with this CPU usage is less than 2%
