### ISSUE TITLE
В v4 перестал работать FastClick, viewport не помогает

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2954]
Версия: v4.0.0-beta.26
Тестирование на реальном устройстве: iPhone 6S Plus, iOS 12.1.2

После обновления v3 => v4 перестал работать FastClick, это видно невооруженным глазом: на айфоне заметна пауза между тапом по ссылке и действием.

Viewport:

`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui, viewport-fit=cover">`

также есть:
`<meta name="apple-mobile-web-app-capable" content="yes">`
  
Если добавить в конфиг включение FastClick, который, согласно блогу, был отключен по умолчанию, все заработает:

```
var app = new Framework7({
    touch: {
        fastClicks: true,
    },
..
}
```

Может что-то еще есть, влияющие на FastClick?

**Comment by shastox** [comment]
Нет, задержки нет, в Сафари все хорошо.

**Comment by nolimits4web** [comment]
Возьми оттуда мета таг. Может minimal-ui ломает, это не валидное значение

**Comment by shastox** [comment]
Похоже, это какая-то проблема с Кордовой. В Сафари если открыть веб-версию приложения, то все хорошо, а сборка PhoneGap - дает задержки.

**Comment by nolimits4web** [comment]
Вот это плагин должен стоять https://github.com/apache/cordova-plugin-wkwebview-engine

**Comment by shastox** [comment]
> Вот это плагин должен стоять https://github.com/apache/cordova-plugin-wkwebview-engine

Спасибо! Не знал, что только в WKWebView убрали задержку. Если кому интересно, вот обсуждение: https://github.com/ftlabs/fastclick/issues/514

**Comment by shastox** [comment]
Кто только переходит на WKWebView: плагин https://github.com/apache/cordova-plugin-wkwebview-engine сломает загрузку локальных файлов, к примеру файлов роутера.

Нужно использовать: https://github.com/ionic-team/cordova-plugin-ionic-webview

Тема на форуме: http://forum.framework7.io/t/solved-cors-issues-with-f7-in-wkwebview/1767
