### ISSUE TITLE
Side Panel Content is not changing

### ISSUE THREAD

**Issue by hypesol** [framework7io/framework7#2956]
Hi
I am working on framework7 and I made a menu of the side panel of the home screen. and also make a side menu on the internal page. But whenever I clicked on the menu of the internal page that always opens the menu of the homepage.

Content is not replacing Please guide me how I can solve this issue.

Thanks

**Comment by praveenmujawdiya** [comment]
You can use routable panels: http://framework7.io/docs/panel.html#routable-panels
