### ISSUE TITLE
Проблема с Pull-to-refresh и некоторыми элементами

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2957]
Версии тестирования: v3 и v4 (последняя).
Ссылка: http://f7.dev.t3b.ru/ (пример очень минимален, на v3). Роутер подгружает страницу по адресу: http://f7.dev.t3b.ru/pages/main.html

Есть некоторые элементы, которые ломают pull-to-refresh. В примере есть timeline и pull-to-refresh. Если мы кликаем по свободной области справа и тянем вниз - проблем нет. Если мы кликаем по жирному **TITLE** и тянем вниз, то тут возникают проблемы: pull to refresh не работает. Также замечены проблемы с row и col-*. Как выглядит это "не работает":

**Сафари (iOS 12)**: происходит bounce-эффект, весь экран тянется вниз. Можно просто открыть ссылку в iPhone, чтобы увидеть проблему.

 **Cordova (iOS 12)**: пока тянем вниз, стрелка тянется вниз, не переворачивается.

**Cordova (Android 6)**: стрелка вообще не появляется.

**Comment by nolimits4web** [comment]
Related #2944 ?

**Comment by shastox** [comment]
> Related #2944 ?

У автора того тикета есть в примере  **style="height: 100%"**, у меня же нет никакой кастомизации. Коммит https://github.com/framework7io/framework7/commit/a8a2de7aca4c5808f3c8189d91fb728cf48bcea6 включен в v4 beta26, а там проблема также воспроизводится. Поэтому не уверен, что тоже самое.

Пример обновил до v4 beta26.

**Comment by shastox** [comment]
В его примере https://jsbin.com/wojuwiture/edit?html,js,output я вообще не смог в Сафари на iPhone увидеть какой-то проблемы: все ок.
