### ISSUE TITLE
(Vue+F7) A "Reset to root" option for panels so no 'back' buttons show up on immediate children

### ISSUE THREAD

**Issue by cepm-nate** [framework7io/framework7#2958]
**Is your feature request related to a problem? Please describe.**
I have a nice pop-out panel on the left with a menu of links. When I tap one of the links, the new screen shows a large 'BACK' button at the top left of the screen. That back button is not needed, as this page is directly reachable from the menu, and is NOT a sub-page of whatever else was showing prior to me opening the menu.

**Describe the solution you'd like**
I'd like an option in panel settings (or router) to make the target link the new 'main' view, so it smoothly transitions to it and leaves the menu button at the top left of the window instead of replacing it with a <BACK button.

**Describe alternatives you've considered**

- I tried putting the panel menu into it's own page and using it as the root, but that makes for a horrible tablet experience (full screen width list items!). Having the menu in the panel works well as I can set the leftBreakpoint, and it looks great on a tablet, desktop, and a phone.
- I've tried firing $f7router.clearPreviousHistory() on @panel:close and @panel:closed, no dice.
- I've tried setting stackPages=true on the page / panel containing the menu, but I don't think that quite fits the bill.
- Adding the 'left menu' button to each of the headers of the pages linked from the menu. This seems like it would add a lot of useless history and make the android:back button act a little funny sometimes. But this option is most likely candidate so far.

**Additional context**
I'm new to Vue and Framework 7, perhaps there is a better solution or an event that I'm overlooking? Does anyone else use a "master menu" in a panel?

**Comment by nolimits4web** [comment]
I guess you mean so called Split View. In this case logic should be the following:
- on left panel link which load pages which are considered as "root" pages just add `data-reload-all="true"` attribute on `reload-all` vue property. 
- in addition you can add someting like `?isRoot=true` to the link url, and handle it in loaded page component to show menu link in this case or back link if it is not root

**Comment by cepm-nate** [comment]
Thanks @nolimits4web , I overlooked those attributes. In the future, where is the best spot to ask questions like this?

**Comment by nolimits4web** [comment]
Best place for questions i forum, as always https://forum.framework7.io
