### ISSUE TITLE
Framework7 SvelteJS Version 3 component

### ISSUE THREAD

**Issue by ansarizafar** [framework7io/framework7#2963]
It would be great If framework7 also has components for Sveltejs Version 3.

**Comment by DenisNP** [comment]
There is no crossplaftorm UI-library for Svelte for now. Framework7 can be first :)

**Comment by ansarizafar** [comment]
Is there any new update on this issue?

**Comment by cayter** [comment]
@ansarizafar Isn't Svelte 3 already implemented? https://framework7.io/svelte/introduction.html

**Comment by srbala** [comment]
@ansarizafar  Please close this issue, Svelete components are available now
