### ISSUE TITLE
Ripple Effect in custom element or custom content in V4

### ISSUE THREAD

**Issue by marcosdourado** [framework7io/framework7#2964]
Hello everyone.

I'm having a problem with the ripple effect.
When I get an element, for example a Link and add an extra content, the ripple effect simply hides it for a few seconds and then returns the element again (when the effect ends), here example of customization:

```html
<Link href="/example/">
  <span className="super-text">Teste</span>
</Link>
```
the result of this is:
![click](https://user-images.githubusercontent.com/4989884/51715212-ed120680-201e-11e9-9eab-7294da3cb960.gif)

I think the problem of this is simply a matter of positioning, however I have no idea how the ripple was built. My question then is can I consider this as a bug? Is there any way to resolve this other than "no-ripple"?

I already thank the answers, I searched but I did not find anything related, if it exists, please show me. Thank you very much

**Comment by nolimits4web** [comment]
Maybe have some styling conflict. Ripple element basically will prepend `<div class="ripple-wave"></div>` to the link content so it will become:
```
<a href="/example/" class="link">
  <div class="ripple-wave"></div>
  <span class="super-text">Teste</span>
</a>

**Comment by marcosdourado** [comment]
Hey @nolimits4web  using Button component instead of Link, it worked. I just did not go deep to understand why, maybe after I do that. Thank you anyway :)
