### ISSUE TITLE
app.virtualList.get doesnt work on a dynamic page

### ISSUE THREAD

**Issue by CodingAnonymous** [framework7io/framework7#2965]
Hi, I have a virtualList on my home page and it is initialised in app.js.

app.virtualList.get(".virtual-list"); in app.js work perfect when I'm on the home page, but when I'm on a dynamic template7 page and perform the same app.virtualList.get(".virtual-list"); in app.js I get nothing (undefinded) back. Where is the error?

When I log the variable app on a dynamic template7 page, I don't get the current view correct: app.views.current is "-".

**Comment by nolimits4web** [comment]
I guess you call it in a wrong time or in a wrong place, or you need to specify correct selector. Please provide a JSFiddle with the issue
