### ISSUE TITLE
Android App freeze while opening panel and scrolling list at the same time

### ISSUE THREAD

**Issue by freddysu** [framework7io/framework7#2966]
I use the template from https://github.com/phonegap/phonegap-template-vue-f7-split-panel
and updated both framework7 & framework7-vue to 3.6.5
To reproduce the bug, I just add a f7-list in Home.vue from the template with dummy data so it can be scrolled.
Here's the complete code: https://github.com/freddysu/f7-panel-bug-demo

* Framework7 version: framework7: 3.6.5, framework7-vue: 3.6.5
* Platform and Target: Android Cordova app (Not on iOS)
* Live Link or JSFiddle: 

### Describe the bug
On physical Android device, when scrolling the list and click on menu icon to open the panel at the same time, the app will freeze.

### To Reproduce
1. Scroll the page before it stop and click on menu icon at the same time
2. The whole app freeze (all you can do now is kill the app)

### Expected behavior
Open the panel before/after the scrolling finished without freezing the App.

### Actual Behavior
The whole page freeze no matter what you click.

### Screenshots
![screenshot_20190125-162504](https://user-images.githubusercontent.com/2948101/51734678-35cdcc00-20c0-11e9-9ac6-eaa45658464d.png)

### Additional context
I've tried not use framework7-vue ``<left-panel-view />`` and use plain framework 7 ``<div class="panel panel-left panel-reveal">`` instead. But the bug still exists.
You can only see the bug on physical Android device cuz you need to scroll and then click the menu icon at the same time.

**Comment by ivanq21** [comment]
I have this problem too.  And I dont know how to solve this shit

**Comment by freddysu** [comment]
> I have this problem too. And I dont know how to solve this shit

I just build my own drawer on Android and use f7's drawer on iOS, but my drawer does not support swiping to open. Also, I have to maintain both my drawer and f7's drawer which is quite inconvenient. Hope they can fix it asap.

**Comment by ivanq21** [comment]
I have one solution after a lot of wasted time. Its work for me, but I think its not perfect solution, I know it's awful =) but anyway...
First,I put in near link element with class .panel-open  one more element for example with class "over_hide". And set it position absolute to cover .panel-open, for prevent click on menu button)
 Like this : 
<div class="left">
                      <div class="over_hide"></div>
                         <a href="#" class="link icon-only panel-open" data-panel="left">
                          <i class="f7-icons size-36">menu</i>
                          </a>
    </div>

Second, I manipulated with js, to be precise with touch events.
Like this:

  document.addEventListener('touchstart', onDocumentTouchStart, false);
   document.addEventListener('touchmove', onDocumentTouchMove, false);

 var over;
 function onDocumentTouchMove(){
        clearTimeout(over);
        $$('.over_hide').show();
        $$('body').addClass('active');
        over = setTimeout(function() {
            $$('.over_hide').hide();
            $$('body').removeClass('active');
        }, 1500);
    }
    function onDocumentTouchStart(){
        clearTimeout(over);
    }
    $$('.over_hide').on('click', function(){
        $$(this).hide();
    })

It help's me)

**Comment by Remskei** [comment]
I have the same issue. When trying to open panel before scrolling animation is finished, the app freeze.

**Comment by mrbboy** [comment]
I seem to be having the same issue, I tried keeping track of the scroll and remove class panel-open from the "a" element and add it back in after a timeout of 250.  But unfortunately the issue still prevails.   Are there any updates?
