### ISSUE TITLE
Split view (using version 4.0.0-beta.28) not work

### ISSUE THREAD

**Issue by krosoftware** [framework7io/framework7#2971]
I downloaded template: https://framework7io.github.io/framework7-template-split-view/ and try to use it with 4.0.0-beta.28 - it does not work correctly with Material Theme

**Comment by nolimits4web** [comment]
These templates are not yet ready to work with v4. Use `framework7-cli` to start v4 project https://forum.framework7.io/t/new-framework7-cli-feedback-needed/5373/58
