### ISSUE TITLE
Font size in the Picker Date-Time causes overflow problems in small screens

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#2975]
* Framework7 version: 3.6.5 and 4.0.0 beta 29
* Platform and Target: iOS and Android (Read below)

### Describe the bug
The problem occurs with the **iOS theme** on screens with dimensions like the **iPhone SE** and the **iPhone 8** and with the **MD theme** on screens with dimensions like the **iPhone SE**.

### To Reproduce
View the Picker page in Kitchen Sink example from the framework7.io site with devices with this screen size.

### Screenshots
![iphonese-picker](https://user-images.githubusercontent.com/1197819/51804918-e70e6680-2266-11e9-9c22-d03990a87bba.png)

**Comment by shastox** [comment]
Set **--f7-picker-column-font-size** https://github.com/framework7io/framework7/blob/v4/src/core/components/picker/picker.less#L39

**Comment by DAnn2012** [comment]
Thanks @shastox for the reply.

Yes, probably by using Framework7 v4 this is the solution (if possible, with media queries).

But do not you think that an automatic reduction would be better when the screen size is small?

**Comment by shastox** [comment]
No, because the screen is small, and you want to make a lot of columns.

**Comment by DAnn2012** [comment]
Okay!

**Comment by DAnn2012** [comment]
This solution seems to work with both v3 and v4 on screens with dimensions like the iPhone SE and the iPhone 8:

```
@media (max-width: 375px) and (orientation: portrait) {
	.picker-columns {
		font-size: 20px !important;
	}
}

@media (max-width: 320px) and (orientation: portrait) {
	.picker-columns {
		font-size: 16px !important;
	}
}
```
