### ISSUE TITLE
При вызове метода router.refreshPage два и более раза для popup происходит их накопление

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2978]
Версия: v4 beta 31
Пример: http://f7.dev.t3b.ru/ 
Самый минимальный код. На первом экране, который в DOM, есть ссылка на открытие **popup**, контент которого встроен в конфиг routes: http://f7.dev.t3b.ru/js/app.js

**Воспроизведение проблемы**
1. Жмем на popup.
2. В открывшемся popup жмем на Reload два и более раза. Вызовется функция:

```
function reload()
{
	viewMain.router.refreshPage();
}
```

Если мы кликнули два и более раза, то образуется стек попапов и при закрытии, т.е. нажатии на Close, у нас один закроется попап, а под ним будет - другой.

**Comment by shastox** [comment]
Обновил пример, сделал его еще минимальней.

**Comment by nolimits4web** [comment]
Ну этот метод никак не предназначен для перезагрузки popup'a целиком, да и незачем так делать. Если очень нужно, то просто инициализируй View внутри попапа, и делай reload/refresh на нем
