### ISSUE TITLE
Incorrect padding-top when toolbar on top and hide-navbar-on-scroll is enabled for tab page-content

### ISSUE THREAD

**Issue by 1isten** [framework7io/framework7#2980]
* Framework7 version: v3 and v4 beta
* Vue.js version: 2.5.13
* Platform and Target:
For v3, in Android devices or Browsers(md theme);
For v4 beta, both md theme and ios theme(when set toolbar position to the top)
* Live Link or JSFiddle: https://jsfiddle.net/1isten/d230xkqy/12/
(live jsfiddle for v3 only because I can't find the CDN link for v4 beta version)

### Describe the bug
When toolbar(tabs) is positioned under the navbar at the top and hide-navbar-on-scroll is enabled for page-content, after scrolling down one of the tab content(triggering navbar-hidde), the padding-top value is incorrect for other tabs' page content.

**padding-top: calc(var(--f7-navbar-height) + var(--f7-toolbar-height));**

should be

**padding-top: calc(var(--f7-toolbar-height));**

when the navbar is hidden.

### To Reproduce
1. Go to https://jsfiddle.net/1isten/d230xkqy/12/
2. Scroll down the content for tab1 to hide the navbar
3. Switch to tab2 and tab3
4. See the incorrect large padding top of the contents of tab2 and tab3

### Expected behavior
padding-top for page-content should be only the height of toolbar when navbar is hidden.

### Actual Behavior
padding-top: calc(var(--f7-navbar-height) + var(--f7-toolbar-height));

### Additional context
(May be another bug) For framework v4 beta I found that when placing the toolbar at the top and enabling hide-navbar-on-scroll, for ios theme the toolbar cannot be pushed to the top when hiding navbar on scroll. It just stays on the same position and it leaves the position where navbar was placed at an empty gap. Currently I can't make a live jsfiddle for that because no v4 CDN and maybe I will open a new issue for that bug if the final release of v4 does't fix that.

**Comment by nolimits4web** [comment]
It is not really an issue and padding there is correct. You should just call `navbar.show()` method you switch the tab. Changing padding on page content is not correct approach because content will jump on navbar hide/show.

The second issue with Toolbar staying on same place when navbar hidden is fixed

**Comment by 1isten** [comment]
> > Is there a way to keep it hidden while tab switching and only show again if I scroll up any of the page content?
> 
> But if you change page-content's padding to just toolbar height and switch to new Tab (which is on top), how can you show it if there won't be possible to scroll top? Or what if tab's height is low and it is not scrollable at all. Optionally you can change then current tab's `.scrollTop` property and maybe if its is on top, then show navbar, otherwise keep its hidden

I didn't realize the un-scrollable problem XD. I'll try `.scrollTop` to do the trick. Thanks for your following up and advice.
