### ISSUE TITLE
Skeleton font is displaying incorrectly (iOS)

### ISSUE THREAD

**Issue by YaroslavErmolaev** [framework7io/framework7#2981]
* Framework7 version: 4 beta 31
* Platform and Target: iOS 12 Cordova app (iPhone X iOS 12.1.2)

![img_2203](https://user-images.githubusercontent.com/22396848/52202945-82748c80-28a2-11e9-9d4b-2736e1a6cf07.PNG)

**Comment by shastox** [comment]
В kitchen работает?

**Comment by nolimits4web** [comment]
Fixed
