### ISSUE TITLE
[v4] --f7-device-pixel-ratio not correctly set on iPhone 6s

### ISSUE THREAD

**Issue by mjwvb** [framework7io/framework7#2982]
* Framework7 version: 4.0.0-beta34
* Platform and Target: iPhone 6s (iOS 12.1.2)

On the iPhone 6s the border height is not scaled for hi-dpi purposes. The variable --f7-device-pixel-ratio contains the value 1, although it should be 2. The effect is that borders are two times as thick as they should be.

I was trying to debug the problem, and it seems that it doesn't respond to the following media query:

```css
@media (min-resolution: 2dppx) {
    --f7-device-pixel-ratio: 2;
}
```

On the other hand, it works with the following:

```css
@media
  only screen and (-webkit-min-device-pixel-ratio: 2),
  only screen and (   min--moz-device-pixel-ratio: 2),
  only screen and (     -o-min-device-pixel-ratio: 2/1),
  only screen and (        min-device-pixel-ratio: 2),
  only screen and (                min-resolution: 192dpi),
  only screen and (                min-resolution: 2dppx) { 
    :root {
        --f7-device-pixel-ratio: 2;
    }
}
```

It seems that an additional ":root { ... }" wrapper is required, and also "-webkit-min-device-pixel-ratio: 2".
(see https://css-tricks.com/snippets/css/retina-display-media-query/)

Another working quickfix:

```css
.device-pixel-ratio-2 {
    --f7-device-pixel-ratio: 2;
}
```

**Comment by nolimits4web** [comment]
Can't see such issue, as you can see in output CSS https://unpkg.com/framework7@4.0.0-beta.35/css/framework7.css it is rendered to:
```css
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx) {
  :root {
    --f7-device-pixel-ratio: 2;
  }
}
@media (-webkit-min-device-pixel-ratio: 3), (min-resolution: 3dppx) {
  :root {
    --f7-device-pixel-ratio: 3;
  }
}
```

So if you use autoprefixer in your app, make sure you have correct browser list setup https://github.com/framework7io/framework7/blob/master/package.json#L42-L50

**Comment by mjwvb** [comment]
Oh well that was the problem actually: I wasn't using any autoprefixer (nor postcss) at all in my css processing chain of webpack... 

I'm importing framework.bundle.less into my own less file to modify the color variables in there. This was inherited from my v3 implementation. However, as I was not using the autoprefixer, min-resolution was not being prefixed by -webkit. I finally fixed this by adding postcss to the chain, with the postcss-preset-env plugin.

I don't know if framework.less is actually intended to be imported from outside? If so, then it would probably be useful to document the autoprefixer requirement somewhere for v4 migration.

Anyway, thank you for your help and keep up the good work! It's the best mobile UI framework out there really :)

**Comment by nolimits4web** [comment]
👍
