### ISSUE TITLE
'no-hairline' class cannot be applied for navbar in iOS theme ('.navbar:after' cannot be removed)

### ISSUE THREAD

**Issue by 1isten** [framework7io/framework7#2985]
* Framework7 version: v3 and v4 beta
* Vue.js version: 2.5.13
* Platform and Target: iOS theme
* Live Link or JSFiddle: https://jsfiddle.net/1isten/d230xkqy/15/

### Describe the bug
In iOS theme, class cannot be applied as `<f7-navbar title="My App" class="no-hairline or-any-other-classes">` always renders to `<div class="navbar"></div>` with only a single 'navbar' class. So, the hairline of navbar cannot be removed.

### To Reproduce
1. Go to https://jsfiddle.net/1isten/d230xkqy/15/
2. The sample code is trying to hide the navbar hairline with `class="no-hairline"` or scoped css
3. Check with Chrome inspector, the 'no-hairline' class is not applied to the navbar html element
4. The hairline still exist

### Expected behavior
'div.navbar::after' should be removed

### Actual Behavior
'div.navbar::after' still exists

**Comment by nolimits4web** [comment]
See https://github.com/framework7io/framework7/issues/2869

**Comment by 1isten** [comment]
Any update?
