### ISSUE TITLE
overswipe not working on touchscreen

### ISSUE THREAD

**Issue by utillity** [framework7io/framework7#2986]
* Framework7 version: 4.0.0-beta.35 (also .34)
* React.js version: 16.8.1
* Platform and Target: OpenEmbedded (Linux) with Electron 2.0.2

### Describe the bug
I use a List and ListItem with a swipeout and one SwipeoutButton has overswipe set. This works as expected and used to work fine also with version F7v3. After deploying to the embedded hardware, ever since F7v4 (both beta 34 and 35) the overswipe action is not applied. I have to slowly swipe the menu open and manually tap one of the SwipeoutButtons. They also won't always activate on first tap either - sometimes I have to retry 3 or 4 times, until the action is executed. As stated, it works fine with F7v3x

### To Reproduce
That's the hard part. It only breaks on the embedded device with a touchscreen. It works just fine, when I open the same compilation on any other browser or platform.

regards, Tilli

**Comment by nolimits4web** [comment]
Can you try to enable `touch.fastClicks: true` app parameter?

**Comment by utillity** [comment]
added that to my Framework7Params - will test on next deploy and let you know. thanks for the tip!

**Comment by utillity** [comment]
Yep, that's the problem! When activating fastClick, overswipe works again! Thanks for the tip!
