### ISSUE TITLE
Strange behavior of firefox with autocomplete

### ISSUE THREAD

**Issue by hmr-it-jr** [framework7io/framework7#2988]
* Framework7 version: 3.6.2
* Platform and Target: Firefox (Win 10)

### Describe the bug
It's not possbible to select something from autocomplete.

### To Reproduce
1. Start firefox
2. Go to a page with autocomplete
3. Try to select

### Expected behavior
Select should happen.

### Actual Behavior
It is strange. We develop some apps where in development everything was fine. Since test release some users say that in firefox the autocomplete is not working. We weren't able to reproduce it. So today - out of nowhere - one of our dev computers where it worked perfectly stopped doing it's job. I've created a video for you. There are no errors on the console. It's the latest version of firefox with no extensions.

### Screenshots
[http://sendvid.com/xwrnk983](http://sendvid.com/xwrnk983)

**Comment by hmr-it-jr** [comment]
It might be similar to #2549

**Comment by hmr-it-jr** [comment]
@nolimits4web we did some research and found out it has something to do with the screen size. If we go into the developer tools and set a larger screen size it works.

Here is a more detailed video: 
http://sendvid.com/0ivbl9kr

In Firefox there is this message on the console if we open it while clicking on the autocomplete:

**original:** Speicherverbrauch von "will-change" ist zu hoch. Die Budget-Grenze ist die Fläche des Dokuments multipliziert mit 3 (250125 px). Vorkommen von "will-change", die das Budget überschreiten, werden ignoriert.

**translated:** memory consumption of „will-change“ is too high. The budget-maximum is the area of the document multiplied by 3 (250125 px). Existing "will-change" which consume more than the budget will be ignored.

Hardware: As you can see in the video we use as 24 inch screen with full hd 1920x1080

-------------

**We will pay you (or any other user) for fixing it - please contact us at: info@hmr-it.de**
Remote testing on our machines where the bug occurs is possible!

**Comment by nolimits4web** [comment]
@hmr-it-jr so it even happens to you in Chrome? Can someone else replicate it?

**Comment by hmr-it-jr** [comment]
@nolimits4web yes, we've discovered that if it happens on a device it's bugy in all browsers which are installed on the device. We can confirm it on more than 20 devices with different specs (normal computers and developement computers with >16 GB RAM and Intel i7). So it's not a problem with limited resources. In Chrome there is no warning on the console, but on Firefox the message from above shows up. As in #2549 no one was able to replicate it, but we and the users of our app can replicate it - in our app and on the fromework7.io autocomplete page. Browsers are all clean without any addons, we've even tried to disable anti virus and firewall, etc. but nothing worked. We're out of ideas so that's why we want you to pay for fixing it asap.

**Comment by hmr-it-jr** [comment]
@nolimits4web thank you for trying to fix it, but it's not fixed yet. I've created a small demo of autocomplete  with framework7 4.1.1 but it's still not working.

![20190314_090527](https://user-images.githubusercontent.com/36242595/54340972-ec6a1980-4638-11e9-8aff-3d7d7a8cd64a.gif)

**Comment by hmr-it-jr** [comment]
@nolimits4web any news? How can we support you with this issue?

**Comment by hmr-it-jr** [comment]
@nolimits4web this bug is still in v5.1.3 - is there really no way to fix it? We would pay you for that to fix it!

![f7bug](https://user-images.githubusercontent.com/36242595/69408451-33032e00-0d07-11ea-9f18-88906262a923.gif)
