### ISSUE TITLE
Status bar text color android

### ISSUE THREAD

**Issue by khudia** [framework7io/framework7#2989]
On out of box when creating cordova vue app there black text color on black statusbar.
And may be there is anywhere theme to post sugestions for updates. Such as for example "click" on back button on android navigate router back. Thanks

**Comment by nolimits4web** [comment]
Use http://framework7.io/docs/statusbar.html#statusbar-app-parameters `androidBackgroundColor` and `androidTextColor` statusbar parameters with required values
