### ISSUE TITLE
Need help to Extend New Framework 7 V2 for AngularJS 1.x.

### ISSUE THREAD

**Issue by siddmegadeth** [framework7io/framework7#2993]
Need help to Extend New Framework 7 V2 for AngularJS 1.x.
If possible please provide plugins for Framework V2 using AngularJS 1.x
.
We have exisiting app built using AngularJS 1.x using Framework 7 V1.
We would like to upgrade to Framework7 V2.

We are not looking to change or upgrade to Vue or React.
AngularJS currently serve our purpose and we are invested in it.

**Comment by nolimits4web** [comment]
Duplicate #2794
