### ISSUE TITLE
"Panel": Problem with v4 running on iOS 9.x / iOS 10.x

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#2997]
I've already read that version 4 is not fully compatible with iOS 9.x and iOS 10.x because they do not support CSS variables correctly.

Despite this, I wanted to check on the simulator iOS 10.2 (14C89) and I also found what is shown in the video (#2937).

It seems that the apparent block is due to something that has to do with Panel and the "**with-panel-transitioning**" class in `<html>,` "**panel-backdrop**" (with the style _display: block_) and "**panel-closing**" (and the style _display: block_) classes in `<div>` that remain even after the closing of the Panel and all the taps are addressed on "**panel-backdrop**".

These are the classes with the Panel open:

![with-panel-open](https://user-images.githubusercontent.com/1197819/52534640-90b02600-2d44-11e9-9e41-1297af55c6cb.png)

And these are the classes after closing the Panel:

![after-panel-close](https://user-images.githubusercontent.com/1197819/52534673-d7058500-2d44-11e9-9185-6d5b332f2cb5.png)

Is it not possible to solve this problem by doing other tests of version 4 on iOS 9.x and iOS 10.x?

Thanks.

**Comment by nolimits4web** [comment]
The only fix here can be by replacing CSS variables with actual values. 

On latest 10.3.x it works correctly

**Comment by DAnn2012** [comment]
Yes, on iOS 10.3.x and later it works correctly.

However, I wanted to look for the reason why on the lower versions it does not work.

I tried to turn off animations by using the following commands to open and close the panels in the Safari console and the situation seems to have improved:

```
app.panel.open("left", false)
```
```
app.panel.close("left", false)
```
```
app.panel.open("right", false)
```
```
app.panel.close("right", false)
```
So, the problem seems connected to animations.

**Comment by nolimits4web** [comment]
The reason is CSS variables, more specific - inability to do transitions for transform values with CSS variables. That is why many other transitions can be broken too

**Comment by DAnn2012** [comment]
I tried to replace `transition-duration` with `-webkit-transition-duration` in the framwork7.bundle CSS file and now the animations on iOS 10.2 seem to work well.

**Comment by SpiderNeo1** [comment]
Hello, 
Thanks to @DAnn2012 for relaunching the subject.

Did you try to add the tag `-webkit-transition-duration` instead of replacing `transition-duration` ?

Personally, I would like to run my app on the V4 instead of the V3. But my application must be at least compatible with iOS 9.3.

As soon as I have a moment, I’ll run some tests on my side.

Thanks to you two.

**Comment by DAnn2012** [comment]
Hello @SpiderNeo1 ,

I tried to generate a new content of the `framework7.bundle.css` file with the online tool

[http://www.cssdrive.com/cssautoprefixer/](http://www.cssdrive.com/cssautoprefixer/)

with a browser filter wider than the one contained in the `browserslist` section of the v4 `package.json` file (which is different from that of v3) and added me the lines with the prefix `-webkit-` automatically.

The tests I've done so far seem pretty positive.

**Comment by SpiderNeo1** [comment]
CSS variables works from mobile safari >= 9.3
