### ISSUE TITLE
Accordion Content Text Missing Randomly

### ISSUE THREAD

**Issue by kyleroberthammond** [framework7io/framework7#2998]
* Framework7 version: 3.6.6
* React.js version: 16
* Platform and Target:Chrome 72

Has anyone bumped into this before? 

![issue](https://user-images.githubusercontent.com/12946312/52543818-9162be00-2e11-11e9-9a21-cb88f82012fb.gif)

**Comment by Jaimet92** [comment]
I've a similar problem in accordion list. There is a visual glitch when opened.

* JSFiddle: https://jsfiddle.net/amfyw5rp/1/
* Framework7 version: 3.6.6
* Vue.js version 3.6.6
* Platform: Chrome, Android, iOS

**Comment by Jaimet92** [comment]
![ezgif-2-665bee81dc4b](https://user-images.githubusercontent.com/1878622/52581775-e8758c80-2e2b-11e9-8557-6e40a79b91f0.gif)

**Comment by kyleroberthammond** [comment]
Also happening on 4.0.1

**Comment by kyleroberthammond** [comment]
> I've a similar problem in accordion list. There is a visual glitch when opened.
> 
> * JSFiddle: https://jsfiddle.net/8zhr3vkc/3/
> * Framework7 version: 3.6.6
> * Vue.js version 3.6.6
> * Platform: Chrome, Android
> * On Safari & Firerox 65 & Edge this does not seem to happen

Find any work arounds for this? It seems to be pretty random for me. 4.0.1 does seem to do it less often.

**Comment by Jaimet92** [comment]
When TouchRipple shuts down, visual failure is more noticeable: https://jsfiddle.net/mc1k6gL5/

Some items don't render until scroll or click another item.

**Comment by Jaimet92** [comment]
I have been able to fix it by removing the 'swipeout' attr: https://jsfiddle.net/z7fs9n04/

**Comment by kyleroberthammond** [comment]
Ok here is a clear example of it.
For framework7 React. It seems to be related to having the ListItem as a link or href

https://jsfiddle.net/quallman1234/vcme6snq/

**Comment by kyleroberthammond** [comment]
Any hints of a fix? Its only happening in chrome :(. Dont have a large user base so can shift them to firefox for the time being.

**Comment by AliMamed** [comment]
have the same problem with react and chrome

**Comment by kyleroberthammond** [comment]
Still happening in 4.3.1
