### ISSUE TITLE
Scoped styles is invalid in some cases.

### ISSUE THREAD

**Issue by jacktanxd** [framework7io/framework7#2999]
* Framework7 version: 3.6.6
* Platform and Target: iOS 12 HBuilder app, or Chrome browser
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
I want to modify the navbar style on some pages, so I used 'scoped' to achieve this, but it failed.

### Code show as below
`<style scoped>
	.ios .navbar {
		background-color: #2D3F5E;
		color: white;
	}
</style>`

**Comment by nolimits4web** [comment]
This won't work because scoped styles are scoped to component, so it will be translated to something like `component .ios .navbar {}` which is not a valid selector. And in iOS theme navbar is detached from page, check in dev tools for correct layout and styling
