### ISSUE TITLE
Md theme colors not applied to navbar / toolbar

### ISSUE THREAD

**Issue by nschermer** [framework7io/framework7#3004]
* Framework7 version: 4.0.1

### Describe the bug
In v4 the toolbar/navbar are not colored to the theme color.

### To Reproduce
<body class="color-theme-red">

### Expected behavior
Red bar with white text. Feels more native on md.

### Actual Behavior
Gray bar with red/black text.

**Comment by nolimits4web** [comment]
> Feels more native on md.

It feels same native. If you need what you ask, check Kitchen Sink -> Color Themes

**Comment by nschermer** [comment]
A sorry, i completely overlooked this.
