### ISSUE TITLE
[v3] backport input's clear button behaviour from v4

### ISSUE THREAD

**Issue by waptaxi** [framework7io/framework7#3010]
In v3 when input is focused and we tap it's clear button, keyboard hides and shows up again causing flickering and viewport resizing.
But in v4 it works like a charm without hiding a keyboard.
Is it possible to backport this feature to v3 for those who are not ready for v4 yet?

**Comment by nolimits4web** [comment]
With pleasure, but not really possible as it is due to fast clicks disabled in v4. It is not so easy to disable it in v3. What you can try is to add `no-fastclicks` class to some input's parent element, maybe to parent list item or parent list

**Comment by waptaxi** [comment]
Thanks, made it work by setting `no-fastclick` class (NOT `no-fastclicks` ) to parent `<f7-list-input>`
