### ISSUE TITLE
"typing" field in package.json has wrong value in 4.0.2

### ISSUE THREAD

**Issue by fjorgemota** [framework7io/framework7#3011]
* Framework7 version: 4.0.2
* Platform and Target: Any

### Describe the bug

In 4.0.2 the `typing` field in the package.json has value `framework7.d.ts`, the problem is that file doesn't exist in root path of the package.

I'm not sure if this is related to #3006, because I didn't changed anything related to package.json there, so maybe some script is getting the wrong value somewhere? I don't know.

### To Reproduce
1. Create a project and install `framework7` and `typescript`;
2. Create a typescript file importing framework7;
3. Try to compile the file, it will fail with the following error:

```
TS7016: Could not find a declaration file for module 'framework7'. node_modules/framework7/js/framework7.js' implicitly has an 'any' type.
  Try `npm install @types/framework7` if it exists or add a new declaration (.d.ts) file containing `declare module 'framework7';` 
```

### Expected behavior
The file should compile successfully

### Actual Behavior
Typescript will emit the following error:

```
TS7016: Could not find a declaration file for module 'framework7'. node_modules/framework7/js/framework7.js' implicitly has an 'any' type.
  Try `npm install @types/framework7` if it exists or add a new declaration (.d.ts) file containing `declare module 'framework7';` 
```

**Comment by nolimits4web** [comment]
Woops, i accidently changed it. Releasing 4.0.3 right now

**Comment by fjorgemota** [comment]
No problem! Thank you for the corrections! :)
