### ISSUE TITLE
Search Bar Styling on Android with Dark Theme

### ISSUE THREAD

**Issue by jdspugh** [framework7io/framework7#3017]
* Framework7 version: 4.0.5
* Platform and Target: Android

### Describe the bug
Android search bar is white in the Smart Select component when a dark theme is applied.

### To Reproduce
Create a Smart Select component with search enabled and go to the selection screen. You will see the white search bar.

### Expected behavior
Should be more consistent with the iOS theme by adding these css stylings:

```
.md .theme-dark,
.md.theme-dark {
  --f7-searchbar-bg-color: #303030;
  --f7-searchbar-input-bg-color: #171717;
  --f7-searchbar-input-text-color: #fff;
}
```

### Screenshots
Current styling with a dark theme
<img width="270" alt="screen shot 2019-02-17 at 9 01 25 pm" src="https://user-images.githubusercontent.com/3017823/52913254-3c361900-32f7-11e9-9367-daf9eb7d0ecc.png">

Styling with suggested css modifications
<img width="272" alt="screen shot 2019-02-17 at 9 00 52 pm" src="https://user-images.githubusercontent.com/3017823/52913255-3c361900-32f7-11e9-8853-0b2fe91ad913.png">

**Comment by nolimits4web** [comment]
Thanks, makes sense, pushed fix
