### ISSUE TITLE
$setState handling of quotes

### ISSUE THREAD

**Issue by jdspugh** [framework7io/framework7#3018]
* Framework7 version: 4.0.5
* Platform and Target: All
* Live Link or JSFiddle: https://jsfiddle.net/6dvye3h7/

### Describe the bug
It seems that $setState doesn't handle quotes. If I use the above JSFiddle and edit the name from John Smith to John "Smith", clicking the Done button does nothing.

**Comment by nolimits4web** [comment]
Yes, it happens because `value="John Smith"` becomes `value="John "Smith""` which generates invalid HTML markup. In this case (and in latest 4.0.5) just use `escape` helper here and it will work correctly https://jsfiddle.net/jrycu640/

**Comment by jdspugh** [comment]
Makes sense. Thanks for the solution.
