### ISSUE TITLE
V4 some thing about card-expandable 

### ISSUE THREAD

**Issue by boboxiaodd** [framework7io/framework7#3020]
* Framework7 version: [e.g. 3.0.0] 4.0.5
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser] iOS12 Cordova
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
i use `card-expandable` and `Pull to Refresh`
but when `card-expandable` swipeToClose ,  `pull to refresh` also fire
i must to 
destory `pull to refresh` and hide `ptr-arrow` when `card-expandable` open
create `pull to refresh`  and show `ptr-arrow` when `card-expandable` close

some times , `card-expandable` can't complete expandable:

![image](https://user-images.githubusercontent.com/4714247/52934813-84eee000-3392-11e9-81b6-3f7979df63a3.png)

![image](https://user-images.githubusercontent.com/4714247/52934837-97691980-3392-11e9-8706-4453150efddd.png)

**Comment by nolimits4web** [comment]
Pushed fix to not enable PTR on expandable cards when they opened. But for the second case when it is not opened correctly would be good to see live example or JSFiddle

**Comment by boboxiaodd** [comment]
i use background-image replace img , it work correct
```html
<div data-id="{{id}}" class="card card-expandable  bg-color-black">
            <div class="card-content">
                <div style="background: url({{photo}}) no-repeat center top; background-size: cover; height: 100vw">
                    <div class="card-header text-color-white">{{name}}</div>
                    <a href="#" class="link card-close card-opened-fade-in color-white" style="position: absolute; right: 15px; top: 15px">
                        <i class="icon f7-icons">close_round_fill</i>
                    </a>
                </div>
                <div class="card-content-padding">
                    ....
                </div>
            </div>
</div>
```
