### ISSUE TITLE
Not working on Android 5.1

### ISSUE THREAD

**Issue by TkStas** [framework7io/framework7#3021]
* Framework7 version: 4
* Platform and Target: Cordova Android 5.1

Does not work - app.views.main.router.navigate ();
Error in the core - line 2544
     / * iosPreloaderContent: ("\ n <span class = \" preloader-inner \ "> \ n" + (Array.from ({length: 12})) map (function () {return '<span class = "preloader -inner-line "> </ span> ';}). join (' ')) +" \ n </ span> \ n ") .trim (), * /
Does not work - async (routeTo, routeFrom, resolve, reject) {}

**Comment by nolimits4web** [comment]
You may need `Array.from` polyfill https://github.com/es-shims/Array.from
