### ISSUE TITLE
Unexpected token )

### ISSUE THREAD

**Issue by aigenseer** [framework7io/framework7#3022]
Hallo,

i am using Cordova with React and your Framework7. I create with Babel and Webpack bundle files and i get always syntax Errors on my Code. I had to adapt the following lines in Framework7-react(^4.0.0) and in Framework7(^4.0.0).

Framework7-react

Line 721 "}," to "}"
![bildschirmfoto vom 2019-02-19 09-52-19](https://user-images.githubusercontent.com/26250042/53003565-7f93a300-342f-11e9-9822-e3568ed24ac2.png)

Alle Funktionen mit den Parametern "options.props || {}," sind betroffen
Line 35, 122, 180 "options.props || {}," to "options.props || {}"
![bildschirmfoto vom 2019-02-19 09-52-49](https://user-images.githubusercontent.com/26250042/53003670-c5506b80-342f-11e9-80db-9f1c26d1f55f.png)

Framework7
Line 805 "}," to "}"
![bildschirmfoto vom 2019-02-19 10-00-31](https://user-images.githubusercontent.com/26250042/53003807-182a2300-3430-11e9-8bff-80c7ad05359b.png)

Line 56, 77 "}," to "}"
![bildschirmfoto vom 2019-02-19 10-01-59](https://user-images.githubusercontent.com/26250042/53003872-3e4fc300-3430-11e9-806a-687b3799af05.png)

**Comment by nolimits4web** [comment]
Make sure you have correctly configured Babel https://github.com/framework7io/framework7-cli/blob/master/create-app/templates/generate-webpack-config.js#L69-L81

https://babeljs.io/docs/en/babel-plugin-syntax-trailing-function-commas

**Comment by aigenseer** [comment]
Thank you for the feedback!
I adjusted my Babel configuration, but to no avail. I still get the same error messages.

![bildschirmfoto vom 2019-02-19 11-14-50](https://user-images.githubusercontent.com/26250042/53007471-9a6a1580-3437-11e9-8bf1-fa119890ee30.png)

.babelrc
`
{
  "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
  "plugins": [
    "syntax-trailing-function-commas",
    "@babel/proposal-class-properties"
  ]
}
`
