### ISSUE TITLE
Uncaught Error: Cannot find module 'framework7-react'

### ISSUE THREAD

**Issue by durgeshsatyam** [framework7io/framework7#3026]
* Framework7 version: [e.g. 4.0.5]
* React.js version: [e.g. 16.8.3]
* Platform and Target: Chrome browser
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/vxb8oyke/)

### Describe the bug
`    import Framework7React from 'framework7-react'; `

After importing framework7-react v4.0.5 I am getting the following error in my browser
Uncaught Error: Cannot find module 'framework7-react'

Although while using the  framework7-react v3 it works just fine.
I think this is a bug in the framework7-react v4.

### To Reproduce
install framework7-react v4.0.5 in meteor
and import it.

**Comment by nolimits4web** [comment]
How does it related to Framework7? Everything is correct in `framework7-react` package. It is for sure something wrong on your Meteor-side, check and make sure this module is bundled and included correctly

**Comment by JimVanEeden** [comment]
I actually have the same problem. Installed using `yarn add framework7-react`. Upon inspecting I find that in framework7-react there is this line: `"main": framework7-react.js`, but that file doesn't exist in the folder, while it did in v3.
