### ISSUE TITLE
input-clear-button overlaps input when longer text or numbers

### ISSUE THREAD

**Issue by pontigol** [framework7io/framework7#3027]
* Framework7 version: 3.3.2
* Platform and Target: iOS 12 Cordova app

### Describe the bug
When typing a longer text or number that fills the whole input, the last character is covered by the input-clear-button. This only happens with regular inputs. Searchbar works fine, there's a small gap between the last character and the clear button.

### Expected behavior
See gif describing the (according to me, correct) behavior in searchbar.
![input-clear-button-no-overlap](https://user-images.githubusercontent.com/16635066/53249352-30ac6e80-36b8-11e9-840d-0c0a509cbebf.gif)

### Actual Behavior
See gif describing the (according to me, incorrect) behavior in regular input.
![input-clear-button-overlap](https://user-images.githubusercontent.com/16635066/53249378-3bff9a00-36b8-11e9-93de-300535c7270c.gif)

### Additional context
Gifs taken when using framework7 website in browser (for convenience) but same behavior in iPhone app.

**Comment by DAnn2012** [comment]
This happens because `.searchbar input` has a right padding of 48-pixel in the theme MD and 28-pixel in the theme iOS while `.list input` has no right padding.

**Comment by pontigol** [comment]
Thanks! That fixed it. Should it be changed in F7 or is there a reason why there's no padding-right on .search bar input (eg follows md / ios style guide)?

**Comment by DAnn2012** [comment]
Hello @nolimits4web 

In future updates, you plan to add a variable similar to this:

`--f7-searchbar-input-padding-horizontal`

also for the other `input` fields to add padding to the right?

Thanks.

**Comment by DAnn2012** [comment]
Hello @nolimits4web

sorry if I insist and I repeat the question:

In future updates _of framework7 v4_, you plan to add a variable similar to this:

`--f7-searchbar-input-padding-horizontal`

also for the other `input` fields to add padding to the right?

Thanks.

**Comment by nolimits4web** [comment]
@DAnn2012 sure, will add on a days
