### ISSUE TITLE
Jumpy surrounding elements when opening/closing Expandable Cards 

### ISSUE THREAD

**Issue by JJJ** [framework7io/framework7#3029]
### Describe the bug
The closing animation of an expandable card is jumpy.

It almost appears to reset or disregard to Y-offset of the page’s scroll position, in addition to possibly not reserving the card’s original dimensions before being expanded.

Note that this does not affect the first card; only the second and after.

### To Reproduce
1. Create a few expandable cards, one after another
2. Scroll down and expand a card
3. See the surrounding cards jump out of place

### Expected behavior
iOS expandable cards do a pretty good job at leaving their surrounding elements unaffected by their zoom animations. It’s a rather impressive set of calculations and mockery. I think the expectation is that these work as well as those, which IMO is a pretty high standard.

### Actual Behavior
Animation is very close, but the surrounding elements shifting around ruin the rest of the experience.

### Screen Recording (converted to GIF)

![89a7b8e2-495d-4546-8da3-01d44898ea78](https://user-images.githubusercontent.com/88951/53299258-6c9d1c00-37fd-11e9-929f-5d00d5ac560a.gif)

**Comment by nolimits4web** [comment]
Can anyone else see this? For some reason i can't replicate it on my iPhone X iOS 12.1.4

**Comment by Overman775** [comment]
expandable card not jumpy on Galaxy s9 note on ios and android theme, but they flicker sometimes

https://drive.google.com/file/d/1GGXmMmDWkCVBBFMrKOEqVcgj5TjDpkgD/view?usp=sharing

**Comment by willmero** [comment]
@nolimits4web Was able to repro this in Safari under 12.2.0 see video here:
https://www.youtube.com/watch?v=j2HMKVl1_6g&feature=youtu.be

Would love to implement this feature into some of my apps!

**Comment by willmero** [comment]
Confirmed this is an issue introduced in iOS 12.2.0. Things working fine on iOS 12.1.x

**Comment by JJJ** [comment]
Issue persists in iOS 12.3 betas.
