### ISSUE TITLE
Iphone XS Max Status bar and home button bar floats

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#3030]
* Framework7 version: v3
* Platform and Target: IOS

### Describe the bug
top status bar and home button bar is floating around app's navbar and bottom bar, not sure if this is a framework 7 issue, or by cordova issue. any thoughts? refer to image below. 

![image](https://user-images.githubusercontent.com/14131170/53312170-f5e04b80-38ee-11e9-82ff-3c369d97084f.png)

**Comment by shastox** [comment]
JSFiddle ?

**Comment by pluckannfeel** [comment]
doesnt need to have jsfiddle, its clear what's the problem is

**Comment by Overman775** [comment]
Read this https://framework7.io/docs/safe-areas.html

**Comment by pluckannfeel** [comment]
safe areas are applied automatically on portrait view. which should work fine

**Comment by pluckannfeel** [comment]
@nolimits4web  hello vladimir, are safe area only available on version 4 of framework 7?

**Comment by nolimits4web** [comment]
@pluckannfeel hi, it is not a framework7 issue, it uses safe areas when they are available, could be a webview or cordova config issue. Make sure you are using latest cordova with WKWebView

**Comment by nolimits4web** [comment]
And latest Framework7 v3 or v4
