### ISSUE TITLE
[Documentation] missing Vue -> Dialog

### ISSUE THREAD

**Issue by cepm-nate** [framework7io/framework7#3038]
* Framework7 version: 4.0.6 (as shown on site)

### Describe the bug
The page at https://framework7.io/vue/ does not have the 'Dialog' section.

### To Reproduce
1. Go to https://framework7.io/vue/introduction.html
2. Look at list of components.
3. Notice that 'Dialog' is missing

### Expected behavior
I would expect there to be a page about it, as Dialog exists within the kitchen sink app for vue.
https://github.com/framework7io/framework7-vue/blob/master/kitchen-sink/src/pages/dialog.vue

But I do see that there is not an actual f7-dialog component, but not having a link for it is a little confusing at first.

Perhaps this could be explained on the intro page? Something like "There are additional features available in Framework7, even if they don't have specific Vue components. Feel free to use the Search or Ktichen Sink to find them"?

**Comment by nolimits4web** [comment]
Just use core API in the way like it is done in kitchen sink, there is no sense to duplicate same Dialog docs as for core
