### ISSUE TITLE
Popover: not correct targetEl (in event info)

### ISSUE THREAD

**Issue by YaroslavErmolaev** [framework7io/framework7#3042]
* Framework7 version: 4.0.6
* Platform and Target: iOS 11 Cordova app
* Live Link or JSFiddle: https://jsfiddle.net/enzo0508/tdcnw3kL/

### Describe the bug
Only the first-popover targetEl return always (in popoverOpen event).

### To Reproduce
1. Click "Button 1"
2. See alert info
3. Click "Button 2"
4. See alert info (same button-id)

**Comment by nolimits4web** [comment]
https://jsfiddle.net/n64Lv089/
