### ISSUE TITLE
Apply V4 corrections on V3

### ISSUE THREAD

**Issue by SpiderNeo1** [framework7io/framework7#3043]
Hello Vladimir, 

I hope you're okay.

Just to ask you, if you could apply the common fixes from V4 to V3 please while I find a way to make the V4 compatible with iOS 9.0 and 10.0 (https://github.com/framework7io/framework7/issues/2997)

Thank you. Have a good day !

**Comment by nolimits4web** [comment]
Only critical fixes will be applied for v3. What fixes you are looking to be applied for v3?

**Comment by SpiderNeo1** [comment]
This https://github.com/framework7io/framework7/commit/00630031657e7ea35eeb94f285b5bc3cf9c9f818 or this https://github.com/framework7io/framework7/commit/399c94528c60c7b09053d62190380abf6d44b68f for example.

**Comment by nolimits4web** [comment]
This https://github.com/framework7io/framework7/commit/399c94528c60c7b09053d62190380abf6d44b68f is about expandable cards, there is no such in v3 ;) 

Another one not so critical to do the full release, there are a lot of other ways how to attach event listener in React, Vue.

A bit later yes, this will land to v3

**Comment by SpiderNeo1** [comment]
Thank you Vladimir.
