### ISSUE TITLE
Custom build failing to exclude iOS or MD themes with custom config

### ISSUE THREAD

**Issue by PhilSole** [framework7io/framework7#3044]
Framework7 version: 4

I was trying to create a custom F7 build to minimise unused CSS by leaving out ios in the config.themes array.  ios styles keep on showing up in the resultant build.  

I investigated and found in 'build-core-styles.js' that the 'buildBundle()' function ignores the config and includes both ios and md themes.  Is this intentional?

**Comment by nolimits4web** [comment]
Pushed fix, but it won't save much in v4, it was actual and significant in v3, that is why i included both themes
