### ISSUE TITLE
[Vue f7-tab] click tabbar cannot render the tab's content

### ISSUE THREAD

**Issue by alterhu2020** [framework7io/framework7#3046]
* Framework7 version: 4.0.6
* Vue.js version: 2.6.3
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle:  https://github.com/ForkProjects/framework7-issue-example.git

### Describe the bug
click the tabbar just as official kitchen-sink's vue demo in the page:  [https://github.com/framework7io/framework7/blob/master/kitchen-sink/vue/src/pages/tabbar.vue ](https://github.com/framework7io/framework7/blob/master/kitchen-sink/vue/src/pages/tabbar.vue )
which I had used in Vue-Cli3 , but it doesn't work.

### To Reproduce
1. Git clone this repository:  [https://github.com/ForkProjects/framework7-issue-example](https://github.com/ForkProjects/framework7-issue-example)
2. Go to the root folder, and run the command `npm install` and `npm run serve`
3. When the server started , go to the home page and click the "About" link to the about page
4. In the about page ,click the Tab 1, Tab 2 to see the tab page if rendered content or not .

### Expected behavior
Click the tab,the tab content should be rendered to correct current correct 

### Actual Behavior
Tab content not rendered to current tab's content ,still the first tab's content.

### Screenshots

![image](https://user-images.githubusercontent.com/5029046/53678956-edc64880-3d00-11e9-8e6e-3c0c0ef190f8.png)

### Additional context
**Could you add the latest Vue-Cli 3 example for framework-vue if possible ?**  thanks very much .

**Comment by alterhu2020** [comment]
@nolimits4web What's the reason it doesn't work in my Vue CLI3 for framework7 4.0.6 ? appreciated that your help .

**Comment by nolimits4web** [comment]
Read documentation correctly, you need to include `framework7.bundle.css` if you include bundle js

**Comment by alterhu2020** [comment]
oh, my god . thanks @nolimits4web
