### ISSUE TITLE
Невозможно применить стиль <style scoped> для компонента роутера в iOS -теме для navbar'a

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3048]
Для стилизации **data-f7-...** добавляется к элементу `<div class="page">` а в iOS-теме navbar на одном уровне с этим элементом, т.е. мы не сможем стилизовать навбар.

**Comment by shastox** [comment]
Вот это строка: https://github.com/framework7io/framework7/blob/a4adebff1aa92bd25374a17146802ad62e75c0a6/src/core/modules/component/component-class.js#L101

Для iOS-темы, по идее, этот атрибут должен ставиться просто и для navbara.

**Comment by shastox** [comment]
Этот баг сильно мешает стилизации под iOS. Просто использовать style без scope бывает не подходит: мы ставим стиль для popup, который на большом экране открыт не на весь экран и мы можем сломать стили подложки.

Может есть какое-то временное решение?

**Comment by nolimits4web** [comment]
Автоматически не могу добавить так как это может много сломать. Теперь можно добавить в ручную к любому элементу
```
<div class="page">
  <div class="navbar">
    <div class="navbar-inner" data-f7-{{$id}}> .... </div>
  </div>
</div>

**Comment by shastox** [comment]
А к самому navbar можно добавить? Ведь классы к navbar нельзя устанавливать, их F7 игнорирует (возможно, только в ios-теме).
