### ISSUE TITLE
Pull To Refresh icon never disappears after pulling down page

### ISSUE THREAD

**Issue by macsupport** [framework7io/framework7#3055]
* Framework7 version: 4.1.0
* Platform and Target: iOS 11+ Cordova app

[jsfiddle](https://jsfiddle.net/macsupport/Lmj65og7/)

Pull To Refresh has worked for me since version 2 with the following code. After upgrading to v4.10, when one pulls down to initiate PTR, the icon rotates infinitely and doesn't every go away.

  

```
 var ptr = app.ptr.get(".ptr-content");
var $ptrContent = $$('.ptr-content');
// Add 'refresh' listener on it
$ptrContent.on('ptr:refresh', function (e) {
  // Emulate 2s loading
  setTimeout(function () {
    app.ptr.done(); // or e.detail();
  }, 1000);
});
```

### Expected behavior
Icon should disappear after settimeout

**Comment by nolimits4web** [comment]
Just check console and you immediately will see your error. Here is working version https://jsfiddle.net/hfwq58rd/

**Comment by macsupport** [comment]
Oops, I just forgot to add Jquery to the jsfiddle (but it's in my project). Unfortunately, in my App, with jQuery loaded and the above code, I still have this issue in v4. 
[Here is a link to the App]([url](http://www.vetcalculators.com/app/)). PTR is enabled on each page linked from the main page.
