### ISSUE TITLE
"theme-dark" doesn't apply on panels

### ISSUE THREAD

**Issue by armavion** [framework7io/framework7#3057]
[Using version 4.1.0, released on march 4th 2019]

I applied "theme-dark" to body tag. Everything is beautifully dark, except the right panel which is still white. 

Used the following code:
<div id="app">
    <div class="panel panel-right panel-reveal">
            <div class="list links-list">
...
                </div>
    </div>
</div>

This is the light theme:
https://cloud.armankarimi.com/index.php/s/o7nNUCh37azmPor/download

And this is the dark theme:
https://cloud.armankarimi.com/index.php/s/i4f59xaPM0Z6Ybp/download

Thanks :)

**Comment by nolimits4web** [comment]
Make sure there i a correct layout in right panel with `.view` and `.page` elements

**Comment by armavion** [comment]
This is my layout:

    <div id="app" class="">
        <div class="panel panel-right panel-reveal">
            <div class="list links-list">
            <ul>
                <li></li>
            </ul>
        <div class="view view-main"></div>
    </div>

#app is the first thing in <body class="theme-dark">

Am I doing something wrong? 

Thanks

**Comment by nolimits4web** [comment]
There must be a page element inside in order to have dark bg color:
```
<div class="panel panel-right panel-reveal">
  <div class="page">
    ... other content
```

**Comment by armavion** [comment]
Thank you Vlad. I must've missed it in the docs.
