### ISSUE TITLE
Any icon doesn't display on Android device, but PC.

### ISSUE THREAD

**Issue by JamesZBL** [framework7io/framework7#3058]
While running dev server, Any icon doesn't display on Android device, I used Firefox for Android. But they display on my dev PC.

**Comment by hectorgrebbell** [comment]
Have you tried connecting a network debugger?
https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE

**Comment by shastox** [comment]
Возможно, проблема с путями к файлам шрифтов.
