### ISSUE TITLE
Выбор стек технологии

### ISSUE THREAD

**Issue by amediateam** [framework7io/framework7#3060]
В процессе выбора стека столкнулся с вопросом. Основной критерии производительность!
Какой самый оптимальный, производительный и быстрый ?
1. Framework7 Core
2. Framework7  Vue
3. Framework7 React

**Comment by shastox** [comment]
Возможностей Core хватит и для сложных проектов - проверено многократно, да, что-то менее удобно, но "костылей" не будет точно.

Если вы планируете использовать Cordov'у, то рекомендую не использовать ни Vue или ни React, т.к. крайне важна скорость работы, а любые доп. библиотеки только замедляют. Например, F7 используют свою реализацию Dom7, а не тащит каких-то монстров.

Если вы делаете сложный веб-сайт и действительно хорошо знаете Vue / React, то рекомендую использовать одну из этих технологий. Если вы не владеете ни Vue ни React, то сначала изучите их, чем просто лезть на F7 + Vue / React, ведь чтобы использовать правильно любую технологию, ее стоит сначала хорошенько изучить.
