### ISSUE TITLE
Проблема с CSS-переменными при использовании "чужой" темы

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3061]
У нас тема iOS и есть subnavbar. Задача: поменять высоту navbar и установить ему md-тему.

1. Пишем в CSS: 
```
:root{
    --f7-subnavbar-height: 200px;
} 
```
Все ок, высота изменена.

2. Теперь в `<div class="subnavbar">` добавляем класс **md** и получаем: `<div class="md subnavbar">`. После этих действий высота **navbar** вернулась к исходному состоянию, хотя **padding** для **page-content** считается попрежнему правильно.

Чтобы установить нужную высоту, в CSS нужно изменить запись на :
```
.navbar{
    --f7-subnavbar-height: 200px;
} 
```

Рабочий пример: http://f7.dev.t3b.ru/ версия F7 - 4.1.0

**Comment by shastox** [comment]
Дело не в конкретной CSS-переменной, такая же проблема, к примеру, с **--f7-subnavbar-inner-padding-left**

**Comment by nolimits4web** [comment]
Это то как работает CSS в целом - свойства указанные на элементе имеют больший приоритет чем те же свойства что указаны на родителе. В данном случае `.md` имеет больший приоритет чем `:root`, просто поменяйте `:root` на `.md`

**Comment by shastox** [comment]
> Это то как работает CSS в целом - свойства указанные на элементе имеют больший приоритет чем те же свойства что указаны на родителе. В данном случае `.md` имеет больший приоритет чем `:root`, просто поменяйте `:root` на `.md`

В этом случае сломается padding у page-content. Обновил: http://f7.dev.t3b.ru/

**Comment by nolimits4web** [comment]
Значит нужно указать и там и там `.root, .md { .... }`
