### ISSUE TITLE
Wondering if there is any way to open an external webpage under F7's page structure

### ISSUE THREAD

**Issue by JazzHunter** [framework7io/framework7#3066]
Hello Vladimir:

I have an App targeting native IOS/Android with F7-vue & cordova. I want to open an f7-page under f7's route, navbar, with the content in f7-page-content from external webpage(like www.google.com). 
--Knowing cordova-plugin-inappbrowser can open a new web-view, but don't have the left/right slide effect, nor have the unifier navbar/tabbar/statusbar control.(may cordova-plugin-themeablebrowser do this?)
--F7's link can add 'external' attribute to open an external  web-link, but the new-opened webpage doesn't have the navbar, which can't back to previous page, especially in IOS.

So wondering if there is any good idea from you to plugin an external web in f7's f7-page-content?

Thanks for you great work about F7~~!

**Comment by nolimits4web** [comment]
Check this plugin https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller
