### ISSUE TITLE
vdom - Inline SVG compatibility (case sensitive)

### ISSUE THREAD

**Issue by spoxies** [framework7io/framework7#3073]
I just learned (the hard way), that SVG elements are case-sensitive. The SVG spec says; SVG is XML and is case-sensitive (unlike HTML).

In F7 the tags are made lower-case (if included as a component), and therefore those lower cased nodes will not function. 
```
<animateTransform/>, <linearGradient/>, <feComponentTransfer/>, <feMerge/>, ...etc
```

**Example:**
```
<template>
   <div class="page" data-name="..">
      <svg xmlns=".." ..>
         <defs>
            <linearGradient ..>
               <stop offset="5%" .. />
            </linearGradient>
         </defs>
         <animateTransform fill="freeze" .. />
         <path .. />
      </svg>
   </div>
</template>
```
**_would become:_**
```
<template>
   <div class="page" data-name="..">
      <svg xmlns=".." ..>
         <defs>
            <lineargradient ..>
               <stop offset="5%" .. />
            </lineargradient>
         </defs>
         <animatetransform fill="freeze" .. />
         <path .. />
      </svg>
   </div>
</template>
```
I will be submitting a PR that checks if an element is an instance of SVGElement, before making it lower-case. It would probably slightly decrease the performance/speed. Please see if you think it would be worth it.

Many thanks for this great project there is nothing more to wish for, it is stunningly complete!!

**Comment by nolimits4web** [comment]
Fixed by #3074
