### ISSUE TITLE
access $f7 instance from simple javascript file 

### ISSUE THREAD

**Issue by alterhu2020** [framework7io/framework7#3077]
* Framework7 version: 4.000
* Vue.js version: 2.0.5
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: No 

### Describe the bug
How to access framework instance $f7 object from single javascript file ?

### To Reproduce

1. How to access the framework7 instance?  as the official Vue example mentioned that we init the framework from `App.vue` file as below:
```bash

export default {
  name: 'App',
  data () {
    return {
      // Framework7 parameters here
      f7params: {
        root: '#app',
        name: 'vrpano', // App name
        id: 'com.dd.app', // App bundle ID
        theme: 'ios', // Automatic theme detectio
        // Enable swipe panel
        panel: {
          swipe: 'left'
        },
        // Enable fast clicks
        touch: {
          fastClicks: true
        },
        clicks: {
          externalLinks: '.external'
        },
        routes: routes,
        dialog: {
          title: i18n.t('app.name'),
          buttonOk: i18n.t('app.ok'),
          buttonCancel: i18n.t('app.cancel')
        }
      },
      routesBeforeEnter (to, from, resolve, reject) {
        console.log(`current router is: ${to.path}`)
        resolve()
      }
    }
  }
}
```
2. Now i had another javascript utils , I want to access the `toast`object in the file, how I can access the $f7 instance?
### Expected behavior

Can access the $f7 instance, so I can use the toast function in the single javascript file.

### Actual Behavior
No clue where to find the instance in the javascript file .

**Comment by Overman775** [comment]
Try this on main.js

```
app = new Vue({
  el: '#app',
  template: '<app/>',
  components: {
    app: App
  },
  mounted: function() {
    this.$f7ready((f7) => {
      //make F7 global
      window.$f7 = f7;
      console.log('F7 ready');	
	  })
  }
});  
```

**Toast:**

```
function toast(text) {
  // create F7 toast message
  var toastCenterPet = window.$f7.toast.create({
    text: text,
    position: "center",
    closeTimeout: 2000
  });
  toastCenterPet.open();
}
```

**Comment by alterhu2020** [comment]
This way will create a global variable in the page, it's not a good idea, anyway, thanks for your help @Overman775
