### ISSUE TITLE
swipeBack throw error: Cannot read property 'route' of null

### ISSUE THREAD

**Issue by boboxiaodd** [framework7io/framework7#3084]
* Framework7 version: [e.g. 3.0.0]  lastest version
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser] browser
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

Live URL:
http://app.djazhong.com:9000/home  password:9527

use back icon ,is correct ,but when swipBack throw error:
```js
framework7.bundle.js:6047 Uncaught TypeError: Cannot read property 'route' of null
    at HTMLDivElement.<anonymous> (framework7.bundle.js:6047)
    at HTMLDivElement.fireCallBack (framework7.bundle.js:1224)
    at HTMLDivElement.handleEvent (framework7.bundle.js:1081)

router.pageCallback('afterOut', currentPage, $currentNavbarInner, 'current', 'next', { route: currentPage[0].f7Page.route, swipeBack: true });
```

by the way , i set `iosSwipeBack` = `false` , it don't work

**Comment by nolimits4web** [comment]
It happens because you init main view 2 times, one with `view-init` class, another one with `app.views.create`

**Comment by boboxiaodd** [comment]
my bad, Thank you
