### ISSUE TITLE
Expandable Cards 

### ISSUE THREAD

**Issue by jonyking** [framework7io/framework7#3086]
* Framework7 version: 4.1.0, 4.2.0
* Platform and Target: iOS 12.1
* Live Link or JSFiddle:-
### Describe the bug
The expandable card on iOS 12.1 has a white topbar. The Card is not fullsize

### To Reproduce
See this video please.
![ezgif com-optimize](https://user-images.githubusercontent.com/24831213/54677499-4cfaca00-4b03-11e9-9f50-f1f1e0c8d922.gif)

### Expected behavior
It shouldn't have white bar at the top. Like here:
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/24831213/54677498-4cfaca00-4b03-11e9-99e0-ea5de7f3619f.gif)

### Actual Behavior
There is a white bar between expandable card and top.

### Screenshots
See the videos pls.

**Comment by boboxiaodd** [comment]
i use 4.1.1 has same problem, but 4.1.0 is correct

**Comment by jonyking** [comment]
Same problem with 4.2
