### ISSUE TITLE
Customized ListItem, the render out  result leak of &lt;ul&gt; tag

### ISSUE THREAD

**Issue by rooyeetone** [framework7io/framework7#3089]
* Framework7 version: 4.1.0
* React.js version: 16.8.4
* Platform and Target: web

### Describe the bug

When use customized ListItem, the render out  result leak of &lt;ul&gt; tag, this cause the f7 style can not be adapted properly.

### To Reproduce
The list view:

```
<List noHairlinesMd className="user-list">
       <UserItem user={this.props.user} />)}
</List>
```

The customized ListItem:

```
export default class extends React.Component {
  render() {
    const { user } = this.props;
    return (
      <ListItem>
        {user.fullname}
      </ListItem>
    );
  }
}
```

### Expected behavior
The render out should be:

```
<div class="user-list list no-hairlines-md"><ul><li class=""><div class="item-content"><div class="item-inner">John doe</div></div></li></ul></div>
```

### Actual Behavior
But we get this:

```
<div class="user-list list no-hairlines-md"><li class=""><div class="item-content"><div class="item-inner">John doe</div></div></li></div>
```

**Comment by nolimits4web** [comment]
Use slot for this case:
```
<UserItem slot="list" ...
```

**Comment by rooyeetone** [comment]
Thanks @nolimits4web .

I tried using slot, rendering UserItem directly it's works just like expected; but when rendering UserItem through array iteration, slot seem to be ignored:

```
<List ...>
 {users.map((user) => <UserItem slot="list" key={user.username} user={user} />)}
</List>
```

**Comment by nolimits4web** [comment]
Can't replicate the issue, i have:
```
class CustomListItem extends React.Component {
  constructor() {
    super()
  }
  render() {
    return (
      <ListItem title={`Item ${this.props.title}`} />
    )
  }
}
```
and
```
<List>
  {[1,2,3,4].map(n => (
    <CustomListItem slot="list" key={n} title={n} />
  ))}
</List>
```

All renders correctly. Would be good to see live example then or JSFiddle with the issue

**Comment by rooyeetone** [comment]
Thanks for helping @nolimits4web , it was my mistake, I put an extra conditional item
in List: 

```
<List ...>
 {users.map((user) => <UserItem slot="list" key={user.username} user={user} />)}
 {users.length == 0 && <EmptyItem  slot="list" /> }
</List>
```
I re-arrange code like below, it works just fine:

```
let items;
if (users.length == 0) {
  items = <EmptyItem slot="list" />;
} else {
  items = users.map((user) => <UserItem slot="list" key={user.username} user={user} />);
}
```
and 

```
<List>
  {items}
</List>
```

It was my fault not putting entire code on the post, I'm sorry for that.
And thanks a lot.
