### ISSUE TITLE
native Vue component for calendar / date picker

### ISSUE THREAD

**Issue by jacobg** [framework7io/framework7#3099]
It doesn't look like there's a native Vue component for calendar / date picker. It requires using javascript API to create it and wire it up:
http://framework7.io/docs/calendar.html

It'd be nice to have a true Vue component for that.

Also, why is there a separate date picker implementation for f7-list-item of type="date" that looks like this?

![Screen Shot 2019-03-26 at 2 31 00 PM](https://user-images.githubusercontent.com/736985/55023764-e595bc00-4fd3-11e9-801d-5db505650ccf.png)

I think the first calendar component looks much better.

**Comment by nolimits4web** [comment]
I haven't added it because there wasn't much sense of just wrapping what we have in JS with a Vue component, as the JS realization is still more flexible. But i agree for date picker input, it could be very convenient, will add it.

> Also, why is there a separate date picker implementation for f7-list-item of type="date" that looks like this?

This is just browser's native date picker :)
