### ISSUE TITLE
[Feature Request] iOS 11 Music App Style Popup

### ISSUE THREAD

**Issue by JosephShenton** [framework7io/framework7#3100]
### Note
This is a feature request.

### Feature
Introduced in iOS 11 the Music app received this nice style of popup

Example: https://support.apple.com/library/content/dam/edam/applecare/images/en_US/applemusic/iphone7-ios11-apple-music-mini-player-up-next-animation.gif
Example: https://github.com/LeoNatan/LNPopupController

**Comment by vg0x01** [comment]
Could probably achieve this with a sheet modal but would be a beautiful addition to f7.

**Comment by boboxiaodd** [comment]
maybe like this:
https://github.com/alexaubry/BulletinBoard

**Comment by JosephShenton** [comment]
Yeah

**Comment by willmero** [comment]
Yes! This would be absolutely amazing. I have been trying to achieve this in my own apps by modifying the action grid, but needless to say, a native implementation into F7 would be stellar.

**Comment by JosephShenton** [comment]
@nolimits4web think you could implement this?

**Comment by spoxies** [comment]
Description of the similar (but more complicated) md component 'modal-bottom-sheet': 
https://material.io/design/components/sheets-bottom.html#modal-bottom-sheet

It would almost be the sheet-modal but draggable:
https://framework7.io/docs/sheet-modal.html

Behaviour: Shows content/height 1st div and ondrag/click show full content/height. Currently optimistic I'm starting on an implementation myself. If I'll produce something useful I will submit it...(don't get hopes up).

**Comment by spoxies** [comment]
What a legend ❤️ !! By the looks of it; this implementation is nicer/more uniform than mine. Many thanks!

**Comment by JosephShenton** [comment]
Awesome! ❤️
