### ISSUE TITLE
Problem with Layout and Design in my App (My First installation in Vue.JS)

### ISSUE THREAD

**Issue by ethlyseria** [framework7io/framework7#3102]
Good day,

I'm very new with Framework7 for Vue.JS,

I just copied and paste the tabs from this example from docs: https://framework7.io/vue/toolbar-tabbar.html under Tabbar Label.

But I'm facing with this kind of distort output.

![distortoutput](https://user-images.githubusercontent.com/42052787/55076023-5a015580-50cf-11e9-8a2c-ea68439cf78c.JPG)

Here's my setup.

In my main.js

```
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import './registerServiceWorker'
import Framework7 from 'framework7/framework7.esm.bundle.js'
import Framework7Vue from 'framework7-vue/framework7-vue.esm.bundle.js'

Framework7.use(Framework7Vue);

Vue.config.productionTip = false

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')
```

and in my App.vue

```
<template>
  <div id="app">
    <router-view/>
  </div>
</template>

<style>
@import '~framework7/css/framework7.bundle.min.css';
</style>
```

The versions that I'm using are
```
    ...
    "framework7": "^4.2.0",
    "framework7-vue": "^4.2.0"
    ...

```

**Comment by nolimits4web** [comment]
You have a wrong app layout and other stuff. Just use F7 Cli to start with F7+Vue http://framework7.io/cli/
