### ISSUE TITLE
remove vdom layer and use web components

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#3103]
According to f7 docs, f7 uses a small vdom implementation. Please consider to replace it by "web-components"-stack in near future. I actually use lit-elment (which is based on lit-html) which only uses native browser web-component-stack (custom elements, templates, ...)

https://lit-element.polymer-project.org/

You can see the benefits for templating here:
https://medium.com/@lucamezzalira/a-night-experimenting-with-lit-html-585a8c69892a

Actually, f7 updates the dom by itself even when using web-components by bypassing lit-html updates because of vdom-layer...

**Comment by nimo23** [comment]
And maybe f7 can remove "Template7" and mark it as deprecated in favour of javascript with template literals.

**Comment by nolimits4web** [comment]
web-components is not the replacement for VDOM, it is not a question about one or another one. These are different technologies and can be used together, and usually used together.
