### ISSUE TITLE
Add/Remove class script not working anywhere

### ISSUE THREAD

**Issue by arunraj103** [framework7io/framework7#3104]
$(document).ready(function() {
    	$(window).scroll(function(){
    if ($(this).scrollTop() > 50) {
       $('.card_new').addClass('fixed');
    } else {
       $('.card_new').removeClass('fixed');
    }
});
});

**Comment by nolimits4web** [comment]
`window` is not scrollable in Framework7. Use Forum to find the solution https://forum.framework7.io/
