### ISSUE TITLE
Stepper does not work on 3 page deep level

### ISSUE THREAD

**Issue by akadebnath** [framework7io/framework7#3105]
First of all, I could not provide jsfiddle sample as it is big and involdes multiple pages. So I am trying to describe in as much details as possible.

Version: Framework7 3.1.1
Platform: Browser and Android

I have the app structure like this.

Home > Restaurant page > Menu page

In Restarurant page, I show menus and steppers to add items to cart.

I initialize the steppers as below:
```
for(var i = 0; i < menus.length; i++) {
    $$("#menus").append('<div class="stepper stepper-small stepper-fill stepper'+ i +'"><div class="stepper-button-minus"></div><div class="stepper-input-wrap"><input class="stepperval stepperval'+ i +'" type="number" readonly value=0></div><div class="stepper-button-plus"></div></div>';
    app.stepper.create({  el: $$(".stepper" + i) });
}
```

In Restaurant page, when clicked on Menu name, the Menu page opens.

In Menu page, I have link to Restaurant page again.

Now, when I navigate as Home > Restaurant then the steppers works perfect.
But if I navigate as Home > Restaurant > Menu > Restaurant then the stepper does not work.

What I have analyzed.

In the second navigation, assignment only works when I write like this:
`$$("body #restaurantaddress").html('My restaurant');`
-- adding the body element is important here. Otherwise the html assignment does not work.

The same does not work for steppers.
If I write
`app.stepper.create({  el: $$("body .stepper" + i) });`
then no help.

Please let me know how to get this work.

Also let me know if you need any other informaton.

Screenshots for reference:
![01 home](https://user-images.githubusercontent.com/18642790/55270542-e37a7880-52c5-11e9-8e13-f66390abd0c7.png)
![02 restaurant](https://user-images.githubusercontent.com/18642790/55270543-e37a7880-52c5-11e9-8264-64c055ef9a8d.png)
![03 menu](https://user-images.githubusercontent.com/18642790/55270544-e4130f00-52c5-11e9-8dca-fb2cb2286cfd.png)

**Comment by nolimits4web** [comment]
There is something wrong with your selectors when you create Steppers, just make sure you call it on every page withing the page scope, or they all have unique selectors
