### ISSUE TITLE
Device detection library - iPhone 7

### ISSUE THREAD

**Issue by vg0x01** [framework7io/framework7#3111]
* Framework7 version: **4.1**
* Platform and Target: **iOS 12 Cordova app**

### Describe the bug
Device detection library does not recognise iPhone 7 as` device-iphone` as html class.
(iOS Simulator in Xcode)

### To Reproduce

`app.dialog.alert(document.getElementsByTagName("html")[0].classList);` in your app.js, shows missing `.device-iphone` class

### Expected behavior
`.device-iphone` class is present and able to target with css.

### Actual Behavior
Device detection library does not recognise iPhone 7 as` device-iphone`.

### Screenshots
https://imgur.com/VIfPnnp

### Additional context
Only way to differentiate iPhone X and iPhone 7 in CSS is to use `device-pixel-ratio-*`

**Comment by nolimits4web** [comment]
And it shouldn't be there http://framework7.io/docs/device.html#device-related-classes. If you really need to detect `iphone` then go with `device.iphone` util http://framework7.io/docs/device.html#methods-properties
