### ISSUE TITLE
Text inputs graphics broken in login screen on F7 v4 / Cordova / iOS / Webpack

### ISSUE THREAD

**Issue by pontigol** [framework7io/framework7#3115]
* Framework7 version: 4.2.0
* Platform and Target: iOS 12 Cordova app (with webpack)

### Describe the bug
Inputs with type "text" (possibly other types too, but not "password") are displayed with broken styling in login screen, but not elsewhere, in F7 v4. At least when creating a Cordova app with framework7-cli using webpack.

### Expected behavior
![image](https://user-images.githubusercontent.com/16635066/55545214-01344d00-56cd-11e9-9d65-7b5d4307917b.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/16635066/55545232-0beee200-56cd-11e9-9a48-f516438290cf.png)

**Comment by nolimits4web** [comment]
In your build/webpack.config.js find the line:
```
removeRedundantAttributes: true,
```
and replace it to:
```
removeRedundantAttributes: false,
```

**Comment by pontigol** [comment]
Works, thanks!
