### ISSUE TITLE
Strange panel behaviour with pushState

### ISSUE THREAD

**Issue by holtwick** [framework7io/framework7#3116]
This is probably not a bug, but the behavior is unexpected, sample at https://jsfiddle.net/perenzo/jyxkqr7b/

- Demo app with panel whos `f7-view` loads its contents via `:url`
- App has config: `view { pushState: true }`
- Try to open panel

Expected: See content of :url

Actual: Does not load correct content

Workaround: Set `:push-state="false"` for `f7-view`

Video: https://www.dropbox.com/s/8nrffu1sg76kt1u/PushState.mp4?dl=0

**Comment by nolimits4web** [comment]
Everything is correct, when push-state enabled, it ignores url from `:url` prop and take the one from browser. You don't have any routes specified for this. But anyway, push-state is supported well only for main view, and it should be enabled only on main view with `:push-state="true"` prop
