### ISSUE TITLE
Title large sporadic rendering on scroll to top - iOS 12.2, Cordova 

### ISSUE THREAD

**Issue by willmero** [framework7io/framework7#3121]
* Framework7 version: latest 4.2.2
* Platform and Target: iOS 12.2, Cordova iOS 5.0
* Live Link or JSFiddle: https://youtu.be/91z1wBgVGEM

### Describe the bug
In Cordova app, the header title large will not render until after bounce animation finishes when scrolling back to the top of the app body. 

https://youtu.be/91z1wBgVGEM

### To Reproduce
1. Deploy Framework7 kitchen sink app to Cordova app
2. Scroll half way down on the main page of the kitchen sink app
3. Forcefully scroll back up to the top 
4. Observe janky rendering

### Expected behaviour
Title renders immediately on scroll into view instead of waiting till after page bounce

### Actual Behavior
Title renders only after page bounce animation finishes when scrolling to the top of the page

### Screenshots
https://youtu.be/91z1wBgVGEM

**Comment by nolimits4web** [comment]
And you of course use WKWebView ?

**Comment by vg0x01** [comment]
I had this problem with UIWebview and Simulator. I did not have this problem changing to WKWebview and deploying to actual device.

**Comment by willmero** [comment]
Didn't realize WKWebView was needed for this! After messing around with WKWebView on Cordova 4.5.5, was able to clear up this performance issue. Thank you.
