### ISSUE TITLE
Side panel not scrollable anymore

### ISSUE THREAD

**Issue by michael-mathieu** [framework7io/framework7#3122]
Migration from 3.6.3 to 4.2.2.
Everything is fine except the side panel (that contains a list) is frozen = I can't scroll anymore.

To reproduce: add a list in the side panel with 100 items, list is scrollable with 3.6.3 not with 4.2.2.

**Comment by nolimits4web** [comment]
Make sure you have put that list inside page-content

**Comment by michael-mathieu** [comment]
Have you tested your "solution"?

On https://framework7.io/docs/panel.html for **side** panel, we have to put  in the beginning of the app root element.

If I add in the "page-content", the side panel is ignored.
