### ISSUE TITLE
Uncaught TypeError: Cannot read property 'route' of undefined in Vue.JS 3.5.5

### ISSUE THREAD

**Issue by deanilvincent** [framework7io/framework7#3128]
* Framework7 version: ^4.2.2
* Vue.js version: 3.5.5
* Platform and Target: Google Chrome

Here's the console log error

Uncaught TypeError: Cannot read property 'route' of undefined
    at Router.back (back.js?770e:577)
    at Framework7.handleClicks (clicks.js?9dd2:82)
    at eval (events-class.js?8085:79)
    at Array.forEach (<anonymous>)
    at eval (events-class.js?8085:78)
    at Array.forEach (<anonymous>)
    at Framework7.emit (events-class.js?8085:72)
    at emitAppTouchEvent (touch.js?460e:663)
    at HTMLDocument.appClick (touch.js?460e:669)
back @ back.js?770e:577
handleClicks @ clicks.js?9dd2:82
(anonymous) @ events-class.js?8085:79
(anonymous) @ events-class.js?8085:78
emit @ events-class.js?8085:72
emitAppTouchEvent @ touch.js?460e:663
appClick @ touch.js?460e:669

![hC97wmf0tK](https://user-images.githubusercontent.com/10904957/55965730-bd7fab80-5ca9-11e9-8150-0e8d857bf91f.gif)

It works at first but after the 2nd try, then it throws an error on the console log.

Here's my App.vue

```
<template>
  <div id="app">
    <f7-app :params="f7params">
      <f7-view
        tab
        main
        url="/home/"
      >
      </f7-view>
    </f7-app>
  </div>
</template>

<style>
@import url("https://fonts.googleapis.com/icon?family=Material+Icons");
</style>

<script>
import routes from "./router";
export default {
  data: () => ({
    f7params: {
      name: "My App",
      id: "com.myapp.test",
      theme: "auto",
      routes: routes
    }
  })
};
</script>
```
Here's my sample Something Page

```
<template>
  <div>
    <f7-page :page-content="false">
      <f7-navbar title="Something" back-link="Back">
        <f7-nav-right>
          <f7-link
            icon-ios="f7:reload"
            icon-aurora="f7:reload"
            icon-md="material:compare_arrows"
          ></f7-link>
        </f7-nav-right>
      </f7-navbar>
    </f7-page>
  </div>
</template>
```

Any help? I'm new with framework7io for Vue and I don't know why it shows an error even those are just from docs.

**Comment by nolimits4web** [comment]
Would be good to see some live example or JSFiddle with the issue as i can't replicate it

**Comment by deanilvincent** [comment]
Hi @nolimits4web I've created this [sample repository](https://github.com/deanilvincent/framework7vue-starter-sample). It's the same from what I did on the project that triggers the same error.

**Comment by nolimits4web** [comment]
@deanilvincent please put there some instruction on how to build it, run and replicate the issue. Even better, that already built version will be included there

**Comment by deanilvincent** [comment]
@nolimits4web There's a default readme file inside the [app folder](https://github.com/deanilvincent/framework7vue-starter-sample/tree/master/app)

**Comment by geri777** [comment]
I have the issue

**Comment by Chickyky** [comment]
> I have the same problem when I use links with parameters like
> path: '/segement/:id?'

I have same issue
how to fix it?
thanks for advice

**Comment by geri777** [comment]
Be very careful with the URLs you are building:
For example: 

`<a :href="'/somthing/' + id + '/'">` ... was wrong
`<a :href="'/somthing/' + id">` .. was ok

If you are redirecting rom the controller, instead of using the url with the parameter, use the param argument:

```
this.$f7router.navigate('/some-page/', {
  props: {
    foo: 'bar',
    bar: true,
  }
})
```

**Comment by Chickyky** [comment]
thanks @geri777 for reply
I will check all link navigate
Have you fixed it yet?

**Comment by geri777** [comment]
yes, mine is currently working.

**Comment by geri777** [comment]
Bad news, mine is working in the webbrowser. When I create a Cordova App from it and click the back button on the Androd Phone, the app immediately crashes. :-( 
I am sure it's still on the router...

**Comment by geri777** [comment]
I have now found out that the app does not crash. It is just closed to the Background. When I press the button for the active apps selection, it's there and I can open it again. Looks like if the router does not push the navigation events to the OS (however this works).

**Comment by AntonPolkanov** [comment]
I had exactly the same issue with React: the very first backward navigation from a `productPage` to a `catalogPage` worked fine, but the second crashed. It turned out, that the `catalogPage` wasn't returning a `Page`, but a `div` with the `Page`.
```
return (
    <div> // <---- WRONG
      {products && (
        <Page name="catalog">
          <Navbar title="Catalog" />
          <List>
            {products.map((product) => (
              <ListItem
                key={product.id}
                title={product.title}
                link={`/product/${product.id}/`}
              />
            ))}
          </List>
        </Page>
      )}
    </div>
  );
``` 

The `Router` expects the previous page to be an f7Page. It can be seen here: https://github.com/framework7io/framework7/blob/ce7a2dc21b29a05d6c782bd53a4155f542867d9c/src/core/modules/router/back.js#L776

So, the problem can be fixed in the following way:
```
return (
    <Page name="catalog">
      <Navbar title="Catalog" />
      <List>
        {products &&
          products.map((product) => (
            <ListItem
              key={product.id}
              title={product.title}
              link={`/product/${product.id}/`}
            />
          ))}
      </List>
    </Page>
  );
```
