### ISSUE TITLE
Framework7 v4.2.2 popover wrong position in expandable cards. 

### ISSUE THREAD

**Issue by yourioshelper** [framework7io/framework7#3132]
**Issue with the location on popovers**

When creating an expandable card with a simple list view, and making it open an popover the location becomes more and more disrupted when you scroll down. as the popover stays on the same height as when the card is opened. leaving a dark area on the entire screen.

for a simple demonstration go to:

[here](https://www.ang3lo.net/epsilon/kitchen-sink/epsilon) 

1. If on PC press F12 (Chrome) and select the view to be any small phone screen, example iPhone X.

2. Open the card named "Weekly Setup"

3. first hit the first list view, the popover is in the correct position.

4. Now scroll down to the last list view, once clicked the screen will display as an popover is opened when non are to be seen in the application.

If this issue please could be fixed in the upcoming updates, that would be awesome.

As screenshots won't display this issue as clear as the actual thing i did not add any.

**Comment by nolimits4web** [comment]
Remove `page` class from `card-content` element, it shouldn't be there
