### ISSUE TITLE
Use setColorTheme('black') and setBarsStyle('empty / fill')  when switching between multiple pages is a bit of a problem.

### ISSUE THREAD

**Issue by idreamin** [framework7io/framework7#3134]
![test](https://user-images.githubusercontent.com/38604167/56153534-f93bad80-5fe8-11e9-957d-1c4f2df6374c.gif)

The first time use setColorTheme('black') and setBarsStyle('fill') , when the page is scrolling，use setColorTheme('black') and setBarsStyle('empty')  and when the page scrolls to the top，use setColorTheme('black') and setBarsStyle('fill'). when switching between multiple pages It seems to have a problem ! 

Thank you very much !

**Comment by nolimits4web** [comment]
This is custom methods, so it is your custom logic, not related to F7 core functionality
