### ISSUE TITLE
ColorPicker bars bug

### ISSUE THREAD

**Issue by Overman775** [framework7io/framework7#3137]
Привет!
Немного протестировал этот замечательный ColorPicker и нашёл баг, при выборе цвета через RGB bars некорректно отрабатывает колонка при перетаскивании, c эмуляцией touch всё работает корректно.

**Повторение:**
Chrome dev tools --> desktom или mobile (no touch) --> RGB BARS --> сменить цвет перетаскиванием

**Видео:**

![bug2](https://user-images.githubusercontent.com/47769319/56280323-618eaa00-6123-11e9-8a95-17e3e7aa6596.gif)

**Comment by nolimits4web** [comment]
При переключении на no-touch перезагружал браузер? Это надо делать

**Comment by Overman775** [comment]
Конечно перезагружал... и вот ещё обнаружил закономерность, когда быстро нажимаешь и тащишь то всё срабатывает как надо, а вот если подождал, например секунду, то перетаскивание отваливается. Подозреваю что дело в fastclick

**Comment by nolimits4web** [comment]
А с вертикальным range Slider такой же баг? Тут просто используется он

**Comment by Overman775** [comment]
Аналогичный глюк. С "разбегу" цепляет скрол, при небольшой задержке скрол не таскается 
![range](https://user-images.githubusercontent.com/47769319/56282918-bdf4c800-6129-11e9-9e06-60aee64dc5d9.gif)

**Comment by shastox** [comment]
Подтверждаю, есть такой баг с Color Picker при mobile (no touch). Windows 7, Chrome.

> А с вертикальным range Slider такой же баг? Тут просто используется он

Да, воспроизводится.
