### ISSUE TITLE
F7 Swiper virtual slides lose content after few swipes in React

### ISSUE THREAD

**Issue by nehloo** [framework7io/framework7#3138]
* Framework7 version: 4.3.0
* React.js version: 16.8.1
* JSFiddle test: https://jsfiddle.net/vyqwLtcm/

### Describe the bug
F7 Swiper virtual slides lose content after few swipes in React.

### To reproduce
Swipe left through the virtual slides in the JSFiddle: https://jsfiddle.net/vyqwLtcm/

### Expected behavior
Should be able to slide through 600 virtual slides, and see a text/title on each slide: Slide 1, Slide 2, ... Slide 600.

### Actual behavior
Swiper loses the text/title somewhere between Slides 3 and 4 (possibly while it updates "virtualData" with "renderExternal"), and it doesn't display Slide 3 at all (try to slowly swipe left from Slide 2, and you'll see how Slide 3 is being skipped and it jumps straight to Slide 4). Then, no other slides are displaying the text/title beyond Slide 5.

### Log
This log still shows that "renderExternal" actually compiles the correct slides and their content:

console.log(this.state.virtualData.slides);
* ["Slide 1", "Slide 2"]
* ["Slide 1", "Slide 2", "Slide 3"]
* ["Slide 2", "Slide 3", "Slide 4"]
* ["Slide 3", "Slide 4", "Slide 5"]
* ...
* ["Slide 21", "Slide 22", "Slide 23"]
* ["Slide 22", "Slide 23", "Slide 24"]
* ...
* ["Slide 598", "Slide 599", "Slide 600"]

**Comment by nolimits4web** [comment]
You need to correctly set `left` property on slide like in example https://jsfiddle.net/yn51jhwz/

**Comment by nehloo** [comment]
Thanks!... Can I reopen with a related issue? It's about "slidesPerView:3" displaying only one slide at first, then correcting to display 3 slides per view after the first swipe left: https://jsfiddle.net/bu0xrm7t/
