### ISSUE TITLE
Expandable Cards top transform incorrect if page is scrolled when inside swiper slider

### ISSUE THREAD

**Issue by willmero** [framework7io/framework7#3139]
* Framework7 version: 4.3.0
* Platform and Target: iOS 12.2
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/):

JSFiddle: https://jsfiddle.net/amngeqy8/2/show
Youtube Demo: https://www.youtube.com/watch?v=qM4w28FipAE

### Describe the bug
There seems to be an issue with offset of an expandable card relative to the top of the screen/web browser when an expandable card is placed within a swiper slider on iOS 12.2.x

### To Reproduce
1. Visit the JS Fiddle link in safari on an iOS 12.2.x device 
https://jsfiddle.net/amngeqy8/2/show 
2. Scroll down so that the expandable cards are almost out of view
3. Click on one of the cards, and observe that it opens properly
4. Close the expandable card by swiping down on the card to close it
5. Re-click on the expandable card, and observe the weird offset from the top

### Expected behavior
Expandable card will properly scale to the appropriate offset from the top of the page

### Actual Behavior
A strange translation offset occurs during the second attempt of opening an expandable card

### Screenshots
![IMG_1584](https://user-images.githubusercontent.com/6343859/56318699-b33c3200-612d-11e9-8a79-1e78d56676cf.PNG)

**Comment by nolimits4web** [comment]
Well, iOS 12 becomes more and more annoying with such issues :) Fixed now, will land in next update

**Comment by willmero** [comment]
@nolimits4web you are my favourite person in the world 🙏🏼 If only Apple didn't just always change things like this, that would be just swell haha.
