### ISSUE TITLE
issues with links in Framework7

### ISSUE THREAD

**Issue by davidfdelgado** [framework7io/framework7#3142]
Hello People, 

Framework7 Core (4.2.2)
I have a problem with my Project. I don't really want to declare every link in the router section of the .js-file.
When i set the ".link" class in the a-tag it will be completely ignored and does not load the page. I tried to do it like in the documentation but nothing ist working. 

Here ist the link to my Project: http://dev-shahin.entwickler.online/homepage . 

Maybe someone has an idea what is getting wrong?

**Comment by nolimits4web** [comment]
> I don't really want to declare every link in the router section of the .js-file.

Then it won't work. It is a requirement to declare all available routes
