### ISSUE TITLE
pageInit firing before render

### ISSUE THREAD

**Issue by xpario** [framework7io/framework7#3144]
v4.3 (also existed in v4.2). the pageInit page event fires *before* the page is fully rendered. This makes it impossible to retrieve width/height properties of elements on the page via javascript/jquery (sample below). Either pageInit should fire after page is rendered or create a pageRendered page event.

Example of issue. Create a DIV on the page that has a width of 100% (via CSS).  Call from pageInit:

$("#mydiv").outerWidth()

The above returns “0” when called in the pageInit event. If you call the same code once the page is rendered (from a click on the page), it correctly returns the DIV width (in my case the value is 360).

**Comment by nolimits4web** [comment]
Hi! This can't actually happen, issue probably is in something else. Would be good to see JSFiddle with the issue or live example

**Comment by xpario** [comment]
I would have to build a whole f7 project that utilizes the router to demonstrate on jsFiddle and my code is being built in PhoneGap, so its difficult to share. Here are the steps to reproduce:

1) Create a DIV in a Router template
2) Set the DIV (with id="mydiv") width to 100% via CSS

<div id="mydiv" style="width=100%;" onclick="alert($("#mydiv").outerWidth());"></div>

3) navigate to the template us f7 Router API
4) in the pageInit Event execute:

alert($("#mydiv").outerWidth());

5) Above will return "0"
6) Click on the div, alert will display the width of the DIV in pixels (in my case it shows 360)

**Comment by nolimits4web** [comment]
Everything works correctly https://jsfiddle.net/uvpn5bz7/

**Comment by nolimits4web** [comment]
> I would have to build a whole f7 project that utilizes the router to demonstrate on jsFiddle

It is easy to create JSFiddle, and when you created issue you may have seen there is already F7 JSFiddle template

**Comment by nolimits4web** [comment]
I can suggest that you are referencing wrong element, you may have few `#mydiv` elements

**Comment by xpario** [comment]
I found my issue. I had the parent DIV set to display:none and was checking width before displaying the DIV. the width returns "0" if a parent DIV is display:none. I moved the outerWidth() command to after removing the display:none and it returned the correct value.
