### ISSUE TITLE
Router.navigate not working after Build [APK] [ANDROID]

### ISSUE THREAD

**Issue by AnasProgrammer2** [framework7io/framework7#3145]
Hello . **thanks for everything you do to make a development is easy .**

i have a complete project (by Framework7 V4) is working fine in chrome (pc and phone )
but the problem after i build my project to android [APK]
my problem is  mainView.router.navigate('/about'); , is not working and that's any error message 
I am use a  : 
1-  Framework v4
2- create project by Framework7 CLI Create with WebPack
3- build by use " npm run build-cordova-dev"

i am try :
1 - install cordova-plugin-whitelist
2- change my commend formart 
  - mainView.router.navigate('/about');
  -mainView.router.navigate({name:'about'});
--i do everything but is not working too
here simple of my project file : 

**router.js** 
```

import HomePage from '../pages/home.f7.html';
import upload from '../pages/upload.f7.html';
import imgprocess from '../pages/imgprocess.f7.html';
import about from '../pages/about.f7.html';

import NotFoundPage from '../pages/404.f7.html';

var routes = [
  {
    path: '/',
    component: HomePage,
	
  },
  { name:'upload',
    path: '/upload/',
    component: upload,
  },
   { name:'imgprocess',
    path: '/imgprocess/',
    component: imgprocess,
  },
    { name:'about',
    path: '/about/',
    component: about,

  }, 
 ,
  {
    path: '(.*)',
    component: NotFoundPage,
  },
];
export default routes;

```
**index.js** 
```

  <meta http-equiv="Content-Security-Policy" content="default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui, viewport-fit=cover">

  <meta name="theme-color" content="#007aff">
  <meta name="format-detection" content="telephone=no">
  <meta name="msapplication-tap-highlight" content="no">
  <title>Colourise</title>
  
  
 
```

my code in **app.js** 
```
  $$("#upload3").on('click',function(){

 var mainView = app.view.main;
   mainView.router.navigate({ name: 'about' });
    });
```
`<p><a  href="#" id="upload3" name="upload3" class="button button-raised button-fill">go</a></p>`

i try and try everything .  i think the problem with Framework7 Core

**Comment by nolimits4web** [comment]
https://forum.framework7.io/t/my-router-navigate-is-not-solved-maybe-the-problem-in-f7-core/6714
