### ISSUE TITLE
Would you consider the ”Translucent Bars “ in future update?

### ISSUE THREAD

**Issue by JazzHunter** [framework7io/framework7#3151]
Hello~
Grateful for your amazing work on F7.
With using F7-vue V4.3 targeting native App on IOS/Android, I noticed that the status bar will be controlled by F7-statusbar ( which is a fixed block dom), or by Mobile's OS, nether of which **I can put my page-content to the top edge of physical device.**
I have searched F7's docs, the css variables about status is pretty little....

So, would you consider the feature of "Translucent Bars " in future's update version? Where the page-content of f7-page can be set at the top edge of physical device.
In my opinion,  the adjustment may be followings:
1. Statusbar bgcolor should add 'transparent' attribute. (with help of cordova-plugin-statusbar)
2. Navbar, as well as notificaltions should have extra padding height ( the same height as original statsbar, also with safe-area considered)
3. Re-calculate current page's height
4. ...

Thanks again for your work~

**Comment by JosephShenton** [comment]
+1

**Comment by JazzHunter** [comment]
Thanks guys~

**Comment by BananaAcid** [comment]
Do you guys know of a current work around? I do not seem to get this fixed :/

**Comment by nolimits4web** [comment]
Released in v5
