### ISSUE TITLE
Swipeout - swipeout:deleted unbinds all events for the other list items with the same class.

### ISSUE THREAD

**Issue by TravisVincent** [framework7io/framework7#3152]
* Framework7 version: 3.4.2
* Platform and Target: iOS 8+, Android 4.4+ [phonegap]

### Describe the bug
When making a list with HTML and giving all `<li>` the same class used for a delete callback with Swipeout, the callback will only be used once.
I searched in framework7.js and found that on calling the Swipeout:delete function the element is removed with the remove() function.
This also unbinds the event used as a callback for all other list items.

### To Reproduce
1. Make a list in html. e.g. `<ul><li></li></ul>`
2. Add at least 2 items. 
3. Add the class "swipeout" and "my-callback-event" to each `<li>`
4. Add the following code in javascript:
`
 $$(".my-callback-event").on("swipeout:deleted", function (e) {
    console.log(this);
});`
5. The second time the event is supposed to be called, nothing happens.

### Expected behavior
Each list item responds to the callback event.

### Actual Behavior
Only the first time the event is called it will work.

### Screenshots
![bug](https://user-images.githubusercontent.com/42176397/56661815-d2ddd800-66a2-11e9-8487-3c9e84a22526.PNG)

**Comment by nolimits4web** [comment]
Please provide live example or JSFiddle. Removing element has nothing to do with events unbinding, from what i see everything works correctly

**Comment by TravisVincent** [comment]
I was busy fixing this, and i found out it was a whole different issue.
Sorry for the trouble.

PS: It indeed works well :)
