### ISSUE TITLE
hides navbar when displaying the keyboard

### ISSUE THREAD

**Issue by tmwebs** [framework7io/framework7#3156]
* Framework7 version: 4.3.0
* Platform and Target: iOS 12 Cordova app

### Describe the bug
In version 2.0 I had it fixed, but I have updated to version 4.3 and again I have the problem with iOS

### Expected behavior
the navbar and statusbar should remain fixed when opening the keyboard and not disappear.

### Screenshots

![Simulator Screen Shot - iPhone Xʀ - 2019-04-26 at 12 01 09](https://user-images.githubusercontent.com/12540076/56801487-d5187180-681d-11e9-84f6-609671870c96.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-04-26 at 12 06 59](https://user-images.githubusercontent.com/12540076/56801488-d5187180-681d-11e9-9c30-daa4814b8506.png)

### Additional data
I'm using cordova-plugin-keyboard
my configuration is:

> statusbar: {
    iosOverlaysWebView: true,
    iosTextColor: 'white',
    overlay: true,
    scrollTopOnClick: true,
    androidOverlaysWebView: true,
    androidTextColor: 'white',
    androidBackgroundColor: '#00b34e'
  },
    input: {
    scrollIntoViewOnFocus: true,
    scrollIntoViewCentered: true,
  },

Thanks you.

**Comment by nolimits4web** [comment]
It is not F7 issue. Search on forum, there are plenty of solutions http://forum.framework7.io/

**Comment by tmwebs** [comment]
i have `Keyboard.shrinkView(true); ` but this is the result
![Captura de pantalla 2019-04-26 a las 12 47 43](https://user-images.githubusercontent.com/12540076/56802883-82d94f80-6821-11e9-9a61-01c80ef7b3f9.png)

**Comment by tmwebs** [comment]
I have solved it, the problem is that Keyboard.shrinkView(true) fails in iOS 12, I found the solution in this page:

https://github.com/cjpearson/cordova-plugin-keyboard/issues/77

modifying the CDVKeyboard.m file of the plugin cordova-plugin-keyboard for this:

https://gist.github.com/mattio/ba5d77474e725463bc75cfbf1dba0cca
