### ISSUE TITLE
How to use Timeline component with Vue?

### ISSUE THREAD

**Issue by caiotarifa** [framework7io/framework7#3158]
**Is your feature request related to a problem? Please describe.**

Not exactly, but I didn't find the `Timeline` component in the Vue documentation.

[https://framework7.io/docs/timeline.html](https://framework7.io/docs/timeline.html)

**Describe the solution you'd like**

Use `<Timeline />`, `<TimelineItem />`, `<TimelineMonth />` and `<TimelineYear />` with Vue library.

**Describe alternatives you've considered**

Use handmade markup or create my own custom component.

**Comment by Overman775** [comment]
Timeline not released in Vue components, use as simple HTML
