### ISSUE TITLE
Implement FastClick fork due to new iOS 11.3 behavior

### ISSUE THREAD

**Issue by Twisterking** [framework7io/framework7#3159]
Hi there,
So seems like something changed in `iOS 11.3`, which requires a `fastclick` fork to keep working correctly.

Link: https://stackoverflow.com/questions/49322811/cordova-adds-350ms-delay-on-click-events-in-ios
github Link: https://github.com/lasselaakkonen/fastclick/tree/fix-ios-11-3-event-timestamps

Maybe this has happened already, if not please implement this fork as it seems to be needed on iOS! Thanks!

**Comment by nolimits4web** [comment]
Framework7 uses own fast clicks implementation, this is not needed
