### ISSUE TITLE
tab on tabs with page-content

### ISSUE THREAD

**Issue by Overman775** [framework7io/framework7#3171]
Привет! Столкнулся с такой проблемой, возможно баг или просто мой косяк...

Есть routed tabs в одном из которых есть ещё animated tabs, к animated tabs почему то не цепляется page-content прокрутка. Если цеплять page-content к родителю animated tabs(первый routed tabs) то прокрутка работает, но так как animated tabs разной длины то соответственно прокрутка идёт по наибольшей длине, этот вариант не подходит.

**Пример:**
https://jsfiddle.net/Silver775/j0Ld6e9n/

**Comment by nolimits4web** [comment]
Нужно просто зафиксировать высоту на нужную в дочерних page-content https://jsfiddle.net/sz73w1rq/
