### ISSUE TITLE
wkwebview height error

### ISSUE THREAD

**Issue by tmwebs** [framework7io/framework7#3178]
* Framework7 version: 4.3.1
* Platform and Target: iOS 12 Cordova app

### Describe the bug
when I install the plugin cordova-plugin-wkwebview-engine, there are two problems:
- the view appears bad to me, as shown in the image, en iPhone X, Xs y Xr.
- navigation does not work.

Can you help me?

![Simulator Screen Shot - iPhone Xʀ - 2019-05-16 at 12 45 30](https://user-images.githubusercontent.com/12540076/57848320-e2030200-77d8-11e9-9bdb-6923f041942d.png)

**Comment by nolimits4web** [comment]
It is recommended to use F7 CLI to setup a project, these issues are solved there

**Comment by tmwebs** [comment]
the navigation I solved it with cordova-plugin-wkwebview-file-xhr but it still does badly the height, however, when closing the keyboard, the height gets well

I have tried F7 CLI, but it doesn't work for me

**Comment by tmwebs** [comment]
After searching a lot, I found a solution at https://github.com/apache/cordova-plugin-wkwebview-engine/issues/53

I added in CDVInAppBrowser.m the following code:

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
if (@available(iOS 11.0, *))
{
[self.webView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
};
#endif

I hope it can help
