### ISSUE TITLE
Can't access to cordova plugin

### ISSUE THREAD

**Issue by khudia** [framework7io/framework7#3185]
I just added cordova-plugin-nativestorage to app and then tried to access to it in $f7ready method by calling console.warn(NativeStorage) = got error  ReferenceError: NativeStorage is not defined. Then i tried to add cordova-plugin-file and got error ReferenceError: cordova is not defined.  All this plugins support browser platform.... And with plugin cordova-plugin-camera is the same issue - i can't acces to it by  "navigator.camera"

**Comment by praveenmujawdiya** [comment]
Add <script src="cordova.js"></script>

**Comment by khudia** [comment]
` <% if (process.env.TARGET === 'cordova') { %>
  <script src="cordova.js"></script>
  <% } %>
`
this is what in index.html and if i remove "if" statement and leave as you so -- nothing happens. just the same message: ReferenceError: NativeStorage is not defined
