### ISSUE TITLE
swipeot repaint

### ISSUE THREAD

**Issue by Overman775** [framework7io/framework7#3188]
Привет! При анализе производительности обнаружил что компонент Swipeout перерисовывается при перелистывании табов, возможно фича такая,  кто знает ))

**Демо:**
Отослал видео сообщением на форуме

**Решения:** 
`.swipeout-content{
    transform: translate3d(0px, 0px, 0px);
    will-change: transform;
}`
`.swipeout-content{
    transform: translate3d(0px, 0px, 0px);
}`
`.swipeout-content{
    will-change: transform;
}`

**Comment by nolimits4web** [comment]
Привет! Я точно не помню, но кажется был баг когда это свойство было, то при большом количестве элементов на странице, было сильное падение производительности

**Comment by nolimits4web** [comment]
https://github.com/framework7io/framework7/issues/273

**Comment by Overman775** [comment]
Наверно тогда не стоит трогать раз работает, было интересно твоё мнение 😃 
Теоретически могло падать из за нехватки оперативной памяти так как will-change "подготавливает" элементы к последующему рендерингу
