### ISSUE TITLE
npm run build-cordova-android-prod fails because of UglifyJS

### ISSUE THREAD

**Issue by patchlog** [framework7io/framework7#3190]
* Framework7 version: 4.2
* Platform and Target: Android production

### Describe the bug
when running npm run build-cordova-android-prod the build process fails with the following error:
ERROR in js/app.js from UglifyJs
Unexpected token: name «t7ctx», expected: punc «;» [./node_modules/template7/dist/template7.esm.js:16,4][js/app.js:106,4]

The same thing happens for npm run build-cordova-ios-prod

The solution is to use the terser-webpack-plugin instead of uglifyjs-webpack-plugin

**Comment by nolimits4web** [comment]
Latest CLI already uses Terser instead, you can check what is changed here https://github.com/framework7io/framework7-cli/commit/e67868c6dcb4794c55b5c7c3cc054b9f1cf9ee70
