### ISSUE TITLE
issue with Range when using f7 with react, router and AppBar

### ISSUE THREAD

**Issue by orhan-swe** [framework7io/framework7#3193]
* Framework7 version: 4.4.0
* React.js version: 16.7.0
* Platform and Target: Chrome
* Live Link or JSFiddle: https://lucid-cori-c77ce7.netlify.com/

### Describe the bug
Range is broken. Values cumming from range are NaN, and is showing wrong values
Happens only when using Range with Appbar, Views and Router, and Range is not in the main view.

### To Reproduce
1. Go to https://lucid-cori-c77ce7.netlify.com/
2. Click on AppBar lightning icon
3. You can see broken range both for the dual range and for the normal range

### Expected behavior
Range should show values 30 to 60 but instead everything is at 0
Source code:
https://github.com/orhan-swe/f7_router_react_appbar_range_issue/blob/master/src/scenes/SearchPage.js

and the whole sample app source:
https://github.com/orhan-swe/f7_router_react_appbar_range_issue

### Actual Behavior
Range should show between 30 and 60

### Screenshots
See source code and https://lucid-cori-c77ce7.netlify.com/

### Additional context
If the SearchPage is main page that is shown first the error does not happen.

**Comment by orhan-swe** [comment]
Views are created in:
https://github.com/orhan-swe/f7_router_react_appbar_range_issue/blob/master/src/root/AppViewLoader.js

**Comment by nolimits4web** [comment]
Issue is because you just setting `tab-active` class on view. It is not enough to switch the tab, it also need to trigger events that can tell to Range Slider that it became visible and needs to recalc its styles. Switch tabs with built-in logic using `tab-link` class on tab buttons, like in examples here https://framework7.io/react/tabs.html

**Comment by orhan-swe** [comment]
@nolimits4web thanks for the info, I switched to routed tabs instead of views for this and the issue can not be seen anymore
