### ISSUE TITLE
No way to combine virtual lists with messages.

### ISSUE THREAD

**Issue by burtontanner** [framework7io/framework7#3194]
**Is your feature request related to a problem? Please describe.**
if i render too many messages, it kills the performance in the app.

**Describe the solution you'd like**
Add a prop to the messages component that will virtuaize the list (only render what is visible).

**Describe alternatives you've considered**
write something my self.

**Comment by ezbank** [comment]
like

**Comment by andrewvmail** [comment]
Agree this will be a good feature to have
