### ISSUE TITLE
Маленькая оптимизиция метода show() для Tooltip

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3195]
Когда мы создаем tooltip, то мы указываем targetEl. При показе, т.е. методе show(), мы должны снова передавать этот targetEl. 

Предложение: входящий параметр метода show() сделать опциональным, ведь он уже указан при создании tooltip.

Пример кода, где показано дублирование: https://github.com/framework7io/framework7/issues/2681#issuecomment-421923658

**Comment by nolimits4web** [comment]
> При показе, т.е. методе show(), мы должны снова передавать этот targetEl.

Это нужно делать только если нужно показать tooltip над другим target. А так, так и работает, если при вызове show() не передать элемент, то будет использован тот, который был указан при создании

**Comment by shastox** [comment]
> А так, так и работает, если при вызове show() не передать элемент, то будет использован тот, который был указан при создании

https://github.com/framework7io/framework7/blob/master/src/core/components/tooltip/tooltip.js#L18 тут вроде как раз наоборот - задавать обязательно.

**Comment by nolimits4web** [comment]
Это общий метод приложения, тут конечно нужно указать иначе не понятно какой tooltip показывать.

**Comment by iahu** [comment]
It's same as my case. Though I have set a `target` property to `Popover` component, but the targetEl aways be the button, which trigger the popover opened. So that the popover position aways be 'top'.

Aways use the `target` props should be right, as my case. Use the `open` method with a target argument is complicated.
