### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by regchiu** [framework7io/framework7#3198]
* Framework7 version: 4.4.0
* Vue.js version: 2.6.10
* Platform and Target: Chrome browser
* Live Link or JSFiddle: https://jsfiddle.net/L89qcrp7/

### Describe the bug

I use single file components.

I have a component.

#### time-picker.vue
```vue
<template>
  <div class="block block-strong no-padding no-margin margin-bottom">
    <div id="time-picker-container"></div>
  </div>
</template>
<script>
export default {
  mounted() {
    const picker = this.$f7.picker.create({
      containerEl: '#time-picker-container',
      toolbar: false,
      rotateEffect: true,
      cols: [
        {
          values: ['AM', 'PM'],
        },
        {
          values: (() => {
            const arr = []

            for (let i = 1; i <= 12; i++) {
              arr.push(i)
            }

            return arr
          })(),
        },
        {
          values: (function() {
            const arr = []
            for (var i = 0; i <= 59; i++) {
              arr.push(i < 10 ? '0' + i : i)
            }
            return arr
          })(),
        },
      ],
    })
  },
}
</script>
```

I use it.

#### schedule.vue
```vue
<template>
  <f7-page name="schedule">
    <f7-navbar title="Setting">
      <f7-nav-right>
        <f7-link icon-ios="f7:add" icon-md="material:add" popup-open=".new-schedule"></f7-link>
      </f7-nav-right>
    </f7-navbar>

    <f7-popup class="new-schedule">
      <f7-page>
        <f7-navbar>
          <f7-nav-left>
            <f7-link popup-close>Cancel</f7-link>
          </f7-nav-left>
          <f7-nav-title>Add Schedule</f7-nav-title>
          <f7-nav-right>
            <f7-link popup-close>Save</f7-link>
          </f7-nav-right>
        </f7-navbar>
        <time-picker/>
      </f7-page>
    </f7-popup>
  </f7-page>
</template>
<script>
import TimePicker from '../components/time-picker'
export default {
  components: {
    'time-picker': TimePicker,
  },
}
</script>
```

### To Reproduce
1. Go to 'schedule' page.
2. Click on 'add' button.
3. See the picker has problem.
4. Click on the picker then see the error.
```sh
Uncaught TypeError: Cannot read property 'style' of undefined
    at Dom7.transform (dom7.module.js:339)
    at Object.updateColItems [as updateItems] (picker-column.js:121)
    at Framework7.handleTouchEnd (picker-column.js:259)
    at eval (events-class.js:121)
    at Array.forEach (<anonymous>)
    at eval (events-class.js:120)
    at Array.forEach (<anonymous>)
    at Framework7.emit (events-class.js:114)
    at emitAppTouchEvent (touch.js:767)
    at HTMLDocument.appTouchEndPassive (touch.js:798)
```

I am not sure if this is a bug, maybe I am doing something wrong.

Thanks.

### Expected behavior

The picker component should render correctly without having to adjust the screen size to view the content.

### Actual Behavior

The picker component not rendered correctly.

### Screenshots
1. Click on add button to open the popup window .
![未命名1](https://user-images.githubusercontent.com/25433868/58791313-8c29b900-8624-11e9-813d-af13b6bea161.png)

2. When I click on the picker,  will be see the error.
![未命名2](https://user-images.githubusercontent.com/25433868/58790136-52f04980-8622-11e9-9ed0-129b7db4a21d.png)
3. Press F12 can see the picker content.
![未命名1](https://user-images.githubusercontent.com/25433868/58790178-68657380-8622-11e9-8abc-d2bba83d2eae.png)

**Comment by nolimits4web** [comment]
> Sorry, I can't implement it on JSFiddle.

Why? Start from forking this fiddle with Vue and F7 https://jsfiddle.net/nolimits4web/jcwzqovz/

**Comment by regchiu** [comment]
Finally, I solved this problem by opening a new page instead of opening popup.

**Comment by regchiu** [comment]
https://jsfiddle.net/hq5Leu2k/

**Comment by regchiu** [comment]
I can't reproduce it on JSFiddle.  😢 
There is no error msg. 
https://jsfiddle.net/zurtjhmL/1/
