### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'eventsParent.emit.apply') (framework7.bundle.js:3108)

### ISSUE THREAD

**Issue by YaroslavErmolaev** [framework7io/framework7#3201]
* Framework7 version: 4.4.3 (and 4.4.2)
* Platform and Target: iOS 12 Cordova

### Describe the bug
If use "var myEvents = new Framework7.Events();"
Error in Safari Developer Console:
TypeError: undefined is not an object (evaluating 'eventsParent.emit.apply') (framework7.bundle.js:3108)

In previous version all works fine.

**Comment by nolimits4web** [comment]
Update to 4.4.3

**Comment by YaroslavErmolaev** [comment]
Извиняюсь, не там обновил и поэтому не проверил версию 4.4.3. Все работает! Спасибо!
