### ISSUE TITLE
Проблема в отрисовке контента при анимации открытия страницы в iOS-теме

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3205]
**Задача**: показать с сервера относительно много данных на странице. 

**Решение**:

```
pageInit : function () {
//Загружаем контент и показываем его через $setState()
}
```

Но если запрос пройдет **быстро**, то _анимация страницы_ **совпадет** по времени с _добавлением данных в DOM_ и будут заметные сильные тормоза в отрисовке. В MD-другая анимация, там нет проблем.

Архитектурных решения два: 
1) сначала полностью сформировать страницу, а потом на нее переходить.
2) данные с сервера **отображать** строго после завершения анимации (загружать по прежнему можно в pageInit)

Пока я делаю так: 

```
pageInit : function () {
    setTimeout(function () {
       //Загрузка контента, которая точно не пересечется с анимацией страницы
    }, 300);
}
```

**Предлагаю**: или описать этот момент в документации или как-то "подготовить почву" для работы с этой особенностью.

**Comment by nolimits4web** [comment]
Для этого есть pageAfterIn событие, таймауты использовать нельзя

**Comment by shastox** [comment]
> Для этого есть pageAfterIn событие, таймауты использовать нельзя

Это событие не подходит по двум причинам:

1. (важная, ее нельзя пренебречь) **page1** (загрузили данные по pageAfterIn) > **page2** (возвращаемся обратно) > **page1** в этом случае событие **pageAfterIn** сработает заново и снова загрузим данные на **page1**
2. Получение данных бывает быстрым и мы теряем время на анимацию, лучше начать загрузку данных в **pageInit**, а показывать их уже потом.

Все можно реализовать самостоятельно, я скорее к тому, что в документации везде указывается pageInit, что в реальных условиях не подходит.

**Comment by nolimits4web** [comment]
Укажу в документации
