### ISSUE TITLE
active-state class being added to every element

### ISSUE THREAD

**Issue by FishSaidNo** [framework7io/framework7#3210]
* Framework7 version: 4.4.3
### Describe the bug
Hello!
I've found that the `.active-state` class is being applied to every element, not just those defined in `app.params.touch.activeStateElements`.

Looking at [line 39 of touch.js](https://github.com/framework7io/framework7/blob/master/src/core/modules/touch/touch.js#L39) the `findActivableElement` function:

```js
  function findActivableElement(el) {
    const target = $(el);
    const parents = target.parents(params.activeStateElements);
    let activable;
    if (target.is(params.activeStateElements)) {
      activable = target;
    }
    if (parents.length > 0) {
      activable = activable ? activable.add(parents) : parents;
    }
    if (activable && activable.length > 1) {
      const newActivable = [];
      let preventPropagation;
      for (let i = 0; i < activable.length; i += 1) {
        if (!preventPropagation) {
          newActivable.push(activable[i]);
          if (activable.eq(i).hasClass('prevent-active-state-propagation')
            || activable.eq(i).hasClass('no-active-state-propagation')
          ) {
            preventPropagation = true;
          }
        }
      }
      activable = $(newActivable);
    }
    return activable || target;
  }
```

If neither the target element nor any of its parents are activable elements, the function returns the target. This seems to be a bug. Or is this expected behaviour?

I've been debugging an intermittent issue with delegated click events not firing in certain scenarios, this seems to be the culprit.

Changing the function to `return activable || $();` fixes the issue & doesn't seem to have any adverse side-effects.

Cheers,
Morgan

**Comment by FishSaidNo** [comment]
Also, a minor issue with the docs.
The default `touch.activeStateElements` at https://framework7.io/docs/app.html#app-parameters are listed as `a, button, label, span, .actions-button`

For me in v4.4.3 the defaults are `a, button, label, span, .actions-button, .stepper-button, .stepper-button-plus, .stepper-button-minus, .card-expandable, .menu-item, .link, .item-link`

**Comment by nolimits4web** [comment]
> If neither the target element nor any of its parents are activable elements, the function returns the target. This seems to be a bug. Or is this expected behaviour?

This is expected behavior, not a bug.

Docs are fixed
