### ISSUE TITLE
iOS transition .page-next shows up before .router-transition starts producing a Flash Of Unwanted Content

### ISSUE THREAD

**Issue by vdcrea** [framework7io/framework7#3222]
* Framework7 version: 4.4.3
* Vue.js version: 2.6.10
* Platform and Target: Web browser

### Describe the bug
iOS transition `.page-next shows` up before `.router-transition` is applied to router producing a Flash Of Unwanted Content

### To Reproduce
1. Click anything to navigate from a page to another
2. See FOUC

### Expected behavior
.page-next should be visible during transition only, not before it starts

### Actual Behavior
.page-next content flashes just before transition starts

### Screenshots
http://yesponge.com/F7VueiOSFOUC.mp4

### Additional context
The following scss seems to fix the issue:

```
.view-main {
  .page-next {
    display: none;
  }
  &.router-transition {
    .page-next {
      display: block;
    }
  }
} 
```

**Comment by nolimits4web** [comment]
This shouldn't happen as page-next has correct position when it is added to DOM https://github.com/framework7io/framework7/blob/master/src/core/components/page/page-ios.less#L15

Make sure you are not modifying page classes on page init or before animation begins

**Comment by nolimits4web** [comment]
And i guess you won't see such issues in Kitchen sink or default templates

**Comment by vdcrea** [comment]
Your are right, given the less it cannot happen.

It's maybe related to a weird thing I have with the router on http://yesponge.com/  (investigating now: using Chrome everything is fine, but with Mobile Safari the pages bump after each transition as if it happen twice)

Initial url of the main view is conditional new user go to '/welcome/', others to '/', there is probably an issue with that, i will try with one route only and redirect after.

Closing for now, until I figure out what is happening.
