### ISSUE TITLE
4.4.5: $f7.views.current is undefined, (and some types are broken?)

### ISSUE THREAD

**Issue by NikitaKA** [framework7io/framework7#3230]
* Framework7 version: v4.4.5
* Platform and Target: Chrome 75, Cordova Android 8.0

### Describe the bug
this.$f7.views.current is undefined

### To Reproduce
console.log(this.$f7.views.current.router)

### Expected behavior
this.$f7.views.current is not undefined
![image](https://user-images.githubusercontent.com/2543427/60336968-72249180-99aa-11e9-81f2-bc0a75e87638.png)

### Actual Behavior
Error in nextTick: "TypeError: Cannot read property 'router' of undefined"

### Screenshots
![image](https://user-images.githubusercontent.com/2543427/60337071-b7e15a00-99aa-11e9-86c9-be48e9beea31.png)

### Additional context
Works fine in all previous 4.* versions of Framework7.

**Also, some types are broken:**
![image](https://user-images.githubusercontent.com/2543427/60337455-caa85e80-99ab-11e9-81fe-73ea71d59ab4.png)
![image](https://user-images.githubusercontent.com/2543427/60337473-d7c54d80-99ab-11e9-8b93-678a610871bc.png)
![image](https://user-images.githubusercontent.com/2543427/60337527-f6c3df80-99ab-11e9-8eef-78a2400640aa.png)

(I'm not sure about types, maybe it just a WebStorm problem with Typescript support?)

**Comment by nolimits4web** [comment]
Can't see such issue, i have updated all my Vue apps with latest version without the issue. Probably something else is causing it. Do you have live example or JSFiddle?

**Comment by NikitaKA** [comment]
Unfortunately, it's a huge complicated Vue application (wrapped by Cordova) with non-standard module system, so it may take too much time to separate all logic :( Maybe, that is the reason of errors, haha. I will comment here if I found a solution or something related to that problem.

**Comment by Harjot1Singh** [comment]
I'm also experiencing this in React using the same version

**Comment by NikitaKA** [comment]
Problem with types was an issue of my IDE, fixed by clearing a cache.
