### ISSUE TITLE
Initializing Router with Incorrect Params

### ISSUE THREAD

**Issue by akoumjian** [framework7io/framework7#3231]
* Framework7 version: 4.4.3
* Platform and Target: Cordova Browser (Vue)

### Describe the bug
Setting the `pushState` params in the `f7params` on app initialization does not seem to get passed down to the Router instance on initialization. I believe there is a bug on this line where it should just be pointing to `app.params` instead of `app.params.view`:

https://github.com/framework7io/framework7/blob/8b8a5bd7702ee9df6f5ac96e744f4ff4e9c491b1/src/core/modules/router/router-class.js#L29

### To Reproduce
1. Initialize an app with Framework7-Vue
2. Pass in f7params to the main app instance such as `pushState: true,  pushStateSeparator: "",`
3. Observe the browser user not pick up those settings.

### Expected behavior
f7params should be used by Router instance at the application level

### Actual Behavior
Router is using default view params.

**Comment by nolimits4web** [comment]
All correct, it must be set as:
```
f7params = {
  ...
  view: {
    pushState: true,
    ...
  }
}
```
But the very correct place is to set in on required view explicitly
