### ISSUE TITLE
If pushState is turned on, 404 often occurs in the back of cordova packaged app

### ISSUE THREAD

**Issue by david1688** [framework7io/framework7#3233]
### pushState=true
If pushState is turned on, 404 often occurs in the back of cordova packaged app. This is an accidental problem, please advise how to solve it.

**Comment by david1688** [comment]
f7params: {
        id: 'io.framework7.testapp', // App bundle ID
        name: 'Framework7', // App name
        theme: 'auto', // Automatic theme detection
        // App routes
        routes: routes,
        view: {  // 注意这里 pushState 是 view 的属性，直接是直接挂在 framework7 上
          pushState: true,
          pushStateRoot: document.location.pathname.split('index.html')[0],
        },
      },

**Comment by david1688** [comment]
f7params: {
        id: 'io.framework7.testapp', // App bundle ID
        name: 'Framework7', // App name
        theme: 'auto', // Automatic theme detection
        // App routes
        routes: routes,
        view: {  // 注意这里 pushState 是 view 的属性，直接是直接挂在 framework7 上
          pushState: true,
          pushStateRoot: document.location.pathname.split('index.html')[0],
        },
      },

**Comment by nolimits4web** [comment]
It mean that your pushState root or routes is configured incorrectly

**Comment by david1688** [comment]
thanks !   
I git clone https://github.com/framework7io/framework7-template-vue-webpack ,
the routes.js  is like --

   export default [
  {
    path: '/',
    component: HomePage,
    alias: '/index.html',
  },
  {
    path: '/panel-left/',
    component: PanelLeftPage,
  },
  {
    path: '/panel-right/',
    component: PanelRightPage,
  },
  {
    path: '/about/',
    component: AboutPage,
  },
  {
    path: '/form/',
    component: FormPage,
  },
  {
    path: '/dynamic-route/blog/:blogId/post/:postId/',
    component: DynamicRoutePage,
  },
  {
    path: '(.*)',
    component: NotFoundPage,
  },
];
