### ISSUE TITLE
If pushState is turned on, 404 often occurs in the back of cordova packaged app

### ISSUE THREAD

**Issue by david1688** [framework7io/framework7#3235]
thanks !  but ,  Accidental 404 of pages  version: framework7 4.0+ cordova 8.0

I git clone https://github.com/framework7io/framework7-template-vue-webpack ,

 f7params: {
    id: 'io.framework7.testapp', // App bundle ID
    name: 'Framework7', // App name
    theme: 'auto', // Automatic theme detection
    // App routes
    routes: routes,
    view: { 
      pushState: true,
      pushStateRoot: document.location.pathname.split('index.html')[0],
    },
  },

the routes.js is like --

export default [
{
path: '/',
component: HomePage,
alias: '/index.html',
},
{
path: '/panel-left/',
component: PanelLeftPage,
},
{
path: '/panel-right/',
component: PanelRightPage,
},
{
path: '/about/',
component: AboutPage,
},
{
path: '/form/',
component: FormPage,
},
{
path: '/dynamic-route/blog/:blogId/post/:postId/',
component: DynamicRoutePage,
},
{
path: '(.*)',
component: NotFoundPage,
},
];

**Comment by nolimits4web** [comment]
Please, use forum for questions
