### ISSUE TITLE
Routable tabs broken since 4.4.3

### ISSUE THREAD

**Issue by etiennea** [framework7io/framework7#3239]
Basically after switching tabs it will not reload original tab. 

After clicking the link .tab-active does get added correctly to the tab div but the view inside it does not get loaded.

Reverted to 4.4.3 and it all worked again. Thank you in advance.

**Comment by nolimits4web** [comment]
Would be good to see live example or jsfiddle with the issue

**Comment by etiennea** [comment]
Here is the fiddle

https://jsfiddle.net/qfngdrzj/10/

If you go to the tabbed page, then to tab 1 then tab 2 then tab 1 will not render. Am I doing something wrong?

**Comment by shastox** [comment]
> Here is the fiddle
> 
> https://jsfiddle.net/qfngdrzj/10/
> 
> If you go to the tabbed page, then to tab 1 then tab 2 then tab 1 will not render. Am I doing something wrong?

https://jsfiddle.net/qfngdrzj/10/
view : {
        unloadTabContent : false,
},

**Comment by etiennea** [comment]
I have 6 tabs with many pics in each of them, I am not sure not unloading them is the best solution, but at least that works.

**Comment by shastox** [comment]
Если заменить **component** => **componentUrl** проблема остается?
