### ISSUE TITLE
***PreloaderContent в app.utils - это функции или строки: расхождение в документации и коде

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3240]
В документации говорится, что iosPreloaderContent, mdPreloaderContent и auroraPreloaderContent - это **функции**: https://framework7.io/docs/utils.html#preloadercontent

А в коде это **строки**: https://github.com/framework7io/framework7/blob/34e67c758a40049fba9b72d8dfd0d07e555547cf/src/core/utils/utils.js

Не знаю где ошибка - в документации или в коде.

**Comment by nolimits4web** [comment]
Ошибка была в документации
