### ISSUE TITLE
Search function is not available when multiple virtuallist component instances.

### ISSUE THREAD

**Issue by jacktanxd** [framework7io/framework7#3242]
* Framework7 version: 4.3.3
* Vue.js version: 2.6.10
* Platform and Target: iOS 12Cordova app, Chrome browser
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Describe the bug
If there are two instances of a component that contains a virtuallist, the first instance can be searched correctly, but the second one will be affected by the first instance and cannot be searched.

[company.zip](https://github.com/framework7io/framework7/files/3359841/company.zip)

In the attached file, there is a component file named companyVirtualList.vue , which is used by company.vue and companySearch.vue respectively. It can be used correctly in company.vue, but it cannot be used in companySearch.vue.

**Comment by nolimits4web** [comment]
Would be better to see JSFiddle or live example, or code examples, rather than zip file

**Comment by jacktanxd** [comment]
companyVirtualList.vue:
<template>
    <div>
        <f7-block-title>共 {{resultCount}} 个结果</f7-block-title>
        <f7-list class="searchbar-not-found">
            <f7-list-item title="无结果"></f7-list-item>
        </f7-list>
        <f7-list
                ref="f7List"
                class="searchbar-found"
                media-list
                virtual-list
                :virtual-list-params="{ items, searchAll, renderExternal, height: $theme.ios ? 63 : ($theme.md ? 73 : 46)}"
        >
            <ul>
                <f7-list-item
                        v-for="(item, index) in vlData.items"
                        :key="index"
                        media-item
                        :link="'/super/company/companyGeneral/'+item.id"
                        :title="item.shortName"
                        :text="item.address"
                        :style="`top: ${vlData.topPosition}px`"
                >
                    <f7-link
                            slot="subtitle"
                            icon-material="near_me"
                            icon-size="16"
                            color="teal"
                            no-link-class
                    > {{item.region}} {{item.builderType2}}
                    </f7-link>
                    <img slot="media"
                         :src="item.pictureThumbnail!=null ? item.pictureThumbnail : 'static/img/no-pic.jpg'"
                         width="80"/>
                    <f7-icon slot="after" class="iconfont icon-link" color="green" v-if="item.onlineState==1"></f7-icon>
                    <f7-icon slot="after" class="iconfont icon-unlink" color="gray" v-else></f7-icon>
                </f7-list-item>
            </ul>
        </f7-list>
    </div>
</template>
<script>
    export default {
        data() {
            return {
                items: [],
                resultCount: 0,
                vlData: {
                    items: [],
                },
            };
        },
        mounted() {
            this.loadCompanys();
        },
        methods: {
            searchAll(query, items) {
                const found = [];
                for (let i = 0; i < items.length; i += 1) {
                    if (items[i].shortName.toLowerCase().indexOf(query.toLowerCase()) >= 0 ||
                        items[i].address.toLowerCase().indexOf(query.toLowerCase()) >= 0 ||
                        (items[i].companyCode != null && items[i].companyCode.toLowerCase().indexOf(query.toLowerCase()) >= 0) ||
                        query.trim() === '') found.push(i);
                }
                this.resultCount = found.length;
                return found; // return array with mathced indexes
            },
            renderExternal(vl, vlData) {
                this.vlData = vlData;
            },
            loadCompanys(region, onlineState) {
                var self = this;
                if (self.Global.companys == null) {
                    //首次加载单位数据
                    self.ApiService.get(self.ApiUrl.COMPANY, null,
                        function (data, status, xhr) {
                            console.log(data);
                            // debugger;
                            self.Global.companys = data.data;
                            self.replaceAllItems(region, onlineState);
                        }
                    );
                }
                else {
                    self.replaceAllItems(region, onlineState);
                }
            },
            replaceAllItems(region, onlineState) {
                var items = [];
                if (region == null && onlineState == null) items = this.Global.companys;
                if (region == null && onlineState != null) items = this.Global.companys.filter(c => c.onlineState == onlineState);
                if (region != null && onlineState == null) items = this.Global.companys.filter(c => c.region == region);
                if (region != null && onlineState != null) items = this.Global.companys.filter(c => c.region == region && c.onlineState == onlineState);
                this.resultCount = items.length;
                this.$refs.f7List.f7VirtualList.replaceAllItems(items);
            },
        },
    };
</script>

companySearch.vue:
<template>
    <f7-page id="companySearch-page" class="companySearch-page">
        <f7-navbar title="搜索单位" back-link="Back" bg-color="blue" color="white" text-color="white">
            <f7-subnavbar :inner="false">
                <f7-searchbar
                        search-container=".media-list"
                        search-in=".item-title"
                        :disable-button="!$theme.aurora"
                        placeholder="请输入单位名称或地址"
                        @searchbarSearch="searchbarSearch"
                ></f7-searchbar>
            </f7-subnavbar>

        </f7-navbar>
       <companyVirtualList ref="companyVirtualList" />
    </f7-page>
</template>
<script>
    import companyVirtualList from "./companyVirtualList.vue"
    export default {
        data() {
            return {

            };
        },
        components:{
            companyVirtualList
        },
        mounted() {

        },
        methods: {
            searchbarSearch(searchbar, query, previousQuery) {
                if (query.trim() === '')
                    // debugger;
                this.$refs.companyVirtualList.resultCount = this.$refs.companyVirtualList.$refs.f7List.f7VirtualList.items.length;
            },
        },
    };
</script>

company.vue:
<template>
    <f7-page id="company-page" ptr @ptr:refresh="pullRefresh" class="company-page">
        ......
        <f7-popup class="demo-popup-swipe-handler" swipe-to-close="to-bottom" swipe-handler=".swipe-handler"
                  :opened="popupOpened" @popup:closed="popupOpened = false">
            <f7-page>
                <div slot="fixed" class="swipe-handler"></div>
                
                <f7-block class="text-color-black text-align-center font-size-18 margin-top-half " >{{popupTitle}}</f7-block>
                <companyVirtualList ref="companyVirtualList"/>
            </f7-page>
        </f7-popup>
    </f7-page>
</template>

<style lang="less">
    .company-page {
    }
</style>


<script>

    import companyVirtualList from "./companyVirtualList.vue"

    export default {
        data() {
            return {
         
            };
        },
        mounted() {
        
        },
        components: {
            ......
            companyVirtualList
        },
        methods: {
            ......
            dateDetailClick(events) {
                var self = this;
                if(events == 0){
                    self.onlineState = 0;
                    self.popupTitle = '离线单位';
                }else if(events == 1){
                    self.onlineState = 1;
                    self.popupTitle = '在线单位';
                }else if(events == null){
                    self.popupTitle = '联网单位';
                    self.onlineState = null;
                }

                self.popupOpened = true;
                self.$refs.companyVirtualList.loadCompanys(self.regionName,self.onlineState);
            },
           
        }
    };
</script>

**Comment by jacktanxd** [comment]
companyVirtualList.vue:
`<template>
    <div>
        <f7-block-title>共 {{resultCount}} 个结果</f7-block-title>
        <f7-list class="searchbar-not-found">
            <f7-list-item title="无结果"></f7-list-item>
        </f7-list>
        <f7-list
                ref="f7List"
                class="searchbar-found"
                media-list
                virtual-list
                :virtual-list-params="{ items, searchAll, renderExternal, height: $theme.ios ? 63 : ($theme.md ? 73 : 46)}"
        >
            <ul>
                <f7-list-item
                        v-for="(item, index) in vlData.items"
                        :key="index"
                        media-item
                        :link="'/super/company/companyGeneral/'+item.id"
                        :title="item.shortName"
                        :text="item.address"
                        :style="`top: ${vlData.topPosition}px`"
                >
                    <f7-link
                            slot="subtitle"
                            icon-material="near_me"
                            icon-size="16"
                            color="teal"
                            no-link-class
                    > {{item.region}} {{item.builderType2}}
                    </f7-link>
                    <img slot="media"
                         :src="item.pictureThumbnail!=null ? item.pictureThumbnail : 'static/img/no-pic.jpg'"
                         width="80"/>
                    <f7-icon slot="after" class="iconfont icon-link" color="green" v-if="item.onlineState==1"></f7-icon>
                    <f7-icon slot="after" class="iconfont icon-unlink" color="gray" v-else></f7-icon>
                </f7-list-item>
            </ul>
        </f7-list>
    </div>
</template>
<script>
    export default {
        data() {
            return {
                items: [],
                resultCount: 0,
                vlData: {
                    items: [],
                },
            };
        },
        mounted() {
            this.loadCompanys();
        },
        methods: {
            searchAll(query, items) {
                const found = [];
                for (let i = 0; i < items.length; i += 1) {
                    if (items[i].shortName.toLowerCase().indexOf(query.toLowerCase()) >= 0 ||
                        items[i].address.toLowerCase().indexOf(query.toLowerCase()) >= 0 ||
                        (items[i].companyCode != null && items[i].companyCode.toLowerCase().indexOf(query.toLowerCase()) >= 0) ||
                        query.trim() === '') found.push(i);
                }
                this.resultCount = found.length;
                return found; // return array with mathced indexes
            },
            renderExternal(vl, vlData) {
                this.vlData = vlData;
            },
            loadCompanys(region, onlineState) {
                var self = this;
                if (self.Global.companys == null) {
                    //首次加载单位数据
                    self.ApiService.get(self.ApiUrl.COMPANY, null,
                        function (data, status, xhr) {
                            console.log(data);
                            // debugger;
                            self.Global.companys = data.data;
                            self.replaceAllItems(region, onlineState);
                        }
                    );
                }
                else {
                    self.replaceAllItems(region, onlineState);
                }
            },
            replaceAllItems(region, onlineState) {
                var items = [];
                if (region == null && onlineState == null) items = this.Global.companys;
                if (region == null && onlineState != null) items = this.Global.companys.filter(c => c.onlineState == onlineState);
                if (region != null && onlineState == null) items = this.Global.companys.filter(c => c.region == region);
                if (region != null && onlineState != null) items = this.Global.companys.filter(c => c.region == region && c.onlineState == onlineState);
                this.resultCount = items.length;
                this.$refs.f7List.f7VirtualList.replaceAllItems(items);
            },
        },
    };
</script>
`

companySearch.vue:
`
<template>
    <f7-page id="companySearch-page" class="companySearch-page">
        <f7-navbar title="搜索单位" back-link="Back" bg-color="blue" color="white" text-color="white">
            <f7-subnavbar :inner="false">
                <f7-searchbar
                        search-container=".media-list"
                        search-in=".item-title"
                        :disable-button="!$theme.aurora"
                        placeholder="请输入单位名称或地址"
                        @searchbarSearch="searchbarSearch"
                ></f7-searchbar>
            </f7-subnavbar>

        </f7-navbar>
       <companyVirtualList ref="companyVirtualList" />
    </f7-page>
</template>
<script>
    import companyVirtualList from "./companyVirtualList.vue"
    export default {
        data() {
            return {

            };
        },
        components:{
            companyVirtualList
        },
        mounted() {

        },
        methods: {
            searchbarSearch(searchbar, query, previousQuery) {
                if (query.trim() === '')
                    // debugger;
                this.$refs.companyVirtualList.resultCount = this.$refs.companyVirtualList.$refs.f7List.f7VirtualList.items.length;
            },
        },
    };
</script>
`

company.vue:
`
<template>
    <f7-page id="company-page" ptr @ptr:refresh="pullRefresh" class="company-page">
        ......
        <f7-popup class="demo-popup-swipe-handler" swipe-to-close="to-bottom" swipe-handler=".swipe-handler"
                  :opened="popupOpened" @popup:closed="popupOpened = false">
            <f7-page>
                <div slot="fixed" class="swipe-handler"></div>
                
                <f7-block class="text-color-black text-align-center font-size-18 margin-top-half " >{{popupTitle}}</f7-block>
                <companyVirtualList ref="companyVirtualList"/>
            </f7-page>
        </f7-popup>
    </f7-page>
</template>

<style lang="less">
    .company-page {
    }
</style>


<script>

    import companyVirtualList from "./companyVirtualList.vue"

    export default {
        data() {
            return {
         
            };
        },
        mounted() {
        
        },
        components: {
            ......
            companyVirtualList
        },
        methods: {
            ......
            dateDetailClick(events) {
                var self = this;
                if(events == 0){
                    self.onlineState = 0;
                    self.popupTitle = '离线单位';
                }else if(events == 1){
                    self.onlineState = 1;
                    self.popupTitle = '在线单位';
                }else if(events == null){
                    self.popupTitle = '联网单位';
                    self.onlineState = null;
                }

                self.popupOpened = true;
                self.$refs.companyVirtualList.loadCompanys(self.regionName,self.onlineState);
            },
           
        }
    };
</script>
`

**Comment by gowy222** [comment]
The bug still in V4.4.7 
just met the same bug...

**Comment by nolimits4web** [comment]
Closing as not the issue, more likely you have wrong or same selectors in parameters
