### ISSUE TITLE
FW7 Version veriable

### ISSUE THREAD

**Issue by VIEWSION** [framework7io/framework7#3243]
Hey,

I'm not sue if it exists already.... but is there a constant/variable/function to request the release version of FW7 in use? I want to show it automatically on a kind of "about panel"l...

**Comment by nolimits4web** [comment]
There isn't, not sure is it really needed. But if you use bundler like webpack and use npm then you can just include/read it from package.json file https://github.com/framework7io/framework7/blob/master/packages/core/package.json

**Comment by VIEWSION** [comment]
Ok - cool. Reading the package.json is a good idea! Thx!
