### ISSUE TITLE
Ошибка / улучшение при Floating Labels и Additional Info в Inputs

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3245]
1. Берем пример https://framework7.io/docs/inputs.html#examples Floating Labels
2. К каждому элементу списка добавляем `<div class="item-input-info">Дополнительная информация</div>` согласно разделу Validation + Additional Info
3. Получается почти наслоение меток на дополнительную информацию.

Url: https://jsfiddle.net/dbv90738/

Воспроизведение: ставить фокус первому полю, потом второму и т.д.

**Comment by nolimits4web** [comment]
https://framework7.io/docs/inputs.html#item-info

> item-input-with-info - required additional class on input item

Это как раз даст дополнительный отступ
