### ISSUE TITLE
Ошибка: при создании view в popup у страницы вызывается не свое событие

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3249]
Url: http://t.dev.t3b.ru/test3/index.html (воспроизводится только с файлами) сделал крайне минимальный пример.

Есть `<view></view>`, в него загружается **home.f7.html**, в которой есть ссылка на открытие **popup**. Структура этого **popup**:

`popup>view>page`

В **page1.f7.html** есть событие **pageInit** (вывод в консоль), теперь мы переходим по ссылке на **page2.f7.html**, которая имеет структуру просто **page** и происходит вызов события **pageInit**, которое относится к **page1.f7.html**, хотя в само событие в параметры функции попадает конечно страница **page2**.

**Comment by nolimits4web** [comment]
Всё правильно, событие `page:init` вешается на элемент попапа. И когда вторая страница загружается событие всплывает до попапа. Нужно тогда писать так:
```
<div class="page" @page:init="onPageInit">
```
