### ISSUE TITLE
page-with-navbar-large not applied for MD theme

### ISSUE THREAD

**Issue by hectorgrebbell** [framework7io/framework7#3251]
* Framework7 version: 4.4.6
* React.js version: 16.8.6
* Platform and Target: Chrome 75

### Describe the bug
page-with-navbar-large is not applied correctly when MD theme is active

### To Reproduce
Add a NavTitleLarge. Switch theme to MD. Add some content.

### Expected behavior
Content is below NavBar

### Actual Behavior
Content is covered by NavBar

### Additional context
https://github.com/framework7io/framework7/blob/master/src/core/components/navbar/navbar.js#L566 executes adding the class. 

On IOS the below sets `hasNavbarLarge: true ` but on MD it doesn't.
https://github.com/framework7io/framework7/blob/master/src/phenome/components/page.jsx#L406

This then causes https://github.com/framework7io/framework7/blob/master/src/phenome/components/page.jsx#L183 to remove it.

You can workaround the issue by adding `className="page-with-navbar-large"` to the Page.

**Comment by nolimits4web** [comment]
Make sure you have set `large=true` prop on navbar with `NavTitleLarge`
