### ISSUE TITLE
Bypass Links Handler for all elements in the block

### ISSUE THREAD

**Issue by bugsmafia** [framework7io/framework7#3252]
Необходимо дополнить Link element для полного отключения обработки роутера F7 сразу всех внутренних href в блоке.
Стало актуально после появления десктоп версии движка.
Яндекс.Директ и другие рекламные платформы, не позволяют добавить класс "external" в ссылки, F7 роутер их обрабатывает и не позволяет произвести переход по ним.

**Comment by nolimits4web** [comment]
Для этого есть параметр `clicks.externalLinks` https://framework7.io/docs/app.html#app-parameters
Можно указать например, `.external, .some-block a`
