### ISSUE TITLE
iPad navigation inconistency

### ISSUE THREAD

**Issue by holtwick** [framework7io/framework7#3255]
If using the `master: true` option in the `routes` definition, the opened sub-pages are stacked. In most iPad apps instead the right pane is usually just replaced.

**Describe the solution you'd like**
I would love to see a full iPad demo, as there is for iPhone, Android and Aurora on the start page already. 

I would also like the first item to not have a "Back" button, when there is no page to navigate to.

[Using this Fiddle](https://jsfiddle.net/perenzo/e8kcdzxy/11/
) I was not able to achieve this by setting any of these options: https://framework7.io/docs/routes.html#route-options

<img width="504" alt="image" src="https://user-images.githubusercontent.com/49557/61294332-e0a08680-a7d5-11e9-85c2-13e763af91b4.png">

Video: https://holtwick.de/download/20190716-142948-iPadBack.mp4

Real world example: [OnePile iOS](https://onepile.app/)

**Comment by nolimits4web** [comment]
> the opened sub-pages are stacked. In most iPad apps instead the right pane is usually just replaced.

There is a `reloadDetail` view parameter that will do what you need https://framework7.io/docs/view.html#view-parameters
And you can see this behavior in Kitchen Sink https://framework7.io/kitchen-sink/core/?theme=ios

> I would also like the first item to not have a "Back" button, when there is no page to navigate to.
Right now this can be done manually by, for example, checking `router.history.length` and adding some class to page to hide back button. But i will built-in this behavior in v5

**Comment by holtwick** [comment]
This is strange. I found your demo in the kitchen sink and it seems to work as expected. I identified, that you are using the option in the linking list item like this:

```
<f7-list-item :reload-detail="true" link="/master-detail/1/">Detail Page 1</f7-list-item>
``` 

But when I do the same in my app, I don't get the same effect. These are my routes at runtime:

![Safari 2019-07-19 at 14 28 02@2x](https://user-images.githubusercontent.com/49557/61535122-bea34000-aa31-11e9-9f58-a4e0166cd9d5.png)

What am I doing wrong?

**Comment by holtwick** [comment]
Well it has the effect, that back navigation is not working anymore, but the back link still appears.

**Comment by nolimits4web** [comment]
If you use reloadDetail for all detail pages of master, then you can just add this CSS rule:
```
.view-master-detail .navbar-master-detail .link.back, .view-master-detail .page-master-detail .navbar .link.back {
    display: none;
}
```

**Comment by holtwick** [comment]
I see. Well in my case I only want to hide it for the top-level page in master. But I can try to find a workaround that is based on your proposal. I just wonder if it isn't the expected behavior that the first page in master with no previous page on the stage hides the `back` button?

**Comment by nolimits4web** [comment]
This is already done in v5, it has new `page-master-detail-root` class on page (the first detail page). And it is also hides back link in navbar for such page by default

**Comment by holtwick** [comment]
Awesome! Thanks.
