### ISSUE TITLE
IE11 issue

### ISSUE THREAD

**Issue by pet2131** [framework7io/framework7#3258]
Hello,

When I try to view the live demo examples in Internet Explorer 11 I get nothing but a white screen and these errors in the console:

> SCRIPT438: Object doesn't support property or method 'from'
and
> SCRIPT5009: 'Dom7' is undefined

Is there a way to fix those?

Is there a version of Framework7 that is working(partly) on IE11?

Keep up the good work!

**Comment by nolimits4web** [comment]
Sorry, but IE11 is not supported at all
