### ISSUE TITLE
List accordion cannot be "opened" using prop

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3264]
* Framework7 version: 4.4.7
* Vue.js version: 2.6.10
* Platform and Target: pwa (not tested elsewhere)
* Live Link or JSFiddle: https://jsfiddle.net/0d6eugsa/

### Describe the bug
The props "opened" does not work on an accordion-item when it's a list-item

### To Reproduce
1. Create a list accordion
2. Add the "opened" props on the accordion-item

### Expected behavior
The accordion-item should be opened by default

### Actual Behavior
The accordion-item is closed by default

**Comment by nolimits4web** [comment]
There is no such `opened` prop. Check docs https://framework7.io/vue/list-item.html

**Comment by Pitouli** [comment]
My bad, I was using the prop of the accordion item (
https://framework7.io/vue/accordion.html)
