### ISSUE TITLE
radio in virtual-list BUG! v4.4.+

### ISSUE THREAD

**Issue by gowy222** [framework7io/framework7#3268]
### Describe the bug
Checked item1 radio, then scrolldown to deep and deep(such as to item10000),
then goback to item1, the radio state just back in unChecked again...

means...VDOM can not saving kinda css(or css after clicked) changes like Radio.

**Comment by gowy222** [comment]
2nd bug? Searchbar can not work in router pages
=============================================
IF I router same componentUrl couple times like:
 {
    path: '/vlistdom1/',
    componentUrl: './vlistDOM.html  ',
  },

 {
    path: '/vlistdom2/',
    componentUrl: './vlistDOM.html  ',
  },

thus, the Searchbar in the 2nd router page '/vlistdom2/' is not working...

**Comment by gowy222** [comment]
2nd bug? Searchbar can not work in router pages

according to the sample: https://framework7.io/kitchen-sink/core/pages/virtual-list-vdom.html

IF I router same componentUrl couple times like:
{
path: '/vlistdom1/',
componentUrl: './vlistDOM.html ',
},

{
path: '/vlistdom2/',
componentUrl: './vlistDOM.html ',
},

thus, the Searchbar in the 2nd router page '/vlistdom2/' is not working...

**Comment by shastox** [comment]
> ### Describe the bug
> Checked item1 radio, then scrolldown to deep and deep(such as to item10000),
> then goback to item1, the radio state just back in unChecked again...
> 
> means...VDOM can not saving kinda css(or css after clicked) changes like Radio.

https://framework7.io/docs/virtual-list.html 
cache:true

**Comment by gowy222** [comment]
cache:true; (according to the doc, cache regular value is true, means auto init right?)

but the checked radio state will display in the wrong row via scrolling…

**Comment by nolimits4web** [comment]
Closing as not the issue, use VL DOM cache or bind and watch/keep that state in your code logic

**Comment by gowy222** [comment]
set cache:true;
but the checked radio state will display in the wrong row via scrolling…
