### ISSUE TITLE
[FR] Missing React components

### ISSUE THREAD

**Issue by rafamel** [framework7io/framework7#3270]
There's currently several components not implemented for React. Are they intentionally left out, or is there a plan to release them at some point in the future?

Ej. Picker, Color Picker, Data Table, Dialog, Elevation, Infinite Scroll...

**Comment by nolimits4web** [comment]
> Are they intentionally left out

Yes, use core JS api or plain HTML for them

Color Picker is part of the ListInput, Infinite Scroll part of the Page
