### ISSUE TITLE
[FR] Pass React Component Extensions as context

### ISSUE THREAD

**Issue by rafamel** [framework7io/framework7#3271]
**Is your feature request related to a problem? Please describe.**

React Component Extensions are only accesible on Class components.

**Describe the solution you'd like**
 In order to make them accessible to hooks and functional components, it would be ideal to use the React context api, hence passing them in context, and exporting the React Context Provider, Consumer, and object, so it can be used in hooks and Class components alike.

**Comment by nolimits4web** [comment]
Done for v5
