### ISSUE TITLE
Grid columns not responsive within list

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#3272]
* Framework7 version: 4.4.10
* Platform and Target: Cordov, FF, Chrome
* Live Link or JSFiddle: 
https://jsfiddle.net/teamscoring/w0co5v2m/3/

### Describe the bug
I am grouping form inputs within  a grid (5 columns).  My last row only has 2 cells so I added 3 empty cells to space it out (`<div class="col"><&nbsp;</div>`).  I put this structure within a list view (1 row per list row).  No matter what I do to the last row, it just won't space the cells out evenly.  The Fiddle provides an example.

I also experimented by taking the grid out of the list view and placing it inside a div block.  It works as expected but it looks ugly.  The list structure seems to be messing up the flex.

I didn't initially notice this because I had 4 full rows.  It wasn't until I added another shorter row that the problem surfaced.  I just checked V3 and it wasn't a problem there.

### To Reproduce
Check fiddle

### Expected behavior
Grid should responsively build a nice even grid 

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
Check CSS:
https://jsfiddle.net/kb24wxoa/
