### ISSUE TITLE
Stacked Popups via Router

### ISSUE THREAD

**Issue by holtwick** [framework7io/framework7#3280]
I have multiple popups defined via routes. One popup is opening another. They show up correctly and stack well. But when closing via `popup-close` attributed link, only the second click has an effect and closes both.

Video:  https://holtwick.de/download/20190805-214052-popup-stack.mp4

Console says: `Error: Framework7: it is not allowed to use router methods on global app router. Use router methods only on related View, e.g. app.views.main.router.back(...)`

Routes:

```js
{
      path: '/settings/',
      popup: {
        component: iosSettings,
      },      
    },    
    {
      path: '/sync/icloud',
      popup: {
        component: iosICloud,
      },      
    },
```

Template:

```
<template>
  <f7-popup>
    <f7-view
      :push-state="false"
      :master-detail-breakpoint="0"
    >
      <f7-page>
        <f7-navbar>
          <f7-nav-left>
            <f7-link popup-close
                     icon-ios="f7:close"
                     icon-md="f7:close">
            </f7-link>
          </f7-nav-left>
          <f7-nav-title>Apple Cloud</f7-nav-title>
        </f7-navbar>

        <icloud></icloud>
      </f7-page>
    </f7-view>
  </f7-popup>
</template>
```

**Comment by nolimits4web** [comment]
Well, actually all correct :) With first click it closes underlying popup and with second one current one. Just make popup-close link more specific, e.g. add `popup-1` and `popup-2` classes to Popups, and use the following on links: `<f7-link popup-close=".popup-1" ...>` and `<f7-link popup-close=".popup-2" ...>`

**Comment by holtwick** [comment]
Ah great! Thanks. That works much better. Even in Vue I can programmatically do this now:

```js
this.$f7.close('.popup-1')
```
