### ISSUE TITLE
Routable tab component starting with a <form> tag is blank

### ISSUE THREAD

**Issue by jdspugh** [framework7io/framework7#3282]
* Framework7 version: 4.4.10
* Platform and Target: All

### Describe the bug
Routable tab tab component starting with a `<form>` tag renders as blank. Adding an outer `<div>` will hack/fix the problem.

### To Reproduce
Routes include a routable tab like:
```
  { 
    path: '/test/:id?/', component: new TabComponent(),
    tabs: [
      {path:'/', id:'tab-1', component: new Tab1Component()},
      {path:'/2/', id:'tab-2', component: new Tab2Component()},
      {path:'/3/', id:'tab-3', component: new Tab3Component()},
    ]
  }
```
Tab1Component has a template like:
```
<form>
  ...
</form>
```
It works if I add an outer div:
```
<div>
  <form>
    ...
  </form>
</div>
```

### Expected behavior
Form should render

### Actual Behavior
Blank tab content

**Comment by nolimits4web** [comment]
Thanks, fixed
