### ISSUE TITLE
Navbar inner hides Smart select title bar

### ISSUE THREAD

**Issue by jonybuzz** [framework7io/framework7#3286]
* Framework7 version: 4.4.10
* Theme: MD (didn´t test iOS)
* Live Link or JSFiddle: https://jsfiddle.net/23frzan6/2/

### **Navbar inner** & **Smart select title** issue
As shown in the fiddle, the navbar hides de smart select title, espescially the back button.

### Expected behavior
Smart select bar should have priority over the navbar. Otherwise it should be specified the incompatibiity in documentation

**Comment by nolimits4web** [comment]
Navbar should be a direct child of Page, otherwise call manually navbar hide when smart select opens
