### ISSUE TITLE
SmartSelect.close() the instance on the open or opened event handlers seems to doesn't work properly

### ISSUE THREAD

**Issue by isaacbatst** [framework7io/framework7#3293]
* Framework7 version: 4.4.10
* Platform and Target: Cordova App - Tested on Android 9 and Browser
* https://jsfiddle.net/isaacbatst/xr1gdojp/32/  (Thanks for the template)

### Describe the bug
Using smartselect.close() method on opened handler crashes closeByBackdropClick feature.
Using smartselect.close() method on open handler makes the open event doesn't trigger anymore.
### To Reproduce
1. Go to https://jsfiddle.net/isaacbatst/xr1gdojp/32/
2. Click on the button to init the smartselects
3. Open the first smartselect three times to see the error 1.
4. Open the second smartselect three times to see the error 2.

### Expected behavior
Expected the smartselect to open when the counter equals 0 and to do not open when the counter equals 1.

### Actual Behavior
Using smartselect.close() method on opened handler does my logic to open the smart select only when the counter equals 0, but it crashes closeByBackdropClick feature.

Using smartselect.close() method on open handler stops triggering the open event.

### Additional context
The counter starts at 0 and it's toggled each time you open the smartselect.
Each smart select has its own counter.

TESTED ONLY IN THE **SHEET** MODE.

**Comment by isaacbatst** [comment]
For some reason when I posted my message was entirely replaced by the issue template, so I had to write it again.

**Comment by isaacbatst** [comment]
Oh, and tested only opening the smart select in a **SHEET**

**Comment by isaacbatst** [comment]
And also I got doing what I wanted first by triggering a click on the '.sheet-close' button, but I think it's still a thing to watch out

**Comment by isaacbatst** [comment]
I tried also closing the smartselect by triggering the '.sheet-close' button instead, and just had the same issues.

**Comment by nolimits4web** [comment]
You can add zero timeout to `opened` handler to make it work correctly https://jsfiddle.net/L9v3kadu/. But anyway, such usecase is wrong, there is no sense to open something just to close it. You should do required check and don't allow it to open when it is not needed https://jsfiddle.net/L9v3kadu/

**Comment by isaacbatst** [comment]
I see... I got it, thanks for the advice, it really makes sense. So, where should be the best point (speaking in organization/best practices terms) to put that check? On a click handler of the 'a.smart-select' element?
