### ISSUE TITLE
Предложения по календарю, таймпикеру

### ISSUE THREAD

**Issue by Overman775** [framework7io/framework7#3299]
Добрый день Владимир!

Анализируя календарь F7 пришёл к мысли что будет удобнее и продуктивнее брать локали(monthNames и т.д.) из Intl.DateTimeFormat. Также можно сделать вывод даты через 

Судя по https://caniuse.com/#search=Intl конфликтов не должно быть, ios 10+ android 5 поддерживаются.
https://webkit.org/blog/6978/javascript-internationalization-api/

Предлагаю:
- Брать локали из Int l(monthNames и т.д.)
- Вывод даты и/или времени в input через Intl.DateTimeFormat().format
- Кастомизация вывода(weekday: "short" и т.д.)
- Возможность вручную менять текущую локаль

**Comment by nolimits4web** [comment]
Добавил в v5
