### ISSUE TITLE
StatusBar [v5]

### ISSUE THREAD

**Issue by lailton** [framework7io/framework7#3302]
Hello @nolimits4web,

I am doing a test using v5 and I noticied that statusbar is not working,
It will be removed?

for all themes ( iOS/Android/Desktop ) when I click SHOW STATUS nothing happen.

Thanks

**Comment by nolimits4web** [comment]
Yes, it is gone in v5

**Comment by lailton** [comment]
Oh, sad... I liked it... 
There is any reason why it will be removed?

Any chance keep it available?

**Comment by nolimits4web** [comment]
> There is any reason why it will be removed?

Yes, it is not needed anymore

> Any chance keep it available?

No:) Please wait for release
