### ISSUE TITLE
[v5] Calendar no longer works on Safari 11.1.2 (Mac)

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3303]
After the recent changes to the Calendar, this component no longer works on **Safari 11.1.2** (latest version compatible with OS X El Capitan 10.11.6) the Calendar no longer opens and the following error is displayed in the console:

![Schermata 2019-08-23 alle 19 34 32](https://user-images.githubusercontent.com/1197819/63613872-fc235c00-c5e1-11e9-9844-f8cc740cd5a1.png)

The problem seems to concern: `yearFormatter`, `monthFormatter`, `dayFormatter` and `timeSelectorFormatter`.

and as a solution at the time I found that it seems to work well by modifying, for example, from

`currentYear = calendar.yearFormatter.format(date);`

to

`currentYear = new Intl.DateTimeFormat(calendar.params.locale, { year: 'numeric' }).format(date);`

and so on also for `monthFormatter`, `dayFormatter` and `timeSelectorFormatter`.

With **Firefox 68.0.2** on OS X El Capitan version 10.11.6, everything seems ok.

Maybe f7 v5 will no longer be compatible with Safari 11.1.2?

**Comment by DAnn2012** [comment]
Maybe I found another solution, **after** the following lines...

```
dayFormatter: new Intl.DateTimeFormat(calendar.params.locale, { day: 'numeric' }),
monthFormatter: new Intl.DateTimeFormat(calendar.params.locale, { month: 'long' }),
yearFormatter: new Intl.DateTimeFormat(calendar.params.locale, { year: 'numeric' }),
timeSelectorFormatter: new Intl.DateTimeFormat(calendar.params.locale, calendar.params.timePickerFormat),
});
```

**add** these lines...

```
calendar.dayFormatter = new Intl.DateTimeFormat(calendar.params.locale, { day: 'numeric' });
calendar.monthFormatter = new Intl.DateTimeFormat(calendar.params.locale, { month: 'long' });
calendar.yearFormatter = new Intl.DateTimeFormat(calendar.params.locale, { year: 'numeric' });
calendar.timeSelectorFormatter = new Intl.DateTimeFormat(calendar.params.locale, calendar.params.timePickerFormat);
```

and no other changes.

**Comment by nolimits4web** [comment]
Thanks for noticing 👍 Fixed
