### ISSUE TITLE
Notification black background

### ISSUE THREAD

**Issue by VisualMafia** [framework7io/framework7#3306]
On some devices there is a problem with the background in the notifications. I can’t find the reason, there are no such devices. Such a problem in versions 3 and 4.

`	      let notif = this.$f7.notification.create({
		      icon: '<i class="icon f7-icons color-blue">bell_fill</i>',
		      title: 'text',
		      subtitle: 'text',
		      text: 'text',
		      closeOnClick: true,
		      closeButton: true,
		      closeTimeout: 300000,
	      });
	      notif.open();`

![notification](https://user-images.githubusercontent.com/32130604/64022834-b0236a80-cb3f-11e9-86f7-1bf45775cfcb.jpg)

**Comment by nolimits4web** [comment]
This is why it is not recommended to us iOS theme on android and MD theme on ios devices. It is because notification in iOS theme has `backdrop-filter` CSS property. You need to remove it to avoid this Android bug
