### ISSUE TITLE
iOS tablet input focusing bug

### ISSUE THREAD

**Issue by Jogiter** [framework7io/framework7#3308]
* Platform and Target: [e.g. iOS 11 safari browser]

### iOS tablet input focusing bug
visiting [https://framework7.io/](https://framework7.io/) in safari on my tablet

### To Reproduce
1. Click the 'Inputs' 
2. focusing any input
3. Scroll the page(quickly or slowly)

### Expected behavior
the focusing line fixed in the input

### Actual Behavior
the focusing line fixed in the screen

### Screenshots
![input-good](https://user-images.githubusercontent.com/9711036/64142998-e82cf500-ce40-11e9-860b-b28195464978.jpeg)
![input-bad](https://user-images.githubusercontent.com/9711036/64142999-e8c58b80-ce40-11e9-81a3-c63bc67769a3.jpeg)

**Comment by nolimits4web** [comment]
You need to open it in new page, no much sense to test it in iframe which is just for preview

**Comment by Jogiter** [comment]
> You need to open it in new page, no much sense to test it in iframe which is just for preview

actually, i do clone the master repo and run script `yarn run vue:dev`，and then i visiting my locale page on my ipad, It behaves the same as in iframe
