### ISSUE TITLE
regression clip-path on android 6.0 from v5.0.0-beta.12

### ISSUE THREAD

**Issue by thedeadofblackfire** [framework7io/framework7#3309]
Hi Vladimir, 

First, great job for Framework7. 
I love it since v1 !

Im using the upcoming v5 to build a new fresh cordova hybrid app.
On some of my mobile screens, im using clip-path & border-radius css instructions to make some beautifull shapes & effects.
With v5.0.0-beta.11, on a samsung note 9 (android 9) & on an huawei honor 7 (android 6) devices, the pages displays correctly.
But since the v5.0.0-beta.12, only the note 9 works well. The older android 6 is displaying now a blank area on the clip-path & border-radius when im deploying the apk on it.
I thought first that was an issue with the framework7.bundle.min.css files but after some researching, something on the framework7.bundle.min.js make the trouble since the latest commits after beta.11. 
For both samsung note 9 & huawei honor 7, im using the latest Chrome & Android web view, exactly the same release number. On local dev environment, the latest chrome is ok.

Do you have any idea ? What is the minimum requirement (web view / android version) for the upcoming final v5 ?
On all the other production apps are using fw7 4.4.10 correctly with clip-path effect. I didn't check the 4.5.0 on it to see if the same issue.

Thank you.

Nick

**Comment by nolimits4web** [comment]
Could you please provide more details better with the issue in JSFiddle so i can see what is exactly doesn't work?

**Comment by thedeadofblackfire** [comment]
I tried to put the example on jsfiddle but it's only from cordova old devices the bogus coming.

Finally, i found the issue, it was the commit "v5: Core: CSS - remove unnecessary transform" removing "transform: translate3d(0,0,0);" 

My temp solution for old android device is to enable it again in a separate css file:
.link,
.tab-link {
	transform: translate3d(0,0,0);
}
.navbar {
	transform: translate3d(0,0,0);
}

Another note, on iOS, the clip-path has some crap effect when the user scolls, the solution is also to add transform: translate3d(0,0,0); on the same css element that contains the clip-path to have fluid animation.
