### ISSUE TITLE
Datepicker and Colorpicker F7 v5.beta14 clear button bug

### ISSUE THREAD

**Issue by Overman775** [framework7io/framework7#3310]
Привет!

Нашел баг, при нажатии на clear-button в инпуте clear-button крестик не исчезает, инпут как положено чистится.
Также предлагаю при очистке через clear-button слать пустой массив через событие calendar:change дабы не городить лишних листенеров.

```
        <f7-list-input 
          type='datepicker' 
          clear-button 
          :value="dateStart"
          @calendar:change="dateStart = $event"
        >
```

П.С.: таймпикер ещё не проверял

**Comment by Overman775** [comment]
На beta14 аналогично.
Такая же проблема и с colorpicker, не удаляется clear-button.
Предлагаю возвращать пустой объект через colorpicker:change при нажатии clear-button и дописать возможность принимать value пустой объект(сейчас выдаёт ошибку)

**Comment by nolimits4web** [comment]
Тут надо просто обрабатывать это событие:
```
        <f7-list-input 
          type='datepicker' 
          clear-button 
          :value="dateStart"
          @input:clear="dateStart = []"
          @calendar:change="dateStart = $event"
        >
```

**Comment by nolimits4web** [comment]
И у Color Picker'a по идее не может быть такого чтобы не было значения

**Comment by Overman775** [comment]
> Тут надо просто обрабатывать это событие:
> 
> ```
>         <f7-list-input 
>           type='datepicker' 
>           clear-button 
>           :value="dateStart"
>           @input:clear="dateStart = []"
>           @calendar:change="dateStart = $event"
>         >
> ```

Можно и так, но по сути очистка поля это событие изменения календаря.
Даже с заменой на пустой массив clear-button не исчезает
![ScreenCaptureProject4](https://user-images.githubusercontent.com/47769319/64250660-235a2180-cf30-11e9-8678-a4b3386d35e4.gif)

**Comment by Overman775** [comment]
> И у Color Picker'a по идее не может быть такого чтобы не было значения

Можно посмотреть с другой стороны, например нам нужно знать выбран ли цвет или нет чтобы дальше работать с ним, отсылать в БД и т.д, или наоборот пришли данные где нет цвета, или пользователь очистил цвет через clear button. При отсутствие hex ключа в объекте можно просто автоматом ставить белый и дальше строить colorpicker

**Comment by nolimits4web** [comment]
Fixed for `datepicker`
