### ISSUE TITLE
Swipeable Tabs or Swiper can not work well on LoginScreen or Popup.

### ISSUE THREAD

**Issue by ATShiTou** [framework7io/framework7#3313]
* Framework7 version: 4.5.0
* React.js version: 16.9.0
* Platform and Target: All
* Live Link or JSFiddle: https://jsfiddle.net/wehycmbr/6/

1. Open Popup
2. Swipe

### Expected behavior
Can not stop correctly.

**Comment by nolimits4web** [comment]
You need to do `swiper.update` (http://idangero.us/swiper/api/#methods) when popup opened. Or use HTML elements instead of components https://framework7.io/docs/tabs.html#swipeable-tabs and you can pass swiper's `observer` and `observeParents` parameters

**Comment by ATShiTou** [comment]
Would you please show an example ? How can I fix it on  https://jsfiddle.net/wehycmbr/6/  ?

I do not understand how to call `swiper.update`(http://idangero.us/swiper/api/#methods)
