### ISSUE TITLE
Page custom transistion F7 V5.beta14

### ISSUE THREAD

**Issue by Overman775** [framework7io/framework7#3317]
Привет!

Не знаю баг это или нет, возможно поспешил :), но не получается задать transistion эффект. Через роутер options всё работает а когда в самом  view пишешь то эффект не меняется

**Пример:**
`<f7-view id="main-view" main :transition="'f7-circle'" :options="{transition: 'f7-circle'}" :params="{transition: 'f7-circle'}">`

или в f7params
```
        view: {
        	transition: 'f7-circle'
        },
```

Пример JSFiddle:
https://jsfiddle.net/Silver775/f7smdxgu/

Пробовал также локально на свежем билде, такая же история

**Цель:**
Единожды прописать анимацию перехода между страницами

**Comment by nolimits4web** [comment]
Поспешил :) Это еще не "релизнуто". Будет в 15 бете
