### ISSUE TITLE
lazy modules swiper

### ISSUE THREAD

**Issue by yijiaqingilm** [framework7io/framework7#3318]
use it like this 
![image](https://user-images.githubusercontent.com/18654185/65030928-f6b3fa00-d972-11e9-869c-5bcd122cd5ba.png)

error:
![image](https://user-images.githubusercontent.com/18654185/65030977-0a5f6080-d973-11e9-92e1-82893831818a.png)

What should I do to make it work?

**Comment by yijiaqingilm** [comment]
Device$1  is a global variable, but there is no place to define it

**Comment by nolimits4web** [comment]
Show all related code, how do you use it, app parameters, etc.

**Comment by nolimits4web** [comment]
What is in the main JS file

**Comment by yijiaqingilm** [comment]
![image](https://user-images.githubusercontent.com/18654185/65032292-6d51f700-d975-11e9-8179-4021fc8c7f15.png)

This is a lazily loaded file, but $Device$1 doesn't know what file to refer to
