### ISSUE TITLE
using toolbar hideOnPageScroll will cause iOS flicker 

### ISSUE THREAD

**Issue by mohshraim** [framework7io/framework7#3320]
* Framework7 version: [e.g. 4.4.10]
* Platform and Target: [e.g. iOS 12.3  WKWebView]

### Describe the bug
initialize app with options hideOnPageScroll  for toolbar at bottom
this will cause Very bad flicker while scrolling on iOS, the flicker can be very obvious if page content contain many images and more controls...
remove this hideOnPageScroll  from app init will make app scrolling very smooth as expected

Note
* Flicker obvious  appear even on iPhoneX
*  i didn't test it on Android and i think flicker came from bounce exist on iOS 

Thanks

**Comment by nolimits4web** [comment]
Would be great to see live example or JSFiddle with the issue
