### ISSUE TITLE
Feature Request: Regular Website/Web App style and Specific OS Theming for Desktop

### ISSUE THREAD

**Issue by D-Marc1** [framework7io/framework7#3322]
**Describe the solution you'd like**
It would be really cool if it would be eventually possible to add a true website/web app styling, much like Bootstrap for web and [Photon](https://mauriceconrad.github.io/Photon/]) for desktop.

**Additional context**
This would truly make it possible to only use one framework and code base for all platforms.

**Comment by nolimits4web** [comment]
There is an `aurora` theme that is designed to be used in desktop apps/websites

**Comment by D-Marc1** [comment]
Yes, but aurora isn't themed for Mac, Windows, Linux, like how Framework7 is for iOS and Android. Obviously it would be very time consuming, and I can understand you not feeling like it would be worth the time.

Additionally, I feel like Aurora should convert things like pickers to a form select, so it's more suitable for the web out of the box.
