### ISSUE TITLE
Icons cheatsheet outdated

### ISSUE THREAD

**Issue by vicovictor** [framework7io/framework7#3326]
On this page https://framework7.io/icons/, the cheatsheet is outdated. The correct cheatsheet should be this https://github.com/framework7io/framework7-icons/blob/master/cheatsheet/index.html. Took me a while to figure out why the icons were not showing. 😅 

I could help update https://framework7.io/icons/. Lemme know if there is a repo that I can contribute.

**Comment by nolimits4web** [comment]
Fixed a while ago
