### ISSUE TITLE
When navigating for 2 times or more on LoginScreen. The Router will be last.

### ISSUE THREAD

**Issue by ATShiTou** [framework7io/framework7#3327]
* Framework7 version: 4.5.0
* React.js version: 16.9.0
* Platform and Target: All
* Live Link or JSFiddle: https://jsfiddle.net/e2qkyhjp/26/
### Describe the bug
When navigating for 2 times or more on LoginScreen. The Router will be last.

### To Reproduce
1. Click on 'Login Screen'
2. Click on 'Forgot'
3. Click on 'Reset'
4. Go back to LoginScreen. It will be last.

### Expected behavior
When navigating for 2 times or more on LoginScreen. The Router will be last.

### Actual Behavior
NO

### Screenshots
NO

### Additional context
NO

**Comment by nolimits4web** [comment]
Because you need to keep main login screen page in routes too, or enable `stackPages` on its View

**Comment by ATShiTou** [comment]
It works, thank you!
