### ISSUE TITLE
$$("tbody").append('tr') failed to append

### ISSUE THREAD

**Issue by kdzxiaoli** [framework7io/framework7#3328]
* Framework7 version: [e.g. 3.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
it's not work to append tr to tbody using $$ function
but use other tag such as li  span   it works successfully

### To Reproduce
`$$('tbody').append('<tr><td>111</td></tr>')`

### Expected behavior
to append to the tbody element

### Actual Behavior
only the tr's text to append to the tbody element

### Additional context
framework version is Framework7 4.4.3

**Comment by nolimits4web** [comment]
Use it like so:
```
$$('tbody').append($$('<tr><td>111</td></tr>'))
