### ISSUE TITLE
ListItem in custom component doesn't wrap into <ul> tag (React, JSFiddle is available)

### ISSUE THREAD

**Issue by MrFoxPro** [framework7io/framework7#3329]
* Framework7 version: 4.5.1
* React.js version: 16.9.0
* Platform and Target: Chrome browser
* Live Link or JSFiddle: https://jsfiddle.net/m8dkf4ny/

### Describe the bug
If i wrap ListItem in another component, <ul> tag doesn't display, so content is being rendered wrong

### To Reproduce
see jsfiddle
1 and 2 items are wrapped in another functional component, and last is rendered as simple ListItem
![image](https://user-images.githubusercontent.com/17229619/65832275-e721a300-e2da-11e9-8010-a8bc77aa5e58.png)

![image](https://user-images.githubusercontent.com/17229619/65832281-04ef0800-e2db-11e9-806a-6259b50181c0.png)

**Comment by MrFoxPro** [comment]
Found that using wrapped Toolbar it's also being rendered incorrect, out of page-current

**Comment by MrFoxPro** [comment]
Are reusable components disallowed?

**Comment by nolimits4web** [comment]
Use `slot="list"` on custom list items https://jsfiddle.net/t8n41ax9/
