### ISSUE TITLE
Range slider  and  date time problem in latest update of google chrome

### ISSUE THREAD

**Issue by espriweb** [framework7io/framework7#3330]
Hi, I noticed that the following components:

theme android:

"range slider" -> not work in desktop browser mode
"date time" -> use standard html calendar in desktop browser mode
"ripple touch" -> disabled on desktop browser mode

they no longer work on the google-chrome desktop browser, while on firefox they work properly.

I found the problem on 2 different PCs (windows 10) where I recently updated google-chrome to the version (77.0.3865.90). The strangest thing is that if I use the development tool in adroid / apple simulation mode the two components work correctly.

As if that were not enough, I went to your site and repeated the tests described above and verified the same problem from your site.

You can help me?
Thanks in advance

* Framework7 version: [e.g. 4.5.2]
* Platform and Target: [Chrome browser 77.0.3865.90 WIN10]
* Live Link or JSFiddle: https://framework7.io/docs/inputs.html

### Describe the bug
Go to top

### To Reproduce
1. Go to https://framework7.io/docs/inputs.html
2. Click on "range slider" and "date time"
3. Scroll down to "range slider" and "date time"
4. See error Not Work

### Actual Behavior
Explain what is actually happening

**Comment by cepm-nate** [comment]
I just went to https://framework7.io/docs/range-slider.html and tried it with "Desktop" mode. The sliders themselves seem to work fine, but the "$200 - $400" text is NEVER updated based on the range in "Price Slider". Not sure if it is supposed to though? (this is on Chrome 77.0.3865.120)

https://framework7.io/docs/calendar.html#examples, everything uses the Framework 7 components, in all themes.

I can't speak for "ripple touch", as I'm not sure what mean by that. Ripple touch effect should only be on android theme, and it looks like it works fine here at https://framework7.io/docs/button.html with android theme selected. The DESKTOP theme does highlight the buttons, but no ripple effect.
