### ISSUE TITLE
Long press to reorder/sort lists

### ISSUE THREAD

**Issue by holtwick** [framework7io/framework7#3331]
It would be great to be a able to long press on a list item (or any other element if possible) to initiate a drag operation. Most common use case would certainly be reordering a list.

Please note that iOS 13 also adds new gestures related to lists like this one that would be nice to have:

> There is also a new 2-finger gestures when looking at item lists (like emails and notes). Without changing mode, simply drag 2 fingers up or down a list of items, and iPadOS will switch into the select/edit mode and allow you to quickly select multiple items. This makes selecting longs lists of notes or emails fast and easy. [cultofmac](https://www.cultofmac.com/630294/all-the-new-gestures-coming-to-ipad-in-ipados/)

**Comment by nolimits4web** [comment]
It is now available in latest v5 release. Check this commit https://github.com/framework7io/framework7/commit/be0c243f1a4d322c8a97ebbc2c2c8f6578451973
