### ISSUE TITLE
object.assign error on ie 11

### ISSUE THREAD

**Issue by newhow** [framework7io/framework7#3334]
Previously reported as a framework7-vue only issue at #https://github.com/framework7io/framework7/issues/1430

But when I tried to open [split-view-template demo](https://framework7io.github.io/framework7-template-split-view/ ) on ie11, I still got the object.assign error. That template does not use vue.

**Comment by newhow** [comment]
follow up: actually the first three templates on the  [page](https://framework7.io/templates/) do not work on ie11.

**Comment by nolimits4web** [comment]
F7 doesn't support IE 11
