### ISSUE TITLE
Spinner does not work in Popup

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#3336]
* Framework7 version: 5.0.0-beta.19
* Framework7 Vue version: 5.0.0-beta.19
* Vue.js version: 2.6.10
* Platform and Target: Windows 10 / Chrome Web Browser

### Describe the bug
`<f7-preloader>` does not work in Popups.

### To Reproduce

Add to main component:

```html
<f7-popup tablet-fullscreen :opened="false" :animate="false">
      <f7-page>
        <f7-navbar title="Preloader"></f7-navbar>
        <f7-block>
          <f7-preloader :size="50"></f7-preloader>
        </f7-block>
      </f7-page>
    </f7-popup>
```

### Expected behavior
Preloader shown.

### Actual Behavior
Preloader not shown

### Screenshots
![does-not-work-in-popup](https://user-images.githubusercontent.com/19615586/66049457-b6847800-e52b-11e9-8a20-e1c15388f0a7.png)
![does-work-in-simple-page](https://user-images.githubusercontent.com/19615586/66049458-b71d0e80-e52b-11e9-81e3-50c369fbcb8d.png)

### Additional context
Does work in simple page:
```html
  <f7-page>
    <f7-navbar title="Preloader"></f7-navbar>
    <f7-block>
      <f7-preloader :size="50"></f7-preloader>
    </f7-block>
  </f7-page>
```

**Comment by nolimits4web** [comment]
framework7-vue is on same version?

**Comment by scriptPilot** [comment]
Updated both to 5.0.0-beta.19 - same issue.

**Comment by nolimits4web** [comment]
Would be good to see JSFiddle or live example as i can't replicate it

**Comment by scriptPilot** [comment]
Working in the page: https://jsfiddle.net/5b3qvf1n/3/
Working in the popup with theme=md: https://jsfiddle.net/5b3qvf1n/12/
Not working in the popup with theme=ios: https://jsfiddle.net/5b3qvf1n/12/

Seems to be buggy in ios only?

**Comment by scriptPilot** [comment]
@nolimits4web - Thank you! My son loves Kidoverse by the way :-D

**Comment by scriptPilot** [comment]
@nolimits4web - I figured out it's working when there is some content in the element - this will work:

```<f7-preloader>&nbsp;</f7-preloader>```

This not:

```<f7-preloader></f7-preloader>```

**Comment by nolimits4web** [comment]
> My son loves Kidoverse by the way :-D

Nice, thanks 👍 :)

>  I figured out it's working when there is some content in the element - this will work:

Will be fixed in next update
