### ISSUE TITLE
Some material icons not showing

### ISSUE THREAD

**Issue by alexandreguertin** [framework7io/framework7#3339]
Here is an example that is not working (calendar_today):

```
<f7-link
  tab-link="#tab-1"
  tab-link-active
  text="Calendar"
  icon-ios="f7:calendar"
  icon-md="material:calendar_today"
></f7-link>
```

I tried updating the fonts files too.

**Comment by nolimits4web** [comment]
Then this icon is not in the font. Closing as not related to F7

**Comment by alexandreguertin** [comment]
@nolimits4web How do you know if it is in the font or not. It is clearly in the [Material Design Icons documentation](https://material.io/resources/icons/)

**Comment by nolimits4web** [comment]
I guess if you can’t see it then it is not there :)

**Comment by alexandreguertin** [comment]
But Calendar_today is in the documentation! 
<img width="619" alt="Screen Shot 2019-10-07 at 6 21 20 AM 1" src="https://user-images.githubusercontent.com/51795734/66304294-dbca0b00-e8ca-11e9-969e-4af3451a4f07.png">

**Comment by nolimits4web** [comment]
Sure, but it still not related to Framework7
