### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by darkfrog26** [framework7io/framework7#3343]
* Framework7 version: 5.0.2
* Platform and Target: Chrome / iPhone X view

### Describe the bug
It's difficult to explain what is causing this issue as the error is unclear (attaching screenshot).

The issue was found during upgrade from 4.5.2. Everything in the app appears to be working fine, but this error appears in the console when the page is refreshed in iPhone X view (does not appear in desktop view or after loading in desktop view and then resizing to iPhone X view).

This appears to be an issue with loading the navbar (looking at the source references from the screenshot below, but I've updated the navbar based on the requirements of 5 in the migration guide:

```html
<div class="navbar main-navbar">
    <div class="navbar-bg"></div>
    <div class="navbar-inner">
        ...
    </div>
</div>
```

### Screenshots
![Screenshot from 2019-10-07 15-00-23](https://user-images.githubusercontent.com/877534/66344539-c88f5d80-e913-11e9-962d-80e2d456917a.png)

**Comment by nolimits4web** [comment]
Do you have maybe a live example or some instructions or screen recording on how to see or replicate the issue?

**Comment by darkfrog26** [comment]
Sorry for the inconvenience. I just found out there was a second navbar hidden in the code. It would probably be a good idea to provide better error handling for this though. Going ahead and closing as my issue is resolved.
