### ISSUE TITLE
Pull by refresh is not working in vuejs

### ISSUE THREAD

**Issue by jawahar273** [framework7io/framework7#3345]
* Framework7 version: 5.0.2
* Nuxt.js version: 2.9.0
* Platform and Target: Android 8 Chrome browser
* Live Link or JSFiddle: Your own document pull by refresh `https://framework7.io/vue/page.html`

### Describe the bug
Pull by refresh is not closing properly

### To Reproduce
1. Go to page 
3. Pull by refresh

### Expected behavior
Closing of pull by refresh after callback `done()`

### Actual Behavior
No closing of pull by refresh

**Comment by nolimits4web** [comment]
It was just issue in demo, not in F7

**Comment by jawahar273** [comment]
@nolimits4web I am working on a production app where the done callback is `undefined` in `@ptr:refresh="initFunction"`

**Comment by nolimits4web** [comment]
More complete example can explain more on what you are trying to do
