### ISSUE TITLE
Styling f7-navbar navbar-bg in vue

### ISSUE THREAD

**Issue by etiennea** [framework7io/framework7#3346]
* Framework7 version: 5.0.3

### Describe the bug
Impossible to style the background color of the navbar inline due to this new element containing the styling. This new element does not repect the no-hairline and when I try to use plain html class="navbar" in vue it does not work anymore

Any help would be appreciated!

**Comment by nolimits4web** [comment]
Would be good to see code example first of what have you tried and what you want to achieve

**Comment by etiennea** [comment]
I wish to have a background color set from user loaded code. 

<f7-navbar large style="background-color: red"></f7-navbar>

Would not work since then it doesn't collapse properly, the color needs to go on the navbar-bg right?

**Comment by nolimits4web** [comment]
Just use css variables in style attributes https://framework7.io/docs/navbar.html#css-variables
