### ISSUE TITLE
1px and 2px alternating separation line for list view with links

### ISSUE THREAD

**Issue by caleb87** [framework7io/framework7#3348]
* Framework7 version: 4.5.1+
* Platform and Target: Android 9/10 with Chrome

### Describe the bug
List view with LINKS uses a separation line that is 2px and then 1px alternating each row. Chrome on Windows 10 does not do this. Attached screenshot shows demo from home page doing it.

If the list is larger, it will continue to alternate. The screenshot only shows 3 links.

### To Reproduce
View any list view **with links** on Chrome/Android. Regular list views do not do this.

### Expected behavior
All lines even, 1px or 2px, but not alternating. 

### Actual Behavior
View any list view **with links** on Chrome/Android

### Screenshots
I measured the line in the "Simple Links List", and the "light" one is 1px and the other is 2px. Notice the other lists without links are all consistently 2px.
![Screenshot_20191009-113717](https://user-images.githubusercontent.com/6970514/66511093-285c4480-ea8b-11e9-9f71-6e53754a4fc8.png)

**Comment by caleb87** [comment]
I fixed it by removing the following code, but I don't know how this might affect other stuff.

```
transform-origin: 50% 100%;
transform: scaleY(calc(1 / var(--f7-device-pixel-ratio)));
```

**Comment by nolimits4web** [comment]
First of all there is no sense to test it when it runs in iframe. What you are referencing called hairlines, they MUST be 1 physical pixel size. Issue you are pointing is just a rendering bug of the current browser. And putting the fix you mentioned will make very thick borders for everyone else ;)

**Comment by caleb87** [comment]
I agree it's a bug with Chrome on Android.

Chrome/Android is the bulk of the market, so even though it's a browser bug it's worth finding a solution in my opinion. The inconsistency of the variable sized hairlines looks absolutely awful. 

My newest "solution" has not been tested enough, but so far it provides a true 1px border on 4k monitors, Pixel, iPhone. Tested in Safari and Chrome. Also opened it Edge/Firefox which also were good. 

I suspect there's a reason the background was used instead of a border, but for my purposes this works as a crutch. The only alternative is not using hairlines at all. 

Basic idea example, with randomly used #ccc for color:
```
.item-inner:after {
	background-color: rgba(0,0,0,0) !important;
	border-bottom: 0.1px solid #ccc;	
}
```
![comparison](https://user-images.githubusercontent.com/6970514/66878462-d4f86380-ef6e-11e9-9ef7-3dc499bd52ca.png)

**Comment by caleb87** [comment]
This issue affects other stuff like Action Sheet. Ionic would have been a better framework, as we don't need to spend time fixing trivial bugs.
