### ISSUE TITLE
Recent uglify changes have broken F7

### ISSUE THREAD

**Issue by tomchiverton** [framework7io/framework7#3350]
* Framework7 version: 4.5.2
* Platform and Target: iOS and Android

### Describe the bug
Recent uglify changes have broken F7

### To Reproduce
1. run npm run build-prod

### Expected behavior
builds

### Actual Behavior
Errors with 
```
ERROR in app.js from UglifyJs
`warnings` is not a supported option
```

### Additional context
Ack in forum with work around https://forum.framework7.io/t/build-error-framework7-vue-webpack-app-template/8313/2

**Comment by nolimits4web** [comment]
Framework7 doesn’t use UglifyJs for a while. Update to latest version
