### ISSUE TITLE
Click touches don't work with small drag gesture

### ISSUE THREAD

**Issue by holtwick** [framework7io/framework7#3352]
With F7 v5 I have a problem with responsiveness. As soon as I move the finger a little bit while pressing a button, it is not triggered anymore. The usual behavior would be to click on touchUp when no other gesture was triggered.

I hope I could explain the problem... the video attached shows a FAB on top of `f7-swipeout-actions` list items. If I click without moving the menu is shown. If I press, move a little bit and then release the `@click` is not fired.

Similar behavior on list items and other UI elements.

### Screenshots
https://holtwick.de/download/20191010-211716.mp4

**Comment by nolimits4web** [comment]
Hi, just increase `app.touch.touchClicksDistanceThreshold` parameter https://framework7.io/docs/app.html#app-parameters

**Comment by holtwick** [comment]
Awesome! I put it to a value of 32 and the results are much better now. Thanks!
