### ISSUE TITLE
Smart select dark theme issue

### ISSUE THREAD

**Issue by templatetuners** [framework7io/framework7#3353]
I have theme-dark class applied to .view class
On some pages I create smart select options dynamically than append to html
Looks like there are two bugs or I am doing something wrong

1. when opening smart select, I can't see selected value until I press on it
2. dark theme doesn't apply on popup

video http://screenshots.justapps.eu/Screencast_12-47_11-10-2019.mp4

**Comment by nolimits4web** [comment]
Because smart select which is opened in modal opened outside of the View where you added theme-dark. Add that class to main container or add `cssClass: 'theme-dark'` smart select parameter to make it dark theme

**Comment by templatetuners** [comment]
Check this please https://jsfiddle.net/qgm8uv7s/
Open About page than toggle after that open smart select

**Comment by nolimits4web** [comment]
Have you read what i wrote above? https://jsfiddle.net/azgLxj87/
