### ISSUE TITLE
Calendar/datepicker date can not be selected on Chrome 

### ISSUE THREAD

**Issue by manish2535** [framework7io/framework7#3355]
* Framework7 version: 4.5 and 5
* Platform and Target: Chrome Browser Version 77.0.3865.90
* Live Link or JSFiddle: https://framework7.io/docs/calendar.html

### Describe the bug
Can not select any date within a DatePicker or Calendar on Chrome. Works perfectly fine on Edge.

### To Reproduce
1. Go to https://framework7.io/docs/calendar.html on Chrome Browser.
2. Open any Datepicker or Calendar from Example and try to select a date.
3. The date can not be selected. 

### Expected behavior
The clicked date should be selected

### Actual Behavior
Nothing happens, the selected date not selected

### Screenshots
![image](https://user-images.githubusercontent.com/4663798/66706999-48e50280-ed08-11e9-9bc4-788ccbdaa070.png)

### Additional context
Found a weird thing, if I keep clicking on any date like 10 times or 15 times, it eventually selects the Date.

**Comment by nolimits4web** [comment]
Can't see anything like that. Can anyone replicate the issue?

**Comment by shastox** [comment]
У меня не воспроизводится, версия: 77.0.3865.90, как у автора

**Comment by manish2535** [comment]
This is definitely a bug,  I have now tried it in multiple desktops and also in Android phone as a Cordova App and the same problem. WOrks perfectly fine on iPhone.

**Comment by shastox** [comment]
Android 9, Chrome : no problems

**Comment by nolimits4web** [comment]
Android 8 Chrome, no issues as well

**Comment by manish2535** [comment]
Very strange.. I have also asked a couple of other friends to try it. I will update this thread asap. Thanks for looking into this.

**Comment by nolimits4web** [comment]
Closing as no one else can confirm and see it
