### ISSUE TITLE
No way to create static navbar in vue?

### ISSUE THREAD

**Issue by etiennea** [framework7io/framework7#3356]
By default all navbars in the vue version are fixed and I can't find a way to create a normal static one that scrolls with the content. Perhaps there should be a flag for that. 

Also I did a lot of custom styling thanks to the innerClass but the navbar-bg is now outside of that. Should I add a class to the navbar element instead? Or could the innerClass also apply to navbar-bg? Or could there be an innerClassNavbarBg? 

Thanks in advance.

**Comment by nolimits4web** [comment]
> By default all navbars in the vue version are fixed and I can't find a way to create a normal static one that scrolls with the content.

Add `slot="static"` to Navbar:
```
<f7-navbar slot="static">
```

> Should I add a class to the navbar element instead?

Yes.

P.S. Please, don't ask questions here. Use forum for questions
