### ISSUE TITLE
Framework7 will not disallow context menu on iOS 13 

### ISSUE THREAD

**Issue by brian-g** [framework7io/framework7#3359]
* Framework7 version: 4.4.10, 5.0.4
* Platform and Target: iOS 13 Capacitor App
* Live Link or JSFiddle: https://codepen.io/brian_glaeske/pen/rNNegeX

### Describe the bug
Despite setting the disableContextMenu: true, tapHold: false, active elements on Framework 7 will not activate if a long press is performed in a mobile browser. We have noticed this primarily on iOS 13, but also see it on some Android as well. 

### To Reproduce
Using an iOS 13 device, go to:
1. Go to 'https://codepen.io/brian_glaeske/pen/rNNegeX'
2. Tap and hold 'About' for at least 500ms 

3. Quick tap 'About'
4. Tap and hold 'Back' for at least 500ms

### Expected behavior
Expected that the navigation to the About would happen. In the second case, the Back button navigation should work as well. 

### Actual Behavior
Nothing is happening

**Comment by PatrickG** [comment]
Maybe `-webkit-user-drag: none;` solves your problem.
