### ISSUE TITLE
Text is misaligned if font size is increased in system settings

### ISSUE THREAD

**Issue by JeemBeen** [framework7io/framework7#3361]
* Framework7 version: 3.x, 4.x, 5.x 
* Platform and Target: Android Cordova

### Describe the bug
If you increase font size in Android system settings text in many components is misaligned
e.g. Buttons, Dialog.

### To Reproduce
Install Framework7 Kitchen Sink as Cordova app.

### Expected behavior
Correct position of component text e.g. Button, Dialog.

### Actual Behavior
Wrong or misaligned position of component text e.g. Button, Dialog.

### Screenshots
![Screenshot_20191016-152549](https://user-images.githubusercontent.com/48677418/66932368-c5911d00-f037-11e9-9e3d-d96fd2b9adcd.jpg)
![Screenshot_20191016-152528](https://user-images.githubusercontent.com/48677418/66932479-f709e880-f037-11e9-80da-cbe6dd9f19b1.jpg)

### Additional context
AFAIK if you increase font size also line height is increased e.g. Button MD Theme 

From:
font size: 14px
line height 36px

after you set font size to large in system settings 

To:
font size: 16.1px
line height: 41.4px

**Comment by MounicaChanda0809** [comment]
Can I fix this?
