### ISSUE TITLE
Проблема с цветом фона navbar в 5й версии: для ios и md нужно редактировать разные CSS-переменные

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3362]
### 4я версия
Чтобы определить цвет фона navbar для любой темы нужно в CSS:
```
:root{
--f7-bars-bg-color: #1EB8EA;
}
```

### 5я версия

Из-за **.ios-translucent-bars** решение из 4й версии работает только в md-теме, а в ios-теме нужно делать так:
```
:root{
--f7-bars-bg-color-rgb: 30, 184, 234;
}
```
Но это решение уже не работает в md-теме. Чтобы работало в всех темах, нужно комбинировать:
```
:root{
  --f7-bars-bg-color: #1EB8EA;
  --f7-bars-bg-color-rgb: 30, 184, 234;
}
```

**Comment by Overman775** [comment]
Можно так

```
--f7-bars-bg-color-rgb: 30, 184, 234;
--f7-bars-bg-color: rgb(var(--f7-bars-bg-color-rgb));
```

**Comment by shastox** [comment]
У меня не вопрос, как сделать цвет. У меня сообщение о том, является ли это ошибкой F7 v5 или так и было задумано.

**Comment by nolimits4web** [comment]
Это не ошибка. Так задумано, нужно указывать 2 цвета, одним цветом тут не обойтись
