### ISSUE TITLE
convertToData wrong if input.name is array

### ISSUE THREAD

**Issue by aldoexpert** [framework7io/framework7#3365]
app.form.convertToData() not valid the data convert, if have the input name as array

Example html:
&lt;form class="form-trx">
    Array: &lt;input type="text" name="bayar[CASH][]" value="12500">
    &lt;br>
    Array: &lt;input type="text" name="bayar[CASH][]" value="5000">
&lt;/form>

Result convert:
`app.form.convertToData('.form-trx');`
Just only one of array/object
bayar[CASH][]: "5000"

Where the input value of 12500 ?
Please check it
Thanks

**Comment by samodraland** [comment]
"name" nya cukup "bayar" aja dengan id yg unik
<input type="text" name="bayar" id="bayar1" value="12500">
<input type="text" name="bayar" id="bayar2" value="5000">

**Comment by aldoexpert** [comment]
thanks for mr. @samodraland for the reply
but what I hope is in the form of arrays, because there are still other fields and that allow for easy programming also using arrays and multi input
maybe mr. @nolimits4web can help for this

**Comment by alexiscm72** [comment]
Framework 7 convertToData is ignoring input type text array: for example: 
<input type="text" name="no_invoice[]" /> 
Removing [] doesn't work either. 
F7 only take as array checkbox/radio fields, this bug must be solved.

**Comment by pancaz** [comment]
> thanks for mr. @samodraland for the reply but what I hope is in the form of arrays, because there are still other fields and that allow for easy programming also using arrays and multi input maybe mr. @nolimits4web can help for this

yes i have same problems, can someone give solutions ?
