### ISSUE TITLE
WebApp - Chrome LightHouse wants font-display: auto

### ISSUE THREAD

**Issue by BananaAcid** [framework7io/framework7#3371]
Testing the PWA, chrome shows an error on:

```
Ensure text remains visible during webfont load
Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading. Learn more.

…fonts/Framework….woff2(www.url.com)
…fonts/MaterialI….woff2(www.url.com)
```
the "Learn more" link leeds to 
https://developers.google.com/web/updates/2016/02/font-display?utm_source=lighthouse&utm_medium=devtools

**Comment by nolimits4web** [comment]
Then please set it in your app styles. I am not sure it will makes sense for icon fonts

**Comment by BananaAcid** [comment]
I think, this is mainly important for icon fonts. As google states, it reserves the space for the chars. No jumping because of delayed loading. But normal text areas benefit from it as well.
