### ISSUE TITLE
lighten searchbar

### ISSUE THREAD

**Issue by vg0x01** [framework7io/framework7#3377]
**Is your feature request related to a problem? Please describe.**
search bar on iOS 12.4 appears lighter than framework7 search bar. 

**Describe the solution you'd like**
Change searchbar input bgcolor to #f0f0f0 as per iOS.

**Describe alternatives you've considered**
none

**Additional context**
Lighten searchbar to make more identical to iOS

**Comment by nolimits4web** [comment]
Please, just set it to anything you like in custom styles. Defaults are defaults here, it is also related to translucent navbar
