### ISSUE TITLE
Framework7 - Infinite Scroll top - not move scroll to the bottom on page open

### ISSUE THREAD

**Issue by rsmmukesh** [framework7io/framework7#3382]
Im using Framework7 - Infinite Scroll and applied the class "infinite-scroll-top" along with the div with class "page-content". but when i open the page the scrollbar remains at the top but it shout be at the bottom and we can scroll to up to load more. right ?

Can you specify why scrollbar in the top? is it a bug or any other procedure is there ?

**Comment by nolimits4web** [comment]
This doesn't set page scroll to bottom. You need to set initial page content scroll on your own

**Comment by rsmmukesh** [comment]
But actually scrollbar should be at the bottom like messages. Now we have to move down then again we have to move up. anyway thanks for the reply.
I have tried some jquery codes but not working, How to move scroll bar to bottom in framework7 ?

**Comment by nolimits4web** [comment]
You need to set it programmatically https://developer.mozilla.org/docs/Web/API/Element/scrollTop
