### ISSUE TITLE
f7-searchbar vue component will not render the disable-link-text attribute

### ISSUE THREAD

**Issue by raspenberg** [framework7io/framework7#3385]
* Framework7 version: v5.1.0
* Vue.js version: ^2.6.10
* Platform and Target: All

### The bug
The f7-searchbar attribute **disable-link-text** seems not to be working correctly. It does not matter what text you enter, it will still display the text **Cancel**

### To Reproduce
1. Add the Vue component f7-searchbar to your code and set the **disable-link-text** attribute to someting other than _Cancel_
```
    <f7-searchbar :disable-link-text="currentLanguage.search.cencel"
                  :placeholder="currentLanguage.search.placeholder"
                  :clear-button="true"></f7-searchbar>
```
2. Go to your test environment.
3. Test the component by writing something in the search box
4. Check out the rendered cancel-text

### Expected behavior
I expect my text to be rendered instead of the text _Cancel_

### Actual Behavior
Even if I set the **disable-link-text** to someting else, the text displayed will be 

> Cancel

**Comment by nolimits4web** [comment]
It must be `disable-button-text` https://framework7.io/vue/searchbar.html#searchbar-properties

**Comment by raspenberg** [comment]
Ok, thanks. 
**But** the code I entered was from all the **examples on that exact page**.
