### ISSUE TITLE
Overswipe "delete" button does not accept color property

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#3397]
In the latest version of F7Vue, the overswipe button does not accept any color property, when property delete is true.

**Comment by nolimits4web** [comment]
Delete button is always red and its background controlled by `--f7-swipeout-delete-button-bg-color` CSS prop, you can change this prop to any color you need

**Comment by scriptPilot** [comment]
Thank you for the response @nolimits4web - I thought deleting the entry after swipeout must not be allways means to delete the entry ... for example overswipe to move to another list ... but ok, is a workaround :-)
