### ISSUE TITLE
Gauge value text not visible in dark mode

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#3398]
Gauge value text is not visible in dark mode.

**Comment by nolimits4web** [comment]
It is for demo. Gauge value text accepts text color value that you can set to whatever you need

**Comment by scriptPilot** [comment]
@nolimits4web - Ok, thank you for the repsonse. I thought, by default, all F7-Vue elements should be displayed well in light and dark mode without custom CSS.
