### ISSUE TITLE
app.js not build successful while running npm run dev

### ISSUE THREAD

**Issue by tharun777** [framework7io/framework7#3402]
below are the broken code after successful build.

(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('D:ramework7
ode_modules
ollup-plugin-vue
untime
ormalize.js')) :
  typeof define === 'function' && define.amd ? define(['D:ramework7
ode_modules
ollup-plugin-vue
untime
ormalize.js'], factory) :
  (global = global || self, global.app = factory(global.__vue_normalize__));
}(this, (function (__vue_normalize__) { 'use strict';

  __vue_normalize__ = __vue_normalize__ && __vue_normalize__.hasOwnProperty('default') ? __vue_normalize__['default'] : __vue_normalize__;

please give copy of app.js for vue or fix the bug , hope the information is clear now

**Comment by nolimits4web** [comment]
There is something wrong in your setup, use Framework7 CLI to setup app

**Comment by tharun777** [comment]
how can you close without fixing the issue ?

**Comment by tharun777** [comment]
how can you close without fixing the issue ?
