### ISSUE TITLE
Photo Browser Paging number missing when @click open the photo by index

### ISSUE THREAD

**Issue by lauchogit** [framework7io/framework7#3405]
In my modified code, i try to open 2nd photo by:
`@click="openPopupDark('1')`

The modified function would be:
```
openPopupDark: function (whichPhoto) {
	const self = this;
	self.popupDark.open(whichPhoto);
},
```

When it triggers the photo browser, the paging number is missing.
*if user swipe to another photo, it paging will appear
![image](https://user-images.githubusercontent.com/37097224/69206976-438d9a00-0b89-11ea-8370-86446bf14bf6.png)

**Comment by nolimits4web** [comment]
Update F7 to latest version
