### ISSUE TITLE
Photo Browser image not showing when @click open the first photo by index

### ISSUE THREAD

**Issue by lauchogit** [framework7io/framework7#3406]
I try to modify the function to open the first photo with:
`@click="openPopupDark('0')`

The function is
```
openPopupDark: function (whichPhoto) {
	const self = this;
	self.popupDark.open(whichPhoto);
},
```

the photo browser will be triggered but show nothing, unless the user tries to swipe, then the photo will appear.
*this only happen to photo with index 0, the other index (1,2,3..) is fine.
*the missing paging number issue is submitted at #3405 
![image](https://user-images.githubusercontent.com/37097224/69207236-0b3a8b80-0b8a-11ea-80e7-e4d58b94b9eb.png)
![image](https://user-images.githubusercontent.com/37097224/69207309-40df7480-0b8a-11ea-8c42-5cb54a9b5bb7.png)

**Comment by nolimits4web** [comment]
- Update to F7 to latest version
- Photo index parameter must be a number
