### ISSUE TITLE
Перекрытие chevron-right списка элементом sortable-handler

### ISSUE THREAD

**Issue by AlexZubov** [framework7io/framework7#3409]
**Проблема:**
При включении сортировки списка типа ist links-list и подобных, где имеется chevron-right, элемент "гамбургер" сортировки накладывается на chevron.
пример:
![2019-11-21_09-26-10](https://user-images.githubusercontent.com/27336108/69313100-af333e00-0c41-11ea-8575-c8338adb1290.png)
структура:
```
<a class="link sortable-toggle" data-sortable=".sortable">Сортировать</a>
<div class="list links-list sortable sortable-tap-hold">
  <ul>
    <li>
      <a href="#">Link Item 1</a>
     <div class="sortable-handler"></div>
    </li>
    <li>
      <a href="#">Link Item 2</a>
     <div class="sortable-handler"></div>
    </li>
    <li>
      <a href="#">Link Item 3</a>
     <div class="sortable-handler"></div>
    </li>
    ...
  </ul>
</div>
```

**Предлагаю добавить дополнительный стиль, который решает проблему:**
```
.list.sortable.sortable-enabled a.item-link:before {
    visibility: hidden;
}
```

**Comment by nolimits4web** [comment]
Fixed in f49faf83e2b07c937b30c837def85351e396b634
