### ISSUE TITLE
Support lazy-loading for message contents

### ISSUE THREAD

**Issue by kraln** [framework7io/framework7#3411]
Related: #473

* Framework7 version: 4
* Platform and Target: Cordova App

### Describe the bug
Images with lazy do not work when embedded in messages

### To Reproduce
Add some messages with images with lazy class and data-src

### Expected behavior
Images load lazily

### Actual Behavior
Nothing

### Additional context
In the original, now closed ticket, the issue was for adding new messages. However, in my case, I need to re-create the chat history from a local cache on app load. Here, it would be nice if those historical images didn't immediately trigger a http request, as it starts to get really slow with a huge chat history. I am creating the messages in bulk with addMessages.

### Alternative fix
ability to re-initalize the lazy feature after creating the dom elements.

**Comment by kraln** [comment]
Workaround:

Call app.lazy.create($$('.messages-content')); after creating the messages.

**Comment by nolimits4web** [comment]
It is already supported, you just need (as on any other page where there is no lazy images on initial load) to init it with `app.lazy.create` as you already did
