### ISSUE TITLE
Top safe areas in portrait mode not always added properly

### ISSUE THREAD

**Issue by brainfoolong** [framework7io/framework7#3413]
I  have the following setup:
* Framework7 5.1.3 Core
* Installed as PWA in fullscreen mode
* Android Chrome: `5.0 (Linux; Android 10; MI 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36`
* Xiaomi Mi 9 with a notch
* Design is locked to `theme: 'md'`
* I have a navbar in the app

When i first open up my app, the safe area above the navbar is added correctly, the notch is not overlapping my content/navbar.

However, after a reload with just swiping down, the page reloads and the safe areas are gone, as long is i do not interact with some inputs. As soon as i focus and input, the safe areas are added and content is slighty shifted down. 

After a reload it should also be like on first page load, the safe areas should be there without interaction.

Is there anything i can configure to fix this? I don't want to use hacks by firing some events in the background.

Here is a animated screen record to show the behaviour.

![framework7-safeareas](https://user-images.githubusercontent.com/1684236/69414467-1e2c9780-0d13-11ea-90cc-0a03fdea988f.gif)

**Comment by nolimits4web** [comment]
Sorry, but F7 doesn't do anything with safe areas, they are handled by browser. I believe issue can be with your browser that doesn't set correctly safe areas when app reloaded. Closing as not really related to F7 itself

**Comment by brainfoolong** [comment]
@nolimits4web Ok thank you. Than probably the documentation should be updated. I quote: `On devices with safe areas (like with top screen notch), app UI must include additional top/bottom spacing (to consider top notch and new bottom bar) in portrait orientation and additional left/righ spacing (to consider left/right notch) in landscape orientation. In portrait orientation Framework7 will do required styles modifications automatically`.

On page: https://framework7.io/docs/safe-areas.html

**Comment by nolimits4web** [comment]
Everything is correct in docs)

**Comment by brainfoolong** [comment]
I understand, from the docs, that F7 does styling for safe areas beacuse of `In portrait orientation Framework7 will do required styles modifications automatically...`. But you've said it doesn't, so i am confused. But ok.

**Comment by nolimits4web** [comment]
It does, in your case issue is in the browser that doesn’t report that safe areas must be applied
