### ISSUE TITLE
vue f7-statusbar component is broken

### ISSUE THREAD

**Issue by BananaAcid** [framework7io/framework7#3414]
Upgraded to latest framework7. Recompiling, it triggers an error:

```
[Vue warn]: Unknown custom element: <f7-statusbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <App> at src/app.vue
       <Root>
```

btw. the homepage search, searching "statusbar" leads to a broken page.

Versions:
    framework7: 5.1.3
    framework7-vue: 5.1.3

**Comment by nolimits4web** [comment]
https://blog.framework7.io/migration-to-framework7-v5-1374257bb5a7?source=collection_home---4------0-----------------------

**Comment by BananaAcid** [comment]
Seriously? Then you should probably not remove the statusbar page, but add a note on that page that leads to migration guide! You should also take into account, there might be people around, still having a project with a codebase using F7 v4.

**Comment by nolimits4web** [comment]
Seriously 😎 http://v4.framework7.io/
