### ISSUE TITLE
Can't $setState recursively inside $setState callback

### ISSUE THREAD

**Issue by dexter0323** [framework7io/framework7#3421]
* Framework7 version: current

### Describe the bug
I can't $setStates recursively  

### To Reproduce
Open this link https://codepen.io/djsambo/pen/dyyxoqj

### Expected behavior
It should let me set states recursively 

### Actual Behavior

**Comment by shastox** [comment]
Потому, что вы не поняли как работает обновление. Нужно так:

this.$setState();
this.$setState();

и на самом деле можно: nextFrame() или nextTick():

this.$setState().then(function() {
...nextTick(...$setState)...
})

**Comment by thekingrenz23** [comment]
> Потому, что вы не поняли как работает обновление. Нужно так:
> 
> this.$setState();
> this.$setState();
> 
> и на самом деле можно: nextFrame() или nextTick():
> 
> this.$setState().then(function() {
> ...nextTick(...$setState)...
> })

 Please translate this to english
