### ISSUE TITLE
pull-to-refresh and infinite scroll create 2 <span class="preloader-inner"> in html result in double loader image by md theme.

### ISSUE THREAD

**Issue by woodman250** [framework7io/framework7#3423]
* Framework7 version: [5.1.3]
* Vue.js version: [3.0.0]
* Platform and Target: [Chrome browser]
* Live Link or JSFiddle: 
https://framework7.io/vue/page.html#infinite-scroll
NOTE: switch the theme to android at the top of the fake phone.

### Describe the bug
pull-to-refresh and infinite scroll create 2 <span class="preloader-inner"> in html result in double loader image by md theme.

**Comment by nolimits4web** [comment]
I can't see 2 loaders on that page

**Comment by woodman250** [comment]
Append the image I snaped.
![avatar](https://github.com/woodman250/Image-storage/blob/master/f7-bug.png?raw=true)

**Comment by woodman250** [comment]
Why close this issue? The problem is obvious in the image. Cloud you give some reason?

**Comment by fatihbatal** [comment]
@woodman250 It looks like Vladimir fixed it 3 days ago, a day before your last message. 
Still, I got curious and checked the link you gave and I can confirm that Android preview still has the issue of double preloaders both on Infinite Scroll example and Pull-to-Refresh.
Yet, this might have to do with the preview pages were not updated to reflect the most recent changes of the repo. 
I just wanted to weigh in here and would say that his time spent on fixes and updates on Framework7 itself is way more valuable for all of us than updating the preview pages of the website; don't you think?

**Comment by woodman250** [comment]
@fatihbatal Thanks your reply. I totally agree your words. Actually, I found this problem in my app when updating framework7 from 1.7 to lastest version. Then I found same problem in android demo example of website. All in one, framework7  save lots of time to me. I hope it will be better and better.

**Comment by woodman250** [comment]
@fatihbatal I rebuilded my app several minutes ago. The problem disappeared.
