### ISSUE TITLE
no sort event thrown when using virtual list

### ISSUE THREAD

**Issue by dgurza** [framework7io/framework7#3426]
Framework7 version: seen on 4.1.0, 4.2.0 and 4.5.2
Vue.js version: 2.6.10
Platform and Target: electron, ios theme
Live Link or JSFiddle: https://jsfiddle.net/4h7nfp5m/ (ADDED TO THE DEFAULT ROUTE 404)

when creating a sortable virtual list the event for on sort does not fire

To Reproduce
1. create a sortable virtual list
2. bind some action to the @sortable:sort event
3. Sort the list
4. no event fires

Expected behavior
I would expect the event sortable:sort event to fire

Actual Behavior
the event does not fire

Screenshots
see Jfiddle

Additional context
this featured worked before moving from V1 to V4

**Comment by nolimits4web** [comment]
Because it should be used correctly, and VL is intended to render data dynamically, not with existing list items. Here is the example https://github.com/framework7io/framework7/blob/master/kitchen-sink/vue/src/pages/virtual-list.vue

Also, on VL, `:sortable-move-items="false"` should be set

**Comment by dgurza** [comment]
I took the example that you linked to and replaced the list in my previous JSFiddle with it.
I made it sortable and again it seems like the onSort event doesn't fire. 

Please see https://jsfiddle.net/owgp2b7e/5/ I as with previous example I placed the list in the Default 404 page 

Any help would be really appreciated
