### ISSUE TITLE
Photo browser doesn't open properly in standalone mode on Safari

### ISSUE THREAD

**Issue by theryan722** [framework7io/framework7#3429]
* Framework7 version: 5.1.3
* Platform and Target: Safari 13.0.3 on macOS 10.14.6

### Describe the bug
Opening a photobrowser in standalone mode on safari displays the navbar of the photobrowser at the bottom of the screen. If you switch desktops or minimize/maximize the window is opens fully.

This only happens on Safari, on every other browser it works fine.

### To Reproduce
1. Instantiate a Framework7 instance (I'm using Framework7 core, not vue/react).
2. Instantiate a photobrowser instance in standalone mode and open it. Here is the example code for a standalone phtobrowser from the documentation (https://framework7.io/docs/photo-browser.html#examples):

```
var myPhotoBrowserStandalone = app.photoBrowser.create({
    photos : [
        'https://cdn.framework7.io/placeholder/sports-1024x1024-1.jpg',
        'https://cdn.framework7.io/placeholder/sports-1024x1024-2.jpg',
        'https://cdn.framework7.io/placeholder/sports-1024x1024-3.jpg',
    ]
});
myPhotoBrowserStandalone.open();
```

### Expected behavior
The photo browser to displays in full screen.
It should look like this:
![Screen Shot 2019-12-01 at 21 37 37](https://user-images.githubusercontent.com/11343869/69926528-d4fee500-1482-11ea-9e95-6ac308185304.png)

### Actual Behavior
The photo browser flashes and then only displays the navbar/top portion of the image on the bottom of the page.

### Screenshots
![Screen Shot 2019-12-01 at 19 53 50](https://user-images.githubusercontent.com/11343869/69926481-a84acd80-1482-11ea-89b6-5fcb8caf3ccd.png)

**Comment by theryan722** [comment]
A hacky fix I found for it is to immediately hide/show the photobrowser element after calling `myPhotoBrowserStandalone.open();`.

For example:

```
myPhotoBrowserStandalone.open();
$$(myPhotoBrowserStandalone.el).hide();
$$(myPhotoBrowserStandalone.el).show();
```
This appears to work for me.

**Comment by nolimits4web** [comment]
I can't see any issues on macOs safari 13.0.3 at standalone photo browser at https://framework7.io/kitchen-sink/core/?theme=md Can anyone else see such?

**Comment by nolimits4web** [comment]
And macOs is 10.15.1

**Comment by theryan722** [comment]
Maybe it's just me then haha. It didn't happen all the time: just when you opened another photobrowser later without refreshing the page. Again, this could just be the way I'm handling things, as more testing on the example website seems to work okay for me.
