### ISSUE TITLE
there is no f7-vue components declare files on typescript

### ISSUE THREAD

**Issue by AlwaysLoveme** [framework7io/framework7#3431]
* Framework7 version: 5.1.3]
* Vue.js version: [2.6.10]
* Platform and Target: [Chrome browser]

### Describe the bug
i am using framework7-vue width typescript, so import f7 like this, 'import Framework7Vue from 'framework7-vue/framework7-vue.esm.bundle.js'', but i got some error when i run my project:
"Could not find a declaration file for module './components/view'. 'E:/NEWSALE/newsale/node_modules/framework7-vue/components/view.js' implicitly has an 'any' type" and so on .
it means all components do not have own declaration file, would you please add components declaration files in f7-vue, thanks a lot!

### Expected behavior
running have no errors width typescript.

### Actual Behavior
got typescript errors

**Comment by Kukks** [comment]
Having the same issue.
