### ISSUE TITLE
Navigation bar issues on iPad

### ISSUE THREAD

**Issue by holtwick** [framework7io/framework7#3432]
Since the latest major update the top navigation is missing as soon as I open detail pages:

![Screen Shot 2019-12-03 at 11 22 18](https://user-images.githubusercontent.com/49557/70042587-6f644300-15bf-11ea-9f9c-dabb8ec7c6d5.png)

This problem continues to exist, when I remove `ptr`.

**Comment by nolimits4web** [comment]
Are you sure nothing is missing? What is the HTML layout of pages?

**Comment by holtwick** [comment]
Please take a look here e.g. by setting device emulation in your browser to `iPad`:
https://m.onepile.app/

It looks like it is sliding the navigation as it would on regular iPhone like view:
<img width="1440" alt="CleanShot 2019-12-04 at 09 30 11@2x" src="https://user-images.githubusercontent.com/49557/70126209-da258500-1678-11ea-975b-ca4a21e57344.png">

**Comment by nolimits4web** [comment]
Ok, see where it comes from, will fix it

**Comment by nolimits4web** [comment]
Pushed fix in 460759d1. Wondering can you check does it fix issue on your side?

**Comment by holtwick** [comment]
I tried to test it by integrating the `master` temporarily via `npm link framework7 framework7-vue` into my project, but failed. Do you have a tip, what would be the best way to test it?

**Comment by nolimits4web** [comment]
Yeah, it should be built first locally and use this instead. Or can you post the layout of your master page so I check it by my self

**Comment by nolimits4web** [comment]
Ok, i can confirm, this fix fixed the issue. So it will arrive in the next update i will release this weekend

**Comment by holtwick** [comment]
Thanks for all the great work @nolimits4web ! Today I didn't find the time to test it.

**Comment by holtwick** [comment]
I can confirm it is working now as of Framework7 5.2.0. Thanks!
