### ISSUE TITLE
Gauge colors are inverted when the gauge type is semi-circle

### ISSUE THREAD

**Issue by DivadNojnarg** [framework7io/framework7#3437]
* Framework7 version: [5.1.3] (latest)
* Platform and Target: [iOS13, Android, desktop safari (latest), desktop chrome (latest)]

### Describe the bug
Gauge colors are inverted when the gauge type is semi-circle.

### Expected behavior
Assuming a is the current percentage and b = 100-a the remaining part. a should be coloured but not b

### Actual Behavior
b is coloured and not a (see left side of the screenshot)

After quickly exploring the HTML inspector:

```html
<path class="gauge-back-semi" d="M195,100 a1,1 0 0,0 -190,0" stroke="#eeeeee" stroke-width="10" fill="transparent"></path>
```

This part should have `stroke="#2196f3"`

```html
<path class="gauge-front-semi" d="M195,100 a1,1 0 0,0 -190,0" stroke="#2196f3" stroke-width="10" stroke-dasharray="298.45130209103036" stroke-dashoffset="-149.22565104551518" fill="none"></path>
```
This part should have `stroke="#eeeeee"`

When calling the gauge, I followed exactly the documentation. 

### Screenshots
![Screenshot 2019-12-05 at 12 59 30](https://user-images.githubusercontent.com/18291543/70236535-66ad7180-1765-11ea-8cac-9ff376be46e4.png)

### Additional context
Related issue: https://forum.framework7.io/t/gauge-colors-are-inverted-on-ios/4664

**Comment by nolimits4web** [comment]
Where do you see this, i can see all correct in kitchen sink:

<img width="1023" alt="gauge" src="https://user-images.githubusercontent.com/999588/70263170-c9732d00-17a6-11ea-8f1a-a96e36a77978.png">

**Comment by DivadNojnarg** [comment]
In a personal app with only 1 gauge. I am using the framework7.bundle.min.css and framework7.bundle.min.js. I also noticed that the update function does not work as expected, but only with semicircle gauges.

![Hnet com-image](https://user-images.githubusercontent.com/18291543/70305671-446b3080-1805-11ea-9f70-ea1e4434d65e.gif)

It works well with circle gauges.

![Hnet com-image copy](https://user-images.githubusercontent.com/18291543/70305787-8c8a5300-1805-11ea-8737-47ab1262f9ae.gif)
