### ISSUE TITLE
Pagination Footer is not working

### ISSUE THREAD

**Issue by dexter0323** [framework7io/framework7#3438]
* Framework7 version: Current version 

### Describe the bug
Pagination Footer is not working, even in your explanation page it does not work.
https://framework7.io/docs/data-table.html#pagination-footer

### To Reproduce
1. Create a Data Table with pagination footer using the exact code you provide in the link
https://framework7.io/docs/data-table.html#pagination-footer
2. I try using the initialization class data-table-init
3.Also with app.dataTable.create(parameters) and nothing

### Expected behavior
Be able to paginate and select per page

Спасибо

**Comment by nolimits4web** [comment]
This is just a UI, without any paging logic. Paging logic supposed to be implemented manually
