### ISSUE TITLE
calendar in zh-cn locale mode

### ISSUE THREAD

**Issue by SSXiao** [framework7io/framework7#3443]
![image](https://user-images.githubusercontent.com/20103801/70595830-47a85700-1c1f-11ea-9d9a-a05383489783.png)

**Comment by SSXiao** [comment]
do not need the chinese char '日'. but there is no formatter for day of month in calendar

**Comment by nolimits4web** [comment]
This is how browser formats the day by default  🤷‍♂️
```
new Intl.DateTimeFormat('zh-cn', { day: 'numeric' }).format(new Date());
// -> 11日
```

**Comment by nolimits4web** [comment]
Will add ability to specify custom formatters

**Comment by SSXiao** [comment]
Thanks very much for you working! Waiting for the new ability! Now users can use 'en-US' mode and then specify weekdays and months formatters(monthNames, dayNames) temporarily.😁
