### ISSUE TITLE
No sort event thrown when using virtual list #3426

### ISSUE THREAD

**Issue by dgurza** [framework7io/framework7#3444]
Please look here for context https://github.com/framework7io/framework7/issues/3426

I took the example that you linked to and replaced the list in my previous JSFiddle with it.
I made it sortable and again it seems like the onSort event doesn't fire. 

Please see https://jsfiddle.net/owgp2b7e/5/ I as with previous example I placed the list in the Default 404 page 

Any help would be really appreciated

**Comment by nolimits4web** [comment]
Just add `@sortable:sort="onSort"` to `<f7-list>` https://jsfiddle.net/5bmrzeox/
And update to v5 https://jsfiddle.net/p08u69qL/
