### ISSUE TITLE
Text editor fast click issue again?

### ISSUE THREAD

**Issue by templatetuners** [framework7io/framework7#3446]
I had this issue with v2 or v3 in past.. in my cordova app i use trumbowyg text editor. In iOS there was a problem on typing, fixed with `class="no-fastclick"`

Updated now to F7 5.1.0 and in iOS 13 when i press on any buttons nothing happens, **fastClicks** disabled
Tried your text editor, same thing.

https://www.youtube.com/watch?v=aaeR7wEgDcA

Installed keyboard plugin too

Is this is a F7 bug or cordova or iOS..? thanks

**Comment by shastox** [comment]
wkwebview?

**Comment by nolimits4web** [comment]
@templatetuners make sure you are using WKWebView in your cordova app
