### ISSUE TITLE
Framework7 router is intercepting links outside the f7-app.

### ISSUE THREAD

**Issue by mishraas** [framework7io/framework7#3451]
* Framework7 version: 5.1.3
* Platform and Target: MacOSX and Chrome browser (latest versions)
* Live Link or JSFiddle: https://jsfiddle.net/ashu2289/qkas4e73/22/

### Description
Link navigations are captured by F7 router even if the link is not under F7 app root element.

### To Reproduce
1. Create an anchor tag(link) outside the framework 7 root component(f7-app)[similar to any 3rd party components which gets appended in body section on page load].
2. Click on the link.

### Expected behavior
F7 router should not intercept the link and let the navigation happen (similar to prevent-router/external config within F7 app).

### Actual Behavior
Link url is appended to the current url in browser navigation bar and the F7 router is unable to resolve the url thus 404.

**Comment by nolimits4web** [comment]
Yes, it intercepts all links, and it is by design. You can control it using `externalLinks` app parameter https://framework7.io/docs/app.html#app-parameters, by adding there for example `.third-party-external-client a` selector
