### ISSUE TITLE
a view have only one Routable Tabs??

### ISSUE THREAD

**Issue by love48280** [framework7io/framework7#3453]
* Framework7 version: [v4.4.3]

### Describe
in a routable tabs page  have a `<a href="/xx">`
when click the `<a>`, i hope to the other routable tabs page;

now the problem is ： click `<a>` can't to the page;
when I delete the tabs attribute in the route,  click `<a>`  is can to the page

is there a problem with my configuration, or don't support a routable tabs page to other routable tabs page

If support , can you give me an example， thank you !!

**Comment by shastox** [comment]
`in a routable tabs page have a <a href="/xx">
when click the <a>, i hope to the other routable tabs page;`
There are no error in current behaviour. Read : https://forum.framework7.io/t/tab-view/8817

**Comment by love48280** [comment]
thank you!! I've found own mistakes..

**Comment by nolimits4web** [comment]
Closing as seems to be resolved
