### ISSUE TITLE
Restrict width of the main view in large screens

### ISSUE THREAD

**Issue by paulovieira** [framework7io/framework7#3454]
**Is your feature request related to a problem? Please describe.**

I would like to suggest an improvement to framework7 apps when they are used in "large" screens (example: when the viewport width is >= 1920px).

In those cases it might be better to actually restrict the width of the main view a bit to provide a better user experience, otherwise the user has to make an extra effort to find the important elements of the application. 

This is a well known fact in design (for instance, a basic concept in typography is "line lenght" - the lines of text should not be too long, otherwise it will harder to read: https://en.wikipedia.org/wiki/Line_length)

A pratical example: the web version of the (official) WhatsApp. The printscreens below show how it looks like in 1920px and 1366px. In the larger screen the main container doesn't take all the available width.

In 1920px:
![whatsapp_w1920](https://user-images.githubusercontent.com/2184309/70994769-d527f300-20c6-11ea-9ab0-a50289d48964.jpg)

In 1366px:
![whatsapp_w1366](https://user-images.githubusercontent.com/2184309/70994772-d9541080-20c6-11ea-9cf4-03de7dccd1a3.jpg)

This effect is relatively easy to achieve with a bit of user defined css, like this:
```css
    body {
      display: flex;
      justify-content: center;
    }

    .main-view {
      max-width: 1500px;
    }
```

But I think it would make sense for F7 to have an official css class and instructions. The fact that there is an official theme for desktop (Aurora) is a proof that this kind of customization should be part of the library.

Thanks.

**Comment by nolimits4web** [comment]
Sorry, but I can't put it into the core, as it is a pretty custom thing which highly depends on design requirements, and it is far not every web app and especially desktop/mobile app have such size limit. And anyway it can be done easily if required with just couple of extra lines of custom CSS
