### ISSUE TITLE
Попытка прокрутки при клике на Expandable Cards

### ISSUE THREAD

**Issue by zavodteplic** [framework7io/framework7#3457]
**Is your feature request related to a problem? Please describe.**
Это багом не назовешь, но исключить возможность появления следующего поведения думаю стоит: при открытии Expandable Cards и возможном прокручивании экрана во время открытия (например медленный телефон или очень шустрый пользователь) карточка  раскрывается не на весь экран - остается непокрытая область прокрутки. 

**Describe the solution you'd like**
Расчет области вести позднее или поставить запрет на scroll

**Describe alternatives you've considered**

**Additional context**
[Видео](https://photos.app.goo.gl/R6wB9SyUuUqMePVX7)

**Comment by srbala** [comment]
English Please. This will help the community to participate

**Comment by peterlevel1** [comment]
It would be nice using English as the communication language.
