### ISSUE TITLE
ActionSheet Dialog Remains Open when I navigate back to the page -Solved

### ISSUE THREAD

**Issue by chrismuiruriz** [framework7io/framework7#3460]
This issue has been bothering me for the last few weeks.

![App Flow](https://i.ibb.co/VJ9dhH0/flow.jpg)

I have an ActionSheet on my home component page with buttons as seen below: the code works fine when the page loads.

```js
var self_ = this;
var clientListItemActionSheet = self_.$app.actions.create({
    buttons: [
        {
            text: 'Actions',
            label: true
        },
        {
            text: 'Team',
            onClick: function () {
                clientListItemActionSheet.close();
                mainView.router.navigate('/crew/' + selectedClientItemId + '/' + selectedClientItemRev + '');
            }
        },
        {
            text: 'Packing List',
            onClick: function () {
                clientListItemActionSheet.close();
                mainView.router.navigate('/list/' + selectedClientItemId + '/' + selectedClientItemRev + '');
            }
        }
    ]
});
```
This code works perfectly, I am able to navigate to the list component page

```js
mainView.router.navigate('/list/' + selectedClientItemId + '/' + selectedClientItemRev + '');
```

But when I go back to the home component page from the list component page and open the ActionSheet then navigate to the list component page again, the Action Sheet remains open and visible on the list page.

This is the code for opening the ActionSheet

```js
clientListItemActionSheet.open();
```

I have tried this in both Framework7 5.1.0 and 5.2.0 and the issue is the same. 
My code is inside the ``pageInit`` method

```
...
on: {
    pageInit: function () {
        //My code us here 
    }
}
```

Simplified Question: Why does my ActionSheet remain open when I navigate to the list page after navigating back to the home page from the list page.

Please help!

**Comment by nolimits4web** [comment]
* You shouldn't call `clientListItemActionSheet.close();` in button handler as it close actions automatically on button click
* Maybe there are some errors in browser console? Or how do you open it, issue somewhere there. It don't open itself

**Comment by chrismuiruriz** [comment]
There are no errors in the console! It's just weird.

**Comment by chrismuiruriz** [comment]
It seems like the method to close the actionsheet is not triggered.

**Comment by chrismuiruriz** [comment]
Finally, I was able to solve this.

I was using this code to open the ActionSheet:
```js
$$('body').on('click', '.client-list-item', function (e) {
    e.preventDefault();
    clientListItemActionSheet.open();
});
```

I updated the code to this:
```js
$$('[data-el-page="home"]').on('click', '.client-list-item', function (e) {
    e.preventDefault();
    clientListItemActionSheet.open();
});
```

And just like that, the issue was resolved. I added the ``data-el-page`` attribute to the element with the class ``page`` and used it instead of the body.

```html
<template>
    <div class="page" data-el-page="home">
        <!-- My code here -->
     </div>
</template>
```

Thanks @nolimits4web your comment helped.
