### ISSUE TITLE
Center Toast's text alignment

### ISSUE THREAD

**Issue by lauchogit** [framework7io/framework7#3461]
1. For "toast on centre", if the sentence is too long, the text is left-aligned.
 I wish to centre-position the text.
![image](https://user-images.githubusercontent.com/37097224/71464143-90e9d080-27f3-11ea-918b-f8192db222d5.png)
Below is my temporary solution
Solution 1: use `&nbsp;` to replace the space. e.g. `Download&nbsp;completed`
Solution 2: I customise in CSS like below,
```
  <style type="text/css">
    .toast {
     text-align: center;
   }
 </style>
```
![image](https://user-images.githubusercontent.com/37097224/71494061-241c1800-287f-11ea-8637-759021936d71.png)

**Comment by nolimits4web** [comment]
Ref #3469
