### ISSUE TITLE
IOS calendar/datepicker invalid date selection

### ISSUE THREAD

**Issue by chaiwei** [framework7io/framework7#3462]
* Framework7 version: 5.2.0
* Platform and Target: IOS Safari Browser
* Live Link or JSFiddle: https://framework7.io/docs-demos/core/calendar.html?theme=ios

### Describe the bug
Invalid date selection for Jan-Feb on year 1970 and before.
I tried to select "01 Jan 1970" but the calendar return "01 Feb 1970".

### To Reproduce
1. Go to https://framework7.io/docs-demos/core/calendar.html?theme=ios with IOS safari browser
2. Click on datepicker year, select year 1970 or before 
3. Click on datepicker month, select month January
4. Click on date 01, and the datepicker will return 01 Feb 1970

### Expected behavior
 It should return date on 01 Jan 1970

### Actual Behavior
The datepicker return 01 Feb 1970

### Screenshots
![calendar-ios-issue](https://user-images.githubusercontent.com/423006/71512819-bf8aa880-28d2-11ea-84b2-b69ed0265625.gif)

### Additional context
Seems the bug only occur on IOS device, having no issue on Android and Window PC.

**Comment by chaiwei** [comment]
Any one else have encounter this?

**Comment by marcopesce** [comment]
This bug is present only on the web version (I suppose due to some rounding error). If you compile to a native iOS app you will get the **native calendar** picker that do not have this issue.
