### ISSUE TITLE
CSS will-change

### ISSUE THREAD

**Issue by holtwick** [framework7io/framework7#3465]
Not a bug but something I stumbled upon and think it could be useful for F7 in performance critical animations: https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

**Comment by Overman775** [comment]
This property shouldnt be overused, especially on samrtphones, using this on too many elements can cause performance issues

**Comment by nolimits4web** [comment]
This is added on modals in 0802378ad401559807be07c64cf0f5177eba0dfd
