### ISSUE TITLE
Bottom Toast's text alignment

### ISSUE THREAD

**Issue by lauchogit** [framework7io/framework7#3469]
1. how to text-align-center for bottom toast? 
![image](https://user-images.githubusercontent.com/37097224/71494653-b45c5c00-2883-11ea-9761-833d57a72b8c.png)

2. if the page width is large enough, bottom/top toast will be left-align. How to make it center-align?
![image](https://user-images.githubusercontent.com/37097224/71494674-cfc76700-2883-11ea-9235-be00f865fe31.png)

**Comment by Overman775** [comment]
**1**
```
.toast-text {
    width: 100%;
    text-align: center;
}
```
**2**
```
var app = new Framework7({
  toast: {
    position: 'center',
  }
});

.toast{
  bottom: calc(8px + var(--f7-safe-area-bottom)) !important;
}
```
**3**
Questions are asked on the forum, not on the github

**Comment by nolimits4web** [comment]
As @Overman775 suggested just use custom styles to tweak it as you need
