### ISSUE TITLE
Page header disappears while using custom transition effect

### ISSUE THREAD

**Issue by VaqifKazim** [framework7io/framework7#3470]
* Framework7 version: 5.3.0
* React.js version: 16.5.0
* Platform and Target: Desktop, Chrome 78.0.3904.87, Mozilla Firefox 71.0
* Live Link or JSFiddle: Bug appears even at Framework7 React Kitchen Sink (only iOS theme)

### Describe the bug
When using page transitions (only iOS theme), header of the next page appear only after transition completes. This bug appears while using every different transition effect.

### To Reproduce
1. Go to Framework7 React Kitchen Sink
2. Scroll down to "Page Loaders & Router"
3. Go to "Page Transitions"
4. Select one of the transition effects
5. See error

### Expected behavior
Transition effect when header appears as normally as the whole content.

### Actual Behavior
Here is screenshot of actual behavior:

### Screenshots
![Знімок екрану з 2020-01-06 15-38-20](https://user-images.githubusercontent.com/25103577/71816021-c1a2f300-309a-11ea-95f4-7f9d7be73065.png)

### Additional context
This bug appeared before than I upgraded version of Framework7 React (from 5.1.1 to 5.3.0) and it still exists after upgrading.

**Comment by AlwaysLoveme** [comment]
I got this problem too.
