### ISSUE TITLE
Keyboard navigation is non-existent, some default functionality is actually removed

### ISSUE THREAD

**Issue by wysisoft** [framework7io/framework7#3482]
This framework is really nice but the keyboard navigation is nonexistent, i'm developing a universal app that will have a desktop component, and I like your framework so much i'm going to do a bunch of work to get keyboard behavior better, but please look at functionality like keen-ui which brags about how good the keyboard handling is. Specific issues:

1. CSS seems to hide the focus outline of buttons, I need to use keen-ui buttons for my project now.
2. Modal popups don't have good tab behavior, tab focus wanders outside the modal. I need to use keen-ui modals for my project now.
3. alt-left and alt-right doesn't go forward and back in any demo i've seen, so I need to customize the router and handle my own keyboard events.
4. All controls should have good feedback regarding which control is currently in focus, buttons, switches, sheets, list items (see openui5 for good focus behavior of list items).

**Comment by wysisoft** [comment]
5. some kind of escape button behavior on popups/panels would be nice, i see it for some controls but not others

**Comment by AliMamed** [comment]
> 5. some kind of escape button behavior on popups/panels would be nice, i see it for some controls but not others
Popup should close on escape if you create it with `closeOnEscape` [parameter](https://framework7.io/docs/popup.html#popup-parameters).
