### ISSUE TITLE
Ошибка в замена [ и ] в названии поля в request при отправке данных как объект

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3490]
Если мы передаем данные как объект в **request**, то такое имя **name[]** будет подвержено изменениям: **[** и **]** будут заменены соответствующими кодами из-за **Utils.serializeObject()**, гугл говорит, что так делать не нужно: https://stackoverflow.com/a/20928882 , практика показывает, что некоторые сервера не могут обработать такие переменные.

Вот строка: https://github.com/framework7io/framework7/blob/master/src/core/utils/request.js#L169
И наверное тут тоже самое: https://github.com/framework7io/framework7/blob/master/src/core/utils/request.js#L79

Решение: передавать FormData в request, там **[** и **]** не заменяются.

**Comment by nolimits4web** [comment]
А зачем передавать имя `name[]`? Если можно передать правильно как `app.request.post('/', {foo:[1, 2, 3]})`. И всё правильно отправляется

<img width="314" alt="Снимок экрана 2020-01-28 в 19 53 16" src="https://user-images.githubusercontent.com/999588/73285926-d55bf800-4207-11ea-9fb3-b4309af71e87.png">

**Comment by shastox** [comment]
Такой вариант действительно работает, спасибо.
