### ISSUE TITLE
Autocomplete error on Windows laptops with touchscreen

### ISSUE THREAD

**Issue by hmr-it-jr** [framework7io/framework7#3491]
* Framework7 version: 5.3.2
* Platform and Target: Windows 10, every Browser
* Live Link or JSFiddle: proof in gif

![20200128_154151](https://user-images.githubusercontent.com/36242595/73274586-193e0580-41e6-11ea-8822-4fe46e65cd96.gif)

### Describe the bug
On a Windows laptop with touchscreen / Windows tablet the autocomplete is not working if you click it with the mouse, If you click the autocomplete element with through the touch screen it get's selected immidiately.

### To Reproduce
1. Have a Windows laptop with a touchscreen
2. Go to the offical documentation (framework7.io) with a browser you prefer
3. Click on the autocomplete showcase with your mouse
4. Try to select a fruit at the simple drown autocomplete with your mouse (it won't work)
4. Now try to select it by touching it with your finger (this will work immidiately)

### Expected behavior
The autocomplete should be usable on Windows laptops with touchscreen too.

### Actual Behavior
The autocomplete works on Windows laptops with touchscreen only if the touchscreen is used.

### Additional context
Explanation of what you see in the gif:

- first we go to the offical doc as described above
- we do what is described in To Reproduce
- after this we go to the device manager and disable the touchscreen
- we restart the browser
- now the autocomplete works immidiately because the touchscreen is disabled

**Comment by ndikanov** [comment]
Related issue: [The resizable grid can't be resized using a mouse / touchpad.](https://github.com/framework7io/framework7/issues/3483)
