### ISSUE TITLE
Photo Browser title's font color issue in dark theme

### ISSUE THREAD

**Issue by lauchogit** [framework7io/framework7#3496]
This is for Framework7 core v5.4
When open Photo Browser with the dark theme(Photo Browser default dark theme, not global), it will have the title in black.
This only happens in the Page type Photo Browser.
No problem on the Standalone and Popup type.
![image](https://user-images.githubusercontent.com/37097224/73724326-02f3f480-4766-11ea-8a34-3d5500abd508.png)

**Comment by shastox** [comment]
Everything works in kitchen

**Comment by lauchogit** [comment]
> Everything works in kitchen

Edited.
Using the global dark theme has no issue, it only caused by using the default Photo Browser dark theme.

**Comment by nolimits4web** [comment]
Duplicate #3498
