### ISSUE TITLE
Light theme Photo Browser title is white colour after enable the global dark theme

### ISSUE THREAD

**Issue by lauchogit** [framework7io/framework7#3498]
* Framework7 version: 5.4.0

### Describe the bug
After enabling the global dark theme, the light theme photo browser will have a white colour font title.
This is all done by using the default kitchen sink core.

### To Reproduce
Steps to reproduce the behaviour:
1. Change Color Themes to Dark
2. Click on Photo Browser
3. Click on Standalone/Popup/Page (light theme)

### Expected behaviour
Black colour title text

### Actual Behavior
White colour title text

### Screenshots
![image](https://user-images.githubusercontent.com/37097224/73900972-508a7180-48cc-11ea-8dff-2915be959a3c.png)

**Comment by nolimits4web** [comment]
It is expected, you may want to redefine this CSS variable in your CSS styles:
```
:root {
  --f7-photobrowser-bars-text-color: #000;
}
```
