### ISSUE TITLE
Elements misaligned in webapp view

### ISSUE THREAD

**Issue by JJJ** [framework7io/framework7#3505]
* Framework7 version: Latest
* Platform and Target: iOS web app
* Live Link or JSFiddle: https://framework7.io/kitchen-sink/core/?theme=ios

### Describe the bug
When adding the kitchen sink as a web app, every single element that relies on the height of the viewport and requires some kind of bottom alignment appears partially offscreen.

### To Reproduce
1. Add the kitchen sink as an app
2. Click on that app
3. Select nearly any component (calendar, popup, etc)
4. See the bottom of the page

### Expected behavior
I expect for all of the components to be perfectly aligned to mirror iOS as closely as is achievable.

### Actual Behavior
All components that are bottom aligned or rely on viewport height appear partially offscreen.

### Screenshots
![136004B5-929B-4DEE-95C3-7A1D3D8CB34E](https://user-images.githubusercontent.com/88951/74621947-933a1e00-5104-11ea-93fc-9562de09cf53.png)
![D071A795-A536-4852-AB7C-D53B67DD3573](https://user-images.githubusercontent.com/88951/74621949-959c7800-5104-11ea-9fcb-d78e1b8e4a50.png)
![DCEA47FA-8C2C-4636-80E8-EA866F1B134A](https://user-images.githubusercontent.com/88951/74621950-96350e80-5104-11ea-8586-732d2d779509.png)

**Comment by nolimits4web** [comment]
What is the iOS version/device? I can't see such issues

**Comment by JJJ** [comment]
Perhaps the kitchen sink web app was cached strangely on my end.

I’ve reinstalled it, and it looks much better.

Closing this. Sorry for the chatter.
