### ISSUE TITLE
Parameter `loadInitialPage` does not prevent initial page loading

### ISSUE THREAD

**Issue by Morjodrom** [framework7io/framework7#3539]
Despite the parameter `loadInitialPage` being set to `false` the initial page is loaded. 

### To Reproduce
This behaviour is intended inside `router-class.js`, the initial page is loaded on first `app.view.create` call
```JavaScript
//..
if (historyRestored) {
   router.navigate(initUrl, {
        // ...
   });
}
//...
```

### Expected behavior
No xhr request and no page reinitialization happens after the page 

### Actual Behavior
The framework requests the same page via ajax and then replaces the .page container with the same content.

### Additional context
I am building a server-first app, so the page content is fully available after the initial page loading, no additional requests needed.

### A screenshot
I made a screenshot of ```console.log('page-init')``` inside page:init handler.
As it seems, the page inits twice after loading in a browser. 
![изображение](https://user-images.githubusercontent.com/11189913/75380510-36025180-58e8-11ea-8ca9-8ada5f4acd4f.png)

**Comment by nolimits4web** [comment]
I guess you mean when you have pushState enabled? Did you try to disable set `pushStateOnLoad: false` view's parameter too?

**Comment by Morjodrom** [comment]
Yes, `pushState` is enabled and `pushStateOnLoad: false` has solved the problem. Sorry for bothering, I did not understand the definition of `pushStateOnLoad` parameter in the docs.
And thank you for Framework7 of course!

**Comment by nolimits4web** [comment]
Glad it solved 👍
