### ISSUE TITLE
Dropdown menu in Navbar is not opened correctly

### ISSUE THREAD

**Issue by Applemann** [framework7io/framework7#3540]
* Framework7 version: 5.4.5
* Platform and Target: Android 9 Cordova app
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
In framework7-svelte when I add dropdown Menu into Navbar to right position and open it so it is rewritten by Subnavbar:
https://forum.framework7.io/uploads/default/original/2X/a/a1d02fb0f2b09d016fd0d8581a93216f5b9f31d5.png

My code is:
```
  <Navbar title="Navbar title">
    <Subnavbar> Test </Subnavbar>

    <NavRight>
      <MenuItem style="margin-left: auto" iconF7="square_arrow_up" dropdown>
        <MenuDropdown right>
          <MenuDropdownItem href="#" text="Menu Item 1" />
          <MenuDropdownItem href="#" text="Menu Item 2" />
          <MenuDropdownItem href="#" text="Menu Item 3" />
        </MenuDropdown>
      </MenuItem>
    </NavRight>

  </Navbar>
```

### Expected behavior
Show opened dropdown menu in Navbar correctly.

**Comment by nolimits4web** [comment]
This will require to tweak a bit z-index, try to add this:
```
  <NavRight class="right-with-menu">
```
and in CSS:
```
.navbar .right-with-menu {
  z-index: 700;
}
```

**Comment by Applemann** [comment]
I tried your solution, but it still don't work for me.
