### ISSUE TITLE
Navbar count text of photo browser won't update

### ISSUE THREAD

**Issue by yuanwowo** [framework7io/framework7#3551]
* Framework7 version: 5.4.5
* Platform and Target: Mobile Chrome browser

### Describe the bug
Navbar count text won't update if I swipe to next/prev slide. But it works fine if I click the toolbar navigation buttons.

### To Reproduce
1. Go to https://framework7.io/kitchen-sink/core/?theme=md
2. Open photo browser example page
3. Swipe from the first slide to the last slide.  The Navbar text remains ‘1 of 5’.

**Comment by nolimits4web** [comment]
Can't see such issue and see all works correctly. Anyone see same issue?

**Comment by yuanwowo** [comment]
I've found that if I swipe photo slowly(not too fast),  I can reproduce issue 100% of the time. I record screen to GIF. Please see it below.
![1](https://user-images.githubusercontent.com/2813912/75785313-7a856580-5d9e-11ea-9e63-ae985cad98ef.gif)
