### ISSUE TITLE
Framewor7-Svelte Issue, missing event pageBeforeUnmount

### ISSUE THREAD

**Issue by thebestgin** [framework7io/framework7#3554]
I think the event "pageBeforeUnmount" is missing in the Svelte component [page (https://github.com/framework7io/framework7/blob/master/src/svelte/components/page.svelte)](https://github.com/framework7io/framework7/blob/master/src/svelte/components/page.svelte).

The event is not fired and I can't find anything in the source code.

**Comment by nolimits4web** [comment]
Use Svelte's `onDestroy` instead https://svelte.dev/docs#onDestroy

**Comment by thebestgin** [comment]
Thanks for your suggestion. Unfortunately this event does not fire at route "keepAlive: true". According to your documentation, we need the requested event. Or have I misunderstood something?

**Comment by thebestgin** [comment]
> Use Svelte's `onDestroy` instead https://svelte.dev/docs#onDestroy

Thanks for your suggestion. Unfortunately this event does not fire at route "keepAlive: true". According to your documentation, we need the requested event. Or have I misunderstood something?
