### ISSUE TITLE
Swiper Component - Using zoom with lazy loading

### ISSUE THREAD

**Issue by 3zzy** [framework7io/framework7#3563]
I'm using Swiper in Framework7 using Vue components. Its been great so far, except I just can't get zoom to work with lazy loading since they probably have special layouts. However, I confirmed that zoom does with lazy loading in Swiper (https://swiper-demo-39-zoom-fxnhzf.stackblitz.io)

This is my template:
```
<f7-swiper dir="rtl" v-if="swiper.init" v-bind="swiper">
    <f7-swiper-slide
        zoom
        v-for="(slide, index) in virtualData.slides"
        :id="index"
        :key="index"
        :style="slideOffset"
    >
        <img :data-src="slide" class="swiper-lazy" alt="" />
        <div class="swiper-lazy-preloader"></div>
    </f7-swiper-slide>
</f7-swiper>
```

The image doesn't load because the `data-src` is not replaced with `src`.

**Comment by nolimits4web** [comment]
Lazy loading need to be also enabled in Swiper parameters https://swiperjs.com/api/#lazy

**Comment by 3zzy** [comment]
@nolimits4web Yes, its set to true and preloadimages to false but still won’t work.

**Comment by nolimits4web** [comment]
Then would be good to see live example or fiddle where it doesn't work

**Comment by 3zzy** [comment]
Is there a fiddle I can fork from? That would be really helpful. Thanks.
