### ISSUE TITLE
Svelte issue on triple dot argument of JS in Marshmallow android OS

### ISSUE THREAD

**Issue by raiyanihiren** [framework7io/framework7#3565]
* Framework7 version: [e.g. 5.5.0]
* Platform and Target: [e.g. Android 6.0.1 Marshmallow Device]

### Describe the bug
When running application on Marshmallow android, js error trigger for triple-dot unexpected

### Expected behaviour
It will run all android version but from marshmallow and below this js error triggered

### Screenshots
Please check screenshot for more detail.
[
<img width="697" alt="Screenshot at Mar 09 14-28-47" src="https://user-images.githubusercontent.com/10560877/76206120-74b9d500-6221-11ea-8c15-20868bbde33e.png">
<img width="702" alt="Screenshot at Mar 09 14-28-14" src="https://user-images.githubusercontent.com/10560877/76206130-7a171f80-6221-11ea-97d8-f87ca39aeea3.png">

](url)

**Comment by nolimits4web** [comment]
Did you create app with Framework7 CLI? Make sure F7-Svelte package is transpiled in babel settings and your `browserslist` in `package.json` covers Android 6 (by default it is not)

**Comment by raiyanihiren** [comment]
Thank for your reply,
Yes, I am used Framwork7 CLI, but I don't know how to add browser list or bible settings. Can you help, how can I solved that error?
