### ISSUE TITLE
Add issue template for Svelte

### ISSUE THREAD

**Issue by Applemann** [framework7io/framework7#3572]
**Is your feature request related to a problem? Please describe.**
Here in Github when I want to create issue, I can choose a templates for: Core, React or Vue, but
not for Svelte yet.

**Describe the solution you'd like**
Can you please make an issue template also for Framework7-Svelte?

**Describe alternatives you've considered**
Now I am taking Framework7-Core tamplate.

**Additional context**
Add any other context or screenshots about the feature request here:
![image](https://user-images.githubusercontent.com/2686906/76594928-ae792d00-64fa-11ea-92e8-9dff0102014b.png)

P.S.: Also you have a mistake in name of templates: you have ` Framewor7-Core` instead of ` Framework7-Core`

**Comment by nolimits4web** [comment]
Added
