### ISSUE TITLE
CSS Only Mode

### ISSUE THREAD

**Issue by easrng** [framework7io/framework7#3575]
I dislike using frameworks such as React, Vue, or Angular, and in general I would prefer if my UI did not rely on javascript, so I would appreciate if framework7 would allow us to use the CSS styles without the javascript.
There doesn't seem to be any other alternative to framework7's iOS theme that don't require Javascript, except a few very old ones that use the pre-iOS 7 design like [iocss](https://git.io/JviTN), and the android/material theme does have other ooptions, like [Matter](https://git.io/JviTj).
In the past I have written CSS for my apps to look like iOS myself, but none of my attempt came close to the level of detail provided by framework7.
If what I want is already available, in framework7 or otherwise, please let me know.

**Comment by paulovieira** [comment]
You might like tailwindcss - https://tailwindcss.com (and the respective component library https://tailwindui.com).

It doesn't have a iOS theme (nor an Android theme), but it doesn't use js in most components (and if it uses, it's very light).
