### ISSUE TITLE
Provide all f7-Components as web-compontents by using Stencil

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#3576]
**Is your feature request related to a problem? Please describe.**
I find it's time to provide all f7-components as web-components. 

The web-components can be provided by translating f7-components to stencil-components. Stencil will then compile it to raw web-components. Stencil has also built-in support for framworks like react, angular, vue. However, f7 can use its raw javascript bundle to compile it to web-components with the help of stencil. As web-components are framework independent they can be used in any framwork making the further maintanance of f7-react, f7-vue, f7-svelte (at least the most parts) likely useless.

**Describe the solution you'd like**
To have all f7-components as stencil-components, so that one can compile it to web-components.

**Additional context**
Learn more: https://stenciljs.com/docs/introduction

**Comment by boustanihani** [comment]
It's sad that this didn't receive any attention.
