### ISSUE TITLE
Messagebar send-link slot is not rendered

### ISSUE THREAD

**Issue by AliMamed** [framework7io/framework7#3577]
* Framework7 version: 5.5.0
* React.js version: 16.13.0
* Platform and Target: any
* Live Link or JSFiddle: https://jsfiddle.net/aqo6d1e8/

### Describe the bug
Messagebar's send-link slot contents is not rendered
IMHO problem is here https://github.com/framework7io/framework7/blob/master/src/phenome/components/messagebar.jsx#L147 when it is converted to https://github.com/framework7io/framework7/blob/master/packages/react/components/messagebar.js#L213
as `F7Link` receives the element also to 'send-link' slot and doesn't render it as it doesn't has such slot

**Comment by nolimits4web** [comment]
Fixed by #3578
