### ISSUE TITLE
Multiple popup close in wrong order

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3581]
* Framework7 version: 5.5.0 (and before)
* Vue.js version: 2.6.11 (and before)
* Platform and Target: tested on Chrome on Mac but occurs probably on all platform
* Live Link or JSFiddle: https://jsfiddle.net/fy5a63r8/2/

### Describe the bug
When you open several popup, the "popup-close" attribute on navbar link does not close the popup it is attached to, but it close the first open popup. 

### To Reproduce
1. Go to https://jsfiddle.net/fy5a63r8/2/
2. Open popups B, C & D 
3. Try to close popup D : you will have to click 3 times

Bonus : if you are on big screen (and the popup is not fullscreen), you will observe that the black overlay disappears on the first click (and if the popup has "push" effect, the push effect will be canceled on first click)

### Expected behavior
Clicking the "popup-close" link should close the popup it is located on.
And the overlay should disappear only when the last popup is closed.

### Actual Behavior
The "popup-close" link closes popup in wrong order (FIFO instead of LIFO). 
And the overlay disappears on the first click.

**Comment by AliMamed** [comment]
I understand that it's not the solution for your question, but maybe you could think about navigating using several pages with in one popup.

**Comment by Pitouli** [comment]
@AliMamed : UX speaking, pages navigation would not be a satisfying solution in my situation :) 

And technically speaking, I could simply replace "popup-close" links by @click links that close the popup based on the ref. But even if it is only few lines of code, I strongly believe that closing popups in LIFO order by default is better, and it makes the code lighter.

**Comment by FishSaidNo** [comment]
If you give each popup a specific class (or unique id) and supply the `data-popup` attribute to the close link, it should close the correct popup for you.

Eg.
`<div id="popup-page-b" class="popup">...</div>`
and
`<a href="#" class="link popup-close" data-popup="#popup-page-b">Close</a>`

https://framework7.io/docs/popup.html#control-popup-with-links

**Comment by Pitouli** [comment]
Thanks @FishSaidNo, that will be an easier workaround than the one I intended to use!

Nevertheless, I believe it would be even easier to have a LIFO behavior instead of a FIFO behavior.

**Comment by nolimits4web** [comment]
Fixed in ba16a210896ed8d28661f4661da9a94be6709f4a Now on popup close it will check if there are many modals match, and close the one which is the parent of the clicked close link, or last one (if no links passed)
