### ISSUE TITLE
Tabs bar covers page-content on Firefox

### ISSUE THREAD

**Issue by jaco** [framework7io/framework7#3585]
* Framework7 version: 4.5.2, 5.5.3
* Platform and Target: Firefox 70, 71, 72

### Describe the bug
On firefox, tabs bar covers page-content

### To Reproduce
1. Run `framework7 create`
2. Choose all default options except starter template (Simple web app, Framework7 Core)
3. Choose starter template: `Tabbed Views (Tabs)`
4. Run `npm run start`
5. Open app in small Firefox window

### Expected behavior

Tab bar covers page content (left: safari, right: firefox):

![image (1)](https://user-images.githubusercontent.com/60188/77825511-17bb8b80-710a-11ea-9bfe-cffae89970b3.png)

**Comment by shastox** [comment]
https://github.com/framework7io/framework7/issues/2053#issuecomment-355756625
