### ISSUE TITLE
Прозрачная область в верхней части Toolbar

### ISSUE THREAD

**Issue by imsuspend** [framework7io/framework7#3586]
* Framework7 version: 5.5.3
* Platform and Target:  iPhone 11 / iOS 13.4 / Safari browser

### Describe the bug
Прозрачная область в верхней части Toolbar

### To Reproduce
1. Go to 'https://framework7.io
2. Click on 'Showcase/Toolbar & Tabbar/Hide Toolbar On Scroll'

### Screenshots
![IMG_0098 (1)](https://user-images.githubusercontent.com/925307/77829023-f23d7a80-7127-11ea-9971-2751a0915e29.png)

### Additional context
То же самое, когда запускаю приложение (cordova run browser), на iPhone 11 / iOS 13.4 / Safari browser - Toolbar с такой же проблемой.

**Comment by nolimits4web** [comment]
Проблема была поправлена в 5.5.3, если нет то давайте живой пример. На сайте из-за кэша возможно отображается старая версия

**Comment by imsuspend** [comment]
К сожалению проблема не полностью исправлена. Tabbar – да, в 5.5.3 все хорошо, а вот Toolbar так и остался. Спасибо! Отправлено из приложения "Почта" для Windows 10 От: Vladimir KharlampidiОтправлено: суббота, 28 марта 2020 г. в 19:16Кому: framework7io/framework7Копия: imsuspend; AuthorТема: Re: [framework7io/framework7] Прозрачная область в верхней части Toolbar (#3586) Проблема была поправлена в 5.5.3, если нет то давайте живой пример. На сайте из-за кэша возможно отображается старая версия—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nolimits4web** [comment]
Toolbar и Tabbar это одно и тоже. Проблемы больше нет

![55686721-DDBF-4427-8647-5460B44AB75D](https://user-images.githubusercontent.com/999588/77830998-7e0dd180-713d-11ea-9922-7ce4869a251d.png)
![71DA0762-FE29-4A02-A6D1-DC4A2BF9CF06](https://user-images.githubusercontent.com/999588/77831005-836b1c00-713d-11ea-86ea-99b04fb19486.png)
