### ISSUE TITLE
Can't resolve './images/index' in '/node_modules/framework7/components/swiper/swiper-src/components/core'

### ISSUE THREAD

**Issue by kyleroberthammond** [framework7io/framework7#3596]
Can't resolve './images/index' in '/home/kyle/Desktop/LionV2/node_modules/framework7/components/swiper/swiper-src/components/core'

Ive been having this problem for a few versions, hoping the latest fixed it but it didnt,
im sure its something simple.
I have been going into the core-class and commenting the images area out to get it working.
Starts to annoy me, as i have to do it everytime i do a npm install.
Am i missing a module?

**Comment by apuntovanini** [comment]
Same issue here!

**Comment by HenrijsS** [comment]
For me removing yarnclean file fixed it!
