### ISSUE TITLE
f7.dialog.create content with  html-El <i> problem

### ISSUE THREAD

**Issue by thebestgin** [framework7io/framework7#3597]
The following js-code produces 3 icons. 
But it is only one icon in the content.
The icon has only classes.
If I change `<i>` to `<div>` everything works fine.
If I use material icons with text everything works fine too.

JS-Code
var dialogOk = f7.dialog.create({
          title: "Title",
          text: "Text",
          content: `<div><i class="icon icon-app-check color-green"/></div>`,
        });
        dialogOk.open();

HTML-Output
`<div class="dialog dialog-no-buttons text-align-center modal-in" style="display: block;">
          <div class="dialog-inner">
            <div class="dialog-title">Title</div>
            <div class="dialog-text">Text</div>
            <div><i class="icon icon-app-check color-green"></i></div><i class="icon icon-app-check color-green">
          </i></div><i class="icon icon-app-check color-green">          
        </i></div>`

**Comment by nolimits4web** [comment]
This is a not valid HTML `<div><i class="icon icon-app-check color-green"/></div>`
`I` tag is not a self-closing, it must be:
`<div><i class="icon icon-app-check color-green"></i></div>`
