### ISSUE TITLE
Missing events on text-editor

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3599]
* Framework7 version: v5 (tested on 5.5.5 & 5.5.6)
* Vue.js version: v2 (tested on 2.2.1)
* Platform and Target: all
* Live Link or JSFiddle: https://jsfiddle.net/xrofwcqa/2/

### Describe the bug
Several `text-editor` events are missing when use as a `f7-list-input` : `popoveropen` & `popoverclose`

`keyboardopen` & `keyboardclose` events do not fire (neither on `f7-text-editor` nor on `f7-list-input`), but since I only tested on desktop, this is perhaps normal? 
input event does not fire neither, but it is probably because I do not know in which situation it should trigger...

Additionally, it would be awesome to have a more intelligent "blur" event (or create a new "edition-completed" event?)
Currently, when you click on a popover button, the texteditor send a blur event (since, effectively, it has lost the focus in favor of the popover). But in my situation (and probably in most situations), I would like an event that triggers when the user finishes its edition (so I can save the content to the db automatically). Currently, I'm saving the content every time the user changes the style of its text.

By using focus, blur, popoverClose and popoverOpen events, you can easily create this new event. 
I made a demo in the 5th `text-editor` of my fiddle.
But of course, it requires `popoverClose` and `popoverOpen` events to trigger, which is not the case in `f7-list-input` (and those are the notes I use).

### To Reproduce
There are 5 text-editor on the page. Open the console to see the events thanks to console.log

1. `f7-text-editor` with `@texteditor:event`: mostly work (except input and keyboardOpen/Close)
2. `f7-text-editor` with `@event`: nothing work
3. `f7-list-input` with `@texteditor:event`: only `change` events
4. `f7-list-input` with `@event`: only `focus`, `change` & `blur` events
5. A `f7-text-editor` that listen to `focus`, `blur`, `popoverOpen` & `popoverClose` to emit a 'edition-completed' event

### Expected behavior
All events should work _(honestly, I do not know if they should work on the `@texteditor:event` or the `@event` form... I suppose the first one, but currently it sometimes the second that works best)_

### Actual Behavior
Some events are not triggered

**Comment by nolimits4web** [comment]
In `f7-list-input` you need to pass event listeners in `text-editor-params`:
```
... text-editor-params="{ on: { focus: onFocus } }"
```
This is the list of events https://framework7.io/docs/text-editor.html#app-and-text-editor-instance-events

In `f7-text-editor` you need to listen for these events as attributes https://framework7.io/vue/text-editor.html#text-editor-events
