### ISSUE TITLE
Possible bug? Need add "no-swipe-back" for login-screen 

### ISSUE THREAD

**Issue by stanleyxu2005** [framework7io/framework7#3601]
(Correct me, if I'm wrong) I think `<f7-page login-screen>` should contain a `no-swipe-back` by default, otherwise user can bypass (close) the login screen by swiping back.

**Comment by nolimits4web** [comment]
No, login-screen provides layout, and in lot of cases it is used for just usual forms, so just add `no-swipe-back` on your own
