### ISSUE TITLE
Navbar clickBack event doesn't work.

### ISSUE THREAD

**Issue by Applemann** [framework7io/framework7#3605]
* Framework7 version: 5.5.3
* Svelte version: 3.18.1
* Platform and Target: Cordova App Android 9, Chrome browser
* Live Link or JSFiddle/CodeSandbox: [CodeSandbox](https://codesandbox.io/s/epic-pine-2wrxz?file=/About.svelte)

### Describe the bug
I have code:
```
<Navbar title="AboutTest" backLink="Back"  on:clickBack={() => { console.log("test") }}></Navbar>
```
I want to run my function when user click on back link in Navbar, but it doesn't work.

### To Reproduce
Into CodeSandbox I added my code into Navbar of About page.
1) In CodeSandbox go to About page
2) Click to back link in Navbar

### Expected behavior
I expect that my function: `on:clickBack={() => {console.log("test")}}` will be run and into console write test output log.

### Actual Behavior
Nothing. Only go back but my function is not lounched.

### Screenshots
![image](https://user-images.githubusercontent.com/2686906/79897772-7b379100-840a-11ea-8d31-735c34c15eb0.png)

**Comment by Applemann** [comment]
Hello after upgrade to framework7 version: 5.7.0
I still cannot handle clickBack or backClick events..

My code is:
```
  <Navbar backLink on:clickBack={() => { alert("test") }} title="test title">
    <slot name="subnavbar"> </slot>
    <NavRight>
      <Link popoverOpen=".popover-menu">
        <Icon material="reorder" />
      </Link>
    </NavRight>
  </Navbar>
  <Menu name="popover-menu" />
```

**Comment by orhan-swe** [comment]
The commit d822832 solved another bug. The onClickBack and onBackClick are not triggering at all. I am using react and have tested this on version 5.1.3 and on 5.7.1 and it is not working in ether one of the two. 

This is my code:
```
 <Navbar 
        title="Settings"
        backLink="Back"
        onClickBack={() => this.props.updateAccount()}
 />
```
Splitting it in to NavLeft and NavTitle does not work ether..

Also I think this worked in version 4 as I was using this feature in an older app..

**Comment by nolimits4web** [comment]
This what works perfectly for me in latest F7-React:
```
<Navbar title="About" backLink="Framework7" onClickBack={() => alert('hello world')}>
```
And in latest F7-Svelte
```
<Navbar title="About" backLink="Framework7" on:clickBack={() => { alert("test") }}>
```
If it is still doesn't work for you, create new issue and provide link to JSFiddle or similar with live example

**Comment by Applemann** [comment]
@nolimits4web here you can download test project: https://github.com/Applemann/Backlink-bug
where is latest version framework7 and svelte and `clickBack` event don't run function `alert("test")`:
https://github.com/Applemann/Backlink-bug/blob/master/src/components/about.svelte

when you click to back link button in navbar.

I tested it in Android 9 and Chromium Version 80.0.3987.163

**Comment by Applemann** [comment]
@nolimits4web did you try my test project from my last comment or do you will open this issue?
I would like for don't forget this issue.

**Comment by djsambo** [comment]
Hello I have the same issue.

**Comment by nolimits4web** [comment]
@Applemann any reason why your repo uses different version of F7 and F7-Svelte, they should be the same and latest, all works there!

**Comment by Applemann** [comment]
@nolimits4web Yes I didn't run: `npm install framework7-svelte` 
because I thought that command: `npm install framework7` update all framework7 packages..
It's my mistake. I'm sorry..

Now after run: `npm install svelte framework7 framework7-svelte`
All is OK. Thank you very much ;)
