### ISSUE TITLE
Popup element is not removed from the dom when created dynamically with el parameter

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#3607]
* Framework7 version: [e.g. 5.6.0]
* Platform and Target: [Chrome browser]
* Live Link or JSFiddle: https://codepen.io/blikblum/pen/mdeRrOo?editors=1010

### Describe the bug
Popup element is not removed from the dom when created dynamically with el parameter and there's a static popup in the page

### To Reproduce
1. Go to https://cdpn.io/blikblum/debug/mdeRrOo/yPAJjKpaNmPA
2. Open dev tool and click on Open Content Button 
3. Look at devtool inspector, you should see an popup element inserted as child of root element
4. Close the popup, The inserted popup is removed
5. click on Open Element Button, an popup element is inserted as child of root element
6. close the popup: the inserted element is not removed. Clicking and closing over again will increase the number of nodes in dom

### Expected behavior
The popup element should be removed from dom when closed

### Actual Behavior
The popup element is kept dom when closed

### Additional context
If i remove the static popup in the template, the dynamic popup element is removed when closed

**Comment by nolimits4web** [comment]
It happens because you call `.destroy` on `closed`, call it with, for example, 0 setTimeout, and it will work

**Comment by blikblum** [comment]
Many thanks. 

BTW: Is really necessary to call closed in those cases? In the docs example `destroy` is not called.
