### ISSUE TITLE
$setState stops updating

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#3611]
* Framework7 version: [e.g. 5.6.0]
* Platform and Target: [e.g. Brower, Android, Ios]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
I have a folder tree and file list that I update using $setState({files: data.files}) when a folder is clicked.  This works fine (folder files are listed correctly).  An action I have is to delete a file from the list.  I was simply directly deleting the list item using dom7 remove.  Then when I click another folder, the list is always blank (again it updates using setState and data is correct).  If I refresh the page it works as expected again.  I checked with the previous version of FW7 and everything worked as expected.  I commented out the dom7 remove (list item was not removed obviously) and the updates to the list worked as expected after a delete action.  It seems like in this latest update, tinkering with the VDOM causes a problem.

I wish I could create a fiddle of this but it's kinda involved to do.

**Comment by nolimits4web** [comment]
> I was simply directly deleting the list item using dom7 remove

You shouldn't do this if you use VDOM with setState, you need to remove the items by properly updating the state
