### ISSUE TITLE
Framework7 5.6.0 does not support Android6, according to the official document layout and initialization, white screen

### ISSUE THREAD

**Issue by a57571735** [framework7io/framework7#3613]
Framework7 5.6.0 does not support Android6, according to the official document layout and initialization, white screen

**Comment by a57571735** [comment]
It works fine on Android10

**Comment by a57571735** [comment]
Where can I see framework7 v5 browser support and Android version support

**Comment by nolimits4web** [comment]
Impossible to say what Android version is supported because they all have different webview. Open browser console and see what is the error, based on missing feature you can define which version is supported, but i would say, in most cases it works from Android 7+
