### ISSUE TITLE
clearPreviousHistory not working

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3614]
* Framework7 version: latest
* Vue.js version: latest
* Platform and Target: web & cordova
* Live Link or JSFiddle: https://jsfiddle.net/Lvhucmpd/

### Describe the bug
When navigating with the param `clearPreviousHistory: true`, the previous page is not removed from the DOM. With the param `reloadAll: true`, none is removed.

### To Reproduce
1. Go to https://jsfiddle.net/Lvhucmpd/
2. Click on the links until Page D
3. Click the Reload button
4. Observe the DOM: the page C is still there
5. If you do the same again, then it throw an exception the 2nd time you do the reload

### Expected behavior
The history should be empty and the pages removed from the DOM

### Additional context
The `reloadAll` option does not work either: it does not remove any page. But contrary to the `clearHistory` option, you can repeat the pattern indefinitely without an error being thrown.

**Comment by nolimits4web** [comment]
Two points i see:
1. your `settingsReload` should be nothing else but:
```
const settingsReload = {
  reloadAll: true,
};
```
2. Can't understand but there is something wrong with fiddle, it is not even remove previous pages with usual forward navigation

**Comment by Pitouli** [comment]
Strange that it does not work on fiddle :( 
So there is no bug, but I still have an issue related to routing.

When my user disconnect, I `reloadAll` the tabs behind the LoginPage. But I have a `beforeEnter` that checks if the user is connected and redirect to "Must be auth" page if it is not the case.

**The issue is: is there a way to have the guard reusing the same settings that was used when triggering it?**

----

For example, in my situation, I trigger this when the user state change: 

    const settingsReload = {
      reloadAll: true,
    };
    this.$f7.panel.close('left', false);
    this.$f7.views.parameters.router.navigate('/parameters/', settingsReload);
    this.$f7.views.home.router.navigate('/home/', settingsReload);
    this.$f7.views.timeline.router.navigate('/timeline/', settingsReload);
    this.$f7.views.contacts.router.navigate('/contacts/', settingsReload);

In my `routes.js`, all these routes have the following `beforeEnter`:

```
function checkAuth(to, from, resolve, reject) {
  const { currentUser } = firebase.auth();
  if (!currentUser) {
    reject();
    this.navigate('/auth-required/');
  } else resolve();
}
```

The problem is that the `reloadAll` seems to be ignored if the checkAuth() reject the routing.

I can replace `this.navigate('/auth-required/');` by `this.navigate('/auth-required/', { reloadAll: true );` in `checkAuth()` and it works well for the given example.

But the issue is now that if I have a link to a "must be auth" page in a "public" page, then clicking this link will `reloadAll` instead of simply navigating to the `/auth-required/` page (with a back button to the "public" page).

It seems that a good solution would be to have access in the checkAuth method to the params used when calling the router, so it can reuse the same.

I looked inside the `this`, but I didn't found it
