### ISSUE TITLE
Navbar large title issue

### ISSUE THREAD

**Issue by omar2205** [framework7io/framework7#3615]
* Framework7 version: 5.7.0
* Svelte version: 3.18.1
* Platform and Target: Chrome 
* Live Link or JSFiddle/CodeSandbox: [CodeSandbox](https://codesandbox.io/s/recursing-khorana-go625)

### Describe the bug
Large Navbar bugs out _(both the small and large titles are visible)_ when navigating to a route and navigating back (in IOS only).

### To Reproduce
1. Open the above sandbox
2. Click on About
3. Click < Back
4. The title bugs out (both the small and large titles are visible)

### Screenshots
https://i.imgur.com/KizlJe9.gifv

**Comment by nolimits4web** [comment]
```
<Navbar title="App" titleLarge="Big App" />
```
Should be:
```
<Navbar title="App" titleLarge="Big App" large />
```
