### ISSUE TITLE
Problem while Using Routify - Cant Disable Built-In Router

### ISSUE THREAD

**Issue by enesyurtlu** [framework7io/framework7#3623]
* Framework7 version: 5.7.0
* Svelte version: 3.21.0
* Platform and Target: Both
* Live Link or JSFiddle/CodeSandbox: 

### Describe the bug
I cannot disable built-in router. I just want to use Svelte-Routify package as router. When i click on a "<a>" tag, it just does nothing. Not pushes the state or goes to url. I tried disabling router but it didnt work.

**### UPDATE**
I added (class="external") and finally i could get links worked. but i want to disable built-in router and click handlers.

**Comment by nolimits4web** [comment]
You can disable router by setting: `router: false` parameter on View

**Comment by enesyurtlu** [comment]
it didnt worked. i already added that parameter
