### ISSUE TITLE
Theme colour is not getting applied on dialog buttons

### ISSUE THREAD

**Issue by harish0507** [framework7io/framework7#3624]
* Framework7 version: 5.7.0
* Platform and Target: Any
* JSFiddle: https://jsfiddle.net/harish0507/3pv5msjb/2/

### Description
Theme colour is not getting applied on dialog buttons when theme colour class is applied to app's root element.

### To Reproduce
Steps to reproduce the behaviour:
1. Go to JSFiddle
2. Note that `.color-theme-purple` is set on app's root element `#app`
3. But the dialog button colour is not purple, Default colour is being applied

### Expected behaviour
The dialog button colour should be same as the theme colour set on app's root element.

### Actual Behaviour
The default colour is getting applied to the dialog button irrespective of the theme colour set.

### Screenshots
<img width="327" alt="Screenshot 2020-05-01 at 4 01 57 PM" src="https://user-images.githubusercontent.com/14799952/80799778-5f2fae80-8bc5-11ea-8932-30892f3492bd.png">

**Comment by nolimits4web** [comment]
It is by design:
https://framework7.io/docs/dialog.html#css-variables
`--f7-dialog-button-text-color` defined on `:root` -> it won't be overridden by class on app. Redefine this var on `:root` or add that class to `<html>` element
