### ISSUE TITLE
toolbar-tabbar not stick at the page bottom

### ISSUE THREAD

**Issue by YaoKaiLun** [framework7io/framework7#3626]
# Describe the bug
toolbar-tabbar not stick at the page bottom, after closing and reopening chrome in IOS.

### To Reproduce
1. Open the [demo])(https://framework7.io/react/toolbar-tabbar.html) in ios chrome
2. closed and reopened the chrome browser
2. See toolbar-tabbar not stick at the page bottom

### Expected behavior
toolbar-tabbar should stick at the page bottom

### Screenshots
![image](https://user-images.githubusercontent.com/11460856/80828918-b57a0d00-8c18-11ea-8250-aaf3c639589d.png)

### Additional context
Some same issues like this https://stackoverflow.com/questions/58935402/ios-chrome-calculates-the-wrong-height-of-the-document, but i still don't know how to fix it.

**Comment by nolimits4web** [comment]
Sorry, it is obviously issue with Chrome, not with F7
