### ISSUE TITLE
Can't go back to first page in routable popup

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3627]
* Framework7 version: latest (5.7.1 and before)
* Vue.js version: latest
* Platform and Target: all
* Live Link or JSFiddle: https://jsfiddle.net/ptoy8ham/

### Describe the bug
If you navigate inside a popup, you cannot go back to the first page

### To Reproduce
1. Go to https://jsfiddle.net/ptoy8ham/
2. Click on popup
3. Go deep with Page C and Page D links
4. Go back with back button until the initial page of the popup

### Expected behavior
The first page (with the close button) should appear

### Actual Behavior
It's the "Page Not Found" that appears

### Additional context
When the popup hasn't a "swipe to close" feature, it completely blocks the app

**Comment by nolimits4web** [comment]
Because firs page in Popup must be loaded from route too, e.g.:
```
<f7-popup>
  <f7-view url="/page-a/" />
</f7-popup>
