### ISSUE TITLE
componentUrl searches for components in wrong directory

### ISSUE THREAD

**Issue by jacekk015** [framework7io/framework7#3635]
Main App Component with Single File Component using componentUrl doesn't respect this folder "./" notation.
Directory structure in attached pic.
In /app/js directory I have main app.js file and my components are in /app/js/components directory
`componentUrl: './components/app.html'`
https://xxx.pl/app/components/app.html 404 (Not Found)

`componentUrl: 'components/app.html'`
https://xxx.pl/app/components/app.html 404 (Not Found)

I need to use:
`componentUrl: './js/components/app.html'`
which is improper because /components is a subfolder of /js

![Zrzut ekranu z 2020-05-15 14-14-30](https://user-images.githubusercontent.com/14165726/82049353-75a23380-96b6-11ea-8adc-6a6aca22da62.png)

**Comment by nolimits4web** [comment]
It is not some kind of import (like in es modules or require), this paths are just strings and get executed on client side (in browser), so you need to make this paths not relative from current file, but relative to your app URL when it is running
