### ISSUE TITLE
Swipeout + Link = open link on desktop after swiping

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3637]
* Framework7 version: latest
* Vue.js version: latest
* Platform and Target: desktop (tested on Chrome Browser)
* Live Link or JSFiddle: https://jsfiddle.net/sa9qp138/

### Describe the bug
On desktop, when doing a swipe out on a list item with link, if you release the click on the link, it will open the link.

### To Reproduce
1. Go to https://jsfiddle.net/sa9qp138/
2. Swipe the page B link at the top
3. Release your click on the link
4. The popup open

### Expected behavior
The link should be swiped out, so you can click the swipe options

### Actual Behavior
The link activate so you cannot use the swipe options

### Additional context
No problem on phones

**Comment by gaohomway** [comment]
Have you solved this problem? It still exists in V7
