### ISSUE TITLE
VirtualDOM if condition

### ISSUE THREAD

**Issue by aldoexpert** [framework7io/framework7#3644]
I have use f7 v5.7
and I try for code in template html
{{#if (bool1 or bool2 or bool3) and !bool4 }}
{{#if (bool1 || bool2 || bool3) && !bool4 }}
but no one can work

how can I do this condition?

**Comment by shastox** [comment]
{{#if bool1}}{{#if bool2}}...
or 
{{#js_if "this.bool1 && this.bool2 ..."}

**Comment by aldoexpert** [comment]
Thanks @shastox this works
