### ISSUE TITLE
Form input datetime-local not showing time in IOS

### ISSUE THREAD

**Issue by KyooMario** [framework7io/framework7#3645]
* Framework7 version: 5.7.1
* Platform and Target: iphone 7 iOS 13.4.1

The bug:
The time is not showing in the input box after selection or with pre value.

Please advise.

Screenshots
![Framework7 input datetime-local](https://user-images.githubusercontent.com/38975838/82707144-c64bfa80-9c7b-11ea-808c-b9aade9dee90.png)
<!--

Kind regards,
Mario

**Comment by nolimits4web** [comment]
This is how iOS natively handles this type of input https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/datetime-local
You may want to use custom picker instead https://framework7.io/docs/picker.html
