### ISSUE TITLE
Usual Searchbar dont' working

### ISSUE THREAD

**Issue by gost1k** [framework7io/framework7#3652]
"framework7": "^5.7.5",
    "framework7-cli": "^3.3.1",
    "framework7-vue": "^5.7.5",
    "vue": "^2.6.11",
   Platform and Target: Cordova

Приветствую. По ошибке: не работает поиск у компонента Searchbar https://framework7.io/vue/searchbar.html#examples (взят пример с Usual Searchbar). 
Даже если взять "голый" исходник у virual list не выполняется метод "searchAll". При этом отрабатывает ошибка, которая вызывает элемент с классом "searchbar-not-found". Но список при этом не ререндерится. В чем может быть проблема?

**Comment by nolimits4web** [comment]
Смотрите пример в Vue Kitchen Sink https://github.com/framework7io/framework7/blob/master/kitchen-sink/vue/src/pages/virtual-list.vue

**Comment by gost1k** [comment]
![error 2](https://user-images.githubusercontent.com/9681233/84160633-134f0f80-aa77-11ea-894d-96ffc9e9e3bf.png)
![error 1](https://user-images.githubusercontent.com/9681233/84160641-14803c80-aa77-11ea-80fc-0b2bcfe3cdb7.png)

Дело в том что указанный вами пример Vue Kitchen Sink тоже не работает в этой конфигурации. взят чистый код, без правок

**Comment by nolimits4web** [comment]
Ну вот тут же этот пример работает как надо https://framework7.io/kitchen-sink/vue/

**Comment by nolimits4web** [comment]
Значит где это у вас ошибка или давайте пример где это не работает, за основу можно взять это https://codesandbox.io/s/framework7-vue-tjvyd
