### ISSUE TITLE
ListInput hairline issue

### ISSUE THREAD

**Issue by sharadkamal** [framework7io/framework7#3661]
framework 7 react, facing an issue related to list input hairline on ios devices, where the related line disappear on ios devices only and in android devices the view works fine. (expansion on the issue here the list input fields on ios is stuck together making the hairline disappear)  

issue on ios devices

![ios issue](https://user-images.githubusercontent.com/60175205/84646335-91039700-af1f-11ea-8a44-1a81205fb436.PNG)

on android devices works fine

![andriod view](https://user-images.githubusercontent.com/60175205/84646443-bd1f1800-af1f-11ea-92c3-37afcb78b2b5.PNG)

**Comment by nolimits4web** [comment]
It is by design, last item in list in iOS theme doesn't have underline. You can add empty `<li>` after it
