### ISSUE TITLE
Scroll indicator in the middle of the screen on iPhones with safe areas

### ISSUE THREAD

**Issue by eafif** [framework7io/framework7#3663]
* Framework7 version: 5.7.8
* Vue.js version: 2.6.11
* Platform and Target: iOS - only on iPhone with safe areas (such as iPhone X and 11)
* Live Link or JSFiddle: I have included a [repo](https://github.com/eafif/f7buggy) where I could replicate the issue (there is also a video of the issue at [here](https://github.com/eafif/f7buggy/blob/master/buggy.mov))

### Describe the bug
For iPhones with safe areas, when I use the `created` or `mounted` Vue callback to fetch remote data, the scroll indicator appears in weird, random places.

### To Reproduce
Steps to reproduce the behavior :
1. Download the [repo](https://github.com/eafif/f7buggy)
2. `npm run build-prod-cordova`
3. Run in iPhone 11 simulator
4. Visit the details page multiple times and see that scroll indicator appears in weird places
5. You can refer [to this video](https://github.com/eafif/f7buggy/blob/master/buggy.mov) too

### Expected behavior
The scroll indicator should be at the edge of the screen

### Actual Behavior
The scroll indicator appears in random places

### Screenshots
<img width="320" alt="Screen Shot 2020-06-18 at 12 58 58 PM" src="https://user-images.githubusercontent.com/4964765/85050185-baad0000-b163-11ea-9e9a-9570d03a2b6b.png">

### Additional context
If I use the `page:afterin` event to start fetching from the backend, the scroll indicator will be in the right position.

**Comment by 11digits** [comment]
What worked for me was to use f7ready insite mounted like so

import { f7, f7ready } from 'framework7-vue';

      f7ready(() => {
///              you code here
          });
      },
