### ISSUE TITLE
iOS: DatePicker on Popup

### ISSUE THREAD

**Issue by linarislamov** [framework7io/framework7#3670]
* Framework7 version: 5.7.8
* Vue.js version: 2.6.11
* Platform and Target: iOS 13.5.1 Cordova app
* cordova-plugin-ionic-webview: ^4.1.3

### Describe the bug
The first datePicker don't close on Popup page

### Screenshots
![](https://i.imgur.com/zhwSquH.gif)

### Additional context
It can be solved partly by adding a backdrop
but the backdrop disappears on the repeated Popup starting

![](https://i.imgur.com/6GtL8S0.gif)

**Comment by shastox** [comment]
Try: routableModals => false in DatePicker

**Comment by linarislamov** [comment]
thanks @shastox 
it's worked
