### ISSUE TITLE
Form storage in routable panels

### ISSUE THREAD

**Issue by kriboogh** [framework7io/framework7#3673]
* Framework7 version: 5.7.8
* Platform and Target: all
* Live Link or JSFiddle: https://jsfiddle.net/4gwfcevs/

### Describe the bug
When you include a form with form store data inside a routable panel, data isn't stored in local storage. Reason is that the form isn't initialised when the panel is made visible. form.js only initialises form storage on tabs and pageInit, but pageInit is never triggered for routable panels.

### To Reproduce
1. Click on right panel
2. Fill in form
3. Check local storage (inspect element in desktop browser)
4. Localstorage is empty.

### Expected behavior
Localstorage should contain an entry f7form-my-form

### Actual Behavior
Localstorage is empty

### Additional context

can be solved by adding (form.js line 309):
  ```
  panelOpen: function panelOpen(panel) {
      var app = this;
      panel.$el.find('.form-store-data').each((index, formEl) => {
        app.form.storage.init(formEl);
      });
    },
    panelClose: function panelOpen(panel) {
      var app = this;
      panel.$el.find('.form-store-data').each((index, formEl) => {
        app.form.storage.destroy(formEl);
      });
    }
```

(Or pageinit should be triggered for routable panels ??? )
Probably also happens for routable modals ?

**Comment by nolimits4web** [comment]
Everything that has kind of "auto initialization" requires View + Page to be initialised. Make sure you form in panel is wrapped with View > Page to work correctly

**Comment by kriboogh** [comment]
But as you can see in the fiddle, there is a view and page tag around the form?
