### ISSUE TITLE
Expandable Search некорректно работает с Large Navbar

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3675]
Ссылка: https://codesandbox.io/s/infallible-gagarin-06l41
Изменения сделаны только в файлы **pages/home.html** и только в том, что изменен **Navbar**.

Как воспроизвести: кликнуть на **Search** (справа в Navbar), будет скролл **page-content**, хотя его не должно быть.

Если убрать класс **navbar-large** и удалить DOM-элемент:

```
<div class="title-large">
          <div class="title-large-text">TITLE</div>
</div>
```

Все становится нормально: клик по Search не вызовет скролл **page-content**.

**Comment by nolimits4web** [comment]
Это только в MD теме?

**Comment by shastox** [comment]
Нет, для обоих тем.

**Comment by nolimits4web** [comment]
> кликнуть на Search (справа в Navbar), будет скролл page-content, хотя его не должно быть.

У меня не воспроизводится, есть может видео или скриншот?

**Comment by shastox** [comment]
Это видео с примера по той же ссылке: https://codesandbox.io/s/infallible-gagarin-06l41

https://yadi.sk/i/FtT58Neum8DGdA
