### ISSUE TITLE
how to use router.on(event, handler) for Vue

### ISSUE THREAD

**Issue by toosui** [framework7io/framework7#3685]
### Describe the bug
**i dont use this ，cant find ducument teach**

### Screenshots
![QQ截图20200730091854](https://user-images.githubusercontent.com/16643466/88869569-bafde800-d245-11ea-9f41-198382aaf310.png)

**Comment by pukarsharma112** [comment]
you can use add it on app params ie. params = {}

**Comment by toosui** [comment]
thanks

**Comment by pukarsharma112** [comment]
> thanks

**Comment by pukarsharma112** [comment]
Did this worked for you?

**Comment by toosui** [comment]
> Did that worked for you?

i dont use ，i use router.on

**Comment by toosui** [comment]
> Did that worked for you?

This is wrong

**Comment by plague69** [comment]
What is the question? Hard to understand.

Are you asking for details about how to use `router.on()` events?

**Comment by toosui** [comment]
> What is the question? Hard to understand.
> 
> Are you asking for details about how to use `router.on()` events?



> What is the question? Hard to understand.
> 
> Are you asking for details about how to use `router.on()` events?

yes i dont ues, how to use?

**Comment by plague69** [comment]
Firstly, questions should go into the forums, not as an issue. This is for issues with the code.

In regards to router.on() and it's use, you need to reference under the "[Router Instance Events](https://framework7.io/docs/view.html#router-instance-events)" section of the doc.

Can be used as such: (I think this is what you are after?)
router.on(_Event_, (_Arguments_) => { /* your function using the arguments */ });
eg:
`View.router.on('pageInit', (pageData) => { console.log(pageData); };`

**Comment by plague69** [comment]
@nolimits4web suggest close
