### ISSUE TITLE
vue版本缺失很多文档

### ISSUE THREAD

**Issue by johnnycsy** [framework7io/framework7#3687]
Missing and incomplete documentation

- <f7-navbar>  click:back  Invalid, need to customize  $f7router.back(). 

- this.$f7router.navigate  Click twice, page exception appears

- Infinite Scroll Can't use

There are many conflicts within the VUE version

**Comment by srbala** [comment]
@johnnycsy Please update issue title in English. Thanks to Bing, it translate it to "The version is missing a lot of documents"

**Comment by plague69** [comment]
> @johnnycsy Please update issue title in English. Thanks to Bing, it translate it to "The version is missing a lot of documents"
"There is a lot of missing documentation for the Vue version of Framework7"

@johnnycsy 
- What is wrong with Infinite Scroll and how to reproduce?
- Can you please define conflicts? or examples
