### ISSUE TITLE
Ошибка с пустым атрибутом value и select

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#3688]
В компоненте роутера у нас есть **select**:

```
<select name="cars" required validate>
        <option value="">Выберите...</option>
        <option value="1">BMW</option>
        <option value="2">Volvo</option>
</select>
```

**value** для первого ```<option>``` пустое. После монтирования компонента **value** вообще исчезает из атрибутов, получается ```<option>Выберите...</option>``` в этом заключается ошибка. Теперь мы выполним код 
```$app.input.validate``` он вернет **true**, а должен вернуть **false**. Если мы вручную в инспекторе для первого ```<option>``` добавим пустой **value**, то уже код ```$app.input.validate``` будет возвращать **false**, что правильно.

Воспроизведение: 
1. Открыть https://codesandbox.io/s/amazing-mcclintock-gzv8e (добавлено только **select**, **button** и метод **valid**)
2. Нажать на кнопку вверху экрана Valid
3. В консоли высветится **true**
4. В инспекторе добавим пустое **value** для первого ```<option>```
5. Нажимаем кнопку Valid - в консоли будет уже **false**.

Примечание:
Пустое **value** для первого ```<option>``` испольузется для правильной валидации, вот рабочий пример: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_select_required

**Comment by shastox** [comment]
Для тех, кто столкнется, вот такое "кривое" решение в pageIni:

```
this.$el.find('select').find('option').each((index, el) => {
   const $el = this.$(el);
   if ($el.attr('value') === null) {
      $el.attr('value', '');
   }
});
```

после этого валидация начинает работать корректно.

**Comment by srbala** [comment]
@shastox It would be great benefit to the community, issues and possible work around are in English. 
Please use it going forward. Here in my attempt for second thread message, Bing translations as follows ...  

> For those who will encounter, here's a "crooked" solution in pageInit: 
```
this.$el.find('select').find('option').each((index, el) => {
   const $el = this.$(el);
   if ($el.attr('value') === null) {
      $el.attr('value', '');
   }
});
```
> validation then starts working correctly.
