### ISSUE TITLE
File input dialog doesn't trigger from button

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#3689]
* Framework7 version: [latest 5]
* Platform and Target: [All]
* Live Link or JSFiddle: https://jsfiddle.net/qsx8kbpz/2/

### Describe the bug
I want to open the file input dialog from a button.  Everything seems to fire correctly but the dialog never opens.  

### To Reproduce
Fiddle show a simple example.  Click browse, dialog opens.  Click open, dialog doesn't.  console.log entries show all events are firing correctly.

### Expected behavior
Should open.

**Comment by shastox** [comment]
Change line:

$$("#file-input").trigger("click");

to

$$("#file-input").click();

**Comment by eradin** [comment]
That worked.  Is there a bug in trigger?  These two methods should work the same.

**Comment by plague69** [comment]
I think this is a Framework7 issue, if you use jQuery's Dom (https://code.jquery.com/jquery-3.5.1.min.js) and `jQuery("#file-input").trigger("click");` it works

**Comment by nolimits4web** [comment]
`$$("#file-input").trigger("click");` and `$$("#file-input").click();` are different things. `.trigger` just triggers the event, while `.click` does the click
