### ISSUE TITLE
In <List sortable>, the sortableSort event never fires

### ISSUE THREAD

**Issue by renefournier** [framework7io/framework7#3692]
According to docs https://framework7.io/docs/sortable-list.html#sortable-events after a sortable <List> is sorted, a sortableSort event should fire. There is no example of how to listen on or capture this event in the docs, but according to documentation it should be something like:

```
  <List sortable on:SortableSort={() => console.log('sorted 1')}>
```
or 
```
  <List sortable onSortableSort={() => console.log('sorted 2')}>
```
But, no workey.

**Comment by srbala** [comment]
@renefournier based on your one line of code does not provide much information to your issue. Check following links. on the demo phone view, click on "Toggle" to see the feature in action

https://framework7.io/react/sortable.html
https://framework7.io/svelte/sortable.html
