### ISSUE TITLE
Progressbar hide doesn't work

### ISSUE THREAD

**Issue by eradin** [framework7io/framework7#3695]
* Framework7 version: latest
* Platform and Target: [browser and perhaps cordova apps but didn't test]
* Live Link or JSFiddle: https://jsfiddle.net/ru03fqh5/

### Describe the bug
app.progressbar.hide() doesn't hide the bar

### To Reproduce
see fiddle

bar is set at 25% on start.  Changed to 50% and then an alert box is shown to verify the 50% indicator.  After alert close, hide should hide the bar.  It doesn't.

### Expected behavior
should hide according to the documentation.

### Actual Behavior
No op.

**Comment by nolimits4web** [comment]
This is only for dynamically created progressbars. If you already have it in DOM, then just set display:block/none on it
