### ISSUE TITLE
[v6 alpha] Reporting of a couple of anomalies

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3700]
* Framework7 version: f7 v6 (Core) from **alpha 4** to **alpha 10**
* Platform and Target: Mac 10.11.6 El Capitan with Safari 11.1.2 and Firefox 78.2.0esr browsers

### Describe the bug
I started testing the various alpha of f7 version 6 with Kitchen Sink and I noticed that, while in alpha 1 to 3 these anomalies do not occur, in **alpha 4 to 10** the following anomalies occur:

1. The links to the pages in the **left side panel** (_Accordion_, _Action Sheet_, etc.) do not work
2. The links to change the **theme** - _iOS Theme_, _Material (MD) Theme_ and _Aurora Desktop Theme_ - produce, almost every time they are selected, the error page "**Not found** - _Sorry_ - _Requested content not found._" after changing the theme

**Comment by nolimits4web** [comment]
Do you see it in Core or React version?

**Comment by nolimits4web** [comment]
Thanks, fixed now
