### ISSUE TITLE
[v6 alpha] Swiper's examples don't work correctly

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3701]
* Framework7 version: f7 v6 (Core) up to **alpha 10**
* Platform and Target: Mac 10.11.6 El Capitan with Safari 11.1.2 and Firefox 78.2.0esr browsers

### Describe the bug
In my testing of the various alpha of f7 version 6 with Kitchen Sink I noticed that the **Swiper's examples** don't work correctly.

Instead the examples published at this link: https://swiperjs.com/demos/ work correctly.

**Comment by nolimits4web** [comment]
Fixed in https://github.com/framework7io/framework7/commit/2fc021c86192766befac3e8ab35bb41c59d30780
