### ISSUE TITLE
Bug when closing popup from panel

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3720]
* Framework7 version: latest
* Vue.js version: latest
* Platform and Target: iOS (web or cordova)
* Live Link or JSFiddle: https://pitouli.fr/tempsharing/bug-panel-popup-framework7.htm + https://jsfiddle.net/unes52o3/1/

### Describe the bug
I was saying in this issue https://github.com/framework7io/framework7/pull/3630#issuecomment-633143661 that there was a bug when opening a push popup from a panel: the main page was keeping "white corners" when everything was closed.
I just discovered there is a bigger issue: if you then switch to landscape mode, then the page is completely broken (it stay at portrait width for part of it, and go to landscape with for the rest of it).
 
### To Reproduce
1. Go to https://pitouli.fr/tempsharing/bug-panel-popup-framework7.htm with an iphone (same code than https://jsfiddle.net/unes52o3/1/, but you cannot reproduce the bug on jsfiddle), in portrait mode
2. Click on ''Panel Left'
3. Click on 'Popup'
4. Close Popup ; observe there is now "white corners" on the main page
5. Close Panel Left
6. Turn the phone on landscape mode
7. Observe the bug

Note : there is a similar bug if you go from landscape to portrait, except it's the bottom of the page that is cropped.

### Screenshots
![IMG_3576](https://user-images.githubusercontent.com/542778/94274453-04b53700-ff46-11ea-9bff-16f40dfaae4a.PNG)
![IMG_3577](https://user-images.githubusercontent.com/542778/94274441-01ba4680-ff46-11ea-8403-0cb22230652c.PNG)

**Comment by nolimits4web** [comment]
Well, it seems like it is Safari rendering issues as there are no any styles that can cause this. Will investigate
