### ISSUE TITLE
Text Editor in List Input in Svelte does not work

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3723]
* Framework7 version: 5.7.12
* Svelte version: 3.20.1
* Platform and Target: Mac 10.11.6 El Capitan with Safari 11.1.2 and Firefox 78.3.0esr browsers
* Live Link or JSFiddle/CodeSandbox:

https://framework7.io/kitchen-sink/svelte/index.html?theme=ios
https://framework7.io/docs-demos/svelte/text-editor.html

### Describe the bug
As soon as you try to enter text in the "About" field of the Text Editor in List Input examples included in Kitchen Sink and in the "Text Editor Svelte Component" page, the browser tab freezes and shows the "spinning wait cursor" (in Safari) or a message that "browser operation is slowed down by a web page" (in Firefox) and you can't go on.

### To Reproduce
https://framework7.io/kitchen-sink/svelte/index.html?theme=ios
https://framework7.io/docs-demos/svelte/text-editor.html

### Expected behavior
In the Core, React and Vue versions the Text Editor in List Input works correctly.

**Comment by DAnn2012** [comment]
Hello @nolimits4web ,

Could this change also affect these lines or are they okay?

https://github.com/framework7io/framework7/blob/5ad505d2aa948aad51985c3e38ef96bc5cacce75/src/svelte/components/list-input.svelte#L670-L673

https://github.com/framework7io/framework7/blob/5ad505d2aa948aad51985c3e38ef96bc5cacce75/src/svelte/components/input.svelte#L438-L441

https://github.com/framework7io/framework7/blob/5ad505d2aa948aad51985c3e38ef96bc5cacce75/src/svelte/components/input.svelte#L607-L610

Thank you.

**Comment by nolimits4web** [comment]
@DAnn2012 you are right, pushed fix for those too
