### ISSUE TITLE
Custom component props can't pass object

### ISSUE THREAD

**Issue by gmkseta** [framework7io/framework7#3727]
* Framework7 version: v5.7.12

##
![image](https://user-images.githubusercontent.com/26623194/94676921-02444a00-0357-11eb-9a91-bc1e161eafda.png)

In general, react js  and vuejs can send objects or arrays to props.

However, it is not possible to send objects from the framework7 core.

I think we need some of helper

**Comment by shastox** [comment]
```
Template7.registerHelper('jsonStringify', function (data, options) {
    if (data.value && typeof data.value === 'string') {
        data.value  = data.value.replace("'", "&#39;");
    }
    return JSON.stringify(data);
});
```
```
<list-item data-item='{{jsonStringify this}}'></list-item>
```
