### ISSUE TITLE
MD: Missing Popover Angles

### ISSUE THREAD

**Issue by phoebusryan** [framework7io/framework7#3729]
I am not sure if this is a bug or a feature... Is there a reason that Popovers in MD-Theme doesn't have angles?

**Comment by nolimits4web** [comment]
Yes, It is a feature because there is no popovers angles in official MD theme guides

**Comment by fishsaidno** [comment]
That's understandable reasoning. However, our user testing has shown that: a reasonable percentage of (android) users get confused by the lack of context as to what they clicked on to trigger the popover. 

Unfortunately, the `md` theme's popover style can't be overridden by adding `ios` or `aurora` classes - the rendering of the angle is broken.
