### ISSUE TITLE
Kitchen Sink Core Links Fail on iOS via Cordova

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [framework7io/framework7#3733]
I have pulled the latest Framework7 from GitHub, having used it previously, so I have experience with it.

I pulled down the latest kitchen sink and extracted only the core folders and copied the required .js and .css and pointed index.html to them. I then hosted these files (attached)
[kitchen-sink-ios.zip](https://github.com/framework7io/framework7/files/5322092/kitchen-sink-ios.zip)
on my own web server [https://apex.trisys.co.uk/legacy/development/test/f7/kitchensink](https://apex.trisys.co.uk/legacy/development/test/f7/kitchensink) to test that all worked perfectly standalone. 
As you can see, the component links all work perfectly as expected.

I then moved these files/folders onto my macOS Sierra laptop and built with Cordova. It built perfectly and I was able to test it both in the Xcode iPhone simulator and an actual connected iPhone.

The problem is that whilst the kitchen-sink application opens as expected, none of the links to components works on both the simulator and iPhone. I attach a video showing this on the iOS simulator: 

[framework7-ios.zip](https://github.com/framework7io/framework7/files/5322130/framework7-ios.zip)

You should see that non component links work as expected. It is only the router href's which do not work.

I know that this may be either a Framework7, Cordova or an Apple problem, however I felt it worth while to send you this report so that you are aware of this given that Apple has released a iOS 14 this last week.

**Comment by TriSysBusinessSoftware** [comment]
So I have narrowed this down to the router as the cause.
Both of these work when deployed via a web site:

```
<a class="item-content item-link" href="/about/">
<a class="item-content item-link" href="#" onclick="app.views.main.router.navigate({ name: 'about' })">
```

However both of these fail when deployed via Cordova to an iPhone.

**Comment by nolimits4web** [comment]
KS is not indented to be a just drop-in for cordova apps. You need to properly configure cordova iOS v6 to work properly with XHR requests

**Comment by TriSysBusinessSoftware** [comment]
I was simply looking for a starting point. I did this exact same process years ago and it worked perfectly. I was hoping to upgrade to the latest F7, but that will no longer be possible as I do not understand why the default behaviour which works fine in a web page has to be configured differently to work in Cordova. I do not understand what this means "need to properly configure cordova iOS v6 to work properly with XHR requests".

**Comment by nolimits4web** [comment]
>  I did this exact same process years ago and it worked perfectly

The process how cordova works on iOS has dramatically changed

> I do not understand what this means "need to properly configure cordova iOS v6 to work properly with XHR requests".

Use forum search (https://forum.framework7.io) about cordova v6 info and how to make it work

> I was simply looking for a starting point

https://framework7.io/cli/

**Comment by TriSysBusinessSoftware** [comment]
Thanks for your super-quick response.
