### ISSUE TITLE
MD theme on iPad instead of iOS when theme=auto

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3737]
* Framework7 version: 5.7.12
* Platform and Target: iPad iOS 14 **EMULATOR** (no physical device access to test on)

### Describe the bug
On emulator iPad (tested on 8th gen & Air 4th gen) the app is rendered with the MD theme (both with Cordova and the web) when theme=auto.

### To Reproduce
Go to: https://framework7.io/kitchen-sink/core/ from the emulator

### Expected behavior
Should be the iOS theme when "auto" is selected

### Additional context
I do not have a real iPad available to test.
It works as expected on iPhone (both emulator and physical)

It seems it's because of the "desktop first" iPad browser: 
https://developer.apple.com/videos/play/wwdc2019/203/
https://github.com/firebase/firebase-js-sdk/issues/3598

**Comment by Pitouli** [comment]
Ok, in fact, you already did the correction
https://github.com/framework7io/framework7/commit/9d2dee14caea4c2a431357e2b70bdeef247f370f

But it appears that, at least on iOS 14, the window.screen.width and height do not return expected values, so the detection fails. Perhaps you could use the "Mobile" keyword in the userAgent string? It seems it appears on Safario iOS but not on Safari Mac.

**Comment by nolimits4web** [comment]
What is returned with `window.screen.width` and `height` for you?

**Comment by Pitouli** [comment]
iPad Air - 4th Generation - 14.0

> window.screen.width
< 820
> window.screen.height
< 1180

And we can observe that the overlay does not cover the footer.
(and you can observe that Firebase also fails at detecting the iPad, that's why there is this error alert)

![Simulator Screen Shot - iPad Air (4th generation) - 2020-10-08 at 10 29 39](https://user-images.githubusercontent.com/542778/95434150-36200080-0951-11eb-9db8-69fc1ff6895c.png)

**Comment by Pitouli** [comment]
iPad - 8th generation - 14.0

```
> window.screen.width
< 810
> window.screen.height
< 1080
```
And same issue with the overlay, that goes under the status bar, but leave a gap the size of the status bar below.

![simulator_screenshot_D010773A-B7C8-45CB-A656-5B3F5E4994B6](https://user-images.githubusercontent.com/542778/95434811-01607900-0952-11eb-9070-9ee82eb5f3b6.png)

**Comment by nolimits4web** [comment]
Ok, seems like they just increased screen sizes in these last gen devices. I will just add these sizes to device detection script
