### ISSUE TITLE
SmartSelect display value is not updated if it is changed outside control

### ISSUE THREAD

**Issue by AliMamed** [framework7io/framework7#3741]
* Framework7 version: 5.x.x
* React.js version: 16.x.x
* Platform and Target: browser
* [JSFiddle](https://jsfiddle.net/alimamed/orzep1x8/6/)

### Describe the bug
Say we have list with SmartSelect and it's value is stored in state. Our ss opens in Page. It works normally if user clicks on smartselect and selects different value.
But if we have some other logic that modifies the state including this smartselect value, then the display value of smartselect in list is not updated.

### To Reproduce
1. Go to [JSFiddle](https://jsfiddle.net/alimamed/orzep1x8/6/)
2. Select something except 'Banana' in Fruit selector. - works fine
3. Now click blue button - display value in list is not changed. While if you click on SmartSelect you will see radiobutton at correct value

My current workaround is to reinit all smart-selects on page on componentdidupdate which is too much straight forward 😊 
Please fix this at least in v6

**Comment by nolimits4web** [comment]
Because it is not possible to detect changes from outside on nested Select, just output value text manually like here https://jsfiddle.net/q56rpvgz/

**Comment by AliMamed** [comment]
Thanks! Would be great to have your example in docs!
