### ISSUE TITLE
When to adapt to Vue3.0

### ISSUE THREAD

**Issue by AlwaysLoveme** [framework7io/framework7#3746]
* Framework7 version: [e.g. 3.0.0]
* Vue.js version: [e.g. 2.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
In v6
