### ISSUE TITLE
The Svelte ListInput (and other) components don't support bind:value={value}

### ISSUE THREAD

**Issue by amit777** [framework7io/framework7#3749]
* Framework7 version: 5.7.13
* Svelte version:  3.29.4
* Platform and Target: [Desktop]

### Describe the bug
if I have a <ListInput> with Svelte's bind:value syntax (like below), the foo variable doesn't 2-way bind.
```
 <ListInput
      label="Test Input"
      type="text"
      bind:value="{foo}"
    ></ListInput>
```
### To Reproduce
1. Create a simple ListInput as above
2. Test 2-way binding

### Expected behavior
2-way data binding should work

### Additional context
I found this forum post that describes the same issue.  https://forum.framework7.io/t/how-to-bind-a-value-to-svelte-input/9656

It seems like binding should just work since it's a core feature of svelte.

**Comment by DanielBanobreDopico** [comment]
Yeah.
This is a fundamental Svelte feature.

**Comment by nolimits4web** [comment]
Closing as was fixed in v6
