### ISSUE TITLE
[v6 alpha 11] Theme Color change in KS does not work correctly for MD theme

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3752]
* Framework7 version: v6.0.0 alpha 11 
* Platform and Target: Mac 10.11.6 El Capitan with Safari 11.1.2 browser

### Describe the bug
Theme color change from "Color Themes" page of KS included in f7 v6 alpha 11 does not work correctly for MD theme.

I think this is due to this recent change: https://github.com/framework7io/framework7/commit/8ec605996e4ed1652b5838ea82aaabad5e0993c6

**Comment by nolimits4web** [comment]
Fixed in v6 branch
