### ISSUE TITLE
Error in the "sources" field of the f7 Source map files?

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3755]
I noticed that in the Source map files that are included in f7 (for example `framework7.bundle.min.js.map` which is indicated in the `sourceMappingURL` of the `framework7.bundle.min.js` file) in the `"sources"` field is indicated `["0"]`.

![f7-map](https://user-images.githubusercontent.com/1197819/97619775-ec42ab80-1a20-11eb-9fa6-c3ca4c8dda59.png)

This causes a _file not found (404) error_ in the browser developer tools as the source map of the min.js file looks for a "0" file that does not exist.

![f7-0](https://user-images.githubusercontent.com/1197819/97619834-011f3f00-1a21-11eb-880d-9bfe88ed3fe8.png)

I report this because I saw that, for example, in the jquery-2.2.4.min.js.map file the "sources" field contains ["jquery-2.2.4.js"] and the browser developer tools load this file as Source map of the min.js file.

![jquery-map](https://user-images.githubusercontent.com/1197819/97619888-172cff80-1a21-11eb-8ce5-2e84e12fb9c3.png)

**Comment by DAnn2012** [comment]
In the `"sources"` field of [framework7.min.js.map](https://github.com/framework7io/framework7/blob/v3/packages/core/js/framework7.min.js.map) (**framework7 v3.6.7**) is indicated `["framework7.js"]`

![f7-v3-map](https://user-images.githubusercontent.com/1197819/97696828-6a956100-1aa6-11eb-9303-bf52bb0be6e3.png)

In the `"sources"` field of `framework7.bundle.min.js.map` (**framework7 v6.0.0 alpha 15**) is indicated

![f7-v6a15-map](https://user-images.githubusercontent.com/1197819/97697301-1b036500-1aa7-11eb-9d74-c6d8e1dac179.png)

is it okay now?

**Comment by DAnn2012** [comment]
@nolimits4web It is also about [swiper.min.js.map in swiper.js 5.x](https://unpkg.com/browse/swiper@5.4.5/js/swiper.min.js.map) and [swiper-bundle.min.js.map in swiper.js 6.x](https://unpkg.com/browse/swiper@6.3.5/swiper-bundle.min.js.map)

**Comment by nolimits4web** [comment]
@DAnn2012 should be ok as it is building source map from original source files, but i will double check. And will fix it in Swiper side too

**Comment by nolimits4web** [comment]
Checked, it works correctly
