### ISSUE TITLE
Latest release in the sidebar

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3767]
I note that as the _latest_ release in the sidebar is reported **version 5.7.6**

![f7-latest-release-sidebar](https://user-images.githubusercontent.com/1197819/98929532-8ef83100-24db-11eb-81e4-10ed0b87a1e9.png)

**Comment by DAnn2012** [comment]
@nolimits4web As soon as you can, could you take a look?

Thanks.

**Comment by DAnn2012** [comment]
@nolimits4web I close this issue because I saw that the **Releases** section in the sidebar has been completely removed.

**Comment by nolimits4web** [comment]
@DAnn2012 yes, found an easiest fix 😄

But actually doing proper releases requires too complex CI/toolchain, so I decided not to go wit it, as anyway it is not too useful
