### ISSUE TITLE
how to effective my scss with variable ?

### ISSUE THREAD

**Issue by Summer-andy** [framework7io/framework7#3769]
in this way : 
.ListInfo {
  --f7-list-item-title-font-size: 14px;
  --f7-list-item-title-text-color: #333333;
  --f7-list-item-after-text-color: #333333;
  --f7-list-item-after-font-size: 14px;
}
 the style is effective, but in this way: 
$fontSize: 14px;
$color: #333333;

.ListInfo {
  --f7-list-item-title-font-size: $fontSize:;
  --f7-list-item-title-text-color: $color;
  --f7-list-item-after-text-color: $color;
  --f7-list-item-after-font-size: $fontSize:;
}

it doesnt work

**Comment by AliMamed** [comment]
Hi you need to correct your syntax according to this [note](https://sass-lang.com/documentation/breaking-changes/css-vars):

```
$fontSize: 14px;
$color: #333333;

.ListInfo {
--f7-list-item-title-font-size: #{$fontSize};
--f7-list-item-title-text-color: #{$color};
--f7-list-item-after-text-color: #{$color};
--f7-list-item-after-font-size: #{$fontSize};
}
```

**Comment by Summer-andy** [comment]
thanks!
