### ISSUE TITLE
Source Code npm install error on Windows

### ISSUE THREAD

**Issue by xclw2000** [framework7io/framework7#3774]
I follow the instruction [http://www.framework7.cn/react/kitchen-sink.html](url) to run Kitchen Sink locally.
But when I step to Step 4: npm install I got erros
![image](https://user-images.githubusercontent.com/32091566/99890510-0592ec80-2c9b-11eb-8856-f9aecec8c921.png)
and I can't continue.
How to resolve this?

My environment
![image](https://user-images.githubusercontent.com/32091566/99890603-109a4c80-2c9c-11eb-911f-02ba529df2a8.png)

**Comment by chancyk** [comment]
@xclw2000 I ran into this same problem. I think it's an issue in the swiper dependency that is pinned at version 6.3.5 in F7, but was subsequently fixed.

See this swiper issue titled [Line breaks can't be quoted on Windows](https://github.com/nolimits4web/swiper/issues/3985).

**Comment by chancyk** [comment]
Here's a workaround I've used for now.
```bash
mkdir project
cd project
npm install framework7
# open package.json with some text editor
notepad node_modules\framework7\package.json
# edit the swiper dependency to be 6.4.5 instead of 6.3.5
```
and then proceed with the framework7-cli install `f7 create`, but the only thing I've been able to get working on Windows for now is the Core package without the Webpack bundler.
