### ISSUE TITLE
[framework7-svelte] MessagebarSheetImage: no background-url style

### ISSUE THREAD

**Issue by vladdancer** [framework7io/framework7#3776]
This [commit](https://github.com/framework7io/framework7/commit/2100a99d50101e46e8a64402a7cf20a9d63fa920#diff-5714ba4af35367da3ddaf887a43a5f6f117308b9dbfc12459df8d7fc22c11cfb) removed `style` attribute from `src/svelte/components/messagebar-sheet-image.svelte` that is used for `background-image` on attachment.

You can check it on documentation site: 
https://framework7.io/svelte/messagebar.html

**Comment by nolimits4web** [comment]
closing as fixed a while ago
