### ISSUE TITLE
button style bleeds outside of f7

### ISSUE THREAD

**Issue by jacobg** [framework7io/framework7#3783]
See this code sandbox, which creates a button from another ui widget library on an f7 page:
https://codesandbox.io/s/f7-maz-vue-dpnej?file=/src/pages/Maz.vue

As the screenshot below shows, f7 applies a global `button` css style that affects non-f7 components.

f7 should make sure that its styles are scoped only to f7 widgets and layouts.

![Screen Shot 2020-12-08 at 11 01 22 AM](https://user-images.githubusercontent.com/736985/101507897-0e471c00-3945-11eb-8d9c-607b0463328d.png)

**Comment by nolimits4web** [comment]
> f7 should make sure that its styles are scoped only to f7 widgets and layouts.

It is not possible, only with ugly classes like `f7-button`. But I don't want to force people to write a lot of extra markup. Just tweak styles to make it look appropriate. Always there will be a library that can affect (or be affected) with styles
