### ISSUE TITLE
No transition on root views when closing a pushing popup because of "!important" keyword

### ISSUE THREAD

**Issue by Pitouli** [framework7io/framework7#3786]
When sliding down a pushing popup, the popup behind move back in place following the finger movement.
But the main views do not follow, and wait for the complete closing of the popup before moving back in place.

After analyse, it's only because of the "!important" keyword here:
https://github.com/framework7io/framework7/blob/78d29c14de9facb26a763a595e3d70f06e929f9e/src/core/components/popup/popup.less#L139

But I suppose that it is there for a reason.
Do you remember why this "!important" is required? :)

Edit: in fact, it has been added in the same commit that was correcting an issue I raised myself few months ago!
https://github.com/framework7io/framework7/commit/1b2cc36af7cf1960a77a73bb7c9488311f969b1c

But technically, I do not see why it is required.

**Comment by nolimits4web** [comment]
It is already fixed in v6
