### ISSUE TITLE
[Vue] Props

### ISSUE THREAD

**Issue by georgemark0v** [framework7io/framework7#3787]
"framework7": "^5.7.14",
"framework7-vue": "^5.7.14",
"vue": "^2.6.11"

How vue props works in f7? I'm passing object through router to page and seems its creating new object. When im update some property its not make changes on another page but reactivity works only on current page.

Methods to route from Page №1 on Page №2:

```
this.$f7.view.current.router.navigate(`/chat${chat.id}`, {
       props: {
           chat: chat
        }
});  
```

Page №2 on mounted 

`this.chat.isBackground = false;`

But on Page №1 property isBackground still true

**Comment by stanleyxu2005** [comment]
You can try to use `context` instead of props
