### ISSUE TITLE
Comment line that contains `$render` will crash Single File Component

### ISSUE THREAD

**Issue by khlau10** [framework7io/framework7#3801]
* Framework7 version: 6.0.1
* Platform and Target: Cordova App
* Live Link or JSFiddle: Can't demonstrate it on JSFiddle because it involves separate Single File Component.

### Describe the bug
When using Framework7 Core Router Component (Single File Component), a commented line that contains `$render` before `return $render;` will cause the following error in the browser console:
`Uncaught SyntaxError: Unexpected token '}'`

### To Reproduce
1. Create the Single File Component with the following code:
```
<template>
	<div class="page">
		<div class="page-content">
			<div class="block block-strong">
				<p>Here is your blank Framework7 app. Let's see what we have here.</p>
			</div>
		</div>
	</div>
</template>
<style>

</style>
<script>
	export default (props, { $h, $f7, $on }) => {
		// $render
		return $render;
	}
</script>
```
2. `$ npm run start`
3. In the opened browser, the page is not rendered
4. In the browser developer console, there is this line of error: `Uncaught SyntaxError: Unexpected token '}'`

### Expected behavior
The page should render the contents successfully

### Actual Behavior
The page contents is not rendered

### Screenshots
https://postimg.cc/PPBDKCM9

### Additional context
- The project setup is WITHOUT using bundler (webpack)
- The Single File Component is used in `index.html` as per below:
```
...
<div id="app">
    <!-- Your main view, should have "view-main" class -->
    <div class="view view-main view-init safe-areas" data-url="/home"></div>
 </div>
...
```

- The `routes.js` is as per below:
```
var routes = [
  {
    path: '/',
    url: './index.html',
  },
  {
    path: '/home',
    componentUrl: './pages/home.f7.html',
  }
];

```
- After remove the comment line that contains `$render`, the page rendered correctly.

**Comment by nolimits4web** [comment]
Because component parser will replace `$render` occurrences with render function that will produce and error. Just don't do it

**Comment by khlau10** [comment]
> Because component parser will replace `$render` occurrences with render function that will produce and error. Just don't do it

If this is the case, then the sample code in https://framework7.io/docs/router-component.html#single-file-component should be corrected to not using `$render` in comment.
I used the sample code and triggered this error, was spending some time to figure out what's the problem.
