### ISSUE TITLE
Error when setting the browserHistorySeparator to an empty string

### ISSUE THREAD

**Issue by damerick** [framework7io/framework7#3803]
* Framework7 version: 6.0.1
* Platform and Target: Firefox browser

### Describe the bug
I set the server rewrite to index.html.
After enabling browserHistory and setting the browserHistorySeparator to an empty string, with the page reloaded, I saw a blank screen and 2 errors in the console.

But it works fine with Framework7 version 5.

### To Reproduce
1. In app.js:
![screenshot](https://user-images.githubusercontent.com/54470578/103635552-a60b4a80-4f83-11eb-8360-dc5575625297.png)
2. Go back to the browser and reload the page:
![screenshot](https://user-images.githubusercontent.com/54470578/103636962-b4f2fc80-4f85-11eb-9f48-3c6b8f85b675.png)

### Expected behavior
No errors, and the page renders correctly.

### Actual Behavior
2 errors, blank page.

**Comment by nolimits4web** [comment]
This basically means there is an error loading route -> you have some misconfiguration of routes/browser-history

**Comment by damerick** [comment]
In the routes config, I changed:

  // About page
  {
    path: '/about/',
    **url: './pages/about.html',**
    name: 'about',
  }


to:

  // About page
  {
    path: '/about/',
    **url: '/pages/about.html',**
    name: 'about',
  }

Problem solved.
