### ISSUE TITLE
View loaded via data-url v6.0.1

### ISSUE THREAD

**Issue by Gbandza** [framework7io/framework7#3804]
* Framework7 version: 6.0.1
* Platform and Target: Chrome browser + Safari browser
* Live Link or JSFiddle: https://jsfiddle.net/Jeelig/kmv503tr/6/

### Describe the bug
I tried to move an application from v5 to v6, but I faced an issue regarding views.
Actually, in v5 it was possible to create a view and link a html file through the route, and load it (excuse my french). An example below, from the JSFiddle I created : 
```
<div id="view-tickets" class="view view-init tab view-tickets" data-name="tickets" data-url="/tickets/">
        <!-- tickets page will be loaded here dynamically from /tickets/ route -->
</div>
```
This is currently KO with v6.0.1.

### To Reproduce
Steps to reproduce the behavior (JS Fiddle) :
1. Go to burger menu
2. Click on 'Tickets'

### Expected behavior
Show the page defined in the route file (ex: tickets.html in my case)

### Actual Behavior
Shows a blank page

**Comment by nolimits4web** [comment]
In v6 it works in the same way. Would be good to see live example with the issue. JSFiddle you provided uses Framework7 v4
