### ISSUE TITLE
 Trigger input event  if have input, not need value changed or add an API.

### ISSUE THREAD

**Issue by rwsbillyang** [framework7io/framework7#3817]
I am using Input F7  React v6.0.6 for image file upload. The process is:  select a local image file -> crop -> upload binary data

It's no problem when firstly select a file or select a different file. But when select a same file again, nothing happens except blur and focus.  The input event is not triggered as explained in doc :
> input | (event) | Fired immediately when input value changed. Note: Input event triggers after beforeinput, keypress, keyup, keydown events.

It's difficult to enter the next process of cropping again unless do an extra operation of clear.

**Comment by nolimits4web** [comment]
If you select same file then file input won't trigger "change" it is native browser behavior. You need to manually clear its value then
