### ISSUE TITLE
[v6] Using HTML Img tag in template page causes app load error

### ISSUE THREAD

**Issue by willmero** [framework7io/framework7#3819]
* Framework7 version: 6.0.4
* Platform and Target: web, chrome, iOS Safari

### Describe the bug
I seem to be getting an error initalizing the Framework7 app if I try to use an img that is sourced from the local img directory when used inside a templated page (like home.html for example).

Error: 
`Uncaught (in promise) Error: TypeError: Cannot create property 'elm' on string 'div,[object Object],[object Object],[object Object]' at framework7-bundle.js:12329`

This also happens if I use the lazy image option. I can only get local images to load if I use the div background lazy load option, so it seems to be an issue specifically with the img tag itself.

### To Reproduce
1. Fork F7 V6 kitchen sink
2. In the home.html file, insert any image like 
`< img src="./img/beach.jpg">`
3. Reload the app, and observe the error

### Expected behavior
The app loads with the image loaded

### Actual Behavior
App fails to load. Only index.html is showing, but default home route is not initialized

**Comment by nolimits4web** [comment]
Hey @willmero v6 template is very strict about self-closing tags https://framework7.io/docs/router-component.html#component-template

It needs to be `<img src="./img/beach.jpg" />` to work correctly

**Comment by maqeelqureshi** [comment]
For me tempate7 expressions are generating the same error when migrating from V5 to V6. And I have no idea how to migrate with minimum changes in the actual code.

   <template>
      {{userName}}
   </template>
   <script>
     export default (props, { $f7,  $on    }) => {
       alert(LastloggedInUser);
       let userName = LastloggedInUser || "";
       return $render;
     }
   </script>

**Comment by maqeelqureshi** [comment]
> Hey @willmero v6 template is very strict about self-closing tags https://framework7.io/docs/router-component.html#component-template
> 
> It needs to be `<img src="./img/beach.jpg" />` to work correctly

For me tempate7 expressions are generating the same error when migrating from V5 to V6. And I have no idea how to migrate with minimum changes in the actual code as I have extensive use of such expressions on 30+ screens.

   <template>
      {{userName}}
   </template>
   <script>
     export default (props, {      $f7,       $on     }) => {
       alert(LastloggedInUser);
       let userName = LastloggedInUser || "";
       return $render;
     }
   </script>
