### ISSUE TITLE
Wrong typings path

### ISSUE THREAD

**Issue by sinapcs** [framework7io/framework7#3820]
* Framework7 version: 6.0.7
* Platform and Target: Doesn't matter

### Describe the bug
When you want to import ES Modules in a typescript based project you get a missing type definition error.

### To Reproduce
1. start a new Create React App project with TypeScript
```
npx create-react-app my-app --template typescript
```
2. import a component from `framwork7/components`
```js
import Tabs from "framework7/components/tabs";
```
3. See error
`Could not find a declaration file for module 'framework7/components/tabs'. `

### Expected behavior
The `typings` value in `package.json` of a component should look like this:
```json
  "typings": "../../types/components/component_name/component_name.d.ts"
```

### Actual Behavior
The current `typings` value is:
```json
  "typings": "../../types/components/component_name.d.ts"
```
which is missing the `component_name` directory.

**Comment by nolimits4web** [comment]
Fixed by #3821
