### ISSUE TITLE
<img> tag breaks the component?

### ISSUE THREAD

**Issue by allnash** [framework7io/framework7#3826]
* Framework7 version: 6.0.11
* Platform and Target: ALL

### Describe the bug
I created a new app with the CLI, Cordova, iOS, Android and PWA.
In the home page, I added <img> tag to display logo. The page goes white.
No idea what the issue is.
I replaced the img src to an external image on the web, still white page.
If I remove the tag it works. The tag is correct.

**Comment by allnash** [comment]
I think this bug is specific to the way the CLI generates the project. Something is happening with the path resolver plugin. Do you want me to post the generated project? Also I am unable to see the components. What happened to the good old browser debugging capability.

**Comment by nolimits4web** [comment]
https://framework7.io/docs/router-component.html#component-template

> All self-closing tags must be closed!. If you will have not closed self-closing tags like <br>, <img src="">, <input ...>, then compiler will throw an error.

**Comment by allnash** [comment]
Thanks for the reply
