### ISSUE TITLE
v6 App theme prop is not reactive

### ISSUE THREAD

**Issue by AliMamed** [framework7io/framework7#3833]
* Framework7 version: 6.0.11
* React.js version: 17.0.1
* Platform and Target: Chrome browser
* Live Link: https://codesandbox.io/s/magical-nobel-jdi9c

### Describe the bug
Changing `App`'s prop `theme` via state doesn't cause any changes to app's theme.

### To Reproduce
1. Go to https://codesandbox.io/s/magical-nobel-jdi9c
2. Click on theme name in list
3. Click on 'Root class' link to show `html`'s element class

**Comment by nolimits4web** [comment]
Sorry, but It is by design, theme can not be changed dynamically after initialization. Too many internals depend on it

**Comment by AliMamed** [comment]
clear, thx for the answer
