### ISSUE TITLE
progressbar typing typo

### ISSUE THREAD

**Issue by juanreynolds** [framework7io/framework7#3834]
version: 6.0.12

file: progressbar.d.ts
line: 12

error: 
`ref?: React.MutableRefObject<{el: HTMLElement | null; set: (progress: number; duration: number) => void}>;`

solution:
```
  ref?: React.MutableRefObject<{el: HTMLElement | null }>; 
  set: (progress: number, duration: number) => void;
```

**Comment by nolimits4web** [comment]
What is the typo/error? Progressbar ref contains `el` and `set` properties

**Comment by nolimits4web** [comment]
https://github.com/framework7io/framework7/blob/master/src/react/components/progressbar.jsx#L27-L30

**Comment by juanreynolds** [comment]
It is in the typings file (progressbar.d.ts):

```
interface ProgressbarProps {
  slot?: string;
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  progress ?: number;
  infinite ?: boolean;
  **ref?: React.MutableRefObject<{el: HTMLElement | null; set: (progress: number; duration: number) => void}>;**
  color?: string;
  colorTheme?: string;
  textColor?: string;
  bgColor?: string;
  borderColor?: string;
  rippleColor?: string;
  themeDark?: boolean;
}
```

It is supposed to be two separate properties: ref and set. 
Currently the set property is missing as it is part of the type of the ref property:

Incorrect:
`React.MutableRefObject<{el: HTMLElement | null; set: (progress: number; duration: number) => void}>`
Correct:
`ref?: React.MutableRefObject<{el: HTMLElement | null }>;set: (progress: number, duration: number) => void;`

The correct line above I put on one line to show the difference but it is actually two properties and will go on two lines.

If it is transpiled node console gives the following errors:
ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
12:78-79
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(12,79)
      TS1005: ',' expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
12:96-97
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(12,97)
      TS1005: ';' expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
12:98-100
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(12,99)
      TS1131: Property or signature expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
12:106-107
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(12,107)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
12:107-108
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(12,108)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
13:8-9
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(13,9)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
14:13-14
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(14,14)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
15:12-13
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(15,13)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
16:10-11
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(16,11)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
17:14-15
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(17,15)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
18:14-15
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(18,15)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
19:12-13
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(19,13)
      TS1109: Expression expected.

ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts
20:0-1
[tsl] ERROR in /home/juan/mobile_app/mobile_cms/framework7-react/node_modules/framework7-react/components/progressbar/progressbar.d.ts(20,1)
      TS1128: Declaration or statement expected.

**Comment by leecrossley** [comment]
Would be great to get this fix published ASAP! Much appreciated.
