### ISSUE TITLE
Datetime picker issue: "RangeError: Invalid time value"

### ISSUE THREAD

**Issue by juanreynolds** [framework7io/framework7#3841]
* Framework7 version: 6.0.12

### Describe the bug
I refer https://forum.framework7.io/t/vue-datetime-picker-issue-rangeerror-invalid-time-value/12387
DatePicker allows for values as strings which comes in handy when one needs to pass in values from serializable data model.
When timePicker is set to true it fails. 

### To Reproduce
Initialise DatePicker with calendarParams: { timePicker: false }
In a managed form (React etc) pass in an array of string date values.
The datePicker works as expected.

Initialise DatePicker with calendarParams: { timePicker: true }
In a managed form (React etc) pass in an array of string date values.
The datePicker crashes.

If I look through the code I can see places where calendar.value[i] is converted to a new Date, ie: line 678:
`if (new Date(newValue).getTime() === new Date(calendar.value[i]).getTime()) {`
Here getTime is called on a Date object no matter if calendar.value[i] is a Date object or a string.
In other places in the code getTime() (or some other time function) is called on  calendar.value[i] directly without ensuring it is a Date object. I have highlighted the places in the code where this is the case with the suggested fix. 

### Fix (calendar-class.js)
line 300:
```
- valueToAdd.setHours(calendar.value[0].getHours(), calendar.value[0].getMinutes());
+ var date = new Date(calendar.value[0]);
+ valueToAdd.setHours(date.getHours(), date.getMinutes());
```

line 697:
```
- if (calendar.value.length === 0 || Math.abs(calendar.value[0].getTime() - newValue.getTime()) >= (rangePickerMinDays - 1) * 60 * 60 * 24 * 1000 && (rangePickerMaxDays === 0 || Math.abs(calendar.value[0].getTime() - newValue.getTime()) <= (rangePickerMaxDays - 1) * 60 * 60 * 24 * 1000)) calendar.value.push(newValue);else calendar.value = [];
+ if (calendar.value.length === 0 || Math.abs(new Date(calendar.value[0]).getTime() - newValue.getTime()) >= (rangePickerMinDays - 1) * 60 * 60 * 24 * 1000 && (rangePickerMaxDays === 0 || Math.abs(new Date(calendar.value[0]).getTime() - newValue.getTime()) <= (rangePickerMaxDays - 1) * 60 * 60 * 24 * 1000)) calendar.value.push(newValue);else calendar.value = [];   
```  

line 784:
```
- $el.find(’.calendar-time-selector a’).text(value && value.length ? calendar.timeSelectorFormatter.format(value[0]) : calendar.params.timePickerPlaceholder);
+ $el.find(’.calendar-time-selector a’).text(value && value.length ? calendar.timeSelectorFormatter.format(new Date(value[0])) : calendar.params.timePickerPlaceholder);
```

line 1509:
```
- if (value) timeString = calendar.timeSelectorFormatter.format(value);
+ if (value) timeString = calendar.timeSelectorFormatter.format(new Date(value));
```

line 1682:
```
- value = [calendar.value[0].getHours(), calendar.value[0].getMinutes()];
+ var date = new Date(calendar.value[0]);
+ value = [date.getHours(), date.getMinutes()];
```

**Comment by nolimits4web** [comment]
> pass in an array of string date values 

string date is not a Date, it is a string. Calendar accepts only Dates as values
