### ISSUE TITLE
app.sheet.stepOpen, .stepClose and .stepToggle types are missing in definitions

### ISSUE THREAD

**Issue by RaddishIoW** [framework7io/framework7#3847]
* Framework7 version: 6.0.14
* Platform and Target: all
* Live Link or JSFiddle: 

### Describe the bug
The Typescript types for the functions on `app.sheet.stepOpen()`, `app.sheet.stepClose()` and `app.sheet.stepToggle()` are missing from the type definitions, leading to errors in Typescript.

### To Reproduce
1. Attempt to use `app.sheet.stepToggle()` in function.
2. Observe Typescript errors about missing type.

### Expected behavior
The types are listed.

### Actual Behavior
Observed error:
```
Property 'stepToggle' does not exist on type '{ create(parameters: Parameters): Sheet; destroy(el: HTMLElement | Sheet |
CSSSelector): void; get(el?: HTMLElement | CSSSelector | undefined): Sheet; open(el?: HTMLElement | ... 1 more ... |
undefined, animate?: boolean | undefined): Sheet; close(el?: HTMLElement | ... 1 more ... | undefined, animate?: boolean |
un...'.ts(2339)
```

Types are listed as:
```
(property) Sheet.AppMethods.sheet: {
    create(parameters: Sheet.Parameters): Sheet.Sheet;
    destroy(el: Sheet.Sheet | HTMLElement | CSSSelector): void;
    get(el?: HTMLElement | CSSSelector | undefined): Sheet.Sheet;
    open(el?: HTMLElement | ... 1 more ... | undefined, animate?: boolean | undefined): Sheet.Sheet;
    close(el?: HTMLElement | ... 1 more ... | undefined, animate?: boolean | undefined): Sheet.Sheet;
}
```

**Comment by DAnn2012** [comment]
Methods are missing and also Events, such as:

`sheet:stepopen`, `stepOpen` and `sheetStepOpen`
`sheet:stepclose`, `stepClose` and `sheetStepClose`
`sheet:stepprogress`, `stepProgress` and `sheetStepProgress`

**Comment by RaddishIoW** [comment]
I might be missing something, but my current install of Framework7 v6.0.16 still does not have definitions for the step-related methods on the Sheet AppMethods Interface?

From `sheet.d.ts`
```
interface AppMethods {
    sheet: {
      /** create Sheet Modal instance */
      create(parameters: Parameters): Sheet;
      /** destroy Sheet Modal instance */
      destroy(el: HTMLElement | CSSSelector | Sheet): void;
      /** get Sheet Modal instance by HTML element */
      get(el?: HTMLElement | CSSSelector): Sheet;
      /** open Sheet Modal */
      open(el?: HTMLElement | CSSSelector, animate?: boolean): Sheet;
      /** closes Sheet Modal */
      close(el?: HTMLElement | CSSSelector, animate?: boolean): Sheet;
    };
  }
```

Shouldn't it have method definitions for `stepToggle` etc?
