### ISSUE TITLE
Uncaught Error: Invalid hook call

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#3851]
I have created a typical skeleton from the f7-react example from https://framework7.io/react/app.html and get the following error:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

which points to these lines:

```
resolveDispatcher ../pkg/framework7-react.v6.0.14.js:14963 (throws error)
useRef ../pkg/framework7-react.v6.0.14.js:15002
App ../pkg/framework7-react.v6.0.14.js:16494
renderWithHooks ../pkg/react-dom.v17.0.2.js:14989
```

**From F7-React script:** 
```
function resolveDispatcher() {
  var dispatcher = ReactCurrentDispatcher.current;

  if (!(dispatcher !== null)) {
    {
     // THIS ISSUE IS CALLED
      throw Error( "Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:\n1. You might have mismatching versions of React and the renderer (such as React DOM)\n2. You might be breaking the Rules of Hooks\n3. You might have more than one copy of React in the same app\nSee https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem." );
    }
  }

  return dispatcher;
}
```

* Framework7 version: "framework7": "^6.0.14", "framework7-react": "^6.0.14",
* React.js version: "react": "^17.0.0", "react-dom": "^17.0.0",
* Platform and Target: Firefox Deskop Browser

**Comment by nimo23** [comment]
According to this:

1. You might have mismatching versions of React and the renderer (such as React DOM)
-> This is not the case, I use only one version (`npm ls react-dom` prints "react-dom@17.0.2")

**2. You might be breaking the Rules of Hooks
-> In my simple application I do not use any hooks, so it seems that F7-React does break those hook rules.**

3. You might have more than one copy of React in the same app
-> This is not the case, I use only one version (`npm ls react` prints "react@17.0.2")

**Comment by nolimits4web** [comment]
Hard to understand what you are doing wrong, are such issue for the first time. Create F7-React app with F7 CLI and start from there https://framework7.io/cli/

**Comment by nimo23** [comment]
My setup is based on https://www.snowpack.dev/ with yarn. The rest of the program is taken from kitchensink:

```
// app.js
import React from 'react';
import ReactDOM from 'react-dom';
import Framework7 from 'framework7/lite-bundle';
import Framework7React from 'framework7-react';
import App from './app.jsx';

import 'framework7/framework7-bundle.css';
import './css/app.css';

Framework7.use(Framework7React);

// Mount React App
ReactDOM.render(React.createElement(App), document.getElementById('app'));
```

Maybe f7 is not compatible with snowpack?
