### ISSUE TITLE
Framework7-React: Fix issue with Snowpack

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#3852]
The problem is described in https://github.com/framework7io/framework7/issues/3851 which was closed because I did not know where the error lies. I created a simple project "f7-react-snowpack" to reproduce the error:

[f7-react-snowpack.zip](https://github.com/framework7io/framework7/files/6217242/f7-react-snowpack.zip)

To start the project, do the following:
1. `yarn install`
2. `yarn start`

The browser will open with the following error:

![Screenshot at Mar 28 13-34-57](https://user-images.githubusercontent.com/3045549/112751105-7d1bb400-8fcc-11eb-808a-44fa361ca6dd.png)

**Describe the solution you'd like**
- Framework7-React should work with Snowpack. 
- And please put the linter https://www.npmjs.com/package/eslint-plugin-react-hooks in `framework7-react` to avoid such issues in future and to satisfy https://reactjs.org/docs/hooks-rules.html.

**Comment by nolimits4web** [comment]
I think more correct to address this question to Snowpack. F7 works perfectly with web pack, vite, esbuild. And there is no mentioned issues in code

**Comment by nimo23** [comment]
@nolimits4web Yes, thanks. I think this is indeed a snowpack issue.
