### ISSUE TITLE
Swipeable Tabs: begin next tab of last tab with first tab

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#3853]
Please provide a property (e.g., "swipe-circle") which enables the following: when the last tab is active and user swips further, then it begins again with the first tab: For example, a tab bar with 3 tabs:

Tab1 (swipe to next) Tab2 (swipe to next) Tab 3 (swipe to next) Tab 1 ..

**Comment by AlwaysLoveme** [comment]
> Please provide a property (e.g., "swipe-circle") which enables the following: when the last tab is active and user swips further, then it begins again with the first tab: For example, a tab bar with 3 tabs:
> 
> Tab1 (swipe to next) Tab2 (swipe to next) Tab 3 (swipe to next) Tab 1 ..


if you using with Vue , you can set swiper-params option, like this:
```
  <f7-tabs animated swipeable :swiper-params="{ loop: true }">
      ****
  </f7-tabs>
```

**Comment by nimo23** [comment]
Does this also work for `framework7-react`?

**Comment by AlwaysLoveme** [comment]
> Does this also work for `framework7-react`?


React just setup "swiperParams" option
see here: [https://framework7.io/react/tabs.html](https://framework7.io/react/tabs.html)
![image](https://user-images.githubusercontent.com/29945352/113996834-20e94780-988a-11eb-831e-28152bb80542.png)

**Comment by nimo23** [comment]
Ok, then I think we can close this issue as this is already provided by swiper-params.
