### ISSUE TITLE
Data Table: footer navigation is not fixed

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#3854]
The kitchen sink example of "Data Table with footer pagination" on mobile phone: the footer is not fixed at the bottom and moves if user scrolls to the right (or left).

**Describe the solution you'd like**
The footer (unlike the header) should be fixed at the bottom and should not be moved with its content if user scrolls to right (or left)

**Comment by nolimits4web** [comment]
This is for sure, can be done with some minimal custom CSS customization, e.g. setting `position: sticky` or something similar

**Comment by nimo23** [comment]
Yes, I know but user expects that footer is sticky by default. Does not make sense to scroll it with its content because (unlike its headers) it is independent from its datatable content..
