### ISSUE TITLE
Provide new theme: Fluent UI

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#3855]
Currently, there are 3 themes (ios, android and desktop theme). I would really like to see that F7 adapts the Fluent theme (https://developer.microsoft.com/de-de/fluentui#/controls/web/button) to its components. Please look at its components and evaluate it:

- https://developer.microsoft.com/de-de/fluentui#/controls
- https://github.com/microsoft/fluentui

I think Fluent UI is unobstrusive, simple and would be a great fit on small screens. 

What do you think?

**Comment by nolimits4web** [comment]
No chances, sorry. F7 has a variety of CSS variables to give you an opportunity customize it. We can't cover all possible themes and design systems

**Comment by nimo23** [comment]
That's pitty. I think Fluent UI (from Microsoft) has a very bright future and there are only three big players on the interface design:

- google (material themes)
- apple (ios)
- microsoft (fluentUI)

So there would be only three themes to be covered in F7. 
@nolimits4web Maybe you can keep **FluentUI** in mind and evaluate it in future. Would be great.
