### ISSUE TITLE
Include built versions in download

### ISSUE THREAD

**Issue by ppetree** [framework7io/framework7#3856]
**Is your feature request related to a problem? Please describe.**
Previous versions included the pre-built files. For those of us using cloud build services we don't have nor need nodejs installed so we have no way to build.

**Describe the solution you'd like**
Include the prebuilt files or a separate place to download them.

**Describe alternatives you've considered**
New problem. Even looking at building locally and there's just not enough information available in the F7 docs to proceed with any level of confidence.

**Additional context**
Again, many developers use a cloud build service so we don't want nor need nodejs, java libraries or any of the other components needed.

**Comment by nolimits4web** [comment]
It can be downloaded from `npm`. If you don't use NPM you can download it from variety of CDNs that mirror NPM, like this one http://unpkg.com/framework7/

**Comment by ppetree** [comment]
I'm sorry but I'm not finding the prebuilts on NPM.

Also, is there a list of the CDN's?

**Comment by nolimits4web** [comment]
https://unpkg.com/browse/framework7@6.0.14/
https://www.jsdelivr.com/package/npm/framework7
