### ISSUE TITLE
Feature Request: built-in F7 Nuxt and Next

### ISSUE THREAD

**Issue by D-Marc1** [framework7io/framework7#3859]
**Is your feature request related to a problem? Please describe.**

I love using Framework7 Vue, but I wish there were a built-in Nuxt version as well.

**Describe the solution you'd like**
A built-in Nuxt version of Framework7

**Describe alternatives you've considered**

There's a library called [Nuxt7](https://github.com/nuxt-community/nuxt7), which is maintained by one of the authors and the top contributors of Nuxt, but it doesn't seem like issues are being addressed. The main one for me is that using a [right side panel has been issue since 2018](https://github.com/nuxt-community/nuxt7/issues/40), yet is still not fixed.

I really think this is a feature that would take F7 to the next (nuxt) level. Similar to how adding a built-in version for Vue, React and Svelte did. Frameworks like Nuxt and Next have greatly improved the experience for developing apps, especially due to automatically taking care of boiler plate stuff, like routes automatically being created and components automatically importing. It would be awesome to have them baked into F7.

I know this would obviously be a time-consuming task, but just figured I would suggest it as a feature request.

**Comment by nolimits4web** [comment]
Next.js already supported https://blog.framework7.io/framework7-next-js-server-side-rendering-yes-1f6c9334dc03
Nuxt will be done when they will support Vue 3

**Comment by D-Marc1** [comment]
This is excellent news! Thank you so much for your hard work @nolimits4web! You're the man!

**Comment by riderx** [comment]
Any update for nuxt ?

**Comment by D-Marc1** [comment]
Support for SvelteKit would be nice also. I know it's supported in KonstaUI, but I would love for it to be built into F7. SvelteKit has support for SPAs also.
