### ISSUE TITLE
Route config asyncComponent is not woking in custom function

### ISSUE THREAD

**Issue by AlwaysLoveme** [framework7io/framework7#3861]
* Framework7 version: [6.0.14]
* Vue.js version: [3.0.10]
* Platform and Target: [Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Describe the bug
When using variables to import dynamically compoent, it reports that the module cannot be found

```js
import TabsRoute from "./tabs";

function resolveRoute({ name = "", path = "", component = "" }) {
  return {
    path,
    name,
    options: {
      transition: "f7-push",
    },
    asyncComponent: () => import(`${component}`),
  };
}
const routes = [
  ...TabsRoute,
  resolveRoute({ // this cause error: "Cannot find module '../pages/main/home-main/home-main.vue'"
    name: "main",
    path: "/main/:id",
    component: "@/pages/main/home-main/home-main.vue",
  }),
  {
    path: "/goods-list",
    name: "goodsList",
    asyncComponent: () =>
      import("@/pages/main/goods-manage/goods-list/goods-list.vue"), // it is work well
  },
  // Default route, match to all pages (e.g. 404 page)
  {
    path: "(.*)",
    asyncComponent: () => import("@/pages/notfound/notfound.vue"),
  },
];
export default routes;

```

### Expected behavior
can work well

### Actual Behavior
error with "Cannot find module...."

### Screenshots
![image](https://user-images.githubusercontent.com/29945352/113653146-d8822c00-96c7-11eb-8695-2f481ea13157.png)

**Comment by nolimits4web** [comment]
Closing as this is how webpack works. Check webpack docs on how such dynamic imports work there

**Comment by joshua1** [comment]
@nolimits4web  how does dynamic import work with Vite ? given the change. async routes (in svelte) always fail on reload with the error 
```
view.svelte:197 Uncaught TypeError: switch_value is not a constructor
```
Note this only happens when you refresh the browser on an asyncComponent route
