### ISSUE TITLE
[v6] Template android app stuck in splash screen

### ISSUE THREAD

**Issue by jpdelmundo** [framework7io/framework7#3862]
* Framework7 version: 6.0.14
* Platform and Target: Android API Level 22 (same issue with 23)

### Describe the bug
Output cordova android app stuck on splash screen due to javascript error in app.js:

> Uncaught SyntaxError: Unexpected token )

### To Reproduce
Prepare and run android emulator (or install and run apk)

1. Run `framework7 create --ui`
2. In the Create App page, select simple web app and cordova app under app type then click the Create App button at the bottom of the page.
3. Open a terminal to the app directory
4. Run `npm run cordova-android` (app should start in the emulator)

### Expected behavior
App splash screen goes away after a few seconds and app continues to the home page.

### Actual Behavior
App stuck in splash screen.

### Screenshots
![2021-04-07_144134](https://user-images.githubusercontent.com/1436852/113826135-66d3dc00-97b4-11eb-9a66-449e61f4cb58.png)
![2021-04-07_151714](https://user-images.githubusercontent.com/1436852/113826155-6a676300-97b4-11eb-9da0-b501dbbc3092.png)

### Additional context
App works on API Level 24 and above. Cordova v9 supports Android API 22-29, which is what this Framework7 template is configured to use.

I used the template above to show it is not an issue with the code I am working on.

**Comment by nolimits4web** [comment]
Closing as not related to Framework7 itself. Not sure what Android version you test on, but F7 compatible with Android v7+

**Comment by bestforName** [comment]
config.xml
