### ISSUE TITLE
improve ripple effect 

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#3863]
**Is your feature request related to a problem? Please describe.**
F7 Material Design does not use the Ripple effect in accordance to the official Material Design. F7-Ripple Effect uses always the same mid point (within an element) regardless of where the user clicks within this element. And F7 does always use the same ripple intensity regardless of its pressure.

**Describe the solution you'd like**
Click, for example, a button of https://material-ui.com/components/buttons/. You see that the start point of the ripple effect depends on the clicked position (instead of the mid point of the element). And the ripple effect does also depend on the pressure (the more pressure, the  stronger the ripple intensity (= higher color, higher spread).

**Comment by nolimits4web** [comment]
The link you provided is not an official Material Design implementation. And in F7 touch ripple also starts from the point you clicked, not mid point, but it also depends on elements, some like navbar links have touch ripple always from center, it is by design

**Comment by nimo23** [comment]
Btw, the ripple effect seems to be smoother and more precise in https://material-ui.com/components/buttons/ in compare to f7-ripple effect. Maybe there is room to improve this in f7?

**Comment by nimo23** [comment]
>And in F7 touch ripple also starts from the point you clicked, not mid point, but it also depends on elements, some like navbar links have touch ripple always from center, it is by design

yes, this is correct. I did use the navbar links..


@nolimits4web Compare the ripple effect of the official Material Design, for example, click the button of https://material.io/components/buttons and click the buttons from https://framework7.io/kitchen-sink/core/?theme=md. You see the differences. For example, F7 ripple effect is shown within the whole element and is also very fast which seems not so smooth as the ripple effect of https://material.io/components/buttons.
