### ISSUE TITLE
how to resolve this？

### ISSUE THREAD

**Issue by liedezhangqiu** [framework7io/framework7#3865]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! framework7-source@0.0.0 build:prod: `cross-env-shell NODE_ENV=production "gulp build-core && gulp build-vue && gulp build-react && gulp build-svelte"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the framework7-source@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
      xxxxxxxxx

**Comment by liedezhangqiu** [comment]
why not provide external accessable  .js linkfile

**Comment by nolimits4web** [comment]
https://unpkg.com/browse/framework7@6.0.14/
