### ISSUE TITLE
Bug in page.vue

### ISSUE THREAD

**Issue by arifcakiroglu** [framework7io/framework7#3870]
Hi,

I found a bug in [ this line](https://github.com/framework7io/framework7/blob/master/src/vue/components/page.vue#L354) .

I guess you forgot to leave a **space** at the beginning. It causes classes to be unified when you add sub-navbar.

<img width="473" alt="Screen Shot 2021-04-13 at 20 13 56" src="https://user-images.githubusercontent.com/1484664/114593454-cd656800-9c94-11eb-8a7c-4a6ac47a02e4.png">

**Comment by nolimits4web** [comment]
Fixed in #3871
