### ISSUE TITLE
Content hidden by bottom bar with tabbed template 

### ISSUE THREAD

**Issue by boosh** [framework7io/framework7#3873]
* Framework7 version: ﻿4.0.8
* Vue.js version: @vue/cli 4.5.12
* Platform and Target: web (dev server)

### Describe the bug
The bottom bar obscures page content.

### To Reproduce
Create demo app:

```
  "cwd": "/Users/me/projects/mobile-app",
  "type": [
    "capacitor"
  ],
  "name": "Toy App",
  "framework": "vue",
  "template": "tabs",
  "bundler": "webpack",
  "cssPreProcessor": "scss",
  "theming": {
    "customColor": false,
    "color": "#007aff",
    "darkTheme": false,
    "iconFonts": true,
    "fillBars": false
  },
  "customBuild": false,
  "webpack": {
    "developmentSourceMap": true,
    "productionSourceMap": true,
    "hashAssets": false,
    "preserveAssetsPaths": false,
    "inlineAssets": true
  },
  "pkg": "io.framework7.toyapp",
  "capacitor": {
    "platforms": [
      "ios",
      "android"
    ]
  }
}
```

Run dev server then go to e.g. the settings page. The last item in the list can't be seen.

### Expected behavior
The bottom bar shouldn't obscure content.

### Actual Behavior
The bottom bar obscures content 

### Screenshots
Scrolled all the way to the bottom, but the bottom bar obscures content: 

<img width="412" alt="Screenshot 2021-04-18 at 05 38 13" src="https://user-images.githubusercontent.com/362148/115134471-e60caf80-9fff-11eb-9dbb-46f54786aa63.png">

**Comment by nolimits4web** [comment]
What is the browser?

**Comment by boosh** [comment]
Firefox 88 on Mac

**Comment by nolimits4web** [comment]
It is FF issue handling overlfow, do the search here or on forum. There were solutions to this
