### ISSUE TITLE
page is blank when browserHistory is true and "browserHistorySeparator=''" on H5 Project

### ISSUE THREAD

**Issue by AlwaysLoveme** [framework7io/framework7#3875]
* Framework7 version: [6.0.15]
* Vue.js version: [3.0.11]
* Platform and Target: [Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Describe the bug
The history mode is enabled for routing, the project is not deployed in the root directory, but the project is blank when opened, the page is not rendered, and the console does not report an error

### Expected behavior
no blank page

### Actual Behavior
page did not render

### Screenshots
![image](https://user-images.githubusercontent.com/29945352/115673386-27de8280-a37f-11eb-8b9f-253f798a847c.png)

**Comment by nolimits4web** [comment]
> the project is not deployed in the root directory

Make sure you have correct `browserHistoryRoot` parameter then
