### ISSUE TITLE
Can accordition be used outside <App>?

### ISSUE THREAD

**Issue by GitKou** [framework7io/framework7#3877]
* Framework7 version:  6.0.16
* React.js version: 17.0.2
* Platform and Target: Chrome browser
* Live Link or JSFiddle: https://codesandbox.io/s/nervous-mcclintock-xf1wm?file=/src/App.js

### Describe the bug
It seems like Accordion must be used inside APP,  because of event emit? 
Can I use  Accordion when my App is not framework7 App?
![image](https://user-images.githubusercontent.com/7437397/116174801-b701e680-a741-11eb-9f3f-9eeef2fe831e.png)
![image](https://user-images.githubusercontent.com/7437397/116175095-40191d80-a742-11eb-8ff5-774a226f2fc5.png)

### To Reproduce
1. Go to https://codesandbox.io/s/nervous-mcclintock-xf1wm?file=/src/App.js
2. Click on AccordionToggle
3. See it has no reaction

**Comment by nolimits4web** [comment]
> Can I use Accordion when my App is not framework7 App?

No, all F7 components designed to work as a part of App
