### ISSUE TITLE
Mis-type 'color' props in Typescript 'Progressbar'

### ISSUE THREAD

**Issue by 1000ship** [framework7io/framework7#3878]
* Framework7 version: [e.g. 3.0.0]
* React.js version: [e.g. 16.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/vxb8oyke/)

### To Reproduce

Write this code, and check typescript error
```tsx
<Progressbar
  progress={ ... }
   color="yellow"
/>
```

### Expected behavior
It's not runtime/compile error, but typescript makes this error

### Actual Behavior
Explain what is actually happening
It makes typescript error

### Screenshots
<img width="643" alt="Screen Shot 2021-04-28 at 5 59 13 PM" src="https://user-images.githubusercontent.com/2270565/116376677-72fb0880-a84b-11eb-9e3d-d96e8f14ac17.png">
<img width="632" alt="Screen Shot 2021-04-28 at 5 59 25 PM" src="https://user-images.githubusercontent.com/2270565/116376710-79898000-a84b-11eb-9372-d630075452ee.png">

### Additional context

I think it's missing `color` props error in `ProgressbarProps`

**Comment by nolimits4web** [comment]
It was fixed few versions ago. Make sure you are on latest v6
