### ISSUE TITLE
Framework7-react SmartSelect props el 

### ISSUE THREAD

**Issue by xiaomingyu-git** [framework7io/framework7#3902]
In  smart-select with ts ,el props is required , like this .
     el: HTMLElement | CSSSelector;
    /** Link to initialized View instance which is required for Smart Select to work. By default, if not specified, it will be opened in parent View. */
    But sometimes ,it is ok to use default value.
I think  
     el?: HTMLElement | CSSSelector;
is better.

Could anyone tell me ,what is  "parent View "  in last file ?
[SearchPage.md](https://github.com/framework7io/framework7/files/6614600/SearchPage.md)

**Comment by xiaomingyu-git** [comment]
![image](https://user-images.githubusercontent.com/44595719/121147128-2e638380-c873-11eb-94ab-0d3fa90d0041.png)\

it runs twice when i use html selecter

**Comment by xiaomingyu-git** [comment]
![image](https://user-images.githubusercontent.com/44595719/121147895-df6a1e00-c873-11eb-84f4-abcdf7792e65.png)


it does not work without el

**Comment by nolimits4web** [comment]
Use ts-ignore for now. I will make it optional

**Comment by xiaomingyu-git** [comment]
> Use ts-ignore for now. I will make it optional

thx a lot for you hardwork .
