### ISSUE TITLE
Text-Editor, External and Internal Link handling

### ISSUE THREAD

**Issue by thebestgin** [framework7io/framework7#3903]
Hi,

I use the Text Editor more and more often.
This one works great overall.

I hope I have not overlooked the following feature so far.
An optimization is what I would like to see. 
When using a link, I often miss the option, if the link is an internal link for Framwork7 or an external link.
External links should not run through the router.
In Framework7 is used for the component Link the class "external" for it in combination with _blank, _self

The feature could be used like this.
Linkinput
![image](https://user-images.githubusercontent.com/10037845/121498565-d3e63680-c9dc-11eb-8627-488ecac9f2db.png)
`{external:_blank}https://framework7.io/svelte/link.html`
With the first part you can add the Framwork7 classen and attributes for the link.

Only as a suggestion.

**Comment by nolimits4web** [comment]
Good idea, will add some support for adding custom attributes to link and image

**Comment by thebestgin** [comment]
I've been thinking about how to make the feature nice to use from a user perspective. 

The calendar gets additional property. These properties are filters. With the filters Framework7 finds out what are internal links and what are external links. If a url starts with "https://framework7.io/" then it is an internal link. Everything else is an external link. Maybe you can also work with regex here.

This would have the great advantage that the logic is not in the persistent storage of the editor content.

**Comment by nolimits4web** [comment]
Ok, so not to mess with formats, I think it is better to leave it to developer to decide. So now (with next release), editor will have `insertLink` and `insertImage` events, and based on these, you now can detect when link/image was added and post process the HTML/value

**Comment by thebestgin** [comment]
> Ok, so not to mess with formats, I think it is better to leave it to developer to decide. So now (with next release), editor will have `insertLink` and `insertImage` events, and based on these, you now can detect when link/image was added and post process the HTML/value

This is the best solution. 👍
