### ISSUE TITLE
Action Sheet/Popover backdrop not removed on.closed

### ISSUE THREAD

**Issue by xPh03n1x** [framework7io/framework7#3904]
### Describe the bug
Using the latest version of Framework7, when a new Action Sheet or Popover is opened, Framework7 adds backdrop by default:
`<div class="actions-backdrop"></div>` and `<div class="popover-backdrop"></div>` respectively.

Once button from the menu is clicked and the Action Sheet / Popover is closed and destroyed, the backdrop elements remain in the DOM.

### To Reproduce
1. Create and open either an Action Sheet or Popover
2. Click on any button to close the Action Sheet/Popover
3. Look at the DOM Elements and you will find the popover element created by Action Sheet/Popover still existing (`$('.actions-backdrop, .popover-backdrop').length` will be greater than 0)

### Expected behavior
Just like the `.actions-modal` and `.popover` elements are removed once closed, the backdrop elements should be removed as well.

### Actual Behavior
The backdrop elements for Actions Sheet and Popover remain in the DOM after `close()` and `destroy()`

**Comment by nolimits4web** [comment]
It is by design because these backdrops will be re-used by other modals of same type

**Comment by xPh03n1x** [comment]
I urge you to reconsider this. Having multiple not displayed DOM elements with opacity on them only puts strain on the hardware as the browser still computes their rendering, even if they are not displayed.
I personally don't consider it to be good practice to have non-used elements bothering the renderer, especially since calling `create()` will still make the needed backdrop if it doesn't exist.
