### ISSUE TITLE
Сборка под iOS

### ISSUE THREAD

**Issue by Brizhanev** [framework7io/framework7#3906]
Здравствуйте, столкнулся с проблемой, есть приложение, созданное с помощью framework7-cli, при запуске на MacOS через эмулятор приложение не загружается дальше загрузочного экрана, если удалить плагин SplashScreen, то просто белый экран. Проблем с кодом нет, создаю обычное HelloWorld приложение из документации Cordova, заменяю папку www на свою и то же самое приложение запускается и работает. Пробовал отладку через Safari, Dom загружается, Ajax запросы к серверу идут, но на экране эмулятора пусто.

**Comment by nolimits4web** [comment]
Hi! Please use forum for questions https://forum.framework7.io
