### ISSUE TITLE
I would like to customize the color themes of my app

### ISSUE THREAD

**Issue by cvmartins1996** [framework7io/framework7#3909]
Framework7 v5
I would like to customize the color themes of my app, however my navbar is still gray instead of the deprecated blue theme, is this the new default or can I keep the old color I had in version 3 of framework7?

follow image of my app in version 5
![image](https://user-images.githubusercontent.com/22302846/123334189-1b121280-d519-11eb-9c9c-35c91d2de024.png)

follows image in the old version.
![image](https://user-images.githubusercontent.com/22302846/123334215-26653e00-d519-11eb-9cdb-af7e360eb595.png)

thanks

**Comment by DAnn2012** [comment]
Hello @cvmartins1996 

at this link you will find how to generate a color theme (and how to choose the navbar style) for framework7 v5:

https://v5.framework7.io/docs/color-themes.html#generate-color-theme
