### ISSUE TITLE
The `input` and `img` tags in the KS code (Core) are not self-closing

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3915]
I noticed that the `input` and `img` tags in the Kitchen Sink code (Core) are not self-closing, instead in the React/Svelte/Vue code are self-closing.

For the moment, I have noticed this on the following pages:

- https://github.com/framework7io/framework7/blob/master/kitchen-sink/core/pages/action-sheet.html
- https://github.com/framework7io/framework7/blob/master/kitchen-sink/core/pages/form-storage.html
- https://github.com/framework7io/framework7/blob/master/kitchen-sink/core/pages/inputs.html

@nolimits4web do you think it is appropriate to modify them?

Thanks.

**Comment by nolimits4web** [comment]
No, it is fine here

**Comment by DAnn2012** [comment]
@nolimits4web Okay, but here the `img` tag in the two _icons_ of "**Button 1**" is closed, in those of "**Button 2**" and "**Button 3**" it is not closed:

https://github.com/framework7io/framework7/blob/741261e21ff3e8dc52c17be75e47237396a9337c/kitchen-sink/core/pages/action-sheet.html#L99-L129

And in these other cases the `input` tag is closed:

https://github.com/framework7io/framework7/blob/741261e21ff3e8dc52c17be75e47237396a9337c/kitchen-sink/core/pages/login-screen-page.html#L12

https://github.com/framework7io/framework7/blob/741261e21ff3e8dc52c17be75e47237396a9337c/kitchen-sink/core/pages/login-screen-page.html#L21

**Comment by nolimits4web** [comment]
And it is still fine, these are different use cases. In template they must be closed, anywhere else - not
