### ISSUE TITLE
Нужен совет автора!

### ISSUE THREAD

**Issue by jumong** [framework7io/framework7#3916]
Какую ветку рекомендуете использовать для  гибридных мобильных приложений
 Framework7-Core или Framework7-Vue с точки зрения производительности?

**Comment by nolimits4web** [comment]
Производительность +- одинаковая, рекомендую Vue или React версию ✌️

**Comment by jumong** [comment]
Vue 2 или 3 версия ? Спасибо, Владимир!

**Comment by nolimits4web** [comment]
Только Vue 3
