### ISSUE TITLE
css-loader 6.2.0 no longer loads font icons correctly

### ISSUE THREAD

**Issue by ang3lx** [framework7io/framework7#3924]
if update  css-loader          ^5.2.7  →   ^6.2.0     
no longer loads font icons correctly

solution downgrade to 5.2.7

**Comment by nolimits4web** [comment]
closing as it is not Framework7 issue

**Comment by askotx** [comment]
This worked for me: 
https://github.com/jakejarvis/jarv.is/commit/8874b4f0ac542318775fa6f1d6a3515ad1828406
