### ISSUE TITLE
making framework7 work with sveltejs/kit

### ISSUE THREAD

**Issue by bhvngt** [framework7io/framework7#3925]
* Framework7 version: [e.g. 3.0.0] `6.0.22`
* Svelte version: [e.g. 3.0.0] `v1.0.0-next.131`
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser] `chrome`
* Live Link or JSFiddle/CodeSandbox: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. 

https://codesandbox.io/s/admiring-hertz-46b3y?file=/src/routes/index.svelte:262-268

### Describe the bug
@sveltejs/kit needs to compile the source differently for ssr. So it expects source svelte files from the third party library.

### To Reproduce
It has been reproduced in the above referred codesandbox 

### Expected behavior
framework7 should work with @sveltejs/kit

### Actual Behavior
framework7 breaks when integrated with @sveltejs/kit

**Comment by nolimits4web** [comment]
It is fixed in 6.1.0 beta

**Comment by bhvngt** [comment]
Thanks for your reply. I tried to use 6.1.0 beta with sveltejs/kit. I am getting following error

`Cannot read property 'trigger' of undefined`. It seems to be happening for the View component. Here's the updated [sandbox](https://codesandbox.io/s/sveltejskit-framework7-playground-46b3y?file=/src/routes/index.svelte) where the error is simulated. 

Am I importing `framework7 svelte components` correctly or do I need to import it differently?

**Comment by rakanus** [comment]
same issue here also even with > 6.3 ver
