### ISSUE TITLE
In 6.1.0-beta View Components throws type error when used with sveltejs/kit

### ISSUE THREAD

**Issue by bhvngt** [framework7io/framework7#3927]
* Framework7 version: [e.g. 3.0.0] `6.1.0-beta.6`
* Svelte version: [e.g. 3.0.0] `@sveltejs/kit 1.0.0-next.136`
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser] `Chrome`
* Live Link or JSFiddle/CodeSandbox: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. 

[CodeSandbox](https://codesandbox.io/s/sveltejskit-framework7-playground-46b3y?file=/src/routes/index.svelte:306-331)

### Describe the bug
When View component is used, it throws following error

```
Cannot read property 'trigger' of undefined
TypeError: Cannot read property 'trigger' of undefined
    at View.destroy (/sandbox/node_modules/framework7/cjs/components/view/view-class.js:122:14)
    at view.svelte:182:40
    at run (/sandbox/node_modules/svelte/internal/index.js:22:12)
    at Array.forEach (<anonymous>)
    at run_all (/sandbox/node_modules/svelte/internal/index.js:28:9)
    at Object.render (/sandbox/node_modules/svelte/internal/index.js:1679:13)
    at render_response (file:///sandbox/node_modules/@sveltejs/kit/dist/ssr.js:379:28)
    at async respond$1 (file:///sandbox/node_modules/@sveltejs/kit/dist/ssr.js:1223:10)
    at async render_page (file:///sandbox/node_modules/@sveltejs/kit/dist/ssr.js:1268:20)
    at async resolve (file:///sandbox/node_modules/@sveltejs/kit/dist/ssr.js:1613:10)
```

### To Reproduce
[CodeSandbox](https://codesandbox.io/s/sveltejskit-framework7-playground-46b3y?file=/src/routes/index.svelte:306-331)

### Expected behavior
View Component should work as expected

**Comment by nolimits4web** [comment]
Duplicate #3928

**Comment by bhvngt** [comment]
I believe this is a different issue than #3928. This occurs when I specifically use `View` Component. When I remove this component, all other components work. This is during `svelte-kit dev` where as #3928 happens when `svelte-kit preview` is run.

**Comment by iva2k** [comment]
I encountered the same issue with latest framework7@7.1.1.

I see issues just closed in this framework without investigation, PR or fix. It is a very bad signal to potential users. The issue happens, and quick code review shows unguarded property access, and apparently the object is undefined. I patched the line with a guard, and the error was fixed, however, few lines down there is another unguarded access to other properties of the same undefined object, and the code smells (property assigned null and then deleted. Null should be assigned after deletion).

Those code smells and blatant non-fixes of issues are enough to tape this framework with red tape and not touch it with a nine-foot pole.

Here's my patch if anyone needs it (I won't bother making a PR here as I don't have any hopes for it):

```
diff --git a/components/view/view-class.js b/components/view/view-class.js
index 3297499281d527da66e1afb561c33eda1c6bab47..a03a03609e57b71d8827d32c9380c32ccc9c04ba 100644
--- a/components/view/view-class.js
+++ b/components/view/view-class.js
@@ -94,7 +94,7 @@ class View extends Framework7Class {
   destroy() {
     let view = this;
     const app = view.app;
-    view.$el.trigger('view:beforedestroy');
+    if (view && view.$el) { view.$el.trigger('view:beforedestroy'); }
     view.emit('local::beforeDestroy viewBeforeDestroy', view);
     app.off('resize', view.checkMasterDetailBreakpoint);
 
@@ -106,8 +106,10 @@ class View extends Framework7Class {
       delete app.views[view.name];
     }
 
-    view.$el[0].f7View = null;
-    delete view.$el[0].f7View;
+    if (view && view.$el) {
+      delete view.$el[0].f7View;
+      view.$el[0].f7View = null;
+    }
     app.views.splice(app.views.indexOf(view), 1); // Destroy Router
 
     if (view.params.router && view.router) {
```
