### ISSUE TITLE
smart-select losts selection in the first line of a list

### ISSUE THREAD

**Issue by MDB80** [framework7io/framework7#3929]
Framework7 version: 6.0.22
Platform and Target: Cordova app + (Chrome browser + Safari br.) Android/ Ios
 
### Describe the bug
smart-select losts selection in the first line of a list

### To Reproduce
`<div class="page-content"><div class="block-title">Options</div><div class="list"><ul><li> <a href="#" class="item-link smart-select smart-select-init"> <select name="A"><option selected>Switch</option><option>Pulse</option> </select><div class="item-content"><div class="item-inner"><div class="item-title">Event type</div></div></div></a></li><li> <a href="#" class="item-link smart-select smart-select-init"> <select name="B"><option selected>Switch</option><option>Pulse</option> </select><div class="item-content"><div class="item-inner"><div class="item-title">Event type</div></div></div></a></li></ul></div></div>`

### Expected behavior
Same code - same results.

### Actual Behavior
Same code - different results.

### Screenshots

![Screenshot_20210726-111838](https://user-images.githubusercontent.com/33500808/126965613-78418105-5048-4d12-afed-36fd6e00d805.png)     ![Screenshot_20210726-112223](https://user-images.githubusercontent.com/33500808/126966007-b967fb88-4ef0-45d2-af30-8ab6a1e38e01.png)

### Additional context
Please someone resolve it.

**Comment by nolimits4web** [comment]
option element must have `value` attribute
