### ISSUE TITLE
smart-select losts selection in the first line of a list

### ISSUE THREAD

**Issue by MDB80** [framework7io/framework7#3930]
Framework7 version: 6.0.22
Platform and Target: Cordova app + (Chrome browser + Safari br.) Android/ Ios

### Describe the bug
smart-select losts selection in the first line of a list

### To Reproduce
`<div class=page-content><div class=block-title>Options</div><div class=list><ul><li><a class="item-link smart-select smart-select-init"href=#><select name=A><option value=0 selected>Switch<option value=1>Pulse</select><div class=item-content><div class=item-inner><div class=item-title>Event type</div></div></div></a><li><a class="item-link smart-select smart-select-init"href=#><select name=B><option value=0 selected>Switch<option value=1>Pulse</select><div class=item-content><div class=item-inner><div class=item-title>Event type</div></div></div></a></ul></div></div>`

### Expected behavior
Same code - same results.

### Actual Behavior
Same code - different results.

### Screenshots
![Screenshot_20210726-111838](https://user-images.githubusercontent.com/33500808/126972292-2a99dcc7-11ec-4f34-a907-4710c2663672.png) ![Screenshot_20210726-112223](https://user-images.githubusercontent.com/33500808/126972306-ab3ebafb-2135-46e4-a19b-0aa118d05218.png)

### Additional context

Dear mr. Kharlampidi,
Sorry for #3929, but when it minified, something went wrong. I assure you that even with value it is the exact same thing. 
It's not nice to Close the Issue dismissing people who are trying to help you.

I have wasted a lot of time reporting this and other problems. This is not a nice behavior.

And,by the way: the content of "value" attribute represents the value to be submitted with the form, should this option be selected. If this attribute is omitted, the value is taken from the text content of the option element.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

Before closing in less than 5 minutes, it would be best to get informed.

**Comment by nolimits4web** [comment]
Please, provide a live example using template from this thread https://forum.framework7.io/t/how-to-ask-a-good-question-on-forum/11172

**Comment by MDB80** [comment]
Solved....my mistake....nothing to report.

It was a conflict on the scripts: during tabs loading, the scripts on the "Devices" and "Settings" tabs, are executed simultaneously.
I didn't expect this behavior.

I apologize.
