### ISSUE TITLE
Getting  large chunk size warnings

### ISSUE THREAD

**Issue by mishrasatyam** [framework7io/framework7#3931]
* Framework7 version: 6.1.1 
* * Framework7-cli  version:  5.0.1 
* Svelte version: 3.40.3
* Platform and Target: Android

### Describe the bug
Getting below warning with pnpm build-capacitor-android

warnings when minifying css:
Empty property '-moz-font-feature-settings' at 18851:2. Ignoring.
Empty property 'font-feature-settings' at 18852:7. Ignoring.
../www/assets/material-icons.2c03dc5d.woff2            102.43kb
../www/assets/Framework7Icons-Regular.611bca65.woff2   107.68kb
../www/assets/material-icons.2055fce8.woff             131.31kb
../www/assets/Framework7Icons-Regular.0014a3ee.woff    137.78kb
../www/assets/index.1037a745.css                       572.13kb / brotli: skipped (large chunk)
../www/assets/index.cbfa1f66.js                        62.84kb / brotli: 8.78kb
../www/assets/vendor.5687216e.js                       951.64kb / brotli: skipped (large chunk)

(!) Some chunks are larger than 500kb after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
### To Reproduce
1.Create new project with framework7 cli  
2. Add android platform
3. pnpm build-capacitor-android
### Expected behavior
Shouldn't get  these warnings : 
Some chunks are larger than 500kb after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

**Comment by nolimits4web** [comment]
it is up to you to optimize it:
- use dynamic import()
- use custom Framework7 build (importing only components) you use
- etc.
