### ISSUE TITLE
stepper is inaccurate when increment with a step="0.1"

### ISSUE THREAD

**Issue by MDB80** [framework7io/framework7#3932]
Framework7 version: 6.0.22
Platform and Target:Cordova app + Chrome browser

### Describe the bug
stepper is inaccurate when increment with a step="0.1"

### To Reproduce
Create a simple step with input
`<input name="pr" type="text" value="10.0" min="6.0" max="24.0" step="0.1" readonly />`
and touch increase/decrease

### Expected behavior
10.0 - 10.1 -10.2....

### Actual Behavior
10.0 - 10.100000000000001 - 10.200000000000001  - 10.3 - 10.4 -

### Screenshots
![Cattura](https://user-images.githubusercontent.com/33500808/127171556-787b2363-2ea4-4000-9edf-4b9bc295b9a7.JPG)

### Additional context

In order to fix it, at the moment, I added this line between 317:318 in "framework7/src/core/components/stepper/stepper-class.js"

`value = Number.parseFloat(value).toFixed(stepper.decimalPoint);`

![Cattura2](https://user-images.githubusercontent.com/33500808/127172406-6c6aaa01-8f54-44fd-8989-75c0d0cd2046.JPG)

but I think the problem is in the line 317: ` let value = Math.round(newValue / step) * step;`

**Comment by nolimits4web** [comment]
Well, this is how JS and programming languages work in general :) https://0.30000000000000004.com

Stepper has `formatValue` parameter where you should do required modifications to value https://framework7.io/docs/stepper.html#stepper-parameters (NOT IN SOURCE CODE)

**Comment by MDB80** [comment]
Your answers are always, short, quick and unthoughtful.

Of course I know formatValue. Thank god I can still read.

The point is, that it is not interesting how bad floating point math works in javascript; but that in a smartselect after 10.5 there is a 10.6 and not 10.6000000001. That doesn't make sense.

***@***.***Also at a glance it really doesn't look normal.

Fixing the problem is easy, however, in this way, I’ll spend a lot of extra code.

Anyway, I got annoyed. I'm not going to post anymore. Since those are the answers anyway.

Goodbye



Da: Vladimir Kharlampidi ***@***.******@***.***>
Inviato: martedì, 27 luglio 2021 16:50
A: framework7io/framework7 ***@***.***>
Cc: Massimo Dalla Bona ***@***.***>; Author ***@***.***>
Oggetto: Re: [framework7io/framework7] stepper is inaccurate when increment with a step="0.1" (#3932)


Well, this is how JS and programming languages work in general :) https://0.30000000000000004.com

Stepper has formatValue parameter where you should do required modifications to value https://framework7.io/docs/stepper.html#stepper-parameters (NOT IN SOURCE CODE)
