### ISSUE TITLE
Login screen - open via prop change only works once

### ISSUE THREAD

**Issue by ong-appxplore** [framework7io/framework7#3934]
* Framework7 version: 6.1.1
* Platform and Target: Chrome browser

### Describe the bug
I am using login screen component and open it via prop change. But after the first time open and close, it would not open again. 

### To Reproduce
This bug is happening even in the documentation. [https://framework7.io/svelte/login-screen.html] (https://framework7.io/svelte/login-screen.html)

1. Go to the documentation link above
2. Scroll down to 'Examples' header
3. Click on 'Open via prop change' and see login screen appear
4. Click on 'Sign In' without filling anything and then a pop up appear, click on 'Ok'
5. Click on 'Open via prop change' again and login screen no longer appear

### Expected behavior
In Step 5, the login screen should appear again no matter how many times I repeat Step 3 and 4. 
In the documentation, it should works like the other button 'as overlay

### Actual Behavior
In Step 5, the login screen is not appearing although it should

### Additional context
I have tried Login Screen API and Link/Button with loginScreenOpen property. They work just fine but the prop change is a bit problematic.

**Comment by ong-appxplore** [comment]
Hi @nolimits4web , I have tried it but it's not working and I can't bring up a codesandbox as it keeps giving `'target' is a required option` error in the CodeSandbox template provided.

**Comment by nolimits4web** [comment]
What you have tried? You need to update F7 to 6.2.0

**Comment by ong-appxplore** [comment]
I tried it in my local. I think it's better to put up a codesandbox to show. Now I have different error after updating F7 to 6.2.0. 
Maybe you can check this link? [https://codesandbox.io/s/frosty-smoke-oeoui?file=/index.js](https://codesandbox.io/s/frosty-smoke-oeoui?file=/index.js)

**Comment by nolimits4web** [comment]
If you have different error, create a different issue describing the issue

**Comment by ong-appxplore** [comment]
Sorry, I think there's some issues with other F7 components. After I've removed them, its fine now. I have simulate it in the codesandbox provided. [https://codesandbox.io/s/frosty-smoke-oeoui?file=/App.svelte](https://codesandbox.io/s/frosty-smoke-oeoui?file=/App.svelte). Can you please help to check? Currently, I always need to toggle twice for the loginScreen to appear or disappear.
