### ISSUE TITLE
Vite + Vue3 + Typescript build error

### ISSUE THREAD

**Issue by AlwaysLoveme** [framework7io/framework7#3935]
* Framework7 version: [6.2.0]
* Vue.js version: [3.1.5]
* Platform and Target: [ Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Describe the bug
Vite + TS build with error

### Expected behavior
vite build success!

### Actual Behavior
build error

### Screenshots
![image](https://user-images.githubusercontent.com/29945352/128119491-5ac69076-8d6a-4f89-8a98-554395ac0d43.png)

![image](https://user-images.githubusercontent.com/29945352/128119602-505e07fc-5365-4dc6-aa61-37ef694d1eeb.png)

**Comment by nolimits4web** [comment]
Closing as not related to Framework7
