### ISSUE TITLE
Tailwind Integration

### ISSUE THREAD

**Issue by joshua1** [framework7io/framework7#3936]
I am using the framework7-svelte flavvour and want to use Tailwind alongside the Framework7 styling. I cant seem to get it to work with the CLI project even after selecting the use pre-processor option. Has anyone ever gotten tailwind working with the framework7 CLI project. If yes, please share how you went about it .
Thanks

**Comment by liho00** [comment]
![image](https://user-images.githubusercontent.com/77238199/131715131-ecbefd34-b7f7-45e5-a86f-431f3ea7042d.png)
how about adding the prefix in tailwind.config.js
