### ISSUE TITLE
F7-Vue ignoring plugin parameters

### ISSUE THREAD

**Issue by valnub** [framework7io/framework7#3952]
* Framework7 version: 6.3.5
* Vue.js version: 3.2.20
* Platform and Target: macOS 11.5.2 (Safari and Chrome)
* Minimal example code: https://github.com/valnub/f7-ws-vue-test

### Describe the bug
I created the plugin [f7-welcomescreen](https://github.com/valnub/Framework7-Plugin-Welcomescreen). Few weeks ago a user [complained](https://github.com/valnub/Framework7-Plugin-Welcomescreen/issues/64) that it is not working anymore in F7-Vue. I looked into it and can confirm that it doesn't work in F7-Vue but it works in F7-React and F7-Core. I dug into the issue and found out that in the vue version the [plugin parameters](https://github.com/valnub/f7-ws-vue-test/blob/master/src/components/app.vue#L55) are ignored by F7. Is this a bug in F7-Vue or did I do something wrong here?

### To Reproduce
1. `git clone https://github.com/valnub/f7-ws-vue-test`
2. `cd f7-ws-vue-test`
3. `yarn`
4. `yarn start`

### Expected behavior
Blue welcome screen should show up

### Actual Behavior
Blue screen does not show up

### Screenshots

This is the expected blue screen:

![Expected blue screen](https://user-images.githubusercontent.com/3787662/139541942-b165b442-8619-498a-abb6-2dbbca12befc.jpg)

### Other

Plugin source code and be found here: https://github.com/valnub/Framework7-Plugin-Welcomescreen/blob/master/index.js

**Comment by nolimits4web** [comment]
This is how Vue.js works, if you pass to component some props which are not defined in component `props` it ignores them and set as HTML attributes. And apparently F7's App component doesn't know about `welcomescreen` prop and doesn't it expect it. So probably some other way of initializing the plugin should be made

**Comment by valnub** [comment]
@nolimits4web Thanks for your reply. Is there a best practice on how to initialize F7 plugins for Vue? Couldn't find anything on F7 docs. I'm also quite confused what this has to do with Vue props as I just want to pass plugin initialization values to F7-Vue.

**Comment by nolimits4web** [comment]
>  I'm also quite confused what this has to do with Vue props

```
params = {
  foo: 1,
  bar: 2,
}
```
and
```
<f7-app v-bind="params" />
```
will be the same as
```
<f7-app :foo="1" :bar="2" />
```

So adding extra properties to params produces unknown prop passed to component

> Is there a best practice on how to initialize F7 plugins for Vue

Best practice is to extend F7 instance or prototype and use proper init using F7 instance, e.g.:

```
f7ready((f7) => {
  f7.welcomescreen.create(...pluginParams)
})
```
