### ISSUE TITLE
I wondering if I use svelte ,it still exists vdom?

### ISSUE THREAD

**Issue by Athxx** [framework7io/framework7#3953]
I wondering if I use svelte ,it still exists vdom?

**Comment by nolimits4web** [comment]
no, svelte doesn't use vdom

**Comment by Athxx** [comment]
> no, svelte doesn't use vdom

I know, I just wondering svelte intergrate f7, if I don't use `DOM7`, whether it still exists vdom in f7 part?

**Comment by nolimits4web** [comment]
dom7 has nothing to do with vdom
