### ISSUE TITLE
how to access router params 

### ISSUE THREAD

**Issue by bobwatcherx** [framework7io/framework7#3962]
**home.svelte**

<Link href="/food/mamama">food</Link>

**my routes.js**
.....
,{
    path: '/food/:id', **id is param to food.svelte**
    component: FoodPage,

  },

**food.svelte**
<script>
	import {
		Page,
		Link
	} from 'framework7-svelte'
</script>
<Page style="padding:50px">
	<Link back> back</Link>
	FOODS  {router.params.id} // what is script to display **id params**
	</Page>

**Comment by nolimits4web** [comment]
There is a forum for questions https://forum.framework7.io
