### ISSUE TITLE
f7-svelte browser history issues

### ISSUE THREAD

**Issue by thoward27** [framework7io/framework7#3966]
* Framework7 version: 6.3.14
* Svelte version: 3.45.0
* Platform and Target: Desktop Chrome browser
* Live Link or JSFiddle/CodeSandbox: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following CodeSandbox template: [CodeSandbox](https://codesandbox.io/s/framework7-svelte-yf8m2) **This link doesn't work for me, shows an error on load**

### Describe the bug
I am trying to produce a svelte application with framework 7. One requirement is that the app works well with the standard browser navigation. Unfortunately, I cannot figure out how to get the svelte starter app to use `browserHistory`. This is my first time working with Framework7, so I know I am most likely just missing something, but I feel I have tried just about everything I can think of.

### To Reproduce
1. Start a new Svelte project with the Framework7 CLI (Simple web app, with Svelte, tabbed layout, SCSS, Dark theme)
2. Try to enable `browserHistory` (I've tried adding it to specific views, adding it to the f7 json, adding it to the f7 props)
3. Navigate to the about page, note the URL does not change.

### Expected behavior
I expect the URL to change.

### Actual Behavior
Nothing changes.

### Additional context
I am really looking for the shortest path here. When starting a new svelte project with the f7 CLI, what are the steps necessary to get `browserHistory` fully functional. Ideally, I want `enabled` to be the default behavior in my app.

Thanks for providing and maintaining this beautiful framework!

**Comment by nolimits4web** [comment]
Hard to say as you didn't provide live example, but it just should be enabled on main view as a prop, e.g.:
```
<View main browserHistory ...>
```

**Comment by thoward27** [comment]
🤦 

I don't know how I didn't catch that the prop needed to be on the main view...

Thank you!
