### ISSUE TITLE
Missing parameter name at

### ISSUE THREAD

**Issue by PeraDev7** [framework7io/framework7#3971]
* Framework7 version: 6.0
* Platform and Target: Cordova Web

### Describe the bug
Random, when  i wrote the code, i get the 
```
Uncaught TypeError: Missing parameter name at 56
    at framework7-bundle.min.js:2474:39
```
when i need to open a new page

Click on button (button load a new page)

### Expected behavior
Open the page

### Actual Behavior
No actionsl olny the 
Uncaught TypeError: Missing parameter name at 56
    at framework7-bundle.min.js:2474:39

### Additional context
Code at that line : 
```
if (!i) throw new TypeError("Missing parameter name at " + a);
                        t.push({
                            type: "NAME",
                            index: a,
                            value: i
                        }), a = s
```

**Comment by nolimits4web** [comment]
impossible to realize something without proper code example or better live example with the issue

**Comment by PeraDev7** [comment]
I solved, it was an error on routes configuration.
