### ISSUE TITLE
Is Framework7 for Vue 3 ready?

### ISSUE THREAD

**Issue by kostia7alania** [framework7io/framework7#3974]
* Framework7 version: 6.3.15
* Vue.js version: 3.2.29
* Platform and Target: Windows Chrome browser
* Live Link or JSFiddle: https://codesandbox.io/s/funny-einstein-26gxq

### Describe the bug
At leasts - Popups don't work!

### To Reproduce
1) Go to https://codesandbox.io/s/funny-einstein-26gxq
2) If there is an issue with modules - just click the refresh button
3) Click the POPUP button.
4. See an error

### Expected behavior
Popup content rendered slot

### Actual Behavior
Popup content didn't render slot

### Screenshots
![image](https://user-images.githubusercontent.com/18175496/152381698-67a2655d-4ca9-475f-bc92-aca90ce0470d.png)

**Comment by nolimits4web** [comment]
Yes, create project with F7 CLI
