### ISSUE TITLE
Photo Browser Show No Image On Build

### ISSUE THREAD

**Issue by iqbalfn** [framework7io/framework7#3983]
* Framework7 version: 6.3.16
* Framework7 Vue version: 6.3.16
* Vue.js version: 3.2.31
* Platform and Target: All

### Describe the bug

Component photo browser is actually work well on development, but not showing any image after build. It does the some on f7 skeleton as well. No error shown on browser console.

### To Reproduce

Create new framwork7 vue application:

```bash
$ framework7 create
  > Cordova app (targets native iOS and Android apps, or native desktop app with Electron)
  > My App
  > Framework7 with Vue.js
  > Blank
  > SCSS (SASS)
  > No, use default color theme
  > No, i want to use my own custom icons
$ npm i
```

Edit file `/src/pages/home.vue` and fill it with content as below:

```html
<template>
  <f7-page name="home">
    <f7-photo-browser
        :photos="photos"
        theme="dark"
        type="page"
        back-link-text="Back"
        ref="pageDark"
        :routable-modals="false" />
    <f7-button fill raised @click="$refs.pageDark.open()" text="Open" />
  </f7-page>
</template>


<script>
export default {
  data() {
    return {
      photos: [
        'https://placekitten.com/800/800',
        'https://placekitten.com/1024/1024'
      ]
    };
  },
};
</script>
```

Now build it with below script:

```bash
$ npm run build
```

Now access the `www` folder from browser after adding it to one of nginx vhost:

```bash
open -a "Firefox" http://localhost/f7/www/index.html
```

### Expected behavior

It should show the image on build as well.

### Actual Behavior

It only work well on development environment, and no image is visible after building

### Screenshot Development

<img width="395" alt="Screen Shot 2022-02-15 at 11 44 04" src="https://user-images.githubusercontent.com/5726035/153994177-15a7ece7-aea0-4fa7-88fc-85e0d882e0fa.png">

### Screenshot On Build
<img width="393" alt="Screen Shot 2022-02-15 at 11 43 36" src="https://user-images.githubusercontent.com/5726035/153994229-c49cc27d-acb3-4fd2-8c02-b6764dae513b.png">

**Comment by nolimits4web** [comment]
Issue is related to Vite/Rollup, it ignores Swiper modules during the build, disable tree shaking in vite.config under the `build` props:
```
...
build: {
    outDir: BUILD_DIR,
    assetsInlineLimit: 0,
    emptyOutDir: true,
    // disable tree shake here
    rollupOptions: {
      treeshake: false,
    },
  },
```
