### ISSUE TITLE
[v7] Removing references to PhoneGap

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#3985]
Hello.

Considering that Adobe has communicated [the end of the development of PhoneGap and PhoneGap Build as early as 2020](https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c), I think it is appropriate to remove the references to PhoneGap in the source code, in the KitchenSink and in the framework7 documentation.

Thanks.

**Comment by codegreenie** [comment]
The latest version of Framework7 focuses more on Command Line installation and deployment (Development & LIVE). Phonegap has been depreciated
