### ISSUE TITLE
Svelte 3.46 gives "Uncaught Error: Function called outside component initialization"

### ISSUE THREAD

**Issue by basejump** [framework7io/framework7#3992]
for `"framework7-svelte": "^6.3.16"` version I have a very simple application here https://github.com/yakworks/framework7-svelte-simple

master works when its tied to `"svelte": "3.38.3"` 

this branch https://github.com/yakworks/framework7-svelte-simple/tree/svelte-3.46
shows the error when upgrading to 3.46. Tried changing from `import { App,  View } from 'framework7-svelte';` to `import { App,  View } from 'framework7-svelte/esm/framework7-svelte-src';` and still get `index.mjs?v=6582916b:948 Uncaught Error: Function called outside component initialization`

is it possible to upgrade to svelte or is it tied to 3.38?

**Comment by nolimits4web** [comment]
fixed in https://github.com/framework7io/framework7/commit/feda228523ba672cac2df49b1d6c6ce7d45e91fd
