### ISSUE TITLE
[v7] 'Function called outside component initialization', works on 6.3.16

### ISSUE THREAD

**Issue by basejump** [framework7io/framework7#3993]
simple app here https://github.com/yakworks/framework7-svelte-simple works on 6.3.16
but fails when upgrading to v7 beta. 

Example here of error https://github.com/yakworks/framework7-svelte-simple/tree/f7-7-beta12

possibly related to #3992 ? same error. Tried down grading vite to 2.3.1 which is what the kitchen-sink uses but no luck. Kitchen sink works, is it adding the router in somehow avoids the error? Confused on the internals here.

**Comment by basejump** [comment]
When adding router in here https://github.com/yakworks/framework7-svelte-simple/tree/f7-7-beta12-router
it runs and display home page but give an
```
Uncaught TypeError: Cannot read properties of undefined (reading 'once')
    at f7ready (f7.js:102:18)
    at attachEvents (use-tab.js:17:5)
    at use-tab.js:30:5
    at run (index.mjs:18:12)
    at Array.map (<anonymous>)
```

**Comment by basejump** [comment]
and latest commit her https://github.com/yakworks/framework7-svelte-simple/tree/f7-7-beta12-router to gets rid of error by simply adding `import 'framework7/lite';`

**Comment by nolimits4web** [comment]
fixed in https://github.com/framework7io/framework7/commit/feda228523ba672cac2df49b1d6c6ce7d45e91fd
