### ISSUE TITLE
Preloader animation not working on iOS 15.4

### ISSUE THREAD

**Issue by maitto** [framework7io/framework7#3998]
### Describe the bug
Opening the documentation example for preloaded with iOS 15.4 or MacOS 12.3 with Safari 15.4 shows the indicator without any animation, same with the implementation in our mobile app. https://framework7.io/docs/preloader#examples

Only the Android and desktop examples show the animation moving on the platforms mentioned above.

### To Reproduce
1. Go to https://framework7.io/docs/preloader#examples on iOS 15.4 device
2. Open iOS example

### Expected behavior
Loding animation moves

### Actual Behavior
Loading animation is frozen / does not move

**Comment by happyendin** [comment]
same issue on iOS 15.4, is there any block by wkwebview upgrade?

**Comment by l0gg3r** [comment]
experiencing same issue on iOS 15.4
