### ISSUE TITLE
No Icons on Framework7-Svelte

### ISSUE THREAD

**Issue by osmancoskun** [framework7io/framework7#3999]
* Framework7 version: 6.3.16
* Framework7 Svelte version: 6.3.16
* Framework7 Icons version: 5.0.5
* Svelte version:  3.46.4
* Platform and Target: Development in Manjaro Gnome Linux. Target, Android and IOS
* Live Link or JSFiddle/CodeSandbox: https://arnivadeneme.web.app/

### Describe the bug
When i try to create a new project from `framework7`, we cant use icons on project. With same instructions, we create a new project from `framework7` on `windows`, we can use icons on project. Instructions are from official website.

### To Reproduce
1. Go to link.

### Expected behavior
Using icons on projects

### Actual Behavior
Texts instead of icons on 

### Screenshots
[Screenshot1](https://i.ibb.co/dKct12g/Screenshot-from-2022-03-24-13-09-21.png)

### Additional context
Actually we can create project on windows and push to git. then we pull in Linux and after `npm i` it works like a charm

**Comment by osmancoskun** [comment]
problem is in `npm postinstall`. cpy command is not for linux. manual copying worked

**Comment by vitalijalbu** [comment]
Yes i agree,  I get same error after _npm build_ (react + vite js). Post install action doesn't copy f7-icons webfont to the folder.
