### ISSUE TITLE
Missing component exports in package.json

### ISSUE THREAD

**Issue by Hollul** [framework7io/framework7#4011]
* Framework7 version: 7.0.1
* Platform and Target: Cordova App (Android) / Webpack

I tried to update framewok7 from v6 to v7 for my app. I'm using Webpack to bundle files and get some errors. Seems like some components (navbar, toolbar) are not exported from framework7 package:

`Module not found: Error: Package path ./components/navbar is not exported from package D:\my-app\node_modules\framework7`
`Module not found: Error: Package path ./components/toolbar is not exported from package D:\my-app\node_modules\framework7`

When I change the package.json in node_modules/framework7 these errors go away.

There are also two more errors with snabbdom I see:

<pre>
ERROR in ./node_modules/framework7/modules/component/snabbdom/snabbdom.js 42:0-24
Module not found: Error: Can't resolve './h' in 'D:\my-app\node_modules\framework7\modules\component\snabbdom'
Did you mean 'h.js'?
BREAKING CHANGE: The request './h' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./node_modules/framework7/modules/component/patch.js 2:0-46 7:14-18
 @ ./node_modules/framework7/modules/component/component-class.js 7:0-31 77:10-15 91:10-15 277:21-26 360:19-24
 @ ./node_modules/framework7/modules/component/component.js 1:0-45 14:0-27 18:4-13 40:19-28
 @ ./node_modules/framework7/framework7.esm.js 28:0-84 41:143-158 42:0-90 42:0-90
 @ ./src/js/_app.js 23:0-52 38:0-14 55:14-24 81:12-14

ERROR in ./node_modules/framework7/modules/component/snabbdom/snabbdom.js 43:0-32
Module not found: Error: Can't resolve './thunk' in 'D:\my-app\node_modules\framework7\modules\component\snabbdom'
Did you mean 'thunk.js'?
BREAKING CHANGE: The request './thunk' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./node_modules/framework7/modules/component/patch.js 2:0-46 7:14-18
 @ ./node_modules/framework7/modules/component/component-class.js 7:0-31 77:10-15 91:10-15 277:21-26 360:19-24
 @ ./node_modules/framework7/modules/component/component.js 1:0-45 14:0-27 18:4-13 40:19-28
 @ ./node_modules/framework7/framework7.esm.js 28:0-84 41:143-158 42:0-90 42:0-90
 @ ./src/js/_app.js 23:0-52 38:0-14 55:14-24 81:12-14
</pre>

**Comment by nolimits4web** [comment]
https://github.com/framework7io/framework7/issues/4012
