### ISSUE TITLE
Fixed slot should not be placed inside page-content

### ISSUE THREAD

**Issue by lroal** [framework7io/framework7#4021]
* Framework7 version: [e.g. 7.0.2]
* Vue.js version: [e.g. 3.2.31]
* Platform and Target: [e.g. iOS 11 Cordova app in Chrome browser]

### Describe the bug
Content inside the fixed slot is placed inside the page-content. 

### To Reproduce
```
<slot name="fixed"  > 
        <div style="position: absolute" >
              <p>
              This is a big fixed content block.  It should remain fixed, even when page-content scrolls past the height of the viewport.</p>
        </div>
</slot>
```

### Expected behavior
Place the slot contents just before the page-content.

**Comment by nolimits4web** [comment]
It is wrong syntax, it must be:
```
<template #fixed>
        <div style="position: absolute" >
              <p>
              This is a big fixed content block.  It should remain fixed, even when page-content scrolls past the height of the viewport.</p>
        </div>
</template>

**Comment by lroal** [comment]
That work - but I needed to remove the position: absolute in order to display it.
**Another problem now: it is not possible to scroll to bottom if fixed top takes multiple lines.**
Possibly because margin-bottom is incorrect on page-content.

![image](https://user-images.githubusercontent.com/631501/166426300-3a5b7f0f-de79-43b5-96c8-40be263f5f51.png)
