### ISSUE TITLE
No export for props interface

### ISSUE THREAD

**Issue by Chupriarti** [framework7io/framework7#4024]
* Framework7 version: 6.3.17
* React.js version: 17.0.2
* Platform and Target: Chrome browser

There is a problem then trying to wrap framework7 react components in my own component and extend its props (types) - props interface in files like `node_modules\framework7-react\components\toggle\toggle.d.ts` has no export.

And so TypeScript shows this error:
`Exported variable 'Toggle' has or is using name 'ToggleProps' from external module ".../node_modules/framework7-react/components/toggle/toggle" but cannot be named.ts(4023)`

There is a way how to extract props types and use it for typing, but I need to do it with every component:
```js
export type F7ToggleProps = React.ComponentProps<typeof ToggleBase>
```

Why there is no export interface props and can it be added?

I've added `pull request` for this - https://github.com/framework7io/framework7/pull/4023

Example:
```js
import { Toggle } from "framework7-react";

export type F7ToggleProps = React.ComponentProps<typeof Toggle >;

export const MyToggle: React.FC<F7ToggleProps> = props => {
	return (
		<div>
			<Toggle {...props} />
		</div>
	);
});
```

With export props interface it will be possible to do like this:

```js
import { Toggle } from "framework7-react";
import { ToggleProps } from "framework7-react/components/toggle";

export const MyToggle: React.FC<ToggleProps > = props => {
	return (
		<div>
			<Toggle {...props} />
		</div>
	);
});
```

**Comment by nolimits4web** [comment]
Fixed in https://github.com/framework7io/framework7/pull/4023
