### ISSUE TITLE
Svelte + Framework7 Sheet Bug

### ISSUE THREAD

**Issue by osmancoskun** [framework7io/framework7#4049]
* Framework7 version: 7.0.5
* Svelte version: 3.48.0
* Platform and Target: All Platforms
* Live Link or JSFiddle/CodeSandbox: https://github.com/osmancoskun/f7-sheet-bug
### Describe the bug
When trying to use sheet on framework7, we saw a bug which is annoying and make application unusable. When you run application and click on next page, you will see a button. Button only opens sheet. if you open it only once, there is no problem.
But if you follow these steps, application gives closeByBackDropClick error and make application unusable.
### To Reproduce
1. Go to  page with button on main screen.
2. Click on Open Sheet and close it few times.
3. Go back to previous page with backlink
4. Try to go to page again.
5. See error on browser console.

### Expected behavior
Sheet to work as expected
### Actual Behavior
Cannot open sheet few times.

### Screenshots
![Screenshot from 2022-06-12 16-57-58](https://user-images.githubusercontent.com/44034936/173236792-749d91c0-7270-46f6-a888-c60158fabb24.png)

**Comment by nolimits4web** [comment]
It happens because you open sheet and then its content is changed, which can lead to sheet re-render/re-creation in a bit wrong way. Just call open sheet within 0 timeout, after its content upated like so:
```
<Button
    fill
    on:click={() => {
      modalTitle = "Vladimir";
      setTimeout(() => {
        f7.sheet.open(".test");
      })
    }}>Open Sheet</Button
  >
```
