### ISSUE TITLE
React & vite js doesn't load .env values

### ISSUE THREAD

**Issue by vitalijalbu** [framework7io/framework7#4056]
* Framework7 version: 7.0.5
* React.js version: 18.2.0
* Platform and Target: capacitor, but also all devices
* Live Link or JSFiddle: I cannot create a link cause it takes too much time.

### Describe the bug
Just started a new blank vite js and f7 template, but cannot import values from .env files.

### To Reproduce
1. create .env file
2. add some values starting with VITE_ (ex: VITE_API_URL)
3. console.log(import.meta.env.VITE_API_URL) in any js file
4. See undefined value

### Expected behavior
2-3 moths ago, i think with the f7 version 7.0.1 or 7.0.0 it worked perfectly.

### Screenshots
https://t.me/framework7ru/4821

**Comment by nolimits4web** [comment]
How this is related to Framework7? `.env` file must be in Vite project root, which is the `src` folder

**Comment by petersahanaya** [comment]
it still say's undefine idk why i put the .env in src folder but is still undefine. can anyone help me ?

**Comment by blackdreamer15** [comment]
I faced the same issue and after adding the .env file inside the src directory, it resolved it.
