### ISSUE TITLE
Why framework7 with vuejs doesn't have infinite scroll component?

### ISSUE THREAD

**Issue by francelwebdev** [framework7io/framework7#4064]
* Framework7 version: [e.g. 3.0.0]
* Vue.js version: [e.g. 2.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
There is a Forum for questions
