### ISSUE TITLE
vite: missing export in package

### ISSUE THREAD

**Issue by willmendil** [framework7io/framework7#4066]
* Framework7 version: .0.7
* Platform and Target: windows

### Describe the bug
getting `  [vite:resolve] Missing "./framework7-bundle.css" export in "framework7" package`

### To Reproduce
Install wails.io and simply import the bundle.js in the index.html. When running wails dev, vite spits out the issue

### Expected behavior
should import without problem

### Actual Behavior
Getting the error mentioned abot

**Comment by nolimits4web** [comment]
https://www.framework7.io/docs/package#es-module-bundle

**Comment by willmendil** [comment]
I'm struggeling to understand how to fix my problem. 

I have `script(defer='' type="module" src='./node_modules/framework7/framework7-bundle.js')` in the index.html
I can put the import in the javascript, but i don't see how that helps (it doesn't). and I don't understand what how to work with the export json described in the documentation
