### ISSUE TITLE
Initial Page Route '/' not working when browserHistory: true

### ISSUE THREAD

**Issue by pancaz** [framework7io/framework7#4080]
* Framework7 version: [e.g. 3.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
when i create initial page route '/' its not working when browserHistory: true

### To Reproduce
1. make initial page route
2. enable true browserhistory
3. See error not found

### Expected behavior
browserhistory enabled true and initial page route '/' working

### Additional context
target browser and cordova android

**Comment by vitalijalbu** [comment]
I ALSO HAVE THIS PRBLEM, I'M BUILDING A WEBSITE AND OF COURSE NNED IT URGENTLY.

**Comment by nolimits4web** [comment]
That is the point of `browserHistory`, initial route will be ignored
