### ISSUE TITLE
Swipe back gesture not always triggering

### ISSUE THREAD

**Issue by lroal** [framework7io/framework7#4088]
Sometimes the swipe back gesture is very hard to trigger compared to the native one. I am testing on iphone 13 mini.
Can anything be done to make it more like the native one ?
I think it is more unreliable when using my right thumb than my left thumb.

**Comment by nolimits4web** [comment]
There is a param that you can configure touch active area for swipe back https://framework7.io/docs/view#param-iosSwipeBackActiveArea
