### ISSUE TITLE
Condition render popup in React backdrop not showing

### ISSUE THREAD

**Issue by vitalijalbu** [framework7io/framework7#4089]
Backdrop is not showing if displaying conditionally (setstate true or false) popup component.
If display it normally all is ok, but if doing

`{StateOpended && (<Popup opened />)}`
backdrop is not showing, only the popup.
Source forum: https://forum.framework7.io/t/condition-render-popup-in-react-backdrop-not-showing/15757

[CodeSandbox – 24 Oct 22]()

* Framework7 version: 7.0.8
* React.js version: 18
* Platform and Target: all
* Live Link or JSFiddle: https://codesandbox.io/s/f7-popup-bugs-forked-itoq3g

### Describe the bug
`{StateOpended && (<Popup opened />)}`
backdrop is not showing, only the popup.

**Comment by nolimits4web** [comment]
Popup state must be toggled by using `opened` prop, otherwise even on popup close it won't be able to destroy itself on close
