### ISSUE TITLE
Calendar Picker missing

### ISSUE THREAD

**Issue by theavijitsarkar** [framework7io/framework7#4092]
* Framework7 version: 7.0.2
* Vue.js version: 3.2.33
* Platform and Target: Browser / Cordova

### Describe the bug
Calendar picker is missing in vue framework7
https://framework7.io/docs/calendar

### Expected behavior
Calendar picker should be present in vue f7 just as it is present in normal version

### Actual Behavior
calendar is missing

**Comment by nolimits4web** [comment]
You should use core version of the Calendar API in Vue version
