### ISSUE TITLE
Theme Color Issue with Dialogbuttons?

### ISSUE THREAD

**Issue by phoebusryan** [framework7io/framework7#4104]
- Framework7 version: 6.3.2
- Platform and Target: All
- Live Link or CodeSandbox: -

### Describe the bug

If I change the theme-color of F7 via Bodyclass to e.g. Purple (color-theme-deeppurple), the dialogbuttons are still blue. I think, that's not correct.

### To Reproduce

Set theme to e.g. purple. The color-Attribut in CSS-Class ".dialog-button"  uses the variable "--f7-dialog-button-text-color)" which is always blue. I know I can change this by myself but isn't it wrong that the button isn't purple?

### Expected behavior

Dialog-Buttons should also be purple.

### Actual Behavior

Dialog-Buttons are blue.

**Comment by Simone4e** [comment]
_Live Link or CodeSandbox:_ please add it.

**Comment by phoebusryan** [comment]
Sorry for my late response.

Just go to https://framework7.io/docs/dialog#examples 

... and changed the theme to a different color via Firebug or similar (direct or via javascript with this command:
Dom7('.view-main').addClass('color-theme-red');

.... then click on "ALERT" or any other buttons to see that the buttons still have blue color.

**Comment by nolimits4web** [comment]
Dialog is rendered our of the View, you need to add class to body/html or to dialog itself

**Comment by phoebusryan** [comment]
Okay, makes sense. How can I add a class to the dialog?
