### ISSUE TITLE
Error: with npm run build-cordova

### ISSUE THREAD

**Issue by dinodev0101** [framework7io/framework7#4114]
- Framework7 version: 7.0.9

### Describe the bug

I created a new project with
"framework7 create --ui"
by selecting core for framework, cordova(Android, iOS) for platform, simple view and including all components with default themes.

After creating and installing "node modules" for this simple project, I was going to run this script:
npm run build-cordova.

But there was an error I encountered.

The 7th, 8th lines of the file (./build/build-cordova.js) are
```
let entry = fs
    .readdirSync(path.resolve(__dirname, '../cordova/www/assets'))
    .filter((f) => f.includes('index.') && f.includes('.js'))[0];

const hash = entry.split('index.')[1].split('.js')[0];
```

But here, entry is undefined with your current release.
So I changed them to

```
let entry = fs
    .readdirSync(path.resolve(__dirname, '../cordova/www/assets'))
    .filter((f) => f.includes('index-') && f.includes('.js'))[0];

const hash = entry.split('index-')[1].split('.js')[0];
```

And I replaced all 'index.' in this file to 'index-'. After that, I could build project.

**Comment by amyounesi** [comment]
me too
