### ISSUE TITLE
Feature request: 'Ajax Pages' for Tabs

### ISSUE THREAD

**Issue by dnmd** [framework7io/framework7#412]
As mentioned in a issue and in various questions on the forum;
- How to load view tab dynamically? #280
- [Pages in the Tab-Bar example](http://www.idangero.us/framework7/forum/#!/questions:pages-in-the-tab-bar-exampl)
- [How to separate each tab into its own page](http://www.idangero.us/framework7/forum/#!/getting-started:how-to-seperate-eacb-tab-in)
- [Is there any way to refresh the content of a tab when we visit it?](http://www.idangero.us/framework7/forum/#!/questions:is-there-any-way-to-refresh)

It seems there are more people (besides me) looking for a way to load 'Ajax Pages', to leverage for example Template7. In my current solution using the `$$('.tab').on('show', function(){ })` event I have to overcome a lot of "issues" which already have been implemented within F7 (which is awesome, did I mention that :)), it feels a bit like I am reinventing the wheel. Therefore this request.

Current "issues" that we need to overcome;
- handling the whole request via e.g. `mainView.router.load(options)`
  - to leverage Template7 etc.
- caching / reloading
- page "transitions" e.g. showing the `myApp.showIndicator();`
- etc.

**Comment by nolimits4web** [comment]
I see, the problem not seems pretty hard, but probably a bit confusing because it has a lot of different ways to implement it. Currently i am working on new open-source demo app based on tab bar layout. Will try to cover there such questions

**Comment by nimo23** [comment]
I do not use tab-on event for loading tab-content:

```javascript
$('#tab1').on('show', function () {
   //refresh tab here
});


I load the tab-contents with the following method:

```javascript
in js:
view_tab_1.router.load({url: 'src/tab_1.html', animatePages: false})

in index.html:
<div id="view_1" class="view view-main tab">
      	<!-- Navbar-->
		<div class="navbar">
			<div class="navbar-inner">
				<div class="center">1</div>
			</div>
		</div>
        <!-- Pages-->
        <div class="pages navbar-through"><!--loaded by router--!></div>
      </div>


in tab_1.html:
<!-- Navbar-->
<div class="navbar">
	<div class="navbar-inner">
		<div class="center">Tab 1</div>
	</div>
</div>
<div class="page" data-page="p-contacts">
	<div class="page-content">
		<div class="content-block-title">..</div>
		<div class="content-block">
			..
		</div>
	</div>
</div>

Which way is better? "on-event" or "navigator"?

**Comment by nimo23** [comment]
Maybe, it would be better to provide something like "page-load"-property to load a view dynamically without triggering a link in html. For example:

`<div class="pages navbar-through" data-page-load="src/tab1.html"></div>`

This will load the content of tab1.html in index.html (only) one time.

**Comment by ptoner** [comment]
I'm sure someone could come up with a more elegant permanent solution.

I'm using the Material scrolling tabbar. I haven't tested this with anything else. 


Using 1.5.0 if you change lines 7552-7554 from 

```javascript
                if (clicked.hasClass('tab-link')) {
                    isTabLink = true;
                    app.showTab(clickedData.tab || clicked.attr('href'), clicked);
                }
```

to 

```javascript
                if (clicked.hasClass('tab-link')) {
                    isLink = true;
                }
```

It'll force a tab-link to act like a normal link. Which means if you're using the default ajax links the tab links start acting like any other link. If you throw the "no-animation" class on the tab link you can barely tell the difference between it and the non-ajax tabs. Hitting the back button looks slightly off but I can live with it for now.

**Comment by boynet** [comment]
+1 or more specific case:
make scrollable toolbar normal linkable and no tab like

**Comment by guylando** [comment]
So what is the recommended way to load an ajax tab view?

**Comment by guigiani** [comment]
Any improvement on this?

**Comment by nolimits4web** [comment]
It is possible in v2
