### ISSUE TITLE
Description in Smart Select

### ISSUE THREAD

**Issue by kumar-dinesh** [framework7io/framework7#4125]
If description element can be added to Smart Select would be really nice.

It can be achieved by using data-description attribute on option attribute and then elements be populated on initialisation.
<option data-description="Batman from Gotham">Batman</option>

<img width="316" alt="Screenshot 2023-01-17 at 11 01 30 AM" src="https://user-images.githubusercontent.com/57162970/212817970-94839f1e-5135-4f5f-b1e1-05c562eb805c.png">

**Comment by Simone4e** [comment]
Actually you can already do it you have to use [renderItems](https://framework7.io/docs/smart-select#param-renderItems) here's an [live example](https://codesandbox.io/p/sandbox/brave-snow-zwfq4r?file=%2Fsrc%2Fpages%2Fhome.f7.html&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A63%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A63%7D%5D)

**Comment by kumar-dinesh** [comment]
> Actually you can already do it you have to use [renderItems](https://framework7.io/docs/smart-select#param-renderItems) here's an [live example](https://codesandbox.io/p/sandbox/brave-snow-zwfq4r?file=%2Fsrc%2Fpages%2Fhome.f7.html&selection=%5B%7B%22endColumn%22%3A85%2C%22endLineNumber%22%3A54%2C%22startColumn%22%3A85%2C%22startLineNumber%22%3A54%7D%5D)

That's what I was looking for

**Comment by kumar-dinesh** [comment]
That's what I was looking for
