### ISSUE TITLE
[Feature request] Prevent close element cordova back button

### ISSUE THREAD

**Issue by Simone4e** [framework7io/framework7#4147]
It would be useful to be able to block the back button when in the element (e.g. popup) it has the parameter "don't close" (e.g. in the popup it is `closeByBackdropClick` or `closeOnEscape`

So you should add to the Cordova file:

```
document.addEventListener(
      'backbutton',
      function (e) {
      if ($('.popup.modal-in').length) {
          if ($('.popup.modal-in>.view').length) {
              //if this popup has this parameter 
              e.preventDefault();
              return false;
             //else ...
            
          }
     }
});
```

**Comment by nolimits4web** [comment]
This is a custom script file, you can for sure just modify that file according to your needs

**Comment by Simone4e** [comment]
It's not a custom script just a basic usage, if I have closeByBackDrop false I want to denied close from all source included cordova back button
