### ISSUE TITLE
[v8] Swiper 3D Cube and 3D Coverflow effects demos in KS are not working properly

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7#4155]
- Framework7 version: **8.0 beta 2 to 8.0 beta 9**
- Platform and Target: iOS and MD themes tested on Safari 16.4 (17615.1.26.101.9, 17615) - macOS Monterey 12.6.4 (21G526)

### Describe the bug

The Swiper 3D Cube and 3D Coverflow effects demos in KS are not working properly (**Framework7 8.0 beta 2 to 8.0 beta 9**)

### Screenshots

![Istantanea 2023-03-31 alle 13 10 26](https://user-images.githubusercontent.com/1197819/229106545-986a4a4d-b7b6-4464-b5dd-326c6d6a78cd.png)

![Istantanea 2023-03-31 alle 13 11 04](https://user-images.githubusercontent.com/1197819/229106568-18ba930e-4d9a-40c5-b290-7f2849ce9b3e.png)

**Comment by nolimits4web** [comment]
Maybe cache? Works for me in Safari 16.3

**Comment by DAnn2012** [comment]
Hi @nolimits4web 

I thank you for the answer.

I found out that the problem was caused by having the experimental features `CSS 3D Transform interoperability` turned on in Safari's Develop menu.

By disabling this feature everything became normal.

The strange thing is that with Framework7 7.1.5 and 8.0 beta 1 (which include the old version of Swiper) and with the demos published on the Swiper site (new version)

https://swiperjs.com/demos#effect-cube

https://swiperjs.com/demos#effect-coverflow

The defect does not occur even with that feature active.

Thank you.

**Comment by DAnn2012** [comment]
Hi @nolimits4web 

Even the recent **Safari 16.4.1** update by default has the experimental features `CSS 3D Transform interoperability` active in Safari's Develop menu and doesn't make the two effects **3D Cube** and **3D Coverflow** of Swiper included in Framework7 v8.x work well.

By disabling this feature everything goes back to normal.

Thanks.

**Comment by DAnn2012** [comment]
With the release of **Swiper 10.0.3** (which is included in **Framework7** version **8.2.0**) I did more tests with the demos posted here:

https://swiperjs.com/demos#effect-cube

https://swiperjs.com/demos#effect-coverflow

And I checked that:

- with the **Core**, **React** and **Vue** versions everything works correctly both with the `CSS 3D Transform interoperability` feature enabled and disabled
- **Element** versions only work with `CSS 3D Transform interoperability` disabled, otherwise they have the same problem as in Framework7

**Comment by nolimits4web** [comment]
Yes, and it is issue with Safari, no ways to fix it at the moment. Use core version of Swiper instead
