### ISSUE TITLE
Please keep menus!

### ISSUE THREAD

**Issue by ghys** [framework7io/framework7#4156]
**Is your feature request related to a problem? Please describe.**
I've seen you've decided to remove menu components in f7 v8.
I just want you to know that they're very much being used in our project and hardly replaceable. See the screenshots and GIFs in the additional context section!
I very much would like to upgrade to f7 v8 eventually (there are additional hurdles) but this is kind of a showstopper, because menus were used *a lot* in our case.

**Describe the solution you'd like**
Please keep menus alive for the foreseeable future!

**Describe alternatives you've considered**
Buttons & popovers; yes, but it wouldn't be the same, menus are used everywhere.

**Additional context**

https://community.openhab.org/t/light-control-card/140372
![](https://community-openhab-org.s3.dualstack.eu-central-1.amazonaws.com/original/3X/9/2/92efe49d2b2b4e52b0a55c0c503b2a0469242f4e.gif)

https://www.openhab.org/docs/ui/layout-pages.html#responsive-layout-pages
![image](https://user-images.githubusercontent.com/2004147/229311283-5e04ada0-2fc2-464c-94f2-36be6a32a402.png)

![](https://www.openhab.org/assets/img/responsive2.b69d2105.gif)

**Comment by nolimits4web** [comment]
> Describe alternatives you've considered
> Buttons & popovers; yes, but it wouldn't be the same, menus are used everywhere

button + popover is exactly the same, why not?

**Comment by nolimits4web** [comment]
P.S. you can check this CodeSandbox and port it from v7 like it is done here https://codesandbox.io/p/sandbox/f7-core-menu-pj8z3q
