### ISSUE TITLE
Aurora options for v8+ 

### ISSUE THREAD

**Issue by basejump** [framework7io/framework7#4160]
We are very sad to see the Aurora theme deprecated. 
We have been digging into version 8 and looking at the options as we make heavy use of the framework 7 on the desktop. 

Are there and notes or thread as far as options for v8+ using the desktop? Will it be possible for us to add it back in in our code base or is it mobile only from v8+ and recommendation is to stay on v7 for future?

Thanks for any links or guidance that can be provided for those of us who are looking at what our options are.

**Comment by godpod** [comment]
we are also heavily dependent on Aurora. Please provide a way to add back the aurora theme in v8. 

Really sad to see Aurora being removed as it is one of the main themes and also a great theme for desktops and electron app version of the mobile versions. Quite different from ios and md themes and has its own use cases.

Can support Framework7 if this is reconsidered in v8. Looking forward for early resolving this.

**Comment by JonMale** [comment]
Looking at the commit to remove it, the Aurora theme was obviously a ton of work to maintain.  That said, we would welcome the return of a desktop theme of some sort as we supply a data grid heavy admin console in addition to our mobile app.

Thank you for all your years maintaining Framework7.  We're beginning a fairly large project and had been waiting for 8.0 to drop.

**Comment by nolimits4web** [comment]
You have few options:

- stay on v7
- switch to iOS theme which looks pretty the same
- better option - migrate to Material You which is supposed to be a cross platform/device/screen

**Comment by gaohomway** [comment]
It is a pity that the Aurora theme was deleted. Our web pages rely heavily on the Aurora theme.
I don't know why the Aurora theme was abandoned. You can open a discussion page to hear more people's thoughts on the Aurora theme.

The biggest difference between the Aurora theme and the iOS theme is that there are CSS events, which allow each element to have different effects when the mouse passes over it. So it doesn't require much maintenance work, so I don't know why the Aurora theme was abandoned.
