### ISSUE TITLE
Swiper slider "Cannot read properties of undefined (reading 'length')" when viewing within mobile view

### ISSUE THREAD

**Issue by willmero** [framework7io/framework7#4164]
- Framework7 version: 8
- Platform and Target: mobile browser
- Live Link or CodeSandbox/CodeSandbox: https://framework7.io/kitchen-sink/svelte/dist/?theme=ios

### Describe the bug

When swiping on the swipers within the Kitchen-sink I'm seeing a number of errors in the console for "Cannot read properties of undefined (reading 'length')'"

### To Reproduce

1. Visit the following kitchen-sink link in Chrome: https://framework7.io/kitchen-sink/svelte/dist/?theme=ios
2. Open up the dev tools and select the "Toggle device toolbar" button in the top left corner of dev tools to see the website in a mobile setting
3. Refresh the page to ensure you have the mobile version running
4. Look at the console, and try swiping on the swipers

### Expected behavior

No errors in the console. Functionality seems to still work at a first glance, but wondering what other effects this will have later on.

### Actual Behavior
Multiple errors in the console

### Screenshots
![Screenshot 2023-04-13 at 1 02 34 PM](https://user-images.githubusercontent.com/6343859/231832518-12475fe4-b143-46fb-8b49-388482a6509e.png)

**Comment by Ada-lave** [comment]
Hi, can u say how you fix that
