### ISSUE TITLE
[virtual-list] jumps back to top after scrolling down the list

### ISSUE THREAD

**Issue by trancee** [framework7io/framework7#4171]
- Framework7 version: 8.0.4
- Platform and Target: Web
- Live Link or CodeSandbox: https://codesandbox.io/p/sandbox/inspiring-hill-nxrfc8

### Describe the bug

When using the `virtual-list` component and adding multiple items so that you have to scroll the list, after a while it suddenly disrupts the scrolling and jumps back to the top.

### To Reproduce

1. Open the sandbox
2. See multiple gray card items
3. Scroll down the list
4. When nearing the end of the list, it will suddenly jump back to the top

### Expected behavior

It should not jump back to the top after reaching a certain amount of height when scrolling down the list.

### Actual Behavior

When nearing the end of the list by scrolling down, it will suddenly jump back to the top.

### Screenshots

See sandbox.

**Comment by nolimits4web** [comment]
It is because you have wrong config https://codesandbox.io/p/sandbox/gracious-kare-x0i07z?file=%2Fsrc%2Fpages%2Fhome.f7.html&selection=%5B%7B%22endColumn%22%3A15%2C%22endLineNumber%22%3A30%2C%22startColumn%22%3A15%2C%22startLineNumber%22%3A30%7D%5D
