### ISSUE TITLE
Add cssClass Dialog Shortcuts Parameters

### ISSUE THREAD

**Issue by Simone4e** [framework7io/framework7#4196]
**Is your feature request related to a problem? Please describe.**

It's not really a problem, in terms of code optimization it would be nice to have the "cssClass" property to allow developers to set a class for all `dialogs`. In my case a class to make the dialog scrollable.

**Describe the solution you'd like**

Simply add this entry as a default entry

```
var app = new Framework7({
  dialog: {
    ...
    cssClass: 'class',
    ...
  }
});
```

**Describe alternatives you've considered**

At the moment I have to put it in each `dialog `manually.

**Comment by nolimits4web** [comment]
If you want to add it to every dialog, then it is even better to use just `.dialog` class which all dialogs have
