### ISSUE TITLE
You need to use slot=list

### ISSUE THREAD

**Issue by cyberbeat** [framework7io/framework7#4202]
You need to use slot=list

_Originally posted by @nolimits4web in https://github.com/framework7io/framework7/issues/4201#issuecomment-1624160416_

Sorry, but I don't understand, where is this documented?

Even if I used` slot="list" `in the f7-item-group element I get two cascaded `<ul>`:

```
<div class="list list-strong-ios list-outline-ios list-dividers-ios media-list">
<ul>
<div class="list-group" slot="list">
<ul>
<li class="list-group-title media-item">A....
```

from vue-template code

```
<f7-block-title>Dynamic list-group</f7-block-title>
    <f7-list media-list dividers-ios strong-ios outline-ios>
      <f7-list-group v-for="g in groups" slot="list">
        <f7-list-item title="A" group-title />
...
```

Same demo as before:

https://codesandbox.io/p/sandbox/inspiring-pond-93tw8k?file=%2Fsrc%2Fpages%2Fhome.vue

**Comment by cyberbeat** [comment]
https://codesandbox.io/p/sandbox/inspiring-pond-93tw8k?file=%2Fsrc%2Fpages%2Fhome.vue

**Comment by cyberbeat** [comment]
If I understand right, in components/list.js this part is relevant:

```
if (tag && typeof tag === "symbol") {
...
}
```

In the first example this case happens (symbol), in the second example, the third case.

**Comment by nolimits4web** [comment]
```
<f7-list media-list dividers-ios strong-ios outline-ios>
  <template #after-list>
    <f7-list-group v-for="g in groups">
      ...
    </f7-list-group>
  </template>
</f7-list>
```

**Comment by cyberbeat** [comment]
Thanks, that works, although it's quite unintuitive.
