### ISSUE TITLE
"props" not passed to component when using "openIn"

### ISSUE THREAD

**Issue by Tarekajaj** [framework7io/framework7#4215]
- Framework7 version: 8.1.0
- Platform and Target: Chrome
- Live Link or CodeSandbox: [CodeSandbox](https://codesandbox.io/p/sandbox/new-night-rkpy42?file=%2Fsrc%2Fjs%2Fapp.js%3A1%2C1)

### Describe the bug

When using router.navigate with openIn option the props are not passed to the component loaded, i.e. page inside modal

### To Reproduce

in the CodeSandbox, click "Open normally", you will see the full list of pros received by the test page (id & extra),
but if you click on "Open with openIn="popup" which is the same except it has openIn="popup", you will only see the id prop passed in the url and not the extra prop passed in the options

### Expected behavior

the props passed in the navigate option to be available at the destination component normally

### Actual Behavior

props passed in navigate are not available

### Screenshots

Check [CodeSandbox](https://codesandbox.io/p/sandbox/new-night-rkpy42?file=%2Fsrc%2Fjs%2Fapp.js%3A1%2C1)

### Additional context

N/A

**Comment by njvb** [comment]
+upvote
