### ISSUE TITLE
Wrong React interfaces are used for the Svelte import components. 

### ISSUE THREAD

**Issue by ievgennaida** [framework7io/framework7#4255]
Framework 7 Svelte types has react styles css.

- Framework7 
    "framework7": "8.3.2",
    "framework7-svelte": "8.3.2",

- Platform and Target: Chrome PC

Files:

list-index.svelte
input.d.ts

Trying to import react styles:

See   inputStyle ?: React.CSSProperties;

**Comment by nolimits4web** [comment]
t0ggles-create konsta

**Comment by nolimits4web** [comment]
t0ggles-unlink

**Comment by nolimits4web** [comment]
t0ggles-create f7
