### ISSUE TITLE
iOS back touch swipe doesnt work at 120hz Promotion

### ISSUE THREAD

**Issue by bulutg** [framework7io/framework7#4274]
- Framework7 version: 8.3.3
- Platform and Target: iOS 17.5.1 Capacitor and safari
### Describe the bug

iOS back touch swipe doesnt work at Promotion 120hz

### To Reproduce

1. Back swipe kitchensink

### Expected behavior

Smooth back swipe

### Actual Behavior

Low fps

**Comment by nolimits4web** [comment]
Not related to F7
