### ISSUE TITLE
After Version 8 F7 does not work on IOS 12.x devices

### ISSUE THREAD

**Issue by grahampontin** [framework7io/framework7#4279]
- Framework 7 v8.x
- Target platform Safari on IOS 12.x

### Describe the bug

v8 App fails to initialize on older IOS devices.

### To Reproduce

To reproduce: open the f7 kitchen sink v8 on any IOS 12.x device (e.g. iPad Air) in safari. A blank screen is all you see. Works fine in F7 versions <=7.  

### Expected behavior

App should initialize 

### Actual Behavior

blank screen

**Comment by nolimits4web** [comment]
Could you find an even older device? Why in the world were should support iOS 12?
