### ISSUE TITLE
the framework customized alert does not work well with jquery blur event.

### ISSUE THREAD

**Issue by morer** [framework7io/framework7#49]
Hey, I catch this problem. In the kitchen-sink,I include the jquery lib and  I add an input with id="txt" in list-view.html, and in kitchen-sink.js, I add the code below 
'''
    if (page.name === 'list-view') {
        console.log("hellow");
        $("#txt").blur(function(e){
        console.log("hellow");
            if($(this).val().trim()===''){
                $(this).focus();
                myApp.alert("You should input something");
                }
        });
    }
'''
something bad happen, it run into an infinite loop!!

**Comment by jefmaus** [comment]
I need focus input field after myApp.alert.

You should consider adding the option to return focus after closing the alert.

Example: myApp.alert ("message", "input_return_focus");
