### ISSUE TITLE
Swipe back will crash/freeze navigation (IOS, add to HomeScreen App)

### ISSUE THREAD

**Issue by sneila** [framework7io/framework7#594]
Hi, 

On iPhone i created a Homescreen App (through safari) of the standard demo (under /dist).

Fire the app up. 
Click Service, the About page, and than add a Dynamic Page.
Swipe 3 times to get to the home/start screen and than all navigation will not work. None of the buttons will work.
Except the open sidebar icon top right.

Usually it takes 3 swipe back to freeze navigation, whatever the amount of pages you visited (create dynamic page .)

ps: i think that the behavior works like this if you swipe fast. If you swipe slower it might not freeze.

**Comment by nolimits4web** [comment]
Hi,
Can't replicate this issue. What is your device and OS version?

**Comment by sneila** [comment]
iPhone 6, IOS 8.4 (not 8.4.1)

i can replicate it every single time
just swipe fast back, like you would with any app.

as homescreen app as well as in Safari

I will test it on an older iphone with outdate ios too and let you know

these are my setting in the my-app.js:

var myApp = new Framework7({
	pushState: true,
	cache: false,
	swipeBackPageAnimateOpacity: false,
	swipeBackPageAnimateShadow: false,
	swipeBackPageActiveArea: 100,
	// swipeBackPageThreshold: 100,
	swipeBackPage: true
	// swipePanel: 'left'
});

tried everything related to swiping. 
And AnmateOpacity, does not seem to work, the 'previous' page still show darken (i guess less opacity) while swiping.

When it freezes, if on home page, i can click Services, it shows the click animation (focus), but nothing happens. Initially i thought there is some sort of overlay that does not disappear, but there is clicktrough so i have no idea, it's hard to debug it on the phone with Safari dev tools.
On desktop, i can not simulate the dragging fast, to see if it happens too.

**Comment by nolimits4web** [comment]
I still can't replicate it. Can you check your `mainView.allowPageChange` property, i guess for some reason it is still `false` at this moment?

**Comment by sneila** [comment]
I mirrored the device on my screen:
https://drive.google.com/file/d/0B6MtqClJH_q-ZFJ6ZjM5YXBHTVE/view?usp=sharing

You see how i can scroll 5 levels deep, and then when swipe back, at some point it just stays stuck.
There is no way to record the tap, but before i tap the sidebar, i try all links on that page, and nothing happens.

allowPageChange: true does also not do anything.

**Comment by nolimits4web** [comment]
Then there could be issue with layout or with data, do you see any errors in console?

**Comment by sneila** [comment]
The layout is the standard one that comes with the distribution.
To be honest i did not try  to use this because of this issue, so i dod not continue to look into it.

There are also no errors in the console. (Was the first thing i tried/looked into)

I have no clue what can trigger it.

**Comment by valnub** [comment]
Never had this problem. Can anyone replicate this? Otherwise I'd close it since the ticket is old af.

**Comment by shyamkushwah** [comment]
ng-repeat behaviour unexpected with swipeBackPage property in angularjs with framework7.

I am use swipeBackPage = true property for swipe than ng-repeat behaviour unexpected (ng-repeat bind multiple time) on screen swipe or back both opration.

![capture1](https://user-images.githubusercontent.com/30834627/29074598-8400d8c0-7c6d-11e7-965f-eb850c9b9af3.PNG)

**Comment by ZanderBrown** [comment]
Should be resolved in V2
