### ISSUE TITLE
Material: Action Grid Component

### ISSUE THREAD

**Issue by murliatdure** [framework7io/Framework7#676]
![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3QTBOb0p2WTh4NFE/components_bottomsheets_modal13.png)

**Comment by murliatdure** [comment]
Grid-style bottom sheet with icons

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3a2JBazEtX3R2Ulk/components_bottomsheets_specs7.png)

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B7WCemMG6e0VTDNtb2dnZTZCXzQ/components_bottomsheets_specs8.png)

**Comment by nolimits4web** [comment]
Will look, probably worth to implement, but again, can be done with few custom additional CSS styles on action sheet

**Comment by J05HI** [comment]
@nolimits4web 
If you like I can integrate that and commit it then :)

**Comment by ZanderBrown** [comment]
@J05HI please open a PR

**Comment by nolimits4web** [comment]
Done in v2
