### ISSUE TITLE
Material: Search

### ISSUE THREAD

**Issue by murliatdure** [framework7io/Framework7#683]
Searchbar integrated with the Navbar (incl back button)

![image](http://i.stack.imgur.com/rtRLq.png)

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3aUhWVUw3TFhUN1U/components_textfields_auto1.png)

![image](http://d.ibtimes.co.uk/en/full/1438927/whatsapp.png)

![image](http://www.tuexpertoapps.com/wp-content/uploads/2015/04/whatsapp-material-design-android-02.jpg)

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3M1RJdzAwWE05cmc/components_textfields_auto4.png)

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3ZTFiMi1fRzZIcVU/components_textfields_auto6.png)

References:
https://www.google.com/design/spec/components/text-fields.html#text-fields-formatting
https://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field

**Comment by murliatdure** [comment]
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsa1RlU3Y2SDJWREE/patterns_navigational-transitions_sibling-to-sibling_tabs-02_xhdpi_003.webm

**Comment by nolimits4web** [comment]
This feature is also on roadmap

**Comment by nolimits4web** [comment]
In v2
