### ISSUE TITLE
Trig Javascript in .html file after loading page.

### ISSUE THREAD

**Issue by tcladet** [framework7io/framework7#70]
Hello!
When you click on a link, an Ajax call is done and the page is loaded. But in this page, there is Javascript content that can trigger external libraries' content like Highcharts for example.

Are there any way to use Javascript in .html file after an Ajax call loading page ?

Thanks for your Framework!
CloudCompany

**Comment by tonyjohnvan** [comment]
Actually you don't have to use any other external libraries since I figured that $$ in Framework 7 have some jQuery functions to use, thus:

$$(document).on('pageInit', function(e) {
    var page = e.detail.page;

    $$(page.container).find("script").each(function (el) {
        if ($$(this).attr('src')) {
            jQuery.getScript($(this).attr('src'));
        }
        else {
            eval($$(this).text());
        }
    });
});
will do the job smoothly.

**Comment by tsanren89** [comment]
Doesn't work with me, any other solution? Thanks.

`$$(document).on('pageInit', function(e) {
	var page = e.detail.page;

	$$(page.container).find("script").each(function(el) {
		if ($(this).attr('src')) {
			jQuery.getScript($(this).attr('src'));
		}
		else {
			eval($(this).text());
		}
	});
});
`

**Comment by eslindsey** [comment]
Fully native Framework7 implementation (no jQuery necessary):

    $$(page.container).find('script').each(function (el) {
        if ($$(this).attr('src')) {
            var s = document.createElement('script');
            s.src = $$(this).attr('src');
            $$('head').append(s);
        } else {
            eval($(this).text());
        }
    });
