### ISSUE TITLE
Picker in Android Webkit using readonly input, however soft-keyboard is always show up! 

### ISSUE THREAD

**Issue by deaboway** [framework7io/framework7#755]
Picker in Android Webkit using readonly input, however soft-keyboard is always show up!

**Comment by nolimits4web** [comment]
Can't replicate it. Would be good to know Android version and browser type/version

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted
