### ISSUE TITLE
What is the best way to load dynamic page in a view?

### ISSUE THREAD

**Issue by gpetrov** [framework7io/framework7#76]
Hi Vlad,

Compliments about your Framework7! It looks amazing! 

Just one question about loading dynamic pages in a view.

We would like to load a page that is initially empty with loader, that kicks off an Ajax call to load its content. When content arrives the page should be emptied and the loader replaced with the real content. Preferably afterwards we would like also to implement a pull to refresh.

What will be the best way to do so? Currently if the page is initially empty and then content is loaded with loadContent it becomes another page .. so the back button returns to the loader page instead of replacing the current...

Thanks,
   George

**Comment by max-wen** [comment]
I think if the  `view.router` had an API like `replaceContent`(with page name parameter) would be better. 

for example: 

``` javascript

var popupView = null;
var cachedUrl = '';
// pop-up tool
function loadPopupPage(pageUrl) {
    if( cachedUrl != pageUrl ) {
        $$.get(pageUrl,function(pageContent){
            $$('.popup-view').find('.page-content').html(pageContent);
        });
    }
    cachedUrl = pageUrl;
    myApp.popup('.popup-view');
}

```

I need to handle the cache myself, if the `view.router` provides `replaceContent` API.
