### ISSUE TITLE
Ok, and cancel for modals should have keyboard shortcuts

### ISSUE THREAD

**Issue by etiennea** [framework7io/framework7#798]
Ok, and cancel for modals should work with keyboard Esc and return keypress

**Comment by nolimits4web** [comment]
Sorry, it is a mobile framework. There is no such things on mobiles :smile:

**Comment by etiennea** [comment]
Well actually it's so good I use it for web stuff as well!
But seriously there is a return button on the prompt modal and it should work and if you do that you might as well add Esc so it can be used for web stuff without being really hacky.

**Comment by nicooprat** [comment]
I'm also thinking about using F7 on a responsive project, and basic keyboard actions could be really useful, eg. up/down + enter on autocomplete results. As you said, it's "mobile-first", not "mobile-only" :) It's especially the best frontend framework I know, that feature is one of the few missing to be perfect!

**Comment by ZanderBrown** [comment]
@nolimits4web do you plan on adding this?

**Comment by nolimits4web** [comment]
@ZanderBrown not on my roadmap ;)
