### ISSUE TITLE
smart select item-after

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [framework7io/framework7#910]
Hello Framework7 team,

I can set the value of a smart select and when I open the options I can see the value is checked.
But do I manually have to populate the item-after so I can see the selected item before opening smart select?
Please advise.

Kind regards,
Mario

**Comment by nolimits4web** [comment]
Yes, at the moment you have to update item-after manually if you change select value programmatically. For example $('.item-after').text('sometext');

**Comment by valnub** [comment]
Maybe we can fix this in v2 ?

**Comment by TommyZG** [comment]
Hi, this is still an issue. Can we trigger update of .item-after by $$(".smart-select").focus() or .change() or .click()? We can't at the moment - is there anything other than those three that would trigger the update? Setting it manually works, of course.

**Comment by valnub** [comment]
@TommyZG F7 v2 final has been released few days ago. Did you check if the problem still exists there?

**Comment by TommyZG** [comment]
Hi, 

We will be able to test it on our new projects. Right now, we are maintaining existing ones with v1 for at least 6 months. I guess v1 will not be supported anymore?

**Comment by caique0202** [comment]
Hi

Has this been fixed? When I just call $$('#smartSelect').val('154') it's not changing the text.

Thanks
Carlos

**Comment by valnub** [comment]
@caique0202 Are you using v1 or v2?

**Comment by caique0202** [comment]
I'm using V2.

I had to use the workaround $('.item-after').text('xyz');

**Comment by nolimits4web** [comment]
Trigger `change` event on smart select so it can understand that something happend and will change value automatically
