### ISSUE TITLE
Issue with Framework 7 Multiple Swipers

### ISSUE THREAD

**Issue by josieboy** [framework7io/framework7#931]
Hello @nolimits4web i am using the 3 SLIDES PER VIEW, 10PX BETWEEN as demostrated on http://framework7.io/docs/swiper.html .

Once the page loads up i get this 
![dis1](https://cloud.githubusercontent.com/assets/18010020/14410385/3c95cd76-ff26-11e5-8683-15e35b36157e.png) and it doesn't slide .

When i resize the browser i get this 
![dis2](https://cloud.githubusercontent.com/assets/18010020/14410397/6955618c-ff26-11e5-85fc-9912ae53768d.png) and it works ..

How can i make this work without resizing 

Here is my HTML
```html
<div class="content-block-title">2 Slides Per View, 20px Between</div>
 <div class="swiper-container swiper-3">
   <div class="swiper-pagination"></div>
   <div class="swiper-wrapper">
     <div class="swiper-slide"><span>Slide 1</span></div>
     <div class="swiper-slide"><span>Slide 2</span></div>
     <div class="swiper-slide"><span>Slide 2</span></div>
     <div class="swiper-slide"><span>Slide 10</span></div>
   </div>
 </div>
```
Here is my JavaScript
```javascript
  var mySwiper3 = MyApp.fw7.app.swiper('.swiper-3', {
    pagination:'.swiper-3 .swiper-pagination',
    spaceBetween: 10,
    slidesPerView: 3,
    paginationHide: false,
  paginationClickable: true
  });
```

**Comment by ZanderBrown** [comment]
@josieboy i've updated you issue so that we can actually see you samples. I suggest you make use of the 'Preview' tab in future

Is this still an issue? @nolimits4web is this correct usage?

**Comment by valnub** [comment]
When do you initialize swiper in javascript? You should wait for `DOMContentLoaded`. If you init to early it will look like in your 1st screenshot. When resized, Swiper will recalculate and then it looks fixed.

**Comment by motatoes** [comment]
I'm currently facing the same issue! This is because I'm initially hiding the slider and then showing it according to some condition. Is there anyway to update the slider manually after showing it ?

**Comment by valnub** [comment]
Try to trigger a resize event manually

`$(window).trigger('resize');`

**Comment by motatoes** [comment]
I was able to solve my issue by setting `observer: true` in the swiper settings. This is based on [this issue](https://github.com/nolimits4web/Swiper/issues/1611#issuecomment-184740575) related to dynamic content that is fetched via ajax and then appended to the swiper. I don't think it is related to the OP's issue,  but the appearance of the swiper is similar to that descriped in the original issue.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
