### ISSUE TITLE
Feature request - Remove options from smartselect

### ISSUE THREAD

**Issue by jarodium** [framework7io/framework7#938]
Hello 

This is a followup from issue #765

I would like to propose a 'remove an option' method from a smartselect ( with or without virtual list )

Currently i am hacking away with the following code

``` js
$$('#mysmartselectid')[0].options.remove(INDEX)
```

This works, and the smartselect component does it's job updating the select's popup.

However I have noticed that the selected value does not update after I issue the command in the console, so I think it should have a function to remove options, in which a developer should opt from the following behaviors upon deleting:
1. Select the next item in the list ( if there are no more items next then it should select the previous element.
2. No selection. Clears the component and it's input.

Another feature request that would be great would be*\* clearAll*\* options from the smartselect component, so that we can update the list again without any problems.

This would be great because triggering 'myApp.initSmartSelects('#' + page);' does not seem right. I have checked the source code and I have the ability to choose an individual select but, at this time I have not tried it since deleting an option triggers the update in the select's popup.

**Comment by ZanderBrown** [comment]
@nolimits4web , @valnub what do you think?

**Comment by nolimits4web** [comment]
From my point of view such logic must be done at developer side, and it is pretty clear what to do:
- delete required options (Dom7's .remove() method or anything is simpler) do its job well
- select required option after removal
- trigger `change` method on select to auto update its value

Anyway, smart select was highly reworked in v2. Closing for now
