### ISSUE TITLE
Google Place Autocomplete API

### ISSUE THREAD

**Issue by CarlosJimenez** [framework7io/framework7#95]
Hi
I have troubles trying to use Google Place Autocomplete API inside a form. One of the field of the form is a input type="text", that should be autocompleted.
It worked in bootstrap, but when I tried to do the same in F7 I found that input is not autocompleted.
## on the form I added

```
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
```

---
## In the form my field is

```
      <li>
        <div class="item-content">
          <div class="item-media"><i class="icon icon-form-place"></i></div>
          <div class="item-inner">
            <div class="item-title label">Lugar</div>
            <div class="item-input">
              <input id="myplace" type="text" />
            </div>
          </div>
        </div>
      </li>
```

---
## on the javascript

$$(document).on('pageInit', function (e) {
    var page = e.detail.page;
    // other pages initialization
    if (page.name === 'myform') {
        function placeChanged() {
           console.log('placeChanged');
        }
        var input = $$('#myplace')[0];
        var autocomplete = new google.maps.places.Autocomplete(input);
        google.maps.event.addListener(autocomplete, 'place_changed', placeChanged);
    }
## });

First (I don't know why) my input included autocomplete="off"  (google added)
I am receiving the autocomplete info, but it's not filled in the input box.

PD: I include some of your form icons in svg in case that you want to include in Framework 7

i.icon.icon-form-name2 {
  width: 29px;
  height: 29px;
  background-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 58 58'><rect fill='%238e8e93' width='58' height='58' rx='10' ry='10'/><path fill='%23fff' d='M6 41v-3l8-4v-2s-1-2-1-3c-1-3-2-7 1-9 1-1 2-2 4-2s3 1 4 2c3 2 3 6 2 9-1 1-2 3-3 3v2l10 4v3h-25zM36 37h17.5v2h-17.5zM32 28h21v2h-21zM29 19h24.5v2h-24.5z'/></svg>");
}

i.icon.icon-form-email2 {
  width: 29px;
  height: 29px;
  background-image: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 58 58"><rect fill="%238e8e93" width="58" height="58" rx="10" ry="10"/><path fill="%23fff" d="M32 36c-1 0-2 1-3 2h-6c0-1-1-2-2-3s-1-3-1-4c0-2 1-4 2-6s2-3 3-4c2-1 3-1 4-1h3c1 1 2 2 2 3l1-3h3l-2 12c-1 1-1 2-1 2v1l1 1 3-1 3-4c1-2 1-3 1-5s0-4-1-5c-1-2-3-3-5-4s-4-2-6-2c-3 0-6 1-8 2s-4 3-5 5c-1 3-2 5-2 8s1 5 2 7 3 4 5 5c3 1 5 1 8 1s6 0 8-1 3-2 4-4h3c0 1-1 3-3 4-1 1-3 2-5 3s-4 1-7 1c-2 0-5 0-7-1l-6-3c-1-1-2-3-3-5s-1-4-1-7c0-2 0-5 1-8 2-3 4-5 6-7 3-2 6-2 10-2 3 0 5 0 7 1 3 2 5 3 6 6 1 2 2 4 2 6 0 3-2 6-4 9-2 2-4 4-7 4l-2-1s-1 0-1-1v-1zm-9-5c0 2 1 3 2 4 0 1 1 1 2 1s1 0 2-1c1 0 2-1 2-1l2-3v-4c0-1 0-3-1-3-1-1-1-2-3-2 0 0-1 0-2 1l-2 2s-1 1-1 3l-1 3z"/></svg>');
}

i.icon.icon-form-tel2 {
  width: 29px;
  height: 29px;
  background-image: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 58 58"><rect fill="%238e8e93" width="58" height="58" rx="10" ry="10"/><path fill="%23fff" d="M10 17c0 8 7 16 12 21 6 5 13 9 21 8l5-6c1-1 1-2 0-3l-7-4c-1 0-2 0-3 1l-3 3c-7-5-10-7-15-13l3-3c1-1 1-2 0-3l-5-7c-1-1-2-1-3 0l-5 6z"/></svg>');
}

i.icon.icon-form-calendar2 {
  width: 29px;
  height: 29px;
  background-image: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 58 58"><rect fill="%238e8e93" width="58" height="58" rx="10" ry="10"/><path fill="%23fff" d="M29 46h-14v-2c0-1 1-2 2-3l4-4 3-2 2-2s0-1 1-1v-2c0-1 0-2-1-3l-1-1c-1-1-2-1-3-1-3 0-4 2-5 5h-2c0-2 1-4 2-5 2-1 3-2 5-2s4 1 5 2 2 3 2 5c0 1 0 2-1 3 0 1-1 2-2 2l-4 4c-3 2-4 3-5 5h12v2zM42 46h-2v-19c-2 2-4 3-6 4v-2c4-2 6-4 7-6h1v23zM27 17h-1v-9l-3 9h-1l-3-9v9h-1v-10h1l3 8 4-8h1zM35 13c0 1 0 2-1 3 0 1-1 1-2 1h-1l-1-1c-1 0-1-1-1-1v-4l1-1 2-1c1 0 2 1 2 1 1 1 1 2 1 3zm-1 0v-1c0-1-1-1-1-1 0-1-1-1-1-1-1 0-1 0-2 1v4c1 1 1 1 2 1h1l1-1v-2zM42 17h-1v-6c0-1-1-1-1-1h-1s0 1-1 1v6h-1v-7h1v1c0-1 1-2 2-2s2 1 2 3v5z"/></svg>');
}

i.icon.icon-form-place {
  width: 29px;
  height: 29px;
  background-image: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 58 58"><rect fill="%238e8e93" width="58" height="58" rx="10" ry="10"/><path fill="%23fff" d="M10 31c1-2 3-3 5-4s4-2 6-1l6-13c-4-2-1-9 3-7l17 8c4 2 1 9-3 7l-7 13c2 1 3 2 4 5 0 2 0 4-1 6 0 1-1 2-2 1l-11-5-8 12c0 1-2 0-1-1l4-13-11-5c-1-1-1-2-1-3zm15-4c0 1 1 2 2 1l5-12c1-1-1-2-1 0l-6 11z"/></svg>');
}

**Comment by Isainsosa** [comment]
Hi,

I tried this solution but it does not fire the place_changed event, it makes up touching elsewhere on the screen. Can you help please?

**Comment by ganeshlore** [comment]
hi Vladimir,
i tried your solution but still not work for me. no drop down show when i build the app but its work on web browser.

<h3>CSS :</h3>
```
.pac-container {
  z-index:20000;
}

```
<h3>Google MAP JS :</h3>
```
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
```

 
<h3>HTML :</h3>
       <div class="item-content">
         <div class="item-inner">
             <div class="item-input">
                 <input type="text" placeholder="Select Your Location" id="rlocation" name="rlocation"> 
              </div>
          </div>
      </div>



<h3>JS :</h3>
```javascript
/*
this js inside -> $$(document).on('pageInit', function (e) {
*/
var rinput = document.getElementById('rlocation') ;  
	
    var rautocomplete = new google.maps.places.Autocomplete(rinput, {
        types: ["geocode"]
    });
    
	google.maps.event.addListener(rautocomplete, 'place_changed', function() {
        var place = rautocomplete.getPlace();
        if (!place.geometry) {
            return;
        }
		

        var raddress = '';
        if (place.address_components) {
            raddress = [
                (place.address_components[0] && place.address_components[0].short_name || ''),
                (place.address_components[1] && place.address_components[1].short_name || ''),
                (place.address_components[2] && place.address_components[2].short_name || '')
            ].join(' ');
			 
			 var lat = place.geometry.location.lat();
             var lng = place.geometry.location.lng();  
			
			$("#rlocation[name=rlocation]").attr('latlng', lat+','+lng);
			console.log('latlong : '+lat+','+lng);
			
		}
		
	});
```

**Comment by ganeshlore** [comment]
hi CarlosJimenez,
Can You Share Your Working Code Sample Here
Thank You

**Comment by ganeshlore** [comment]
hi Guys
its Work Fine i Just Miss the Whit list the Domain in Config,xml file

```
<access origin="*"/>
    <!-- Added the following intents to support the removal of whitelist code from base cordova to a plugin -->
    <!-- Whitelist configuration. Refer to https://cordova.apache.org/docs/en/edge/guide_appdev_whitelist_index.md.html -->
    <plugin name="cordova-plugin-whitelist" version="1" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
``` 

:-)

**Comment by nive745** [comment]
Hi,
I am having issue while implementing google autocomplete. it works fine in browser but when i run app in mobile suggestion are coming but selection is not working. i am using framework7 with cordova. I tried all solution describe above but not work for me.

HTML code

<div class="inputs-list mg0 location_div">
   <div class="location">
      <i class="fa fa-map-marker location-img"></i>
      <div class="item-input">
         <input type="text" id="autocomplete" placeholder="Enter your address" onfocus="geolocate();">
      </div>
   </div>
</div>


JQUERY

function initAutocomplete() {

        // Create the autocomplete object, restricting the search to geographical
        // location types.

        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});
        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        
        autocomplete.addListener('place_changed', fillInAddress);
      }

function fillInAddress() {
        alert("here")
      }
// Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {

          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });

            autocomplete.setBounds(circle.getBounds());
          });
        }
}

**Comment by nive745** [comment]
Please give me reply

**Comment by ganeshlore** [comment]
send me your full page code
i need to understand if u call autocomplete before HTMLInputElement Appear
  or  not


////////////////////////////////////////////// please Check Below things
/////////////////////////////////////////////////////

CASE : 1

autocomplete = new google.maps.places.Autocomplete(
        /** @type {!HTMLInputElement}
*/(document.getElementById('autocomplete')),
        {types: ['geocode']});


it's write code by the way


if u get this error : InvalidValueError: not an instance of HTMLInputElement

means your auto complete happen before ur input element appears


//////////////////////////////////////////////////////////////////////


CASE : 2

      in your  Config.xml  just  put
<access origin="*"/>


<plugin name="cordova-plugin-whitelist" version="1" />
<allow-intent href="http://*/*" />
<allow-intent href="https://*/*" />
<allow-intent href="tel:*" />
<allow-intent href="sms:*" />
<allow-intent href="mailto:*" />
<allow-intent href="geo:*" />
<platform name="android">
<allow-intent href="market:*" />
</platform>
<platform name="ios">
<allow-intent href="itms:*" />
<allow-intent href="itms-apps:*" />
</platform> //////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////




On Tue, Mar 8, 2016 at 3:24 PM, nive745 <notifications@github.com> wrote:

> Please give me reply
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolimits4web/Framework7/issues/95#issuecomment-193694399>
> .
>



-- 
--
*G*anesh *L*ore

**Comment by nive745** [comment]
Hi Ganeshlore,

First of all thanks for the reply.
You can check below link for html code.
http://dev.eoniansoftware.com/letshavegame_demo/www/demolink.html

when you type in location search box you can see autocomplete results appear. when i click on any places it fill up into text box for browser but its not working in mobile app.

config.xml
`
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.eonian.letshavegame" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>PlayEcology</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <access origin="*"/>
	<icon src="icon.png" />
    <content src="listing.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
	
    <platform name="android">
        <allow-intent href="market:*" />
    	 
      </platform>

    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>

 

</widget>

`

**Comment by ganeshlore** [comment]
fastClicks:false

On Tue, Mar 8, 2016 at 5:00 PM, nive745 <notifications@github.com> wrote:

> Hi Ganeshlore,
>
> First of all thanks for the reply.
> You can check below link for html code.
> http://dev.eoniansoftware.com/letshavegame_demo/www/demolink.html
>
> when you type in location search box you can see autocomplete results
> appear. when i click on any places it fill up into text box for browser but
> its not working in mobile app.
>
> config.xml
> `
> <?xml version='1.0' encoding='utf-8'?>
>
> PlayEcology
>
> A sample Apache Cordova application that responds to the deviceready event.
>
>
> Apache Cordova Team
>
>
>
>
>
>
>
>
>
>
>
> <platform name="android">
>     <allow-intent href="market:*" />
>      
>
> <platform name="ios">
>     <allow-intent href="itms:*" />
>     <allow-intent href="itms-apps:*" />
> </platform>
>
> `
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolimits4web/Framework7/issues/95#issuecomment-193738790>
> .
>



-- 
--
*G*anesh *L*ore

**Comment by nive745** [comment]
Hi Ganeshlore,

Yeah, it's working great. Thank you very much for this help. It helped me a lot.

You/'ve saved me from wasting lots of hours on this simple task.

Once again thanks for the help. I really appreciate your support.

**Comment by ganeshlore** [comment]
Happy Coding.....🙂

**Comment by yankopetrov** [comment]
In my case `fastClicks:false` was not an option. 

I tried also 
```$$('body').on('touchend','.pac-container', function(e){e.stopImmediatePropagation();})```
but when the event was triggered the box was already hidden.

So changing `touchend` with `touchstart` solve my problem.
```$$('body').on('touchstart','.pac-container', function(e){e.stopImmediatePropagation();})```

Now google autocomplete works fine for me.

**Comment by shirishpickup** [comment]
Even i'm banging my head on this issue. I can able to select the item on the mobile, but place_changed event is not trigged and the keyboard is still showing. Please help!!

**Comment by SnehaSSD** [comment]
@shirishpickup did you get any solution for this problem ?

**Comment by shirishpickup** [comment]
@SnehaSSD Yes i did. Which version of Angular, are you using Sneha ?

**Comment by bhupeshp** [comment]
Hi guys, I followed the above steps and still faced the same issue. Below (way 2) resolved my issue though:

way 1:Remove entire fastclick from app var myApp = new Framework7({ material: true, materialPageLoadDelay: 250, materialRipple: true, fastclick:false, }); 

way 2:remove fastclick only for goole suggestion area$(document).on({ 'DOMNodeInserted': function() { $('.pac-item, .pac-item span', this).addClass('no-fastclick'); } }, '.pac-container'); I prefer the second one where fastclick is removed from only suggestion area.

original answer: https://tutel.me/c/programming/questions/38367768/google+autocomplete+not+working+in+framework7

**Comment by Srijan1702** [comment]
@shirishpickup Hi, I am also facing the same issue. I am not able to select suggestions shown by google api on iOS only. It's working fine on android and browser. I am using Angular 4 Ionic 3 and have Xcode 9. I have tried almost everything still no luck. Please help!!!

**Comment by shirishpickup** [comment]
Hey Srijan,

You need to do, skip click hijack

Try this.
.config(function( $mdGestureProvider ) {
          $mdGestureProvider.skipClickHijack();
      });

**Comment by Srijan1702** [comment]
Hi Shirish( @shirishpickup ) 

I am not sure where to put the code as I am new in the technology.
I have tried but it's not working, here's my code. Thank you in advance. 

in Html:

      `<input id="pac-input" name="address" type="text" (keyup)="onKeyup()" [(ngModel)]="address" placeholder="Your street, building number..." class="name_txt" (click)="selectedSavedAddress = false" required />`
in ts:

```
ionViewDidEnter() {
    let input = document.getElementById('pac-input');
    let options = {
      types: ['geocode'], 
      componentRestrictions: {country: "SG"}
    };

    var autocomplete = new google.maps.places.Autocomplete(input, options);
     console.log(autocomplete, 'autocomplete');

    var local_this = this;
    google.maps.event.addListener(autocomplete, 'place_changed', () => {
      var place = autocomplete.getPlace();
      var address = place.formatted_address;
      var postal_code_find = _.find(place.address_components, (ac: any) => {
        return ac.types[0] === 'postal_code';
      });
      var postal_code = '';

      postal_code_find && (postal_code = postal_code_find.short_name);

      var latitude = place.geometry.location.lat();
      var longitude = place.geometry.location.lng();

      let coord = {
        lat: latitude, 
        lng: longitude
      };

      let address_data = {
        address: address,
        postal_code: postal_code || ''
      };

      local_this.extractAddressData(address_data);
      local_this.ref.detectChanges();
    });
}

onKeyup() {
    console.log('keyup');
    angular.module('**whichModuleToPutHere**', ['ngMaterial'])
    .config(function( $mdGestureProvider ) {
      console.log('mdGestureProvider');
      
      $mdGestureProvider.skipClickHijack();
  });

  }
```

**Comment by shirishpickup** [comment]
App.config(function($mdGestureProvider) {
    $mdGestureProvider.skipClickHijack();
});

Add this to your app.js file where you define the module.
