### ISSUE TITLE
virtuallist doesn't render new items after using deleteAllItems()

### ISSUE THREAD

**Issue by drustthecoder** [framework7io/framework7#953]
Hi
I'm having trouble with virtual list. when I use `deleteAllItems()` on my virtual list it clears all items, but after appending new items via `appendItem()` I can see that new items are added to virtual list `items` property (they exist in `items` property of my virtual list) but they are not rendered and now shown in the list. also `onItemBeforeInsert()` doesn't fire up anymore when appending items after using `deleteAllItems()`.
This problem also happens if you delete all items of virtual list using `deleteItem()` and delete them one by one.
What is interesting is that if you leave at least one item in the virtual list and don't clear it completely appending new items and everything else works just fine.

**Steps to reproduce:**
1. Create a virtual list.
2. Append items to it.
3. Delete all items.
4. Append new items.

**Expected results:**
New items should be rendered and shown.

**Actual result:**
New items are added to "items" property of virtual list and yet not rendered and shown.

**Additional info:**
I'm using virtual list with dynamic height function and template property for rendering items.

If there is any more information needed I'll be glad to provide it.

**Comment by nolimits4web** [comment]
Is this issue still actual as i can not replicate it? Works fine for me

**Comment by SimplyLab** [comment]
I have the same problem.

It delete only the first item of the list. Using deleteItem don't update display. Using update work only one.

Quite problematic

**Comment by ZanderBrown** [comment]
Could you provide some details and a codepen / jsfiddle please?

**Comment by SimplyLab** [comment]
After some code reading and console.log usage, i think I understand what is happening in my case.

I create a Virtual List and I use the callback "renderItem"

`renderItem: function (index, item) {`

On my template for items, I inject the "index" value on a "onclick" action of an html element.

So, the deleteItem function in Framework7.js is called with index = 2 (i just pass index value without manipulate it).

Look at the  console.log(index); I put near the "splice" function .

The console output "20" !! So splice is called with splice(20,1). 

The 20 is "built" by  `index = index + indexShift;` line. It does 2 + 0 = 20 as text.

To have the good behaviour, I have to call deleteItem with a parseInt(index) parameter.

I don't understand why the index value that was given by the `renderItem: function (index, item) {` callback must be "parseInt"ed 

I spent 2 hours understanding what happened. But now it works

       ```
     // Delete
            vl.deleteItems = function (indexes) {
                var prevIndex, indexShift = 0;
                for (var i = 0; i < indexes.length; i++) {
                    var index = indexes[i];
                    if (typeof prevIndex !== 'undefined') {
                        if (index > prevIndex) {
                            indexShift = -i;
                        }
                    }
                    index = index + indexShift;
                    prevIndex = indexes[i];

                    // Delete item
                    console.log(index);
                    var deletedItem = vl.items.splice(index, 1)[0];
        
                    // Delete from filtered
                    if (vl.filteredItems && vl.filteredItems.indexOf(deletedItem) >= 0) {
                        vl.filteredItems.splice(vl.filteredItems.indexOf(deletedItem), 1);
                    }
                    // Update cache
                    if (vl.params.cache) {
                        var newCache = {};
                        for (var cached in vl.domCache) {
                            var cachedIndex = parseInt(cached, 10);
                            if (cachedIndex === index) {
                                delete vl.domCache[index];
                            }
                            else if (parseInt(cached, 10) > index) {
                                newCache[cachedIndex - 1] = vl.domCache[cached];
                            }
                            else {
                                newCache[cachedIndex] = vl.domCache[cached];   
                            }
                        }
                        vl.domCache = newCache;
                    }
                }
                vl.update();
            };
```

**Comment by ZanderBrown** [comment]
If you've got a fix please open a PR 😄

**Comment by SimplyLab** [comment]
In fact I just "feed" the deleteItem public function using parseInt(index) et not index. And all is working perfect now.

If I have time I will try to understand why the renderItem callback give me a non Integer index. I think it would better to fix on this side rather than parseInt at the end.

I will update

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
