### ISSUE TITLE
Ajax callbacks silently fail when an undefined identifier was used 

### ISSUE THREAD

**Issue by mitya** [framework7io/framework7#955]
It seems that F7 ajax helpers generate an `ajaxError` event in case of any errors, including calls to undefined functions / usage of undefined variables (which typically happens because of a typo). jQuery ajax methods produce a nice error message with a stack trace in the console.

Am I doing something wrong, or is it by design? Looks like a really important feature to me.

This fails with a nice error in the Chrome/Safari/FF console:

```
jQuery.getJSON("/valid-endpoint.json", function() { thatMethodDoesNotExist() })
```

This silently fails and triggers the global `ajaxError` callback:

```
Dom7.getJSON("/valid-endpoint.json", function() { thatMethodDoesNotExist() })
```

<img width="507" alt="screen shot 2016-05-02 at 03 04 51" src="https://cloud.githubusercontent.com/assets/19074/14945189/2033210c-1014-11e6-8515-ca936c80a5df.png">

**Comment by nolimits4web** [comment]
AS I see, it happens because with `json` request "success" callback wrapped with `try/catch` statement. Will see how to fix this

**Comment by nolimits4web** [comment]
This must be already fixed in v2
