### ISSUE TITLE
Need a standard method to cancel ajax-form submission

### ISSUE THREAD

**Issue by ww-fy-sun** [framework7io/framework7#958]
Currently the method to cancel Ajax forms submission is to call xhr.abort() in the 'beforeSubmit' event, as suggested by ["this post".](http://forum.framework7.io/#!/getting-started:cancel-ajax-form-submission) But that leads to an Uncaught InvalidStateError at the code line "xhr.send(postData);" (Failed to execute ‘send’ on xhr, for the object's state is no more OPENED). 

On the orther hand, jQuery has a norm method for this: just let the callback at the ‘beforeSubmit’ event return false to prevent erroneous data from actually sending it to the server. That design may be needed for the next releases of Framework7.

**Comment by ZanderBrown** [comment]
This could be good the have

**Comment by DareDevil73** [comment]
I need it too!

**Comment by J05HI** [comment]
Would be great :)

**Comment by J05HI** [comment]
Great! ☺

**Comment by php-ini** [comment]
How to cancel the previous xhr requests and keep the last one only ?
