### ISSUE TITLE
1.4.2 Bug: Disabling cache does not work when template7Pages are enabled.

### ISSUE THREAD

**Issue by ionas** [framework7io/framework7#984]
### A This did not work

``` javascript
var myApp = new Framework7({
  // ...
  template7Pages: true,
  cache: false,
  cacheIgnore: ['/users/index', '/users/add', 'users/index', 'users/add'],
  // ...
```
### B This however did work ('solves' the problem)

``` javascript
var myApp = new Framework7({
  template7Pages: false, // Why does this interact with caching?
  // ...
)}
myApp.params.cache = true; // could also be false to disable any caching
myApp.params.cacheIgnore = ['/users/index', '/users/add', 'users/index', 'users/add'];
```

_**Shouldn't A and B have the same effect?**_

.
###### Additional code required for back link to force reloads

``` javascript
myApp.onPageAfterAnimation('*', function(page){
  $$('.view-main .page-on-left, .view-main .navbar-on-left').remove();
});
```

**Comment by ionas** [comment]
From the docs:
> Let's look at the list of all available parameters:
> ...
> cache 	boolean 	true
Ref: http://framework7.io/docs/init-app.html

**Comment by ionas** [comment]
I did add ` data-ignore-cache="true"` to my links and suddenly cache wasn't and issue. So I was thinking about the cache again and took a look at framework7.js source code looking for "cacheIgnore" (Line 31) and then seeing its a param.

I then decided to set it directly as seen above.
**Any reason for one working but not the other?**

**Comment by ionas** [comment]
Further evaluation shows for me that it is much more related to `template7Pages: true` in conjunction with cache settings. When `template7Pages` is set to true, `cache: false` will make navigating around ignore cache but `cacheIgnore: ['/users/index', '/users/add', 'users/index', 'users/add'],` wont

**Comment by ionas** [comment]
@nolimits4web may I simple make a PR to the documentation stating:
"template7Pages: true will force enable cache (on regular HTML pages) and thus make make cache: false do nothing?"

**Comment by nolimits4web** [comment]
@ionas it is the issue with F7, not with docs :) I'll check and fix it

**Comment by scriptPilot** [comment]
Any update to this bug fix?

**Comment by AysadKozanoglu** [comment]
The simplest way is to define a variable _timestamp_ and set it with _Date.now()_ and give it to route path parameter with _?timestamp_ on every route path ending. 

So in this case framework7 must load every html file on every browser reload again.

after your development and design is finished you can comment it out. This scenario you can use for every framework you use. it is not framework7 specific. 

for examle:

`var timestamp   = Date.now();

routes = [
  {
    path: '/',
    url: './index.html?'+timestamp,
  },
  {
    path: '/about/',
    url: './pages/about.html?'+timestamp,
  },
  {
    path: '/form/',
    url: './pages/form.html?'+timestamp,
  },
  {
    path: '/page-loader-template7/:user/:userId/:posts/:postId/?'+timestamp,
    templateUrl: './pages/page-loader-template7.html',
  },
  {
    path: '/page-loader-component/:user/:userId/:posts/:postId/?'+timestamp,
    componentUrl: './pages/page-loader-component.html',
  }]`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
